bundles/org.openhab.core.karaf/ESH-INF/config/config.xml, bundles/org.openhab.core.karaf/OSGI-INF/featureinstaller.xml, bundles/org.openhab.core.karaf/build.properties, bundles/org.openhab.core.karaf/src/main/java/org/openhab/core/karaf/internal/FeatureInstaller.java, features/karaf/src/main/feature/feature.xml
=> added possibility to select an installation package

bundles/org.openhab.core.karaf/src/main/java/org/openhab/core/karaf/internal/FeatureInstaller.java
=> only install feature if name is not blank

features/karaf/src/main/feature/feature.xml, features/verify-karaf/pom.xml, pom.xml
In preparation of https://github.com/openhab/openhab-distro/issues/11
Signed-off-by: Davy Vanherbergen <davy.vanherbergen@gmail.com>
=> Update to new ESH feature

bundles/org.openhab.core.karaf/src/main/java/org/openhab/core/karaf/internal/FeatureInstaller.java
=> only install features if they are not already installed

bundles/org.openhab.ui.paperui/patch/web/js/constants.js
=> hiding groups in Paper UI

features/karaf/src/main/feature/feature.xml
=> renamed certificate feature

features/karaf/src/main/feature/feature.xml
This resolves https://github.com/openhab/openhab-distro/issues/28
Signed-off-by: Davy Vanherbergen <davy.vanherbergen@gmail.com>
=> Add certificate generation to base runtime 

pom.xml, poms/tycho/pom.xml
Signed-off-by: Davy Vanherbergen <davy.vanherbergen@gmail.com>
=> Update to new p2 repository

poms/tycho/pom.xml
Signed-off-by: Davy Vanherbergen <davy.vanherbergen@gmail.com>
=> Update openhab-deps-repo url to new location

features/karaf/src/main/feature/feature.xml, pom.xml
=> upgraded jupnp to 2.1.0.RC1

bundles/org.openhab.core.compat1x/src/main/java/org/openhab/core/binding/internal/BindingConfigReaderDelegate.java
=> added location item support in config reader delegate

bundles/org.openhab.ui.iconset.classic/icons/office.svg
Signed-off-by: Markus Reiter <me@reitermark.us>
=> Fix office icon.

pom.xml
=> updated jupnp to 2.2.0

bundles/org.openhab.core.karaf/pom.xml, features/karaf/src/main/feature/feature.xml, features/verify-karaf/pom.xml, pom.xml
Related to: openhab/openhab-distro#172
=> changes for Xtext 2.9.2 usage (ESH / OH)

bundles/org.openhab.core.karaf/src/main/java/org/openhab/core/karaf/internal/FeatureInstaller.java
=> improved robustness of feature/package installer

bundles/org.openhab.core.karaf/src/main/java/org/openhab/core/karaf/internal/FeatureInstaller.java
=> fixes https://github.com/openhab/openhab-distro/issues/176

features/karaf/src/main/feature/feature.xml, features/verify-karaf/pom.xml
Related to eclipse/smarthome#1396
=> use ESH Karaf target platform

bundles/org.openhab.core.karaf/META-INF/MANIFEST.MF, bundles/org.openhab.core.karaf/src/main/java/org/openhab/core/karaf/internal/FeatureInstaller.java
=> added esh repos for online mode

bundles/org.openhab.core.karaf/src/main/java/org/openhab/core/karaf/internal/FeatureInstaller.java, bundles/org.openhab.core.karaf/src/main/java/org/openhab/core/karaf/internal/KarafExtensionService.java
=> hrenamed tts addons to voice

features/openhab-esh-addons/src/main/feature/feature.xml, features/verify-karaf/pom.xml
=> added mactts feature and added esh-addons to verification

targetplatform/openhab.target
=> sync'ed target with the one in the distro

bundles/org.openhab.core.compat1x/src/main/java/org/openhab/core/items/internal/ItemUIRegistryDelegate.java
=> adapt to ESH changes of ItemRegistry

bundles/org.openhab.core.compat1x/src/main/java/org/openhab/core/persistence/internal/PersistenceServiceDelegate.java, bundles/org.openhab.core.compat1x/src/main/java/org/openhab/core/persistence/internal/QueryablePersistenceServiceDelegate.java
Linked to https://github.com/eclipse/smarthome/pull/1872
=> Add new persistence method

features/openhab-core/src/main/feature/feature.xml
=> added java sound to the base feature

bundles/org.openhab.core.compat1x/OSGI-INF/audioaction.xml, bundles/org.openhab.core.compat1x/src/main/java/org/openhab/io/multimedia/actions/AudioActionService.java
=> changed audio action to implement ESH interface

features/openhab-core/src/main/feature/feature.xml
Reverts kaikreuzer/openhab-core#57
=> Revert "added java sound to the base feature"

features/openhab-core/src/main/feature/feature.xml
=> added rest-mdns feature to the base package

features/openhab-core/src/main/feature/feature.xml
=> added missing feature dependency

bundles/org.openhab.io.sound/src/main/java/org/openhab/io/sound/internal/EnhancedJavaSoundAudioSink.java
=> fixed playback issue due to stream being closed too early

features/openhab-core/src/main/feature/feature.xml
=> added rest-voice feature

bundles/org.openhab.core.compat1x/src/main/java/org/openhab/io/console/ConsoleInterpreter.java
=> re-added ConsoleInterpreter for openHAB 1 build

bundles/org.openhab.core.compat1x/src/main/java/org/openhab/library/tel/types/ESHCallType.java
=> added toFullString() method

features/openhab-core/src/main/feature/feature.xml
=> added web audio feature

features/openhab-core/src/main/feature/feature.xml, features/openhab-esh-addons/src/main/feature/feature.xml
=> added configuration to features

bundles/org.openhab.core/src/main/java/org/openhab/core/internal/item/DefaultSitemapProvider.java
=> adapted code to ESH API change

bundles/org.openhab.io.sound/src/main/java/org/openhab/io/sound/internal/EnhancedJavaSoundAudioSink.java
=> changed label to be not identical to the one of the host bundle

features/openhab-esh-addons/src/main/feature/feature.xml
Fixes https://github.com/openhab/openhab-distro/issues/332
=> corrected sonos service id

features/openhab-core-resources/src/main/resources/addons-expert.cfg
=> added all transformation services to expert package

features/openhab-core/src/main/feature/feature.xml
=> don't overwrite cfg once it exists

features/openhab-core/src/main/feature/feature.xml
=> replaced mapdb by json database

features/openhab-core/src/main/feature/feature.xml
=> added multimedia actions to new rule engine

features/openhab-esh-addons/src/main/feature/feature.xml
fixes https://github.com/openhab/openhab-distro/issues/333
=> changed start level of transformation services

bundles/org.openhab.ui.dashboard/templates/setup.html
=> improved wording

pom.xml
Signed-off-by: Christian Häussler <c-n-i@web.de> (github: @cniweb)
=> Correct openhab-core URLs

bundles/org.openhab.ui.paperui/patch/web/js/constants.js
fixes https://github.com/openhab/openhab-distro/issues/352
Signed-off-by: Aoun Bukhari <bukhari@itemis.de>
=> Custom label for extensions menu entry

bundles/org.openhab.core.karaf/src/main/java/org/openhab/core/karaf/internal/KarafExtensionService.java
=> adapted to changed ESH API and added links to binding documentation

bundles/org.openhab.ui.paperui/patch/web/js/constants.js
Signed-off-by: Aoun Bukhari <bukhari@itemis.de>
=> Use custom label from module config

bundles/org.openhab.core.karaf/OSGI-INF/featureinstaller.xml, bundles/org.openhab.core.karaf/src/main/java/org/openhab/core/karaf/internal/FeatureInstaller.java, bundles/org.openhab.ui.dashboard/src/main/java/org/openhab/ui/dashboard/internal/DashboardServlet.java, pom.xml
- switched to Karaf 4.0.8
- used bulk feature installation
- synchronised methods to avoid concurrent operations
- fixed issue where dashboard bundle might bind the addons configuration
=> Feature installation improvements

bundles/org.openhab.core.karaf/src/main/java/org/openhab/core/karaf/internal/FeatureInstaller.java
=> only send installed events for new addons

bundles/org.openhab.io.rest.docs/src/main/java/org/openhab/io/rest/docs/internal/RESTDashboardTile.java, bundles/org.openhab.ui.basicui/src/main/java/org/openhab/ui/basicui/internal/BasicUIDashboardTile.java, bundles/org.openhab.ui.classicui/src/main/java/org/openhab/ui/classicui/internal/ClassicUIDashboardTile.java, bundles/org.openhab.ui.dashboard/src/main/java/org/openhab/ui/dashboard/internal/DashboardServlet.java, bundles/org.openhab.ui.dashboard/templates/entry.html, bundles/org.openhab.ui.dashboard/web/main.css, bundles/org.openhab.ui.paperui/src/main/java/org/openhab/ui/paperui/internal/PaperUIDashboardTile.java
Signed-off-by: Vlad Ivanov <vlad@ivanov.email>
=> Dashboard: remove html5 icon, remove z-index for overlay

bundles/org.openhab.io.sound/src/main/java/org/openhab/io/sound/internal/EnhancedJavaSoundAudioSink.java
It wasn't possible to interrupt url streams (e.g. Internet radio) anymore, once a normal (not url) audio file was played.
=> fixed dangling audio streams if files are played in between

bundles/org.openhab.core.karaf/src/main/java/org/openhab/core/karaf/internal/KarafExtensionService.java
=> added further links to documentation pages

features/openhab-core/src/main/feature/feature.xml, pom.xml
=> added jetty-proxy

bundles/org.openhab.core.compat1x.test/META-INF/MANIFEST.MF, bundles/org.openhab.core.compat1x/META-INF/MANIFEST.MF, bundles/org.openhab.core.karaf/META-INF/MANIFEST.MF, bundles/org.openhab.core/META-INF/MANIFEST.MF, bundles/org.openhab.io.jetty.certificate/META-INF/MANIFEST.MF, bundles/org.openhab.io.rest.docs/META-INF/MANIFEST.MF, bundles/org.openhab.io.sound/META-INF/MANIFEST.MF, bundles/org.openhab.ui.basicui/META-INF/MANIFEST.MF, bundles/org.openhab.ui.classicui/META-INF/MANIFEST.MF, bundles/org.openhab.ui.dashboard/META-INF/MANIFEST.MF, bundles/org.openhab.ui.paperui/META-INF/MANIFEST.MF
=> switched to Java8

poms/pom.xml
=> upgraded to deps 1.0.11

poms/pom.xml
=> moved config to the correct place

bundles/org.openhab.core.compat1x/src/main/java/org/openhab/io/net/exec/ExecUtil.java
Signed-off-by: Martin van Wingerden <martinvw@mtin.nl>
=> Corrected spelling error occured => occurred

poms/pom.xml
=> added Jackson version to properties

bundles/org.openhab.core.karaf/src/main/java/org/openhab/core/karaf/internal/KarafExtensionService.java
This depends on https://github.com/eclipse/smarthome/pull/3258
=> implemented new method of ExtensionService interface

features/openhab-core/src/main/feature/feature.xml
=> added jsr223 rule support bundle to rule engine feature

bundles/org.openhab.core/src/main/java/org/openhab/core/OpenHAB.java, bundles/org.openhab.ui.dashboard/src/main/java/org/openhab/ui/dashboard/internal/DashboardServlet.java, bundles/org.openhab.ui.dashboard/templates/index.html, bundles/org.openhab.ui.dashboard/templates/setup.html
Closes https://github.com/openhab/openhab-distro/issues/454
=> add openHAB version and build info to dashboard footer

poms/pom.xml
=> switched to sat version 0.0.6

features/openhab-core/src/main/feature/feature.xml, poms/pom.xml
=> added coap transport feature

features/openhab-core/src/main/feature/feature.xml
=> fixed name of coap transport

features/openhab-core/src/main/feature/feature.xml, poms/pom.xml
=> moved to coap transport feature of ESH

bundles/org.openhab.ui.dashboard/templates/index.html, bundles/org.openhab.ui.dashboard/templates/setup.html, bundles/org.openhab.ui.dashboard/web/js/geolocation.js
=> moved location retrieval from setup to dashboard

poms/pom.xml
=> updated repo version

bundles/org.openhab.io.sound/src/main/java/org/openhab/io/sound/internal/EnhancedJavaSoundAudioSink.java
=> adapt to changed ESH Audio API

features/openhab-core/src/main/feature/feature.xml
=> added commons httpclient to compat feature

poms/pom.xml
=> updated to latest SAT version

poms/tycho/pom.xml
=> Enable JSR305 Null analysis in mvn and build groovy with jdt

poms/tycho/pom.xml
=> Inherit NullAnnotations also in Maven

poms/tycho/pom.xml
=> Sync null analysis error/warnings in IDE and MVN

poms/pom.xml, poms/tycho/pom.xml
=> Use JDT annotations instead of Findbugs JSR305

features/openhab-core/src/main/feature/feature.xml
=> removed dependency on a fixed version of Karaf bundles

features/openhab-core/src/main/feature/feature.xml
=> Moved Jetty client to a separate feature

poms/pom.xml
=> Update dependency repo version

poms/pom.xml
=> upgraded to Jetty 9.3 in targetplatform

bundles/org.openhab.ui.dashboard/META-INF/MANIFEST.MF, bundles/org.openhab.ui.dashboard/build.properties
=> Dashboard: Add DS annotations as optional dependency

poms/pom.xml, poms/tycho/pom.xml
=> Generate DS annotations in maven

.travis.yml
=> added Travis configuration

bundles/org.openhab.io.jetty.certificate/build.properties
Signed-off-by: VelinYordanov <velin.iordanov@gmail.com>
=> Added the lib folder to build.properties.

bundles/org.openhab.core.compat1x/src/main/java/org/openhab/core/binding/internal/BindingConfigReaderDelegate.java
=> also consider Group items for binding configuration delegation

poms/pom.xml, poms/tycho/pom.xml
Similar to https://github.com/eclipse/smarthome/pull/4211 to fix issue https://github.com/eclipse/smarthome/issues/4179.
=> switched to patched ds annotation processor version

bundles/org.openhab.core.compat1x/src/main/java/org/openhab/core/binding/AbstractActiveBinding.java, bundles/org.openhab.core.compat1x/src/main/java/org/openhab/core/binding/AbstractBinding.java, bundles/org.openhab.core.compat1x/src/main/java/org/openhab/core/events/AbstractEventSubscriber.java, bundles/org.openhab.core.compat1x/src/main/java/org/openhab/core/items/GenericItem.java, bundles/org.openhab.core.compat1x/src/main/java/org/openhab/core/library/items/ColorItem.java, bundles/org.openhab.core.compat1x/src/main/java/org/openhab/core/library/items/ContactItem.java, bundles/org.openhab.core.compat1x/src/main/java/org/openhab/core/library/items/DimmerItem.java, bundles/org.openhab.core.compat1x/src/main/java/org/openhab/core/library/items/RollershutterItem.java, bundles/org.openhab.core.compat1x/src/main/java/org/openhab/core/service/AbstractActiveService.java, bundles/org.openhab.core.compat1x/src/main/java/org/openhab/model/item/binding/AbstractGenericBindingProvider.java
See openhab/static-code-analysis#103
Signed-off-by: VelinYordanov <velin.iordanov@gmail.com>
=> Removed unnecessary inheritDoc.

pom.xml, poms/pom.xml
=> Add maven unleash plugin and make git scm definition more flexible to be able to do shadow releases

bundles/org.openhab.core.compat1x/src/main/java/org/openhab/core/binding/internal/BindingConfigReaderDelegate.java
=> adapted to changed ESH API

bundles/org.openhab.core.compat1x/src/main/java/org/openhab/io/net/http/HttpUtil.java
=> reduced logging level as the util class cannot judge the severity

features/openhab-core/src/main/feature/feature.xml
=> updated features to latest ESH changes reg. jUPnP + Jetty HTTP Client

features/openhab-core/src/main/feature/feature.xml, poms/pom.xml
=> Updated to Karaf 4.1.3 and Jetty 9.3.22 and used new ESH features

poms/pom.xml, poms/tycho/pom.xml, targetplatform/openhab.target
=> updated target platform information

poms/pom.xml, targetplatform/openhab.target
Fixes https://github.com/openhab/openhab2-addons/issues/2867
=> updated targetplatform to deps 1.0.19

poms/tycho/pom.xml
=> fixed groupId for DS annotations

bundles/org.openhab.core.compat1x.test/src/test/java/org/openhab/core/compat1x/internal/TypeMapperTest.java, bundles/org.openhab.core.compat1x/src/main/java/org/openhab/core/compat1x/internal/TypeMapper.java
=> adapted DataTimeType mapping to new ESH type

features/openhab-core/src/main/feature/feature.xml
=> added a feature for the Home Builder

poms/pom.xml
=> switching to ESH 0.10.0-SNAPSHOT

poms/pom.xml
fixes shillner/unleash-maven-plugin#91
=> Upgrade maven unleash plugin to version 2.7.3

bundles/org.openhab.ui.dashboard/README.md
Signed-off-by: Thomas Dietrich <thomas.dietrich@tu-ilmenau.de> (github: ThomDietrich)
=> Improve dashboard README

bundles/org.openhab.ui.dashboard/src/main/java/org/openhab/ui/dashboard/internal/DashboardService.java
=> correctly unregister dashboard servlet

poms/tycho/pom.xml
see eclipse/smarthome#4604
Signed-off-by: Simon Kaufmann <simon.kfm@googlemail.com>
=> Disable maven null analysis errors until tycho > 1.0 release

bundles/org.openhab.ui.homebuilder/USAGE.md
Addresses https://github.com/openhab/openhab-docs/issues/591
cc: @ThomDietrich 
Signed-off-by: Kuba Wolanin <hi@kubawolanin.com> (github: kubawolanin)
=> [HomeBuilder] Usage documentation updated

poms/pom.xml, poms/tycho/pom.xml
As discussed at https://github.com/openhab/openhab-core/pull/259#discussion_r157341331
=> introduced eshRelease version

poms/tycho/pom.xml
to prevent formatting issues on automated release
=> Add explicit version to tycho pom.xml

poms/tycho/pom.xml
Fixes https://github.com/openhab/openhab2-addons/pull/2894#issuecomment-352311312
=> added required dependency to scr-plugin

bundles/org.openhab.ui.homebuilder/src/main/java/org/openhab/ui/homebuilder/internal/HomeBuilderDashboardTile.java
Signed-off-by: Svilen Valkanov <svilen.valkanov@musala.com>
=> Update header in HomeBuilder UI

bundles/org.openhab.ui.dashboard/src/main/java/org/openhab/ui/dashboard/internal/DashboardService.java
😶 Revolutionizing the world, one triviality at a time
=> Capitalize Dashboard in log messages

bundles/org.openhab.ui.dashboard/src/main/java/org/openhab/ui/dashboard/internal/DashboardService.java, bundles/org.openhab.ui.dashboard/src/main/java/org/openhab/ui/dashboard/internal/DashboardServlet.java, bundles/org.openhab.ui.dashboard/src/main/java/org/openhab/ui/dashboard/internal/ExternalServiceTile.java
Fixes #281
Signed-off-by: Pauli Anttila <pauli.anttila@gmail.com>
=> [Dashboard] Fix illegal tile caused NPE

pom.xml, poms/pom.xml, tools/checkstyle.properties
**Important:** Should be merged after the new release of the Static Code Analysis Tool
Signed-off-by: Svilen Valkanov <svilen.valkanov@musala.com>
=> Update sat configuration and version 

poms/pom.xml, poms/tycho/pom.xml
=> fixed warnings in build and added equinox.jetty dependency for feed tests

poms/tycho/pom.xml
=> fixed indentation

bundles/org.openhab.core.compat1x/OSGI-INF/actionservicefactory.xml, bundles/org.openhab.core.compat1x/OSGI-INF/autoupdateproviderdelegate.xml, bundles/org.openhab.core.compat1x/OSGI-INF/bindingconfigreaderfactory.xml, bundles/org.openhab.core.compat1x/OSGI-INF/chartproviderfactory.xml, bundles/org.openhab.core.compat1x/OSGI-INF/eventbridge.xml, bundles/org.openhab.core.compat1x/OSGI-INF/eventpublisherdelegate.xml, bundles/org.openhab.core.compat1x/OSGI-INF/itemuiregistry.xml, bundles/org.openhab.core.compat1x/OSGI-INF/persistenceservicefactory.xml, bundles/org.openhab.core.karaf/ESH-INF/config/config.xml, bundles/org.openhab.core.karaf/OSGI-INF/featureinstaller.xml, bundles/org.openhab.core.karaf/OSGI-INF/karafextensionservice.xml, bundles/org.openhab.core/OSGI-INF/defaultsitemapprovider.xml, bundles/org.openhab.core/OSGI-INF/iconforwarder.xml, bundles/org.openhab.io.rest.docs/OSGI-INF/dashboardtile.xml, bundles/org.openhab.io.rest.docs/OSGI-INF/swaggerservice.xml, bundles/org.openhab.io.sound/OSGI-INF/enhancedjavasound.xml, bundles/org.openhab.ui.basicui/OSGI-INF/dashboardtile.xml, bundles/org.openhab.ui.classicui/OSGI-INF/dashboardtile.xml, bundles/org.openhab.ui.homebuilder/OSGI-INF/dashboardtile.xml, bundles/org.openhab.ui.paperui/OSGI-INF/dashboardtile.xml
@kaikreuzer Here are the fixed XML files with the correct indentation.
=> Fixed issues found by Static Code Analysis Tool (OnlyTabIdentationInXmlFilesCheck)

poms/pom.xml
=> updated to latest version of 3rd party dependencies

features/openhab-core/src/main/feature/feature.xml, poms/pom.xml
=> upgrade to Karaf 4.1.5

poms/tycho/pom.xml
=> removed reference to release repo

poms/tycho/pom.xml
same as https://github.com/openhab/openhab2-addons/pull/3406
related to https://github.com/openhab/openhab2-addons/pull/3334
=> moved release repo in profile

bundles/org.openhab.core.compat1x/src/main/java/org/openhab/core/binding/internal/BindingConfigReaderDelegate.java
=> only regard ESH main type when mapping to OH types

poms/pom.xml
=> updated to 1.0.24 dependencies with zigbee libs

poms/pom.xml
=> updated to latest deps version

features/openhab-core/src/main/feature/feature.xml
This should fix issues described in https://github.com/openhab/openhab-distro/pull/703#issuecomment-388773661
=> directly added http client feature to http transport

poms/pom.xml
related to https://github.com/openhab/openhab-distro/pull/708
=> updated dependencies to 1.0.26

bundles/org.openhab.core.karaf/src/main/java/org/openhab/core/karaf/internal/KarafExtensionService.java
=> adapted links to documentation to new website layout

bundles/org.openhab.ui.homebuilder/README.md, bundles/org.openhab.ui.homebuilder/USAGE.md
Update Home Builder documentations links to the new website layout.
=> Update Home Builder documentation links

poms/pom.xml
=> Use newest version of maven-deploy-plugin

tools/checkstyle.properties
Fixes #354
Signed-off-by: Martin van Wingerden <martinvw@mtin.nl>
=> Update version number regex

poms/pom.xml
=> updated to new dependencies with JUPnP 2.4

poms/pom.xml
=> upgraded to official nrjavaserial 3.14.0 release

poms/pom.xml
related to https://github.com/openhab/openhab-deps-repo/pull/6
=> Change to dependencies 1.0.29

features/openhab-core/src/main/feature/feature.xml, poms/pom.xml
=> updated deps to 1.0.30

poms/tycho/pom.xml
Related to https://github.com/openhab/openhab2-addons/pull/2167#issuecomment-411117269
=> added missing smarthome dependencies

poms/tycho/pom.xml
=> added missing segment in bundle name

poms/tycho/pom.xml
This is just yet another try to fix https://openhab.ci.cloudbees.com/job/sandbox-openhab2-release
No idea whether it'll work, but I'd like to try...
=> readded params that existed in the config previously

poms/tycho/pom.xml
Didn't help, so let's revert...
Reverts openhab/openhab-core#379
=> Revert "readded params that existed in the config previously"

bundles/org.openhab.core.karaf/pom.xml
Removes the unused bundle properties.
=> Remove unused bundle properties

poms/pom.xml
Related to https://github.com/openhab/openhab-distro/pull/751
=> Updated deps version for new Zigbee libs

poms/tycho/pom.xml
This should fix https://openhab.ci.cloudbees.com/job/sandbox-openhab2-release/735/
=> removed outdated and no longer existing dependency

poms/pom.xml
Related to https://github.com/openhab/openhab-distro/pull/770
=> updated dependencies for Xtext upgrade

bundles/org.openhab.core.karaf.dep.war/META-INF/MANIFEST.MF, bundles/org.openhab.core.karaf.dep.war/about.html, bundles/org.openhab.core.karaf.dep.war/build.properties, bundles/org.openhab.core.karaf.dep.war/pom.xml, bundles/pom.xml, poms/pom.xml, poms/tycho/pom.xml
See also https://github.com/eclipse/smarthome/pull/6198 and https://github.com/eclipse/smarthome/pull/6209
=> update Tycho version and avoid warnings during the build

poms/pom.xml
Related to https://github.com/openhab/openhab-distro/pull/775
=> updated to 1.0.33 for new zigbee libs

poms/tycho/pom.xml
This should hopefully fix the issues we see at https://openhab.ci.cloudbees.com/job/openHAB2-Bundles/426
=> Adding new ESH bundles as dependencies

poms/tycho/pom.xml
=> added new semantics bundle as dependency

bundles/org.openhab.ui.start/META-INF/MANIFEST.MF, bundles/org.openhab.ui.start/pom.xml, bundles/org.openhab.ui.start/src/main/java/org/openhab/ui/start/internal/RootServlet.java
=>  register static context handler

bundles/org.openhab.ui.start/src/main/java/org/openhab/ui/start/internal/RootServlet.java, features/openhab-core/src/main/feature/feature.xml
Fixes https://github.com/openhab/openhab-core/issues/422 until there is a better solution.
=> temporarily remove ui.start bundle from distro again

bundles/org.openhab.core.compat1x/src/main/java/org/openhab/core/persistence/internal/QueryablePersistenceServiceDelegate.java
prevents NPE as seen in https://github.com/openhab/openhab-distro/issues/801
=> prevent NPEs if persistence service does not play nice

poms/pom.xml
=> update Maven build to deps 1.0.34 as well

tools/checkstyle.properties
Assuming this was the intended goal of the forbidden packages check
CC: @kaikreuzer, @VelinYordanov, @dstivanov
=> Add com.google.common.collect to forbidden packages

features/openhab-core/src/main/feature/feature.xml, poms/pom.xml
=> defined JNA feature that can be used by addons

poms/pom.xml
=> updated dependencies to 1.0.36 with nrjavaserial 3.15.0.OH

bundles/org.openhab.core/src/main/java/org/openhab/core/OpenHAB.java
Fixes https://github.com/openhab/openhab-distro/issues/812
=> leave non-numeric qualifiers in place for version

bundles/org.openhab.ui.dashboard/ESH-INF/i18n/dashboard.properties
Closes: https://github.com/openhab/openhab-core/issues/441
=> Update dashboard / place 1st the Standard package

features/openhab-core/src/main/feature/feature.xml
Related to https://github.com/eclipse/smarthome/pull/6607
=> Added oauth2 client

poms/pom.xml
Signed-off-by: Chris Jackson <chris@cd-jackson.com>
=> Bump ZigBee libraries to 1.1.6

poms/pom.xml
=> Added arm64 support for serial port access

poms/pom.xml
@pfink Can this change be somehow considered in the automatic version upgrade?
=> updated to version 2.5

poms/pom.xml
=> switched to ESH 0.11.0-SNAPSHOT

bundles/org.openhab.core.karaf/src/main/java/org/openhab/core/karaf/internal/FeatureInstaller.java
With https://github.com/openhab/openhab-core/pull/99 bulk feature installation was added. With the code changes of that PR it is assumed that features are always installed succesfully.
Whenever features fail to install the openHAB `FeatureInstaller` will try to reinstall these every minute.
This may generate a lot of load which is hard to debug with many side effects (see [community topic](https://community.openhab.org/t/after-upgrade-to-2-4-stable-im-flooded-with-java-lang-illegalstateexception/61567?u=wborn)).
With this PR the `FeatureInstaller` will again log on error whenever features fail to install.
We could also not install features that aren't returned by `FeaturesService.listFeatures`. However it's still possible features fail to install and this load is generated for other …
=> Log failed feature installation on error

pom.xml
Signed-off-by: Hilbrand Bouwkamp <hilbrand@h72.nl>
=> Updated license url in pom.xml to epl-2.0

features/karaf/openhab-tp/src/main/feature/feature.xml
=> removed some ESH references

features/p2/repo/src/main/filtered-resources/publish-bintray.sh
=> switched from zip to tar.gz as this is available on Linux by default

pom.xml
=> Remove duplicate import

bundles/org.openhab.core.storage.mapdb/src/main/java/org/eclipse/smarthome/storage/mapdb/internal/MapDbStorage.java, bundles/org.openhab.core.storage.mapdb/src/test/java/org/eclipse/smarthome/storage/mapdb/internal/MapDbStorageServiceTest.java
Fixes: https://github.com/eclipse/smarthome/issues/6877
=> MapDB storage: fix deserialization bug and add test

bundles/org.openhab.core.config.discovery.usbserial/src/main/java/org/eclipse/smarthome/config/discovery/usbserial/internal/UsbSerialDiscoveryService.java, itests/org.openhab.core.config.discovery.usbserial.tests/src/test/java/org/eclipse/smarthome/config/discovery/usbserial/internal/UsbSerialDiscoveryServiceTest.java
For better differentiation between different USB devices `UsbSerialDiscoveryService` is extended to add `usb_vendor_id` and `usb_product_id` properties to every thing which represents USB device.
Ported from https://github.com/eclipse/smarthome/pull/6862
Also-by: YordanDZhelev <zhelev.yordan@gmail.com>
=> Extend usb serial discovery service to contain product ID

bundles/pom.xml, pom.xml
Fixes: https://github.com/openhab/openhab-core/issues/496
=> attach source artifact of "bundles"

bundles/org.openhab.core.config.core/src/main/java/org/eclipse/smarthome/config/core/status/ConfigStatusMessage.java
Fixes: https://github.com/openhab/openhab-core/issues/504
=> at missing no-arg constructor for Gson deserialization

bundles/org.openhab.core.config.xml/src/main/java/org/eclipse/smarthome/config/xml/osgi/XmlDocumentBundleTracker.java, bundles/org.openhab.core.test/src/main/java/org/eclipse/smarthome/test/SyntheticBundleInstaller.java, bundles/org.openhab.core.thing/src/main/java/org/eclipse/smarthome/core/thing/internal/ThingManagerImpl.java
Fixes: https://github.com/openhab/openhab-core/issues/508
=> harden against missing bundle symbolic name

pom.xml
Related to: https://github.com/openhab/openhab-core/pull/467#issuecomment-456362798
=> WAR: ignore Eclipse IDE integration of bnd indexer temporary

features/p2/repo/pom.xml
Fixes #524
Signed-off-by: Florian <florian.schmidt.welzow@t-online.de>
=> Remove pluginRepository repo.reficio.org as it is offline

tools/oomph/openHAB-Core.setup
Signed-off-by: Henning Treu <henning.treu@googlemail.com>
=> Adopt openHAB Core IDE setup to folder layout & set workspace name

demo/app/app.bndrun
=> fixed feature names

features/karaf/openhab-core/.project
=> fix project name

features/karaf/openhab-core/src/main/feature/feature.xml
=> a few small fixes in feature definitions

bundles/org.openhab.core.io.rest.core/src/main/java/org/eclipse/smarthome/io/rest/core/internal/service/ConfigurableServiceResource.java
Fixes https://github.com/openhab/openhab-core/issues/556
Fixes https://github.com/eclipse/smarthome/issues/6710
=> handle arrays for pids

bundles/org.openhab.core.io.rest.core/src/main/java/org/eclipse/smarthome/io/rest/core/internal/service/ConfigurableServiceResource.java
Argh, this happens when doing fixes without having a fully working setup in the IDE...
#557 completely failed to fix the issue. :-(
New try here - fixes https://github.com/openhab/openhab-core/issues/556
=> check for lists instead of arrays

bundles/org.openhab.core.model.rule/bnd.bnd
Fixes: https://github.com/openhab/openhab-core/issues/553
=> ensure rules can access joda time packages

demo/app/app.bndrun
Fixes https://github.com/openhab/openhab-core/issues/576
=> removed aries from demo app

bundles/org.openhab.core.automation/src/main/resources/ESH-INF/automation/moduletypes/ItemActions.json
Unify types - Second try
See also types in automation/moduletypes/ItemTriggers.json
=> [automation] Unify types - itemsActions

bundles/org.openhab.core/src/main/java/org/eclipse/smarthome/core/library/unit/SmartHomeUnits.java, itests/org.openhab.core.tests/src/main/java/org/eclipse/smarthome/core/library/types/QuantityTypeArithmeticGroupFunctionTest.java, itests/org.openhab.core.tests/src/main/java/org/eclipse/smarthome/core/library/types/QuantityTypeTest.java
This PR adresses : 
- [ESH issue #6889] (https://github.com/eclipse/smarthome/issues/6889)
- [ESH issue #6846] (https://github.com/eclipse/smarthome/issues/6846)
Checks that
- [ESH issue #6843] (https://github.com/eclipse/smarthome/issues/6843) works as expected
=> Small UoM evolutions

bundles/org.openhab.core.model.core/src/main/java/org/eclipse/smarthome/model/core/internal/folder/FolderObserver.java
Fixes: https://github.com/openhab/openhab-core/issues/591
"Fixes" it hopefully. @cweitkamp please check yourself.
=> model.core: respect OSGi lifecycle

bom/compile/pom.xml, bom/runtime/pom.xml, features/karaf/openhab-tp/src/main/feature/feature.xml
The version 2.5.2 contains the provided JUPnPService capability information.
=> bump jUPnP

bundles/org.openhab.core.model.rule/bnd.bnd
fixes https://github.com/openhab/openhab-core/issues/613
=> made package imports explicit

bundles/org.openhab.core.config.core/src/main/java/org/eclipse/smarthome/config/core/Configuration.java
We recently encountered a ConcurrentModificationException in the setProperties() method. This PR changes the implementation so that a synchronized Map is used throughout the class, including setProperties() and toString() where the synchronization was previously missing.
While doing that we saw that the equals() method was merely comparing the hashcodes of the maps. This could of course result in equals() returning true for Configurations which are actually different, and thus in subtle bugs. We changed that so that equals() delegates to the equals() method of the HashMap objects.
We also simplified the implementation of the setProperties() method as well as the constructors.
=> fix synchronisation and equals() in Configuration

.pullapprove.yml
=> Added PullApprove config

features/p2/poms/pom.xml
Should be merged after https://github.com/openhab/openhab-deps-repo/pull/13
=> Update ohdr.version to 1.0.42

itests/org.openhab.core.semantics.tests/itest.bndrun, itests/pom.xml
=> Enable Semantics Integration Tests

bundles/org.openhab.core.storage.mapdb/src/main/java/org/eclipse/smarthome/storage/mapdb/internal/MapDbStorage.java, bundles/org.openhab.core.storage.mapdb/src/main/java/org/eclipse/smarthome/storage/mapdb/internal/MapDbStorageService.java, bundles/org.openhab.core.storage.mapdb/src/main/java/org/eclipse/smarthome/storage/mapdb/internal/PropertiesTypeAdapter.java, bundles/org.openhab.core.storage.mapdb/src/main/java/org/eclipse/smarthome/storage/mapdb/internal/PropertiesTypeAdapterFactory.java, bundles/org.openhab.core.storage.mapdb/src/test/java/org/eclipse/smarthome/storage/mapdb/internal/MapDbStorageServiceTest.java
* add some comments
* don't catch unspecific `Exception`
* don't use non escaped `<` or `>` in JavaDoc (only for well defined tags)
=> mapdb storage: minor cleanups

bom/runtime/pom.xml
Add nrjavaserial to runtime bom
Signed-off-by: David Graeff <david.graeff@web.de>
=> Add nrjavaserial to runtime bom

bundles/org.openhab.core.io.console.karaf/pom.xml, bundles/org.openhab.core.karaf/pom.xml, features/karaf/pom.xml, pom.xml
Related to: https://github.com/openhab/openhab-core/pull/723#issuecomment-483595667
=> differ between min. karaf version (OSGi) und karaf compilation tooling

bundles/org.openhab.core.thing/src/main/java/org/eclipse/smarthome/core/thing/internal/profiles/SystemProfileFactory.java, bundles/org.openhab.core.thing/src/main/java/org/eclipse/smarthome/core/thing/internal/profiles/TimestampChangeProfile.java, bundles/org.openhab.core.thing/src/main/java/org/eclipse/smarthome/core/thing/internal/profiles/TimestampUpdateProfile.java, bundles/org.openhab.core.thing/src/main/java/org/eclipse/smarthome/core/thing/profiles/SystemProfiles.java, itests/org.openhab.core.thing.tests/src/main/java/org/eclipse/smarthome/core/thing/internal/profiles/TimestampProfileTest.java
=> Proposal for some new profiles : Change and update timestamp

itests/org.openhab.core.magic.tests/.classpath, itests/org.openhab.core.magic.tests/itest.bndrun, itests/org.openhab.core.magic.tests/src/main/java/org/eclipse/smarthome/magic/binding/internal/MagicHandlerFactoryTest.java, itests/org.openhab.core.magic.tests/src/main/java/org/eclipse/smarthome/magic/binding/internal/MagicServiceImplTest.java, itests/pom.xml
- Fixed unit tests magic bundle
Related to #698
=> Enable Magic Bundle Tests

pom.xml, tools/archetype/binding/.project, tools/archetype/binding/pom.xml, tools/archetype/binding/src/main/resources/META-INF/archetype-post-generate.groovy, tools/archetype/binding/src/main/resources/META-INF/maven/archetype-metadata.xml, tools/archetype/binding/src/main/resources/archetype-resources/.classpath, tools/archetype/binding/src/main/resources/archetype-resources/.project, tools/archetype/binding/src/main/resources/archetype-resources/NOTICE, tools/archetype/binding/src/main/resources/archetype-resources/README.md, tools/archetype/binding/src/main/resources/archetype-resources/pom.xml, tools/archetype/binding/src/main/resources/archetype-resources/src/main/java/internal/__bindingIdCamelCase__BindingConstants.java, tools/archetype/binding/src/main/resources/archetype-resources/src/main/java/internal/__bindingIdCamelCase__Configuration.java, tools/archetype/binding/src/main/resources/archetype-resources/src/main/java/internal/__bindingIdCamelCase__Handler.java, tools/archetype/binding/src/main/resources/archetype-resources/src/main/java/internal/__bindingIdCamelCase__HandlerFactory.java, tools/archetype/binding/src/main/resources/archetype-resources/src/main/resources/ESH-INF/binding/binding.xml, tools/archetype/binding/src/main/resources/archetype-resources/src/main/resources/ESH-INF/i18n/__bindingId___xx_XX.properties, tools/archetype/binding/src/main/resources/archetype-resources/src/main/resources/ESH-INF/thing/thing-types.xml, tools/archetype/pom.xml, tools/pom.xml
Note: I think the generated test launch file is not yet correct. But this seems a problem in general to all existing launch files too. So I would suggest to fix this when those files are being fixed to.
Closes #582
=> Added maven archetype project to generate binding skeletons

tools/archetype/binding/src/main/resources/archetype-resources/.classpath
As reported in https://github.com/openhab/openhab2-addons/pull/5462#pullrequestreview-231428050
=> [archetype] .classpath should contain tabs.

bundles/org.openhab.core/src/main/java/org/eclipse/smarthome/core/internal/common/CombinedClassLoader.java, bundles/org.openhab.core/src/main/java/org/eclipse/smarthome/core/internal/common/SafeCallerBuilderImpl.java
Related to: https://github.com/openhab/openhab2-addons/issues/5519
=> safe caller: respect classloader of the class and the interfaces

bundles/org.openhab.core.binding.xml/binding-1.0.0.xsd, bundles/org.openhab.core.config.xml/config-description-1.0.0.xsd, bundles/org.openhab.core.thing.xml/thing-description-1.0.0.xsd
- Updated xml schema definition locations permanently to openHAB
=> Updated xml schema definition locations permanently to openHAB

bundles/org.openhab.core.thing/src/main/java/org/eclipse/smarthome/core/thing/internal/profiles/RawButtonTogglePlayerProfile.java, bundles/org.openhab.core.thing/src/main/java/org/eclipse/smarthome/core/thing/internal/profiles/RawButtonToggleRollershutterProfile.java, bundles/org.openhab.core.thing/src/main/java/org/eclipse/smarthome/core/thing/internal/profiles/RawButtonToggleSwitchProfile.java, bundles/org.openhab.core.thing/src/main/java/org/eclipse/smarthome/core/thing/internal/profiles/RawRockerStopMoveProfile.java, bundles/org.openhab.core.thing/src/main/java/org/eclipse/smarthome/core/thing/internal/profiles/RawRockerUpDownProfile.java, bundles/org.openhab.core.thing/src/main/java/org/eclipse/smarthome/core/thing/internal/profiles/SystemProfileFactory.java, bundles/org.openhab.core.thing/src/main/java/org/eclipse/smarthome/core/thing/profiles/SystemProfiles.java
- Added `RawButtonToggleRollershutterProfile`, `RawRockerStopMoveProfile` and `RawRockerUpDownProfile`
=> Added profiles to control Rollershutter Items via default system triggers

tools/archetype/binding/src/main/resources/archetype-resources/src/main/java/internal/__bindingIdCamelCase__Handler.java, tools/archetype/binding/src/main/resources/archetype-resources/src/main/java/internal/__bindingIdCamelCase__HandlerFactory.java, tools/archetype/binding/src/main/resources/archetype-resources/src/main/resources/ESH-INF/i18n/__bindingId___xx_XX.properties, tools/archetype/binding/src/main/resources/archetype-resources/src/main/resources/ESH-INF/thing/thing-types.xml
- Applied formatter in all files
- Added translation example for config parameter
=> [archetype] Applied formatter in all files

tools/archetype/binding/src/main/resources/META-INF/archetype-post-generate.groovy
Update karaf feature file location
Signed-off-by: David Gräff <david.graeff@web.de>
=> Archetype: karaf feature file location fix

bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/RuleEngineImpl.java
Related to: https://github.com/openhab/openhab-core/pull/787
=> automation: disabled storage must not be null anymore

itests/org.openhab.core.audio.tests/src/main/java/org/eclipse/smarthome/core/audio/internal/AudioServletTest.java
The test suite for the audio servlet contains a test that will fail on systems under heavy load (or just imperformant systems).
An audio stream should be added for 1 (streamTimeout) second.
The stream is requested and it is tested that it can be accessed.
After that the test waits until the stream is no more available (this will be the cause after "streamTimeout").
If the "add stream" and "get request for stream" operations already exceed the "streamTimeout" limit, the test will fail.
This can be handled in the test case itself if we check the timespan we need to get the stream and if we know that the stream is allowed to be non present already, we continue with the next step without failing.
Fixes: https://github.com/openhab/openhab-core/issues/799
=> audio servlet test: harden against slow test systems

bundles/org.openhab.core.model.item/.classpath, bundles/org.openhab.core.model.persistence/.classpath, bundles/org.openhab.core.model.rule/.classpath, bundles/org.openhab.core.model.script/.classpath, bundles/org.openhab.core.model.sitemap/.classpath
=> removed classpath entries of non-existent folders in order to solve compilation errors in IDE

bom/compile/pom.xml, bom/runtime/pom.xml, features/karaf/openhab-tp/src/main/feature/feature.xml
Fixes unreleased resources, disconnecting problems and many more
Signed-off-by: David Gräff <david.graeff@web.de>
=> Update paho to 1.2.1 service release

bundles/org.openhab.core.thing/src/main/java/org/eclipse/smarthome/core/thing/DefaultSystemChannelTypeProvider.java
- Use constructor dependency injection
=> Improvements for 'DefaultSystemChannelTypeProvider'

bundles/org.openhab.core.config.xml/src/main/java/org/eclipse/smarthome/config/xml/AbstractXmlBasedProvider.java, bundles/org.openhab.core.thing/src/main/java/org/eclipse/smarthome/core/thing/DefaultSystemChannelTypeProvider.java, bundles/org.openhab.core.thing/src/main/java/org/eclipse/smarthome/core/thing/internal/profiles/SystemProfileFactory.java, bundles/org.openhab.core/src/main/java/org/eclipse/smarthome/core/i18n/LocalizedKey.java
- Factored out 'LocalizedKey' into separate class
See https://github.com/openhab/openhab-core/pull/785#issue-275320575
=> Factored out 'LocalizedKey' into separate class

bundles/org.openhab.core.config.discovery/src/main/java/org/eclipse/smarthome/config/discovery/internal/PersistentInbox.java
Fixes: https://github.com/openhab/openhab-core/issues/812
=> persistent inbox: do not use incomplete initialized object

bundles/org.openhab.core.model.item/src/org/eclipse/smarthome/model/item/internal/GenericItemProvider.java
Fixes: https://github.com/openhab/openhab-core/issues/811
=> use constructor injection to simplify lifecycle

bundles/org.openhab.core.config.discovery/src/main/java/org/eclipse/smarthome/config/discovery/internal/PersistentInbox.java
Fixes: https://github.com/openhab/openhab-core/issues/823
=> persistent inbox: ensure all members has been set before usage

bundles/org.openhab.core.io.jetty.certificate/pom.xml
=> partly revert #795 

bundles/org.openhab.core.thing/src/main/java/org/eclipse/smarthome/core/thing/link/ThingLinkManager.java, bundles/org.openhab.core/src/main/java/org/eclipse/smarthome/core/common/registry/ProviderChangeListener.java, bundles/org.openhab.core/src/main/java/org/eclipse/smarthome/core/events/AbstractTypedEventSubscriber.java, itests/org.openhab.core.automation.tests/src/main/java/org/openhab/core/automation/event/RuleEventTest.java, itests/org.openhab.core.thing.tests/src/main/java/org/eclipse/smarthome/core/thing/internal/ThingManagerOSGiTest.java, itests/org.openhab.core.thing.tests/src/main/java/org/eclipse/smarthome/core/thing/link/ItemChannelLinkOSGiTest.java
See https://github.com/openhab/openhab-core/issues/834#issuecomment-496301592
=> Added nullness annotations

bundles/org.openhab.core.model.rule.runtime/src/org/eclipse/smarthome/model/rule/runtime/internal/engine/RuleEngineImpl.java
=> model: Use constructor injection to simplify lifecycle

bundles/org.openhab.core.persistence/src/main/java/org/eclipse/smarthome/core/persistence/internal/PersistenceManagerImpl.java
- Fixed JavaDoc to get rid of the Quartz includes
See https://github.com/openhab/openhab-core/pull/850#discussion_r289791406
=> Fixed JavaDoc to get rid of the Quartz includes

bundles/org.openhab.core.model.rule.runtime/src/org/eclipse/smarthome/model/rule/runtime/internal/engine/RuleEngineImpl.java
- Refactoring of `RuleEngineImpl`
See https://github.com/openhab/openhab-core/pull/850#discussion_r289796348
=> model: Refactoring of 'RuleEngineImpl'

bundles/org.openhab.core.model.script/src/org/eclipse/smarthome/model/script/scoping/ScriptImplicitlyImportedTypes.java, bundles/org.openhab.core.model.script/src/org/eclipse/smarthome/model/script/scoping/StateAndCommandProvider.java
- Added `RefreshType.REFRESH` and `BinaryPrefix` to imports
Closes #845
=> [dsl] Added 'RefreshType.REFRESH' and 'BinaryPrefix' to imports

bundles/org.openhab.core/src/main/java/org/eclipse/smarthome/core/common/NamedThreadFactory.java, bundles/org.openhab.core/src/main/java/org/eclipse/smarthome/core/common/ThreadPoolManager.java
... to make it usable for others
=> use separate class for named thread factory

bundles/org.openhab.core.io.rest.sse/src/main/java/org/eclipse/smarthome/io/rest/sse/internal/SseActivator.java
=> workaround for #597

bom/compile/pom.xml, bom/runtime/pom.xml, features/karaf/openhab-tp/src/main/feature/feature.xml
Signed-off-by: Hakan Tandogan <hakan@tandogan.com>
Updating to 0.5.8 so the turkish holidays are available, too 😄
=> [ephemeris] upgrade jollyday library to the latest released version

bundles/org.openhab.core.io.rest.core/pom.xml
See https://github.com/openhab/openhab-core/issues/892#issuecomment-504738793
=> corrected artifact name

pom.xml
Related to: https://github.com/openhab/infrastructure/issues/9
=> bump super POM

bundles/org.openhab.core.config.discovery.upnp/src/main/java/org/eclipse/smarthome/config/discovery/upnp/internal/UpnpDiscoveryService.java
Fixes https://github.com/openhab/openhab-core/issues/895
Signed-off-by: Daniel Walters <danielwalters1@hotmail.com>
=> Fix typo in exception message

bundles/org.openhab.core.ephemeris/src/main/resources/ESH-INF/config/config.xml
- Updated xml schema locations to openHAB
=> Updated xml schema locations to openHAB

bundles/org.openhab.core.ephemeris/src/main/java/org/eclipse/smarthome/core/ephemeris/EphemerisManager.java, bundles/org.openhab.core.ephemeris/src/main/java/org/eclipse/smarthome/core/ephemeris/internal/EphemerisManagerImpl.java, bundles/org.openhab.core.model.script/src/org/eclipse/smarthome/model/script/actions/Ephemeris.java
- Added action to check for bank holiday from a given user file
=> [Ephemeris] Added action to check for bank holiday from a given user file

bom/compile/pom.xml, bom/runtime/pom.xml, features/karaf/openhab-tp/src/main/feature/feature.xml
Replaces: https://github.com/openhab/openhab-core/pull/684
=> provide Java EE modules

bundles/org.openhab.core/src/test/java/org/eclipse/smarthome/core/library/types/DateTimeTypeTest.java
- Added equality tests for parsed dates and timezone
- Moved from integration test to unit test
Related to #872
=> Added equality tests for parsed dates and timezone

bundles/org.openhab.core/src/main/java/org/eclipse/smarthome/core/library/types/QuantityType.java
- Avoid multiple type castings
=> Avoid multiple type castings

itests/org.openhab.core.tests/src/main/java/org/eclipse/smarthome/core/cache/ExpiringCacheAsyncTest.java
=> Fix integration test for ExpiringCacheAsync

itests/org.openhab.core.thing.tests/src/main/java/org/eclipse/smarthome/core/thing/internal/profiles/TimestampProfileTest.java
=> Fix integration test for thing: TimestampChangeProfile

bundles/org.openhab.core.model.script/src/org/eclipse/smarthome/model/script/actions/ScriptExecution.java
=> Unique job key for createTimer in DSL rule

bundles/org.openhab.core.thing/src/main/java/org/eclipse/smarthome/core/thing/profiles/ProfileFactory.java
=> Fixed spelling in JavaDoc

bundles/org.openhab.core.automation.module.script.rulesupport/src/main/resources/ESH-INF/automation/moduletypes/PrivateScriptedTypes.json
Add missing configDescription for required input parameter 'privId'. Issue is described here #962.
Signed-off-by: Philipp Waller <philipp.waller@gmail.com>
=> [automation] Update configDescriptions for jsr223.ScriptedTrigger (#962)

tools/archetype/binding/src/main/resources/META-INF/archetype-post-generate.groovy
This change handles the following cases:
- New binding that will be the first entry in the list
- New binding that is placed after/between multi project bindings. Like bluetooth and mqtt (reported in openhab/openhab2-addons#5860)
Signed-off-by: Hilbrand Bouwkamp <hilbrand@h72.nl>
=> [archetype] Fix groovy script to handle certain cases

bundles/org.openhab.core.semantics/src/main/java/org/eclipse/smarthome/core/semantics/SemanticTags.java
=> [Semantics] Fix properties loading

bundles/org.openhab.core.ui/src/main/java/org/eclipse/smarthome/ui/internal/items/ItemUIRegistryImpl.java, itests/org.openhab.core.ui.tests/src/main/java/org/eclipse/smarthome/ui/internal/items/ItemUIRegistryImplTest.java
=> GetLabel: Handle correctly string value lookling like a transform pattern

bundles/org.openhab.core.persistence/src/main/java/org/eclipse/smarthome/core/persistence/PersistenceManager.java, bundles/org.openhab.core.persistence/src/main/java/org/eclipse/smarthome/core/persistence/PersistenceServiceRegistry.java, bundles/org.openhab.core.persistence/src/main/java/org/eclipse/smarthome/core/persistence/internal/PersistenceManagerImpl.java, bundles/org.openhab.core.persistence/src/main/java/org/eclipse/smarthome/core/persistence/internal/PersistenceServiceRegistryImpl.java, itests/org.openhab.core.model.persistence.tests/src/main/java/org/eclipse/smarthome/model/persistence/extensions/PersistenceExtensionsTest.java
- Specified service for component description
- Minor code improvements
=> [persistence] Use constructor injection to simplify lifecycle

bundles/org.openhab.core/src/main/java/org/eclipse/smarthome/core/internal/items/ItemRegistryImpl.java, bundles/org.openhab.core/src/main/java/org/eclipse/smarthome/core/internal/items/ItemStateConverterImpl.java, bundles/org.openhab.core/src/main/java/org/eclipse/smarthome/core/items/ItemStateConverter.java, itests/org.openhab.core.tests/src/main/java/org/eclipse/smarthome/core/internal/items/ItemStateConverterImplTest.java, itests/org.openhab.core.tests/src/main/java/org/eclipse/smarthome/core/items/GroupItemTest.java, itests/org.openhab.core.tests/src/main/java/org/eclipse/smarthome/core/items/ItemRegistryImplTest.java
=> [itemregistry] Use constructor injection to simplify lifecycle

bundles/org.openhab.core.io.rest.core/src/main/java/org/eclipse/smarthome/io/rest/core/internal/item/ItemResource.java, bundles/org.openhab.core.io.rest/src/main/java/org/eclipse/smarthome/io/rest/JSONResponse.java, bundles/org.openhab.core.io.rest/src/main/java/org/eclipse/smarthome/io/rest/Stream2JSONInputStream.java, itests/org.openhab.core.io.rest.core.tests/src/main/java/org/eclipse/smarthome/io/rest/core/internal/item/ItemResourceOSGiTest.java
- Streamline DTO serialization for REST item resources
Related to #981 
=> [rest] Streamline DTO serialization for REST item resources

bundles/org.openhab.core.model.script/src/org/eclipse/smarthome/model/script/internal/RuleHumanLanguageInterpreter.java
- Added "configurationPid"
- Minor code improvements
Fixes #1001
=> [rulehli] Added "configurationPid"

bundles/org.openhab.core.config.discovery/src/main/java/org/eclipse/smarthome/config/discovery/internal/PersistentInbox.java
- Fixed wrong nullness annotation
=> [inbox] Fixed wrong nullness annotation

.travis.yml, bundles/org.openhab.core.io.http.auth/src/main/java/org/eclipse/smarthome/io/http/auth/internal/AuthenticationHandler.java, bundles/org.openhab.core.io.net/src/main/java/org/eclipse/smarthome/io/net/http/internal/ExtensibleTrustManagerImpl.java, bundles/org.openhab.core/src/main/java/org/eclipse/smarthome/core/internal/service/ReadyServiceImpl.java, pom.xml, tools/static-code-analysis/checkstyle/ruleset.properties
- Bump SAT to 0.7.0 
- Fixed high priority findings
- Defined path to feature file to avoid warnings
=> [infrastructure] bump SAT to 0.7.0

bundles/org.openhab.core.voice/src/main/java/org/eclipse/smarthome/core/voice/internal/VoiceManagerImpl.java
=> [voice] say: log something when the audio sink cannot be found

bundles/org.openhab.core.ui/src/main/java/org/eclipse/smarthome/ui/internal/items/ItemUIRegistryImpl.java
=> Mapview element by default for a location item

bundles/org.openhab.core.io.console.karaf/src/main/java/org/eclipse/smarthome/io/console/karaf/internal/ConsoleSupportKaraf.java, bundles/org.openhab.core.io.console/src/main/java/org/eclipse/smarthome/io/console/extensions/AbstractConsoleCommandExtension.java, bundles/org.openhab.core.io.console/src/main/java/org/eclipse/smarthome/io/console/extensions/ConsoleCommandExtension.java, bundles/org.openhab.core.io.console/src/main/java/org/eclipse/smarthome/io/console/internal/extension/ItemConsoleCommandExtension.java, bundles/org.openhab.core.io.console/src/main/java/org/eclipse/smarthome/io/console/internal/extension/MetadataConsoleCommandExtension.java, bundles/org.openhab.core.io.console/src/main/java/org/eclipse/smarthome/io/console/internal/extension/SendConsoleCommandExtension.java, bundles/org.openhab.core.io.console/src/main/java/org/eclipse/smarthome/io/console/internal/extension/StatusConsoleCommandExtension.java, bundles/org.openhab.core.io.console/src/main/java/org/eclipse/smarthome/io/console/internal/extension/UpdateConsoleCommandExtension.java
=> [console] Use constructor injection to simplify lifecycle

bundles/org.openhab.core.transform/src/main/java/org/eclipse/smarthome/core/transform/AbstractFileTransformationService.java
=> AbstractFileTransformationService: stop watchService properly

bundles/org.openhab.core/src/main/java/org/eclipse/smarthome/core/internal/scheduler/DelegatedSchedulerImpl.java, itests/org.openhab.core.tests/src/main/java/org/eclipse/smarthome/core/internal/scheduler/DelegatedSchedulerTest.java
=> Inject SchedulerImpl into DelegatedSchedulerImpl to fix waiting bundles

bundles/org.openhab.core.model.thing/src/org/eclipse/smarthome/model/thing/internal/GenericThingProvider.xtend
- Removed deleted things from internal map (https://github.com/openhab/openhab-core/commit/d59f4584ffbc8192353bfe3014ccbb0081c44c3f)
Fixes #1042 
=> [DSL] Removed deleted things from internal map

bundles/org.openhab.core.io.net/src/main/java/org/eclipse/smarthome/io/net/http/TrustAllTrustMananger.java, bundles/org.openhab.core.io.net/src/main/java/org/eclipse/smarthome/io/net/http/internal/WebClientFactoryImpl.java, itests/org.openhab.core.io.net.tests/src/main/java/org/eclipse/smarthome/io/net/http/internal/ExtensibleTrustManagerImplTest.java, itests/org.openhab.core.io.net.tests/src/main/java/org/eclipse/smarthome/io/net/http/internal/WebClientFactoryImplTest.java
=> [net] Use constructor injection to simplify lifecycle

itests/org.openhab.core.automation.integration.tests/itest.bndrun, itests/org.openhab.core.automation.integration.tests/src/main/java/org/openhab/core/automation/integration/test/AutomationIntegrationJsonTest.java, itests/org.openhab.core.automation.integration.tests/src/main/java/org/openhab/core/automation/integration/test/AutomationIntegrationTest.java, itests/org.openhab.core.automation.integration.tests/src/main/java/org/openhab/core/automation/integration/test/HostFragmentSupportTest.java, itests/pom.xml
=> Reenable org.openhab.core.automation.integration.tests

itests/org.openhab.core.model.script.tests/.classpath, itests/org.openhab.core.model.script.tests/itest.bndrun, itests/org.openhab.core.model.script.tests/src/main/java/org/eclipse/smarthome/model/script/actions/ScriptExecutionTest.java, itests/org.openhab.core.model.script.tests/src/main/java/org/eclipse/smarthome/model/script/engine/ScriptEngineOSGiTest.java, itests/org.openhab.core.model.script.tests/src/main/java/org/eclipse/smarthome/model/script/lib/NumberExtensionsTest.java, itests/org.openhab.core.model.script.tests/src/main/java/org/eclipse/smarthome/model/script/tests/lib/NumberExtensionsTest.java, itests/pom.xml
- Enable Model Script Tests
Related to #698
Currently failing.
=> Enable Model Script Tests

bundles/org.openhab.core.config.discovery/src/main/java/org/eclipse/smarthome/config/discovery/internal/DiscoveryServiceRegistryImpl.java
- Removed FQN from service declaration
=> Removed FQN from service declaration

bundles/org.openhab.core.thing/src/main/java/org/eclipse/smarthome/core/thing/internal/ThingManagerImpl.java
- Removed orphaned `registerHandlerLock`
As there is no place where a `ThingUID` will be added to the `registerHandlerLock` the `waitForRunningHandlerRegistrations` will always return immediately. Additionally the logic is wrapped by a second `Lock`. We can savely remove this orphaned code.
Closes #1022
=> Removed orphaned 'registerHandlerLock'

bundles/org.openhab.core.storage.json/src/main/java/org/eclipse/smarthome/storage/json/internal/JsonStorage.java, bundles/org.openhab.core.storage.json/src/main/java/org/eclipse/smarthome/storage/json/internal/JsonStorageService.java, bundles/org.openhab.core.storage.json/src/main/java/org/eclipse/smarthome/storage/json/internal/StorageEntry.java, bundles/org.openhab.core.storage.json/src/main/java/org/eclipse/smarthome/storage/json/internal/StorageEntryMapDeserializer.java, bundles/org.openhab.core.storage.json/src/test/java/org/eclipse/smarthome/storage/json/internal/JsonStorageTest.java, bundles/org.openhab.core.storage.mapdb/src/main/java/org/eclipse/smarthome/storage/mapdb/internal/MapDbStorage.java, bundles/org.openhab.core.storage.mapdb/src/main/java/org/eclipse/smarthome/storage/mapdb/internal/MapDbStorageService.java, bundles/org.openhab.core.storage.mapdb/src/main/java/org/eclipse/smarthome/storage/mapdb/internal/PropertiesTypeAdapter.java, bundles/org.openhab.core.storage.mapdb/src/main/java/org/eclipse/smarthome/storage/mapdb/internal/PropertiesTypeAdapterFactory.java, bundles/org.openhab.core.thing/src/test/java/org/eclipse/smarthome/core/thing/internal/ThingManagerImplTest.java, bundles/org.openhab.core/src/main/java/org/eclipse/smarthome/core/storage/DeletableStorage.java, bundles/org.openhab.core/src/main/java/org/eclipse/smarthome/core/storage/DeletableStorageService.java, bundles/org.openhab.core/src/main/java/org/eclipse/smarthome/core/storage/StorageService.java, itests/org.openhab.core.storage.json.tests/pom.xml, itests/org.openhab.core.storage.json.tests/src/main/java/org/eclipse/smarthome/storage/json/internal/JsonStorageServiceOSGiTest.java
- Minor code refactorings / SAT findings
=> [storage] Added nullness annotations

pom.xml
=> switched to latest super-pom

bundles/org.openhab.core.config.dispatch/src/main/java/org/eclipse/smarthome/config/dispatch/internal/ConfigDispatcher.java, itests/org.openhab.core.config.dispatch.tests/src/main/java/org/eclipse/smarthome/config/dispatch/internal/ConfigDispatcherOSGiTest.java, itests/org.openhab.core.config.dispatch.tests/src/main/resources/configurations/local_pid_whitespaces_conf/local.pid.default.file.cfg, itests/org.openhab.core.config.dispatch.tests/src/main/resources/configurations/local_pid_whitespaces_conf/local_pid_services/local.pid.service.file.cfg
- Fixed wrong trimmed properties
See https://github.com/openhab/openhab-distro/issues/978#issue-504014740
=> [config dispatch] Fixed wrong trimmed properties

itests/org.openhab.core.config.discovery.tests/src/main/java/org/eclipse/smarthome/config/discovery/DiscoveryServiceRegistryOSGiTest.java, itests/org.openhab.core.config.dispatch.tests/src/main/java/org/eclipse/smarthome/config/dispatch/internal/ConfigDispatcherOSGiTest.java, itests/org.openhab.core.io.rest.core.tests/src/main/java/org/eclipse/smarthome/io/rest/core/internal/item/ItemResourceOSGiTest.java, itests/org.openhab.core.model.core.tests/src/main/java/org/eclipse/smarthome/model/core/internal/folder/FolderObserverTest.java, itests/org.openhab.core.model.item.tests/src/main/java/org/eclipse/smarthome/model/item/internal/GenericItemProvider2Test.java, itests/org.openhab.core.model.item.tests/src/main/java/org/eclipse/smarthome/model/item/internal/GenericMetadataProviderTest.java, itests/org.openhab.core.model.rule.tests/src/main/java/org/eclipse/smarthome/model/rule/runtime/internal/engine/RuleTriggerTest.java, itests/org.openhab.core.model.script.tests/src/main/java/org/eclipse/smarthome/model/script/engine/ScriptEngineOSGiTest.java, itests/org.openhab.core.model.script.tests/src/main/java/org/eclipse/smarthome/model/script/lib/NumberExtensionsTest.java, itests/org.openhab.core.model.script.tests/src/main/java/org/eclipse/smarthome/model/script/tests/lib/NumberExtensionsTest.java, itests/org.openhab.core.tests/src/main/java/org/eclipse/smarthome/core/internal/common/SafeCallerImplTest.java, itests/org.openhab.core.tests/src/main/java/org/eclipse/smarthome/core/internal/events/OSGiEventManagerOSGiTest.java, itests/org.openhab.core.tests/src/main/java/org/eclipse/smarthome/core/items/GroupItemOSGiTest.java, itests/org.openhab.core.tests/src/main/java/org/eclipse/smarthome/core/service/AbstractWatchServiceTest.java, itests/org.openhab.core.thing.tests/src/main/java/org/eclipse/smarthome/core/thing/ThingPropertiesTest.java, itests/org.openhab.core.thing.tests/src/main/java/org/eclipse/smarthome/core/thing/events/ThingEventFactoryTest.java, itests/org.openhab.core.thing.tests/src/main/java/org/eclipse/smarthome/core/thing/internal/CommunicationManagerOSGiTest.java, itests/org.openhab.core.thing.tests/src/main/java/org/eclipse/smarthome/core/thing/internal/ThingManagerOSGiJavaTest.java, itests/org.openhab.core.thing.tests/src/main/java/org/eclipse/smarthome/core/thing/internal/firmware/FirmwareUpdateServiceTest.java, itests/org.openhab.core.thing.tests/src/main/java/org/eclipse/smarthome/core/thing/internal/profiles/SystemProfileFactoryOSGiTest.java, itests/org.openhab.core.thing.xml.tests/src/main/java/org/eclipse/smarthome/core/thing/xml/test/ChannelTypesTest.java, itests/org.openhab.core.thing.xml.tests/src/main/java/org/eclipse/smarthome/core/thing/xml/test/ConfigDescriptionsTest.java, itests/org.openhab.core.thing.xml.tests/src/main/java/org/eclipse/smarthome/core/thing/xml/test/ThingTypesTest.java
=> Fix SAT MethodNameCheck findings

bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/handler/ActionHandler.java, bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/module/provider/i18n/ModuleTypeI18nService.java, bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/util/ReferenceResolver.java, bundles/org.openhab.core.compat1x/src/main/java/org/openhab/core/binding/BindingProvider.java, bundles/org.openhab.core.compat1x/src/main/java/org/openhab/core/items/ItemFactory.java, bundles/org.openhab.core.compat1x/src/main/java/org/openhab/core/library/types/PointType.java, bundles/org.openhab.core.compat1x/src/main/java/org/openhab/core/transform/TransformationService.java, bundles/org.openhab.core.compat1x/src/main/java/org/openhab/core/transform/actions/Transformation.java, bundles/org.openhab.core.compat1x/src/main/java/org/openhab/io/net/actions/Exec.java, bundles/org.openhab.core.compat1x/src/main/java/org/openhab/io/net/actions/Ping.java, bundles/org.openhab.core.compat1x/src/main/java/org/openhab/io/net/exec/ExecUtil.java, bundles/org.openhab.core.compat1x/src/main/java/org/openhab/io/net/http/HttpUtil.java, bundles/org.openhab.core.compat1x/src/main/java/org/openhab/model/item/binding/BindingConfigReader.java, bundles/org.openhab.core.compat1x/src/main/java/org/openhab/ui/chart/ChartProvider.java, bundles/org.openhab.core.compat1x/src/main/java/org/openhab/ui/items/ItemUIProvider.java, bundles/org.openhab.core.compat1x/src/main/java/org/openhab/ui/items/ItemUIRegistry.java, bundles/org.openhab.core.test/src/main/java/org/eclipse/smarthome/test/SyntheticBundleInstaller.java, bundles/org.openhab.core/src/main/java/org/eclipse/smarthome/core/auth/AuthenticationManager.java, bundles/org.openhab.core/src/main/java/org/eclipse/smarthome/core/auth/client/oauth2/AccessTokenResponse.java, bundles/org.openhab.core/src/main/java/org/eclipse/smarthome/core/auth/client/oauth2/StorageCipher.java, bundles/org.openhab.core/src/main/java/org/eclipse/smarthome/core/items/ItemBuilderFactory.java, bundles/org.openhab.core/src/main/java/org/eclipse/smarthome/core/library/types/DateTimeType.java, bundles/org.openhab.core/src/main/java/org/eclipse/smarthome/core/library/types/HSBType.java, bundles/org.openhab.core/src/main/java/org/eclipse/smarthome/core/types/StateDescriptionFragmentProvider.java
=> Fix SAT JavadocMethodStyleCheck findings

bundles/org.openhab.core.thing.xml/src/main/java/org/eclipse/smarthome/core/thing/xml/internal/ChannelXmlResult.java
=> [xml] Fixed minor spelling issue

bundles/org.openhab.core.automation.module.script/src/main/java/org/openhab/core/automation/module/script/internal/AbstractScriptEngineFactory.java, bundles/org.openhab.core.automation.module.script/src/main/java/org/openhab/core/automation/module/script/internal/ScriptEngineManagerImpl.java, bundles/org.openhab.core.automation.module.script/src/main/java/org/openhab/core/automation/module/script/internal/handler/AbstractScriptModuleHandler.java, bundles/org.openhab.core.automation.module.script/src/main/java/org/openhab/core/automation/module/script/internal/provider/ScriptModuleTypeProvider.java, bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/commands/AbstractCommandProvider.java, bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/composite/CompositeModuleHandlerFactory.java, bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/provider/AbstractResourceBundleProvider.java, bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/provider/AutomationResourceBundlesEventQueue.java, bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/provider/file/AbstractFileProvider.java, bundles/org.openhab.core.automation/src/test/java/org/openhab/core/automation/util/ReferenceResolverUtilTest.java, bundles/org.openhab.core.config.core/src/main/java/org/eclipse/smarthome/config/core/internal/normalization/AbstractNormalizer.java, bundles/org.openhab.core.io.http/src/main/java/org/eclipse/smarthome/io/http/servlet/BaseSmartHomeServlet.java, bundles/org.openhab.core/src/main/java/org/eclipse/smarthome/core/items/ItemRegistry.java, bundles/org.openhab.core/src/main/java/org/eclipse/smarthome/core/service/AbstractWatchService.java, bundles/org.openhab.core/src/test/java/org/eclipse/smarthome/core/common/QueueingThreadPoolExecutorTest.java
- Normalized instantiation of loggers
=> Normalized instantiation of loggers

bundles/org.openhab.core.ui/src/main/java/org/eclipse/smarthome/ui/internal/proxy/ProxyServletService.java, itests/org.openhab.core.config.discovery.tests/src/main/java/org/eclipse/smarthome/config/discovery/internal/InboxOSGiTest.java, itests/org.openhab.core.tests/src/main/java/org/eclipse/smarthome/core/internal/common/SafeCallerImplTest.java, itests/org.openhab.core.thing.tests/src/main/java/org/eclipse/smarthome/core/thing/internal/ThingManagerOSGiTest.java, itests/org.openhab.core.voice.tests/src/main/java/org/eclipse/smarthome/core/voice/voiceconsolecommandextension/SayCommandTest.java
As a result a few more rule counts will drop to zero.
=> Fixes a few more SAT findings

bundles/org.openhab.core.io.rest.core/src/main/java/org/eclipse/smarthome/io/rest/core/config/EnrichedConfigDescriptionParameterDTO.java, bundles/org.openhab.core.io.rest.core/src/test/java/org/eclipse/smarthome/io/rest/core/config/EnrichedConfigDescriptionDTOMapperTest.java
- Fixed potential NPE if 'defaultValue' is null
See https://github.com/openhab/openhab-core/pull/1031#issuecomment-544138235
=> [rest] Fixed potential NPE if 'defaultValue' is null

bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/RuleEngineImpl.java, bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/commands/Printer.java, bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/provider/file/WatchServiceUtil.java, bundles/org.openhab.core.compat1x/src/main/java/org/openhab/core/binding/AbstractActiveBinding.java, bundles/org.openhab.core.config.core/src/main/java/org/eclipse/smarthome/config/core/ConfigUtil.java, bundles/org.openhab.core.io.rest.core/src/main/java/org/eclipse/smarthome/io/rest/core/internal/profile/ProfileTypeResource.java, bundles/org.openhab.core.ui/src/main/java/org/eclipse/smarthome/ui/internal/chart/defaultchartprovider/DefaultChartProvider.java, bundles/org.openhab.core.ui/src/main/java/org/eclipse/smarthome/ui/internal/items/ItemUIRegistryImpl.java, bundles/org.openhab.core.voice/src/main/java/org/eclipse/smarthome/core/voice/text/ExpressionCardinality.java
`isEmpty()` expresses the intent more clearly and is therefore preferred.
Counting the number of elements can also be an expensive operation e.g. when using linked lists.
=> Use isEmpty() instead of "size() == 0"

bundles/org.openhab.core.config.core/src/main/java/org/eclipse/smarthome/config/core/i18n/ConfigI18nLocalizationService.java
=> [config] Use constructor injection to simplify lifecycle

itests/org.openhab.core.automation.module.script.defaultscope.tests/src/main/java/org/openhab/core/automation/module/script/defaultscope/internal/ScopeTest.java
=> Fix ScopeTest on Windows

bundles/org.openhab.core.io.rest/src/main/java/org/eclipse/smarthome/io/rest/Stream2JSONInputStream.java
Fixes #1002
---
With this PR and #1148, a full build with tests on Windows builds successfully for me @lolodomo.
=> Fix ItemResourceOSGiTest on Windows

bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/module/handler/TimeOfDayTriggerHandler.java
Fixes [#1156](https://github.com/openhab/openhab-core/issues/1156)
=> [automation] Fix the created cron to run only once at the trigger minute.

bundles/org.openhab.core.automation/src/main/resources/ESH-INF/automation/moduletypes/EphemerisConditions.json
=> [automation] Fix typos in EphemerisConditions.json

bundles/org.openhab.core.binding.xml/src/main/java/org/eclipse/smarthome/core/binding/xml/internal/BindingInfoXmlProvider.java, bundles/org.openhab.core.binding.xml/src/main/java/org/eclipse/smarthome/core/binding/xml/internal/BindingInfoXmlResult.java, bundles/org.openhab.core.binding.xml/src/main/java/org/eclipse/smarthome/core/binding/xml/internal/BindingXmlConfigDescriptionProvider.java, bundles/org.openhab.core.binding.xml/src/main/java/org/eclipse/smarthome/core/binding/xml/internal/XmlBindingInfoProvider.java, bundles/org.openhab.core.config.xml/src/main/java/org/eclipse/smarthome/config/xml/AbstractXmlBasedProvider.java, bundles/org.openhab.core.config.xml/src/main/java/org/eclipse/smarthome/config/xml/AbstractXmlConfigDescriptionProvider.java, bundles/org.openhab.core.config.xml/src/main/java/org/eclipse/smarthome/config/xml/osgi/XmlDocumentProvider.java, bundles/org.openhab.core.config.xml/src/main/java/org/eclipse/smarthome/config/xml/osgi/XmlDocumentProviderFactory.java, bundles/org.openhab.core/src/main/java/org/eclipse/smarthome/core/binding/BindingInfo.java, bundles/org.openhab.core/src/main/java/org/eclipse/smarthome/core/binding/BindingInfoProvider.java, bundles/org.openhab.core/src/main/java/org/eclipse/smarthome/core/binding/BindingInfoRegistry.java, bundles/org.openhab.core/src/main/java/org/eclipse/smarthome/core/binding/dto/BindingInfoDTO.java, bundles/org.openhab.core/src/main/java/org/eclipse/smarthome/core/binding/i18n/BindingI18nLocalizationService.java, bundles/org.openhab.core/src/main/java/org/eclipse/smarthome/core/binding/internal/i18n/BindingI18nUtil.java
- Moved i18n util class into internal package, introduction of a `BindingI18nLocalizationService`
=> [binding] Added nullness annotations

bundles/org.openhab.core.model.script/bnd.bnd, bundles/org.openhab.core.model.script/pom.xml
fixes #1115
supersedes https://github.com/openhab/openhab-core/pull/1117
=> added "resources" folder as a resource folder to the build

bundles/org.openhab.core.config.xml/src/main/java/org/eclipse/smarthome/config/xml/ConfigXmlConfigDescriptionProvider.java
- Added constructor injection to config xml
=> [xml] Added constructor injection to config xml

bundles/org.openhab.core.storage.mapdb/src/main/java/org/eclipse/smarthome/storage/mapdb/internal/MapDbStorage.java, bundles/org.openhab.core.storage.mapdb/src/test/java/org/eclipse/smarthome/storage/mapdb/internal/MapDbStorageServiceTest.java, bundles/org.openhab.core/src/main/java/org/eclipse/smarthome/core/items/ManagedItemProvider.java, itests/org.openhab.core.tests/src/main/java/org/eclipse/smarthome/core/items/ManagedItemProviderOSGiTest.java
- Added `InstanceCreator` for `PersistedItem`
Fixes #1005
=> Added 'InstanceCreator' for 'PersistedItem'

bundles/org.openhab.core.audio/src/main/java/org/eclipse/smarthome/core/audio/AudioException.java, bundles/org.openhab.core.audio/src/main/java/org/eclipse/smarthome/core/audio/AudioFormat.java, bundles/org.openhab.core.audio/src/main/java/org/eclipse/smarthome/core/audio/AudioHTTPServer.java, bundles/org.openhab.core.audio/src/main/java/org/eclipse/smarthome/core/audio/AudioSource.java, bundles/org.openhab.core.audio/src/main/java/org/eclipse/smarthome/core/audio/AudioStream.java, bundles/org.openhab.core.audio/src/main/java/org/eclipse/smarthome/core/audio/ByteArrayAudioStream.java, bundles/org.openhab.core.audio/src/main/java/org/eclipse/smarthome/core/audio/FileAudioStream.java, bundles/org.openhab.core.audio/src/main/java/org/eclipse/smarthome/core/audio/FixedLengthAudioStream.java, bundles/org.openhab.core.audio/src/main/java/org/eclipse/smarthome/core/audio/URLAudioStream.java, bundles/org.openhab.core.audio/src/main/java/org/eclipse/smarthome/core/audio/UnsupportedAudioFormatException.java, bundles/org.openhab.core.audio/src/main/java/org/eclipse/smarthome/core/audio/UnsupportedAudioStreamException.java, bundles/org.openhab.core.audio/src/main/java/org/eclipse/smarthome/core/audio/internal/AudioConsoleCommandExtension.java, bundles/org.openhab.core.audio/src/main/java/org/eclipse/smarthome/core/audio/internal/AudioManagerImpl.java, bundles/org.openhab.core.audio/src/main/java/org/eclipse/smarthome/core/audio/internal/AudioServlet.java, bundles/org.openhab.core.audio/src/main/java/org/eclipse/smarthome/core/audio/utils/AudioStreamUtils.java, bundles/org.openhab.core.audio/src/test/java/org/eclipse/smarthome/core/audio/internal/AudioConsoleTest.java, bundles/org.openhab.core.io.http/src/main/java/org/eclipse/smarthome/io/http/servlet/BaseSmartHomeServlet.java
I've also created https://github.com/openhab/openhab2-addons/pull/6323 for updating the add-ons for these changes.
=> Add null annotations to audio package

bundles/org.openhab.core.config.core/src/main/java/org/eclipse/smarthome/config/core/ConfigDescription.java, bundles/org.openhab.core.config.core/src/main/java/org/eclipse/smarthome/config/core/ConfigDescriptionBuilder.java, bundles/org.openhab.core.config.core/src/test/java/org/eclipse/smarthome/config/core/ConfigDescriptionBuilderTest.java, bundles/org.openhab.core.config.core/src/test/java/org/eclipse/smarthome/config/core/ConfigDescriptionParameterBuilderTest.java
- Added `ConfigDescriptionBuilder`
=> [config] Added 'ConfigDescriptionBuilder'

bundles/org.openhab.core/src/main/java/org/eclipse/smarthome/core/types/CommandDescriptionBuilder.java, bundles/org.openhab.core/src/main/java/org/eclipse/smarthome/core/types/StateDescriptionFragmentBuilder.java, bundles/org.openhab.core/src/test/java/org/eclipse/smarthome/core/types/CommandDescriptionBuilderTest.java, bundles/org.openhab.core/src/test/java/org/eclipse/smarthome/core/types/StateDescriptionFragmentBuilderTest.java
- Added nullness annotations to `CommandDescriptionBuilder`
- Added unit test for `CommandDescriptionBuilder`
=> [core] Added nullness annotations and unit test for 'CommandDescriptionBuilder'

bundles/org.openhab.core.io.http/src/main/java/org/eclipse/smarthome/io/http/servlet/SmartHomeServlet.java, bundles/org.openhab.core.ui/src/main/java/org/eclipse/smarthome/ui/internal/chart/ChartServlet.java, bundles/org.openhab.core.ui/src/main/java/org/eclipse/smarthome/ui/internal/chart/defaultchartprovider/DefaultChartProvider.java
=> [ui] Use constructor injection to simplify lifecycle

bundles/org.openhab.core.karaf/src/main/java/org/openhab/core/karaf/internal/FeatureInstaller.java, bundles/org.openhab.core.karaf/src/main/java/org/openhab/core/karaf/internal/KarafExtensionService.java
- Added links for (available) docs of all Add-Ons
- Minor code refactoring
Closes #269 
=> Added links for (available) docs of all Add-Ons

bundles/org.openhab.core.thing/src/main/java/org/eclipse/smarthome/core/thing/profiles/SystemProfiles.java, bundles/org.openhab.core.thing/src/main/resources/ESH-INF/i18n/SystemProfiles_de.properties
- Added German translations for profiles
=> [profile] Added German translations for profiles

features/karaf/openhab-tp/src/main/feature/feature.xml
See https://github.com/openhab/openhab2-addons/pull/6275
=> updated netty patch level

bundles/org.openhab.core/src/main/java/org/eclipse/smarthome/core/library/items/DateTimeItem.java, bundles/org.openhab.core/src/main/java/org/eclipse/smarthome/core/library/types/DateTimeType.java, bundles/org.openhab.core/src/main/java/org/eclipse/smarthome/core/library/types/DecimalType.java, bundles/org.openhab.core/src/test/java/org/eclipse/smarthome/core/library/types/DateTimeTypeTest.java, bundles/org.openhab.core/src/test/java/org/eclipse/smarthome/core/library/types/DecimalTypeTest.java
=> Issue #1157 Enhance DecimalType to accept epoch seconds and milliseconds.

bundles/org.openhab.core.io.transport.mqtt/src/main/java/org/eclipse/smarthome/io/transport/mqtt/reconnect/PeriodicReconnectStrategy.java
=> [MQTT] PeriodicReconnectStrategy: fix fields init

bundles/org.openhab.core/src/main/java/org/eclipse/smarthome/core/library/unit/ImperialUnits.java, bundles/org.openhab.core/src/main/java/org/eclipse/smarthome/core/library/unit/SIUnits.java, bundles/org.openhab.core/src/main/java/org/eclipse/smarthome/core/library/unit/SmartHomeUnits.java
- Minor clean-ups in `SmartHomeUnits`, `SIUnits` and `ImperialUnits`
=> Minor clean-ups in 'SmartHomeUnits', 'SIUnits' and 'ImperialUnits'

bundles/org.openhab.core/src/main/java/org/eclipse/smarthome/core/cache/ExpiringCache.java
- Added check for invalid duration
=> [cache] Added check for invalid duration

bundles/org.openhab.core.io.transport.mdns/pom.xml, bundles/org.openhab.core.io.transport.mdns/src/main/java/org/eclipse/smarthome/io/transport/mdns/internal/MDNSClientImpl.java, bundles/org.openhab.core.io.transport.mdns/src/main/java/org/eclipse/smarthome/io/transport/mdns/internal/MDNSServiceImpl.java
=> [io.mdns] Use constructor injection to simplify lifecycle

bundles/org.openhab.core.io.transport.upnp/pom.xml, bundles/org.openhab.core.io.transport.upnp/src/main/java/org/eclipse/smarthome/io/transport/upnp/internal/UpnpIOServiceImpl.java, bundles/org.openhab.core.io.transport.upnp/src/test/java/org/eclipse/smarthome/io/transport/upnp/internal/UpnpIOServiceTest.java
=> [io.upnp] Use constructor injection to simplify lifecycle

itests/org.openhab.core.config.discovery.usbserial.tests/itest.bndrun
Related to: https://github.com/openhab/openhab-core/pull/1218#pullrequestreview-317995622
=> use mock instead of real service implementation

bundles/org.openhab.core.io.rest.core/src/main/java/org/eclipse/smarthome/io/rest/core/internal/extensions/ExtensionResource.java, bundles/org.openhab.core.io.rest.core/src/main/java/org/eclipse/smarthome/io/rest/core/internal/item/ItemResource.java, bundles/org.openhab.core.io.rest.core/src/main/java/org/eclipse/smarthome/io/rest/core/internal/persistence/PersistenceResource.java, bundles/org.openhab.core.io.rest.sitemap/src/main/java/org/eclipse/smarthome/io/rest/sitemap/internal/SitemapResource.java, bundles/org.openhab.core.io.rest.voice/src/main/java/org/eclipse/smarthome/io/rest/voice/internal/VoiceResource.java
Fixes: https://github.com/openhab/openhab-core/issues/1217
=> [rest] Use correct wildcard for mandatory path parameters

bundles/org.openhab.core/src/main/java/org/eclipse/smarthome/core/library/items/StringItem.java
=> Removed duplicate brackets

bundles/org.openhab.core/src/main/java/org/eclipse/smarthome/core/library/types/DateTimeType.java, bundles/org.openhab.core/src/test/java/org/eclipse/smarthome/core/library/types/DecimalTypeTest.java
=> Correcting Issue #1231

bundles/org.openhab.core.compat1x/src/main/java/org/openhab/core/items/GroupItem.java, bundles/org.openhab.core.model.core/src/main/java/org/eclipse/smarthome/model/core/internal/folder/FolderObserver.java, bundles/org.openhab.core.thing/src/main/java/org/eclipse/smarthome/core/thing/util/ThingHelper.java
- Removed dependency on `org.apache.commons.collections`
=> Removed dependency on 'org.apache.commons.collections'

features/karaf/openhab-tp/src/main/feature/feature.xml
Depends on https://github.com/openhab/openhab-osgiify/pull/11
=> Osgiify of dagger library

bom/compile/pom.xml
=> added Californium to compile bom

bundles/org.openhab.core.io.transport.mqtt/src/main/java/org/eclipse/smarthome/io/transport/mqtt/MqttBrokerConnection.java, bundles/org.openhab.core.io.transport.mqtt/src/main/java/org/eclipse/smarthome/io/transport/mqtt/internal/client/MqttAsyncClientWrapper.java
Following  https://github.com/openhab/openhab-core/pull/1259#discussion_r355141114
=> make MQTT subscription tracking thread-safe

bundles/org.openhab.core.io.transport.mqtt/src/main/java/org/eclipse/smarthome/io/transport/mqtt/internal/client/MqttAsyncClientWrapper.java
Fixes https://github.com/openhab/openhab2-addons/issues/6562
=> [mqtt] fix failing subscriptions

bundles/org.openhab.core.io.rest.core/src/main/java/org/eclipse/smarthome/io/rest/core/internal/item/ItemResource.java, bundles/org.openhab.core.io.rest.core/src/main/java/org/eclipse/smarthome/io/rest/core/internal/item/MetadataSelectorMatcher.java, bundles/org.openhab.core.io.rest.core/src/test/java/org/eclipse/smarthome/io/rest/core/internal/item/MetadataSelectorMatcherTest.java, bundles/org.openhab.core.model.item/src/org/eclipse/smarthome/model/item/internal/GenericMetadataProvider.java, bundles/org.openhab.core/src/main/java/org/eclipse/smarthome/core/internal/items/ManagedMetadataProviderImpl.java, bundles/org.openhab.core/src/main/java/org/eclipse/smarthome/core/internal/items/MetadataRegistryImpl.java, bundles/org.openhab.core/src/main/java/org/eclipse/smarthome/core/items/ManagedMetadataProvider.java
- Simplify lifecycle by using constructor injection
=> [metadata] Simplify lifecycle by using constructor injection

bundles/org.openhab.core/src/main/java/org/eclipse/smarthome/core/auth/client/oauth2/OAuthClientService.java
=> Fixed link in JavaDoc

bundles/org.openhab.core/src/main/java/org/openhab/core/internal/items/GroupFunctionHelper.java, bundles/org.openhab.core/src/main/java/org/openhab/core/items/GenericItem.java, bundles/org.openhab.core/src/main/java/org/openhab/core/items/GroupFunction.java, bundles/org.openhab.core/src/main/java/org/openhab/core/items/GroupItem.java, bundles/org.openhab.core/src/main/java/org/openhab/core/library/types/ArithmeticGroupFunction.java, bundles/org.openhab.core/src/main/java/org/openhab/core/library/types/DateTimeGroupFunction.java, bundles/org.openhab.core/src/main/java/org/openhab/core/library/types/QuantityTypeArithmeticGroupFunction.java, itests/org.openhab.core.tests/src/main/java/org/openhab/core/items/GroupItemOSGiTest.java
- Some minor improvements
- Unit tests for 'ItemCommandEvent' on group
=> Added nullness annotations; Some minor improvements; Unit tests for 'ItemCommandEvent' on group

bundles/org.openhab.core.model.item/bnd.bnd, bundles/org.openhab.core.model.persistence/bnd.bnd, bundles/org.openhab.core.model.rule/bnd.bnd, bundles/org.openhab.core.model.script/bnd.bnd, bundles/org.openhab.core.model.sitemap/bnd.bnd, bundles/org.openhab.core.model.thing/bnd.bnd
Related to: https://github.com/openhab/openhab-core/pull/1171
=> Correct Xtext version in bnd.bnd files

bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/binding/BaseThingHandler.java
- Simplify code for `ThingHandler` `updateProperty` method
=> Simplify code for 'updateProperty' method

bundles/org.openhab.core/src/main/java/org/openhab/core/library/dimension/Conductivity.java, bundles/org.openhab.core/src/main/java/org/openhab/core/library/dimension/ElectricConductivity.java, bundles/org.openhab.core/src/main/java/org/openhab/core/library/unit/SmartHomeUnits.java, bundles/org.openhab.core/src/test/java/org/openhab/core/library/unit/SmartHomeUnitsTest.java
=> Add Ampere hour (Ah) and electrolytic conductivity (µS/cm) units

bundles/org.openhab.core.storage.json/src/main/java/org/openhab/core/storage/json/internal/JsonStorageService.java, bundles/org.openhab.core.storage.mapdb/src/main/java/org/openhab/core/storage/mapdb/internal/MapDbStorageService.java
- Fixed storage configurationPids
=> Fixed storage configurationPids

pom.xml
=> switched to SAT 0.9.0

bundles/org.openhab.core/src/main/java/org/openhab/core/library/unit/SmartHomeUnits.java, pom.xml
=> Applied spotless formatter

bundles/org.openhab.core.model.persistence/src/org/openhab/core/model/persistence/extensions/PersistenceExtensions.java, itests/org.openhab.core.model.persistence.tests/src/main/java/org/openhab/core/model/persistence/extensions/PersistenceExtensionsTest.java, itests/org.openhab.core.model.persistence.tests/src/main/java/org/openhab/core/model/persistence/tests/TestPersistenceService.java
- Added test coverage for persistence extension
Related to #1333 
=> [persistence] Added test coverage for persistence extension

bundles/org.openhab.core.automation.module.script/src/main/java/org/openhab/core/automation/module/script/internal/defaultscope/ScriptThingActions.java, bundles/org.openhab.core.model.script/src/org/openhab/core/model/script/ScriptServiceUtil.java, bundles/org.openhab.core.model.script/src/org/openhab/core/model/script/internal/engine/action/ThingActionService.java, bundles/org.openhab.core.model.script/src/org/openhab/core/model/script/scoping/ActionClassLoader.java, bundles/org.openhab.core.model.script/src/org/openhab/core/model/script/scoping/ScriptImplicitlyImportedTypes.java, bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/binding/ThingActions.java, bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/binding/ThingHandlerService.java
- Added nullness annotations to 'ThingActions' and 'ThingHandlerService'
- Minor code improvements and reordering of imports
=> Added nullness annotations to 'ThingActions' and 'ThingHandlerService'

bundles/org.openhab.core/src/main/java/org/openhab/core/library/types/StringListType.java, bundles/org.openhab.core/src/test/java/org/openhab/core/library/types/StringListTypeTest.java
=> added hashCode and equals method to StringListType to fix object comparison

bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/RuleEngineImpl.java, bundles/org.openhab.core.io.rest.sitemap/src/main/java/org/openhab/core/io/rest/sitemap/SitemapSubscriptionService.java, bundles/org.openhab.core.model.rule.runtime/src/org/openhab/core/model/rule/runtime/internal/engine/RuleContextHelper.java, bundles/org.openhab.core.ui/src/main/java/org/openhab/core/ui/internal/items/ItemUIRegistryImpl.java, bundles/org.openhab.core/src/main/java/org/openhab/core/common/ThreadPoolManager.java, bundles/org.openhab.core/src/main/java/org/openhab/core/items/dto/ItemDTOMapper.java
- Remove not needed object array creation for logging
=> Remove not needed object array creation for logging

bundles/org.openhab.core.model.core/src/main/java/org/openhab/core/model/core/internal/folder/FolderObserver.java, bundles/org.openhab.core/src/test/java/org/openhab/core/net/HttpServiceUtilTest.java
- Removed usage of org.apache.commons.lang.ArrayUtils
=> Removed usage of org.apache.commons.lang.ArrayUtils

bom/compile/pom.xml, bom/runtime/pom.xml, bundles/org.openhab.core.io.net/src/main/java/org/openhab/core/io/net/exec/ExecUtil.java, bundles/org.openhab.core.io.net/src/test/java/org/openhab/core/io/net/exec/ExecUtilTest.java, features/karaf/openhab-tp/src/main/feature/feature.xml, itests/org.openhab.core.auth.oauth2client.tests/itest.bndrun, itests/org.openhab.core.model.core.tests/itest.bndrun, itests/org.openhab.core.model.item.tests/itest.bndrun, itests/org.openhab.core.model.persistence.tests/itest.bndrun, itests/org.openhab.core.model.rule.tests/itest.bndrun, itests/org.openhab.core.model.script.tests/itest.bndrun, itests/org.openhab.core.model.thing.tests/itest.bndrun
- Removed dependency on `org.apache.commons.exec`
=> Removed dependency on 'org.apache.commons.exec'

pom.xml
Reverts openhab/openhab-core#1303
=> Revert "Enabled 'spotless:check' by default"

bundles/org.openhab.core/src/main/java/org/openhab/core/library/unit/SmartHomeUnits.java
Signed-off-by: Pauli Anttila <pauli.anttila@gmail.com>
=> [units] Added Bq/m³ and ppb units

bundles/org.openhab.core/src/main/java/org/openhab/core/library/unit/SmartHomeUnits.java, bundles/org.openhab.core/src/test/java/org/openhab/core/library/unit/SmartHomeUnitsTest.java
- Small improvements for SmartHomeUnits
=> Small improvements for SmartHomeUnits

bundles/org.openhab.core.config.core/src/main/java/org/openhab/core/config/core/ConfigConstants.java, bundles/org.openhab.core.config.dispatch/src/main/java/org/openhab/core/config/dispatch/internal/ConfigDispatcher.java, bundles/org.openhab.core.config.dispatch/src/main/java/org/openhab/core/config/dispatch/internal/ConfigDispatcherFileWatcher.java
=> fixed default service pid and removed esh traces in service configuration

bundles/org.openhab.core.audio/src/main/java/org/openhab/core/audio/internal/AudioManagerImpl.java, bundles/org.openhab.core.config.discovery/src/main/java/org/openhab/core/config/discovery/internal/AutomaticInboxProcessor.java, bundles/org.openhab.core.io.rest.mdns/src/main/java/org/openhab/core/io/rest/mdns/internal/MDNSAnnouncer.java, bundles/org.openhab.core.io.transport.mqtt/src/main/java/org/openhab/core/io/transport/mqtt/internal/MqttBrokerConnectionServiceInstanceMarker.java, bundles/org.openhab.core.io.transport.mqtt/src/main/java/org/openhab/core/io/transport/mqtt/internal/MqttServiceImpl.java, bundles/org.openhab.core.model.lsp/src/main/java/org/openhab/core/model/lsp/internal/ModelServer.java, bundles/org.openhab.core.model.script/src/org/openhab/core/model/script/internal/RuleHumanLanguageInterpreter.java, bundles/org.openhab.core.persistence/src/main/java/org/openhab/core/persistence/internal/PersistenceServiceRegistryImpl.java, bundles/org.openhab.core.storage.json/src/main/java/org/openhab/core/storage/json/internal/JsonStorageService.java, bundles/org.openhab.core.test.magic/src/main/java/org/openhab/core/magic/binding/internal/automation/modules/MagicMultiActionMarker.java, bundles/org.openhab.core.test.magic/src/main/java/org/openhab/core/magic/binding/internal/automation/modules/MagicSingleActionService.java, bundles/org.openhab.core.test.magic/src/main/java/org/openhab/core/magic/service/MagicMultiInstanceServiceMarker.java, bundles/org.openhab.core.voice/src/main/java/org/openhab/core/voice/internal/VoiceManagerImpl.java, bundles/org.openhab.core/src/main/java/org/openhab/core/internal/i18n/I18nProviderImpl.java
=> fixed service pids

bundles/org.openhab.core.karaf/src/main/java/org/openhab/core/karaf/internal/FeatureInstaller.java, bundles/org.openhab.core.karaf/src/main/resources/OH-INF/config/config.xml
=> removed legacy add-on support

features/karaf/openhab-core/src/main/feature/feature.xml
=> Add auth feature to runtime base

bundles/org.openhab.core.karaf/src/main/java/org/openhab/core/karaf/internal/jaas/ManagedUserRealm.java, features/karaf/openhab-core/src/main/feature/feature.xml
=> Add the Karaf jaas feature as runtime prerequisite

bundles/org.openhab.core/src/main/java/org/openhab/core/storage/Storage.java
- Improved JavaDoc
Closes #1397
=> [storage] Improved JavaDoc

bundles/org.openhab.core.auth.jaas/src/main/java/org/openhab/core/auth/jaas/internal/JaasAuthenticationProvider.java, bundles/org.openhab.core.auth.oauth2client/src/main/java/org/openhab/core/auth/oauth2client/internal/OAuthStoreHandlerImpl.java, bundles/org.openhab.core.auth.oauth2client/src/main/java/org/openhab/core/auth/oauth2client/internal/StorageRecordType.java, bundles/org.openhab.core.automation.module.script/src/main/java/org/openhab/core/automation/module/script/internal/ScriptEngineManagerImpl.java, bundles/org.openhab.core.config.core/src/main/java/org/openhab/core/config/core/status/ConfigStatusSource.java, bundles/org.openhab.core.config.discovery.mdns/src/main/java/org/openhab/core/config/discovery/mdns/internal/MDNSDiscoveryService.java, bundles/org.openhab.core.config.discovery.usbserial/src/main/java/org/openhab/core/config/discovery/usbserial/internal/UsbSerialDiscoveryService.java, bundles/org.openhab.core.io.rest.sse/src/main/java/org/openhab/core/io/rest/sse/SseResource.java, bundles/org.openhab.core.persistence/src/main/java/org/openhab/core/persistence/HistoricItem.java, bundles/org.openhab.core.test.magic/src/main/java/org/openhab/core/magic/binding/handler/MagicThermostatThingHandler.java, bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/internal/CommunicationManager.java, bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/link/ItemChannelLinkRegistry.java, bundles/org.openhab.core.thing/src/test/java/org/openhab/core/thing/type/ThingTypeBuilderTest.java, bundles/org.openhab.core.ui/src/main/java/org/openhab/core/ui/internal/components/UIComponentProvider.java, bundles/org.openhab.core.ui/src/main/java/org/openhab/core/ui/internal/components/UIComponentSitemapProvider.java, bundles/org.openhab.core.ui/src/main/java/org/openhab/core/ui/internal/tiles/TileService.java, bundles/org.openhab.core.ui/src/main/java/org/openhab/core/ui/tiles/ExternalServiceTile.java, bundles/org.openhab.core/src/main/java/org/openhab/core/auth/GenericUser.java, bundles/org.openhab.core/src/main/java/org/openhab/core/auth/UserRegistry.java, bundles/org.openhab.core/src/main/java/org/openhab/core/internal/items/MetadataCommandDescriptionProvider.java, bundles/org.openhab.core/src/main/java/org/openhab/core/internal/items/MetadataStateDescriptionFragmentProvider.java, bundles/org.openhab.core/src/main/java/org/openhab/core/library/types/StringListType.java, bundles/org.openhab.core/src/test/java/org/openhab/core/items/GenericItemTest.java, itests/org.openhab.core.automation.tests/src/main/java/org/openhab/core/automation/event/RuleEventTest.java, itests/org.openhab.core.config.discovery.tests/src/main/java/org/openhab/core/config/discovery/inbox/DynamicThingUpdateOSGiTest.java, itests/org.openhab.core.ephemeris.tests/src/main/java/org/openhab/core/ephemeris/internal/EphemerisManagerImplOSGiTest.java, itests/org.openhab.core.tests/src/main/java/org/openhab/core/internal/items/ItemUpdaterOSGiTest.java, itests/org.openhab.core.thing.tests/src/main/java/org/openhab/core/thing/internal/ChannelStateDescriptionProviderOSGiTest.java, itests/org.openhab.core.thing.tests/src/main/java/org/openhab/core/thing/internal/ThingManagerOSGiJavaTest.java, itests/org.openhab.core.thing.tests/src/main/java/org/openhab/core/thing/internal/ThingRegistryOSGiTest.java
* Add more `@NonNullByDefault` and `@Nullable` annotations
* Remove unnecessary `@NonNull` annotations
* Fix a few other trivial SAT issues
=> Add and fix more null annotations

bundles/org.openhab.core.automation.module.media/src/main/java/org/openhab/core/automation/module/media/internal/MediaScriptScopeProvider.java, bundles/org.openhab.core.automation.module.script.rulesupport/src/main/java/org/openhab/core/automation/module/script/rulesupport/internal/RuleSupportScriptExtension.java, bundles/org.openhab.core.automation.module.script/src/main/java/org/openhab/core/automation/module/script/ScriptExtensionProvider.java, bundles/org.openhab.core.automation.module.script/src/main/java/org/openhab/core/automation/module/script/internal/ScriptExtensionManager.java, bundles/org.openhab.core.automation.module.script/src/main/java/org/openhab/core/automation/module/script/internal/ScriptExtensionManagerWrapper.java, bundles/org.openhab.core.automation.module.script/src/main/java/org/openhab/core/automation/module/script/internal/defaultscope/DefaultScriptScopeProvider.java, bundles/org.openhab.core.automation.module.script/src/main/java/org/openhab/core/automation/module/script/internal/defaultscope/LifecycleScriptExtensionProvider.java
- Added nullness annotations to `ScriptExtensionProvider`
My pending review for #1264 ... and more.
=> Added nullness annotations to 'ScriptExtensionProvider'

bundles/org.openhab.core/src/main/java/org/openhab/core/items/GenericItem.java
=> Fix concurrency issue in state update

bundles/org.openhab.core.io.transport.serial.rxtx/src/main/java/org/openhab/core/io/transport/serial/internal/RxTxPortProvider.java, bundles/org.openhab.core.io.transport.serial/src/main/java/org/openhab/core/io/transport/serial/internal/SerialPortManagerImpl.java, bundles/org.openhab.core.io.transport.serial/src/main/java/org/openhab/core/io/transport/serial/internal/console/SerialCommandExtension.java
- Simplify lifecycle by using constructor injection
=> [serial] Simplify lifecycle by using constructor injection

bom/compile/pom.xml, bom/runtime/pom.xml, bundles/org.openhab.core.io.http.auth/src/main/java/org/openhab/core/io/http/auth/internal/AuthorizePageServlet.java
- Removed dependency on `org.apache.commons.httpclient`
=> Removed dependency on 'org.apache.commons.httpclient'

bundles/org.openhab.core.automation.module.script/src/main/java/org/openhab/core/automation/module/script/internal/defaultscope/DefaultScriptScopeProvider.java, bundles/org.openhab.core.io.console.karaf/src/main/java/org/openhab/core/io/console/karaf/internal/CommandWrapper.java, bundles/org.openhab.core.io.net/src/main/java/org/openhab/core/io/net/http/internal/WebClientFactoryImpl.java, bundles/org.openhab.core.io.transport.mqtt/src/main/java/org/openhab/core/io/transport/mqtt/internal/MqttBrokerConnectionServiceInstance.java, bundles/org.openhab.core.persistence/src/main/java/org/openhab/core/persistence/QueryablePersistenceService.java, bundles/org.openhab.core/src/main/java/org/openhab/core/auth/Role.java, bundles/org.openhab.core/src/main/java/org/openhab/core/auth/client/oauth2/OAuthClientService.java, bundles/org.openhab.core/src/main/java/org/openhab/core/common/ThreadFactoryBuilder.java, bundles/org.openhab.core/src/main/java/org/openhab/core/internal/events/EventHandler.java, bundles/org.openhab.core/src/main/java/org/openhab/core/internal/events/OSGiEventManager.java, bundles/org.openhab.core/src/main/java/org/openhab/core/service/AbstractWatchService.java, bundles/org.openhab.core/src/test/java/org/openhab/core/common/ThreadFactoryBuilderTest.java
=> Removed some ESH leftovers

bundles/org.openhab.core.automation.module.script.rulesupport/src/main/java/org/openhab/core/automation/module/script/rulesupport/shared/ScriptedAutomationManager.java
- Removed INFO logging from `ScriptedAutomationManager#removeAll()` method
=> [automation] Removed INFO logging from 'ScriptedAutomationManager#removeAll()' method

bundles/org.openhab.core.model.lsp/src/main/java/org/openhab/core/model/lsp/internal/MappingUriExtensions.java, bundles/org.openhab.core.model.lsp/src/main/java/org/openhab/core/model/lsp/internal/ModelServer.java
- Simplify lifecycle by using constructor injection
- Minor code improvements
=> [lsp] Simplify lifecycle by using constructor injection

bundles/org.openhab.core.model.item/bnd.bnd, bundles/org.openhab.core.model.lazygen/src/main/java/org/openhab/core/model/lazygen/LazyLanguageConfig.java, bundles/org.openhab.core.model.lazygen/src/main/java/org/openhab/core/model/lazygen/LazyStandaloneSetup.java, bundles/org.openhab.core.model.sitemap/bnd.bnd, bundles/org.openhab.core.model.thing/bnd.bnd
- Removed dependency on `org.apache.commons.logging`
=> Removed dependency on 'org.apache.commons.logging'

bundles/org.openhab.core.io.rest.ui/src/main/java/org/openhab/core/io/rest/ui/TileDTO.java, bundles/org.openhab.core.ui.icon/src/main/java/org/openhab/core/ui/icon/AbstractResourceIconProvider.java, bundles/org.openhab.core.ui.icon/src/main/java/org/openhab/core/ui/icon/IconProvider.java, bundles/org.openhab.core.ui.icon/src/main/java/org/openhab/core/ui/icon/IconSet.java, bundles/org.openhab.core.ui.icon/src/main/java/org/openhab/core/ui/icon/internal/CustomIconProvider.java, bundles/org.openhab.core.ui.icon/src/main/java/org/openhab/core/ui/icon/internal/IconServlet.java, bundles/org.openhab.core.ui.icon/src/test/java/org/openhab/core/ui/icon/AbstractResourceIconProviderTest.java, bundles/org.openhab.core.ui/src/main/java/org/openhab/core/ui/internal/tiles/TileService.java, bundles/org.openhab.core.ui/src/main/java/org/openhab/core/ui/tiles/ExternalServiceTile.java, bundles/org.openhab.core.ui/src/main/java/org/openhab/core/ui/tiles/Tile.java, bundles/org.openhab.core.ui/src/main/java/org/openhab/core/ui/tiles/TileProvider.java
This makes it easier to annotate the Web UI bundles.
=> Annotate icon and tile classes with null annotations

bom/compile/pom.xml, bom/runtime/pom.xml
=> Update BOMs: remove mapdb, add dagger

features/karaf/openhab-tp/src/main/feature/feature.xml
=> Remove openhab.tp-mapdb

bundles/org.openhab.core.automation.rest/src/main/java/org/openhab/core/automation/rest/internal/RuleResource.java, bundles/org.openhab.core.automation.rest/src/main/java/org/openhab/core/automation/rest/internal/dto/EnrichedRuleDTO.java, bundles/org.openhab.core.automation.rest/src/main/java/org/openhab/core/automation/rest/internal/dto/EnrichedRuleDTOMapper.java
This was part of https://github.com/openhab/openhab-core/pull/1451 and has been separated as an independent PR that can already been reviewed and merged independently.
=> Added "editable" info to rules in REST API

bundles/org.openhab.core.automation.module.script/src/main/java/org/openhab/core/automation/module/script/internal/handler/AbstractScriptModuleHandler.java, bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/RuleEngineImpl.java, bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/module/handler/ChannelEventTriggerHandler.java, bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/module/handler/CompareConditionHandler.java, bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/module/handler/DayOfWeekConditionHandler.java, bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/module/handler/GenericCronTriggerHandler.java, bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/module/handler/GenericEventConditionHandler.java, bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/module/handler/GenericEventTriggerHandler.java, bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/module/handler/GroupCommandTriggerHandler.java, bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/module/handler/GroupStateTriggerHandler.java, bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/module/handler/ItemCommandActionHandler.java, bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/module/handler/ItemCommandTriggerHandler.java, bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/module/handler/ItemStateConditionHandler.java, bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/module/handler/ItemStateTriggerHandler.java, bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/module/handler/SystemTriggerHandler.java, bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/module/handler/ThingStatusTriggerHandler.java, bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/module/handler/TimeOfDayConditionHandler.java, bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/module/handler/TimeOfDayTriggerHandler.java
Some other small code clean-ups and improvements.
These changes were done while working on https://github.com/openhab/openhab-core/pull/1451 and extracted as they are functionally unrelated.
=> [automation] Moved constants to top and made them public for reference

bundles/org.openhab.core/src/main/java/org/openhab/core/items/GroupItem.java, bundles/org.openhab.core/src/test/java/org/openhab/core/library/types/ArithmeticGroupFunctionTest.java
- Added few `ArithmeticGroupFunctionTest` unit tests
=> [test] Added few 'ArithmeticGroupFunctionTest' unit tests

bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/module/handler/DayOfWeekConditionHandler.java, bundles/org.openhab.core.io.rest.log/src/main/java/org/openhab/core/io/rest/log/internal/LogHandler.java, bundles/org.openhab.core.model.persistence/src/org/openhab/core/model/persistence/extensions/PersistenceExtensions.java, bundles/org.openhab.core.ui/src/main/java/org/openhab/core/ui/internal/chart/defaultchartprovider/DefaultChartProvider.java, bundles/org.openhab.core/src/test/java/org/openhab/core/library/types/DateTimeTypeTest.java, itests/org.openhab.core.automation.module.timer.tests/src/main/java/org/openhab/core/automation/module/timer/internal/DayOfWeekConditionHandlerTest.java
- Removed `Calendar` leftovers
=> Removed 'Calendar' leftovers

bundles/org.openhab.core/src/main/java/org/openhab/core/internal/scheduler/CronAdjuster.java, bundles/org.openhab.core/src/test/java/org/openhab/core/internal/scheduler/CronAdjusterMiscTest.java, bundles/org.openhab.core/src/test/java/org/openhab/core/internal/scheduler/CronAdjusterTest.java
=> Fix for cron scheduler handling sunday as number

bundles/org.openhab.core.config.discovery/src/main/java/org/openhab/core/config/discovery/AbstractDiscoveryService.java, bundles/org.openhab.core.config.discovery/src/main/java/org/openhab/core/config/discovery/DiscoveryService.java, bundles/org.openhab.core.config.discovery/src/main/java/org/openhab/core/config/discovery/inbox/Inbox.java, bundles/org.openhab.core.config.discovery/src/main/java/org/openhab/core/config/discovery/internal/AutomaticInboxProcessor.java, bundles/org.openhab.core.config.discovery/src/main/java/org/openhab/core/config/discovery/internal/DiscoveryServiceRegistryImpl.java, bundles/org.openhab.core.config.discovery/src/main/java/org/openhab/core/config/discovery/internal/PersistentInbox.java, bundles/org.openhab.core.config.discovery/src/test/java/org/openhab/core/config/discovery/internal/AutomaticInboxProcessorTest.java, bundles/org.openhab.core.config.discovery/src/test/java/org/openhab/core/config/discovery/internal/PersistentInboxTest.java
- Minor clean-ups for discovery
=> [discovery] Minor clean-ups for discovery

bundles/org.openhab.core.model.script/.classpath, bundles/org.openhab.core.model.script/pom.xml, bundles/org.openhab.core.model.script/src.moved/test/java/org/openhab/core/model/script/internal/actions/TimerImplTest.java, bundles/org.openhab.core.model.script/src/org/openhab/core/model/script/internal/actions/TimerImpl.java
- Fixed `TimerImpl` implementation
- Removed superfluous constructor
- Added unit tests
Fixes #1528
=> Fixed TimerImpl and added unit tests

bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/internal/console/LinkConsoleCommandExtension.java
Do you think that something like this is a useful addition?
Edit: Merge conflicts because it's based on an old 2.5 branch to make it work in my production setup.
=> utility for removing orphan links

bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/binding/BaseThingHandlerFactory.java
- Improved `ThingHandlerService` registrations / removals
- Clear map of `ThingHandlerService` on deactivate
- Recursively get implemented interfaces
=> Improved 'ThingHandlerService' registrations / removals

bundles/org.openhab.core.audio/src/main/java/org/openhab/core/audio/internal/AudioConsoleCommandExtension.java, bundles/org.openhab.core.config.discovery/src/main/java/org/openhab/core/config/discovery/internal/console/DiscoveryConsoleCommandExtension.java, bundles/org.openhab.core.config.discovery/src/main/java/org/openhab/core/config/discovery/internal/console/InboxConsoleCommandExtension.java, bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/internal/console/FirmwareUpdateConsoleCommandExtension.java, bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/internal/console/LinkConsoleCommandExtension.java, bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/internal/console/ThingConsoleCommandExtension.java, bundles/org.openhab.core.voice/src/main/java/org/openhab/core/voice/internal/VoiceConsoleCommandExtension.java
- Added nullness annotations and constructor injection for ConsoleCommandExtensions
=> Added nullness annotations and constructor injection for ConsoleCommandExtensions

bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/RuleEngineImpl.java, bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/commands/AutomationCommandEnableRule.java, bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/commands/AutomationCommandList.java, bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/commands/AutomationCommandRemove.java, bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/provider/AbstractResourceBundleProvider.java, bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/provider/file/AbstractFileProvider.java, bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/parser/ParsingException.java, bundles/org.openhab.core.storage.json/src/main/java/org/openhab/core/storage/json/internal/JsonStorage.java, bundles/org.openhab.core.voice/src/main/java/org/openhab/core/voice/text/AbstractRuleBasedInterpreter.java, bundles/org.openhab.core.voice/src/main/java/org/openhab/core/voice/text/ExpressionAlternatives.java, bundles/org.openhab.core/src/test/java/org/openhab/core/internal/scheduler/PeriodicSchedulerImplTest.java
Introduces 'foreach' as a replacement for loops and iterators to make the code more readable.
I suspect that for and foreach will end up compiling the same code, but I think the improved for loop (foreach) is more readable.
=> [Code style] Replace for loops and iterators with for each loops

bundles/org.openhab.core.model.persistence/src/org/openhab/core/model/persistence/extensions/PersistenceExtensions.java
- Avoid `ArithmeticException` if timeSpan is zero
=> [persistence] Avoid 'ArithmeticException' if timeSpan is zero

bundles/org.openhab.core.io.console.eclipse/src/main/java/org/openhab/core/io/console/eclipse/internal/ConsoleSupportEclipse.java, bundles/org.openhab.core.io.console.karaf/src/main/java/org/openhab/core/io/console/karaf/internal/CommandWrapper.java, bundles/org.openhab.core.io.console.rfc147/src/main/java/org/openhab/core/io/console/rfc147/internal/ConsoleSupportRfc147.java, itests/org.openhab.core.auth.oauth2client.tests/README.md
=> Use "openhab" console scope

bundles/org.openhab.core.audio/src/main/java/org/openhab/core/audio/AudioFormat.java, bundles/org.openhab.core.audio/src/test/java/org/openhab/core/audio/internal/AudioFormatTest.java, bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/commands/Printer.java, bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/commands/Utils.java, bundles/org.openhab.core.config.dispatch/src/test/java/org/openhab/core/config/dispatch/internal/ConfigDispatcherFileWatcherTest.java, bundles/org.openhab.core.model.lsp/src/main/java/org/openhab/core/model/lsp/internal/RuntimeServerModule.java, bundles/org.openhab.core.storage.json/src/main/java/org/openhab/core/storage/json/internal/JsonStorageService.java, bundles/org.openhab.core.transform/src/main/java/org/openhab/core/transform/AbstractFileTransformationService.java, bundles/org.openhab.core.ui.icon/src/main/java/org/openhab/core/ui/icon/internal/CustomIconProvider.java, bundles/org.openhab.core/src/main/java/org/openhab/core/library/types/HSBType.java, bundles/org.openhab.core/src/test/java/org/openhab/core/library/types/HSBTypeTest.java, bundles/org.openhab.core/src/test/java/org/openhab/core/library/types/PercentTypeTest.java, bundles/org.openhab.core/src/test/java/org/openhab/core/library/types/QuantityTypeTest.java, itests/org.openhab.core.config.dispatch.tests/src/main/java/org/openhab/core/config/dispatch/internal/ConfigDispatcherOSGiTest.java, itests/org.openhab.core.storage.json.tests/src/main/java/org/openhab/core/storage/json/internal/JsonStorageServiceOSGiTest.java
=> Fix various deprecations

bundles/org.openhab.core.io.rest/src/main/java/org/openhab/core/io/rest/internal/resources/RootResource.java, bundles/org.openhab.core.io.rest/src/main/java/org/openhab/core/io/rest/internal/resources/beans/RootBean.java, bundles/org.openhab.core.io.rest/src/main/java/org/openhab/core/io/rest/internal/resources/beans/SystemInfoBean.java
As suggested in https://github.com/openhab/openhab-core/pull/1570#issuecomment-679013610
=> [rest] added further system information to rest resources

bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/internal/profiles/ProfileCallbackImpl.java, bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/internal/profiles/ProfileTypeRegistryImpl.java, bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/internal/profiles/TriggerProfileTypeImpl.java
- Added missing nullness annotations in profile implementations
=> Added missing nullness annotations in profile implementations

itests/org.openhab.core.thing.tests/src/main/java/org/openhab/core/thing/binding/BindingBaseClassesOSGiTest.java
- Added unit test for unset thing properties
=> Added unit test for unset thing properties

bundles/org.openhab.core.config.discovery/src/main/java/org/openhab/core/config/discovery/inbox/InboxAutoApprovePredicate.java, bundles/org.openhab.core.config.discovery/src/main/java/org/openhab/core/config/discovery/inbox/events/AbstractInboxEvent.java, bundles/org.openhab.core.config.discovery/src/main/java/org/openhab/core/config/discovery/inbox/events/InboxAddedEvent.java, bundles/org.openhab.core.config.discovery/src/main/java/org/openhab/core/config/discovery/inbox/events/InboxEventFactory.java, bundles/org.openhab.core.config.discovery/src/main/java/org/openhab/core/config/discovery/inbox/events/InboxRemovedEvent.java, bundles/org.openhab.core.config.discovery/src/main/java/org/openhab/core/config/discovery/inbox/events/InboxUpdatedEvent.java
- Added missing nullness annotations to discovery events
=> Added missing nullness annotations to discovery events

bundles/org.openhab.core/src/main/java/org/openhab/core/net/NetUtil.java
Related to https://github.com/openhab/openhab-core/issues/1408
=> Remove deprecated NetUtil methods

bundles/org.openhab.core.ui/src/main/java/org/openhab/core/ui/internal/items/ItemUIRegistryImpl.java, bundles/org.openhab.core.ui/src/test/java/org/openhab/core/ui/internal/items/ItemUIRegistryImplTest.java
Fixes https://github.com/openhab/openhab-core/issues/1624
=> cleaned up some null handling

bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/internal/profiles/ProfileCallbackImpl.java, bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/link/ItemChannelLink.java
Also annotates `ItemChannelLink`.
See https://github.com/openhab/openhab-core/pull/1626#issuecomment-688248044
=> Fix potential NPE in ProfileCallbackImpl

bundles/org.openhab.core.karaf/src/main/java/org/openhab/core/karaf/internal/FeatureInstaller.java
* Use Streams for filtering, mapping and checking predicates
* Add exception to warnings/errors when debug logging is enabled
* Use final featuresService field so method arguments can be removed
Fixes #1486
Related to #1617
=> FeatureInstaller improvements

bundles/org.openhab.core.io.rest.auth/src/main/java/org/openhab/core/io/rest/auth/internal/AuthFilter.java
Currently the AuthFilter will try to find a token in the
X-OPENHAB-TOKEN HTTP header - only when it finds a cookie
named X-OPENHAB-AUTH-HEADER. It can cause problems because
browsers or proxies might block the cookie from being sent
for various reasons (for instance if there's a path set
for it).
There is no downside IMHO to always try to fallback to
checking the X-OPENHAB-TOKEN header for a token, if and
only if it's not already provided in the Authorization
header. It is the responsibility of the client to decide
how it wants to authorize the request among the available
options - by checking a cookie, or something else entirely.
Also removed the '?api_key=' option because Swagger UI
doesn't provide tokens that way anymore.
=> [REST/Auth] Always accept tokens in the alt header

bundles/org.openhab.core.automation/src/main/resources/OH-INF/automation/moduletypes/EphemerisConditions.json, bundles/org.openhab.core.automation/src/main/resources/OH-INF/automation/moduletypes/GenericCronTrigger.json, bundles/org.openhab.core.automation/src/main/resources/OH-INF/automation/moduletypes/SystemTriggers.json, bundles/org.openhab.core.automation/src/main/resources/OH-INF/automation/moduletypes/ThingTriggers.json
=> Use consistent capitalization with Conditions, Triggers, Actions

bundles/org.openhab.core.transform/src/main/java/org/openhab/core/transform/AbstractFileTransformationService.java
=> Fix "Unable to watch transformation directory" warnings

bundles/org.openhab.core.model.rule/src/org/openhab/core/model/rule/jvmmodel/RulesRefresher.java
The rules are often not instantiated within 5 seconds.
On a Raspberry Pi 3B it can take 12 seconds before rules are instantiated.
The code has also been improved with proper null annotations.
Related to #1637
=> Increase StartlevelEvent delay to 15 seconds

bundles/org.openhab.core/src/main/java/org/openhab/core/internal/events/EventHandler.java
- Reduced logging level to warn
=> Reduced logging level to warn

bundles/org.openhab.core.io.rest.sitemap/src/main/java/org/openhab/core/io/rest/sitemap/SitemapSubscriptionService.java
=> Fix callback not added to new PageChangeListener

bundles/org.openhab.core.ephemeris/src/main/java/org/openhab/core/ephemeris/internal/EphemerisManagerImpl.java
=> Sort Ephemeris config parameter options

bundles/org.openhab.core.config.xml/src/test/java/com/acme/Product.java, bundles/org.openhab.core.config.xml/src/test/java/org/openhab/core/config/xml/util/XmlDocumentReaderTest.java
=> Fix two typos

bundles/org.openhab.core.model.script/src/org/openhab/core/model/script/actions/Ephemeris.java
- Added action for `isBankHoliday(<file>)`
Closes #1697
=> Added action for 'isBankHoliday(<file>)'

bundles/org.openhab.core.io.rest/src/main/java/org/openhab/core/io/rest/internal/resources/RootResource.java, bundles/org.openhab.core.io.rest/src/main/java/org/openhab/core/io/rest/internal/resources/beans/RootBean.java
Implements https://github.com/openhab/openhab-core/issues/1678
=> [rest] Include measurement system in REST root resource

features/karaf/openhab-tp/src/main/feature/feature.xml
=> Use openhab-addons-deps Maven repository for all Xtext Orbit bundle dependencies

bundles/org.openhab.core.io.net/src/main/java/org/openhab/core/io/net/exec/ExecUtil.java
Signed-off-by: Connor Petty <mistercpp2000+gitsignoff@gmail.com>
=> Fix and cleanup logging in ExecUtil

bundles/org.openhab.core.automation.module.script/src/main/java/org/openhab/core/automation/module/script/internal/provider/ScriptModuleTypeProvider.java
When one of the engines is unset the ScriptModuleTypeProvider clears all parameter options instead of only those that apply to that engine.
This fixes the Nashorn engine missing from the parameter options on the first openHAB startup.
=> Fix ScriptEngine parameter option removal

bundles/org.openhab.core.model.script.runtime/src/org/openhab/core/model/script/runtime/internal/engine/DSLScriptEngine.java
=> Fixed missing item resolution of DSL scripts created through the UI

bom/compile/pom.xml, bom/runtime/pom.xml, features/karaf/openhab-tp/src/main/feature/feature.xml, itests/org.openhab.core.config.discovery.mdns.tests/itest.bndrun
=> upgraded JmDNS to version 3.5.6

bundles/org.openhab.core.automation.module.script/src/main/java/org/openhab/core/automation/module/script/internal/ScriptEngineManagerImpl.java, bundles/org.openhab.core.automation.module.script/src/main/java/org/openhab/core/automation/module/script/internal/provider/ScriptModuleTypeProvider.java, bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/type/ActionType.java, bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/type/ConditionType.java
- Fixed IndexOutOfBoundsException in `ScriptModuleTypeProvider` when supported script types are empty
- Minor improvements / nullness annotiations
```
2020-10-19 12:10:37.351 [ERROR] [penhab.core.automation.module.script] - bundle org.openhab.core.automation.module.script:3.0.0.202010180307 (135)[org.openhab.core.automation.module.script.internal.provider.ScriptModuleTypeProvider(89)] : The setScriptEngineFactory method has thrown an exception
java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
at jdk.internal.util.Preconditions.outOfBounds(Unknown Source) ~[?:?]
at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Unknown Source) ~[?:?]
at jdk.internal.util.Preconditions.checkIndex(Unknown Source) ~[?:?]
at java.util.Objects.checkIndex(Unknown Source) ~[?:?]
at …
```
=> [automation] Fixed IndexOutOfBoundsException in ScriptModuleTypeProvider

bundles/org.openhab.core.automation.module.media/src/main/java/org/openhab/core/automation/module/media/internal/MediaActionTypeProvider.java
- Sort audio sinks for say and playSound actions
Similar to:
https://github.com/openhab/openhab-core/blob/584c85a07f760216b2c42f482a7800bfe064b0d3/bundles/org.openhab.core.audio/src/main/java/org/openhab/core/audio/internal/AudioManagerImpl.java#L296-L299
=> [automation] Sort audio sinks for say and playSound actions

bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/commands/AutomationCommand.java, bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/commands/AutomationCommandsPluggable.java
=> [automation] Added nullness annotations, use ctor injection in ConsoleCommandExtension
