openhab/openhab-core

bundles/org.openhab.core/src/main/java/org/openhab/core/library/items/CallItem.java, bundles/org.openhab.core/src/main/java/org/openhab/core/library/items/ColorItem.java, bundles/org.openhab.core/src/main/java/org/openhab/core/library/items/ContactItem.java, bundles/org.openhab.core/src/main/java/org/openhab/core/library/items/DateTimeItem.java, bundles/org.openhab.core/src/main/java/org/openhab/core/library/items/DimmerItem.java, bundles/org.openhab.core/src/main/java/org/openhab/core/library/items/ImageItem.java, bundles/org.openhab.core/src/main/java/org/openhab/core/library/items/LocationItem.java, bundles/org.openhab.core/src/main/java/org/openhab/core/library/items/NumberItem.java, bundles/org.openhab.core/src/main/java/org/openhab/core/library/items/PlayerItem.java, bundles/org.openhab.core/src/main/java/org/openhab/core/library/items/RollershutterItem.java, bundles/org.openhab.core/src/main/java/org/openhab/core/library/items/StringItem.java, bundles/org.openhab.core/src/main/java/org/openhab/core/library/items/SwitchItem.java
- Replaced static inline declarations by `List.of()` method
- Adds `RefreshType` to accepted commands of CallItem
=> [core] Replaced static inline declarations by List.of() method

bundles/org.openhab.core.io.rest.auth/src/main/java/org/openhab/core/io/rest/auth/internal/TokenResource.java
Fix https://github.com/openhab/openhab-webui/issues/441
=> [REST Auth] Clear session cookie only when deleting own session

bundles/org.openhab.core.model.script.runtime/src/org/openhab/core/model/script/runtime/internal/engine/DSLScriptEngine.java
Fixes https://github.com/openhab/openhab-core/issues/1728
=> [automation] Allow dashes in rule file names

bundles/org.openhab.core.persistence/src/main/java/org/openhab/core/persistence/dto/ItemHistoryDTO.java
Fixes https://github.com/openhab/openhab-core/issues/1781
=> [persistence] strip unit from historic states in DTO

bundles/org.openhab.core.ui/src/main/java/org/openhab/core/ui/internal/chart/defaultchartprovider/DefaultChartProvider.java
Fixes https://github.com/openhab/openhab-core/issues/1781
=> [charts] Added support for QuantityTypes to DefaultChartProvider

bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/internal/link/ItemChannelLinkResource.java, bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/internal/console/LinkConsoleCommandExtension.java, bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/link/AbstractLink.java, bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/link/ItemChannelLink.java, bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/link/ItemChannelLinkRegistry.java
- Print `ItemChannelLink` configuration in output of console commands
- Renamed subcommands to `link` / `unlink`
=> Print 'ItemChannelLink' configuration in output of console commands

bundles/org.openhab.core.io.transport.mqtt/src/main/java/org/openhab/core/io/transport/mqtt/MqttBrokerConnection.java
Some MQTT servers can be quirky, they do not handle Unsubscribe request properly.
In this case we have to omit sending it. Introduce a boolean flag, telling
whether the request should be sent or not, and add a public function to set it.
iRobot built-in MQTT server is known to suffer from this problem.
Signed-off-by: Pavel Fedin <pavel_fedin@mail.ru>
=> transport/mqtt: Introduce setUnsubscribeOnStop() function

bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/module/handler/GroupCommandTriggerHandler.java
Fixes https://github.com/openhab/openhab-core/issues/1793
=> [automation] Fixed NPE when no command is given in a member-of-group trigger

bundles/org.openhab.core/src/main/java/org/openhab/core/library/items/NumberItem.java
Fixes https://github.com/openhab/openhab-addons/issues/9008
=> Do not provide unit information for plain number items

bundles/org.openhab.core.model.rule/src/org/openhab/core/model/rule/jvmmodel/RulesRefresher.java, bundles/org.openhab.core.model.script/src/org/openhab/core/model/script/jvmmodel/ScriptItemRefresher.java
=> Log reason for rules/scripts refresh

bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/internal/ChannelCommandDescriptionProvider.java, bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/internal/ChannelStateDescriptionProvider.java
- Changed comparison from equals() to reference
Fixes https://github.com/openhab/openhab-addons/issues/8845
=> Changed comparison from equals() to reference

bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/internal/item/MetadataSelectorMatcher.java, bundles/org.openhab.core.io.rest.core/src/test/java/org/openhab/core/io/rest/core/internal/item/MetadataSelectorMatcherTest.java
=> [REST] Apply metadata selector regex on all namespaces

bundles/org.openhab.core.model.script.runtime/src/org/openhab/core/model/script/runtime/internal/engine/DSLScriptEngineFactory.java
Fixes https://github.com/openhab/openhab-core/issues/1818
=> [automation] Create separate DSLScriptEngine instance for every handler

bundles/org.openhab.core.audio/src/main/java/org/openhab/core/audio/internal/AudioServlet.java, bundles/org.openhab.core.auth.oauth2client/src/main/java/org/openhab/core/auth/oauth2client/internal/OAuthStoreHandlerImpl.java, bundles/org.openhab.core.automation.module.script.rulesupport/src/main/java/org/openhab/core/automation/module/script/rulesupport/internal/loader/ScriptFileWatcher.java, bundles/org.openhab.core.automation.module.script/src/main/java/org/openhab/core/automation/module/script/internal/provider/ScriptModuleTypeProvider.java, bundles/org.openhab.core.config.core/src/main/java/org/openhab/core/config/core/ConfigUtil.java, bundles/org.openhab.core.config.core/src/main/java/org/openhab/core/config/core/ConfigurationSerializer.java, bundles/org.openhab.core.config.xml/src/main/java/org/openhab/core/config/xml/util/NodeList.java, bundles/org.openhab.core.config.xml/src/main/java/org/openhab/core/config/xml/util/NodeListConverter.java, bundles/org.openhab.core.ephemeris/src/main/java/org/openhab/core/ephemeris/internal/EphemerisManagerImpl.java, bundles/org.openhab.core.io.http.auth/src/main/java/org/openhab/core/io/http/auth/internal/AuthorizePageServlet.java, bundles/org.openhab.core.io.http.auth/src/main/java/org/openhab/core/io/http/auth/internal/ChangePasswordPageServlet.java, bundles/org.openhab.core.io.http.auth/src/main/java/org/openhab/core/io/http/auth/internal/CreateAPITokenPageServlet.java, bundles/org.openhab.core.thing.xml/src/main/java/org/openhab/core/thing/xml/internal/StateDescriptionConverter.java, bundles/org.openhab.core.ui.icon/src/main/java/org/openhab/core/ui/icon/internal/IconServlet.java, bundles/org.openhab.core.ui/src/main/java/org/openhab/core/ui/internal/chart/ChartServlet.java, bundles/org.openhab.core.voice/src/main/java/org/openhab/core/voice/text/AbstractRuleBasedInterpreter.java, bundles/pom.xml, itests/pom.xml, pom.xml
Updates the code for the latest EEAs.
=> Update LastNPE EEAs to 2.2.1

bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/internal/item/ItemResource.java, bundles/org.openhab.core/src/main/java/org/openhab/core/items/ManagedItemProvider.java, bundles/org.openhab.core/src/main/java/org/openhab/core/items/dto/ItemDTOMapper.java
=> Harden item creation by checking for validity of name

bundles/org.openhab.core.model.item/src/org/openhab/core/model/item/internal/GenericItemProvider.java
=> Avoid potential NPE

bundles/org.openhab.core.automation.rest/src/main/java/org/openhab/core/automation/rest/internal/RuleResource.java, bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/internal/thing/ThingResource.java, bundles/org.openhab.core.io.rest.ui/src/main/java/org/openhab/core/io/rest/ui/internal/UIResource.java
The /things, /rules, /ui/components endpoints retrieve all objects
in their entirety, which can become very big, i.e. channels, config
parameters, script rule modules or trees of UI components can
quickly add up to the size.
When the UI simply displays a list of those objects it retrieves all
this extra information but does nothing with it.
This introduces an optional ?summary=true query parameter for the
above resources to limit the output to pre-defined fields which are
deemed most relevant for displaying these lists, omitting the rest.
When the option is not set, the behavior remains unchanged so this
change is not API breaking. The API version has therefore not been
incremented. The client is responsible for adding the option to
retrieve summarized collections instead of the entire …
=> [rest] Add summary option to rules, things, UI components resources

bundles/org.openhab.core.test.magic/src/main/java/org/openhab/core/magic/binding/handler/MagicOnOffLightHandler.java, bundles/org.openhab.core.test.magic/src/main/resources/OH-INF/thing/channel-types.xml, bundles/org.openhab.core.test.magic/src/main/resources/OH-INF/thing/thing-types.xml
=> [magic] Added a trigger channel for easier tests

bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/TriggerHandlerCallbackImpl.java
=> [automation] Make rule engine use a threadpool

bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/type/ChannelTypeBuilder.java
Signed-off-by: Marcel Verpaalen marcel@verpaalen.com
=> Fix typo in TriggerChannelTypeBuilder

bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/RuleEngineImpl.java
Synchonisation happened before for all rules, but only up to checking for the RUNNING status - which means that subsequent executions were already started to enter the codeblock, before the previous execution finished and set the status back to IDLE.
Now the executions are correctly chained, while different rules are executed in parallel.
Fixes https://github.com/openhab/openhab-core/issues/1868
=> [automation] Synchronize the executions of each rule

bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/internal/CommunicationManager.java
I have spent significant time profiling threads, especially the "OH-eventexecutor-1" thread.
The major insight I had was that this thread spent around 90% of its active time creating proxies for the safecaller.
This PR caches the created proxies and thus avoids them being continuously recreated.
It massively reduces the CPU load that is caused by this thread and hardly has any memory impact (on my production system, it ran smoothly for 5 hours and only cached 60 proxies altogether).
Here's the figures from a thread dump of my production system after > 5 hours with that change:
During the 18877 seconds that the thread existed, it only consumes 32.5 seconds CPU time, which shows that it easily handles the load of event dispatching.
This should hopefully also fix …
=> Cache safe call proxies for profiles instead of continuously recreating them

bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/internal/AutoUpdateManager.java, bundles/org.openhab.core.thing/src/test/java/org/openhab/core/thing/internal/AutoUpdateManagerTest.java
=> Disable AutoUpdateManager for GroupItems

bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/RuleEngineImpl.java, bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/TriggerHandlerCallbackImpl.java, bundles/org.openhab.core.model.rule/src/org/openhab/core/model/rule/jvmmodel/RulesRefresher.java
Fixes https://github.com/openhab/openhab-core/issues/1889
Fixes #1887
=> [automation] Reverted the introduction of an automation threadpool

bundles/org.openhab.core.audio/src/main/java/org/openhab/core/audio/internal/AudioServlet.java, bundles/org.openhab.core.automation.module.script/src/main/java/org/openhab/core/automation/module/script/internal/defaultscope/DefaultScriptScopeProvider.java, bundles/org.openhab.core.io.http/src/main/java/org/openhab/core/io/http/internal/OpenHABHttpContext.java, bundles/org.openhab.core.io.http/src/main/java/org/openhab/core/io/http/servlet/BaseOpenHABServlet.java, bundles/org.openhab.core.io.http/src/main/java/org/openhab/core/io/http/servlet/OpenHABBundleServlet.java, bundles/org.openhab.core.io.http/src/main/java/org/openhab/core/io/http/servlet/OpenHABServlet.java, bundles/org.openhab.core.model.script/src/org/openhab/core/model/script/lib/NumberExtensions.java, bundles/org.openhab.core.model.script/src/org/openhab/core/model/script/scoping/ScriptImplicitlyImportedTypes.java, bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/internal/profiles/SystemHysteresisStateProfile.java, bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/internal/profiles/SystemOffsetProfile.java, bundles/org.openhab.core.ui.icon/src/main/java/org/openhab/core/ui/icon/internal/IconServlet.java, bundles/org.openhab.core.ui/src/main/java/org/openhab/core/ui/internal/chart/ChartServlet.java, bundles/org.openhab.core/src/main/java/org/openhab/core/internal/i18n/I18nProviderImpl.java, bundles/org.openhab.core/src/main/java/org/openhab/core/internal/library/unit/UnitInitializer.java, bundles/org.openhab.core/src/main/java/org/openhab/core/library/types/PercentType.java, bundles/org.openhab.core/src/main/java/org/openhab/core/library/types/QuantityType.java, bundles/org.openhab.core/src/main/java/org/openhab/core/library/unit/Units.java, bundles/org.openhab.core/src/main/java/org/openhab/core/types/util/UnitUtils.java, bundles/org.openhab.core/src/test/java/org/openhab/core/library/dimension/VolumetricFlowRateTest.java, bundles/org.openhab.core/src/test/java/org/openhab/core/library/types/PercentTypeTest.java, bundles/org.openhab.core/src/test/java/org/openhab/core/library/types/QuantityTypeTest.java, bundles/org.openhab.core/src/test/java/org/openhab/core/library/unit/UnitsTest.java, bundles/org.openhab.core/src/test/java/org/openhab/core/types/util/UnitUtilsTest.java, itests/org.openhab.core.model.script.tests/src/main/java/org/openhab/core/model/script/engine/ScriptEngineOSGiTest.java, itests/org.openhab.core.model.script.tests/src/main/java/org/openhab/core/model/script/lib/NumberExtensionsTest.java
=> Rename classes with "SmartHome" in their name

bundles/org.openhab.core.semantics/src/main/java/org/openhab/core/semantics/internal/SemanticsMetadataProvider.java, bundles/org.openhab.core.semantics/src/test/java/org/openhab/core/semantics/internal/SemanticsMetadataProviderTest.java
=> Remove semantic metadata on item tag removal

bundles/org.openhab.core/src/main/java/org/openhab/core/util/HexUtils.java, bundles/org.openhab.core/src/test/java/org/openhab/core/util/HexUtilsTest.java
=> HexUtils: fix empty string handling

bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/UID.java, bundles/org.openhab.core/src/main/java/org/openhab/core/service/ReadyMarker.java
=> Update "o.e.sh" references

bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/internal/ChannelLinkNotifier.java, bundles/org.openhab.core/src/main/java/org/openhab/core/common/AbstractUID.java
=> Improve ChannelLinkNotifier.removed and AbstractUID.getAsString performance

bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/internal/link/ItemChannelLinkConfigDescriptionProvider.java, bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/link/ManagedItemChannelLinkProvider.java
=> [link] Use constructor injection

bundles/org.openhab.core.io.http.auth/.classpath, bundles/org.openhab.core.io.http.auth/pages/authorize.html, bundles/org.openhab.core.io.http.auth/src/main/java/org/openhab/core/io/http/auth/internal/AbstractAuthPageServlet.java, bundles/org.openhab.core.io.http.auth/src/main/java/org/openhab/core/io/http/auth/internal/AuthorizePageServlet.java, bundles/org.openhab.core.io.http.auth/src/main/java/org/openhab/core/io/http/auth/internal/ChangePasswordPageServlet.java, bundles/org.openhab.core.io.http.auth/src/main/java/org/openhab/core/io/http/auth/internal/CreateAPITokenPageServlet.java, bundles/org.openhab.core.io.http.auth/src/main/resources/messages.properties, bundles/org.openhab.core.io.http.auth/src/main/resources/messages_fr.properties
This implements localized messages for the authorize, change
password and create API token pages using a resource bundle.
Messages in English & French are included.
=> Auth pages i18n

bundles/org.openhab.core.automation.module.script.rulesupport/src/main/java/org/openhab/core/automation/module/script/rulesupport/internal/loader/ScriptFileWatcher.java, bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/RuleEngineImpl.java, bundles/org.openhab.core/src/main/java/org/openhab/core/service/StartLevelService.java
=> Improved startup logging and avoid scripts being loaded in start level service thread

bundles/org.openhab.core.automation/src/main/resources/OH-INF/automation/moduletypes/SystemTriggers.json
=> [automation] Added config options for start level trigger

bundles/org.openhab.core.model.script.runtime/src/org/openhab/core/model/script/runtime/internal/engine/DSLScriptEngine.java
Fixes https://github.com/openhab/openhab-core/issues/1900
=> [automation] Always set the value of implicit vars

bundles/org.openhab.core.automation/src/main/resources/OH-INF/automation/moduletypes/SystemTriggers.json
=> Fixed SAT issues

bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/internal/discovery/InboxResource.java
=> Fixed Inbox approve API annotation

bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/RuleEngineImpl.java, itests/org.openhab.core.automation.integration.tests/src/main/java/org/openhab/core/automation/integration/test/AutomationIntegrationTest.java
This should fix the flaky integration test.
=> [automation] Stabilized automation integration test

bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/module/handler/SystemTriggerHandler.java
Fixes https://github.com/openhab/openhab-core/issues/1943
=> [automation] Fixed startup rules being triggered more than once

bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/internal/ThingManagerImpl.java
We claim in the start level description that 80 is only reached once thing handlers are initialized - this is the code to actually fulfill this promise.
=> Introduce ready marker to correctly set start level 80

bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/RuleEngineImpl.java
Fixes https://github.com/openhab/openhab-core/issues/1934
=> [automation] Reintroduce delayed rule initialization

bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/util/ThingHandlerHelper.java, itests/org.openhab.core.thing.tests/src/main/java/org/openhab/core/thing/internal/ChannelLinkNotifierOSGiTest.java
- Added nullness annotations to ThingHandlerHelper
=> Added nullness annotations to ThingHandlerHelper

bom/compile/pom.xml, bom/runtime/pom.xml, features/karaf/openhab-tp/src/main/feature/feature.xml, itests/org.openhab.core.binding.xml.tests/itest.bndrun, itests/org.openhab.core.config.discovery.tests/itest.bndrun, itests/org.openhab.core.config.xml.tests/itest.bndrun, itests/org.openhab.core.ephemeris.tests/itest.bndrun, itests/org.openhab.core.model.thing.tests/itest.bndrun, itests/org.openhab.core.thing.tests/itest.bndrun, itests/org.openhab.core.thing.xml.tests/itest.bndrun
For changes, see: https://x-stream.github.io/changes.html
Replaces #1979, #1980
=> Upgrade to XStream 1.4.15

bundles/org.openhab.core/src/main/java/org/openhab/core/internal/items/ExpireManager.java
Fixes #1989
Signed-off-by: Stefan Triller <github@stefantriller.de>
=> Expire group item states

tools/archetype/binding/src/main/resources/archetype-resources/pom.xml, tools/archetype/binding/src/main/resources/archetype-resources/src/main/resources/OH-INF/binding/binding.xml, tools/archetype/binding/src/main/resources/archetype-resources/src/main/resources/OH-INF/thing/thing-types.xml
Fixes openhab/openhab-addons#9528
Signed-off-by: Stefan Triller <github@stefantriller.de>
=> Fix spotless issue in binding archtype

bundles/org.openhab.core/src/main/java/org/openhab/core/common/QueueingThreadPoolExecutor.java
=> Align all threads to naming convention

bundles/org.openhab.core.io.transport.modbus/src/main/java/org/openhab/core/io/transport/modbus/ModbusBitUtilities.java, bundles/org.openhab.core.io.transport.modbus/src/test/java/org/openhab/core/io/transport/modbus/test/BitUtilitiesCommandToRegistersTest.java
=> [transport.modbus] Support dimensionless QuantityType commands.

bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/internal/GsonMessageBodyWriter.java
Fixes https://github.com/openhab/openhab-distro/issues/1188
=> Prevent errors in log when client closes the HTTP connection

bundles/org.openhab.core.transform/src/main/java/org/openhab/core/transform/AbstractFileTransformationService.java
- Added method to read all files with specific extensions in 'transform/' folder
=> [transformation] Added method to read all files with specific extensions in 'transform/' folder

bundles/org.openhab.core.ui/src/main/java/org/openhab/core/ui/internal/items/ItemUIRegistryImpl.java
Fixes https://github.com/openhab/openhab-core/issues/2055
=> Include group label in warn log message

pom.xml, tools/archetype/binding/src/main/resources/archetype-resources/src/main/feature/feature.xml
See openhab/openhab-addons#9620
=> [skeleton] Remove license header from feature.xml

itests/org.openhab.core.automation.integration.tests/src/main/java/org/openhab/core/automation/integration/test/AutomationIntegrationJsonTest.java, itests/org.openhab.core.automation.module.core.tests/itest.bndrun, itests/org.openhab.core.automation.module.core.tests/src/main/java/org/openhab/core/automation/internal/module/RunRuleModuleTest.java, itests/org.openhab.core.automation.module.core.tests/src/main/java/org/openhab/core/automation/internal/module/RuntimeRuleTest.java, itests/org.openhab.core.automation.module.timer.tests/itest.bndrun, itests/org.openhab.core.automation.module.timer.tests/src/main/java/org/openhab/core/automation/module/timer/internal/BasicConditionHandlerTest.java, itests/org.openhab.core.automation.module.timer.tests/src/main/java/org/openhab/core/automation/module/timer/internal/RuntimeRuleTest.java, itests/org.openhab.core.automation.tests/itest.bndrun, itests/org.openhab.core.automation.tests/src/main/java/org/openhab/core/automation/event/RuleEventTest.java
Fixes #1633
Fixes #1955
Fixes #2080
=> Fix unstable tests due to RuleEngine not being started

bundles/org.openhab.core.io.transport.modbus/src/main/java/org/openhab/core/io/transport/modbus/internal/pooling/ModbusSlaveConnectionFactoryImpl.java
https://community.openhab.org/t/modbus-errors/114602
Signed-off-by: Michael Parment <michael.parment@gmail.com>
=> Changed modbus polling logging level to warning when retrying

bom/runtime/pom.xml, features/karaf/openhab-tp/src/main/feature/feature.xml
Fixes #2140
Signed-off-by: Stefan Triller <github@stefantriller.de>
=> Bump apache.commons.net to 3.7.2

bundles/org.openhab.core.model.script/src.moved/test/java/org/openhab/core/model/script/internal/actions/TimerImplTest.java, bundles/org.openhab.core.model.script/src/org/openhab/core/model/script/internal/actions/TimerImpl.java
=> [timer] Fix to allow timer reschedule after termination

bundles/org.openhab.core.automation.module.script.rulesupport/src/main/java/org/openhab/core/automation/module/script/rulesupport/internal/loader/DependencyTracker.java, bundles/org.openhab.core.automation.module.script.rulesupport/src/main/java/org/openhab/core/automation/module/script/rulesupport/internal/loader/ScriptLibraryWatcher.java, bundles/org.openhab.core.automation.module.script.rulesupport/src/main/java/org/openhab/core/automation/module/script/rulesupport/internal/loader/collection/BidiSetBag.java, bundles/org.openhab.core.automation.module.script/src/main/java/org/openhab/core/automation/module/script/ScriptDependencyListener.java
Caused by https://github.com/openhab/openhab-core/pull/1884.
=> Fix build by updating license headers

bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/util/ReferenceResolver.java, bundles/org.openhab.core.io.net/src/main/java/org/openhab/core/io/net/http/HttpUtil.java, bundles/org.openhab.core.io.net/src/main/java/org/openhab/core/io/net/http/internal/WebClientFactoryImpl.java, bundles/org.openhab.core.ui/src/main/java/org/openhab/core/ui/internal/proxy/AsyncProxyServlet.java, bundles/org.openhab.core.ui/src/main/java/org/openhab/core/ui/internal/proxy/BlockingProxyServlet.java, bundles/org.openhab.core.ui/src/main/java/org/openhab/core/ui/internal/proxy/ProxyServletService.java, bundles/org.openhab.core.ui/src/test/java/org/openhab/core/ui/internal/proxy/ProxyServletServiceTest.java, bundles/org.openhab.core/src/main/java/org/openhab/core/internal/items/ItemUpdater.java, bundles/org.openhab.core/src/test/java/org/openhab/core/common/osgi/ResourceBundleClassLoaderTest.java, itests/org.openhab.core.config.dispatch.tests/src/main/java/org/openhab/core/config/dispatch/internal/ConfigDispatcherOSGiTest.java
Let's fix these deprecations before they get removed one day.
=> Fix deprecations

bundles/org.openhab.core.io.transport.modbus/src/main/java/org/openhab/core/io/transport/modbus/ModbusRegisterArray.java
=> [modbus] equals and hashcode implementation for ModbusRegisterArray

bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/module/handler/CompareConditionHandler.java, bundles/org.openhab.core/src/main/java/org/openhab/core/types/TypeParser.java
- Added nullness annotations to `TypeParser`
---
Related to https://github.com/openhab/openhab-addons/pull/10068
=> Added nullness annotations to TypeParser

itests/org.openhab.core.auth.oauth2client.tests/itest.bndrun, itests/org.openhab.core.automation.integration.tests/itest.bndrun, itests/org.openhab.core.automation.module.core.tests/itest.bndrun, itests/org.openhab.core.automation.module.script.tests/itest.bndrun, itests/org.openhab.core.automation.module.timer.tests/itest.bndrun, itests/org.openhab.core.automation.tests/itest.bndrun, itests/org.openhab.core.binding.xml.tests/itest.bndrun, itests/org.openhab.core.config.core.tests/itest.bndrun, itests/org.openhab.core.config.discovery.mdns.tests/itest.bndrun, itests/org.openhab.core.config.discovery.tests/itest.bndrun, itests/org.openhab.core.config.discovery.usbserial.linuxsysfs.tests/itest.bndrun, itests/org.openhab.core.config.discovery.usbserial.tests/itest.bndrun, itests/org.openhab.core.config.dispatch.tests/itest.bndrun, itests/org.openhab.core.config.xml.tests/itest.bndrun, itests/org.openhab.core.ephemeris.tests/itest.bndrun, itests/org.openhab.core.io.rest.core.tests/itest.bndrun, itests/org.openhab.core.model.core.tests/itest.bndrun, itests/org.openhab.core.model.item.tests/itest.bndrun, itests/org.openhab.core.model.rule.tests/itest.bndrun, itests/org.openhab.core.model.script.tests/itest.bndrun, itests/org.openhab.core.model.thing.tests/itest.bndrun, itests/org.openhab.core.storage.json.tests/itest.bndrun, itests/org.openhab.core.tests/itest.bndrun, itests/org.openhab.core.thing.tests/itest.bndrun, itests/org.openhab.core.thing.xml.tests/itest.bndrun, itests/org.openhab.core.voice.tests/itest.bndrun, pom.xml
See: https://github.com/bndtools/bnd/wiki/Changes-in-5.3.0
Fixes https://github.com/openhab/openhab-core/issues/2134
=> Update bnd to 5.3.0

bom/runtime/pom.xml
Fixes https://github.com/openhab/openhab-core/issues/2236
=> Update outdated group id for ANTLR

bundles/org.openhab.core.automation.module.script.rulesupport/src/main/java/org/openhab/core/automation/module/script/rulesupport/internal/loader/ScriptFileReference.java, bundles/org.openhab.core.automation.module.script.rulesupport/src/test/java/org/openhab/core/automation/module/script/rulesupport/internal/loader/DelegatingScheduledExecutorService.java
Removed Jetbrains annotations which were accidentally introduced in #2222. 
=> Remove Jetbrains @NonNull annotations

tools/archetype/binding/src/main/resources/archetype-resources/src/main/resources/OH-INF/i18n/__bindingId___xx.properties
=> [skeleton] Change locale placeholder from xx_XX to xx

bom/runtime/pom.xml, features/karaf/openhab-tp/src/main/feature/feature.xml
Fixes https://github.com/openhab/openhab-core/issues/2273
=> Upgrade org.apache.servicemix.specs.activation-api-1.2.1 to fix mail sending

bundles/org.openhab.core.thing/src/main/resources/OH-INF/i18n/DefaultSystemChannels_fr.properties
=> French translation added for signal strength options

itests/org.openhab.core.io.rest.core.tests/src/main/java/org/openhab/core/io/rest/core/internal/item/ItemResourceOSGiTest.java
-Fixed JsonParser deprecations
=> Fixed JsonParser deprecations

bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/internal/link/ItemChannelLinkResource.java, bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/link/EnrichedItemChannelLinkDTO.java, bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/link/EnrichedItemChannelLinkDTOMapper.java, itests/org.openhab.core.io.rest.core.tests/src/main/java/org/openhab/core/io/rest/core/internal/link/ItemChannelLinkResourceOSGiTest.java
- Added editable flag for `ItemChannelLinks` by introducing an `EnrichedItemChannelLinkDTO`
Closes #2317 
=> [REST] Added editable flag for ItemChannelLinks by introducing an EnrichedItemChannelLinkDTO

bundles/org.openhab.core.thing/src/main/resources/OH-INF/i18n/DefaultSystemChannels.properties
=> Fix typo in DefaultSystemChannels

bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/CommonTriggerEvents.java, bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/events/AbstractThingRegistryEvent.java, bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/events/ChannelTriggeredEvent.java, bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/events/ThingAddedEvent.java, bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/events/ThingEventFactory.java, bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/events/ThingRemovedEvent.java, bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/events/ThingStatusInfoChangedEvent.java, bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/events/ThingStatusInfoEvent.java, bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/events/ThingUpdatedEvent.java, bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/firmware/FirmwareEventFactory.java, bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/internal/console/ThingConsoleCommandExtension.java, bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/link/events/AbstractItemChannelLinkRegistryEvent.java, bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/link/events/ItemChannelLinkAddedEvent.java, bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/link/events/ItemChannelLinkRemovedEvent.java, bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/link/events/LinkEventFactory.java, bundles/org.openhab.core.thing/src/test/java/org/openhab/core/thing/events/ThingEventFactoryTest.java, bundles/org.openhab.core.thing/src/test/java/org/openhab/core/thing/firmware/FirmwareEventFactoryTest.java
- Added nullness annotations to Thing events
- Minor code imporvements
- Moved `ThingEventFactoryTest` from itest to unit test folder
=> Added nullness annotations to Thing events

bundles/org.openhab.core.config.discovery/src/main/java/org/openhab/core/config/discovery/internal/PersistentInbox.java, bundles/org.openhab.core.config.discovery/src/test/java/org/openhab/core/config/discovery/internal/PersistentInboxTest.java
Build of the new thing UID corrected in case newThingId is provided
Fix #2331
=> [inbox] Approval with newThingId: only one segment allowed

bom/runtime/pom.xml
=> Update runtime BOM for hivemq-mqtt-client upgrade

bundles/org.openhab.core.automation.module.script.rulesupport/src/main/java/org/openhab/core/automation/module/script/rulesupport/internal/loader/ScriptFileWatcher.java, bundles/org.openhab.core.automation.module.script.rulesupport/src/test/java/org/openhab/core/automation/module/script/rulesupport/internal/loader/ScriptFileWatcherTest.java, bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/provider/AutomationResourceBundlesEventQueue.java, bundles/org.openhab.core.io.rest.auth/src/main/java/org/openhab/core/io/rest/auth/internal/AuthFilter.java, bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/internal/PlainMessageBodyReader.java, bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/link/EnrichedItemChannelLinkDTO.java, bundles/org.openhab.core.io.transport.modbus/src/test/java/org/openhab/core/io/transport/modbus/test/IntegrationTestSupport.java, bundles/org.openhab.core.io.transport.modbus/src/test/java/org/openhab/core/io/transport/modbus/test/SmokeTest.java, bundles/org.openhab.core.persistence/src/test/java/org/openhab/core/persistence/extensions/TestPersistenceService.java, bundles/org.openhab.core.test/src/main/java/org/openhab/core/test/java/JavaTest.java, bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/internal/ChannelCommandDescriptionProvider.java, bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/internal/ChannelStateDescriptionProvider.java, bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/internal/ThingManagerImpl.java, bundles/org.openhab.core.ui.icon/src/main/java/org/openhab/core/ui/icon/internal/IconServlet.java, bundles/org.openhab.core.ui/src/main/java/org/openhab/core/ui/internal/proxy/BlockingProxyServlet.java, bundles/org.openhab.core/src/main/java/org/openhab/core/internal/events/ThreadedEventHandler.java, bundles/org.openhab.core/src/test/java/org/openhab/core/internal/items/ItemStateConverterImplTest.java, itests/org.openhab.core.automation.integration.tests/src/main/java/org/openhab/core/automation/integration/test/AutomationIntegrationTest.java, itests/org.openhab.core.tests/src/main/java/org/openhab/core/internal/common/SafeCallerImplTest.java, tools/static-code-analysis/checkstyle/suppressions.xml
=> Fix more SAT findings and add a few suppressions

bundles/org.openhab.core.test.magic/src/main/java/org/openhab/core/magic/binding/handler/MagicOnOffLightHandler.java, bundles/org.openhab.core.test.magic/src/main/resources/OH-INF/thing/channel-types.xml, bundles/org.openhab.core.test.magic/src/main/resources/OH-INF/thing/thing-types.xml
- Added Channel for DateTime Item
=> [magic] Added Channel for DateTime Item

bundles/org.openhab.core/src/test/java/org/openhab/core/internal/scheduler/CronSchedulerImplTest.java
This test would often fail when the system is under load.
Fixes #1242
=> Fix unstable CronSchedulerImplTest

bundles/org.openhab.core/src/main/java/org/openhab/core/library/types/QuantityType.java, bundles/org.openhab.core/src/test/java/org/openhab/core/internal/items/ItemStateConverterImplTest.java, bundles/org.openhab.core/src/test/java/org/openhab/core/library/types/QuantityTypeArithmeticGroupFunctionTest.java, bundles/org.openhab.core/src/test/java/org/openhab/core/library/types/QuantityTypeTest.java
=> Fix decimal separator issues when creating QuantityType from String

bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/internal/discovery/InboxResource.java
Related to openhab/openhab-webui#1035
=> [REST] inbox/approve: new response code 400

bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/internal/CommunicationManager.java
- Log warning (instead of debug) if profile cannot be created e.g. if there is a spelling mistake in the *.items file
=> [profiles] Log warning if profile cannot be created

bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/internal/profiles/SystemProfileFactory.java, bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/internal/profiles/TimestampTriggerProfile.java, bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/profiles/SystemProfiles.java, bundles/org.openhab.core.thing/src/main/resources/OH-INF/i18n/SystemProfiles.properties, bundles/org.openhab.core.thing/src/test/java/org/openhab/core/thing/internal/profiles/TimestampTriggerProfileTest.java, itests/org.openhab.core.thing.tests/src/main/java/org/openhab/core/thing/internal/profiles/SystemProfileFactoryOSGiTest.java
- Added Timestamp on Trigger Profile
This Profile updates the State of an DateTime Item to now each time the Channel is triggered.
=> Added "timestamp-trigger" Profile

bundles/org.openhab.core.automation.module.script/src/main/java/org/openhab/core/automation/module/script/internal/defaultscope/ScriptBusEvent.java, bundles/org.openhab.core/src/main/java/org/openhab/core/events/EventPublisher.java, bundles/org.openhab.core/src/main/java/org/openhab/core/events/TopicEventFilter.java, bundles/org.openhab.core/src/main/java/org/openhab/core/internal/events/OSGiEventPublisher.java, bundles/org.openhab.core/src/main/java/org/openhab/core/items/events/AbstractItemEventSubscriber.java, bundles/org.openhab.core/src/main/java/org/openhab/core/items/events/AbstractItemRegistryEvent.java, bundles/org.openhab.core/src/main/java/org/openhab/core/items/events/ItemAddedEvent.java, bundles/org.openhab.core/src/main/java/org/openhab/core/items/events/ItemEventFactory.java, bundles/org.openhab.core/src/main/java/org/openhab/core/items/events/ItemRemovedEvent.java, bundles/org.openhab.core/src/main/java/org/openhab/core/items/events/ItemUpdatedEvent.java, bundles/org.openhab.core/src/test/java/org/openhab/core/events/AbstractEventFactoryTest.java, bundles/org.openhab.core/src/test/java/org/openhab/core/items/events/ItemEventFactoryTest.java, itests/org.openhab.core.automation.module.core.tests/src/main/java/org/openhab/core/automation/internal/module/RuntimeRuleTest.java, itests/org.openhab.core.tests/src/main/java/org/openhab/core/internal/events/OSGiEventManagerOSGiTest.java
- Added nullness annotations to Item events
=> Added nullness annotations to Item events

bom/compile/pom.xml, bom/runtime/pom.xml, features/karaf/openhab-tp/src/main/feature/feature.xml, itests/org.openhab.core.config.discovery.mdns.tests/itest.bndrun
=> Update to new JmDNS release 3.5.7

bom/compile/pom.xml, bom/runtime/pom.xml, features/karaf/openhab-tp/src/main/feature/feature.xml
Fixes https://github.com/openhab/openhab-core/issues/1886
Fixes https://github.com/openhab/openhab-core/issues/2223
=> upgrade to JUPnP 2.6.0

bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/module/handler/EphemerisConditionHandler.java
This PR fixes the ephemeris offset which does not presently work.
Discussed in [this community post](https://community.openhab.org/t/ephemeris-condition-with-offset-not-working-in-rules-in-oh-3-1-0m5/123088/3?u=cossey)
=> [automation] Ephemeris Offset fix

bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/internal/item/ItemResource.java, itests/org.openhab.core.io.rest.core.tests/src/main/java/org/openhab/core/io/rest/core/internal/item/ItemResourceOSGiTest.java
Replaces https://github.com/openhab/openhab-core/pull/2397
Fixes #2252
=> Fix links to group members in REST response

bundles/org.openhab.core.id/src/main/java/org/openhab/core/id/internal/UUIDResource.java
Implements https://github.com/openhab/openhab-core/issues/2350
=> Make UUID available to users

bundles/org.openhab.core.automation.module.script.rulesupport/src/main/java/org/openhab/core/automation/module/script/rulesupport/internal/loader/DependencyTracker.java, bundles/org.openhab.core.automation.module.script.rulesupport/src/main/java/org/openhab/core/automation/module/script/rulesupport/internal/loader/ScriptFileWatcher.java, bundles/org.openhab.core.automation.module.script.rulesupport/src/main/java/org/openhab/core/automation/module/script/rulesupport/internal/loader/ScriptLibraryWatcher.java
Reverts openhab/openhab-core#2408
=> Revert "[automation] Ignore relative lib directories for scripts"

bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/DefaultSystemChannelTypeProvider.java
=> Add semantics to default system channel types

bundles/org.openhab.core/src/main/resources/OH-INF/i18n/network_it.properties
Signed-off-by: Carmine Gianni <carmixdev@gmail.com>
=> Corrected a typo

bundles/org.openhab.core.automation.module.script.rulesupport/src/main/java/org/openhab/core/automation/module/script/rulesupport/shared/ScriptedAutomationManager.java
=> [automation] Fix missing configuration in rules

bundles/org.openhab.core.automation.module.script.rulesupport/src/main/java/org/openhab/core/automation/module/script/rulesupport/internal/loader/ScriptLibraryWatcher.java
=> [automation] make ScriptLibraryWatcher accessible for other languages

bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/internal/link/ItemChannelLinkResource.java, bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/internal/thing/ThingResource.java, bundles/org.openhab.core.io.rest.ui/src/main/java/org/openhab/core/io/rest/ui/internal/UIResource.java
=> [REST] Fix few content types

bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/internal/item/ItemResource.java
=> [REST] Handle IP v6 in X-Forwarded-Host header

bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/thing/EnrichedThingDTO.java, bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/thing/EnrichedThingDTOMapper.java, bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/dto/AbstractThingDTO.java
=> Help OpenAPI to infer EnrichedThingDTO model channels type as a list of EnrichedChannelDTOs

bundles/org.openhab.core.addon.marketplace/src/main/java/org/openhab/core/addon/marketplace/internal/community/CommunityRuleTemplateAddonHandler.java, bundles/org.openhab.core.addon.marketplace/src/main/java/org/openhab/core/addon/marketplace/internal/community/CommunityUIWidgetAddonHandler.java
These changes resolve all the null analysis errors found in this bundle.
=> Fix null analysis errors in marketplace bundle

bundles/org.openhab.core.addon.marketplace/src/main/java/org/openhab/core/addon/marketplace/internal/community/CommunityMarketplaceAddonService.java, bundles/org.openhab.core.addon.sample/src/main/java/org/openhab/core/addon/sample/internal/SampleAddonService.java, bundles/org.openhab.core.karaf/src/main/java/org/openhab/core/karaf/internal/KarafAddonService.java, bundles/org.openhab.core/src/main/java/org/openhab/core/addon/Addon.java
=> replace multi-parameter constructor with builder on org.openhab.core.Addon

bundles/org.openhab.core.audio/src/main/java/org/openhab/core/audio/internal/AudioServlet.java, bundles/org.openhab.core.audio/src/main/java/org/openhab/core/audio/internal/javasound/JavaSoundAudioSink.java, bundles/org.openhab.core.auth.oauth2client/src/main/java/org/openhab/core/auth/oauth2client/internal/OAuthStoreHandlerImpl.java, bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/RuleEngineImpl.java, bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/commands/AutomationCommandRemove.java, bundles/org.openhab.core.config.discovery/src/main/java/org/openhab/core/config/discovery/AbstractDiscoveryService.java, bundles/org.openhab.core.io.console.karaf/src/main/java/org/openhab/core/io/console/karaf/internal/ConsoleSupportKaraf.java, bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/internal/addons/AddonResource.java, bundles/org.openhab.core.io.transport.modbus/src/main/java/org/openhab/core/io/transport/modbus/BitArray.java, bundles/org.openhab.core.model.lsp/src/main/java/org/openhab/core/model/lsp/internal/RegistryProvider.java, bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/binding/BaseThingHandler.java, bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/internal/ThingManagerImpl.java, bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/internal/profiles/SystemHysteresisStateProfile.java, bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/internal/profiles/SystemOffsetProfile.java, bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/internal/profiles/SystemRangeStateProfile.java, bundles/org.openhab.core.voice/src/main/java/org/openhab/core/voice/text/AbstractRuleBasedInterpreter.java, bundles/org.openhab.core/src/main/java/org/openhab/core/internal/types/StateDescriptionFragmentImpl.java, bundles/org.openhab.core/src/main/java/org/openhab/core/library/types/QuantityType.java, bundles/org.openhab.core/src/main/java/org/openhab/core/service/WatchQueueReader.java, bundles/org.openhab.core/src/test/java/org/openhab/core/library/types/QuantityTypeTest.java, itests/org.openhab.core.auth.oauth2client.tests/src/main/java/org/openhab/core/auth/oauth2client/test/internal/AuthorizationCodeTestAgent.java, itests/org.openhab.core.auth.oauth2client.tests/src/main/java/org/openhab/core/auth/oauth2client/test/internal/ResourceOwnerTestAgent.java, itests/org.openhab.core.tests/src/main/java/org/openhab/core/items/ItemRegistryImplTest.java
Newer PMD versions discover more CompareObjectsWithEquals findings.
Related to https://github.com/openhab/static-code-analysis/pull/423
=> Fix/suppress PMD CompareObjectsWithEquals findings

bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/internal/item/ItemResource.java, itests/org.openhab.core.io.rest.core.tests/src/main/java/org/openhab/core/io/rest/core/internal/item/ItemResourceOSGiTest.java
Add option to skip members, e.g. if the goal of the request to just get the metadata of a group item
=> Align item endpoint with items endpoint

README.md
=> Added GHA build badge

.github/scripts/maven-build, .github/workflows/ci-build.yml
* Checkout merged branches for pull requests
* Echo the mvn command used for builds
* Use more functions in maven-build so it is similar to what will be used for add-on builds
=> GitHub Actions workflow improvements

bundles/org.openhab.core.test.magic/src/main/java/org/openhab/core/magic/binding/MagicBindingConstants.java, bundles/org.openhab.core.test.magic/src/main/java/org/openhab/core/magic/binding/handler/MagicButtonHandler.java, bundles/org.openhab.core.test.magic/src/main/java/org/openhab/core/magic/binding/handler/MagicRollershutterHandler.java, bundles/org.openhab.core.test.magic/src/main/java/org/openhab/core/magic/binding/handler/MagicThermostatThingHandler.java, bundles/org.openhab.core.test.magic/src/main/java/org/openhab/core/magic/binding/internal/MagicHandlerFactory.java, bundles/org.openhab.core.test.magic/src/main/resources/OH-INF/i18n/magic.properties, bundles/org.openhab.core.test.magic/src/main/resources/OH-INF/i18n/magic_de.properties, bundles/org.openhab.core.test.magic/src/main/resources/OH-INF/i18n/magic_en.properties, bundles/org.openhab.core.test.magic/src/main/resources/OH-INF/thing/channel-types.xml, bundles/org.openhab.core.test.magic/src/main/resources/OH-INF/thing/thing-types.xml
- Added Magic Button triggering some events every 5 seconds
- Minor improvements
=> [test] Added Magic Button triggering some events every 5 seconds

bom/compile/pom.xml, bom/runtime/pom.xml, features/karaf/openhab-tp/src/main/feature/feature.xml, itests/org.openhab.core.auth.oauth2client.tests/itest.bndrun, itests/org.openhab.core.automation.integration.tests/itest.bndrun, itests/org.openhab.core.automation.module.core.tests/itest.bndrun, itests/org.openhab.core.automation.module.script.tests/itest.bndrun, itests/org.openhab.core.automation.module.timer.tests/itest.bndrun, itests/org.openhab.core.automation.tests/itest.bndrun, itests/org.openhab.core.binding.xml.tests/itest.bndrun, itests/org.openhab.core.config.core.tests/itest.bndrun, itests/org.openhab.core.config.discovery.mdns.tests/itest.bndrun, itests/org.openhab.core.config.discovery.tests/itest.bndrun, itests/org.openhab.core.config.discovery.usbserial.linuxsysfs.tests/itest.bndrun, itests/org.openhab.core.config.discovery.usbserial.tests/itest.bndrun, itests/org.openhab.core.config.dispatch.tests/itest.bndrun, itests/org.openhab.core.config.xml.tests/itest.bndrun, itests/org.openhab.core.ephemeris.tests/itest.bndrun, itests/org.openhab.core.io.rest.core.tests/itest.bndrun, itests/org.openhab.core.model.core.tests/itest.bndrun, itests/org.openhab.core.model.item.tests/itest.bndrun, itests/org.openhab.core.model.rule.tests/itest.bndrun, itests/org.openhab.core.model.script.tests/itest.bndrun, itests/org.openhab.core.model.thing.tests/itest.bndrun, itests/org.openhab.core.storage.json.tests/itest.bndrun, itests/org.openhab.core.tests/itest.bndrun, itests/org.openhab.core.thing.tests/itest.bndrun, itests/org.openhab.core.thing.xml.tests/itest.bndrun, itests/org.openhab.core.voice.tests/itest.bndrun
This provides mostly bug fixes and more units, see:
https://github.com/unitsofmeasurement/si-units/milestone/15?closed=1
Depends on https://github.com/openhab/openhab-osgiify/pull/29
=> Upgrade UoM dependencies

itests/org.openhab.core.auth.oauth2client.tests/itest.bndrun, itests/org.openhab.core.automation.integration.tests/itest.bndrun, itests/org.openhab.core.automation.module.core.tests/itest.bndrun, itests/org.openhab.core.automation.module.script.tests/itest.bndrun, itests/org.openhab.core.automation.module.timer.tests/itest.bndrun, itests/org.openhab.core.automation.tests/itest.bndrun, itests/org.openhab.core.binding.xml.tests/itest.bndrun, itests/org.openhab.core.config.core.tests/itest.bndrun, itests/org.openhab.core.config.discovery.mdns.tests/itest.bndrun, itests/org.openhab.core.config.discovery.tests/itest.bndrun, itests/org.openhab.core.config.discovery.usbserial.linuxsysfs.tests/itest.bndrun, itests/org.openhab.core.config.discovery.usbserial.tests/itest.bndrun, itests/org.openhab.core.config.dispatch.tests/itest.bndrun, itests/org.openhab.core.config.xml.tests/itest.bndrun, itests/org.openhab.core.ephemeris.tests/itest.bndrun, itests/org.openhab.core.io.rest.core.tests/itest.bndrun, itests/org.openhab.core.model.core.tests/itest.bndrun, itests/org.openhab.core.model.item.tests/itest.bndrun, itests/org.openhab.core.model.rule.tests/itest.bndrun, itests/org.openhab.core.model.script.tests/itest.bndrun, itests/org.openhab.core.model.thing.tests/itest.bndrun, itests/org.openhab.core.storage.json.tests/itest.bndrun, itests/org.openhab.core.tests/itest.bndrun, itests/org.openhab.core.thing.tests/itest.bndrun, itests/org.openhab.core.thing.xml.tests/itest.bndrun, itests/org.openhab.core.voice.tests/itest.bndrun, pom.xml
https://github.com/bndtools/bnd/wiki/Changes-in-6.1.0
=> Update bnd to 6.1.0

bundles/org.openhab.core.ui.icon/src/main/java/org/openhab/core/ui/icon/internal/IconServlet.java
=> Fix IllegalStateException in IconServlet

bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/handler/TriggerHandlerCallback.java, bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/RuleEngineImpl.java, bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/TriggerHandlerCallbackImpl.java, bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/module/handler/ChannelEventTriggerHandler.java, bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/module/handler/TimeOfDayTriggerHandler.java, bundles/org.openhab.core/src/main/java/org/openhab/core/scheduler/SchedulerRunnable.java
- Added nullness anotations to `ChannelEventTriggerHandler` and related classes
=> Added nullness anotations to ChannelEventTriggerHandler

bundles/org.openhab.core.model.script/src/org/openhab/core/model/script/actions/Timer.java, bundles/org.openhab.core.model.script/src/org/openhab/core/model/script/internal/actions/TimerImpl.java
- Added nullness anotations to `TimerImpl` and synchronize reschedule method
=> Added nullness anotations to TimerImpl and synchronize reschedule method

bundles/org.openhab.core.addon.marketplace.karaf/src/main/java/org/openhab/core/addon/marketplace/karaf/internal/community/CommunityKarafAddonHandler.java, bundles/org.openhab.core.addon.marketplace/.classpath, bundles/org.openhab.core.addon.marketplace/src/main/java/org/openhab/core/addon/marketplace/MarketplaceAddonHandler.java, bundles/org.openhab.core.addon.marketplace/src/main/java/org/openhab/core/addon/marketplace/internal/community/CommunityMarketplaceAddonService.java, bundles/org.openhab.core.addon.marketplace/src/main/java/org/openhab/core/addon/marketplace/internal/community/model/DiscourseCategoryResponseDTO.java, bundles/org.openhab.core.addon.marketplace/src/main/java/org/openhab/core/addon/marketplace/internal/community/model/DiscourseTopicResponseDTO.java, bundles/org.openhab.core.addon.marketplace/src/main/java/org/openhab/core/addon/marketplace/internal/json/JsonAddonService.java, bundles/org.openhab.core.addon.marketplace/src/main/resources/OH-INF/config/marketplace.xml, bundles/org.openhab.core.addon.marketplace/src/main/resources/OH-INF/i18n/marketplace.properties, bundles/org.openhab.core/src/main/java/org/openhab/core/addon/Addon.java, bundles/org.openhab.core/src/main/java/org/openhab/core/addon/AddonEvent.java, bundles/org.openhab.core/src/main/java/org/openhab/core/addon/AddonEventFactory.java, bundles/org.openhab.core/src/main/java/org/openhab/core/addon/AddonService.java, bundles/org.openhab.core/src/main/java/org/openhab/core/addon/AddonType.java
- Added nullness annotations to Addon related classes (except for the `Addon` itself)
- Added translations for marketplace bundles
- add resources to classpath
=> Added nullness annotations to Addon related classes

bom/runtime/pom.xml, itests/org.openhab.core.auth.oauth2client.tests/itest.bndrun, itests/org.openhab.core.automation.integration.tests/itest.bndrun, itests/org.openhab.core.automation.module.core.tests/itest.bndrun, itests/org.openhab.core.automation.module.script.tests/itest.bndrun, itests/org.openhab.core.automation.module.timer.tests/itest.bndrun, itests/org.openhab.core.automation.tests/itest.bndrun, itests/org.openhab.core.binding.xml.tests/itest.bndrun, itests/org.openhab.core.config.core.tests/itest.bndrun, itests/org.openhab.core.config.discovery.mdns.tests/itest.bndrun, itests/org.openhab.core.config.discovery.tests/itest.bndrun, itests/org.openhab.core.config.discovery.usbserial.linuxsysfs.tests/itest.bndrun, itests/org.openhab.core.config.discovery.usbserial.tests/itest.bndrun, itests/org.openhab.core.config.dispatch.tests/itest.bndrun, itests/org.openhab.core.config.xml.tests/itest.bndrun, itests/org.openhab.core.ephemeris.tests/itest.bndrun, itests/org.openhab.core.io.rest.core.tests/itest.bndrun, itests/org.openhab.core.model.core.tests/itest.bndrun, itests/org.openhab.core.model.item.tests/itest.bndrun, itests/org.openhab.core.model.rule.tests/itest.bndrun, itests/org.openhab.core.model.script.tests/itest.bndrun, itests/org.openhab.core.model.thing.tests/itest.bndrun, itests/org.openhab.core.storage.json.tests/itest.bndrun, itests/org.openhab.core.tests/itest.bndrun, itests/org.openhab.core.thing.tests/itest.bndrun, itests/org.openhab.core.thing.xml.tests/itest.bndrun, itests/org.openhab.core.voice.tests/itest.bndrun, pom.xml
* Syncs dependencies with Karaf 4.3.4
* Resolves itest runbundles for these new dependencies
---
Related to openhab/openhab-distro#1344
=> Upgrade to Karaf 4.3.4

bundles/org.openhab.core.model.script/src.moved/test/java/org/openhab/core/model/script/lib/NumberExtensionsTest.java, bundles/org.openhab.core/src/main/java/org/openhab/core/library/types/DecimalType.java, bundles/org.openhab.core/src/main/java/org/openhab/core/library/types/HSBType.java, bundles/org.openhab.core/src/main/java/org/openhab/core/library/types/PercentType.java, bundles/org.openhab.core/src/main/java/org/openhab/core/library/types/QuantityType.java, bundles/org.openhab.core/src/test/java/org/openhab/core/library/unit/UnitsTest.java
- Use static BigDecimal values
=> Use static BigDecimal values

bundles/org.openhab.core.io.net/src/main/java/org/openhab/core/io/net/http/ExtensibleTrustManager.java, bundles/org.openhab.core.io.net/src/main/java/org/openhab/core/io/net/http/HttpClientInitializationException.java, bundles/org.openhab.core.io.net/src/main/java/org/openhab/core/io/net/http/TrustAllTrustManager.java, bundles/org.openhab.core.io.net/src/main/java/org/openhab/core/io/net/http/internal/ExtensibleTrustManagerImpl.java
- Added nullness annotatios to io.net.http
=> Added nullness annotations to io.net.http

bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/ChannelGroupUID.java
Signed-off-by: Jacob Laursen <jacob@vindvejr.dk>
=> ChannelGroupUID constructor: Fix parameter description (Javadoc)

bundles/org.openhab.core.config.discovery.upnp/src/main/java/org/openhab/core/config/discovery/upnp/internal/UpnpDiscoveryService.java
=> [upnp] Use constructor injection

bundles/org.openhab.core.config.discovery.mdns/src/main/java/org/openhab/core/config/discovery/mdns/internal/MDNSDiscoveryService.java, itests/org.openhab.core.config.discovery.mdns.tests/src/main/java/org/openhab/core/config/discovery/mdns/internal/MDNSDiscoveryServiceOSGiTest.java
-Replaced `Runnable` by lambda expression and minor improvements
=> [mdns] Replaced Runnable by lambda expression

features/karaf/openhab-tp/src/main/feature/feature.xml
Reverts openhab/openhab-core#2634
=> Revert "Bump netty to 4.1.72.Final for log4j2 2.15.0 fix"

bundles/org.openhab.core.config.discovery.mdns/src/main/java/org/openhab/core/config/discovery/mdns/internal/MDNSDiscoveryService.java, itests/org.openhab.core.config.discovery.mdns.tests/itest.bndrun, itests/org.openhab.core.config.discovery.mdns.tests/src/main/java/org/openhab/core/config/discovery/mdns/internal/MDNSDiscoveryServiceOSGiTest.java
- Cancel removal task on manual scan
=> [mdns] Cancel removal task on manual scan

bundles/org.openhab.core.io.net/src/main/java/org/openhab/core/io/net/http/internal/WebClientFactoryImpl.java
This allows to use an HTTP proxy by using java Standard properties (http.proxyhost/https.proxyhost & proxyport).
This is extremely useful for debugging the development of new bindings, and also when direct internet connectivity is not available on the network.
Signed-off-by: LAFOIS Benjamin <benjamin.lafois@gmail.com>
=> allow the use of an HTTP proxy

bundles/org.openhab.core.io.http.auth/.classpath
This prevents local changes whenever you update this Maven project in Eclipse.
=> Update org.openhab.core.io.http.auth .classpath

bom/runtime/pom.xml, itests/org.openhab.core.auth.oauth2client.tests/itest.bndrun, itests/org.openhab.core.automation.integration.tests/itest.bndrun, itests/org.openhab.core.automation.module.core.tests/itest.bndrun, itests/org.openhab.core.automation.module.script.tests/itest.bndrun, itests/org.openhab.core.automation.module.timer.tests/itest.bndrun, itests/org.openhab.core.automation.tests/itest.bndrun, itests/org.openhab.core.binding.xml.tests/itest.bndrun, itests/org.openhab.core.config.core.tests/itest.bndrun, itests/org.openhab.core.config.discovery.mdns.tests/itest.bndrun, itests/org.openhab.core.config.discovery.tests/itest.bndrun, itests/org.openhab.core.config.discovery.usbserial.linuxsysfs.tests/itest.bndrun, itests/org.openhab.core.config.discovery.usbserial.tests/itest.bndrun, itests/org.openhab.core.config.dispatch.tests/itest.bndrun, itests/org.openhab.core.config.xml.tests/itest.bndrun, itests/org.openhab.core.ephemeris.tests/itest.bndrun, itests/org.openhab.core.io.rest.core.tests/itest.bndrun, itests/org.openhab.core.model.core.tests/itest.bndrun, itests/org.openhab.core.model.item.tests/itest.bndrun, itests/org.openhab.core.model.rule.tests/itest.bndrun, itests/org.openhab.core.model.script.tests/itest.bndrun, itests/org.openhab.core.model.thing.tests/itest.bndrun, itests/org.openhab.core.storage.json.tests/itest.bndrun, itests/org.openhab.core.tests/itest.bndrun, itests/org.openhab.core.thing.tests/itest.bndrun, itests/org.openhab.core.thing.xml.tests/itest.bndrun, itests/org.openhab.core.voice.tests/itest.bndrun, pom.xml
* Syncs dependencies with Karaf 4.3.6
* Resolves itest runbundles for these new dependencies
---
Related to openhab/openhab-distro#1363
=> Upgrade to Karaf 4.3.6

bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/internal/ThingManagerImpl.java
=> add log message with validation errors for things

bundles/org.openhab.core.voice/src/main/java/org/openhab/core/voice/internal/VoiceManagerImpl.java
=> [voice] Fix getSTT

bundles/org.openhab.core.addon.marketplace/src/main/java/org/openhab/core/addon/marketplace/internal/community/CommunityMarketplaceAddonService.java, bundles/org.openhab.core.addon.marketplace/src/main/java/org/openhab/core/addon/marketplace/internal/json/JsonAddonService.java
- Fixed NPE and exception while parsing config value
Closes #2687
=> Fix NPE and exception while parsing config value

bundles/org.openhab.core.voice/src/main/java/org/openhab/core/voice/internal/DialogProcessor.java, bundles/org.openhab.core.voice/src/main/java/org/openhab/core/voice/internal/VoiceConsoleCommandExtension.java
=> [voice] Minor changes requested during review of PR #2693

bundles/org.openhab.core.config.core/src/main/java/org/openhab/core/config/core/internal/validation/ConfigDescriptionParameterValidator.java, bundles/org.openhab.core.config.core/src/main/java/org/openhab/core/config/core/internal/validation/ConfigDescriptionParameterValidatorFactory.java, bundles/org.openhab.core.config.core/src/main/java/org/openhab/core/config/core/internal/validation/ConfigDescriptionValidatorImpl.java, bundles/org.openhab.core.config.core/src/main/java/org/openhab/core/config/core/internal/validation/MessageKey.java, bundles/org.openhab.core.config.core/src/main/java/org/openhab/core/config/core/internal/validation/MinMaxValidator.java, bundles/org.openhab.core.config.core/src/main/java/org/openhab/core/config/core/internal/validation/PatternValidator.java, bundles/org.openhab.core.config.core/src/main/java/org/openhab/core/config/core/internal/validation/RequiredValidator.java, bundles/org.openhab.core.config.core/src/main/java/org/openhab/core/config/core/internal/validation/TypeIntrospections.java, bundles/org.openhab.core.config.core/src/main/java/org/openhab/core/config/core/internal/validation/TypeValidator.java, bundles/org.openhab.core.config.core/src/main/java/org/openhab/core/config/core/validation/ConfigDescriptionValidator.java, bundles/org.openhab.core.config.core/src/test/java/org/openhab/core/config/core/internal/validation/ConfigDescriptionValidatorTest.java, bundles/org.openhab.core.config.core/src/test/java/org/openhab/core/config/core/internal/validation/ConfigValidationExceptionTest.java, bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/internal/ThingManagerImpl.java
- Added nullness annotations to config validation
=> [config] Add nullness annotations to config validation

bundles/org.openhab.core.voice/src/main/java/org/openhab/core/voice/internal/text/StandardInterpreter.java
I have added the rules for es locale.
=> [StandardInterpreter] add Spanish language

bundles/org.openhab.core.automation.module.script.rulesupport/src/main/java/org/openhab/core/automation/module/script/rulesupport/loader/ScriptFileWatcher.java, bundles/org.openhab.core.config.dispatch/src/main/java/org/openhab/core/config/dispatch/internal/ConfigDispatcherFileWatcher.java, bundles/org.openhab.core.config.dispatch/src/test/java/org/openhab/core/config/dispatch/internal/ConfigDispatcherFileWatcherTest.java, bundles/org.openhab.core.model.core/src/main/java/org/openhab/core/model/core/internal/folder/FolderObserver.java, bundles/org.openhab.core/src/main/java/org/openhab/core/service/AbstractWatchService.java, bundles/org.openhab.core/src/main/java/org/openhab/core/service/WatchQueueReader.java, itests/org.openhab.core.tests/src/test/java/service/AbstractWatchServiceTest.java
Fixes #2466
Also adds null-annotations.
=> allow multiple listeners for same directory in WatchService

bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/binding/BaseThingHandler.java, itests/org.openhab.core.thing.tests/src/main/java/org/openhab/core/thing/binding/BindingBaseClassesOSGiTest.java
Fixes #2623 
Since it only extends the allowed parameters to be @Nullable, I don't think it will cause any downstream-problems.
=> fix removal of thing properties (single and bulk)

bundles/org.openhab.core.storage.json/src/main/java/org/openhab/core/storage/json/internal/JsonStorage.java
=> Prevent JsonStorage backup corruption when disk is full

bundles/org.openhab.core.io.rest/src/main/java/org/openhab/core/io/rest/internal/resources/SystemInfoResource.java, bundles/org.openhab.core.io.rest/src/main/java/org/openhab/core/io/rest/internal/resources/beans/SystemInfoBean.java, bundles/org.openhab.core/src/main/java/org/openhab/core/service/StartLevelService.java
=> [rest] show start level in /systeminfo

bundles/org.openhab.core/src/main/java/org/openhab/core/library/unit/ImperialUnits.java, bundles/org.openhab.core/src/test/java/org/openhab/core/library/unit/UnitsTest.java
https://en.wikipedia.org/wiki/Pound_per_square_inch
=> Add new Imperial Pressure unit psi

bundles/org.openhab.core.io.rest.voice/src/main/java/org/openhab/core/io/rest/voice/internal/VoiceResource.java
=> [voice] New REST API to start/stop dialog processing

bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/commands/CommandlineModuleTypeProvider.java, bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/commands/CommandlineRuleImporter.java, bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/commands/CommandlineTemplateProvider.java, bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/thingsupport/AnnotatedThingActionModuleTypeProvider.java, bundles/org.openhab.core.config.discovery/src/test/java/org/openhab/core/config/discovery/internal/AutomaticInboxProcessorTest.java, bundles/org.openhab.core.io.rest.auth/src/main/java/org/openhab/core/io/rest/auth/internal/JwtHelper.java, bundles/org.openhab.core.io.transport.modbus/src/test/java/org/openhab/core/io/transport/modbus/test/BitUtilitiesCommandToRegistersTest.java, bundles/org.openhab.core.io.transport.modbus/src/test/java/org/openhab/core/io/transport/modbus/test/IntegrationTestSupport.java, bundles/org.openhab.core.io.transport.modbus/src/test/java/org/openhab/core/io/transport/modbus/test/SmokeTest.java, bundles/org.openhab.core.storage.json/src/test/java/org/openhab/core/storage/json/internal/JsonStorageTest.java, itests/org.openhab.core.config.discovery.tests/src/main/java/org/openhab/core/config/discovery/DiscoveryServiceMock.java, itests/org.openhab.core.config.discovery.tests/src/main/java/org/openhab/core/config/discovery/DiscoveryServiceMockOfBridge.java, itests/org.openhab.core.model.core.tests/src/main/java/org/openhab/core/model/core/internal/folder/FolderObserverTest.java, itests/org.openhab.core.thing.tests/src/main/java/org/openhab/core/thing/firmware/Constants.java, itests/org.openhab.core.thing.tests/src/main/java/org/openhab/core/thing/internal/ThingManagerOSGiJavaTest.java, itests/org.openhab.core.thing.tests/src/main/java/org/openhab/core/thing/internal/firmware/FirmwareUpdateServiceTest.java
This fixes all 36 AvoidThrowingRawExceptionTypes SAT findings.
=> Avoid throwing raw exception types

bundles/org.openhab.core.storage.json/src/main/java/org/openhab/core/storage/json/internal/JsonStorageService.java
=> Flush old JsonStorage to file before recreating a new one

bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/internal/item/ItemResource.java, bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/internal/item/MetadataSelectorMatcher.java
- Improve metadata query parameter description
Closes #2715 
=> [rest] Improve metadata query parameter description

bundles/org.openhab.core.model.script/src/org/openhab/core/model/script/actions/Voice.java, bundles/org.openhab.core.model.script/src/org/openhab/core/model/script/internal/engine/action/VoiceActionService.java
=> [rule] New actions to start/stop dialog processing

bundles/org.openhab.core.io.http.auth/src/main/java/org/openhab/core/io/http/auth/internal/AbstractAuthPageServlet.java, bundles/org.openhab.core.io.http.auth/src/main/java/org/openhab/core/io/http/auth/internal/AuthorizePageServlet.java, bundles/org.openhab.core.io.http.auth/src/main/java/org/openhab/core/io/http/auth/internal/ChangePasswordPageServlet.java, bundles/org.openhab.core.io.http.auth/src/main/java/org/openhab/core/io/http/auth/internal/CreateAPITokenPageServlet.java, bundles/org.openhab.core.io.rest.auth/src/main/java/org/openhab/core/io/rest/auth/internal/AuthFilter.java
=> Log the remote address of failed login attempts

bundles/org.openhab.core.karaf/pom.xml, features/karaf/openhab-tp/src/main/feature/feature.xml
=> Fix missing feature for Karaf log bundle

.github/workflows/ci-build.yml
Fixes that the wrong build step was made conditional in #2817.
It should conditionally add annotations.
=> Correct GHA build step condition

bundles/org.openhab.core.voice/src/main/java/org/openhab/core/voice/internal/VoiceConsoleCommandExtension.java
=> [voice] New console commands to list the voice services

bundles/org.openhab.core.config.discovery/src/main/java/org/openhab/core/config/discovery/internal/PersistentInbox.java, bundles/org.openhab.core.config.discovery/src/test/java/org/openhab/core/config/discovery/internal/PersistentInboxTest.java
=> Fix PersistentInbox tries to update unmanaged things

bundles/org.openhab.core.voice/src/main/java/org/openhab/core/voice/internal/text/StandardInterpreter.java
Use "imperatif" grammatical mode for commands
=> [standardinterpreter] Update french syntax

bundles/org.openhab.core.persistence/src/test/java/org/openhab/core/persistence/extensions/PersistenceExtensionsTest.java
Fixes #2834 
Fixes #2081 
Explanation: see #2834
=> [test] Fix PersistenceExtensionTest

bundles/org.openhab.core.karaf/pom.xml, bundles/org.openhab.core.karaf/src/main/java/org/openhab/core/karaf/internal/FeatureInstaller.java
Fixes #2571 
I can't test it, though (I was not able to reproduce the issue). Is there an easy way to reproduce the problem? @lolodomo I can provide instructions for a test, if you can reproduce it.
=> Fix exception during startup when kar is not yet loaded

bundles/org.openhab.core.config.core/src/main/java/org/openhab/core/config/core/internal/validation/OptionsValidator.java, bundles/org.openhab.core.config.core/src/test/java/org/openhab/core/config/core/internal/validation/ConfigDescriptionValidatorTest.java
=> Fix config validation for decimal parameters with limited options

bundles/org.openhab.core.model.script.runtime/src/org/openhab/core/model/script/runtime/internal/engine/ScriptImpl.java
=> Fix typo in ScriptImpl exception message

bundles/org.openhab.core.addon.marketplace.karaf/src/main/java/org/openhab/core/addon/marketplace/karaf/internal/community/CommunityKarafAddonHandler.java, bundles/org.openhab.core.addon.marketplace/src/main/java/org/openhab/core/addon/marketplace/AbstractRemoteAddonService.java, bundles/org.openhab.core.addon.marketplace/src/main/java/org/openhab/core/addon/marketplace/MarketplaceAddonHandler.java, bundles/org.openhab.core.addon.marketplace/src/main/java/org/openhab/core/addon/marketplace/internal/community/CommunityBundleAddonHandler.java, bundles/org.openhab.core.addon.marketplace/src/test/java/org/openhab/core/addon/test/AbstractRemoteAddonServiceTest.java, bundles/org.openhab.core.addon.marketplace/src/test/java/org/openhab/core/addon/test/TestAddonHandler.java
=> Fix ServiceException when add-on handlers are not fully initialized

bundles/org.openhab.core.addon.marketplace/src/main/java/org/openhab/core/addon/marketplace/BundleVersion.java
Fixes a few SAT findings in the BundleVersion class.
=> Cleanup BundleVersion

bundles/org.openhab.core/src/test/java/org/openhab/core/internal/scheduler/PeriodicSchedulerImplTest.java
Fixes #2848 
See discussion in the issue.
=> Increase allowed deviation in PeriodicSchedulerImplTest

bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/internal/persistence/PersistenceResource.java
- Improve description of REST API for deleting data from persistence
=> [rest] Improve description of REST API for deleting data from persistence

bundles/org.openhab.core.io.rest.sitemap/src/main/java/org/openhab/core/io/rest/sitemap/internal/SitemapResource.java, bundles/org.openhab.core.io.rest.sitemap/src/main/java/org/openhab/core/io/rest/sitemap/internal/WidgetDTO.java, bundles/org.openhab.core.model.sitemap/src/org/openhab/core/model/sitemap/Sitemap.xtext, bundles/org.openhab.core.ui/src/main/java/org/openhab/core/ui/internal/components/UIComponentSitemapProvider.java
This is part of implementing #2185
=> Implement "forceAsItem" functionality for Charts in sitemaps

bundles/org.openhab.core/src/test/java/org/openhab/core/internal/common/SafeCallerImplTest.java
Failed to to unnecessary stubbing exception in https://ci.openhab.org/job/PR-openHAB-Core/4556/
Also removes unnecessary code.
=> Improve SaferCallerImplTest

bundles/org.openhab.core.io.transport.modbus/src/main/java/org/openhab/core/io/transport/modbus/endpoint/EndpointPoolConfiguration.java, bundles/org.openhab.core.io.transport.modbus/src/main/java/org/openhab/core/io/transport/modbus/internal/pooling/ModbusSlaveConnectionFactoryImpl.java
An attempt to build base to solve Huawei SDongle issues defined in #2926.
=> [modbus] Add configurable after connection delay.

bundles/org.openhab.core.automation.module.script/src/main/java/org/openhab/core/automation/module/script/ScriptTransformationService.java
=> Properly close script engines in script transformation

bundles/org.openhab.core.audio/src/main/java/org/openhab/core/audio/internal/javasound/JavaSoundAudioSource.java, bundles/org.openhab.core.automation.module.script/src/main/java/org/openhab/core/automation/module/script/ScriptTransformationService.java, bundles/org.openhab.core.automation.module.script/src/test/java/org/openhab/core/automation/module/script/ScriptTransformationServiceTest.java
=> Fix a few SAT findings

bundles/org.openhab.core.transform/src/main/java/org/openhab/core/transform/FileTransformationConfigurationProvider.java
The `isRegularFile` check fails for `DELETE` events. As a result deleted files where not removed from the registry.
=> Fix transformations not removed if file deleted

bundles/org.openhab.core.io.transport.modbus/src/main/java/org/openhab/core/io/transport/modbus/internal/pooling/ModbusSlaveConnectionFactoryImpl.java
Fixes #2434  
Reduce log-levels as discussed on the forum (linked in issue).
=> Reduce levels of modbus connection logger

bundles/org.openhab.core.io.transport.mqtt/src/main/java/org/openhab/core/io/transport/mqtt/MqttBrokerConnection.java
=> Fix MQTT status message when disconnected while connecting

bundles/org.openhab.core.model.script/src/org/openhab/core/model/script/actions/Voice.java
Also replace "dialog" by "dialogue"
=> Fix interpret actions description

bundles/org.openhab.core.model.item/src/org/openhab/core/model/item/internal/GenericItemProvider.java, bundles/org.openhab.core.model.item/src/org/openhab/core/model/item/internal/GenericMetadataProvider.java, itests/org.openhab.core.model.item.tests/src/main/java/org/openhab/core/model/item/internal/GenericMetadataProviderTest.java
=> Fix namespace "channel" is added to item metadata

bundles/org.openhab.core.io.rest.voice/src/main/java/org/openhab/core/io/rest/voice/internal/VoiceResource.java, bundles/org.openhab.core.model.script/src/org/openhab/core/model/script/actions/Voice.java, bundles/org.openhab.core.voice/src/main/java/org/openhab/core/voice/VoiceManager.java, bundles/org.openhab.core.voice/src/main/java/org/openhab/core/voice/internal/DialogProcessor.java, bundles/org.openhab.core.voice/src/main/java/org/openhab/core/voice/internal/VoiceConsoleCommandExtension.java, bundles/org.openhab.core.voice/src/main/java/org/openhab/core/voice/internal/VoiceManagerImpl.java, itests/org.openhab.core.voice.tests/src/main/java/org/openhab/core/voice/internal/VoiceManagerImplTest.java
=> [voice] Add voice parameter to startDialog and listenAndAnswer

bom/compile/pom.xml, bom/runtime/pom.xml, features/karaf/openhab-tp/src/main/feature/feature.xml
=> Bump JuPNP to 2.6.1

bundles/org.openhab.core.voice/src/main/java/org/openhab/core/voice/internal/VoiceManagerImpl.java, itests/org.openhab.core.voice.tests/src/main/java/org/openhab/core/voice/internal/VoiceManagerImplTest.java
This revert a change in the behavior introduced in https://github.com/openhab/openhab-core/pull/2976.
=> [voice] fix try all interpreters

bundles/org.openhab.core.ui/src/main/java/org/openhab/core/ui/internal/items/ItemUIRegistryImpl.java
Reported on the forum. Also some code-cleanup.
=> Fix NPE in ItemUIRegistry

itests/org.openhab.core.auth.oauth2client.tests/itest.bndrun, itests/org.openhab.core.automation.integration.tests/itest.bndrun, itests/org.openhab.core.automation.module.core.tests/itest.bndrun, itests/org.openhab.core.automation.module.script.tests/itest.bndrun, itests/org.openhab.core.automation.module.timer.tests/itest.bndrun, itests/org.openhab.core.automation.tests/itest.bndrun, itests/org.openhab.core.binding.xml.tests/itest.bndrun, itests/org.openhab.core.config.core.tests/itest.bndrun, itests/org.openhab.core.config.discovery.mdns.tests/itest.bndrun, itests/org.openhab.core.config.discovery.tests/itest.bndrun, itests/org.openhab.core.config.discovery.usbserial.linuxsysfs.tests/itest.bndrun, itests/org.openhab.core.config.discovery.usbserial.tests/itest.bndrun, itests/org.openhab.core.config.dispatch.tests/itest.bndrun, itests/org.openhab.core.config.xml.tests/itest.bndrun, itests/org.openhab.core.ephemeris.tests/itest.bndrun, itests/org.openhab.core.io.rest.core.tests/itest.bndrun, itests/org.openhab.core.model.core.tests/itest.bndrun, itests/org.openhab.core.model.item.tests/itest.bndrun, itests/org.openhab.core.model.rule.tests/itest.bndrun, itests/org.openhab.core.model.script.tests/itest.bndrun, itests/org.openhab.core.model.thing.tests/itest.bndrun, itests/org.openhab.core.storage.json.tests/itest.bndrun, itests/org.openhab.core.tests/itest.bndrun, itests/org.openhab.core.thing.tests/itest.bndrun, itests/org.openhab.core.thing.xml.tests/itest.bndrun, itests/org.openhab.core.voice.tests/itest.bndrun, pom.xml
=> Bump bnd to 6.3.0

bundles/org.openhab.core.ui/src/main/java/org/openhab/core/ui/internal/items/ItemUIRegistryImpl.java, bundles/org.openhab.core.ui/src/test/java/org/openhab/core/ui/internal/items/ItemUIRegistryImplTest.java
Closes openhab/openhab-webui#1298
=> [sitemap] Allow default color condition for labelcolor and valuecolor

bundles/org.openhab.core.io.rest.sitemap/src/main/java/org/openhab/core/io/rest/sitemap/internal/SitemapResource.java, bundles/org.openhab.core.io.rest.sitemap/src/main/java/org/openhab/core/io/rest/sitemap/internal/WidgetDTO.java, bundles/org.openhab.core.model.sitemap/src/org/openhab/core/model/sitemap/Sitemap.xtext, bundles/org.openhab.core.ui/src/main/java/org/openhab/core/ui/chart/ChartProvider.java, bundles/org.openhab.core.ui/src/main/java/org/openhab/core/ui/internal/chart/ChartServlet.java, bundles/org.openhab.core.ui/src/main/java/org/openhab/core/ui/internal/chart/defaultchartprovider/DefaultChartProvider.java
=> Add option for formatting the y-axis labels in charts

bundles/org.openhab.core.persistence/src/main/java/org/openhab/core/persistence/extensions/PersistenceExtensions.java, bundles/org.openhab.core.persistence/src/test/java/org/openhab/core/persistence/extensions/PersistenceExtensionsTest.java
=> Extend PersistenceExtensions with "between" methods

bundles/org.openhab.core.storage.json/src/main/java/org/openhab/core/storage/json/internal/JsonStorageService.java, bundles/org.openhab.core.storage.json/src/main/java/org/openhab/core/storage/json/internal/migration/BridgeImplTypeMigrator.java, bundles/org.openhab.core.storage.json/src/main/java/org/openhab/core/storage/json/internal/migration/ThingImplTypeMigrator.java, bundles/org.openhab.core.storage.json/src/test/java/org/openhab/core/storage/json/internal/ThingStorageEntityMigratorTest.java, bundles/org.openhab.core.storage.json/src/test/resources/thingMigration-input.json, bundles/org.openhab.core.storage.json/src/test/resources/thingMigration-result.json, bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/ManagedThingProvider.java, bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/internal/ThingStorageEntity.java, bundles/org.openhab.core.thing/src/test/java/org/openhab/core/thing/ManagedThingProviderTest.java, itests/org.openhab.core.storage.json.tests/itest.bndrun, itests/org.openhab.core.storage.json.tests/src/main/java/org/openhab/core/storage/json/internal/ThingMigrationOSGiTest.java, itests/org.openhab.core.storage.json.tests/src/main/resources/org.openhab.core.thing.Thing.json, itests/org.openhab.core.thing.tests/src/main/java/org/openhab/core/thing/binding/ChangeThingTypeOSGiTest.java
Fixes #731
#719 should be reverted in another PR.
=> Use ThingStorageEntity instead of ThingImpl/BridgeImpl for storage

bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/internal/ThingManagerImpl.java, bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/internal/ThingRegistryImpl.java, bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/internal/ThingTracker.java, bundles/org.openhab.core.thing/src/test/java/org/openhab/core/thing/internal/ThingManagerImplTest.java
Fixes #1463 
Depends on #2939 (for tests)
Also code clean-up.
=> Refactor thing update handling of ThingManagerImpl

bundles/org.openhab.core.transform/src/main/java/org/openhab/core/transform/FileTransformationConfigurationProvider.java, bundles/org.openhab.core.ui.icon/src/main/java/org/openhab/core/ui/icon/internal/CustomIconProvider.java
Reported on the forum https://community.openhab.org/t/custom-icons-disappears-in-openhab-3-3/136957/4
=> Fix symlinks not followed

bom/runtime/pom.xml, features/karaf/openhab-tp/src/main/feature/feature.xml, itests/org.openhab.core.config.discovery.mdns.tests/itest.bndrun
For changes see https://github.com/jmdns/jmdns/milestone/10?closed=1
=> Upgrade to JmDNS 3.5.8

bundles/org.openhab.core.automation/src/main/resources/OH-INF/i18n/automation.properties
These were generated using openhab/openhab-core#2966.
=> Add default translations for automation module types

bundles/org.openhab.core.karaf/src/main/java/org/openhab/core/karaf/internal/KarafAddonService.java
When changing to addon.xml later, this can be extended to all add-ons. It is necessary to improve the UI code for changing add-on log levels.
=> Enrich distribution add-on with configDescriptionURI

bundles/org.openhab.core.config.discovery/src/main/java/org/openhab/core/config/discovery/inbox/Inbox.java
=> Fix JavaDoc for Inbox class

bundles/org.openhab.core.auth.oauth2client/src/main/java/org/openhab/core/auth/oauth2client/internal/OAuthClientServiceImpl.java, bundles/org.openhab.core.auth.oauth2client/src/main/java/org/openhab/core/auth/oauth2client/internal/OAuthConnector.java, bundles/org.openhab.core/src/main/java/org/openhab/core/auth/client/oauth2/AccessTokenResponse.java, bundles/org.openhab.core/src/test/java/org/openhab/core/auth/client/oauth2/AccessTokenResponseTest.java
Fixes #3065.
Follow-up in addons: openhab/openhab-addons#13277
=> [oauth] Migrate usage of LocalDateTime to Instant

bundles/org.openhab.core/src/main/java/org/openhab/core/library/items/NumberItem.java
NumberItems always accept QuantityType
=> Allow sending QuantityType to NumberItem

bundles/org.openhab.core.model.script/src/org/openhab/core/model/script/actions/ScriptExecution.java, bundles/org.openhab.core.model.script/src/org/openhab/core/model/script/actions/Timer.java
Reported on the forum. Critical because it breaks timers in DSL rules.
=> Fix createTimer for DSL rules

bundles/org.openhab.core.voice/src/main/java/org/openhab/core/voice/DialogContext.java, bundles/org.openhab.core.voice/src/main/java/org/openhab/core/voice/VoiceManager.java, bundles/org.openhab.core.voice/src/main/java/org/openhab/core/voice/internal/DialogProcessor.java, bundles/org.openhab.core.voice/src/main/java/org/openhab/core/voice/internal/VoiceManagerImpl.java, itests/org.openhab.core.voice.tests/src/main/java/org/openhab/core/voice/internal/VoiceManagerImplTest.java
New dialog methods for voice manager.
Related to https://github.com/openhab/openhab-core/issues/3140
Will close this one https://github.com/openhab/openhab-core/issues/3104
=> [voice] New voice manager dialog methods

bundles/org.openhab.core.model.script/src/org/openhab/core/model/script/scoping/ScriptImplicitlyImportedTypes.java
Fixes #3196 
Re-add a line that was accidentally removed in #3178.
=> Fix DSL action classes regression

bundles/org.openhab.core.automation.module.script/src/main/java/org/openhab/core/automation/module/script/internal/ScriptExtensionManager.java, bundles/org.openhab.core.model.script.runtime/src/org/openhab/core/model/script/runtime/internal/engine/DSLScriptEngine.java, bundles/org.openhab.core.model.script.runtime/src/org/openhab/core/model/script/runtime/internal/engine/DSLScriptEngineFactory.java, bundles/org.openhab.core.model.script/bnd.bnd, bundles/org.openhab.core.model.script/pom.xml, bundles/org.openhab.core.model.script/src/org/openhab/core/model/script/jvmmodel/ScriptJvmModelInferrer.xtend, features/karaf/openhab-core/src/main/feature/feature.xml, itests/org.openhab.core.auth.oauth2client.tests/itest.bndrun, itests/org.openhab.core.config.discovery.mdns.tests/itest.bndrun, itests/org.openhab.core.config.discovery.tests/itest.bndrun, itests/org.openhab.core.config.discovery.usbserial.linuxsysfs.tests/itest.bndrun, itests/org.openhab.core.config.discovery.usbserial.tests/itest.bndrun, itests/org.openhab.core.config.dispatch.tests/itest.bndrun, itests/org.openhab.core.model.core.tests/itest.bndrun, itests/org.openhab.core.model.item.tests/itest.bndrun, itests/org.openhab.core.model.rule.tests/itest.bndrun, itests/org.openhab.core.model.script.tests/itest.bndrun, itests/org.openhab.core.model.thing.tests/itest.bndrun
Follow-up to https://github.com/openhab/openhab-core/pull/2887
`sharedCache` and `privateCache` are made available by injecting them in the context.
=> DSL support for sharedCache/privateCache

itests/org.openhab.core.auth.oauth2client.tests/itest.bndrun, itests/org.openhab.core.automation.integration.tests/itest.bndrun, itests/org.openhab.core.automation.module.core.tests/itest.bndrun, itests/org.openhab.core.automation.module.script.tests/itest.bndrun, itests/org.openhab.core.automation.module.timer.tests/itest.bndrun, itests/org.openhab.core.automation.tests/itest.bndrun, itests/org.openhab.core.binding.xml.tests/itest.bndrun, itests/org.openhab.core.config.core.tests/itest.bndrun, itests/org.openhab.core.config.discovery.mdns.tests/itest.bndrun, itests/org.openhab.core.config.discovery.tests/itest.bndrun, itests/org.openhab.core.config.discovery.usbserial.linuxsysfs.tests/itest.bndrun, itests/org.openhab.core.config.discovery.usbserial.tests/itest.bndrun, itests/org.openhab.core.config.dispatch.tests/itest.bndrun, itests/org.openhab.core.config.xml.tests/itest.bndrun, itests/org.openhab.core.ephemeris.tests/itest.bndrun, itests/org.openhab.core.io.rest.core.tests/itest.bndrun, itests/org.openhab.core.model.core.tests/itest.bndrun, itests/org.openhab.core.model.item.tests/itest.bndrun, itests/org.openhab.core.model.rule.tests/itest.bndrun, itests/org.openhab.core.model.script.tests/itest.bndrun, itests/org.openhab.core.model.thing.tests/itest.bndrun, itests/org.openhab.core.storage.json.tests/itest.bndrun, itests/org.openhab.core.tests/itest.bndrun, itests/org.openhab.core.thing.tests/itest.bndrun, itests/org.openhab.core.thing.xml.tests/itest.bndrun, itests/org.openhab.core.voice.tests/itest.bndrun, pom.xml
=> Upgrade bnd to 6.4.0

bundles/org.openhab.core.persistence/src/main/java/org/openhab/core/persistence/extensions/PersistenceExtensions.java, bundles/org.openhab.core.persistence/src/test/java/org/openhab/core/persistence/extensions/PersistenceExtensionsTest.java
=> Add countSince/countBetween to persistence extensions

bundles/org.openhab.core.voice/src/main/java/org/openhab/core/voice/internal/VoiceManagerImpl.java
=> Prevent null warnings/errors in the IDE

bundles/org.openhab.core.voice/src/main/java/org/openhab/core/voice/DialogContext.java
=> Fix nullable errors in the IDE

bundles/org.openhab.core.automation.module.script/src/main/java/org/openhab/core/automation/module/script/internal/ScriptEngineManagerImpl.java, bundles/org.openhab.core.automation.module.script/src/test/java/org/openhab/core/automation/module/script/internal/ScriptEngineManagerImplTest.java
Reverts openhab/openhab-core#3180. See also discussion in #3224.
=> Revert "Wrap ScriptEngine executions in a SafeCaller"

bundles/org.openhab.core/src/main/java/org/openhab/core/library/types/DecimalType.java
=> Remove redundant ctor in DecimalType

bundles/org.openhab.core.audio/src/main/java/org/openhab/core/audio/utils/ToneSynthesizer.java, bundles/org.openhab.core.automation.module.media/src/main/java/org/openhab/core/automation/module/media/internal/SynthesizeActionHandler.java, bundles/org.openhab.core.automation.module.script/src/main/java/org/openhab/core/automation/module/script/internal/action/ScriptExecutionImpl.java, bundles/org.openhab.core.io.console.karaf/src/main/java/org/openhab/core/io/console/karaf/internal/CompleterWrapper.java, bundles/org.openhab.core.io.rest.auth/src/test/java/org/openhab/core/io/rest/auth/internal/AuthFilterTest.java, bundles/org.openhab.core.io.websocket/src/main/java/org/openhab/core/io/websocket/EventDTO.java, bundles/org.openhab.core.io.websocket/src/main/java/org/openhab/core/io/websocket/EventWebSocket.java, bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/events/ThingStatusInfoEvent.java, bundles/org.openhab.core/src/test/java/org/openhab/core/library/items/NumberItemTest.java, itests/org.openhab.core.config.discovery.tests/src/main/java/org/openhab/core/config/discovery/internal/InboxOSGiTest.java, itests/org.openhab.core.thing.tests/src/main/java/org/openhab/core/thing/link/ItemChannelLinkOSGiTest.java
=> Fix some recently introduced SAT and NPE issues

pom.xml
HTTPS is becoming very popular.
=> Use HTTPS with website URL in pom.xml

bundles/org.openhab.core.automation/src/test/java/org/openhab/core/automation/internal/module/handler/DateTimeTriggerHandlerTest.java, bundles/org.openhab.core.io.rest.auth/src/main/java/org/openhab/core/io/rest/auth/internal/JwtHelper.java, bundles/org.openhab.core.model.rule.runtime/src/org/openhab/core/model/rule/runtime/internal/DSLRuleProvider.java, itests/org.openhab.core.config.discovery.tests/src/main/java/org/openhab/core/config/discovery/internal/InboxOSGiTest.java, itests/org.openhab.core.io.rest.core.tests/src/main/java/org/openhab/core/io/rest/core/internal/item/ItemResourceOSGiTest.java
Fixes a deprecation, unused imports and some raw type warning.
=> Fix several compiler warnings

bom/openhab-core-index/.classpath, bom/runtime-index/.classpath, bom/test-index/.classpath
For some reason Eclipse did not update these BOM .classpath files in #3250.
Related to #2994
=> Use JavaSE-17 JVM

bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/binding/builder/ThingBuilder.java
=> Add JavaDoc for the ThingBuilder

bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/module/handler/DateTimeTriggerHandler.java
Reported on the forum: https://community.openhab.org/t/trigger-based-on-datetime-item-not-firing-after-restart-server/142608
During startup most likely the item state is `UndefType.NULL` which results in no triggering. States are restored from persistence by directly setting the item state, not by an `ItemStateEvent` and were therefore missed. Since changing the trigger is not necessary when the state updates but does not change, the event listening was changed to `ItemStateChangedEvent` only.
=> Fix DateTimeTrigger not triggering on restored state

bundles/org.openhab.core/src/main/java/org/openhab/core/Activator.java
=> Log the version/build on startup

bundles/org.openhab.core/src/main/java/org/openhab/core/internal/addon/AddonI18nUtil.java
=> Fix nullable errors

bundles/org.openhab.core.karaf/src/main/java/org/openhab/core/karaf/internal/KarafAddonService.java
This was accidentally removed when rebasing #3050 
=> Fix logger package addition in KarafAddonService

bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/ManagedThingProvider.java, bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/internal/BridgeImpl.java, bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/internal/ThingImpl.java, bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/util/ThingHelper.java, itests/org.openhab.core.storage.json.tests/src/main/java/org/openhab/core/storage/json/internal/ThingMigrationOSGiTest.java
Reverts #719 and re-implements #693, therefore completing #731
=> Improve channel handling in ThingImpl

bundles/org.openhab.core.automation.rest/src/main/java/org/openhab/core/automation/rest/internal/ThingActionsResource.java
=> [REST] Consider language when requesting thing actions

bundles/org.openhab.core.karaf/src/main/java/org/openhab/core/karaf/internal/KarafAddonService.java, bundles/org.openhab.core/src/main/java/org/openhab/core/internal/addon/AddonI18nUtil.java, itests/org.openhab.core.addon.xml.tests/src/main/resources/test-bundle-pool/acmeweather.bundle/OH-INF/i18n/acmeweather_de.properties, itests/org.openhab.core.addon.xml.tests/src/main/resources/test-bundle-pool/acmeweather.bundle/OH-INF/i18n/acmeweather_nl.properties
Fix openhab/openhab-webui#1666
Signed-off-by: Laurent Garnier wlg.hc@free.fr>
=> Consider language in KarafAddonService when creating Addon

bundles/org.openhab.core.karaf/src/main/java/org/openhab/core/karaf/internal/KarafAddonService.java
Fix openhab/openhab-webui#1667
=> Build default doc link for misc and ui bindings

bundles/org.openhab.core.addon.marketplace/src/main/java/org/openhab/core/addon/marketplace/internal/community/CommunityUIWidgetAddonHandler.java, bundles/org.openhab.core.addon.marketplace/src/main/java/org/openhab/core/addon/marketplace/internal/community/SerializedNameAnnotationIntrospector.java, bundles/org.openhab.core.config.core/src/main/java/org/openhab/core/config/core/dto/ConfigDescriptionParameterDTO.java
Unable to install ui widget from marketplace if yaml contains default value, please see https://github.com/openhab/openhab-core/issues/3332 for details.
fixes https://github.com/openhab/openhab-core/issues/3332
Signed-off-by: Boris Krivonog boris.krivonog@inova.si
=> Fix parsing of YAML default value for community marketplace UI Widgets

bundles/org.openhab.core/src/main/java/org/openhab/core/internal/addon/JarFileAddonService.java
=> Fix CME in JarFileAddonService

bundles/org.openhab.core.addon.marketplace/src/main/java/org/openhab/core/addon/marketplace/internal/json/JsonAddonService.java, bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/internal/addons/AddonResource.java
This was discovered while fixing the configuration handling in https://github.com/openhab/openhab-webui/pull/1684 (independent, but should be fixed).
=> Fix configuration for marketplace-services

bundles/org.openhab.core.automation.rest/src/main/java/org/openhab/core/automation/rest/internal/ThingActionsResource.java
=> Fix CME in ThingActionsResource

bundles/org.openhab.core/src/main/java/org/openhab/core/internal/i18n/I18nProviderImpl.java, bundles/org.openhab.core/src/test/java/org/openhab/core/internal/i18n/I18nProviderImplTest.java
=> Improve handling of erroneous localized messages

bundles/org.openhab.core.model.item/src/org/openhab/core/model/validation/ItemsValidator.xtend
=> Fix a typo in ItemsValidator

bundles/org.openhab.core.automation.module.script.rulesupport/src/main/java/org/openhab/core/automation/module/script/rulesupport/loader/AbstractScriptDependencyTracker.java, bundles/org.openhab.core.automation.module.script.rulesupport/src/main/java/org/openhab/core/automation/module/script/rulesupport/loader/AbstractScriptFileWatcher.java, bundles/org.openhab.core.automation.module.script.rulesupport/src/test/java/org/openhab/core/automation/module/script/rulesupport/loader/AbstractScriptDependencyTrackerTest.java, bundles/org.openhab.core.automation.module.script.rulesupport/src/test/java/org/openhab/core/automation/module/script/rulesupport/loader/AbstractScriptFileWatcherTest.java, bundles/org.openhab.core/src/main/java/org/openhab/core/internal/service/WatchServiceImpl.java, bundles/org.openhab.core/src/main/java/org/openhab/core/service/WatchService.java
Also improve handling of absolute path in `WatchService`
=> Align AbstractScriptDependencyTracker with AbstractScriptFileWatcher

bundles/org.openhab.core.model.sitemap/src/org/openhab/core/model/sitemap/Sitemap.xtext
=> Fix sitemap syntax for List element

bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/internal/ThingManagerImpl.java
Found in the log posted here: https://community.openhab.org/t/openhab-4-0-snapshot-discussion/142322/207
Also makes sure the `checkPrerequisites` job can't crash by catching `RuntimeException` during processing.
=> Fix ConfigValidationException handling in ThingManager

bundles/org.openhab.core.io.rest.transform/src/main/java/org/openhab/core/io/rest/transform/internal/TransformationResource.java
See https://github.com/openhab/openhab-webui/pull/1448#issuecomment-1450720486
=> [REST] List transformation services

tools/i18n-plugin/pom.xml
=> fix i18n-maven-plugin

bom/compile/pom.xml, bom/runtime/pom.xml, features/karaf/openhab-tp/src/main/feature/feature.xml
Fixes openhab/openhab-distro#1473
=> Upgrade JUPnP to 2.7.0

.github/issue_template/sitemap_change.md
This makes sure all maintainers are notified.
=> Add issue template for Sitemap changes

bundles/org.openhab.core.automation.module.script/src/main/resources/OH-INF/config/script-profile.xml, bundles/org.openhab.core.automation.module.script/src/main/resources/OH-INF/i18n/scriptprofile.properties
=> Clarify the script profile config description

bundles/org.openhab.core.semantics/src/main/java/org/openhab/core/semantics/Property.java, bundles/org.openhab.core.semantics/src/main/java/org/openhab/core/semantics/SemanticTags.java
=> Fix Semantics default synonyms

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/feature_request.md, .github/ISSUE_TEMPLATE/sitemap_change.md, .github/PULL_REQUEST_TEMPLATE.md
Based on the templates used in openhab-addons.
You can see what these changes look like in my own fork:
https://github.com/wborn/openhab-core
Related to #3427
=> Add issue and pull request templates and configuration

bundles/org.openhab.core.automation.module.script/src/main/java/org/openhab/core/automation/module/script/internal/ScriptEngineFactoryHelper.java
https://community.openhab.org/t/openhab-4-0-snapshot-discussion/142322/319
=> Fix IndexOutOfBoundsException in ScriptEngineFactoryHelper

bundles/org.openhab.core.transform/src/main/java/org/openhab/core/transform/FileTransformationProvider.java
This is especially important because it clutters the config options for profiles that rely on transformation services.
=> Fix hidden files showing up in TransformationRegistry

bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/commands/AutomationCommandList.java, bundles/org.openhab.core.io.http.auth/src/main/java/org/openhab/core/io/http/auth/internal/AbstractAuthPageServlet.java, bundles/org.openhab.core.io.net/src/main/java/org/openhab/core/io/net/http/HttpUtil.java, bundles/org.openhab.core.io.transport.modbus/src/main/java/org/openhab/core/io/transport/modbus/BitArray.java, bundles/org.openhab.core.io.transport.modbus/src/main/java/org/openhab/core/io/transport/modbus/ModbusRegisterArray.java, bundles/org.openhab.core.model.item/src/org/openhab/core/model/item/internal/GenericItemProvider.java, bundles/org.openhab.core.model.script/src/org/openhab/core/model/script/actions/BusEvent.java, bundles/org.openhab.core.model.script/src/org/openhab/core/model/script/engine/ScriptParsingException.java, bundles/org.openhab.core.model.script/src/org/openhab/core/model/script/lib/NumberExtensions.java, bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/ManagedThingProvider.java, bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/internal/ChannelStateDescriptionProvider.java, bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/xml/internal/ThingDescriptionList.java, bundles/org.openhab.core/src/main/java/org/openhab/core/service/StartLevelService.java
Use new language features, mainly instanceof pattern matching.
This change covers remaining bundles.
Relates to #3508, #3522, and #3580.
=> Code cleanup: Use Java 17 features

bundles/org.openhab.core/src/main/java/org/openhab/core/internal/i18n/I18nProviderImpl.java
=> Change default imperial unit for length to inch

bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/RuleEngineImpl.java
Fixes #3468 
Also logs the full stacktrace at DEBUG level
=> Improve message when rule action fails

bundles/org.openhab.core.thing/src/test/java/org/openhab/core/thing/binding/AbstractStorageBasedTypeProviderTest.java
=> Fix build (AbstractStorageBasedTypeProviderTest)

bundles/org.openhab.core.persistence/src/test/java/org/openhab/core/persistence/filter/PersistenceThresholdFilterTest.java
Tests were failing after the merge of PR #3481
Fix #3600
=> Fix failed persistence tests

bundles/org.openhab.core/src/main/java/org/openhab/core/types/util/UnitUtils.java
The log level was increased during the UoM refactoring but it turns out that a lot of code depends on failing silently. Therefore the log level is again reduced to DEBUG.
=> Reduce loglevel in UnitUtils

tools/upgradetool/src/main/java/org/openhab/core/tools/internal/Upgrader.java
Closes #3613 
It seems that in some cases GSON is not able to correctly serialize/deserialize ZonedDateTime. Since we do not depend on the value in any case (it's just informational), we can store a String instead.
A missing metadata database also failed the check when upgrading items. This has been fixed, too (also it is cosmetics, if there is no metadata storage, then there is no state description that could be converted).
=> Fix UpgradeTool execution log

pom.xml
Related to https://github.com/openhab/openhab-distro/issues/1540
=> Update to SAT version 0.15.0

bundles/org.openhab.core.model.lsp/src/main/java/org/openhab/core/model/lsp/internal/ModelServer.java, bundles/org.openhab.core.model.lsp/src/main/resources/OH-INF/config/lsp.xml, bundles/org.openhab.core.model.lsp/src/main/resources/OH-INF/i18n/lsp.properties, bundles/org.openhab.core.model.lsp/src/main/resources/OH-INF/i18n/lsp_cs.properties, bundles/org.openhab.core.model.lsp/src/main/resources/OH-INF/i18n/lsp_da.properties, bundles/org.openhab.core.model.lsp/src/main/resources/OH-INF/i18n/lsp_de.properties, bundles/org.openhab.core.model.lsp/src/main/resources/OH-INF/i18n/lsp_el.properties, bundles/org.openhab.core.model.lsp/src/main/resources/OH-INF/i18n/lsp_fi.properties, bundles/org.openhab.core.model.lsp/src/main/resources/OH-INF/i18n/lsp_fr.properties, bundles/org.openhab.core.model.lsp/src/main/resources/OH-INF/i18n/lsp_he.properties, bundles/org.openhab.core.model.lsp/src/main/resources/OH-INF/i18n/lsp_hu.properties, bundles/org.openhab.core.model.lsp/src/main/resources/OH-INF/i18n/lsp_it.properties, bundles/org.openhab.core.model.lsp/src/main/resources/OH-INF/i18n/lsp_nl.properties, bundles/org.openhab.core.model.lsp/src/main/resources/OH-INF/i18n/lsp_no.properties, bundles/org.openhab.core.model.lsp/src/main/resources/OH-INF/i18n/lsp_pl.properties, bundles/org.openhab.core.model.lsp/src/main/resources/OH-INF/i18n/lsp_pt.properties, bundles/org.openhab.core.model.lsp/src/main/resources/OH-INF/i18n/lsp_ru.properties, bundles/org.openhab.core.model.lsp/src/main/resources/OH-INF/i18n/lsp_sl.properties, bundles/org.openhab.core.model.lsp/src/main/resources/OH-INF/i18n/lsp_sv.properties, bundles/org.openhab.core.model.lsp/src/main/resources/OH-INF/i18n/lsp_uk.properties, bundles/org.openhab.core.model.lsp/src/main/resources/OH-INF/i18n/lsp_zh.properties
This is needed to clean-up UI. The categories should be used for add-ons while core services should use `system`.
=> Move LSP service from misc to system

tools/upgradetool/src/main/java/org/openhab/core/tools/internal/Upgrader.java
Reported on the forum. State descriptions do no necessarily contain a pattern and thus `.get("pattern")` can return null.
=> Fix NPE in UpgradeTool when no pattern present

bundles/org.openhab.core/src/main/java/org/openhab/core/internal/items/ItemRegistryImpl.java
Fixes #3605 
Posting the `ItemAddedEvent` after notifying the listeners results in `ItemStateUpdated/ChangedEvents` before the `ItemAddedEvent` because the state could be altered by persistence services. This is at least unexpected and can be fixed by swapping the order.
=> Fix event ordering for item events

bundles/org.openhab.core/src/main/java/org/openhab/core/internal/service/WatchServiceImpl.java
It was reported on the forum that in some cases the hash is null.
=> Fix NPE in WatchServiceImpl

bom/compile/pom.xml, bom/runtime/pom.xml, features/karaf/openhab-tp/src/main/feature/feature.xml
=> Bump jose4j

bundles/org.openhab.core.io.rest.sse/src/main/java/org/openhab/core/io/rest/sse/internal/SseItemStatesEventBuilder.java, bundles/org.openhab.core.io.rest.sse/src/main/java/org/openhab/core/io/rest/sse/internal/dto/StateDTO.java
Needed for PR https://github.com/openhab/openhab-webui/pull/1920 and therefore also for solving issue #3643.
/cc @J-N-K
=> Item states SSE stream: Provide state type

tools/upgradetool/src/main/java/org/openhab/core/tools/internal/Upgrader.java
This enhances the metadata creation to system-channel-types that provide a state description with a unit. In addition warnings are printed if the channel MIGHT set a state description but the tool was not able to determine that.
=> [upgradetool] Adjust metadata unit for system channel types

bundles/org.openhab.core.addon.marketplace/src/main/java/org/openhab/core/addon/marketplace/internal/community/CommunityMarketplaceAddonService.java
Allow unusual jar naming convention
Closes https://github.com/openhab/openhab-webui/issues/1912
=> Improve community marketplace addon handler

bom/runtime/pom.xml, bundles/org.openhab.core.semantics/pom.xml, features/karaf/openhab-tp/src/main/feature/feature.xml, itests/org.openhab.core.io.net.tests/itest.bndrun, itests/org.openhab.core.io.rest.core.tests/itest.bndrun
Fixes https://github.com/openhab/openhab-addons/issues/15099
=> Bump spifly to 1.3.6 and asm to 9.4 to support records

bundles/org.openhab.core.persistence/src/main/java/org/openhab/core/persistence/internal/PersistenceManager.java
Fixes https://github.com/openhab/openhab-addons/issues/15236
=> Fix NPE in PersistenceManager

bundles/org.openhab.core.ui/NOTICE, bundles/org.openhab.core.ui/bnd.bnd, bundles/org.openhab.core.ui/pom.xml, bundles/org.openhab.core.ui/src/main/java/org/openhab/core/ui/internal/chart/defaultchartprovider/DefaultChartProvider.java
Reverts openhab/openhab-core#3291
=> Revert "Upgrade XChart to 3.8.4"

bom/compile/pom.xml, bom/runtime/pom.xml, bundles/org.openhab.core/src/test/java/org/openhab/core/library/unit/UnitsTest.java, features/karaf/openhab-tp/src/main/feature/feature.xml, itests/org.openhab.core.addon.tests/itest.bndrun, itests/org.openhab.core.auth.oauth2client.tests/itest.bndrun, itests/org.openhab.core.automation.integration.tests/itest.bndrun, itests/org.openhab.core.automation.module.core.tests/itest.bndrun, itests/org.openhab.core.automation.module.script.tests/itest.bndrun, itests/org.openhab.core.automation.module.timer.tests/itest.bndrun, itests/org.openhab.core.automation.tests/itest.bndrun, itests/org.openhab.core.config.core.tests/itest.bndrun, itests/org.openhab.core.config.discovery.mdns.tests/itest.bndrun, itests/org.openhab.core.config.discovery.tests/itest.bndrun, itests/org.openhab.core.config.discovery.usbserial.linuxsysfs.tests/itest.bndrun, itests/org.openhab.core.config.discovery.usbserial.tests/itest.bndrun, itests/org.openhab.core.config.dispatch.tests/itest.bndrun, itests/org.openhab.core.ephemeris.tests/itest.bndrun, itests/org.openhab.core.io.net.tests/itest.bndrun, itests/org.openhab.core.io.rest.core.tests/itest.bndrun, itests/org.openhab.core.model.item.tests/itest.bndrun, itests/org.openhab.core.model.rule.tests/itest.bndrun, itests/org.openhab.core.model.script.tests/itest.bndrun, itests/org.openhab.core.model.thing.tests/itest.bndrun, itests/org.openhab.core.storage.json.tests/itest.bndrun, itests/org.openhab.core.tests/itest.bndrun, itests/org.openhab.core.thing.tests/itest.bndrun, itests/org.openhab.core.voice.tests/itest.bndrun, tools/upgradetool/pom.xml
=> Bump UoM libraries to 2.2

bundles/org.openhab.core.automation.module.script.rulesupport/src/test/java/org/openhab/core/automation/module/script/rulesupport/loader/AbstractScriptFileWatcherTest.java, bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/module/handler/ItemStateConditionHandler.java, bundles/org.openhab.core.automation/src/test/java/org/openhab/core/automation/internal/module/handler/SystemTriggerHandlerTest.java, bundles/org.openhab.core.config.core/src/main/java/org/openhab/core/config/core/ConfigDescriptionParameterGroupBuilder.java, bundles/org.openhab.core.config.core/src/main/java/org/openhab/core/config/core/ConfigurationSerializer.java, bundles/org.openhab.core.io.transport.modbus/src/test/java/org/openhab/core/io/transport/modbus/test/BitUtilitiesCommandToRegistersTest.java, bundles/org.openhab.core.io.transport.modbus/src/test/java/org/openhab/core/io/transport/modbus/test/BitUtilitiesExtractStateFromRegistersTest.java, bundles/org.openhab.core.io.transport.modbus/src/test/java/org/openhab/core/io/transport/modbus/test/BitUtilitiesExtractStringTest.java, bundles/org.openhab.core.persistence/src/main/java/org/openhab/core/persistence/dto/ItemHistoryDTO.java, bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/internal/CommunicationManager.java, bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/xml/internal/ThingDescriptionList.java, bundles/org.openhab.core/src/main/java/org/openhab/core/internal/items/MetadataRegistryImpl.java, bundles/org.openhab.core/src/main/java/org/openhab/core/library/types/QuantityType.java, bundles/org.openhab.core/src/test/java/org/openhab/core/library/items/NumberItemTest.java, bundles/org.openhab.core/src/test/java/org/openhab/core/types/StateDescriptionFragmentBuilderTest.java, itests/org.openhab.core.thing.tests/src/main/java/org/openhab/core/thing/internal/CommunicationManagerOSGiTest.java
This code cleanup fixes various warnings in Eclipse.
=> Cleanup code

bundles/org.openhab.core.io.rest/src/main/java/org/openhab/core/io/rest/internal/resources/beans/SystemInfoBean.java
=> [rest] Add uptime to /systeminfo endpoint

bundles/org.openhab.core.ui/src/main/java/org/openhab/core/ui/internal/components/UIComponentSitemapProvider.java
=> [sitemap/MainUI] Fix a typo in buildWidget

bundles/org.openhab.core.io.rest.sitemap/src/main/java/org/openhab/core/io/rest/sitemap/internal/MappingDTO.java, bundles/org.openhab.core.io.rest.sitemap/src/main/java/org/openhab/core/io/rest/sitemap/internal/SitemapResource.java, bundles/org.openhab.core.io.rest.sitemap/src/main/java/org/openhab/core/io/rest/sitemap/internal/WidgetDTO.java, bundles/org.openhab.core.model.sitemap/src/org/openhab/core/model/sitemap/Sitemap.xtext, bundles/org.openhab.core.ui/src/main/java/org/openhab/core/ui/internal/components/UIComponentSitemapProvider.java
=> [Sitemap] Introduce "Buttongrid" as new sitemap element

bundles/org.openhab.core.model.core/src/main/java/org/openhab/core/model/core/internal/folder/FolderObserver.java
* Mark extensions as ready in addModelsToRepo only if parser was available
* Store valid extensions using Set instead of List
* Use java.nio where possible
* Add more debug logging
* Cleanup and simplify code
---
This should help with fixing/debugging #3784 and #3793
=> FolderObserver improvements

bundles/org.openhab.core.io.rest/src/main/java/org/openhab/core/io/rest/internal/resources/SystemInfoResource.java
Adds caching as in #3729 for the UoM info endpoint added in #3611.
This is required for making Main UI dynamically load the supported dimensions from the REST API.
=> [rest] Add caching for UoM info

bundles/org.openhab.core/src/main/java/org/openhab/core/library/types/QuantityType.java
=> Improve code in QuantityType

bundles/org.openhab.core/src/main/java/org/openhab/core/util/StringUtils.java
=> Address warnings in StringUtils class

bundles/org.openhab.core/src/main/java/org/openhab/core/auth/ManagedUser.java, bundles/org.openhab.core/src/main/java/org/openhab/core/auth/UserRegistry.java, bundles/org.openhab.core/src/main/java/org/openhab/core/auth/client/oauth2/OAuthClientService.java, bundles/org.openhab.core/src/main/java/org/openhab/core/cache/ExpiringCache.java, bundles/org.openhab.core/src/main/java/org/openhab/core/cache/ExpiringCacheAsync.java, bundles/org.openhab.core/src/main/java/org/openhab/core/cache/lru/LRUMediaCache.java, bundles/org.openhab.core/src/main/java/org/openhab/core/events/TopicGlobEventFilter.java, bundles/org.openhab.core/src/main/java/org/openhab/core/events/TopicPrefixEventFilter.java, bundles/org.openhab.core/src/main/java/org/openhab/core/items/ManagedItemProvider.java, bundles/org.openhab.core/src/main/java/org/openhab/core/items/ManagedMetadataProvider.java, bundles/org.openhab.core/src/main/java/org/openhab/core/items/dto/ItemDTOMapper.java, bundles/org.openhab.core/src/main/java/org/openhab/core/library/items/LocationItem.java, bundles/org.openhab.core/src/main/java/org/openhab/core/library/types/HSBType.java, bundles/org.openhab.core/src/main/java/org/openhab/core/library/types/QuantityType.java, bundles/org.openhab.core/src/main/java/org/openhab/core/scheduler/CronScheduler.java, bundles/org.openhab.core/src/main/java/org/openhab/core/scheduler/Scheduler.java, bundles/org.openhab.core/src/main/java/org/openhab/core/service/ReadyMarkerFilter.java, bundles/org.openhab.core/src/main/java/org/openhab/core/service/ReadyService.java, bundles/org.openhab.core/src/main/java/org/openhab/core/service/WatchServiceFactory.java, bundles/org.openhab.core/src/main/java/org/openhab/core/types/TimeSeries.java, bundles/org.openhab.core/src/main/java/org/openhab/core/util/ColorUtil.java, bundles/org.openhab.core/src/main/java/org/openhab/core/util/StringUtils.java
Other directories still to be handled in other PR.
=>  Fix javadoc warnings in directory org.openhab.core

bundles/org.openhab.core.model.script/src/org/openhab/core/model/script/actions/CoreUtil.java
New functions for RGBW introduced in #3849.
Just direction HsbToRgb. Opposite direction uses existing function which returns array of size 4 instead of 3.
=> [DSL] Expose ColorUtil methods to DSL rules

bundles/org.openhab.core.auth.oauth2client/src/main/java/org/openhab/core/auth/oauth2client/internal/OAuthClientServiceImpl.java, bundles/org.openhab.core.auth.oauth2client/src/main/java/org/openhab/core/auth/oauth2client/internal/OAuthConnector.java, bundles/org.openhab.core/src/main/java/org/openhab/core/auth/client/oauth2/OAuthClientService.java
As is the oauth2 client does not support oauth2 endpoints that require more than the standard fields in the form data posted to the token URL.  This PR adds that support.
An example of where this is needed is the Velux API described here: https://github.com/nougad/velux-cli/blob/master/velux-protocol.md#initial-login
The `user_prefix` param is non standard and there was no way to include it with this client.
I tried to keep the existing constructor options in place so this shouldn't break anything outside of oauth2client that happens to be using the OAuthConnector class.
=> [oauth] Add support for passing extra fields to oauth token request

bundles/org.openhab.core.io.transport.mdns/src/main/java/org/openhab/core/io/transport/mdns/internal/MDNSClientImpl.java
Fix openhab/openhab-addons#16023
=> Fix handling of mDNS instances when an IP address changed

bundles/org.openhab.core.config.discovery.addon/src/main/java/org/openhab/core/config/discovery/addon/AddonSuggestionService.java, bundles/org.openhab.core.karaf/src/main/java/org/openhab/core/karaf/internal/KarafAddonFinderService.java
=> Handle ISE when shutting down

bundles/org.openhab.core.model.yaml/src/main/java/org/openhab/core/model/yaml/internal/YamlModelRepository.java
For consistency with other model files loading.
=> Add a log when loading a YAML file

bundles/org.openhab.core.voice/src/main/java/org/openhab/core/voice/KSEdgeService.java, bundles/org.openhab.core.voice/src/main/java/org/openhab/core/voice/internal/DialogProcessor.java
Add interface that allows to register a keyword spotting service that is not running on the oh server, so the dialog processing can be triggered remotely instead of processing an audio stream.
The reason for having this interface is that the DialogProcessor can avoid the creation of an audio stream from the source that will not be used.
Hope it is an acceptable solution. Best regards.
=> [voice] Add interface to represent a remote keyword spotter

bundles/org.openhab.core.config.discovery.addon.mdns/src/main/java/org/openhab/core/config/discovery/addon/mdns/MDNSAddonFinder.java
(javadoc build badge is red at the moment)
=> minor doc update to fix javadoc build

bundles/org.openhab.core.config.core/src/main/java/org/openhab/core/config/core/CurrencyServiceConfigOptionProvider.java, bundles/org.openhab.core.config.discovery.addon.process/src/main/java/org/openhab/core/config/discovery/addon/process/ProcessAddonFinder.java, bundles/org.openhab.core.persistence/src/main/java/org/openhab/core/persistence/internal/PersistenceManager.java, bundles/org.openhab.core.voice/src/main/java/org/openhab/core/voice/internal/text/StandardInterpreter.java, bundles/org.openhab.core.voice/src/main/java/org/openhab/core/voice/text/AbstractRuleBasedInterpreter.java, bundles/org.openhab.core.voice/src/test/java/org/openhab/core/voice/internal/text/StandardInterpreterTest.java, bundles/org.openhab.core/src/main/java/org/openhab/core/types/TimeSeries.java
=> Reduce SAT warnings

bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/internal/JSONResponseExceptionMapper.java
(Partially) fixes https://github.com/openhab/openhab-distro/issues/1616
=> Don't log errors on NotFoundExceptions in Jetty

bundles/org.openhab.core.test/pom.xml, bundles/org.openhab.core/pom.xml, itests/org.openhab.core.addon.tests/itest.bndrun, itests/org.openhab.core.auth.oauth2client.tests/itest.bndrun, itests/org.openhab.core.automation.integration.tests/itest.bndrun, itests/org.openhab.core.automation.module.core.tests/itest.bndrun, itests/org.openhab.core.automation.module.script.tests/itest.bndrun, itests/org.openhab.core.automation.module.timer.tests/itest.bndrun, itests/org.openhab.core.automation.tests/itest.bndrun, itests/org.openhab.core.config.core.tests/itest.bndrun, itests/org.openhab.core.config.discovery.mdns.tests/itest.bndrun, itests/org.openhab.core.config.discovery.tests/itest.bndrun, itests/org.openhab.core.config.discovery.usbserial.linuxsysfs.tests/itest.bndrun, itests/org.openhab.core.config.discovery.usbserial.tests/itest.bndrun, itests/org.openhab.core.config.dispatch.tests/itest.bndrun, itests/org.openhab.core.ephemeris.tests/itest.bndrun, itests/org.openhab.core.io.net.tests/itest.bndrun, itests/org.openhab.core.io.rest.core.tests/itest.bndrun, itests/org.openhab.core.model.item.tests/itest.bndrun, itests/org.openhab.core.model.rule.tests/itest.bndrun, itests/org.openhab.core.model.script.tests/itest.bndrun, itests/org.openhab.core.model.thing.tests/itest.bndrun, itests/org.openhab.core.storage.json.tests/itest.bndrun, itests/org.openhab.core.tests/itest.bndrun, itests/org.openhab.core.thing.tests/itest.bndrun, itests/org.openhab.core.voice.tests/itest.bndrun, itests/pom.xml
Addresses:
* CVE-2023-6378
* CVE-2023-6481
See: https://logback.qos.ch/news.html#1.3.14
=> Upgrade logback-classic to 1.3.14

bundles/org.openhab.core.ui/src/main/java/org/openhab/core/ui/internal/components/UIComponentSitemapProvider.java
=> Sitemap generator: fix button parsing for Buttongrid

bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/internal/JSONResponseExceptionMapper.java, bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/internal/item/ItemResource.java
See https://github.com/openhab/openhab-distro/issues/1616#issuecomment-1864216523
=> Improve HTTP 404 handling and logging

bundles/org.openhab.core.addon/src/main/java/org/openhab/core/addon/internal/xml/AddonInfoAddonsXmlProvider.java, bundles/org.openhab.core.config.discovery.addon/src/main/java/org/openhab/core/config/discovery/addon/AddonFinder.java, bundles/org.openhab.core.config.discovery.addon/src/main/java/org/openhab/core/config/discovery/addon/AddonFinderConstants.java, bundles/org.openhab.core/src/main/java/org/openhab/core/OpenHAB.java
See https://github.com/openhab/openhab-distro/issues/1616#issuecomment-1865154961
=> Move addons.xml to runtime folder

bundles/org.openhab.core.config.discovery.addon.ip/src/main/java/org/openhab/core/config/discovery/addon/ip/IpAddonFinder.java
…and do not use a dedicated thread pool
=> Delay the IP scan to make sure that no further candidates are added

bundles/org.openhab.core.auth.oauth2client/src/main/java/org/openhab/core/auth/oauth2client/internal/OAuthClientServiceImpl.java, bundles/org.openhab.core.config.core/src/main/java/org/openhab/core/config/core/status/ConfigStatusMessage.java, bundles/org.openhab.core.config.core/src/main/java/org/openhab/core/config/core/xml/osgi/XmlDocumentBundleTracker.java, bundles/org.openhab.core.config.discovery.addon.process/src/main/java/org/openhab/core/config/discovery/addon/process/ProcessAddonFinder.java, bundles/org.openhab.core.persistence/src/main/java/org/openhab/core/persistence/internal/PersistenceManager.java, bundles/org.openhab.core.test/src/main/java/org/openhab/core/test/java/JavaOSGiTest.java, bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/binding/generic/converter/ColorChannelHandler.java, bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/binding/generic/converter/DimmerChannelHandler.java, bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/binding/generic/converter/RollershutterChannelHandler.java, bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/internal/ThingManagerImpl.java, bundles/org.openhab.core.thing/src/test/java/org/openhab/core/thing/internal/profiles/TriggerEventStringProfileTest.java, bundles/org.openhab.core.voice/src/main/java/org/openhab/core/voice/internal/DialogProcessor.java, bundles/org.openhab.core/src/main/java/org/openhab/core/library/items/NumberItem.java, bundles/org.openhab.core/src/main/java/org/openhab/core/library/unit/CurrencyUnit.java, itests/org.openhab.core.automation.module.core.tests/src/main/java/org/openhab/core/automation/internal/module/RuntimeRuleTest.java, itests/org.openhab.core.config.discovery.tests/src/main/java/org/openhab/core/config/discovery/inbox/DynamicThingUpdateOSGiTest.java
=> Minor code cleanup

pom.xml
In addons, we have introduced the custom tags quite a while ago, first on the binding level, and later at top level.
I just noticed, that javadoc build for core does not contain @ implNote sections (neither heading nor content).
With the patch it looks like this:
As of now, the part marked in yellow is missing.
https://ci.openhab.org/view/Documentation/job/openHAB-JavaDoc/javadoc/org/openhab/core/config/discovery/addon/ip/IpAddonFinder.html
=> Javadoc: Introduce custom tags @ implNote and @ apiNote

bundles/org.openhab.core.persistence/src/test/java/org/openhab/core/persistence/extensions/TestPersistenceService.java, bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/internal/profiles/SystemHysteresisStateProfile.java, bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/internal/profiles/SystemRangeStateProfile.java, bundles/org.openhab.core/src/main/java/org/openhab/core/library/types/DecimalType.java, bundles/org.openhab.core/src/main/java/org/openhab/core/library/types/HSBType.java, bundles/org.openhab.core/src/main/java/org/openhab/core/library/types/PercentType.java, bundles/org.openhab.core/src/main/java/org/openhab/core/library/types/QuantityType.java
You can create an `OnOffType` using a boolean nowadays which reduces the amount of code.
=> Use `OnOffType.from` to reduce code

features/karaf/openhab-tp/src/main/feature/feature.xml
Upgrades:
* Netty from 4.1.99.Final to 4.1.104.Final
For all fixes and improvements of these upgrades, see:
* https://netty.io/news/index.html
=> Upgrade Netty to 4.1.104.Final

bom/runtime/pom.xml, features/karaf/openhab-tp/src/main/feature/feature.xml
Updates Jackson from 2.15.2 to 2.16.0
https://github.com/FasterXML/jackson/wiki/Jackson-Release-2.16
This upgrade addresses:
* CVE-2023-35116
=> Update Jackson to 2.16.0

bundles/org.openhab.core/src/main/java/org/openhab/core/library/unit/Units.java, bundles/org.openhab.core/src/test/java/org/openhab/core/library/unit/UnitsTest.java
Fixes #3962
Due to the way month, week and day are defined in Indriya their symbol is not added as alias. This is a bug in indriya, but their release cycles are quite long and we should provide a fix for our users.
This should be backported to 4.1.x
=> Fix month, week, day not supported

bundles/org.openhab.core.config.discovery.addon.ip/src/main/java/org/openhab/core/config/discovery/addon/ip/IpAddonFinder.java
pure documentation change, describes configuration of IP addon finder in the bindings (addon.xml)
=> IP addon finder: developer docs

bundles/org.openhab.core.ui/src/main/java/org/openhab/core/ui/internal/components/UIComponentSitemapProvider.java
Fix openhab/openhab-webui#2242
=> [sitemap] Fix parsing of button (buttongrid element built with MainUI)

bundles/org.openhab.core.config.core/src/main/java/org/openhab/core/config/core/xml/osgi/XmlDocumentBundleTracker.java, bundles/org.openhab.core.config.core/src/test/java/org/openhab/core/config/core/ConfigurationTest.java, bundles/org.openhab.core.config.discovery/src/main/java/org/openhab/core/config/discovery/DiscoveryResultBuilder.java, bundles/org.openhab.core.config.discovery/src/test/java/org/openhab/core/config/discovery/AbstractDiscoveryServiceTest.java, bundles/org.openhab.core.model.persistence/src/org/openhab/core/model/persistence/scoping/GlobalStrategies.java, bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/ThingStatusDetail.java, bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/events/ChannelDescriptionChangedEvent.java, bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/internal/firmware/ProgressCallbackImpl.java, bundles/org.openhab.core.thing/src/test/java/org/openhab/core/thing/binding/BaseDynamicCommandDescriptionProviderTest.java, bundles/org.openhab.core.thing/src/test/java/org/openhab/core/thing/binding/BaseDynamicStateDescriptionProviderTest.java, bundles/org.openhab.core.ui.icon/src/test/java/org/openhab/core/ui/icon/AbstractResourceIconProviderTest.java, bundles/org.openhab.core.ui/src/main/java/org/openhab/core/ui/items/ItemUIRegistry.java, itests/org.openhab.core.model.thing.tests/src/main/java/org/openhab/core/model/thing/test/hue/GenericThingProviderTest4.java, itests/org.openhab.core.thing.tests/src/main/java/org/openhab/core/thing/binding/BindingBaseClassesOSGiTest.java, itests/org.openhab.core.thing.tests/src/main/java/org/openhab/core/thing/internal/ThingManagerOSGiJavaTest.java
This helps with stopping the proliferation of unnecessary semicolons.
=> Remove unnecessary semicolons

bom/compile/pom.xml, bom/runtime/pom.xml, features/karaf/openhab-tp/src/main/feature/feature.xml, itests/org.openhab.core.config.discovery.mdns.tests/itest.bndrun
See [changelog](https://github.com/jmdns/jmdns/milestone/11?closed=1)
=> Upgrade to JmDNS 3.5.9

bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/binding/ThingHandlerService.java
=> Fix JavaDoc build

bundles/org.openhab.core.io.transport.upnp/src/main/java/org/openhab/core/io/transport/upnp/internal/UpnpIOServiceImpl.java
=> Fix NPE in UpnpIOServiceImpl

bundles/org.openhab.core.addon.marketplace/src/main/java/org/openhab/core/addon/marketplace/AbstractRemoteAddonService.java, bundles/org.openhab.core.addon.marketplace/src/main/java/org/openhab/core/addon/marketplace/internal/json/JsonAddonService.java, bundles/org.openhab.core.addon.marketplace/src/test/java/org/openhab/core/addon/marketplace/AbstractRemoteAddonServiceTest.java
=> Fix config parsing and version handling in RemoteAddonServices

bundles/org.openhab.core.addon.marketplace/src/main/java/org/openhab/core/addon/marketplace/AbstractRemoteAddonService.java, bundles/org.openhab.core.addon.marketplace/src/test/java/org/openhab/core/addon/marketplace/AbstractRemoteAddonServiceTest.java, bundles/org.openhab.core.addon.marketplace/src/test/java/org/openhab/core/addon/marketplace/test/TestAddonService.java
Fixes #4045 
Also improves handling of missing/incorrect addon-versions
=> Improve RemoteAddonService and fix test

bundles/org.openhab.core.io.rest.sitemap/src/main/java/org/openhab/core/io/rest/sitemap/internal/SitemapResource.java
=> Useful logs added in SitemapResource for REST API calls

bundles/org.openhab.core.config.discovery/src/main/java/org/openhab/core/config/discovery/internal/console/InboxConsoleCommandExtension.java
This adds command completion for the inbox console commands.
=> [discovery] Add inbox console command completion

itests/org.openhab.core.auth.oauth2client.tests/itest.bndrun, itests/org.openhab.core.automation.integration.tests/itest.bndrun, itests/org.openhab.core.automation.module.core.tests/itest.bndrun, itests/org.openhab.core.automation.module.script.tests/itest.bndrun, itests/org.openhab.core.automation.module.timer.tests/itest.bndrun, itests/org.openhab.core.automation.tests/itest.bndrun, itests/org.openhab.core.config.discovery.mdns.tests/itest.bndrun, itests/org.openhab.core.config.discovery.tests/itest.bndrun, itests/org.openhab.core.config.discovery.usbserial.linuxsysfs.tests/itest.bndrun, itests/org.openhab.core.config.discovery.usbserial.tests/itest.bndrun, itests/org.openhab.core.model.item.tests/itest.bndrun, itests/org.openhab.core.model.rule.tests/itest.bndrun, itests/org.openhab.core.model.script.tests/itest.bndrun, itests/org.openhab.core.model.thing.tests/itest.bndrun, itests/org.openhab.core.storage.json.tests/itest.bndrun, itests/org.openhab.core.thing.tests/itest.bndrun, itests/org.openhab.core.thing.tests/src/main/java/org/openhab/core/thing/internal/AutoUpdateManagerTest.java, itests/org.openhab.core.voice.tests/itest.bndrun
Why do unresolved tests result in "No error" instead of "Failed"?
=> Fix itests not running

bundles/org.openhab.core.automation.module.script/src/main/java/org/openhab/core/automation/module/script/profile/ScriptProfile.java, bundles/org.openhab.core.automation.module.script/src/test/java/org/openhab/core/automation/module/script/profile/ScriptProfileTest.java
=> Script profile: Fix deprecation warning for `toHandlerScript`

bundles/org.openhab.core.model.yaml/src/test/java/org/openhab/core/model/yaml/internal/YamlModelRepositoryImplTest.java
I ran into trouble with ```YamlModelRepositoryImplTest``` several times in an Windows environment (where the sample files are checked out with CRLF endings).
I think line endings should not matter for this test, so I replaces the CRLF with LF.
Not sure if one should also care about may (CR).
=> Relax test to accept files with CRLF line endings

tools/upgradetool/src/main/java/org/openhab/core/tools/internal/Upgrader.java
=> Upgrade Tool: Fix NPE

bundles/org.openhab.core.io.jetty.certificate/pom.xml
Allow for compiling with Java 21
Refs: openhab/openhab-distro#1590
=> Bump maven-shade-plugin to 3.5.2

pom.xml, tools/i18n-plugin/pom.xml
Allow for compiling with Java 21
Refs: openhab/openhab-distro#1590
=> Bump maven-plugin-plugin to 3.11.0

pom.xml
Allow for compiling with Java 21
Refs: openhab/openhab-distro#1590
=> Bump ecj to 3.36.0

bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/DefaultSystemChannelTypeProvider.java
=> Provide unit hint for system channel type `atmospheric-humidity`

bundles/org.openhab.core.automation.module.script.rulesupport/src/main/java/org/openhab/core/automation/module/script/rulesupport/loader/AbstractScriptFileWatcher.java, bundles/org.openhab.core.config.discovery.usbserial.ser2net/src/main/java/org/openhab/core/config/discovery/usbserial/ser2net/internal/Ser2NetUsbSerialDiscovery.java, bundles/org.openhab.core.model.yaml/src/main/java/org/openhab/core/model/yaml/internal/YamlModelRepositoryImpl.java
minor code cleanup, basically just replacing
```.filter(Optional::isPresent).map(Optional::get)``` by ```.flatMap(Optional::stream)```
=> Use flatMap to simplify map operations

bundles/org.openhab.core.auth.oauth2client/src/main/java/org/openhab/core/auth/oauth2client/internal/OAuthConnector.java, bundles/org.openhab.core.auth.oauth2client/src/main/java/org/openhab/core/auth/oauth2client/internal/OAuthStoreHandlerImpl.java, bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/parser/gson/AbstractGSONParser.java, bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/internal/MediaTypeExtension.java, bundles/org.openhab.core.io.rest/src/test/java/org/openhab/core/io/rest/Stream2JSONInputStreamTest.java, bundles/org.openhab.core.storage.json/src/main/java/org/openhab/core/storage/json/internal/JsonStorage.java, bundles/org.openhab.core.storage.json/src/test/java/org/openhab/core/storage/json/internal/JsonStorageTest.java, bundles/org.openhab.core.storage.json/src/test/java/org/openhab/core/storage/json/internal/PersistedTransformationMigratorTest.java, bundles/org.openhab.core.storage.json/src/test/java/org/openhab/core/storage/json/internal/ThingStorageEntityMigratorTest.java, bundles/org.openhab.core/src/main/java/org/openhab/core/library/types/DateTimeType.java
Between Java 17 and Java 21, serialization of Date has changed due to CLDR 42 which uses a narrow non-breaking space.
To ease switching JDK versions, the serialization format is explicitly set to the Java 17 format.
Refs: #4174, openhab/openhab-addons#16657
This helps only for the configuration settings etc.
```GsonBuilder()``` is used in many places. Maybe we should use a custom implementation which sets the date format in the ctor.
=> GsonBuilder: Explicitly set date format

bundles/org.openhab.core.model.thing/src/org/openhab/core/model/thing/internal/GenericThingProvider.xtend
Fix regression introduced in #4076
Resolve #4201
=> Fix textual things not updating on the first change

bundles/org.openhab.core.persistence/src/main/java/org/openhab/core/persistence/extensions/PersistenceExtensions.java
=> Fix a typo in PersistenceExtensions log message

bom/test/pom.xml, tools/i18n-plugin/pom.xml, tools/upgradetool/pom.xml
* Use jdt.annotation 2.2.100 (i18n tool)
* Use gson 2.10.1 (i18n tool, upgrade tool)
* Use logback 1.3.14 (test)
This PR targets test and tools. Other upgrades will be done together with the next Karaf upgrade.
Upgrading logback should fix a dependabot warning, 
https://github.com/openhab/openhab-core/security/dependabot/77
Hope this does not break anything, as we don't have many tests esp. for the upgradetool.
=> Harmonize library versions

bundles/org.openhab.core.thing/schema/thing/thing-description-1.0.0.xsd
Fixes #4156 
Enables checking if item-type in channel defintion of things
=> Improve thing description XSD

bundles/org.openhab.core.automation.module.script.rulesupport/src/main/resources/OH-INF/i18n/jsr223.properties, bundles/org.openhab.core.test.magic/src/main/resources/OH-INF/i18n/magic.properties, bundles/org.openhab.core.ui/src/main/resources/OH-INF/i18n/chart.properties, bundles/org.openhab.core.voice/src/main/resources/OH-INF/i18n/voice.properties
Looks like a few strings are missing.
There are still some translations for binding.* instead of addon.* - maybe those should be fixed as well.
=> Update i18n property files

bundles/org.openhab.core.addon/schema/addon-1.0.0.xsd, bundles/org.openhab.core.addon/schema/addon-info-list-1.0.0.xsd, bundles/org.openhab.core.config.core/schema/config-description-1.0.0.xsd, bundles/org.openhab.core.thing/schema/update/update-description-1.0.0.xsd, pom.xml
=> Enable spotless for schema XSD

bundles/org.openhab.core.config.discovery.usbserial.windowsregistry/src/main/java/org/openhab/core/config/discovery/usbserial/windowsregistry/internal/WindowsUsbSerialDiscovery.java
Fixes https://github.com/openhab/openhab-core/pull/4224#issuecomment-2119849776
=> Fix exception in WindowsUsbSerialDiscovery

bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/binding/generic/converter/ColorChannelHandler.java
=> Fix brightness in generic ColorChannelHandler

bundles/org.openhab.core.addon.marketplace.karaf/src/main/java/org/openhab/core/addon/marketplace/karaf/internal/community/CommunityKarafAddonHandler.java, bundles/org.openhab.core.addon.marketplace/pom.xml, bundles/org.openhab.core.addon.marketplace/src/main/java/org/openhab/core/addon/marketplace/MarketplaceConstants.java, bundles/org.openhab.core.addon.marketplace/src/main/java/org/openhab/core/addon/marketplace/internal/community/CommunityBlockLibaryAddonHandler.java, bundles/org.openhab.core.addon.marketplace/src/main/java/org/openhab/core/addon/marketplace/internal/community/CommunityBundleAddonHandler.java, bundles/org.openhab.core.addon.marketplace/src/main/java/org/openhab/core/addon/marketplace/internal/community/CommunityMarketplaceAddonService.java, bundles/org.openhab.core.addon.marketplace/src/main/java/org/openhab/core/addon/marketplace/internal/community/CommunityRuleTemplateAddonHandler.java, bundles/org.openhab.core.addon.marketplace/src/main/java/org/openhab/core/addon/marketplace/internal/community/CommunityTransformationAddonHandler.java, bundles/org.openhab.core.addon.marketplace/src/main/java/org/openhab/core/addon/marketplace/internal/community/CommunityUIWidgetAddonHandler.java, bundles/org.openhab.core.addon.marketplace/src/main/java/org/openhab/core/addon/marketplace/internal/json/JsonAddonService.java
=> Add support for marketplace transformations

bundles/org.openhab.core.ephemeris/src/main/java/org/openhab/core/ephemeris/internal/EphemerisManagerImpl.java, itests/org.openhab.core.automation.integration.tests/src/main/java/org/openhab/core/automation/integration/test/RuleSimulationTest.java
Fix openhab/openhab-addons#16812
=> Ephemeris: consider the default weekend dayset

bom/runtime/pom.xml, features/karaf/openhab-core/src/main/feature/feature.xml, features/karaf/openhab-tp/src/main/feature/feature.xml, itests/org.openhab.core.model.item.tests/itest.bndrun, itests/org.openhab.core.model.rule.tests/itest.bndrun, itests/org.openhab.core.model.script.tests/itest.bndrun, itests/org.openhab.core.model.thing.tests/itest.bndrun, pom.xml
Finally, the Xtext team released v2.35.0. When we upgraded Karaf, only milestone build M1 was available (and M2 on the day of our upgrade was merged ;-) )....
Now we can go for the release build.
---
* Upgrade Xtext from 2.35.0.M1 to 2.35.0 final release, see release notes: https://eclipse.dev/Xtext/releasenotes.html#/releasenotes/2024/05/28/version-2-35-0
* Upgrade dependencies
* Guava from 33.1.0 to 33.2.0
* Lsp4j from 0.22.0 to 0.23.1
=> Upgrade Xtext to 2.35.0

bundles/org.openhab.core.config.discovery.sddp/src/main/java/org/openhab/core/config/discovery/sddp/SddpDiscoveryService.java
See https://github.com/openhab/openhab-core/pull/4237#issuecomment-2143535345
=> Fix closing bracket in JavaDoc

bundles/org.openhab.core.config.discovery.sddp/src/main/java/org/openhab/core/config/discovery/sddp/SddpDevice.java
SddpDevice provide JavaDoc for fields
=> SddpDevice provide JavaDoc for fields

bundles/org.openhab.core/src/main/java/org/openhab/core/common/PoolBasedSequentialScheduledExecutorService.java, bundles/org.openhab.core/src/test/java/org/openhab/core/common/ThreadPoolManagerTest.java
I did some testing with the new `PoolBasedSequentialScheduledExecutorService` and ended in a deadlock.
The `ScheduledThreadPoolExecutor` used in the background does not spawn new threads as expected.
This PR will call `setCorePoolSize` to spawn new threads or to stop idle threads. 
Additionally this PR does allow a task to be directly executed in case the current threads is from the pool. 
=> Fixed a deadlock in the PoolBasedSequentialScheduledExecutorService

bundles/org.openhab.core.voice/src/main/java/org/openhab/core/voice/internal/VoiceConsoleCommandExtension.java
Allow define interpreters to use on the console command `voice interpret`.
Added param --hlis which allows a comma separated list of interpreter ids.
=> [voice] Add hlis argument to interpret command

bundles/org.openhab.core/src/main/resources/OH-INF/i18n/i18n.properties
=> Fix description of the location setting

pom.xml
This may help with fixing or diagnosing read timouts during deployment.
=> Upgrade maven-deploy-plugin to 3.1.2

bundles/org.openhab.core.model.yaml/src/main/java/org/openhab/core/model/yaml/internal/YamlModelRepositoryImpl.java
See https://community.openhab.org/t/openhab-4-2-milestone-discussion/154316/185
=> Fix AccessDeniedException in YamlModelRepository

bundles/org.openhab.core.io.console/src/main/java/org/openhab/core/io/console/internal/extension/AddonConsoleCommandExtension.java
=> Fix dynamic binding of AddonService to ConsoleCommandExtension service

bundles/org.openhab.core.model.thing/src/org/openhab/core/model/thing/internal/GenericItemChannelLinkProvider.java
=> Add default scope to profile when loading items file

bundles/org.openhab.core.thing/src/test/java/org/openhab/core/thing/binding/AbstractStorageBasedTypeProviderTest.java
Related to #4315 
This fails until #4317 is merged (as expected).
=> Add test to ensure full mapping of types in AbstractStorageBasedProvider

bom/compile/pom.xml, bom/runtime/pom.xml, features/karaf/openhab-tp/src/main/feature/feature.xml, itests/org.openhab.core.config.discovery.mdns.tests/itest.bndrun
See [changelog 3.5.10](https://github.com/jmdns/jmdns/releases/tag/3.5.10) (and [changelog 3.5.11](https://github.com/jmdns/jmdns/releases/tag/3.5.11) and [changelog 3.5.12](https://github.com/jmdns/jmdns/releases/tag/3.5.12))
=> Upgrade to JmDNS 3.5.12

bundles/org.openhab.core.model.rule.runtime/src/org/openhab/core/model/rule/runtime/internal/DSLRuleProvider.java, bundles/org.openhab.core.model.rule/src/org/openhab/core/model/rule/Rules.xtext
=> RulesDSL: add DateTimeTrigger offset

bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/util/ActionInputsHelper.java, bundles/org.openhab.core.io.net/src/test/java/org/openhab/core/io/net/http/BaseHttpUtilTest.java, bundles/org.openhab.core.io.net/src/test/java/org/openhab/core/io/net/http/HttpRequestBuilderTest.java
`&` is not allowed in `@author` tags.
=> Fix JavaDoc

bundles/org.openhab.core.config.core/src/main/java/org/openhab/core/config/core/ConfigDescriptionParameter.java
Refs https://github.com/openhab/openhab-webui/pull/2832.
=> ConfigDescriptionParameter: Document how to allow any step size

bom/compile/pom.xml, bom/runtime/pom.xml, features/karaf/openhab-tp/src/main/feature/feature.xml, itests/org.openhab.core.addon.tests/itest.bndrun, itests/org.openhab.core.auth.oauth2client.tests/itest.bndrun, itests/org.openhab.core.automation.integration.tests/itest.bndrun, itests/org.openhab.core.automation.module.core.tests/itest.bndrun, itests/org.openhab.core.automation.module.script.tests/itest.bndrun, itests/org.openhab.core.automation.module.timer.tests/itest.bndrun, itests/org.openhab.core.automation.tests/itest.bndrun, itests/org.openhab.core.config.core.tests/itest.bndrun, itests/org.openhab.core.config.discovery.mdns.tests/itest.bndrun, itests/org.openhab.core.config.discovery.tests/itest.bndrun, itests/org.openhab.core.config.discovery.usbserial.linuxsysfs.tests/itest.bndrun, itests/org.openhab.core.config.discovery.usbserial.tests/itest.bndrun, itests/org.openhab.core.ephemeris.tests/itest.bndrun, itests/org.openhab.core.io.rest.core.tests/itest.bndrun, itests/org.openhab.core.model.item.tests/itest.bndrun, itests/org.openhab.core.model.rule.tests/itest.bndrun, itests/org.openhab.core.model.script.tests/itest.bndrun, itests/org.openhab.core.model.thing.tests/itest.bndrun, itests/org.openhab.core.storage.json.tests/itest.bndrun, itests/org.openhab.core.thing.tests/itest.bndrun, itests/org.openhab.core.voice.tests/itest.bndrun, tools/i18n-plugin/pom.xml
* Upgrade XStream from 1.4.20 to 1.4.21, fixes CVE-2024-47072. 
See changelog at https://x-stream.github.io/changes.html#1.4.21
=> Upgrade XStream to 1.4.21

bundles/org.openhab.core.persistence/src/test/java/org/openhab/core/persistence/internal/PersistenceManagerTest.java
Related to https://github.com/openhab/openhab-core/pull/4468
@holgerfriedrich for your review
=> Tests for persistence exclusion configuration

.github/workflows/ci-build.yml, README.md, pom.xml
To be delayed until 4.3 is released.
=> Remove Java 17 build, switch to 21

bundles/org.openhab.core.audio/src/main/java/org/openhab/core/audio/AudioFormat.java, bundles/org.openhab.core.audio/src/main/java/org/openhab/core/audio/AudioHTTPServer.java, bundles/org.openhab.core.audio/src/main/java/org/openhab/core/audio/URLAudioStream.java, bundles/org.openhab.core.audio/src/main/java/org/openhab/core/audio/internal/AudioManagerImpl.java, bundles/org.openhab.core.audio/src/main/java/org/openhab/core/audio/internal/javasound/JavaSoundAudioSink.java
From 24 to 2. Remains deprecated usage of FixedLengthAudioStream
=> Warning chase in org.openhab.core.audio

bundles/org.openhab.core.model.core/.classpath, bundles/org.openhab.core.model.item.ide/.classpath, bundles/org.openhab.core.model.item.runtime/.classpath, bundles/org.openhab.core.model.item/.classpath, bundles/org.openhab.core.model.lsp/.classpath, bundles/org.openhab.core.model.persistence.ide/.classpath, bundles/org.openhab.core.model.persistence.runtime/.classpath, bundles/org.openhab.core.model.persistence/.classpath, bundles/org.openhab.core.model.rule.ide/.classpath, bundles/org.openhab.core.model.rule.runtime/.classpath, bundles/org.openhab.core.model.rule/.classpath, bundles/org.openhab.core.model.script.ide/.classpath, bundles/org.openhab.core.model.script.runtime/.classpath, bundles/org.openhab.core.model.script/.classpath, bundles/org.openhab.core.model.sitemap.ide/.classpath, bundles/org.openhab.core.model.sitemap.runtime/.classpath, bundles/org.openhab.core.model.sitemap/.classpath, bundles/org.openhab.core.model.thing.ide/.classpath, bundles/org.openhab.core.model.thing.runtime/.classpath, bundles/org.openhab.core.model.thing/.classpath, bundles/pom.xml
Model generation was pinned to Java 17, as Xtend generator caused issues at the time we introduced Java 21.
After the last updates, this seems no longer be the case.
References:
- https://github.com/openhab/openhab-core/pull/4514#discussion_r1895586941
- #4161
=> Remove workaround for Xtend/Java21

bundles/org.openhab.core.audio/pom.xml, bundles/org.openhab.core.io.jetty.certificate/pom.xml, bundles/org.openhab.core.io.monitor/pom.xml, bundles/org.openhab.core.io.transport.modbus/pom.xml, itests/pom.xml, pom.xml, tools/archetype/binding/pom.xml, tools/upgradetool/pom.xml
* sortpom-maven-plugin to 4.0.0 (breaking change) https://github.com/Ekryd/sortpom?tab=readme-ov-file#news
* maven-clean-plugin to 3.4.0 https://github.com/apache/maven-clean-plugin/releases/tag/maven-clean-plugin-3.4.0
* maven-deploy-plugin to 3.1.3 https://github.com/apache/maven-deploy-plugin/releases/tag/maven-deploy-plugin-3.1.3
* maven-enforcer-plugin to 3.5.0 https://github.com/apache/maven-enforcer/releases
* maven-install-plugin to 3.1.3 https://github.com/apache/maven-install-plugin/releases
* maven-plugin-plugin to 3.15.1
* license-maven-plugin to 4.6 https://github.com/mathieucarbou/license-maven-plugin/releases
* maven-jar-plugin to 3.4.2 https://github.com/apache/maven-jar-plugin/releases/tag/maven-jar-plugin-3.4.2
* maven-archetype-plugin to 3.3.1
* maven-dependency-plugin …
=> Upgrade plugins

bundles/org.openhab.core.config.core/src/main/java/org/openhab/core/config/core/ConfigParser.java, bundles/org.openhab.core.config.core/src/test/java/org/openhab/core/config/core/internal/validation/ConfigValidationExceptionTest.java, bundles/org.openhab.core.io.rest.sitemap/src/main/java/org/openhab/core/io/rest/sitemap/internal/SitemapResource.java, bundles/org.openhab.core.io.transport.modbus/src/main/java/org/openhab/core/io/transport/modbus/internal/ModbusPoolConfig.java, bundles/org.openhab.core.io.websocket/src/main/java/org/openhab/core/io/websocket/log/LogWebSocket.java, bundles/org.openhab.core.persistence/src/main/java/org/openhab/core/persistence/extensions/PersistenceExtensions.java, bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/binding/generic/converter/ColorChannelHandler.java, bundles/org.openhab.core.transform/src/main/java/org/openhab/core/transform/actions/Transformation.java, bundles/org.openhab.core/src/main/java/org/openhab/core/internal/common/AbstractInvocationHandler.java, bundles/org.openhab.core/src/main/java/org/openhab/core/library/types/QuantityTypeArithmeticGroupFunction.java
* Fix JavaDoc build
* Address SAT warnings introduced recently
* Address some of the deprecation warnings seen during compilation
=> Fix JavaDoc, SAT and depreacation warnings

bom/compile/pom.xml, bom/runtime/pom.xml, features/karaf/openhab-tp/src/main/feature/feature.xml
Upgrade hivemq-mqtt-client from 1.3.3 to 1.3.5
Changelog:
https://github.com/hivemq/hivemq-mqtt-client/releases/tag/v1.3.4 https://github.com/hivemq/hivemq-mqtt-client/releases/tag/v1.3.5
Upgrade netty from 4.1.104 to 4.1.118
Changelog:
https://netty.io/news/
=> Upgrade hivemq-mqtt-client to 1.3.5, Netty to 4.1.118.Final

bundles/org.openhab.core.config.core/src/main/java/org/openhab/core/config/core/ConfigUtil.java, bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/internal/addons/AddonResource.java, bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/internal/service/ConfigurableServiceResource.java, bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/internal/thing/ThingResource.java, itests/org.openhab.core.io.rest.core.tests/src/main/java/org/openhab/core/io/rest/core/internal/service/ConfigurableServiceResourceOSGiTest.java
Partly reverts 8e597bde76ef17a7a4d47b1a39b8e44060c43e36.
This restores the semantics of `ConfigUtil::normalizeType` that was in place before #4505 was merged.
This should fix the NPE which crashes the add-on build.
```
java.lang.NullPointerException: Cannot invoke "Object.getClass()" because "value" is null
at org.openhab.core.config.core.ConfigUtil.normalizeType(ConfigUtil.java:197)
at org.openhab.core.config.core.ConfigUtil.normalizeTypes(ConfigUtil.java:234)
```
=> Revert ConfigUtil::normalizeType and fix null annotations

README.md
Credit for the build command to @holgerfriedrich 
https://community.openhab.org/t/potential-problem-with-eclipse-and-latest-core/162024/12
=> Add a quicker build instruction in README

bundles/org.openhab.core.semantics/model/generateTagClasses.groovy, bundles/org.openhab.core.semantics/pom.xml
This upgrade is needed so it would run on Java21.
Also change the generated header to `/*` instead of `/**`
=> Upgrade Groovy to 3.0.23

bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/fileconverter/AbstractThingFileGenerator.java
Keep original order of channels
=> File format generator: do not change order of thing channels

bundles/org.openhab.core.model.rule/src/org/openhab/core/model/rule/jvmmodel/RulesJvmModelInferrer.xtend, bundles/org.openhab.core.model.script/src/org/openhab/core/model/script/jvmmodel/ScriptJvmModelInferrer.xtend
* Handle deprecation of JvmTypesBuilder::newTypeRef
This addresses an open topic from #4578,
https://github.com/openhab/openhab-core/pull/4578#issuecomment-2628896972,
and fixes ~30 warnings.
=> Fix Xtend warnings

bom/compile/pom.xml
Remove inconsistency by using latest version also in the compile bom.
=>  Document use of older nrjavaserial in compile bom

bom/compile/pom.xml, bom/runtime/pom.xml, bundles/org.openhab.core.io.transport.modbus/pom.xml, features/karaf/openhab-core/src/main/feature/feature.xml, features/karaf/openhab-tp/src/main/feature/feature.xml, pom.xml, tools/upgradetool/pom.xml
* Upgrade jose4j for 0.9.5 to 0.9.6 https://bitbucket.org/b_c/jose4j/wiki/Release%20Notes
* Upgrade commons-io from 2.17.0 to 2.18.0 https://commons.apache.org/proper/commons-io/changes-report.html#a2.18.0
* Upgrade commons-net from 3.9.0 to 3.11.1 https://commons.apache.org/proper/commons-net/changes-report.html#a3.11.1
* upgradetool: Upgrade commons-cli from 1.5.0 to 1.9.0
=> Upgrade dependencies

bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/internal/ThingManagerImpl.java, pom.xml
* Upgrade plexus-compiler-eclipse from 2.12.1 to 2.15.0 https://github.com/codehaus-plexus/plexus-compiler/releases
* **Require maven 3.9.6**, this is enforced as required by plexus-compiler
* Upgrade ecj from 3.39.0 to 3.41.0
* Minor adaption of ThingManagerImpl to allow for ecj > 3.39
=> Upgrade plexus-compiler-eclipse and ecj, req. Maven >= 3.9.6

bom/compile/pom.xml, bom/runtime/pom.xml
* remove duplicate import
* add apiguardian-api, a transitive dependeny of junit, to compile bom to avoid JavaDoc warning
=> Adjust dependencies to fix JavaDoc build

bundles/org.openhab.core.auth.oauth2client/src/main/java/org/openhab/core/auth/oauth2client/internal/OAuthClientServiceImpl.java
=> OAuth prevent concurrent token read / refresh

bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/internal/ThingManagerImpl.java
Issue reported here: https://github.com/openhab/openhab-addons/issues/18311#issuecomment-2709903476
A Thing that's not ready because its bridge is disabled should not hold up the startlevel.
=> Allow startlevel to increase past 80 when a bridge is disabled

.github/workflows/ci-build.yml
* GitHub Action for build and test is split up:
* build: spotless, build, test, itest
* sat: build, sat (checkstyle, pmd, spotbugs)
* javadoc: build javadoc to make sure it does not break
This reduces the build time from ~18min to ~13min, using 3 runners in parallel.
The initial idea was to split SAT from compilation. This works for checkstyle and PMD, but not for spotbugs (which requires compilation). So, compilation is done on both runners, but with different focus on checks and tests.
JavaDoc is new, and may prevent that we break core javadoc build from time to time.
Remark: Right now, SAT is the slowest part. Any idea what to save on this one, would speed up the build.
Skipping build completely with maven.main.skip and disabling the compilation of the generated code via profile did …
=> Speedup Build

bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/module/handler/ItemCommandTriggerHandler.java, bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/module/handler/ItemStateTriggerHandler.java, bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/module/handler/ThingStatusTriggerHandler.java, bundles/org.openhab.core.automation/src/main/resources/OH-INF/automation/moduletypes/ItemTriggers.json, bundles/org.openhab.core.automation/src/main/resources/OH-INF/automation/moduletypes/ThingTriggers.json, bundles/org.openhab.core.automation/src/main/resources/OH-INF/i18n/automation.properties
=> Allow using '*' and '?' as wildcards in Item state and command triggers

bundles/org.openhab.core.model.yaml/src/main/java/org/openhab/core/model/yaml/YamlModelListener.java, bundles/org.openhab.core.model.yaml/src/main/java/org/openhab/core/model/yaml/internal/YamlModelRepositoryImpl.java, bundles/org.openhab.core.model.yaml/src/main/java/org/openhab/core/model/yaml/internal/semantics/YamlSemanticTagProvider.java, bundles/org.openhab.core.model.yaml/src/test/java/org/openhab/core/model/yaml/internal/YamlModelRepositoryImplTest.java
Each YAML element provider can now define which YAML file versions it is applicable to and whether it is deprecated or not.
Related to #3666
=> YAML configuration: add basic version management

bundles/org.openhab.core.config.core/src/main/java/org/openhab/core/config/core/ConfigUtil.java
Regression from #4657
Fix #4714
=> Fix NPE in ConfigUtil

bundles/org.openhab.core.model.item/src/org/openhab/core/model/item/internal/fileconverter/DslItemFileConverter.java
Fix an issue discovered by @jimtng when a metadata configuration value is of a type not supported by the DSL syntax for items.
In that case, a warning is now logged and the configuration parameter is ignored.
=> [DSL generator] Check that metadata config value type is supported

bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/Thing.java, bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/binding/builder/ThingBuilder.java
=> Add Javadoc for new equipment tag setters

bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/internal/fileformat/FileFormatResource.java, bundles/org.openhab.core.model.yaml/pom.xml, bundles/org.openhab.core.model.yaml/src/main/java/org/openhab/core/model/yaml/YamlElement.java, bundles/org.openhab.core.model.yaml/src/main/java/org/openhab/core/model/yaml/YamlModelRepository.java, bundles/org.openhab.core.model.yaml/src/main/java/org/openhab/core/model/yaml/internal/YamlModelRepositoryImpl.java, bundles/org.openhab.core.model.yaml/src/main/java/org/openhab/core/model/yaml/internal/semantics/YamlSemanticTagDTO.java, bundles/org.openhab.core.model.yaml/src/main/java/org/openhab/core/model/yaml/internal/things/YamlChannelDTO.java, bundles/org.openhab.core.model.yaml/src/main/java/org/openhab/core/model/yaml/internal/things/YamlThingDTO.java, bundles/org.openhab.core.model.yaml/src/main/java/org/openhab/core/model/yaml/internal/things/YamlThingProvider.java, bundles/org.openhab.core.model.yaml/src/main/java/org/openhab/core/model/yaml/internal/things/fileconverter/YamlThingFileConverter.java, bundles/org.openhab.core.model.yaml/src/main/java/org/openhab/core/model/yaml/internal/util/YamlElementUtils.java, bundles/org.openhab.core.model.yaml/src/test/java/org/openhab/core/model/yaml/internal/things/YamlChannelDTOTest.java, bundles/org.openhab.core.model.yaml/src/test/java/org/openhab/core/model/yaml/internal/things/YamlThingDTOTest.java, bundles/org.openhab.core.model.yaml/src/test/java/org/openhab/core/model/yaml/test/FirstTypeDTO.java, bundles/org.openhab.core.model.yaml/src/test/java/org/openhab/core/model/yaml/test/SecondTypeDTO.java, bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/fileconverter/AbstractThingFileGenerator.java
This PR adds the support of things in a YAML configuration file.
Related to #3666
=> YAML configuration: add support for things

bundles/org.openhab.core.model.thing/src/org/openhab/core/model/thing/internal/fileconverter/DslThingFileConverter.java, bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/fileconverter/AbstractThingFileGenerator.java
Consider the provided list of things to determine if a thing is presented as bridge or thing.
=> [DSL generator] Consider a bridge thing as bridge if it contains things

bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/DefaultSystemChannelTypeProvider.java
See https://github.com/openhab/openhab-core/pull/4745
=> Add Property.Info tag for media channel types

bundles/org.openhab.core.addon.marketplace.karaf/src/main/java/org/openhab/core/addon/marketplace/karaf/internal/community/CommunityKarafAddonHandler.java, bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/parser/jackson/AbstractJacksonYAMLParser.java, bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/parser/jackson/TemplateYAMLParser.java, bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/parser/ValidationException.java, bundles/org.openhab.core.ephemeris/src/main/java/org/openhab/core/ephemeris/internal/EphemerisManagerImpl.java, bundles/org.openhab.core.io.websocket/src/main/java/org/openhab/core/io/websocket/log/LogWebSocket.java, bundles/org.openhab.core.model.core/src/main/java/org/openhab/core/model/core/internal/ModelRepositoryImpl.java, bundles/org.openhab.core.model.yaml/src/main/java/org/openhab/core/model/yaml/internal/YamlModelRepositoryImpl.java, bundles/org.openhab.core.persistence/src/main/java/org/openhab/core/persistence/QueryablePersistenceService.java, bundles/org.openhab.core.semantics/src/main/java/org/openhab/core/semantics/internal/SemanticsServiceImpl.java, bundles/org.openhab.core/src/main/java/org/openhab/core/internal/library/unit/CurrencyConverter.java, bundles/org.openhab.core/src/main/java/org/openhab/core/items/GenericItem.java
fixing a few warnings added in the recent commits, should not include any functional change
=> Cleanup: Java21, SAT

.github/dependabot.yml
This is a first step towards automating plugin and dependency updates. Dependabot will create PRs (which will still need review, no use of auto-merge intended!).
For GHA this will likely not require more configuration.
For Maven, I expect a bit more tuning, as we typically upgrade a lot of dependencies together/in sync with Karaf.
Not sure if I should add ignore statements here or answer the PRs with an ignore package comment. Let's try how this works out.
=> Enable Dependabot PRs

.github/workflows/ci-build.yml
* This restores functionality we had before we migrated the PR builds to GitHub Actions.
* Implement rebuild in ci_build workflow to make PR validation pass
* Remove label rebuild at the end of the workflow
The PR includes the latest fix from add-ons repo to make it work for the status check, see openhab/openhab-addons#18629.
=> [GHA] Allow rebuild using label rebuild

bundles/org.openhab.core.io.http.auth/pages/authorize.html, bundles/org.openhab.core.io.http.auth/src/main/resources/messages.properties
Resolve https://github.com/openhab/openhab-webui/issues/3161
=> Create API Token: add regex validation to html input

bundles/org.openhab.core/src/main/java/org/openhab/core/items/events/ItemEventFactory.java
=> Fix inconsistent payload field name for ItemStateUpdatedEvent lastUpdate -> lastStateUpdate

.github/workflows/rebuild.yml
Rebuild still did not work on PRs from forked repost.
This is to protect the repo from malicious PRs.
The way to do it is basically, to use the `pull_request_target` instead of `pull_request` (which always runs on read-only permissions).
This needs to be done carefully, see
https://securitylab.github.com/resources/github-actions-preventing-pwn-requests/
Permissions have been reduced to the necessary ones. Persistence of checkout credentials has been disabled.
Regression of 
#4739 
#4785
=> [GHA] Permit rebuild from forks

bundles/org.openhab.core.io.rest/src/main/java/org/openhab/core/io/rest/internal/resources/RootResource.java, bundles/org.openhab.core.io.rest/src/main/java/org/openhab/core/io/rest/internal/resources/beans/RootBean.java
=> [rest] Add timezone information to root resource

bundles/org.openhab.core.semantics/pom.xml
* Replace groovy-maven-plugin by gmavenplus-plugin
* Upgrade groovy-all from 3.0.25 to 4.0.27
groovy-maven-plugin has not been updated for over 5 years, see https://mvnrepository.com/artifact/org.codehaus.gmaven/groovy-maven-plugin/2.1.1.
This change is only visible if profile `generate-tag-classes` is set and will not be validated by CI.
Refs: openhab/openhab-distro#1756
=> Use gmavenplus-plugin

itests/org.openhab.core.config.discovery.usbserial.linuxsysfs.tests/itest.bndrun
Itests are still failing silently.
This seems to happen if the feature verification passes, but the itest has issues resolving bundles.
Github hides this output and marks the test as passed.
You can find the output in Jenkins logs, just look for `Unresolved requirement` in 
https://ci.openhab.org/job/openHAB-Core/154/consoleText
=> Resolve runbundles of linuxsysfs itest

pom.xml
Property `oh.java.version` was removed in #4161, but is still used in `features/karaf/pom.xml`.
With some configurations of the dev machine, this leads to wrong javase being pulled in, causing the verification to fail.
This PR reverts this part of #4161.
=> Set property oh.java.version

bundles/org.openhab.core.addon/src/main/java/org/openhab/core/addon/internal/JarFileAddonService.java
This fixes the following warning during build:
```
[INFO] --- bnd:7.1.0:bnd-process (default) @ org.openhab.core.addon ---
[WARNING] openhab-core\bundles\org.openhab.core.addon\pom.xml [0:0]: Invalid component name: JAR-File add-on service
```
Other component names do not contain spaces, I changed that to get rid of the warning.
Not sure about possible side effects.
=> [addonservice] Use valid component name

tools/upgradetool/pom.xml
Regression from #4855.
Fixes #4870.
Gson dependency was implicitly given, but counted as "provided" because it is part of the runtime bom.
However, upgradetool does not use this and is not run during the tests.
=> Fix upgradetool dependencies, regression

bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/RuleEngineImpl.java
This should make debugging of problems (e.g. #4814) easier.
=> [automation] Add logging to script actions/conditions pre-compilation

bundles/org.openhab.core.model.core/src/main/java/org/openhab/core/model/core/internal/folder/FolderObserver.java
=> Fix NPE in FolderObserver

bundles/org.openhab.core.model.core/src/main/java/org/openhab/core/model/core/internal/folder/FolderObserver.java
Related to #3823
Replaces #4444
If the sub-folder where models are supposed to be found does not exist, the service is marked as ready anyway. If not, start level 100 could be never reached at OH startup.
=> Fix ready marker not set for model when folder is missing

bom/runtime/pom.xml
This was missed in last Karaf upgrade #4932.
=> Bump osgi.service.jdbc to 1.1.0

bom/compile/pom.xml
We had different versions in compile bom and runtime.
Sync to 1.0.4.
Refs #4949
=> Use aries.javax.jax.rs-api 1.0.4

bom/compile/pom.xml, bom/runtime/pom.xml, features/karaf/openhab-tp/src/main/feature/feature.xml
* Upgrade jbbp from 1.4.1 to 3.0.1, changelog: https://github.com/raydac/java-binary-block-parser?tab=readme-ov-fie#change-log
Depends-on openhab/openhab-osgiify#72
=> Upgrade jbbp to 3.0.1

bom/compile/pom.xml, bom/runtime/pom.xml, features/karaf/openhab-tp/src/main/feature/feature.xml
Upgrade hivemq-mqtt-client from 1.3.5 to 1.3.7.
Changelog:
https://github.com/hivemq/hivemq-mqtt-client/releases/tag/v1.3.7
https://github.com/hivemq/hivemq-mqtt-client/releases/tag/v1.3.6
=> Upgrade hivemq-mqtt-client to 1.3.7

pom.xml
=> Upgrade i18n-maven-plugin to 5.0.1

features/karaf/openhab-tp/src/main/feature/feature.xml
This was updated to a wrong version in #4932.
Downgrade from 3.19.0 to 3.18.0 to sync with Karaf 4.4.8.
=> Downgrade eclipse.osgi to 3.18.0

bom/compile/pom.xml, bom/runtime/pom.xml, features/karaf/openhab-tp/src/main/feature/feature.xml, itests/org.openhab.core.config.discovery.mdns.tests/itest.bndrun
Upgrades jmdns from 3.6.1 to 3.6.2.
Changelogs:
https://github.com/jmdns/jmdns/releases/tag/v3.6.2
This upgrade is intended to solve the issue encountered after upgrade to 3.6.1, see https://github.com/openhab/openhab-core/pull/4997#issuecomment-3240135911
=> Upgrade jmdns to 3.6.2

bom/compile/pom.xml, bom/runtime/pom.xml, features/karaf/openhab-core/src/main/feature/feature.xml, itests/org.openhab.core.addon.tests/itest.bndrun, itests/org.openhab.core.auth.oauth2client.tests/itest.bndrun, itests/org.openhab.core.automation.integration.tests/itest.bndrun, itests/org.openhab.core.automation.module.core.tests/itest.bndrun, itests/org.openhab.core.automation.module.script.tests/itest.bndrun, itests/org.openhab.core.automation.module.timer.tests/itest.bndrun, itests/org.openhab.core.automation.tests/itest.bndrun, itests/org.openhab.core.config.core.tests/itest.bndrun, itests/org.openhab.core.config.discovery.mdns.tests/itest.bndrun, itests/org.openhab.core.config.discovery.tests/itest.bndrun, itests/org.openhab.core.config.discovery.usbserial.linuxsysfs.tests/itest.bndrun, itests/org.openhab.core.config.discovery.usbserial.tests/itest.bndrun, itests/org.openhab.core.config.dispatch.tests/itest.bndrun, itests/org.openhab.core.ephemeris.tests/itest.bndrun, itests/org.openhab.core.io.net.tests/itest.bndrun, itests/org.openhab.core.io.rest.core.tests/itest.bndrun, itests/org.openhab.core.model.item.tests/itest.bndrun, itests/org.openhab.core.model.rule.tests/itest.bndrun, itests/org.openhab.core.model.script.tests/itest.bndrun, itests/org.openhab.core.model.thing.tests/itest.bndrun, itests/org.openhab.core.storage.json.tests/itest.bndrun, itests/org.openhab.core.tests/itest.bndrun, itests/org.openhab.core.thing.tests/itest.bndrun, itests/org.openhab.core.voice.tests/itest.bndrun
* Upgrade io.methvin.directory-watcher from 0.18.0 to 0.19.1
Changelog:
https://github.com/gmethvin/directory-watcher/compare/v0.18.0...v0.19.1
depends on openhab/openhab-osgiify#75
=> Upgrade io.methvin.directory-watcher to 0.19.1

bundles/org.openhab.core.automation.module.media/src/main/java/org/openhab/core/automation/module/media/internal/MediaActionTypeProvider.java, bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/Rule.java, bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/RuleRegistryImpl.java, bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/provider/AutomationResourceBundlesTracker.java, bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/parser/ValidationException.java, bundles/org.openhab.core.config.core/src/main/java/org/openhab/core/config/core/internal/i18n/I18nConfigOptionsProvider.java, bundles/org.openhab.core.io.console/src/test/java/org/openhab/core/io/console/internal/extension/ItemConsoleCommandExtensionTest.java, bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/internal/profile/ProfileTypeResource.java, bundles/org.openhab.core.semantics/src/main/java/org/openhab/core/semantics/SemanticsService.java, bundles/org.openhab.core.test/src/main/java/org/openhab/core/test/internal/java/MissingServiceAnalyzer.java, bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/internal/ThingConfigDescriptionAliasProvider.java, bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/link/ItemChannelLinkRegistry.java, bundles/org.openhab.core.ui.icon/src/test/java/org/openhab/core/ui/icon/AbstractResourceIconProviderTest.java, itests/org.openhab.core.thing.tests/src/main/java/org/openhab/core/thing/internal/CommunicationManagerOSGiTest.java
Use switch expressions and remove some unnecessary `;` characters.
Should not have any effect besides the cleanup.
=> Simplify switch statements, Java 21

pom.xml
Regression of #4991
Inspired by openhab/openhab-addons#19365
=> Fix tests when having spaces in path

bundles/org.openhab.core.model.item/src/org/openhab/core/model/item/internal/GenericMetadataProvider.java
Regression from #4793
@Nadahar @lolodomo 
What about this way to fix it? Or do you want to go with the Iterator approach described by @Nadahar in the forum?
=> Fix ConcurrentModificationException during loading of .items file

bundles/org.openhab.core.semantics/model/SemanticTags.csv
Correction of a small mistake on AirConditioner that puts synonyms in label
=> Semantics file correction
