bundles/org.openhab.core.compat1x/src/main/java/org/openhab/core/library/types/ArithmeticGroupFunction.java
This allows group items who are not exactly the same base item to be included in logic operations, for example a dimmer can now be included in a group switch item.
=> Backport of https://github.com/openhab/openhab/pull/1460

bundles/org.openhab.core.compat1x/META-INF/MANIFEST.MF, bundles/org.openhab.core.compat1x/OSGI-INF/audioaction.xml
This should finally fix https://github.com/openhab/openhab/issues/4604.
=> removed lazy bundle activation to avoid circular dependencies

bundles/org.openhab.core.compat1x/src/main/java/org/openhab/core/library/items/DimmerItem.java
Fix for https://github.com/openhab/openhab/issues/4707. DimmerItem.getStateAs returns 0 if PercentType requested. Tested together with influxdb persistence.
=> Takeover Dimmer.getStateAs implementation from eclipse's core

bundles/org.openhab.core.karaf/ESH-INF/config/config.xml, bundles/org.openhab.core.karaf/META-INF/MANIFEST.MF, bundles/org.openhab.core.karaf/OSGI-INF/featureinstaller.xml, bundles/org.openhab.core.karaf/OSGI-INF/karafextensionservice.xml, bundles/org.openhab.core.karaf/src/main/java/org/openhab/core/karaf/internal/FeatureInstaller.java, bundles/org.openhab.core.karaf/src/main/java/org/openhab/core/karaf/internal/KarafExtensionService.java, bundles/org.openhab.core/src/main/java/org/openhab/core/OpenHAB.java, bundles/org.openhab.ui.dashboard/META-INF/MANIFEST.MF, bundles/org.openhab.ui.dashboard/OSGI-INF/dashboardservice.xml, bundles/org.openhab.ui.dashboard/src/main/java/org/openhab/ui/dashboard/internal/DashboardService.java, bundles/org.openhab.ui.dashboard/src/main/java/org/openhab/ui/dashboard/internal/DashboardServlet.java, bundles/org.openhab.ui.dashboard/templates/index.html, bundles/org.openhab.ui.dashboard/templates/setup.html, bundles/org.openhab.ui.dashboard/web/main.css, features/openhab-core-resources/.project, features/openhab-core-resources/pom.xml, features/openhab-core-resources/src/main/resources/.gitattributes, features/openhab-core-resources/src/main/resources/.gitignore, features/openhab-core-resources/src/main/resources/addons-expert.cfg, features/openhab-core-resources/src/main/resources/addons-minimal.cfg, features/openhab-core-resources/src/main/resources/addons-simple.cfg, features/openhab-core-resources/src/main/resources/addons-standard.cfg, features/openhab-core/src/main/feature/feature.xml, features/pom.xml
* adapted FeatureInstaller to adapt addons info in ConfigAdmin, so that this info is stored in a file
* removed experimental features
* removed package selection from UI as it is meant to be only set once
* introduced new packages: minimal, simple and expert
* introduced a setup page on the dashboard, if no package is set (and thus openHAB is uninitialized)
* added auto-refresh of dashboard to have new entries appear automatically
=> Refactoring of package handling

bundles/org.openhab.core.karaf/src/main/java/org/openhab/core/karaf/internal/FeatureInstaller.java
=> allow spaces in the list of add-ons in addons.cfg

features/openhab-core-resources/src/main/resources/addons-standard.cfg
=> removed rest-docs from standard package

features/p2/feature.xml
=> also removed io.transport.serial from p2 repo

poms/pom.xml, src/sat/README.md
Contains:
- add bindings Maven profile to the Static Code Analysis tool;
- create an empty properties files, that will include configuration of the
checks that will be applied only for bindings;
- short readme file with link to the sat repo.
See https://github.com/openhab/static-code-analysis/issues/58#issuecomment-292948113
Signed-off-by: Svilen Valkanov <svilen.valkanov@musala.com>
=> Add bindings profile to sat.

poms/pom.xml, src/sat/README.md
See https://github.com/openhab/openhab-core/pull/135#issuecomment-292998383
@kaikreuzer I apologize for #135 and for the further complications that it caused, but even after your addition (#136), the OH2 build is failing locally with:
>[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 40.148s
[INFO] Finished at: Tue Apr 11 11:35:24 EEST 2017
[INFO] Final Memory: 73M/721M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.openhab.tools:static-code-analysis:0.0.4:checkstyle (default) on project org.openhab.binding.airquality: Unable to execute mo
jo: An error has occurred in Checkstyle report generation. Failed during checkstyle execution: Failed to get …
=> Remove properties file for sat bindings profile

bundles/org.openhab.core.compat1x.test/.settings/org.eclipse.jdt.groovy.core.prefs
Set Groovy compiler level to "i don't care" so eclipse problems vanish.
=> Set Groovy compiler level to "i don't care" so eclipse problems vanish

bundles/org.openhab.ui.dashboard/META-INF/MANIFEST.MF, bundles/org.openhab.ui.dashboard/OSGI-INF/dashboardservice.xml, bundles/org.openhab.ui.dashboard/src/main/java/org/openhab/ui/dashboard/internal/DashboardService.java
There is now a line with an absolute Url using the primary IPv4 interface about where openHAB is accessible (both for http & https).
=> Made dashboard component to be activated immediately and improved logging

bundles/org.openhab.io.rest.docs/OSGI-INF/swaggerservice.xml, bundles/org.openhab.io.rest.docs/src/main/java/org/openhab/io/rest/docs/internal/RESTDashboardTile.java, bundles/org.openhab.io.rest.docs/src/main/java/org/openhab/io/rest/docs/internal/SwaggerService.java
This should avoid potential circular dependencies at startup as the dashboard tile does not depend on HttpService anymore.
=> moved the swagger servlet registration to its own component

poms/pom.xml
=> switched to Karaf 4.1.2 and Jetty 9.3.14

bundles/org.openhab.ui.dashboard/src/main/java/org/openhab/ui/dashboard/internal/DashboardService.java
This had been accidentially changed to 0..1 through https://github.com/openhab/openhab-core/pull/191.
=> changed cardinality for tiles back to 0..n

poms/pom.xml
This adds the maven versions plugin and makes it possible to automatically update version properties like `esh.version` or `oh2.version` within the pom.xml, e.g. by using the _versions:update-properties_ or _versions:update-property_ goal.
- http://www.mojohaus.org/versions-maven-plugin/update-properties-mojo.html
- http://www.mojohaus.org/versions-maven-plugin/update-property-mojo.html
=> Add versions plugin for automated updating of version properties

bundles/org.openhab.core.compat1x/src/main/java/org/openhab/ui/chart/internal/ChartProviderDelegate.java
The ESH PR https://github.com/eclipse/smarthome/pull/4291 introduced a change in the ChartProvider API.
This commit changes the compat1x `ChartProviderDelegate` to compile with these changes.
This should be merged when a new ESH stable is built, otherwise it would cause build failure of `openhab-core`.
=> [compat1x] Fix ChartProvider API break

pom.xml, poms/pom.xml
Hi there,
these should be the last changes necessary to get the initial release automation process running:
- Update the unleash plugin to the latest version
- Update the versions plugin to the latest version (makes the error-prone version-property mapping obsolete) as with version 2.5 the _set-property_ goal was introduced.
=> Final changes for initial release automation process

bundles/org.openhab.ui.dashboard/ESH-INF/i18n/dashboard.properties, bundles/org.openhab.ui.dashboard/ESH-INF/i18n/dashboard_fr.properties, bundles/org.openhab.ui.dashboard/ESH-INF/i18n/dashboard_nl.properties, bundles/org.openhab.ui.dashboard/META-INF/MANIFEST.MF, bundles/org.openhab.ui.dashboard/src/main/java/org/openhab/ui/dashboard/internal/DashboardService.java, bundles/org.openhab.ui.dashboard/src/main/java/org/openhab/ui/dashboard/internal/DashboardServlet.java, bundles/org.openhab.ui.dashboard/templates/entry.html, bundles/org.openhab.ui.dashboard/templates/index.html, bundles/org.openhab.ui.dashboard/templates/setup.html, bundles/org.openhab.ui.dashboard/templates/warn.html
French version included
Fixes #214
=> Dashboard internationalization

bundles/org.openhab.ui.dashboard/build.properties, bundles/org.openhab.ui.dashboard/src/main/java/org/openhab/ui/dashboard/internal/DashboardService.java, bundles/org.openhab.ui.dashboard/src/main/java/org/openhab/ui/dashboard/internal/DashboardServlet.java
- included ESH-INF to binary
- simplified getLocalizedText method as it was now only called with a null locale
=> fixed dashboard localization

bundles/org.openhab.core.karaf/.classpath, bundles/org.openhab.core.karaf/.settings/org.eclipse.jdt.core.prefs, bundles/org.openhab.core.karaf/src/main/java/org/openhab/core/karaf/internal/FeatureInstaller.java
- upgraded to Java 8
- reduced calls to listInstalledFeatures, which is very expensive
- properly do the calculation of current/target/diff list of addons, when the config changes
- don't log errors when uninstallation fails as this can happen if it is a dependent feature that must not be uninstalled
=> improved feature installer logic

bundles/org.openhab.ui.dashboard/ESH-INF/i18n/dashboard.properties
@lolodomo this fixes the immediate issue.
I do wonder if we should break down `warn.exposed` to three-four substrings. The strings shouldn't be as complicated and the magic anchor should definitely not be part of it. The same goes for other strings. There are also cases like "Select a package:" where I'd suggest to move the colon out of the string. Wdyt?
Signed-off-by: Thomas Dietrich <thomas.dietrich@tu-ilmenau.de> (github: ThomDietrich)
=> Fix crowdin incompatibility

bundles/org.openhab.core.karaf/META-INF/MANIFEST.MF, bundles/org.openhab.core.karaf/src/main/java/org/openhab/core/karaf/internal/FeatureInstaller.java
- wait for config update when online status has changed
- removed static methods and logger
- proper handling of "minimal" feature
- introduced a sync job that checks if everything is installed as expected (which serves as a retry mechanism in case of failed downloads)
fixes https://github.com/openhab/openhab-distro/issues/602
=> Improved the feature installation logic

bundles/org.openhab.ui.dashboard/README.md, bundles/org.openhab.ui.dashboard/src/main/java/org/openhab/ui/dashboard/internal/DashboardService.java, bundles/org.openhab.ui.dashboard/templates/entry.html, bundles/org.openhab.ui.dashboard/templates/index.html
DOMAINNAME, HOSTNAME and HOSTADDRESS special words are supported.
Signed-off-by: Pauli Anttila <pauli.anttila@gmail.com>
=> [Dashboard] support special words in dashboard tile URL's.

poms/pom.xml
The version 0.10.0.b1 was badly chosen - it should have been 0.10.0-b1 instead.
According to Maven versioning, 0.10.0.b1 is a release and thus considered NEWER than any snapshot.
As we include ESH release + snapshot repos in the openHAB snapshot build, this means that 0.10.0-SNAPSHOTS are now ignored and 0.10.0.b1 is used instead. This leads to issues [like this one](https://github.com/openhab/openhab2-addons/pull/3078#issuecomment-359721434).
=> reduce the esh release version to 0.9.0 to make sure that snapshots are taken

poms/pom.xml
No property "${sat.plugin}" exists.
Fix for warning logs in openhab-2 addons project, as it inherits this pom.
Signed-off-by: Svilen Valkanov <svilen.valkanov@musala.com>
=> Changed SAT artifact ID to correct one

pom.xml
The openhab-core POM has two declarations of the directory-maven-plugin resulting in the following warning:
```
[INFO] Scanning for projects...
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for org.openhab.core:pom-bundles:pom:2.3.0-SNAPSHOT
[WARNING] 'build.plugins.plugin.(groupId:artifactId)' must be unique but found duplicate declaration of plugin org.commonjava.maven.plugins:directory-maven-plugin @ org.openhab.core:pom:2.3.0-SNAPSHOT, /home/wouter/git/openhab/openhab-core/pom.xml, line 84, column 21
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for org.openhab.core:pom:pom:2.3.0-SNAPSHOT
[WARNING] 'build.plugins.plugin.(groupId:artifactId)' must be unique but found duplicate declaration of plugin …
```
=> Fix duplicate directory-maven-plugin declaration

bundles/org.openhab.core.compat1x.test/META-INF/MANIFEST.MF, bundles/org.openhab.core.compat1x.test/src/test/java/org/openhab/core/compat1x/internal/TypeMapperTest.java, bundles/org.openhab.core.compat1x/META-INF/MANIFEST.MF, bundles/org.openhab.core.compat1x/src/main/java/org/openhab/core/compat1x/internal/TypeMapper.java
This specifically makes the QuantityType backward compatible and makes it treated as a simple DecimalType in any 1.x add-ons, such as specifically the persistence services.
=> added support for QuantityType in the compatibility layer

poms/tycho/pom.xml
Sync maven settings with IDE settings again.
Found during review in https://github.com/openhab/openhab2-addons/pull/3087#issuecomment-379549320
=> Null annotations: Disable unchecked conversion warning

bundles/org.openhab.io.sound/src/main/java/org/openhab/io/sound/internal/EnhancedJavaSoundAudioSink.java
The current code actually causes output in the shell, not only in the log like:
```
Exception in thread "Thread-62362" java.lang.RuntimeException: Bitstream errorcode 102
at org.openhab.io.sound.internal.EnhancedJavaSoundAudioSink$1.run(EnhancedJavaSoundAudioSink.java:112)
```
I replaced it by proper logging - for this, I had to declare the logger statically.
=> added proper logging in error case

poms/pom.xml
Version 2.8.0 of the unleash-maven-plugin will, in conjunction with another PR that I plan for openhab-distro, reduce the number of options I need to pass for the release build and therefore simplify the release build execution a little bit. It has no side effect on current CI processes and can be directly merged.
=> Update unleash-maven-plugin to version 2.8.0

features/openhab-core/src/main/feature/feature.xml
Resolves https://github.com/openhab/openhab-distro/issues/685.
Replaces https://github.com/openhab/openhab-distro/pull/686
=> grouped features for serial support

poms/pom.xml, poms/tycho/pom.xml
The `esh.releaseVersion` property became obsolete after PR #321. 
openhab/openhab2-addons#3562 should be merged together with this PR.
=> Remove obsolete esh.releaseVersion property

bundles/pom.xml, features/p2/pom.xml, features/repo/pom.xml, pom.xml, poms/tycho/pom.xml
This change makes us independent from any p2 repository for ESH artifacts. It would be a [major pain](https://gitter.im/openhab/openhab-distro?at=5af6f187862c5e33e92c390b) for our automatic build pipeline to publish intermediate results to a p2 site, just to consume it in further build steps again. By relying on pure Maven dependencies, this should be a much easier and cleaner solution.
=> replace ESH p2 update site dependency by plain Maven dependencies

features/openhab-core/src/main/feature/feature.xml
With the change of https://github.com/openhab/openhab-distro/pull/706, I noticed that installing the websocket client during runtime causes the whole UPnP+Jetty stack (including http server) to restart, which causes all kinds of issues.
As the http transport only adds 2 additional bundles (the rest is usually already there), I think it is the better option to simply include those in the core installation already.
=> made http transport part of core installation

bundles/org.openhab.core.compat1x/src/main/java/org/openhab/core/binding/internal/BindingConfigReaderDelegate.java
Don't destroy the stacktrace information of a caught exception that's about to be rethrown.
This arises from my attempts to debug [OH1-Addons issue 5537](https://github.com/openhab/openhab1-addons/issues/5597), where the source of the error is getting lost...
Signed-off-by: Chris Carman <namraccr@gmail.com> (github: 9037568)
=> Don't lose stacktrace when rethrowing

features/openhab-core/src/main/feature/feature.xml
also move out the rule engine from openhab-core and put it in openhab-distro instead
fixes #361
=> include swagger feature directly in rest-docs

bundles/org.openhab.core.compat1x.test/META-INF/MANIFEST.MF, bundles/org.openhab.core.compat1x/META-INF/MANIFEST.MF, bundles/org.openhab.core/META-INF/MANIFEST.MF, bundles/org.openhab.io.jetty.certificate/META-INF/MANIFEST.MF, bundles/org.openhab.io.rest.docs/META-INF/MANIFEST.MF, bundles/org.openhab.io.sound/META-INF/MANIFEST.MF, bundles/org.openhab.ui.basicui/META-INF/MANIFEST.MF, bundles/org.openhab.ui.classicui/META-INF/MANIFEST.MF, bundles/org.openhab.ui.dashboard/META-INF/MANIFEST.MF, bundles/org.openhab.ui.homebuilder/META-INF/MANIFEST.MF, bundles/org.openhab.ui.paperui/META-INF/MANIFEST.MF
See also https://github.com/eclipse/smarthome/issues/5822.
=> Add Automatic-Module-Name entry to manifests

bundles/org.openhab.core.compat1x/src/main/java/org/openhab/core/library/types/DecimalType.java
The constructors of DecimalType in ESH use BigDecimal.valueOf instead of new BigDecimal. Using valueOf is better because the new constuctors causes undesired rounding. For example the value 0.32 becomes: 0.320000000000000006661338147750939242541790008544921875. With valueOf this doesn't happen. This change will make it work the same as the ESH DecimalType
Closes #371
Signed-off-by: Hilbrand Bouwkamp <hilbrand@h72.nl>
=> Changed constructors DecimalType to work the same as ESH DecimalType

features/openhab-core/src/main/feature/feature.xml
related to https://github.com/eclipse/smarthome/pull/5560
=> include rfc2217 support in serial API

poms/pom.xml
=> updated repo.version which is used for the openhab-core repo location in the target platform

poms/pom.xml
@pfink This seems to be missed in the release process - could you somehow add this so that it is automatically increase upon major/minor official releases?
=> updated repo.version to 2.4.x

bundles/org.openhab.core.compat1x.test/.settings/org.eclipse.jdt.core.prefs, bundles/org.openhab.core.compat1x.test/.settings/org.eclipse.jdt.groovy.core.prefs, bundles/org.openhab.core.compat1x.test/.settings/org.eclipse.pde.core.prefs, bundles/org.openhab.core.compat1x.test/META-INF/MANIFEST.MF, bundles/org.openhab.core.compat1x/.settings/org.eclipse.jdt.core.prefs, bundles/org.openhab.core.compat1x/.settings/org.eclipse.pde.core.prefs, bundles/org.openhab.core.karaf/.settings/org.eclipse.jdt.core.prefs, bundles/org.openhab.core.karaf/.settings/org.eclipse.m2e.core.prefs, bundles/org.openhab.core.karaf/.settings/org.eclipse.pde.core.prefs, bundles/org.openhab.core/.settings/org.eclipse.jdt.core.prefs, bundles/org.openhab.core/.settings/org.maven.ide.eclipse.prefs, bundles/org.openhab.io.jetty.certificate/.settings/org.eclipse.jdt.core.prefs, bundles/org.openhab.io.rest.docs/.settings/org.eclipse.jdt.core.prefs, bundles/org.openhab.io.sound/.settings/org.eclipse.jdt.core.prefs, bundles/org.openhab.ui.basicui/.settings/org.eclipse.jdt.core.prefs, bundles/org.openhab.ui.basicui/.settings/org.eclipse.jdt.groovy.core.prefs, bundles/org.openhab.ui.classicui/.settings/org.eclipse.jdt.core.prefs, bundles/org.openhab.ui.classicui/.settings/org.eclipse.jdt.groovy.core.prefs, bundles/org.openhab.ui.dashboard/.settings/org.eclipse.jdt.core.prefs, bundles/org.openhab.ui.dashboard/.settings/org.eclipse.pde.core.prefs, bundles/org.openhab.ui.paperui/.settings/org.eclipse.jdt.core.prefs, bundles/org.openhab.ui.paperui/.settings/org.eclipse.jdt.groovy.core.prefs
Most of the Eclipse project specific settings are unnecessary. They may even cause issues because they have the wrong values or cause issues when the project defaults change one day.
See also: https://github.com/openhab/openhab2-addons/pull/3472
=> Remove Eclipse project specific settings and some Groovy leftovers

poms/pom.xml, poms/tycho/pom.xml
The maven-resources-plugin is used to copy back the generated XML to the OSGI-INF directory so it is on the classpath in tests.
The `outputDirectory` configuration parameter of the maven-scr-plugin is not used because when it is set to `${project.basedir}` it empties the OSGI-INF dir and would remove non-generated SCR XML files.
Fixes #318
=> Fix maven-scr-plugin does not generate XML for DS annotations in test bundles

bundles/org.openhab.core.karaf/src/main/java/org/openhab/core/karaf/internal/FeatureInstaller.java
I came across this by seeing this in my logs:
```
14:19:12.955 [ERROR] [.core.karaf.internal.FeatureInstaller] - Failed retrieving features: null
```
The NPE was triggered by the fact that the `featuresService` field was null, probably due to the component being already deactivated while the async process was still running.
It slightly concerns me that the component has been deactivated (for which I do not see any reason) and we might want to consider to cancel existing jobs instead of continuing them, but that should be the topic of a different PR.
=> fixes potential NPE in async execution

poms/pom.xml
The openhab-core related changes regaring upgrading to Karaf 4.2.1.
Should be merged simultaneously with: https://github.com/openhab/openhab-distro/pull/761.
=> Upgrade to Karaf 4.2.1

features/openhab-core/src/main/feature/feature.xml
This PR makes sure that GSON 2.7 from Eclipse Orbit is present in the distro, so that gson consumers are resolved against this. 
This should address problems like the one described in https://github.com/eclipse/smarthome/issues/6250.
/cc @maggu2810 
=> mandatorily depend on orbit version of gson 2.7

poms/pom.xml
Recently 3.0.0-M1 of the maven-install-plugin was released which now breaks the openhab2-addons build with:
`[ERROR] Failed to execute goal org.apache.maven.plugins:maven-install-plugin:3.0.0-M1:install (default-install) on project openhab2-addons: NoFileAssignedException: The packaging plugin for this project did not assign a main file to the project but it has attachments. Change packaging to 'pom'. -> [Help 1]`
=> Set maven-install-plugin version to 2.5.2

bundles/org.openhab.core/src/main/java/org/openhab/core/internal/CoreActivator.java
This PR prevents openHAB from being shut down by `System.exit()` calls as long as the core bundle is started (we obviously do not want to prevent the container from ever shutting down).
This is specifically meant as a workaround for https://github.com/eclipse/smarthome/issues/6291, but
makes the server in general more robust wrt malicious third party code.
=> prevent System.exit() calls

features/openhab-core/src/main/feature/feature.xml
This PR brings HTTP Basic Auth to openHAB, using Karaf JAAS feature for authentication.
=> Integrate ESH authentication features in openHAB

poms/pom.xml
I'd assume that our release build failed due to this bug (https://ci.openhab.org/job/openhab2-release/56/) - the url that was used was for uploading artifacts (which requires authentication) and not the one for anonymously downloading artifacts.
=> fixed Bintray release Maven repo url

poms/pom.xml
See also https://community.openhab.org/t/rxtx-fhs-lock-error-opening-lock-file-var-lock-lck-ttyusb0-file-exists-it-is-mine/49117/34
=> upgraded to deps 1.0.35, which includes no_locks nrjavaserial library

bundles/org.openhab.ui.homebuilder/pom.xml
Do not install node in target directory to make sure we do not package node in our jar
Addresses: https://github.com/openhab/openhab-core/pull/417#issuecomment-440162069
I prefer to have it tested before merging, I might have time to test tomorrow.
=> Do not install node in target directory 

features/openhab-core/src/main/feature/feature.xml
Currently, the base openHAB Distro that is started installs the Xtext feature, which [uses Guava 15.0](https://github.com/eclipse/smarthome/blob/master/features/karaf/esh-tp/src/main/feature/feature.xml#L174), so that bundle is installed.
If the user now selects a package that contains the restdocs feature (e.g. "Expert" or "Demo"), [Guava 18](https://github.com/eclipse/smarthome/blob/master/features/karaf/esh-tp/src/main/feature/feature.xml#L233) gets installed, which causes the whole distro to more or less reboot, causing all kinds of issues in the log and briefly deactivating the HTTP server as well, so that the UI might just refresh when the server is not responding - all very undesired effects.
This PR simply adds Guava 18.0 as a bundle to the base installation, so that no restart …
=> fixed version of Guava to use to 18.0

tools/checkstyle.properties
The openhab2-addons [build fails](https://travis-ci.org/openhab/openhab2-addons/builds/468802512?utm_source=github_status&utm_medium=notification) after the 2.4.0 release because this regex was not updated:
```
[INFO] --- sat-plugin:0.5.0:report (default) @ org.openhab.binding.airquality ---
[INFO] Individual report appended to summary report.
[ERROR] Code Analysis Tool has found: 
1 error(s)! 
0 warning(s) 
1 info(s)
[ERROR] .binding.airquality/META-INF/MANIFEST.MF:[0]
The manifest version did not match the requirements ^2.4.0
[INFO] Detailed report can be found at: file:////home/travis/build/openhab/openhab2-addons/addons/binding/org.openhab.binding.airquality/target/code-analysis/report.html
```
=> Update SAT regex to 2.5.0 to fix build

poms/pom.xml
The openhab-core related changes for upgrading to Karaf 4.2.2.
Should be merged simultaneously with: https://github.com/openhab/openhab-distro/pull/834.
=> Upgrade Karaf to 4.2.2

bundles/org.openhab.core.storage.mapdb/src/main/java/org/eclipse/smarthome/storage/mapdb/internal/MapDbStorage.java
The `MapDbStorageService` calls the constructor with a `null` classloader if there has been no one supplied.
=> mapdb storage: fix nullness handling

features/karaf/openhab-tp/src/main/feature/feature.xml
- Update californium dependencies to version 1.0.7 (see https://github.com/eclipse/californium/releases/tag/1.0.7)
Closes openhab/openhab2-addons#4733
=> Update californium dependencies to version 1.0.7

features/p2/repo/src/main/filtered-resources/publish-bintray.sh
https://github.com/openhab/openhab-core/pull/483/files#diff-bb30b633524c1fbbf02501e8dc1d360aR48 does not work as Bintray expects x-gzip as a MIME type.
=> fixed version check and content-type of archive

pom.xml
Makes e.g. `org.openhab.ui.dashboard` be exported, which was missing so far.
=> Export all org.openhab packages (except internal ones)

bundles/org.openhab.core.automation.module.script.rulesupport/src/main/java/org/openhab/core/automation/module/script/rulesupport/internal/ScriptedCustomModuleHandlerFactory.java
This will properly register ScriptedCustomtModuleHandlerFactory, so that custom handlers can be used in JSR223 scripts. This corrects the issue at hand, but there appears to be more updates to get scripted automation up to date with ESH PR #[4668](https://github.com/eclipse/smarthome/pull/4468). The way the code sits now (even after this PR), TriggerHandlers appear to need to be added before the TriggerType.
I didn't see any tests to update, and I'm not prepared to add any ATM, but I will look into filling those gaps.
Fixes #517 
Signed-off-by: Scott Rushworth openhab@5iver.com (github: openhab-5iver)
=> Add registration for ScriptedCustomModuleHandlerFactory

pom.xml
The version 1.8.0_25 is know to be incompatible with our code base.
Java > 1.8 should not work with our currently used Xtext version.
Related to: https://github.com/openhab/openhab-core/issues/522
=> check java version range

features/p2/poms/pom.xml, pom.xml
Solves https://github.com/openhab/openhab-core/issues/528
@maggu2810 I very much hope you will approve this change - it makes the existing addons build work again without further issues and it is tedious to resolve them all considering that we anyhow want to change the build system of the addons repos soon. So I consider this PR to be a temporary measure only until we are fully on bnd.
=> (Temporarily) removed  DS requirements generation to make addon repos compile

features/karaf/openhab-core/src/main/feature/feature.xml
See also https://github.com/openhab/openhab2-addons/pull/4832/files#r255013551
=> added commons-net to openhab-base feature

features/p2/poms/pom.xml, features/p2/poms/tycho/pom.xml
I think we can remove some outdated profiles that were used within the old release process.
@kaikreuzer: Could you check?
=> Remove outdated release profiles

bundles/org.openhab.core.automation/src/main/resources/ESH-INF/automation/moduletypes/ItemActions.json
Considering the bundle name has changed recently, changing this type should not be a breaking change
=> [automation] Adapt input type of ItemCommandAction

bundles/org.openhab.core.io.rest.core/src/main/java/org/eclipse/smarthome/io/rest/core/internal/service/ConfigurableServiceResource.java
The property value "service.pid" can use different types:
* String
* String[]
* Collection of String
Only "String" has been supported.
https://github.com/openhab/openhab-core/pull/557 adds support for String[]
https://github.com/openhab/openhab-core/pull/559 removes the support for String[] again and adds support for the Collection type List only.
This commit ensures that String arrays and every collection type is supported, regardless which (valid) type is used by the OSGi framework implementation.
Fixes: https://github.com/eclipse/smarthome/issues/6710
=> handle different possible service PID types

bom/openhab-core-index/pom.xml, demo/app/app.bndrun, itests/itest-common.bndrun
Generates a simple local index that references all the JARs that resides in the bundles target directory.
This way we can trigger that index generation all the time (without building the whole reactor).
=> workround m2e indexer hickup, build local openhab index

demo/app/app.bndrun
As long as jersey-all is used that bundles a dozen of other artifacts,
we have to blacklist the JAX-RS API. Otherwise it will be added on every
new resolve call.
Related to: https://github.com/openhab/openhab-core/issues/576
Related to: https://github.com/openhab/openhab-core/pull/580
=> blacklist API bundle as long as jersey-all is used

bom/runtime/pom.xml, demo/app/app.bndrun, itests/org.openhab.core.audio.tests/itest.bndrun, itests/org.openhab.core.auth.oauth2client.tests/itest.bndrun, itests/org.openhab.core.automation.tests/itest.bndrun, itests/org.openhab.core.compat1x.tests/itest.bndrun, itests/org.openhab.core.config.core.tests/itest.bndrun, itests/org.openhab.core.config.discovery.mdns.tests/itest.bndrun, itests/org.openhab.core.config.discovery.tests/itest.bndrun, itests/org.openhab.core.io.net.tests/itest.bndrun, itests/org.openhab.core.io.rest.core.tests/itest.bndrun, itests/org.openhab.core.model.thing.tests/itest.bndrun, itests/org.openhab.core.tests/itest.bndrun, itests/org.openhab.core.thing.tests/itest.bndrun, itests/org.openhab.core.thing.xml.tests/itest.bndrun, itests/org.openhab.core.transform.tests/itest.bndrun, itests/org.openhab.core.ui.icon.tests/itest.bndrun, itests/org.openhab.core.ui.tests/itest.bndrun, itests/org.openhab.core.voice.tests/itest.bndrun
For the runtime dependencies a template from the EnRoute project has been used. To allow further customization and usages of different Maven scopes, we migrate the template to this repo.
To be more detailed:
* This is just about the runtime BOM, that is currently used for the demo application and the integration tests.
* I did not add any new dependencies, I just integrated the ones that has been declared by a POM out of our control.
=> add runtime dependency declarations to project

features/karaf/openhab-core/src/main/feature/feature.xml
Fixes: https://github.com/openhab/openhab-core/issues/614
=> add jackson 1.x to compat1x feature

bundles/org.openhab.core/src/main/java/org/eclipse/smarthome/core/internal/library/unit/UnitInitializer.java, bundles/org.openhab.core/src/main/java/org/eclipse/smarthome/core/library/unit/ImperialUnits.java, bundles/org.openhab.core/src/main/java/org/eclipse/smarthome/core/library/unit/SIUnits.java, bundles/org.openhab.core/src/main/java/org/eclipse/smarthome/core/library/unit/SmartHomeUnits.java, itests/org.openhab.core.tests/src/main/java/org/eclipse/smarthome/core/types/util/UnitUtilsTest.java
Also did some clean up, which is in the first commit. The units are in the second commit.
Related to: https://github.com/openhab/openhab2-addons/pull/4913
=> Added standard gravity and dBm Units

bundles/org.openhab.core/src/main/java/org/eclipse/smarthome/core/library/unit/CustomUnits.java, bundles/org.openhab.core/src/main/java/org/eclipse/smarthome/core/library/unit/ImperialUnits.java, bundles/org.openhab.core/src/main/java/org/eclipse/smarthome/core/library/unit/SIUnits.java, bundles/org.openhab.core/src/main/java/org/eclipse/smarthome/core/library/unit/SmartHomeUnits.java
The change with unit classes parent (#617) causes it to report missing imports of tec.uom.se when using static import. Before the change this was not a problem because the parent class was SmartHomeUnits. This change adds a new parent class for all units.
=> Added new parent class for units to fix import problems.

bundles/org.openhab.core.automation/src/main/resources/ESH-INF/automation/moduletypes/DayOfWeekCondition.json
Remove inconsistent visibility "PUBLIC". This value is not documented (there is only HIDDEN and VISIBLE) and this is the only module type that uses PUBLIC instead of just not setting this value at all.
=> [Automation] DayOfWeekCondition

bundles/org.openhab.core.automation/src/main/resources/ESH-INF/automation/moduletypes/GenericCronTrigger.json
A cron trigger module is actually not that "Generic" and a useful trigger type for a lot of rules.
Therefore I suggest to remove the visibility "HIDDEN" with this PR.
I have also added a context "cronexpression" to the TEXT configuration value, so that UI's can offer a cron expression
selection widget.
(we currently have: 'time','item','script','channel','dayOfWeek','rule')
=> [Automation] GenericCronTrigger

bundles/org.openhab.core.config.core/src/main/java/org/eclipse/smarthome/config/core/ConfigDescriptionParameter.java
Improve javadoc by explaining the different defined context values. 
I have added "rule", "channel", "channeltype" and "cronexpression" as those are used within the automation module.
=> ConfigDescriptionParameter: javadoc getContext()

bundles/org.openhab.core.test/src/main/java/org/eclipse/smarthome/test/SyntheticBundleInstaller.java
On Windows `Paths.get().toString()` will correctly convert "/" to "\\" but this is not a valid resource path for `bundle.getResource()` and the resource will not be found. 
Signed-off-by: Andre <afuechsel@gmail.com>
=> Do not use Paths to concatenate resource paths

bom/test/pom.xml, itests/org.openhab.core.audio.tests/itest.bndrun, itests/org.openhab.core.auth.oauth2client.tests/itest.bndrun, itests/org.openhab.core.automation.tests/itest.bndrun, itests/org.openhab.core.binding.xml.tests/itest.bndrun, itests/org.openhab.core.compat1x.tests/itest.bndrun, itests/org.openhab.core.config.core.tests/itest.bndrun, itests/org.openhab.core.config.discovery.mdns.tests/itest.bndrun, itests/org.openhab.core.config.discovery.tests/itest.bndrun, itests/org.openhab.core.config.discovery.usbserial.tests/itest.bndrun, itests/org.openhab.core.io.http.tests/itest.bndrun, itests/org.openhab.core.io.net.tests/itest.bndrun, itests/org.openhab.core.io.rest.core.tests/itest.bndrun, itests/org.openhab.core.io.rest.tests/itest.bndrun, itests/org.openhab.core.model.thing.tests/itest.bndrun, itests/org.openhab.core.semantics.tests/itest.bndrun, itests/org.openhab.core.tests/itest.bndrun, itests/org.openhab.core.thing.tests/itest.bndrun, itests/org.openhab.core.thing.xml.tests/itest.bndrun, itests/org.openhab.core.ui.icon.tests/itest.bndrun, itests/org.openhab.core.ui.tests/itest.bndrun, itests/org.openhab.core.voice.tests/itest.bndrun
Currently the first exceptions that occur in a Java 11 build are due to Mockito/Byte Buddy being incompatible with Java 11:
```
Mockito cannot mock this class: interface java.lang.Runnable.
Mockito can only mock non-private & non-final classes.
If you're not sure why you're getting this error, please report to the mailing list.
Java               : 11
JVM vendor name    : Oracle Corporation
JVM vendor version : 11.0.1+13
JVM name           : OpenJDK 64-Bit Server VM
JVM version        : 11.0.1+13
JVM info           : mixed mode
OS name            : Linux
OS version         : 4.15.0-1026-gcp
Underlying exception : java.lang.UnsupportedOperationException: Cannot define class using reflection
at org.eclipse.smarthome.test.java.JavaTestTest.waitForAssertShouldRunAfterLastCall_whenAssertionSucc …
```
=> Upgrade Mockito to 2.25.0 for Java 11 compatibility

bom/compile/pom.xml, bom/runtime/pom.xml, demo/app/app.bndrun, features/karaf/openhab-core/src/main/feature/feature.xml, features/karaf/openhab-tp/src/main/feature/feature.xml, itests/org.openhab.core.audio.tests/itest.bndrun, itests/org.openhab.core.auth.oauth2client.tests/itest.bndrun, itests/org.openhab.core.automation.tests/itest.bndrun, itests/org.openhab.core.binding.xml.tests/itest.bndrun, itests/org.openhab.core.compat1x.tests/itest.bndrun, itests/org.openhab.core.config.core.tests/itest.bndrun, itests/org.openhab.core.config.discovery.mdns.tests/itest.bndrun, itests/org.openhab.core.config.discovery.tests/itest.bndrun, itests/org.openhab.core.io.net.tests/itest.bndrun, itests/org.openhab.core.io.rest.core.tests/itest.bndrun, itests/org.openhab.core.model.thing.tests/itest.bndrun, itests/org.openhab.core.storage.json.tests/itest.bndrun, itests/org.openhab.core.tests/itest.bndrun, itests/org.openhab.core.thing.tests/itest.bndrun, itests/org.openhab.core.thing.xml.tests/itest.bndrun, itests/org.openhab.core.transform.tests/itest.bndrun, itests/org.openhab.core.ui.icon.tests/itest.bndrun, itests/org.openhab.core.ui.tests/itest.bndrun, itests/org.openhab.core.voice.tests/itest.bndrun
As long as we depend on the internal Gson packages, we need to use the Gson bundle provided by Eclipse Orbit instead of the official one.
Related to: https://github.com/openhab/openhab-core/pull/641
=> bump Gson to 2.8.2

pom.xml, tools/static-code-analysis/checkstyle/ruleset.properties, tools/static-code-analysis/checkstyle/suppressions.xml, tools/static-code-analysis/pmd/suppressions.properties, tools/static-code-analysis/spotbugs/suppressions.xml
This PR is based on the original SAT configuration of ESH with the following changes:
* configuration is updated for newer SAT versions
* suppressions have been updated for package changes
* extensions have been removed from suppressions
Most manifest checks will not work because SAT currently doesn't check bnd.bnd files or the generated manifest in the target directory (https://github.com/openhab/static-code-analysis/issues/341). But at least this PR enables SAT with most of the checks again. :smile: 
Because of https://github.com/openhab/static-code-analysis/pull/342 SAT 0.6.0 seems unusable.
=> Reenable SAT

bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/RuleEventFactory.java, bundles/org.openhab.core.config.discovery/src/main/java/org/eclipse/smarthome/config/discovery/inbox/events/InboxEventFactory.java, bundles/org.openhab.core.thing/src/main/java/org/eclipse/smarthome/core/thing/events/ThingEventFactory.java, bundles/org.openhab.core.thing/src/main/java/org/eclipse/smarthome/core/thing/firmware/FirmwareEventFactory.java, bundles/org.openhab.core.thing/src/main/java/org/eclipse/smarthome/core/thing/link/events/LinkEventFactory.java, bundles/org.openhab.core/src/main/java/org/eclipse/smarthome/core/events/AbstractEventFactory.java, bundles/org.openhab.core/src/main/java/org/eclipse/smarthome/core/events/Event.java, bundles/org.openhab.core/src/main/java/org/eclipse/smarthome/core/events/EventFactory.java, bundles/org.openhab.core/src/main/java/org/eclipse/smarthome/core/items/events/ItemEventFactory.java, itests/org.openhab.core.thing.tests/src/main/java/org/eclipse/smarthome/core/thing/firmware/FirmwareEventFactoryTest.java
The most changes are straight forward.
For `createEventByType` I assume that the current implementations does not fully follow the API.
```
* @return the created event instance
* @throws Exception if the creation of the event fails
```
* `null` is not an event instance (`instanceof` will fail)
* if the creation fails (so also by an unknown type) an exception should be thrown
=> improve nullness of events

bundles/org.openhab.core.audio/src/main/java/org/eclipse/smarthome/core/audio/internal/AudioConsoleCommandExtension.java, itests/org.openhab.core.audio.tests/src/main/java/org/eclipse/smarthome/core/audio/internal/AudioConsoleTest.java
This is the next Java 11 related issue causing the build to fail when #668 is merged.
The fix helps users and also ensures the unit test works on both Java 8 and 11.
---
On Java 8 a NFE without a message is thrown when creating a BigDecimal with the invalid value. 
On Java 11 the NFE has a message which causes the assertion to fail:
```
TEST audioConsolePlaysFileForASpecifiedSinkWithAnInvalidVolume(org.eclipse.smarthome.core.audio.internal.AudioConsoleTest) <<< ERROR: The given volume was invalid
Expected: null
but: was "Character i is neither a decimal digit number, decimal point, nor \"e\" notation exponential mark."
java.lang.AssertionError: The given volume was invalid
Expected: null
but: was "Character i is neither a decimal digit number, decimal point, nor \"e\" notation exponential …
```
=> Print message instead of null on console when specified play volume is invalid

bundles/org.openhab.core/src/main/java/org/eclipse/smarthome/core/library/types/DateTimeType.java
Since Java 9 ([JDK-8164428](https://bugs.openjdk.java.net/browse/JDK-8164428)) the maximum resolution from the underlying clock is used.
Instead of just milliseconds the resolution can now even be tenth of microseconds.
According to the Type JavaDocs `toFullString()` should return the full string representation of the type to be consumed by `valueOf(String)`.
With the changes in this PR `toFullString()` may return higher resolution date time strings on newer Java versions and `valueOf(value)` is able to parse these.
Code depending on a certain resolution returned by `toFullString()` should use the `format(pattern)` method instead so the resolution will not change.
Fixes #667
=> Increase DateTimeType parsing and formatting precision

pom.xml
This fixes a NPE by the unlesh plugin during a version bump. Cause of the NPE: Unit Tests are skipped during release to speed up the process, but itests won't be part of the reactor then even though its part of the POM hierarchy. This breaks some unleash internals.
=> Handle itests as part of the reactor during release

pom.xml
Hotfix for "unleash plugin not found" during release as suggested by @kaikreuzer. Clean solution is tackled by https://github.com/openhab/openhab-core/pull/555. 
=> Add unleash plugin to pom.xml

features/p2/poms/pom.xml
This should be merged immediately before https://github.com/openhab/openhab2-addons/pull/5026.
=> bump SAT version to 0.6.1 for Tycho builds

bundles/org.openhab.core.automation.module.script/bnd.bnd
Fixes #610. Discussed in #653.
Signed-off-by: Scott Rushworth openhab@5iver.com (github: openhab-5iver)
=> [Automation] Add DynamicImport-Package for scripted automation

itests/org.openhab.core.config.discovery.mdns.tests/src/main/java/org/eclipse/smarthome/config/discovery/mdns/internal/MDNSDiscoveryServiceOSGiTest.java
=> Increase stability of MDNSDiscoveryServiceOSGiTest by increasing timeouts to 5s

itests/org.openhab.core.io.net.tests/src/main/java/org/eclipse/smarthome/io/net/http/HttpRequestBuilderTest.java
=> Avoid ByteBuffer incompatibility when compiling with JDK9+

.travis.yml, pom.xml
* Update enforcer to allow compilation with Java 8, 9, 10 and 11
* Update Travis CI configuration to require the Java 11 build to succeed
---
Depends on #685
=> Require successful Travis CI Java 11 build

bom/runtime/pom.xml
The resolver failed to resolve the commons-net bundle used in the Max Cube Binding itests (https://github.com/openhab/openhab2-addons/pull/5376).
=> Add commons-net to bom

bundles/org.openhab.core/src/main/java/org/eclipse/smarthome/core/library/unit/SmartHomeUnits.java, itests/org.openhab.core.tests/src/main/java/org/eclipse/smarthome/core/types/util/UnitUtilsTest.java
=> Added units kvarh and kvar.

bundles/org.openhab.core.thing.xml/src/main/java/org/eclipse/smarthome/core/thing/xml/internal/ChannelGroupTypeConverter.java, bundles/org.openhab.core.thing.xml/thing-description-1.0.0.xsd, itests/org.openhab.core.thing.xml.tests/src/main/java/org/eclipse/smarthome/core/thing/xml/test/ThingTypesTest.java, itests/org.openhab.core.thing.xml.tests/src/main/resources/test-bundle-pool/ThingTypesTest.bundle/ESH-INF/thing/thing-types.xml
The [linuxinput binding](https://github.com/openhab/openhab2-addons/pull/4629) creates a channelgroup for dynamically created channels.
Currently this results in warnings on binding load:
```
2019-04-04 21:35:58.672 [WARN ] [ig.xml.osgi.XmlDocumentBundleTracker] - The XML document '/ESH-INF/thing/thing-types.xml' in module 'org.openhab.binding.linuxinput' could not be parsed: The node 'channels' is missing!
---- Debugging information ----
class               : org.eclipse.smarthome.core.thing.xml.internal.ChannelGroupTypeXmlResult
required-type       : org.eclipse.smarthome.core.thing.xml.internal.ChannelGroupTypeXmlResult
converter-type      : org.eclipse.smarthome.core.thing.xml.internal.ChannelGroupTypeConverter
path                : /thing-descriptions/channel-group-type
line number …
```
=> Channel groups should not require static channels

bundles/org.openhab.core.thing/src/main/java/org/eclipse/smarthome/core/thing/Bridge.java, bundles/org.openhab.core.thing/src/main/java/org/eclipse/smarthome/core/thing/Thing.java, bundles/org.openhab.core.thing/src/main/java/org/eclipse/smarthome/core/thing/binding/builder/BridgeBuilder.java, bundles/org.openhab.core.thing/src/main/java/org/eclipse/smarthome/core/thing/binding/builder/ThingBuilder.java, bundles/org.openhab.core.thing/src/main/java/org/eclipse/smarthome/core/thing/internal/BridgeImpl.java, bundles/org.openhab.core.thing/src/main/java/org/eclipse/smarthome/core/thing/internal/ThingImpl.java, bundles/org.openhab.core.thing/src/main/java/org/eclipse/smarthome/core/thing/util/ThingHelper.java, bundles/org.openhab.core.thing/src/test/java/org/eclipse/smarthome/core/thing/internal/ThingImplTest.java, itests/org.openhab.core.thing.tests/src/main/java/org/eclipse/smarthome/core/thing/binding/ThingFactoryTest.java, itests/org.openhab.core.thing.tests/src/main/java/org/eclipse/smarthome/core/thing/events/ThingEventFactoryTest.java
- Changed property `channels` from `List<Channel>` to `Map<ChannelUID, Channel>` for faster accessing channels of a thing
- Changed property `things` from `List<Thing>` to `Map<ThingUID, Thing>` for faster accessing things of a bridge
- Added new methods `getChannel(ChannelUID)` and `getThing(ThingUID)`
- Fixed SAT findings (e.g. null annotation on `BridgeImpl`)
I removed the method `getChannelsMutable()` from `ThingImpl` and replaced it by a `addChannel(Channel)` method. Imho the best solution will be to omit this new method too, but unfortunately we need it in the helper class `ThingHelper#addChannelsToThing()`. Any ideas how to get rid of that? It is used only in two places - first one can be refactored completely to make use of the `ThingBuilder`: …
=> [core] Improved thing / bridge performance

bundles/org.openhab.core.automation.module.script/.classpath
This makes the projects compile correctly in the IDE again.
=> remove build path entries for non-existent folders

bundles/org.openhab.core.thing/src/main/java/org/eclipse/smarthome/core/thing/internal/BridgeImpl.java, bundles/org.openhab.core.thing/src/main/java/org/eclipse/smarthome/core/thing/internal/ThingImpl.java
- Partially revert #693
Closes #717 - But did not solve the root cause
=> [core] Revert ThingImpl and BridgeImpl changes as the storage uses those implementations

bundles/org.openhab.core.thing/src/main/java/org/eclipse/smarthome/core/thing/util/ThingHelper.java
- Deprecate method `ensureUnique` - could be removed because of superfluous code. It is never used in the framework and we have a more powerful method available.
=> [core] Deprecated method 'ensureUnique'

bundles/org.openhab.core/src/main/java/org/eclipse/smarthome/core/items/MetadataKey.java
Second part of #704
Signed-off-by: David Gräff <david.graeff@web.de>
=> add default constructor to MetadataKey (Gson deserialization support)

features/p2/poms/pom.xml
For Karaf 4.2.3 release notes, see:
https://issues.apache.org/jira/secure/ReleaseNote.jspa?projectId=12311140&version=12344587
For Karaf 4.2.4 release notes, see:
https://issues.apache.org/jira/secure/ReleaseNote.jspa?version=12344856&projectId=12311140
---
Shoud be merged together with:
* https://github.com/openhab/openhab2-addons/pull/5459
* https://github.com/openhab/openhab-webui/pull/56
* https://github.com/openhab/openhab-distro/pull/900
---
The fix for [KARAF-6077](https://issues.apache.org/jira/browse/KARAF-6077) allows for using the servicemix bundles in openhab2-addons instead of wrapping JARs (see https://github.com/openhab/openhab-core/pull/684#discussion_r270680736).
=> Update Karaf to 4.2.4 in openHAB add-ons Parent POM

bundles/org.openhab.core.boot/src/main/java/org/openhab/core/internal/CoreActivator.java, bundles/org.openhab.core.model.lsp/src/main/java/org/eclipse/smarthome/model/lsp/internal/RuntimeServerModule.java
Xtext 2.17 allows for configuring the LanguageServer exit behavior so the SecurityManager workaround can be removed.
Fixes: https://github.com/eclipse/smarthome/issues/6291
Undos: https://github.com/openhab/openhab-core/pull/409
See also: 
* "Configurable Server Exit Behavior" in the Xtext 2.16.0 [release notes](https://www.eclipse.org/Xtext/releasenotes.html#/releasenotes/2018/12/04/version-2-16-0)
* https://github.com/eclipse/xtext-core/issues/885
=> Configure LanguageServer exit behavior

bundles/pom.xml
This fixes the following warnings on Jenkins builds:
`[WARNING] Failed to getClass for org.apache.maven.plugins.source.SourceJarMojo`
See also: [JENKINS-27372](https://issues.jenkins-ci.org/browse/JENKINS-27372)
=> Attach source JARs without forking to fix Jenkins warnings

bundles/org.openhab.core.automation.module.script.rulesupport/src/main/java/org/openhab/core/automation/module/script/rulesupport/internal/loader/ScriptFileWatcher.java
Currently, the scripts are loaded by ScriptFileWatcher based on the lexicographical order of the absolute paths of the scripts. This makes it difficult to control the load order. This change bases the load order solely on the filename, as was originally used before [ESH/#3855](https://github.com/eclipse/smarthome/pull/3855), and preserves the ability to use scripts with the same filename. This PR resolves https://github.com/OH-Jython-Scripters/openhab2-jython/issues/76.
Scripts will be loaded based on the filename. If more than one script have the same filename, their paths will also be taken into account for the sorting. This is especially helpful with the direcotry structure adopted by the Jython helper libraries. Currently, Community scripts (in a community directory), are being loaded …
=> [JSR223] Sort by filename instead of path

bundles/org.openhab.core.model.script/src/org/eclipse/smarthome/model/script/scoping/ScriptImplicitlyImportedTypes.java
- Import 'SmartHomeUnits' in Script Scope
We need it to solve integration test failures in #737. It somehow got lost or was missing (see also https://github.com/eclipse/smarthome/pull/5961).
```
TEST testToUnit_QuantityType3(org.eclipse.smarthome.model.script.engine.ScriptEngineOSGiTest) <<< ERROR: new  ___ QuantityType(1,  ___ KELVIN)
1. The method or field KELVIN is undefined; line 1, column 20, length 6
2. Bounds mismatch: The type argument <Quantity<?>> is not a valid substitute for the bounded type parameter <T extends Quantity<T>> of the constructor QuantityType<T>(Number, Unit<T>); line 1, column 4, length 12
org.eclipse.smarthome.model.script.engine.ScriptParsingException: new  ___ QuantityType(1,  ___ KELVIN)
1. The method or field KELVIN is undefined; line 1, column 20, length 6 …
```
=> Import 'SmartHomeUnits' in Script Scope

bundles/org.openhab.core.io.rest.sse/src/main/java/org/eclipse/smarthome/io/rest/sse/SseResource.java
We should disable the compression regardless if servlet 3 is used or not. It does not matter which servlet version is used, the client should receive the messages as soon as possible without compression or
buffering.
You can identify the lost SSE feature as soon as you enable the usage of Jetty's GzipHandler.
=> REST SSE: disable compression also if servlet 3 support is present

bundles/org.openhab.core/src/main/java/org/eclipse/smarthome/core/common/registry/AbstractRegistry.java
- Reduced logging level in `AbstractRegistry`
As suggested in https://github.com/eclipse/smarthome/issues/6649#issuecomment-445576363
=> [core] Reduced logging level in 'AbstractRegistry'

bundles/org.openhab.core.thing/src/main/java/org/eclipse/smarthome/core/thing/internal/profiles/RawButtonTogglePlayerProfile.java, bundles/org.openhab.core.thing/src/main/java/org/eclipse/smarthome/core/thing/internal/profiles/RawButtonToggleSwitchProfile.java, bundles/org.openhab.core.thing/src/main/java/org/eclipse/smarthome/core/thing/internal/profiles/RawRockerDimmerProfile.java, bundles/org.openhab.core.thing/src/main/java/org/eclipse/smarthome/core/thing/internal/profiles/RawRockerNextPreviousProfile.java, bundles/org.openhab.core.thing/src/main/java/org/eclipse/smarthome/core/thing/internal/profiles/RawRockerOnOffProfile.java, bundles/org.openhab.core.thing/src/main/java/org/eclipse/smarthome/core/thing/internal/profiles/RawRockerRewindFastforwardProfile.java, bundles/org.openhab.core.thing/src/main/java/org/eclipse/smarthome/core/thing/internal/profiles/SystemOffsetProfile.java, bundles/org.openhab.core.thing/src/main/java/org/eclipse/smarthome/core/thing/internal/profiles/SystemProfileFactory.java, bundles/org.openhab.core.thing/src/main/java/org/eclipse/smarthome/core/thing/profiles/SystemProfiles.java
- Added `RawButtonTogglePlayerProfile`, `RawRockerNextPreviousProfile` and `RawRockerRewindFastforwardProfile`
- Fixed `getProfileTypeUID` for RawRockerPlayPauseProfile
- SAT findings and code clean-up
=> Added profiles to control Player Items via default system triggers

bundles/org.openhab.core.io.rest.core/src/main/java/org/eclipse/smarthome/io/rest/core/item/EnrichedItemDTOMapper.java, bundles/org.openhab.core.test.magic/src/main/java/org/eclipse/smarthome/magic/binding/MagicBindingConstants.java, bundles/org.openhab.core.test.magic/src/main/java/org/eclipse/smarthome/magic/binding/handler/MagicDynamicStateDescriptionThingHandler.java, bundles/org.openhab.core.test.magic/src/main/java/org/eclipse/smarthome/magic/binding/internal/MagicDiscoveryService.java, bundles/org.openhab.core.test.magic/src/main/java/org/eclipse/smarthome/magic/binding/internal/MagicDynamicStateDescriptionProvider.java, bundles/org.openhab.core.test.magic/src/main/java/org/eclipse/smarthome/magic/binding/internal/MagicHandlerFactory.java, bundles/org.openhab.core.test.magic/src/main/resources/ESH-INF/i18n/magic_de.properties, bundles/org.openhab.core.test.magic/src/main/resources/ESH-INF/thing/channel-types.xml, bundles/org.openhab.core.test.magic/src/main/resources/ESH-INF/thing/thing-types.xml, bundles/org.openhab.core.thing/src/main/java/org/eclipse/smarthome/core/thing/binding/BaseDynamicStateDescriptionProvider.java, bundles/org.openhab.core.thing/src/main/java/org/eclipse/smarthome/core/thing/binding/BaseThingHandler.java, bundles/org.openhab.core.thing/src/main/java/org/eclipse/smarthome/core/thing/i18n/ChannelTypeI18nLocalizationService.java, bundles/org.openhab.core.thing/src/main/java/org/eclipse/smarthome/core/thing/internal/ChannelStateDescriptionProvider.java, bundles/org.openhab.core.thing/src/main/java/org/eclipse/smarthome/core/thing/type/DynamicStateDescriptionProvider.java, bundles/org.openhab.core/src/main/java/org/eclipse/smarthome/core/internal/items/ItemStateConverterImpl.java, bundles/org.openhab.core/src/main/java/org/eclipse/smarthome/core/internal/types/CommandDescriptionImpl.java, bundles/org.openhab.core/src/main/java/org/eclipse/smarthome/core/internal/types/StateDescriptionFragmentImpl.java, bundles/org.openhab.core/src/main/java/org/eclipse/smarthome/core/items/GenericItem.java, bundles/org.openhab.core/src/main/java/org/eclipse/smarthome/core/library/items/NumberItem.java, bundles/org.openhab.core/src/main/java/org/eclipse/smarthome/core/types/CommandDescription.java, bundles/org.openhab.core/src/main/java/org/eclipse/smarthome/core/types/CommandDescriptionBuilder.java, bundles/org.openhab.core/src/main/java/org/eclipse/smarthome/core/types/CommandOption.java, bundles/org.openhab.core/src/main/java/org/eclipse/smarthome/core/types/StateDescription.java, bundles/org.openhab.core/src/main/java/org/eclipse/smarthome/core/types/StateDescriptionFragment.java, bundles/org.openhab.core/src/main/java/org/eclipse/smarthome/core/types/StateDescriptionFragmentBuilder.java, bundles/org.openhab.core/src/main/java/org/eclipse/smarthome/core/types/StateDescriptionFragmentProvider.java, bundles/org.openhab.core/src/main/java/org/eclipse/smarthome/core/types/StateOption.java, itests/org.openhab.core.thing.tests/src/main/java/org/eclipse/smarthome/core/thing/internal/SimpleThingTypeProvider.java, itests/org.openhab.core.thing.tests/src/main/java/org/eclipse/smarthome/core/thing/type/ChannelStateDescriptionProviderOSGiTest.java
- Added i18n feature for dynamic state descriptions via a `BaseDynamicStateDescriptionProvider` class
- Added null annotations to `StateOption`, `StateDescription` and `ChannelStateDescriptionProvider`
- Make use of `StateDescriptionFragmentBuilder`
- Changed null annotation of `CommandOption` label as we always allow `Nullable` labels
- Minor improvements
=> Added i18n feature for dynamic state descriptions

bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/RuleEngineImpl.java
The member variable "compositeFactory" that holds the
"CompositeModuleHandlerFactory" instance is set in the activation method
by calling the constructor of of "CompositeModuleHandlerFactory".
This reference is destroyed and unset in the deactivate method.
There exists DS managed multiple optional references to
"ModuleHandlerFactory".
The "add" logic does not touch the "compositeFactory" variable.
The "remove" logic checks if the given service reference is a
"CompositeModuleHandlerFactory" and unsets the "compositeFactory" member
variable.
If e.g. a module handler factory is injected that also implements the
CompositeModuleHandlerFactory the CompositeModuleHandlerFactory created
by the activate method is still be used. If that specific module handler
factory is removed again, the variable …
=> automation: remove specific handling for CompositeModuleHandlerFactory

bundles/org.openhab.core.thing/src/main/java/org/eclipse/smarthome/core/thing/binding/builder/BridgeBuilder.java, bundles/org.openhab.core.thing/src/main/java/org/eclipse/smarthome/core/thing/binding/builder/ThingBuilder.java, bundles/org.openhab.core.thing/src/main/java/org/eclipse/smarthome/core/thing/internal/BridgeImpl.java, bundles/org.openhab.core.thing/src/main/java/org/eclipse/smarthome/core/thing/internal/ThingImpl.java
- Removed deprecated methods in `ThingImpl` and `BridgeImpl` and as well in the related builders
Follow-up PR off #693
=> [core] Removed deprecated methods

bundles/org.openhab.core.thing/src/main/java/org/eclipse/smarthome/core/thing/binding/BaseDynamicStateDescriptionProvider.java
- Changed visibility of maps in `BaseDynamicStateDescriptionProvider` to allow subclasses to access and use them
=> Changed visibility of maps in 'BaseDynamicStateDescriptionProvider' to allow subclasses to access and use them

bom/runtime/pom.xml, features/karaf/openhab-core/pom.xml, features/karaf/openhab-core/src/main/feature/feature.xml, features/karaf/openhab-tp/src/main/feature/feature.xml
Fixes: https://github.com/openhab/openhab-core/issues/750
I see two possible fixes for #750:
* use the upstream library all the time and drop the OH specific release of nrjavaserial
* state that the OH nrjavaserial provides the specific capability (`openhab.tp;feature=serial;impl=rxtx`)
I don't know what's the difference between 3.15.0.OH2 of openHAB's nrjavaserial and 3.15.0 of the upstream one.
The nrjavaserial repository of openHAB does not contain any tag or commit that tells me anything about that.
So, let's wait for a reply to https://github.com/openhab/openhab-core/issues/750#issuecomment-487284749
At the moment I switch to the upstream one in this PR, but we can also remain at the OH spefic one, if working with upstream of nrjavaserial is not possible.
=> use upstream nrjavaserial 3.15.0 on runtime

bom/compile/pom.xml
Change compile dependency for compendium specification to R7.
This allows us to use the version 1.4 of the components and we can use the Constructor Injection.
=> Allow to use Declarative Services 1.4

bundles/org.openhab.core.thing/src/main/java/org/eclipse/smarthome/core/thing/binding/BaseDynamicCommandDescriptionProvider.java, bundles/org.openhab.core.thing/src/main/java/org/eclipse/smarthome/core/thing/i18n/ChannelTypeI18nLocalizationService.java, bundles/org.openhab.core.thing/src/main/java/org/eclipse/smarthome/core/thing/type/DynamicCommandDescriptionProvider.java, bundles/org.openhab.core/src/main/java/org/eclipse/smarthome/core/types/CommandDescriptionBuilder.java, bundles/org.openhab.core/src/main/java/org/eclipse/smarthome/core/types/CommandOption.java
- Added i18n feature for dynamic command descriptions via `BaseDynamicCommandDescriptionProvider` class
- Added method `withCommandOptions(List<CommandOption>)` to `CommandDescriptionBuilder`
- Improved JavaDoc on related classes
=> Added i18n feature for dynamic command descriptions

bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/RuleEngineImpl.java, bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/RuleRegistryImpl.java
Cleanup the rule engine implementation by using constructor injection. This allows us to use more final members. Also make some code "nicer looking"
If a rule is added, the status is set dependent on the "disabled storage" (see `addRule) to initializing or uninitialized-disabled.
The old code calls "set enabled" after adding all rules.
This is not necessary at all.
After removing the code my rules are working after an update, so perhaps this is also the root cause for #636 and #746. Sure, this could also just be timing dependent -- we will see.
=> automation: some cleanup

bundles/org.openhab.core.model.core/src/main/java/org/eclipse/smarthome/model/core/SafeEMF.java, bundles/org.openhab.core.model.core/src/main/java/org/eclipse/smarthome/model/core/internal/ModelRepositoryImpl.java, bundles/org.openhab.core.model.core/src/main/java/org/eclipse/smarthome/model/core/internal/SafeEMFImpl.java
The singleton instance of "Diagnostician" is used without synchronization.
The singleton "Diagnostician" instance is using the singleton "EValidator.Registry" instance (without synchronization).
In very rare high load situations there has been CME detected.
My first "solution" has been to synchronize the access of Diagnostician's instance method by using
```java
synchronized (Diagnostician.INSTANCE) {
...
```
But after realize that EMF is using internally other singletons I tried to find any information about EMF and thread safety.
I found this one: https://javahacks.net/2016/07/13/emf-thread-safety/
EMF models are not thread-safe by default and writing multithreaded
applications is not that simple.
The more complex our application became, the more often we got
concurrent modification …
=> model: prevent simultan access of singleton

features/karaf/openhab-core/src/main/feature/feature.xml
As we moved away from the manifest first approach the manifests are generated by Bnd and contain the capabilities already.
So, there is no need anymore to maintain it in the Karaf features manually.
=> remove manual set capabilities in Karaf features

pom.xml
This reverts the DS requirements removal of commit
981a447e9931ae98daaee60c99022a8f97c2441f which has been done on PR #530.
Fixes: https://github.com/openhab/openhab-core/issues/590
Related to: https://github.com/openhab/openhab-distro/pull/882
=> Revert main part of DS requirements removal

bom/compile/pom.xml
Bump the OSGi annotation to allow a pure annotation-driven bundle development.
Related to: https://virtual.osgiusers.org/2018/10/pure-annotation-driven-dev
=> allow to use "Pure Annotation-Driven Bundle Development"

bundles/org.openhab.core.thing/src/main/java/org/eclipse/smarthome/core/thing/i18n/ChannelGroupTypeI18nLocalizationService.java, bundles/org.openhab.core.thing/src/main/java/org/eclipse/smarthome/core/thing/i18n/ChannelTypeI18nLocalizationService.java, bundles/org.openhab.core.thing/src/main/java/org/eclipse/smarthome/core/thing/i18n/ThingTypeI18nLocalizationService.java, bundles/org.openhab.core.thing/src/main/java/org/eclipse/smarthome/core/thing/internal/i18n/ChannelGroupI18nUtil.java, bundles/org.openhab.core.thing/src/main/java/org/eclipse/smarthome/core/thing/internal/i18n/ChannelI18nUtil.java
- Separate i18n infrastructure for `ChannelGroup`
- Use constructor dependency injection
Follow-Up on https://github.com/eclipse/smarthome/pull/6072#discussion_r210986246
=>  Separate i18n infrastructure for 'ChannelGroup'

bundles/org.openhab.core.audio/src/main/java/org/eclipse/smarthome/core/audio/internal/AudioServlet.java
We should not remove entries (so keys) from the map while we are using the key set (a view) of that map (see JavaDoc: otherwise "results of the iteration undefined").
=> audio servlet: don't change map while used by interation

bundles/org.openhab.core.thing/src/main/java/org/eclipse/smarthome/core/thing/i18n/ThingTypeI18nUtil.java, bundles/org.openhab.core.thing/src/main/java/org/eclipse/smarthome/core/thing/internal/profiles/SystemProfileFactory.java, bundles/org.openhab.core.thing/src/main/java/org/eclipse/smarthome/core/thing/internal/profiles/i18n/ProfileI18nUtil.java, bundles/org.openhab.core.thing/src/main/java/org/eclipse/smarthome/core/thing/profiles/ProfileTypeProvider.java, bundles/org.openhab.core.thing/src/main/java/org/eclipse/smarthome/core/thing/profiles/i18n/ProfileTypeI18nLocalizationService.java, bundles/org.openhab.core.thing/src/main/resources/ESH-INF/i18n/SystemProfiles_de.properties, itests/org.openhab.core.thing.tests/src/main/java/org/eclipse/smarthome/core/thing/internal/CommunicationManagerOSGiTest.java, itests/org.openhab.core.thing.tests/src/main/java/org/eclipse/smarthome/core/thing/internal/profiles/SystemProfileFactoryOSGiTest.java, itests/org.openhab.core.thing.tests/src/main/java/org/eclipse/smarthome/core/thing/profiles/i18n/SystemProfileI18nOSGiTest.java
- Added i18n feature for profiles
One comment: There is an internal class `LocalizedProfileTypeKey` which is used in a very similar way for other translatable objects (e.g. https://github.com/openhab/openhab-core/blob/master/bundles/org.openhab.core.thing/src/main/java/org/eclipse/smarthome/core/thing/DefaultSystemChannelTypeProvider.java#L281-L328 and https://github.com/openhab/openhab-core/blob/master/bundles/org.openhab.core.config.xml/src/main/java/org/eclipse/smarthome/config/xml/AbstractXmlBasedProvider.java#L40-L79). I am not very happy with that and think about a refactoring. Let me know your opinion.
=> Added i18n feature for profiles

bom/compile/pom.xml, bundles/org.openhab.core.io.transport.mqtt/src/main/java/org/eclipse/smarthome/io/transport/mqtt/MqttBrokerConnection.java
After the bump of Paho from 1.2.0 to 1.2.1 the library enables the https hostname verification.
This breaks compatibility with current consumers.
Connections cannot be established anymore.
We disable the https hostname verification to keep the old behaviour.
We should add an API so the hostname verification can be enabled if desired.
This also makes the version 1.2.1 the lower version limit as we need to use the API to disable the verification internally.
Related to: https://github.com/openhab/openhab-core/issues/815
=> MQTT: disable https hostname verification

bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/RuleEngineImpl.java, bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/RuleRegistryImpl.java
The current rule registry implementation provides a configuration for the "rule reinitialization delay". That configuration is not used by the rule registry itself but used by the rule engine implementation.
This required the rule engine implementation to contain a special code path that checks if the injected rule registry is an instance of that special implementation to access that configuration parameter.
As the configuration is not used by the registry itself, it does not make sense that it is a configuration of that component.
If the rule engine (at least this special implementation) would like to use a configurable parameter, it should be part of that specific component implementation.
=> rule engine should not depend on specific registry implementation

tools/archetype/binding/src/main/resources/META-INF/archetype-post-generate.groovy, tools/archetype/binding/src/main/resources/META-INF/maven/archetype-metadata.xml, tools/archetype/binding/src/main/resources/archetype-resources/src/main/feature/feature.xml
- Fixed generation of binding skeletons
After https://github.com/openhab/openhab2-addons/pull/5555 which splitted the feature file into separate files we need some adjustments in the skeleton script
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-archetype-plugin:3.1.0:generate (default-cli) on project org.openhab.addons.reactor.bundles: java.io.FileNotFoundException: /home/christoph/Downloads/openhab-master/git/openhab2-addons/bundles/../features/karaf/openhab-addons/src/main/feature/feature.xml (Datei oder Verzeichnis nicht gefunden) -> [Help 1]
```
@J-N-K @Hilbrand May I ask you for validation? Thanks.
Also-by: Hilbrand Bouwkamp <hilbrand@h72.nl>
=> [archetype] Fixed generation of binding skeletons

.travis.yml, bundles/org.openhab.core.io.jetty.certificate/pom.xml, pom.xml
We could use Travis CI to execute some checks in front of the normal build.
This change adds a check if the POM files follow our POM conventions.
If something fails, it show which files violates the convention and the command that should be executed to fix the situation.
For example if the base POM file breaks the convention:
At least one POM file breaks the convention, please use sortpom to fix the POM file(s).
modified:   pom.xml
You should run the following command in the root directory of your working copy:
mvn com.github.ekryd.sortpom:sortpom-maven-plugin:sort -Dsort.keepBlankLines=true -Dsort.createBackupFile=false -Dsort.predefinedSortOrder=recommended_2008_06
=> Travis CI: check POM convention

bundles/org.openhab.core.io.http/src/main/java/org/eclipse/smarthome/io/http/internal/SmartHomeHttpContext.java
The Pax Web Extender is much more happy if this property is present.
Let's make it happy...
Fixes: https://github.com/openhab/openhab-distro/issues/891
=> set http context ID for smarthome HTTP context

bundles/org.openhab.core.thing/src/main/java/org/eclipse/smarthome/core/thing/profiles/i18n/ProfileTypeI18nLocalizationService.java
- Use `newState` profile builder for `StateProfileType`s
Fixes #830
Shall I add an assertion to the unit tests to count the number of available `StateProfileTypes` and `TriggerProfileTypes`?
=> Use correct profile builder

bundles/org.openhab.core.io.rest.sitemap/src/main/java/org/eclipse/smarthome/io/rest/sitemap/internal/PageChangeListener.java
If a change to item A causes visibility changes to item B, we previously
sent an SSE event for B including the new visibility for B, but included
item and state of A. This leads to client confusion, as it'll update its
internal state for the widget belonging to B with the item state of A.
As the visibility change doesn't include updated item and state anyway,
just omit those from the SSE event.
Closes #690
=> Always send correct 'item' member in SSE events.

bom/compile/pom.xml, bom/runtime/pom.xml
When debugging openHAB in Eclipse I ran into serial port locking issues again on Ubuntu 18.04.2.
We resolved these in the distro by using 3.15.0.OH2 which doesn't use liblockdev.
Errors similar to the one below may show after stopping/restarting openHAB when using serial ports on certain distros:
```
RXTX fhs_lock() Error: opening lock file: /var/lock/LCK..ttyUSB0: File exists. It is mine
testRead() Lock file failed
````
See also: https://github.com/openhab/openhab-core/pull/761
=> Use nrjavaserial 3.15.0.OH2 in BOMs

bundles/org.openhab.core.config.discovery/src/main/java/org/eclipse/smarthome/config/discovery/internal/AutomaticInboxProcessor.java, itests/org.openhab.core.config.discovery.tests/src/main/java/org/eclipse/smarthome/config/discovery/internal/AutomaticInboxProcessorTest.java
=> discovery: Use constructor injection to simplify lifecycle

bundles/org.openhab.core.io.rest.sse/src/main/java/org/eclipse/smarthome/io/rest/sse/internal/listeners/SseEventSubscriber.java
=> rest/sse: Use constructor injection to simplify lifecycle

bundles/org.openhab.core.config.discovery/src/main/java/org/eclipse/smarthome/config/discovery/internal/AutomaticInboxProcessor.java, bundles/org.openhab.core.config.discovery/src/main/java/org/eclipse/smarthome/config/discovery/internal/PersistentInbox.java, itests/org.openhab.core.config.discovery.tests/src/main/java/org/eclipse/smarthome/config/discovery/internal/AutomaticInboxProcessorTest.java, itests/org.openhab.core.config.discovery.tests/src/main/java/org/eclipse/smarthome/config/discovery/internal/PersistentInboxTest.java
If a component should be activated an instance is constructed and that object is activated.
Let's split the construction and activation logic also if constructor injection is used.
=> split activation logic

bundles/org.openhab.core.thing/src/main/java/org/eclipse/smarthome/core/thing/link/ThingLinkManager.java
See https://github.com/openhab/openhab-core/pull/837#discussion_r288173361
=> things: Use constructor injection to simplify lifecycle

bundles/org.openhab.core.automation.module.script/src/main/java/org/openhab/core/automation/module/script/internal/defaultscope/DefaultScriptScopeProvider.java
- Added `RefreshType.REFRESH` and `BinaryPrefix` to imports
- General refactoring of class `DefaultScriptScopeProvider`
The `DefaultScriptScopeProvider` needed a little bit more refactoring to be NPE safe and to implement the OSGi lifecycle handling correctly. The changes made it possible to drop the workaround for any `thingActions` queued before the component got activated.
See https://github.com/openhab/openhab-core/issues/834#issuecomment-496833158
Closes #846
=> automation: Refactoring of 'DefaultScriptScopeProvider'

bundles/org.openhab.core.io.net/src/main/java/org/eclipse/smarthome/io/net/http/internal/WebClientFactoryImpl.java
Newer Jetty versions log warnings when weak cipher suites are configured.
This occurs when using Karaf 4.2.6 with Jetty 9.4.18.v20190429.
See also:
* https://github.com/eclipse/jetty.project/pull/3050
* https://github.com/openhab/openhab-distro/pull/900#issuecomment-495381858
Fixes the following warnings:
```
22:25:04.336 [WARN ] [tty.util.ssl.SslContextFactory.config] - Weak cipher suite TLS_RSA_WITH_AES_256_CBC_SHA256 enabled for SslContextFactory@12d643d6[provider=null,keyStore=null,trustStore=null]
22:25:04.338 [WARN ] [tty.util.ssl.SslContextFactory.config] - Weak cipher suite TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA enabled for SslContextFactory@12d643d6[provider=null,keyStore=null,trustStore=null]
22:25:04.339 [WARN ] [tty.util.ssl.SslContextFactory.config] - Weak cipher suite …
```
=> Fix Jetty warnings by excluding weak cipher suites

bundles/org.openhab.core/src/main/java/org/eclipse/smarthome/core/internal/events/EventHandler.java, bundles/org.openhab.core/src/main/java/org/eclipse/smarthome/core/internal/events/ThreadedEventHandler.java
Move the event logging to the place the event is taken from queue and add a message to signal that we wait for an event.
This just move the trace logging to another place to allow a better log of the time consumed for event handling and waiting.
=> move event logging for better analyze options

bundles/org.openhab.core/src/main/java/org/eclipse/smarthome/core/util/HexUtils.java, bundles/org.openhab.core/src/test/java/org/eclipse/smarthome/core/util/HexUtilsTest.java
* improve HexUtils; e.g. don't create Byte array just to copy its content to a byte array
* migrate the HexUtils integration test to a normal JUnit test
=> small improvements of hexutils API and impl.

pom.xml
For Karaf 4.2.5 release notes, see:
https://issues.apache.org/jira/secure/ReleaseNote.jspa?projectId=12311140&version=12345153
For Karaf 4.2.6 release notes, see:
https://issues.apache.org/jira/secure/ReleaseNote.jspa?projectId=12311140&version=12345365
---
Should be merged together with:
* https://github.com/openhab/openhab-distro/pull/924
* https://github.com/openhab/openhab2-addons/pull/5708
* https://github.com/openhab/openhab-webui/pull/79
=> Upgrade Karaf tooling to 4.2.6

bom/compile/pom.xml, bom/openhab-core/pom.xml, bom/runtime/pom.xml, bundles/org.openhab.core.ephemeris/.classpath, bundles/org.openhab.core.ephemeris/.project, bundles/org.openhab.core.ephemeris/NOTICE, bundles/org.openhab.core.ephemeris/pom.xml, bundles/org.openhab.core.ephemeris/src/main/java/org/eclipse/smarthome/core/ephemeris/EphemerisManager.java, bundles/org.openhab.core.ephemeris/src/main/java/org/eclipse/smarthome/core/ephemeris/internal/EphemerisManagerImpl.java, bundles/org.openhab.core.ephemeris/src/main/resources/ESH-INF/config/config.xml, bundles/org.openhab.core.model.script/pom.xml, bundles/org.openhab.core.model.script/src/org/eclipse/smarthome/model/script/actions/Ephemeris.java, bundles/org.openhab.core.model.script/src/org/eclipse/smarthome/model/script/engine/action/ActionService.java, bundles/org.openhab.core.model.script/src/org/eclipse/smarthome/model/script/internal/engine/action/AudioActionService.java, bundles/org.openhab.core.model.script/src/org/eclipse/smarthome/model/script/internal/engine/action/EphemerisActionService.java, bundles/org.openhab.core.model.script/src/org/eclipse/smarthome/model/script/internal/engine/action/PersistenceActionService.java, bundles/org.openhab.core.model.script/src/org/eclipse/smarthome/model/script/internal/engine/action/ThingActionService.java, bundles/org.openhab.core.model.script/src/org/eclipse/smarthome/model/script/internal/engine/action/TransformationActionService.java, bundles/org.openhab.core.model.script/src/org/eclipse/smarthome/model/script/internal/engine/action/VoiceActionService.java, bundles/pom.xml, features/karaf/openhab-core/src/main/feature/feature.xml, features/karaf/openhab-tp/src/main/feature/feature.xml
Ported over from https://github.com/eclipse/smarthome/pull/6227.
@maggu2810 Did I do it correctly to add the jollyday lib to the compile- and runtime-bom?
Also-by: Gaël L'hopital <gael@lhopital.org>
=> Ephemeris service

bundles/org.openhab.core.io.transport.serial.rxtx/src/main/java/org/eclipse/smarthome/io/transport/serial/internal/RxTxPortProvider.java, bundles/org.openhab.core.io.transport.serial.rxtx/src/main/java/org/eclipse/smarthome/io/transport/serial/internal/SerialPortUtil.java
* Get all serial port identifiers by calling RXTX with and without using the `gnu.io.rxtx.SerialPorts` property
* Filter `getSerialPortIdentifiers()` stream on distinct port names
* Fix thread safety issues by saving `getPortIdentifiers()` Enumeration result to new list
Fixes #805
=> Fix serial ports missing when ports are added to system property

bundles/org.openhab.core/src/main/java/org/eclipse/smarthome/core/internal/events/EventHandler.java, bundles/org.openhab.core/src/main/java/org/eclipse/smarthome/core/internal/events/OSGiEventManager.java, bundles/org.openhab.core/src/main/java/org/eclipse/smarthome/core/internal/events/ThreadedEventHandler.java
This changes should address #829 
At the moment we warn if an event subscriber exceeds the limit of expected max. runtime.
This has been done before, too.
It would also be possible (which another implementation I played around today, too) to interrupt the event subscriber if it exceeds the limit. I don't think we should do this. This could perhaps lead into a very confusion behaviour on very high load. The warning should be enough to detect a really bad working event subscriber.
=> don't use safe caller for event delegation to subscribers

pom.xml
The bnd-testing-maven-plugin that is used to run the tests already checks for the skipTests property and do not execute any tests if defined.
We should keep the integration tests part of the reactor also if the tests are not executed.
=> don't drop the itests projects from reactor on skipTests

bundles/org.openhab.core.io.net/src/main/java/org/eclipse/smarthome/io/net/http/internal/ExtensibleTrustManagerImpl.java
It should not matter if the instructions are split or not.
But if it is split the nullness tooling don't know that the stream
after the filter contains only non null elements.
As it should not matter and to make the tooling happy...
=> compine filter and map for tooling

bundles/org.openhab.core.config.discovery.usbserial.linuxsysfs/src/main/java/org/eclipse/smarthome/config/discovery/usbserial/linuxsysfs/internal/PollingUsbSerialScanner.java
As discussed in a side discussion in issue #829 the most CPU consumption (after #763 and #861 have been implemented) is the USB polling.
I'd propose to reduce the polling frequency from 5 to 60 sec.
Signed-off-by: Björn Brings <bjoernbrings@web.de>
=> Reduce polling frequency of usb serial scanner

bundles/org.openhab.core.io.rest.sitemap/src/main/java/org/eclipse/smarthome/io/rest/sitemap/internal/PageChangeListener.java
If visibility of a sitemap widget that does not have a (valid) item is
changed, 'itemToBeSent' becomes null, in which case we need to omit
filling out 'event.item' and 'event.state' (and keep them as null).
Closes #897
=> Add missing null check to PageChangeListener.

bundles/org.openhab.core.automation.module.media/src/main/java/org/openhab/core/automation/module/media/internal/PlayActionHandler.java, bundles/org.openhab.core.automation.module.media/src/main/java/org/openhab/core/automation/module/media/internal/SayActionHandler.java, bundles/org.openhab.core.automation.module.script.rulesupport/src/main/java/org/openhab/core/automation/module/script/rulesupport/internal/delegates/SimpleActionHandlerDelegate.java, bundles/org.openhab.core.automation.module.script.rulesupport/src/main/java/org/openhab/core/automation/module/script/rulesupport/internal/delegates/SimpleConditionHandlerDelegate.java, bundles/org.openhab.core.automation.module.script.rulesupport/src/main/java/org/openhab/core/automation/module/script/rulesupport/internal/delegates/SimpleTriggerHandlerDelegate.java, bundles/org.openhab.core.automation.module.script/src/main/java/org/openhab/core/automation/module/script/internal/handler/AbstractScriptModuleHandler.java, bundles/org.openhab.core.automation.module.script/src/main/java/org/openhab/core/automation/module/script/internal/handler/ScriptActionHandler.java, bundles/org.openhab.core.automation.module.script/src/main/java/org/openhab/core/automation/module/script/internal/handler/ScriptConditionHandler.java, bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/Trigger.java, bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/handler/ActionHandler.java, bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/handler/BaseActionModuleHandler.java, bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/handler/BaseConditionModuleHandler.java, bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/handler/BaseModuleHandler.java, bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/handler/BaseTriggerModuleHandler.java, bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/handler/ConditionHandler.java, bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/handler/ModuleHandler.java, bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/module/handler/AnnotationActionHandler.java, bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/module/handler/CompareConditionHandler.java, bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/module/handler/DayOfWeekConditionHandler.java, bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/module/handler/GenericEventConditionHandler.java, bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/module/handler/ItemCommandActionHandler.java, bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/module/handler/ItemStateConditionHandler.java, bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/module/handler/RuleEnablementActionHandler.java, bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/module/handler/RunRuleActionHandler.java, bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/module/handler/TimeOfDayConditionHandler.java, bundles/org.openhab.core/src/main/java/org/eclipse/smarthome/core/events/EventFilter.java
Therefore introduced two new classes `BaseActionModuleHandler` and `BaseConditionModuleHandler`. A [BaseTriggerModuleHandler](https://github.com/openhab/openhab-core/blob/master/bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/handler/BaseTriggerModuleHandler.java) is already present.
=> [automation] Added nullness annotations

itests/org.openhab.core.automation.module.timer.tests/src/main/java/org/openhab/core/automation/module/timer/internal/DayOfWeekConditionHandlerTest.java, itests/org.openhab.core.automation.module.timer.tests/src/main/java/org/openhab/core/automation/module/timer/internal/TimeOfDayConditionHandlerTest.java
After adding the nullness annotations to the automation stuff, we need
to fix the usage to use a correct nullness handling.
Related to: https://github.com/openhab/openhab-core/pull/910
=> fix nullness handling in itests

bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/module/factory/CoreModuleHandlerFactory.java, bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/module/handler/ThingStatusTriggerHandler.java, bundles/org.openhab.core.automation/src/main/resources/ESH-INF/automation/moduletypes/ItemTriggers.json, bundles/org.openhab.core.automation/src/main/resources/ESH-INF/automation/moduletypes/ThingTriggers.json
- Added `ThingStatusTrigger` for NGRE
Currently I only check for the `ThingStatus.` But IIRC the trigger in DSL rules additionaly compares the `ThingStatusDetail` and the description. Just want to know right now if this is the way how it has to be done.
=> [automation] Added 'ThingStatusTrigger' for NGRE

bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/module/handler/ThingStatusTriggerHandler.java
- Fixed topic for `ThingStatusTriggerHandler`. It is called "things", not "thing".
=> [automation] Fixed topic for `ThingStatusTriggerHandler`

bom/compile/pom.xml, bom/runtime/pom.xml, features/karaf/openhab-tp/src/main/feature/feature.xml, itests/org.openhab.core.audio.tests/itest.bndrun, itests/org.openhab.core.auth.oauth2client.tests/itest.bndrun, itests/org.openhab.core.automation.tests/itest.bndrun, itests/org.openhab.core.binding.xml.tests/itest.bndrun, itests/org.openhab.core.compat1x.tests/itest.bndrun, itests/org.openhab.core.config.core.tests/itest.bndrun, itests/org.openhab.core.config.discovery.mdns.tests/itest.bndrun, itests/org.openhab.core.config.discovery.tests/itest.bndrun, itests/org.openhab.core.io.net.tests/itest.bndrun, itests/org.openhab.core.io.rest.core.tests/itest.bndrun, itests/org.openhab.core.magic.tests/itest.bndrun, itests/org.openhab.core.model.core.tests/itest.bndrun, itests/org.openhab.core.model.lsp.tests/itest.bndrun, itests/org.openhab.core.model.persistence.tests/itest.bndrun, itests/org.openhab.core.model.thing.tests/itest.bndrun, itests/org.openhab.core.semantics.tests/itest.bndrun, itests/org.openhab.core.storage.json.tests/itest.bndrun, itests/org.openhab.core.tests/itest.bndrun, itests/org.openhab.core.thing.tests/itest.bndrun, itests/org.openhab.core.thing.xml.tests/itest.bndrun, itests/org.openhab.core.transform.tests/itest.bndrun, itests/org.openhab.core.ui.icon.tests/itest.bndrun, itests/org.openhab.core.ui.tests/itest.bndrun, itests/org.openhab.core.voice.tests/itest.bndrun
- Bump `tec.uom` libraries to latest version
See [changelog](https://github.com/unitsofmeasurement/uom-se/compare/1.0.9...master). Addresses #644.
=> [uom] Bump `tec.uom` libraries

features/karaf/openhab-core/pom.xml, features/karaf/openhab-tp/pom.xml
Resolves the Jetty bundle duplicates as reported in #892 
---
I still had these changes on my local checkout. :smile:
=> Sync Jetty version with version used by Karaf 4.2.6

tools/archetype/binding/src/main/resources/META-INF/archetype-post-generate.groovy
Due to changes in the archetype maven it generated multi module name with tabs prefixed. This caused the module name to be inserted twice because the added module by maven plugin was not removed when the module is moved by the groovy script.
Signed-off-by: Hilbrand Bouwkamp <hilbrand@h72.nl>
=> [archetype] Fix for double modules in bundle pom

bundles/org.openhab.core/src/test/java/org/eclipse/smarthome/core/library/types/DateTimeTypeTest.java
- Added formatting tests for `DateTimeType`
Related to #832
=> Added formatting tests for 'DateTimeType'

bundles/org.openhab.core.io.transport.serial/src/main/java/org/eclipse/smarthome/io/transport/serial/internal/SerialPortRegistry.java
Change reference cardinality from `MULTIPLE` to `AT_LEAST_ONE` so the serial port provider can be used immediately when `ThingHandler`s are initialized.
Fixes #937
This would always result in the following logging on startup:
`[WARN ] [serial.internal.SerialPortManagerImpl] - No SerialPortProvider found for: /dev/ttyUSB0`
Bindings without serial port reconnection logic would need to be manually restarted (Z-Wave Binding).
=> Fix "No SerialPortProvider found" on startup

bundles/org.openhab.core/src/main/java/org/eclipse/smarthome/core/library/types/DateTimeType.java, bundles/org.openhab.core/src/test/java/org/eclipse/smarthome/core/library/types/DateTimeTypeTest.java
=> DateTimeType: new methods toZone and toLocaleZone

bundles/org.openhab.core.io.transport.mqtt/src/main/java/org/eclipse/smarthome/io/transport/mqtt/internal/ClientCallback.java, bundles/org.openhab.core.io.transport.mqtt/src/main/java/org/eclipse/smarthome/io/transport/mqtt/internal/TopicSubscribers.java, bundles/org.openhab.core.io.transport.mqtt/src/test/java/org/eclipse/smarthome/io/transport/mqtt/internal/TopicSubscriberTests.java
The old code did not properly handle special characters used in regular expressions (e.g. * or parentheses), leading to missing channel updates (cf. https://github.com/openhab/openhab2-addons/issues/5488). 
Also changes the topic matcher in the client callback from `String.matches` to pre-compiled patterns for performance reasons (cf. https://stackoverflow.com/questions/2469244/whats-the-difference-between-string-matches-and-matcher-matches). Especially on systems with with a lot of subscriptions this should be a lot better.
Add tests for the topic matching algorithm.
=> fix MQTT subscription

bundles/org.openhab.core.io.transport.mqtt/src/main/java/org/eclipse/smarthome/io/transport/mqtt/MqttBrokerConnection.java
When a lot of messages are published with QoS>0 Paho complains about "too many publishes in progress". This is due to a very low limit of 10 for inflight messages (see https://mvmn.wordpress.com/2016/07/23/paho-mqtt-client-max-in-flight-messages-for-qos-0/) 
=> increase paho inflight message limit

bundles/org.openhab.core.model.rule.runtime/src/org/eclipse/smarthome/model/rule/runtime/internal/engine/RuleEngineImpl.java, bundles/org.openhab.core.model.rule/src/org/eclipse/smarthome/model/rule/jvmmodel/RulesJvmModelInferrer.xtend
=> [DSL rule] New implicit variable newState

bundles/org.openhab.core.semantics/src/main/java/org/eclipse/smarthome/core/semantics/SemanticTags.java, bundles/org.openhab.core.semantics/src/main/java/org/eclipse/smarthome/core/semantics/internal/SemanticsMetadataProvider.java, bundles/org.openhab.core.semantics/src/main/java/org/eclipse/smarthome/core/semantics/internal/SemanticsServiceImpl.java, itests/org.openhab.core.semantics.tests/src/main/java/org/eclipse/smarthome/core/semantics/SemanticTagsTest.java, itests/org.openhab.core.semantics.tests/src/main/java/org/eclipse/smarthome/core/semantics/internal/SemanticsServiceImplTest.java
- Minor code clean-up (omit use of `@NonNull` annotation)
=> [semantics] Use constructor injection to simplify lifecycle

features/karaf/openhab-tp/src/main/feature/feature.xml
- Added feature for FasterXML Jackson bundles
See https://github.com/openhab/openhab-core/issues/892#issuecomment-520141490
=> Added feature for FasterXML Jackson bundles

bundles/org.openhab.core.ui/src/main/java/org/eclipse/smarthome/ui/internal/items/ItemUIRegistryImpl.java, itests/org.openhab.core.ui.tests/src/main/java/org/eclipse/smarthome/ui/internal/items/ItemUIRegistryImplTest.java
Fixes #832
This change will impact the REST sitemap API and as a consequence all UIs using this API (Basic UI, Android App, ...). All text widgets in sitemap linked to a DateTime item will now be provided to the UI with a date/time formatted in the local time zone in the label field of the widget (field item.state is unchanged).
Before this change,  the label field of the widget was containing the date/time forrmatted in the zone set by the item state.
=> ItemUIRegistry: getLabel returning DateTime item formatted in local time zone

bundles/org.openhab.core/src/main/java/org/eclipse/smarthome/core/library/unit/SmartHomeUnits.java
I was updating the Documentation for the Unit of Measurement as requested by @cweitkamp and found an issue with a couple of UoM symbols during this.
Signed-off-by: Stewart Cossey <stewart.cossey@gmail.com>
=> Fix Incorrect unit symbol for Byte and add unit symbol for Octet.

bundles/org.openhab.core.config.dispatch/src/main/java/org/eclipse/smarthome/config/dispatch/internal/ConfigDispatcher.java, bundles/org.openhab.core.config.dispatch/src/main/java/org/eclipse/smarthome/config/dispatch/internal/ConfigDispatcherFileWatcher.java, itests/org.openhab.core.config.dispatch.tests/src/main/java/org/eclipse/smarthome/config/dispatch/test/ConfigDispatcherFileWatcherTest.java, itests/org.openhab.core.config.dispatch.tests/src/main/java/org/eclipse/smarthome/config/dispatch/test/ConfigDispatcherOSGiTest.java
=> [config dispatch] Use constructor injection to simplify lifecycle

bundles/org.openhab.core.semantics/src/main/java/org/eclipse/smarthome/core/semantics/internal/SemanticsMetadataProvider.java, bundles/org.openhab.core/src/main/java/org/eclipse/smarthome/core/items/ItemRegistryChangeListener.java
- Specified service for component description
- Implement `ItemRegistryChangeListener` interface instead of `RegistryChangeListener<Item>`
=> [semantics] Specified service for component description

bundles/org.openhab.core.thing/src/main/java/org/eclipse/smarthome/core/thing/internal/ChannelCommandDescriptionProvider.java, bundles/org.openhab.core.thing/src/main/java/org/eclipse/smarthome/core/thing/internal/ChannelStateDescriptionProvider.java, bundles/org.openhab.core.thing/src/main/java/org/eclipse/smarthome/core/thing/link/ItemChannelLinkRegistry.java, bundles/org.openhab.core.thing/src/main/java/org/eclipse/smarthome/core/thing/type/ThingTypeRegistry.java, itests/org.openhab.core.thing.tests/src/main/java/org/eclipse/smarthome/core/thing/internal/CommunicationManagerOSGiTest.java
- Added nullness annotations to `ThingTypeRegistry`
=> [thing] Use constructor injection to simplify lifecycle

bundles/org.openhab.core/src/main/java/org/eclipse/smarthome/core/library/types/HSBType.java
- Fix gamma correction in HSBType for color conversion from sRGB to CIE XYZ and back
See https://en.m.wikipedia.org/wiki/SRGB#The_forward_transformation_(CIE_XYZ_to_sRGB) or https://developers.meethue.com/develop/application-design-guidance/color-conversion-formulas-rgb-to-xy-and-back/
=> Fix gamma correction in HSBType for color conversion from sRGB to CIE XYZ and back

.travis.yml
We do not use p2 anymore in this repo. Remove the cache directory. Add the bnd cache directory instead.
=> Travis Cache

bundles/org.openhab.core.ui/src/main/java/org/eclipse/smarthome/ui/internal/items/ItemUIRegistryImpl.java
Fixes #984
Before the change (display from a group so with the default rendering):
And now with this change in Basic UI:
And in Classic UI:
=> Selection widget as default widget for Number or String items with options

features/karaf/pom.xml, pom.xml
=> Removed repos as they are now inherited from the parent pom

bom/runtime/pom.xml
- Removed duplicate dependencies
Fixes the following warnings:
```
13:50:18 [WARNING] Some problems were encountered while building the effective model for org.openhab.core.bom:org.openhab.core.bom.runtime:pom:2.5.0-SNAPSHOT
13:50:18 [WARNING] 'dependencies.dependency.(groupId:artifactId:type:classifier)' must be unique: org.apache.servicemix.specs:org.apache.servicemix.specs.activation-api-1.1:jar -> duplicate declaration of version 2.9.0 @ line 871, column 17
13:50:18 [WARNING] 'dependencies.dependency.(groupId:artifactId:type:classifier)' must be unique: org.apache.servicemix.specs:org.apache.servicemix.specs.jaxb-api-2.2:jar -> duplicate declaration of version 2.9.0 @ line 876, column 17
13:50:18 [WARNING] 'dependencies.dependency.(groupId:artifactId:type:classifier)' must be unique: …
```
=> Removed duplicate dependencies

bundles/org.openhab.core.io.rest.core/src/main/java/org/eclipse/smarthome/io/rest/core/item/EnrichedItemDTO.java, itests/org.openhab.core.io.rest.core.tests/src/main/java/org/eclipse/smarthome/io/rest/core/internal/item/ItemResourceOSGiTest.java
- Changed property type to `Boolean` to allow `null` values
Fixes #985 
=> [rest] Changed property type to Boolean to allow null values

bundles/org.openhab.core.io.rest.voice/pom.xml, bundles/org.openhab.core.io.rest.voice/src/main/java/org/eclipse/smarthome/io/rest/voice/internal/VoiceDTO.java, bundles/org.openhab.core.io.rest.voice/src/main/java/org/eclipse/smarthome/io/rest/voice/internal/VoiceMapper.java, bundles/org.openhab.core.io.rest.voice/src/main/java/org/eclipse/smarthome/io/rest/voice/internal/VoiceResource.java
=> REST Voice API: new API for TTS

bundles/org.openhab.core.io.rest/src/main/java/org/eclipse/smarthome/io/rest/internal/resources/beans/RootBean.java, bundles/org.openhab.core.ui.icon/src/main/java/org/eclipse/smarthome/ui/icon/internal/IconServlet.java, itests/org.openhab.core.ui.icon.tests/src/main/java/org/eclipse/smarthome/ui/icon/internal/IconServletTest.java
Fix #824
If this new parameter is not used by the caller (UI), the behavior is unchanged. So this change will break no existing UI.
When this new parameter is provided and set to true by the caller (UI), the server will search the icon as SVG and PNG formats. If the icon provider is the same in the two cases, it will return the icon with the requested format. In case the 2 icon providers are different for SVG and PNG, the server will return the icon in the format corresponding to the provider with higer priority.
This new parameter allows an UI to select a preferred format for icons without loosing the customized user icons that can be defined  in a different format. Of course, in this case, the UI must handle possible different icon formats returned by the servlet.
Signed-off-by: Laurent …
=> [IconServlet] New optional parameter anyFormat

bom/openhab-core/pom.xml, bundles/org.openhab.core.io.rest.audio/.classpath, bundles/org.openhab.core.io.rest.audio/.project, bundles/org.openhab.core.io.rest.audio/NOTICE, bundles/org.openhab.core.io.rest.audio/pom.xml, bundles/org.openhab.core.io.rest.audio/src/main/java/org/eclipse/smarthome/io/rest/audio/internal/AudioMapper.java, bundles/org.openhab.core.io.rest.audio/src/main/java/org/eclipse/smarthome/io/rest/audio/internal/AudioResource.java, bundles/org.openhab.core.io.rest.audio/src/main/java/org/eclipse/smarthome/io/rest/audio/internal/AudioSinkDTO.java, bundles/org.openhab.core.io.rest.audio/src/main/java/org/eclipse/smarthome/io/rest/audio/internal/AudioSourceDTO.java, bundles/pom.xml, features/karaf/openhab-core/src/main/feature/feature.xml
=> New Audio REST API

bundles/org.openhab.core/src/main/java/org/eclipse/smarthome/core/library/types/DateTimeType.java, bundles/org.openhab.core/src/test/java/org/eclipse/smarthome/core/library/types/DateTimeTypeTest.java
Some formatters such as the `DateTimeFormatter.ISO_LOCAL_DATE_TIME` may also output a string containing 2 nano digits which fail to be parsed by `DateTimeValue`.
As a result the `ChannelStateTests` sometimes fails:
```
[INFO] Running org.openhab.binding.mqtt.generic.ChannelStateTests
[main] WARN org.openhab.binding.mqtt.generic.ChannelState - Command '2019-09-17T17:06:50.35' not supported by type 'DateTimeValue': 2019-09-17T17:06:50.35 is not in a valid format.
[ERROR] Tests run: 12, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.924 s <<< FAILURE! - in org.openhab.binding.mqtt.generic.ChannelStateTests
```
=> Fix DateTimeType parsing of strings with arbitrary number of nano digits

bundles/org.openhab.core/src/main/java/org/eclipse/smarthome/core/internal/items/ItemUpdater.java, bundles/org.openhab.core/src/main/java/org/eclipse/smarthome/core/internal/scheduler/CronSchedulerImpl.java, bundles/org.openhab.core/src/main/java/org/eclipse/smarthome/core/internal/scheduler/DelegatedSchedulerImpl.java, bundles/org.openhab.core/src/main/java/org/eclipse/smarthome/core/internal/scheduler/PeriodicSchedulerImpl.java, itests/org.openhab.core.tests/src/main/java/org/eclipse/smarthome/core/internal/scheduler/CronSchedulerImplTest.java, itests/org.openhab.core.tests/src/main/java/org/eclipse/smarthome/core/internal/scheduler/DelegatedSchedulerTest.java, itests/org.openhab.core.tests/src/main/java/org/eclipse/smarthome/core/internal/scheduler/PeriodicSchedulerImplTest.java
=> [scheduler] Use constructor injection to simplify lifecycle

bundles/org.openhab.core/src/main/java/org/eclipse/smarthome/core/internal/types/StateDescriptionFragmentImpl.java, bundles/org.openhab.core/src/test/java/org/eclipse/smarthome/core/internal/types/StateDescriptionFragmentImplTest.java, bundles/org.openhab.core/src/test/java/org/eclipse/smarthome/core/types/StateDescriptionFragmentBuilderTest.java
=> Fix dynamic options in UI

bundles/org.openhab.core.config.discovery/src/main/java/org/eclipse/smarthome/config/discovery/internal/AutomaticInboxProcessor.java, itests/org.openhab.core.config.discovery.tests/src/main/java/org/eclipse/smarthome/config/discovery/internal/AutomaticInboxProcessorTest.java
- Fixed activation of inbox
After #835 and #836 the real "activation" failed because the method was not annotated.
Fixes https://github.com/openhab/openhab2-addons/issues/6144
=> discovery: Fixed activation of inbox

bundles/org.openhab.core.thing/src/main/java/org/eclipse/smarthome/core/thing/binding/BaseThingHandler.java, bundles/org.openhab.core.thing/src/main/java/org/eclipse/smarthome/core/thing/binding/ThingHandlerCallback.java, bundles/org.openhab.core.thing/src/main/java/org/eclipse/smarthome/core/thing/internal/ThingManagerImpl.java
- Removed access to `ThingRegistry` from `BaseThingHandler`
See https://github.com/eclipse/smarthome/issues/5182
=> [core] Removed access to 'ThingRegistry' from 'BaseThingHandler'

bundles/org.openhab.core.io.rest.sse/src/main/java/org/eclipse/smarthome/io/rest/sse/internal/util/SseUtil.java, bundles/org.openhab.core.io.rest.sse/src/test/java/org/eclipse/smarthome/io/rest/sse/internal/util/SseUtilTest.java
=> [rest] Allow colons in sse topics filter

bundles/org.openhab.core.io.transport.mqtt/src/test/java/org/eclipse/smarthome/io/transport/mqtt/MqttAsyncClientEx.java, bundles/org.openhab.core.io.transport.mqtt/src/test/java/org/eclipse/smarthome/io/transport/mqtt/MqttBrokerConnectionTests.java
Wait for stop future to complete and fix the NPE that would cause the future not to complete.
When disconnecting the client the callback is null.
https://github.com/openhab/openhab-core/blob/0b2de2bfea0e735d13a69755c22b16a59a74fe87/bundles/org.openhab.core.io.transport.mqtt/src/main/java/org/eclipse/smarthome/io/transport/mqtt/MqttBrokerConnection.java#L833
```java
public IMqttToken disconnect(long quiesceTimeout) throws MqttException {
return this.disconnect(quiesceTimeout, null, null);
}
```
See: https://github.com/openhab/openhab-core/pull/1056#issuecomment-536447153
=> Fix MQTT gracefulStop test

itests/org.openhab.core.tests/src/main/java/org/eclipse/smarthome/core/cache/ExpiringCacheAsyncTest.java
Increasing the expiration hopefully prevents the item from expiring too soon occasionally:
```
TEST testFetchValue(org.eclipse.smarthome.core.cache.ExpiringCacheAsyncTest) <<< ERROR: null
java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:86)
at org.junit.Assert.assertTrue(Assert.java:41)
at org.junit.Assert.assertFalse(Assert.java:64)
at org.junit.Assert.assertFalse(Assert.java:74)
at org.eclipse.smarthome.core.cache.ExpiringCacheAsyncTest.testFetchValue(ExpiringCacheAsyncTest.java:55)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at …
```
=> Fix ExpiringCacheAsyncTest.testFetchValue unreliability

bundles/org.openhab.core.config.dispatch/src/main/java/org/eclipse/smarthome/config/dispatch/internal/ConfigDispatcher.java, itests/org.openhab.core.config.dispatch.tests/src/main/java/org/eclipse/smarthome/config/dispatch/test/ConfigDispatcherOSGiTest.java, itests/org.openhab.core.config.dispatch.tests/src/main/resources/configurations/local_pid_list_conf/local.pid.list.default.file.cfg, itests/org.openhab.core.config.dispatch.tests/src/main/resources/configurations/local_pid_list_conf/local_pid_list_services/local.pid.list.service.fifth.file.cfg, itests/org.openhab.core.config.dispatch.tests/src/main/resources/configurations/local_pid_list_conf/local_pid_list_services/local.pid.list.service.first.file.cfg, itests/org.openhab.core.config.dispatch.tests/src/main/resources/configurations/local_pid_list_conf/local_pid_list_services/local.pid.list.service.fourth.file.cfg, itests/org.openhab.core.config.dispatch.tests/src/main/resources/configurations/local_pid_list_conf/local_pid_list_services/local.pid.list.service.second.file.cfg, itests/org.openhab.core.config.dispatch.tests/src/main/resources/configurations/local_pid_list_conf/local_pid_list_services/local.pid.list.service.seventh.file.cfg, itests/org.openhab.core.config.dispatch.tests/src/main/resources/configurations/local_pid_list_conf/local_pid_list_services/local.pid.list.service.sixth.file.cfg, itests/org.openhab.core.config.dispatch.tests/src/main/resources/configurations/local_pid_list_conf/local_pid_list_services/local.pid.list.service.third.file.cfg
- Added support for values containing a list of configuration options (comma-separated list)
Related to #998
Syntax will be:
```
<service-pid>:<property>=<value_1>,<value_2>,...,<value_n>
```
Is this syntax okay? Or do we risk to break something existent because a comma (`,`) is a common used character in configurations. Should we maybe surround the value list by square brackets?
```
<service-pid>:<property>=[<value_1>,<value_2>,...,<value_n>]
```
I would like to add some unit tests. Before that we have to get #995 running.
=> [config dispatch] Added support for values containing a list of configuration options

tools/static-code-analysis/checkstyle/suppressions.xml
This SAT check causes 525 false positives.
See: openhab/static-code-analysis#356
=> Suppress MavenPomderivedInClasspathCheck

bundles/org.openhab.core/src/main/java/org/eclipse/smarthome/core/internal/i18n/I18nProviderImpl.java, itests/org.openhab.core.binding.xml.tests/src/main/java/org/eclipse/smarthome/core/binding/xml/test/BindingInfoI18nTest.java, itests/org.openhab.core.thing.tests/src/main/java/org/eclipse/smarthome/core/thing/testutil/i18n/DefaultLocaleSetter.java
- Changed pid from 'org.eclipse.smarthome.core.i18nprovider' to 'org.eclipse.smarthome.i18n'
=> Changed pid from 'org.eclipse.smarthome.core.i18nprovider' to 'org.eclipse.smarthome.i18n'

itests/org.openhab.core.config.discovery.mdns.tests/src/main/java/org/eclipse/smarthome/config/discovery/mdns/internal/MDNSDiscoveryServiceOSGiTest.java
With these changes the test no longer fails for me. The test is also flawed because `isBackgroundDiscoveryEnabled()` returns `true` at startup without setting it `true` first. So it's better to first test disabling and then enabling.
Fixes #567
=> Fix unstable MDNSDiscoveryServiceOSGiTest

bundles/org.openhab.core.karaf/src/main/java/org/openhab/core/karaf/internal/command/InstallServiceCommand.java, tools/static-code-analysis/pmd/suppressions.properties
Suppresses the `SystemPrintln` SAT findings because this class is a Karaf shell command which prints to the console.
=> Fix InstallServiceCommand SAT findings

features/karaf/openhab-tp/src/main/feature/feature.xml
This adds a feature `openhab.tp-netty` with Netty 4.1.34.Final andthe most common bundles. 
Can/Should we define a `netty.version` which can be used by core- or addons-bundles too add additional bundles and keep them in sync?
=> add a feature for netty

bom/test/pom.xml, itests/org.openhab.core.auth.oauth2client.tests/itest.bndrun, itests/org.openhab.core.automation.module.core.tests/itest.bndrun, itests/org.openhab.core.automation.module.script.defaultscope.tests/itest.bndrun, itests/org.openhab.core.automation.module.script.tests/itest.bndrun, itests/org.openhab.core.automation.module.timer.tests/itest.bndrun, itests/org.openhab.core.config.core.tests/itest.bndrun, itests/org.openhab.core.config.discovery.tests/itest.bndrun, itests/org.openhab.core.config.discovery.usbserial.linuxsysfs.tests/itest.bndrun, itests/org.openhab.core.config.discovery.usbserial.tests/itest.bndrun, itests/org.openhab.core.config.dispatch.tests/itest.bndrun, itests/org.openhab.core.config.xml.tests/itest.bndrun, itests/org.openhab.core.io.rest.core.tests/itest.bndrun, itests/org.openhab.core.model.core.tests/itest.bndrun, itests/org.openhab.core.model.persistence.tests/itest.bndrun, itests/org.openhab.core.model.script.tests/itest.bndrun, itests/org.openhab.core.model.thing.tests/itest.bndrun, itests/org.openhab.core.tests/itest.bndrun, itests/org.openhab.core.thing.tests/itest.bndrun
Mockito 3 does not introduce any breaking API changes, but now requires Java 8 over Java 6 for Mockito 2.
---
Hopefully this update helps with resolving unstable tests or makes it easier to debug them.
This repo as well as the add-ons build successfully locally after the update so I've also created a PR for updating the runbundles in openhab2-addons: https://github.com/openhab/openhab2-addons/pull/6216.
=> Update Mockito to 3.1.0

bundles/org.openhab.core.config.discovery/src/test/java/org/eclipse/smarthome/config/discovery/internal/PersistentInboxTest.java
Activating the `PersistentInbox` after the mocks are initialized prevents the `TimeToLiveCheckingThread` calling the storage mock which would cause the exception.
Fixes #1091
=> Fix unstable PersistentInboxTest

itests/org.openhab.core.tests/src/main/java/org/eclipse/smarthome/core/internal/common/SafeCallerImplTest.java
After some load testing these values improved the stability of the tests.
See: #1113
=> Improve SafeCallerImplTest stability

features/karaf/openhab-core/src/main/feature/feature.xml
- Removed default configuration for ephemeris service from feature file
Closes #1121 
Related to https://github.com/openhab/openhab-distro/pull/984
=> [ephemeris] Removed default configuration for ephemeris service from feature file

features/karaf/openhab-tp/src/main/feature/feature.xml, features/karaf/pom.xml
* re-enable verification for tp-features
* fix jax-ws feature
* extend jackson feature
* use jackson feature  for swagger-jaxrs-provider
Probably fixes https://github.com/openhab/openhab-webui/issues/96
=> fixes for tp-features

itests/org.openhab.core.thing.xml.tests/src/main/java/org/eclipse/smarthome/core/thing/xml/test/ChannelTypesTest.java
Most likely the test is unstable because the `ChannelGroupTypeProvider` is still processing the bundle XML. So using `waitForAssert` may fix this. It's also used like this to assert the channel types got added by the `ChannelTypeProvider`.
Fixes #1090
=> Fix unstable ChannelTypesTest

bundles/org.openhab.core.thing.xml/src/main/java/org/eclipse/smarthome/core/thing/xml/internal/ThingTypeXmlProvider.java, bundles/org.openhab.core.thing.xml/src/main/java/org/eclipse/smarthome/core/thing/xml/internal/ThingTypeXmlResult.java
When a binding such as ZWave has hundreds of ThingTypes it's hard to debug thing type definition issues.
This PR adds a UID (ConfigDescription, ChannelType, ChannelGroupType and ThingType) to the logging so it will be easier to find the root cause of exceptions.
Because the exceptions are caught, an error in one ThingType definition will no longer prevent other perfectly fine ThingTypes to be registered so the impact of definition issues is reduced.
---
This improvement was inspired by https://github.com/openhab/org.openhab.binding.zwave/issues/1249 which would now result in the following error:
```
21:47:32.641 [ERROR] [ing.xml.internal.ThingTypeXmlProvider] - Could not register ThingType: zwave:zwaveme_zuno_01_000
java.lang.IllegalArgumentException: UID must have at least 2 segments.
at …
```
=> Improve ThingTypeXmlProvider exception handling

itests/org.openhab.core.automation.integration.tests/src/main/java/org/openhab/core/automation/integration/test/AutomationIntegrationTest.java
When `waitForAssert` uses `ruleEvents.stream()` the `ruleEventHandler` may add an event to `ruleEvents` at the same time causing a `ConcurrentModificationException`.
Using a `CopyOnWriteArrayList` instead of an `ArrayList` should fix this.
Fixes:
```
TEST assertThatARuleWithConnectionsIsExecuted(org.openhab.core.automation.integration.test.AutomationIntegrationTest) <<< ERROR: null
java.util.ConcurrentModificationException
at java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1361)
at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:499)
at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:486)
at …
```
=> Fix ConcurrentModificationException in AutomationIntegrationTest

itests/org.openhab.core.automation.integration.tests/src/main/java/org/openhab/core/automation/integration/test/AutomationIntegrationJsonTest.java
Sometimes the method returns null causing the test to fail because `waitForAssert` doesn't catch NPEs:
https://github.com/openhab/openhab-core/blob/7279ddbbf661c8b47357a081e00c81c5d44fd955/bundles/org.openhab.core.test/src/main/java/org/eclipse/smarthome/test/java/JavaTest.java#L142
Fixes:
```
TEST assertThatARuleFromJsonFileIsExecutedCorrectly(org.openhab.core.automation.integration.test.AutomationIntegrationJsonTest) <<< ERROR: null
java.lang.NullPointerException
at org.openhab.core.automation.integration.test.AutomationIntegrationJsonTest.lambda$13(AutomationIntegrationJsonTest.java:344)
at org.eclipse.smarthome.test.java.JavaTest.waitForAssert(JavaTest.java:136)
at org.eclipse.smarthome.test.java.JavaTest.waitForAssert(JavaTest.java:120)
at …
```
=> Fix unstable AutomationIntegrationJsonTest

bundles/org.openhab.core/src/main/java/org/eclipse/smarthome/core/internal/scheduler/CronAdjuster.java, bundles/org.openhab.core/src/test/java/org/eclipse/smarthome/core/internal/scheduler/CronAdjusterTest.java
- Fixed cron parsing for Day-Of-Week sub-expression
Fixes #1141 
=> [automation] Fixed cron parsing for Day-Of-Week sub-expression

bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/provider/AbstractResourceBundleProvider.java, bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/provider/ModuleTypeResourceBundleProvider.java, bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/provider/TemplateResourceBundleProvider.java, bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/provider/i18n/ModuleI18nUtil.java, bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/provider/i18n/ModuleTypeI18nServiceImpl.java, bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/provider/i18n/ModuleTypeI18nUtil.java, bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/provider/i18n/RuleTemplateI18nUtil.java, bundles/org.openhab.core.config.core/src/main/java/org/eclipse/smarthome/config/core/i18n/ConfigI18nLocalizationService.java, bundles/org.openhab.core.config.core/src/main/java/org/eclipse/smarthome/config/core/internal/i18n/ConfigDescriptionGroupI18nUtil.java, bundles/org.openhab.core.config.core/src/main/java/org/eclipse/smarthome/config/core/internal/i18n/ConfigDescriptionI18nUtil.java, bundles/org.openhab.core.thing/src/main/java/org/eclipse/smarthome/core/thing/i18n/ChannelGroupTypeI18nLocalizationService.java, bundles/org.openhab.core.thing/src/main/java/org/eclipse/smarthome/core/thing/i18n/ChannelTypeI18nLocalizationService.java, bundles/org.openhab.core.thing/src/main/java/org/eclipse/smarthome/core/thing/i18n/ThingTypeI18nLocalizationService.java, bundles/org.openhab.core.thing/src/main/java/org/eclipse/smarthome/core/thing/internal/i18n/ThingTypeI18nUtil.java, itests/org.openhab.core.automation.integration.tests/itest.bndrun, itests/org.openhab.core.automation.module.core.tests/itest.bndrun, itests/org.openhab.core.automation.module.script.defaultscope.tests/itest.bndrun, itests/org.openhab.core.automation.module.script.tests/itest.bndrun, itests/org.openhab.core.automation.module.timer.tests/itest.bndrun
- Moved i18n util classes into internal packages
- Use `ConfigI18nLocalizationService` instead of `ConfigDescriptionI18nUtil` in other packages than `o.o.c.config.*`
- Refactoring of automation i18n util classes according our default implementation for these util classes (e.g. non static)
- Added nullness annotations for i18n util classes
=> [i18n] Refactoring and annotations

bundles/org.openhab.core.thing.xml/src/main/java/org/eclipse/smarthome/core/thing/xml/internal/ThingXmlConfigDescriptionProvider.java, bundles/org.openhab.core.thing.xml/src/main/java/org/eclipse/smarthome/core/thing/xml/internal/XmlChannelGroupTypeProvider.java, bundles/org.openhab.core.thing.xml/src/main/java/org/eclipse/smarthome/core/thing/xml/internal/XmlChannelTypeProvider.java, bundles/org.openhab.core.thing.xml/src/main/java/org/eclipse/smarthome/core/thing/xml/internal/XmlThingTypeProvider.java, bundles/org.openhab.core.thing/src/main/java/org/eclipse/smarthome/core/thing/DefaultSystemChannelTypeProvider.java, bundles/org.openhab.core.thing/src/main/java/org/eclipse/smarthome/core/thing/internal/ThingConfigDescriptionAliasProvider.java, bundles/org.openhab.core.thing/src/main/java/org/eclipse/smarthome/core/thing/type/ChannelGroupTypeProvider.java, bundles/org.openhab.core.thing/src/main/java/org/eclipse/smarthome/core/thing/type/ChannelTypeProvider.java
- Added constructor injection to thing xml
- Removed `@Nullable` annotation from `getChannelTypes` and `getChannelGroupTypes`
---
There is also a PR to update the add-ons for the annotation changes: https://github.com/openhab/openhab2-addons/pull/6288
=> [xml] Feature thing xml constructor injection

itests/org.openhab.core.automation.integration.tests/src/main/java/org/openhab/core/automation/integration/test/HostFragmentSupportTest.java
waitForAssert doesn't catch NPEs so this PR fixes that by also checking the localized modules for null.
Related to #1089
=> Improve HostFragmentSupportTest stability with null assertions

bom/compile/pom.xml, bom/runtime/pom.xml, features/karaf/openhab-tp/src/main/feature/feature.xml, itests/org.openhab.core.automation.integration.tests/itest.bndrun, itests/org.openhab.core.automation.module.core.tests/itest.bndrun, itests/org.openhab.core.automation.module.script.defaultscope.tests/itest.bndrun, itests/org.openhab.core.automation.module.script.tests/itest.bndrun, itests/org.openhab.core.automation.module.timer.tests/itest.bndrun, itests/org.openhab.core.automation.tests/itest.bndrun, itests/org.openhab.core.ephemeris.tests/itest.bndrun, itests/org.openhab.core.model.core.tests/itest.bndrun, itests/org.openhab.core.model.item.tests/itest.bndrun, itests/org.openhab.core.model.persistence.tests/itest.bndrun, itests/org.openhab.core.model.rule.tests/itest.bndrun, itests/org.openhab.core.model.script.tests/itest.bndrun, itests/org.openhab.core.model.thing.tests/itest.bndrun
- Bump jollyday version to 0.5.9
Changes to `itest.bndrun` files don by
```
find . -name "*.bndrun" -exec sed -i "s|jollyday;version='\[0.5.8,0.5.9)'|jollyday;version='[0.5.9,0.5.10)'|g" {} \;
find . -name "*.bndrun" -exec sed -i "s|org.threeten.extra;version='\[1.4.0,1.4.1)'|org.threeten.extra;version='\[1.5.0,1.5.1)'|g" {} \;
```
---
There are also PRs to update the distro / add-ons for these changes:
- https://github.com/openhab/openhab-distro/pull/990
- https://github.com/openhab/openhab2-addons/pull/6300
=> Bump jollyday version to 0.5.9

bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/util/ConfigurationNormalizer.java, bundles/org.openhab.core.config.core/src/main/java/org/eclipse/smarthome/config/core/ConfigUtil.java, bundles/org.openhab.core.config.core/src/main/java/org/eclipse/smarthome/config/core/internal/normalization/ListNormalizer.java, bundles/org.openhab.core.config.core/src/main/java/org/eclipse/smarthome/config/core/internal/normalization/NormalizerFactory.java, bundles/org.openhab.core.config.core/src/test/java/org/eclipse/smarthome/config/core/ConfigUtilTest.java, bundles/org.openhab.core.model.thing/src/org/eclipse/smarthome/model/thing/internal/GenericThingProvider.xtend, bundles/org.openhab.core.thing/src/main/java/org/eclipse/smarthome/core/thing/internal/ThingFactoryHelper.java, bundles/org.openhab.core.thing/src/main/java/org/eclipse/smarthome/core/thing/internal/ThingManagerImpl.java, itests/org.openhab.core.thing.tests/src/main/java/org/eclipse/smarthome/core/thing/binding/ThingFactoryTest.java
- Consider more than one value when applying the default value(s) for Things and Channels
We have a really powerful normalization tool `ConfigUtil` for parameters. ~I tried to use this tool for determining the correct type of the default value which unfortunately did not work because the normalization tool returns the given object, if it was not possible to convert it. We expect `null` for the default value if we cannot convert it. Any ideas?~
My approach was not needed because the default value is always a `String`. I now moved the normalization of the default value and the method to apply the default configuration to the `ConfigUtil` tool. As s side effect it leads to a nice code clean-up / streamlining in the helper calsses.
TODOs:
Related to #998
Signed-off-by: Christoph Weitkamp …
=> Consider more than one value when applying the default value(s) for Things and Channels

bundles/org.openhab.core.io.transport.mqtt/pom.xml, bundles/org.openhab.core.io.transport.mqtt/src/test/java/org/eclipse/smarthome/io/transport/mqtt/MqttBrokerConnectionTests.java
Using `waitForAssert` instead of sleeping 10ms makes the tests stable when the system has some load.
Fixes #1139
=> Fix unstable MqttBrokerConnectionTests

features/karaf/openhab-core/pom.xml, features/karaf/openhab-tp/pom.xml, features/karaf/pom.xml, pom.xml
For Karaf 4.2.7 release notes, see:
https://issues.apache.org/jira/secure/ReleaseNote.jspa?projectId=12311140&version=12345539
Also updates the following openHAB TP dependencies:
* Jetty 9.4.20.v20190813
* JNA 5.4.0 (used by most add-ons)
---
Should be merged together with:
* https://github.com/openhab/openhab2-addons/pull/6368
* https://github.com/openhab/openhab-webui/pull/139
* https://github.com/openhab/openhab-distro/pull/996
See also : https://github.com/openhab/openhab-distro/issues/995
=> Upgrade Karaf tooling and openHAB TP to 4.2.7

bundles/org.openhab.core.io.transport.serial/pom.xml, bundles/org.openhab.core.io.transport.serial/src/main/java/org/eclipse/smarthome/io/transport/serial/internal/console/SerialCommandExtension.java
I found that change in a branch of mine.
I don't know if you are interested in as this is more or less about "diagnostic" information about the internal handling of serial ports.
For me it has been useful (the time I wrote it) to analyse some serial port "problems".
=> add console command extension for serial inspection

bundles/org.openhab.core.io.transport.mqtt/pom.xml, bundles/org.openhab.core.io.transport.mqtt/src/main/java/org/eclipse/smarthome/io/transport/mqtt/MqttBrokerConnection.java, bundles/org.openhab.core.io.transport.mqtt/src/main/java/org/eclipse/smarthome/io/transport/mqtt/internal/ClientCallback.java, bundles/org.openhab.core.io.transport.mqtt/src/main/java/org/eclipse/smarthome/io/transport/mqtt/internal/MqttBrokerConnectionServiceInstance.java, bundles/org.openhab.core.io.transport.mqtt/src/main/java/org/eclipse/smarthome/io/transport/mqtt/internal/MqttServiceImpl.java, bundles/org.openhab.core.io.transport.mqtt/src/main/resources/ESH-INF/config/brokerConnectionInstance.xml
- Improved ESH-INF labels to comply with casing rules
=> [io.mqtt] Use constructor injection to simplify lifecycle

bundles/org.openhab.core.compat1x/src/main/java/org/openhab/io/net/http/HttpUtil.java, bundles/org.openhab.core.thing/src/main/java/org/eclipse/smarthome/core/thing/internal/ThingManagerImpl.java, bundles/org.openhab.core/src/main/java/org/eclipse/smarthome/core/net/NetUtil.java
Make sure Throwables are not be substituted into log messages so they can be formatted according to the logging configuration.
=> Parameterized logging fixes

itests/itest-common.bndrun
If you would like to use the runblacklist bnd instruction in an integration test it will not work as expected.
In my current test case it is not used at all.
This is caused because an included file overrides this instruction.
IMHO it would be better to use the "Merged Instructions" feature and use a psotfix in the included file. This way you can use the non postfixed instruction as usual.
See: https://bnd.bndtools.org/chapters/820-instructions.html#merged-instructions
=> fix unexpected behavior while using runblacklist in itests

features/karaf/openhab-tp/src/main/feature/feature.xml
- Bump Californium to 2.0.0-RC1
Release for Californium 2.0.0 is scheduled for December 5th 2019 (see https://github.com/eclipse/californium/issues/1131). If we want to use the updated Californium version in OH 2.5.0 release we should move to 2.0.0-RC1 now (before our next OH 2.5.0.M5 milestone - scheduled on Nov. 17th). After milestone OH 2.5.0.M5 we will freeze our code apart from major/critical bug fixes.
Before merging this we should prepare the necessary changes for the [TRÅDFRI Binding](https://github.com/openhab/openhab2-addons/tree/master/bundles/org.openhab.binding.tradfri). @markus7017 Might I ask you to prepare everything? IIRC you already did some tests with updating the binding. Don't you?
Closes #1096
=> Bump Californium to 2.0.0-RC1

bundles/org.openhab.core.thing/src/main/java/org/eclipse/smarthome/core/thing/binding/BaseThingHandler.java, bundles/org.openhab.core.thing/src/main/java/org/eclipse/smarthome/core/thing/binding/BaseThingHandlerFactory.java
- Removed access to `BundleContext` from `BaseThingHandler`
Final commit to resolve eclipse/smarthome#5182
---
Depends on openhab/openhab2-addons/pull/6395 and openhab/openhab2-addons/pull/6396.
=> [core] Removed access to 'BundleContext' from 'BaseThingHandler'

bundles/org.openhab.core.thing/src/main/java/org/eclipse/smarthome/core/thing/internal/ChannelItemProvider.java, bundles/org.openhab.core.thing/src/test/java/org/eclipse/smarthome/core/thing/internal/ChannelItemProviderTest.java
- Call `removeItem()` with item name instead of `ThingUID`
- Added unit test to cover findings in #1226 
Fixes #1226 
=> [thing] Call `removeItem()` with item name instead of `ThingUID`

bundles/org.openhab.core.io.net/src/main/java/org/eclipse/smarthome/io/net/http/internal/WebClientFactoryImpl.java
To prevent weak cipher/protocol warnings it's better to not customize the default excluded ciphers and protocols.
The MD5 ciphers have already been excluded by default since Jetty 9.3.11.v20160721.
Fixes #1064
=> Use default SslContextFactory excludes for weak ciphers and protocols

bundles/org.openhab.core.thing/src/main/java/org/eclipse/smarthome/core/thing/internal/ThingManagerImpl.java, itests/org.openhab.core.thing.tests/src/main/java/org/eclipse/smarthome/core/thing/internal/ThingManagerOSGiJavaTest.java
- Set `UNINITIALIZED` -> `HANDLER_MISSING_ERROR` after enabling a thing and handler / factory is missing (for stand-alone things)
Closes #718 
=> Set 'UNINITIALIZED' -> 'HANDLER_MISSING_ERROR' after enabling a thing and handler / factory is missing

bundles/org.openhab.core.karaf/src/main/java/org/openhab/core/karaf/internal/FeatureInstaller.java
- Reduce logging level in `FeatureInstaller` when uninstalling a binding
Currently we can see an `INFO` logging in `openhab.log` when an extension got uninstalled but nothing when an extension got installed:
openhab.log:
```
...
2019-11-29 14:57:32.774 [INFO ] [core.karaf.internal.FeatureInstaller] - Uninstalled 'openhab-binding-kodi'
...
...
...
```
Both events are logged in the `event.log`:
events.log
```
...
2019-11-29 14:57:32.774 [thome.event.ExtensionEvent] - Extension 'binding-kodi' has been uninstalled.
...
2019-11-29 14:57:46.682 [thome.event.ExtensionEvent] - Extension 'binding-kodi' has been installed.
...
```
Closes #119
=> Reduce logging level in 'FeatureInstaller' when uninstalling a binding

bundles/org.openhab.core.io.transport.mqtt/src/main/java/org/eclipse/smarthome/io/transport/mqtt/MqttBrokerConnection.java
MQTT does only support the levels 0, 1 and 2 as described in the JavaDoc of the setQos() method. The current check allows however setting the QoS level to 3.
=> Fix check which allows QoS 3

bundles/org.openhab.core.io.transport.mqtt/src/main/java/org/eclipse/smarthome/io/transport/mqtt/MqttBrokerConnection.java
Fixes #1237 
In the long run reconnections should be handled by the HiveMQ client. I did not change that now because it would be API breaking. I can fix that for OH2 addons, but maybe other solutions depend on that. IMO the whole public API should be changed for OH3.
=> Fix MQTT reconnection and add some debug logging

features/karaf/openhab-tp/src/main/feature/feature.xml
- Bump Californium to 2.0.0
// CC @markus7017
=> Bump Californium to 2.0.0

bundles/org.openhab.core.io.transport.mqtt/src/main/java/org/eclipse/smarthome/io/transport/mqtt/MqttBrokerConnection.java, bundles/org.openhab.core.io.transport.mqtt/src/main/java/org/eclipse/smarthome/io/transport/mqtt/internal/client/Mqtt3AsyncClientWrapper.java, bundles/org.openhab.core.io.transport.mqtt/src/main/java/org/eclipse/smarthome/io/transport/mqtt/internal/client/Mqtt5AsyncClientWrapper.java, bundles/org.openhab.core.io.transport.mqtt/src/main/java/org/eclipse/smarthome/io/transport/mqtt/internal/client/MqttAsyncClientWrapper.java
Paho and HiveMQ have differences in handling multiple subscriptions to the same topic. This ensures that only one subscription within the client is made even if more than one callback is subscribing to a given topic.
See https://github.com/openhab/openhab2-addons/issues/6488
=> fix multiple MQTT subscriptions

bom/runtime/pom.xml
Related to https://github.com/openhab/openhab-core/pull/1262
This makes the libs also available in the demo app / IDE.
=> added Californium to runtime bom

bundles/org.openhab.core.automation.module.script/src/main/java/org/openhab/core/automation/module/script/AbstractScriptEngineFactory.java, bundles/org.openhab.core.automation.module.script/src/main/java/org/openhab/core/automation/module/script/internal/GenericScriptEngineFactory.java, bundles/org.openhab.core.automation.module.script/src/main/java/org/openhab/core/automation/module/script/internal/NashornScriptEngineFactory.java, bundles/org.openhab.core.automation.module.script/src/main/java/org/openhab/core/automation/module/script/internal/ScriptEngineManagerImpl.java, bundles/org.openhab.core.automation.module.script/src/main/java/org/openhab/core/automation/module/script/internal/provider/ScriptModuleTypeProvider.java
These changes prepare for custom ScriptEngineFactories and does not
include any breaking changes.
* Moved AbstractScriptEngineFactory out of internal so that it can be
used by custom factories
* Modified ScriptEngineModuleTypeProvider to include engines from custom
factories
* Cleaned up some logging
Signed-off-by: Scott Rushworth <openhab@5iver.com>
=> [automation] Prepare automation for custom ScriptEngineFactories

bundles/org.openhab.core.persistence/src/main/java/org/eclipse/smarthome/core/persistence/internal/PersistenceManagerImpl.java
contains + get will do its job as long as all collection access uses the same synchronization locks and as long as every put ensures there will never by a null value be inserted.
If the map implementation checks if a key is available, we can also get the value already (IMHO there is no need for the overhead to first lookup if the key is present and after that is checked, we call the get function). It should be better to get the value and check if it differs from null.
=> contains + get can be replaced by get and a null check

bundles/org.openhab.core/src/main/java/org/eclipse/smarthome/core/items/events/GroupItemStateChangedEvent.java, bundles/org.openhab.core/src/main/java/org/eclipse/smarthome/core/items/events/ItemEventFactory.java, bundles/org.openhab.core/src/main/java/org/eclipse/smarthome/core/items/events/ItemStateChangedEvent.java
- Added missing JavaDoc to `createGroupStateChangedEvent` method in `ItemEventFactory`
=> Added missing JavaDoc to 'createGroupStateChangedEvent' method in 'ItemEventFactory'

bundles/org.openhab.core.model.script/bnd.bnd, bundles/org.openhab.core.model.script/src/org/eclipse/smarthome/model/script/actions/HTTP.java
Add an additional version for each type of HTTP request (GET, PUT, POST, DELETE) that accepts HTTP headers to be sent along with the request.
Addressed issue #1271 
This was tested in a jython script, passing a python's dictionary object to the header argument. RulesDSL user can use newHashMap.
=> [actions] Add the ability to send HTTP headers in sendHttpXXXRequest

bom/compile/pom.xml, bom/runtime/pom.xml, features/karaf/openhab-tp/src/main/feature/feature.xml
- Removed dependency on `org.apache.commons.collections`
Now the question for downward compatibility: Can we risk to remove it from the feature too (e.g. openHAB 1 Add-ons)?
https://github.com/openhab/openhab-core/blob/abb558851fba83978e56c173e13533f8fa512ec7/features/karaf/openhab-tp/src/main/feature/feature.xml#L26-L27
---
Depends on https://github.com/openhab/openhab-core/pull/1244
=> Removed dependency on 'org.apache.commons.collections'

itests/org.openhab.core.config.xml.tests/src/main/java/org/openhab/core/config/xml/test/ConfigDescriptionI18nTest.java
- Fixed unstable ConfigDescriptionI18nTest
Use `ConfigDescriptionProvider` instead of `ConfigDescriptionRegistry` to access translated `ConfigDescription`s.
Fixes #1222
=> Fixed unstable ConfigDescriptionI18nTest

tools/archetype/binding/src/main/resources/archetype-resources/src/main/feature/feature.xml
When generating a new binding with the maven archetype it should refer to openhab core via the variable `ohc.version` In the feature.xml.
=> [archetype] new binding feature should use ohc.version

bundles/org.openhab.core.model.core/src/main/java/org/openhab/core/model/core/internal/folder/FolderObserver.java
https://github.com/openhab/openhab-core/pull/1314 was missing an update for this PID. Without it all file based configuration won't work.
I did some basic testing for https://github.com/openhab/openhab-core/issues/1287 with my Java 11 PRs (+ this PR + https://github.com/openhab/openhab-distro/pull/1030) and didn't run into any Java 11 or Xtext issues.
=> Fix FolderObserver configuration PID

bundles/org.openhab.core/src/main/java/org/openhab/core/library/unit/SmartHomeUnits.java, bundles/org.openhab.core/src/test/java/org/openhab/core/library/unit/SmartHomeUnitsTest.java
SI units are written without spaces.
Fixes #1295 
Signed-off-by: Markus Schraufstetter <markus.schraufstetter@gmail.com>
=> Correction of unit spellings Ampere hour

bundles/org.openhab.core.io.rest/src/main/java/org/openhab/core/io/rest/JSONResponse.java
- Suppress error message in REST response
I am wondering if we can suppress this error message as the REST interface can handle it without any consequences. It often occurs when a request is interrupted or canceled.
```
2019-12-30 14:24:44.491 [ERROR] [lipse.smarthome.io.rest.JSONResponse] - Error streaming JSON through PipedInpuStream/PipedOutputStream: 
com.google.gson.JsonIOException: java.io.IOException: Pipe closed
at com.google.gson.Gson.toJson(Gson.java:671) ~[?:?]
at org.eclipse.smarthome.io.rest.JSONResponse.lambda$0(JSONResponse.java:173) ~[?:?]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_152]
Suppressed: java.io.IOException: Pipe closed
at java.io.PipedInputStream.checkStateForReceive(PipedInputStream.java:260) ~[?:1.8.0_152]
at …
```
=> [rest] Suppress error message in REST response

bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/events/ThingStatusInfoChangedEvent.java, bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/events/ThingStatusInfoEvent.java, bundles/org.openhab.core/src/main/java/org/openhab/core/items/events/ItemCommandEvent.java, bundles/org.openhab.core/src/main/java/org/openhab/core/items/events/ItemStateChangedEvent.java, bundles/org.openhab.core/src/main/java/org/openhab/core/items/events/ItemStateEvent.java, bundles/org.openhab.core/src/main/java/org/openhab/core/items/events/ItemStatePredictedEvent.java
- Streamline format of event outputs / Always prepend "Item" or "Thing" and put identifier between hyphens `'<ID>'`
=> Streamline format of event outputs

bundles/org.openhab.core.auth.oauth2client/src/main/java/org/openhab/core/auth/oauth2client/internal/OAuthConnector.java
It seems unnecessary to log every successful token refresh at log level INFO, especially when the `expiresIn` is relatively short (e.g. hourly).
Signed-off-by: Mark Hilbush <mark@hilbush.com>
=> [oauthclient] Reduce log level to debug for successful token refresh

bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/internal/channel/ChannelTypeResource.java, bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/internal/link/ItemChannelLinkResource.java, bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/internal/thing/ThingTypeResource.java, bundles/org.openhab.core.io.rest.core/src/test/java/org/openhab/core/io/rest/core/internal/channel/ChannelTypeResourceTest.java
These filters help reduce payloads for UIs which
retrieve ad-hoc information rather than maintain
a global state.
=> Add filters to some REST getAll endpoints

bundles/org.openhab.core.model.persistence/src/org/openhab/core/model/persistence/extensions/PersistenceExtensions.java
- Fixed JavaDoc for persistence extension
Related to #1333 
Question is: How should proceed with the return value of `avarageSince()` method?
=> [persistence] Fixed JavaDoc for persistence extension

bom/compile/pom.xml, bom/runtime/pom.xml, bundles/org.openhab.core.model.persistence/NOTICE, bundles/org.openhab.core.model.persistence/bnd.bnd, bundles/org.openhab.core.model.persistence/pom.xml, bundles/org.openhab.core.model.persistence/src/org/openhab/core/model/persistence/extensions/PersistenceExtensions.java, bundles/org.openhab.core.model.rule/bnd.bnd, bundles/org.openhab.core.model.script/bnd.bnd, bundles/org.openhab.core.model.script/src/org/openhab/core/model/script/actions/ScriptExecution.java, bundles/org.openhab.core.model.script/src/org/openhab/core/model/script/actions/Timer.java, bundles/org.openhab.core.model.script/src/org/openhab/core/model/script/internal/actions/TimerImpl.java, bundles/org.openhab.core.model.script/src/org/openhab/core/model/script/scoping/ScriptImplicitlyImportedTypes.java, bundles/org.openhab.core.model.script/src/org/openhab/core/model/script/scoping/ScriptImportSectionNamespaceScopeProvider.java, features/karaf/openhab-tp/src/main/feature/feature.xml, itests/org.openhab.core.model.core.tests/itest.bndrun, itests/org.openhab.core.model.item.tests/itest.bndrun, itests/org.openhab.core.model.persistence.tests/itest.bndrun, itests/org.openhab.core.model.persistence.tests/src/main/java/org/openhab/core/model/persistence/extensions/PersistenceExtensionsTest.java, itests/org.openhab.core.model.rule.tests/itest.bndrun, itests/org.openhab.core.model.script.tests/itest.bndrun, itests/org.openhab.core.model.script.tests/src/main/java/org/openhab/core/model/script/actions/ScriptExecutionTest.java, itests/org.openhab.core.model.script.tests/src/main/java/org/openhab/core/model/script/scheduler/test/MockClosure.java, itests/org.openhab.core.model.thing.tests/itest.bndrun
This PR finally gets rid off Joda Time.
As discussed in the past, this will break rules from users, but as the final rule format is anyhow still under discussion, it is clear that we will need some way or another for rule migration for the 3.0 release. This PR should hence not really have much additional weight.
Fixes #1250
=> replaced Joda Time by Java Time

bundles/org.openhab.core.audio/src/main/java/org/openhab/core/audio/internal/AudioConsoleCommandExtension.java, bundles/org.openhab.core.audio/src/main/java/org/openhab/core/audio/internal/AudioServlet.java, bundles/org.openhab.core.audio/src/test/java/org/openhab/core/audio/internal/AbstractAudioServletTest.java, bundles/org.openhab.core.voice/src/main/java/org/openhab/core/voice/internal/VoiceConsoleCommandExtension.java, bundles/org.openhab.core.voice/src/main/java/org/openhab/core/voice/internal/VoiceManagerImpl.java, itests/org.openhab.core.voice.tests/src/main/java/org/openhab/core/voice/javavoicemanager/VoiceManagerTest.java
- Simplify lifecycle by using constructor injection
- Removed usage of `org.apache.commons.lang.ArrayUtils`
- Minor code improvements
=> [voice] Simplify lifecycle by using constructor injection

pom.xml
See https://github.com/openhab/openhab-core/pull/1303
Signed-off-by: Arne Seime <arne.seime@gmail.com>
=> Added spotless plugin to build/plugins

bundles/org.openhab.core/src/main/java/org/openhab/core/library/unit/SmartHomeUnits.java, bundles/org.openhab.core/src/test/java/org/openhab/core/library/unit/SmartHomeUnitsTest.java
Dear  openHAB developers,
this PR tries to fix some minor issues related to the units of reactive and apparent power.
kvar existed already but I believe it was incorrectly defined. Also var (1000 var = 1 kvar) was missing from the list of units.
Unit for apparent power (VA) and it's common derivates were missing entirely.
These units are used sometimes by smart electricity meters and solar inverters.
I hope you will like these changes.
=> Units for reactive and apparent power

bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/internal/ThingManagerImpl.java
When a thing is enabled, the `ThingManagerImpl` takes care of calling `ThingHandler#initialize()`.
That makes totally sense if the thing was disabled before. However, if `setEnabled(thingUID, true)` is called for a thing which was already enabled, it causes an additional initialization.
Since concurrent hanlder initializations may cause trouble, it is safer to prevent this. Therefore enabling a thing (including starting its thing handler) should only be performed if the thing is disabled.
Signed-off-by: Michael Reitler <michael.dicke@smail.inf.h-brs.de>
=> [ThingManagerImpl] Prevent multiple handler inits on thing enabling

bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/binding/builder/ChannelBuilder.java, bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/dto/ChannelDTO.java, bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/dto/ChannelDTOMapper.java, bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/dto/StrippedThingTypeDTOMapper.java, bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/dto/ThingDTOMapper.java, bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/type/AutoUpdatePolicy.java, bundles/org.openhab.core.thing/src/test/java/org/openhab/core/thing/binding/builder/ThingBuilderTest.java, bundles/org.openhab.core.thing/src/test/java/org/openhab/core/thing/dto/ChannelDTOTest.java, bundles/org.openhab.core.thing/src/test/java/org/openhab/core/thing/dto/ThingDTOTest.java
- Add `AutoUpdatePolicy` property to `ChannelDTO`
- Fix NPE in `ChannelDTOMapper`
- Added unit tests for `ChannelDTO` and `ThingDTO` / `BridgeDTO`
See https://github.com/openhab/openhab-core/pull/1301#issuecomment-579324714 for context.
Also-by: Christoph Weitkamp <github@christophweitkamp.de>
Signed-off-by: Simon Lamon <simonlamon93@hotmail.com>
=> ChannelDTO bugfixes

pom.xml
- Enabled 'spotless:check' by default
Depends on #1302 
// CC: @seime for review
=> Enabled 'spotless:check' by default

bundles/org.openhab.core.voice/src/main/java/org/openhab/core/voice/text/ASTNode.java, bundles/org.openhab.core.voice/src/main/java/org/openhab/core/voice/text/AbstractRuleBasedInterpreter.java, pom.xml
@kaikreuzer This turned out to be a bit more involved than I expected.
I started with what was done in ESH, but immediately ran into problems trying to build the javadocs. It turns out there's an issue with javadoc in Java 11 that results in a nasty (and silent) ClassCastException. I traced it down to this construct `{@link SomeType[]}`. Fortunately, there were only 6 occurrences in the codebase, all of them in `org.openhab.core.voice`. Here's an example:
https://github.com/openhab/openhab-core/blob/master/bundles/org.openhab.core.voice/src/main/java/org/openhab/core/voice/text/ASTNode.java#L66
In this PR, I simply removed the @ in those 6 occurrences until I get some direction on how best to handle these 6 occurrences, as well as how to prevent the offending construct from being …
=> Reenable javadoc generation

bundles/org.openhab.core.io.rest.ui/src/main/java/org/openhab/core/io/rest/ui/internal/UIResource.java, bundles/org.openhab.core.ui/src/main/java/org/openhab/core/ui/components/RootUIComponent.java, bundles/org.openhab.core.ui/src/main/java/org/openhab/core/ui/components/UIComponent.java, bundles/org.openhab.core.ui/src/main/java/org/openhab/core/ui/components/UIComponentRegistry.java, bundles/org.openhab.core.ui/src/main/java/org/openhab/core/ui/components/UIComponentRegistryFactory.java, bundles/org.openhab.core.ui/src/main/java/org/openhab/core/ui/internal/components/UIComponentProvider.java, bundles/org.openhab.core.ui/src/main/java/org/openhab/core/ui/internal/components/UIComponentRegistryFactoryImpl.java, bundles/org.openhab.core.ui/src/main/java/org/openhab/core/ui/internal/components/UIComponentRegistryImpl.java, bundles/org.openhab.core.ui/src/main/java/org/openhab/core/ui/internal/components/UIComponentSitemapProvider.java, bundles/org.openhab.core/src/main/java/org/openhab/core/common/registry/AbstractRegistry.java, bundles/org.openhab.core/src/main/java/org/openhab/core/common/registry/ManagedProvider.java
This is an initial implementation of #1355.
It was simple enough to make to be proposed as
a PR already without waiting for remarks on the RFC.
<strike>The SitemapProvider for the `system:sitemap`
namespace as described in #1355 is not part of
this PR.</strike> edit: now it is.
=> UI component registries initial implementation

bundles/org.openhab.core/src/main/java/org/openhab/core/internal/items/MetadataCommandDescriptionProvider.java, bundles/org.openhab.core/src/main/java/org/openhab/core/internal/items/MetadataStateDescriptionFragmentProvider.java, bundles/org.openhab.core/src/test/java/org/openhab/core/internal/items/MetadataCommandDescriptionProviderTest.java, bundles/org.openhab.core/src/test/java/org/openhab/core/internal/items/MetadataStateDescriptionFragmentProviderTest.java
Implements #1185.
These providers will look into item metadata, which
can be managed by UIs with the API, to set or override
the item's state description (pattern, options, read
only...) or command description.
=> Metadata-based state & command description providers

bundles/org.openhab.core.automation.module.script.rulesupport/src/main/java/org/openhab/core/automation/module/script/rulesupport/internal/loader/ScriptFileWatcher.java
Fixes #841. I also added a few file extensions to the list that are not loaded as scripts.I've tested on Windows 10 and Fedora 31.
Signed-off-by: Scott Rushworth <openhab@5iver.com>
=> [automation] Corrected issue where scripts were not starting when OH restarted

bundles/org.openhab.core.model.script/src/org/openhab/core/model/script/actions/Ephemeris.java
isBankHoliday(offset, filename) in 2.5.0 and master throws away the filename instead of using it.  This little patch should fix this.
Closes: #1374
=> Ephemeris: isBankHoliday(offset, filename) now really uses the filename

bundles/org.openhab.core.io.rest.sse/src/main/java/org/openhab/core/io/rest/sse/internal/ItemStatesSseBroadcaster.java, bundles/org.openhab.core.io.rest.sse/src/main/java/org/openhab/core/io/rest/sse/internal/SseStateEventOutput.java
This fixes a NPE which occurs when a ItemStateChangedEvent
is broadcasted by the ItemStatesSseBroadcaster while some
SseStateEventOutputs haven't initialized their list of
tracked items.
=> Fix NPE with uninitialized state trackers

bundles/org.openhab.core.model.script/src/org/openhab/core/model/script/scoping/ScriptImportSectionNamespaceScopeProvider.java
- Added implicit import for units to rule models
Related to #917
This fix takes care of working rules without using imports of unit classes like https://github.com/openhab/openhab-core/issues/917#issuecomment-520945885. `KILOMETRE_PER_HOUR` now can be used with or without `SIUnits` prefix. The validation issue still is shown while rules are refreshed.
```
rule "Test SIUnits"
when
Item EnConges received command
then
logInfo("Test.rules","Test SIUnits " + SIUnits.KILOMETRE_PER_HOUR.toString)
val QuantityType<Speed> speed = new QuantityType(25.0, SIUnits.KILOMETRE_PER_HOUR)
logInfo("Test.rules", "Test SIUnits speed = " + speed.toString)
end
```
=> [DSL] Added implicit import for units to rule models

bundles/org.openhab.core.automation.module.script.rulesupport/src/main/java/org/openhab/core/automation/module/script/rulesupport/internal/loader/ScriptFileWatcher.java
This change improves the way file extensions are excluded from ScriptFileWatcher. Discussed [here](https://github.com/openhab/openhab-core/pull/1367#discussion_r379914147).
Signed-off-by: Scott Rushworth <openhab@5iver.com>
=> [automation] Improve file extension exclusion

bundles/org.openhab.core.model.persistence/src/org/openhab/core/model/persistence/internal/PersistenceModelManager.java, bundles/org.openhab.core.persistence/src/main/java/org/openhab/core/persistence/PersistenceFilter.java, bundles/org.openhab.core.persistence/src/main/java/org/openhab/core/persistence/PersistenceItemConfiguration.java, bundles/org.openhab.core.persistence/src/main/java/org/openhab/core/persistence/PersistenceService.java, bundles/org.openhab.core.persistence/src/main/java/org/openhab/core/persistence/PersistenceServiceConfiguration.java, bundles/org.openhab.core.persistence/src/main/java/org/openhab/core/persistence/config/PersistenceAllConfig.java, bundles/org.openhab.core.persistence/src/main/java/org/openhab/core/persistence/config/PersistenceConfig.java, bundles/org.openhab.core.persistence/src/main/java/org/openhab/core/persistence/config/PersistenceGroupConfig.java, bundles/org.openhab.core.persistence/src/main/java/org/openhab/core/persistence/config/PersistenceItemConfig.java, bundles/org.openhab.core.persistence/src/main/java/org/openhab/core/persistence/internal/PersistItemsJob.java, bundles/org.openhab.core.persistence/src/main/java/org/openhab/core/persistence/internal/PersistenceManagerImpl.java, bundles/org.openhab.core.persistence/src/main/java/org/openhab/core/persistence/strategy/PersistenceCronStrategy.java, bundles/org.openhab.core.persistence/src/main/java/org/openhab/core/persistence/strategy/PersistenceStrategy.java, itests/org.openhab.core.model.persistence.tests/src/main/java/org/openhab/core/model/persistence/tests/TestPersistenceService.java
Also refactored Simple... classes to Persistence.... classes (that's actually 95% of the changes).
=> Allow persistence services to define default strategies

bundles/org.openhab.core/src/main/java/org/openhab/core/library/unit/SmartHomeUnits.java, bundles/org.openhab.core/src/test/java/org/openhab/core/library/unit/SmartHomeUnitsTest.java
- Fixed intensity conversion from `W/m²` to `µW/cm²`
IIRC conversion from W/m² to µW/cm² should be division by 1,000,000 / 10,000 = 100. Shouldn’t it?
=> [uom] Fixed intensity conversion from W/m² to µW/cm²

bundles/org.openhab.core.automation.module.script/src/main/java/org/openhab/core/automation/module/script/internal/ScriptExtensionManager.java, bundles/org.openhab.core.automation.module.script/src/main/java/org/openhab/core/automation/module/script/internal/ScriptExtensionManagerWrapper.java
Existing API only allows engine factory implementors to request presets are pushed into existing scopes, rather than returning them directory, so that they can be bound into module or library systems. This change allows implementors to capture the presets requested (and potentially ignore any pushed), and therefore expose them via idiomatic import mechanisms for the language being implemented.
Specifically, I am using this for Javascript CommonJS module support. Without this change it's possible, but ugly (using reflection) and tricky (using weakrefs to ensure engines can be collected). This change is minimal and backwards compatible with the current API.
=> [automation] Added API for ScriptEngineFactory implementations to pull presets

bundles/org.openhab.core.automation.module.script/src/main/java/org/openhab/core/automation/module/script/internal/defaultscope/LifecycleScriptExtensionProvider.java
Add a default preset so that scripts, and more importantly modules, can call `lifecycleTracker.addDisposalHook(<disposal function>)`. This will be called when the engine is disposed.
Fixes #1260 
=> [automation] Add script extension to allow scripts to track their disposal

itests/org.openhab.core.tests/src/main/java/org/openhab/core/items/GroupItemOSGiTest.java
Without helping the compiler a bit, it will show null analysis errors in Eclipse.
=> Fix null analysis errors in Eclipse

bundles/org.openhab.core.ui/src/main/java/org/openhab/core/ui/internal/items/ItemUIRegistryImpl.java, bundles/org.openhab.core.ui/src/test/java/org/openhab/core/ui/internal/items/ItemUIRegistryImplTest.java
- Replace unit placeholder in patterns if updated by `DecimalType` states
Fixes #986
=> Replace unit placeholder in patterns if updated by DecimalType states

bundles/org.openhab.core/src/main/java/org/openhab/core/types/StateDescriptionFragmentBuilder.java, bundles/org.openhab.core/src/test/java/org/openhab/core/types/StateDescriptionFragmentBuilderTest.java
- Fix `UnsupportedOperationException` in `StateDescriptionFragmentBuilder` when copying a legacy `StateDescription` as `getOptions()` returns an immutable list.
https://github.com/openhab/openhab-core/blob/1f825fc529a107ba11bdab19992939e213abd99d/bundles/org.openhab.core/src/main/java/org/openhab/core/types/StateDescription.java#L57
=> [core] Fix UnsupportedOperationException in StateDescriptionFragmentBuilder

bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/internal/ChannelCommandDescriptionProvider.java, bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/internal/ChannelStateDescriptionProvider.java, bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/type/DynamicCommandDescriptionProvider.java, bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/type/DynamicStateDescriptionProvider.java, bundles/org.openhab.core/src/main/java/org/openhab/core/internal/types/CommandDescriptionImpl.java, bundles/org.openhab.core/src/main/java/org/openhab/core/internal/types/StateDescriptionFragmentImpl.java, bundles/org.openhab.core/src/main/java/org/openhab/core/types/CommandOption.java, bundles/org.openhab.core/src/main/java/org/openhab/core/types/StateDescription.java, bundles/org.openhab.core/src/main/java/org/openhab/core/types/StateOption.java, itests/org.openhab.core.thing.tests/src/main/java/org/openhab/core/thing/internal/ChannelCommandDescriptionProviderOSGiTest.java, itests/org.openhab.core.thing.tests/src/main/java/org/openhab/core/thing/internal/ChannelStateDescriptionProviderOSGiTest.java
- Dynamic state/command provider should not return original description
- Added integration test for `CommandDescriptionProvider`
See https://community.openhab.org/t/dynamic-state-options-not-showing-up/95625
=> [thing] Dynamic state/command provider should not return original description 

bundles/org.openhab.core.thing.xml/src/main/java/org/openhab/core/thing/xml/internal/ChannelGroupTypeConverter.java, bundles/org.openhab.core.thing.xml/src/main/java/org/openhab/core/thing/xml/internal/ChannelGroupTypeXmlResult.java, bundles/org.openhab.core.thing.xml/src/main/java/org/openhab/core/thing/xml/internal/ChannelTypeConverter.java, bundles/org.openhab.core.thing.xml/src/test/resources/example/example.xml, bundles/org.openhab.core.thing.xml/thing-description-1.0.0.xsd, bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/i18n/ChannelGroupTypeI18nLocalizationService.java, bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/type/ChannelGroupType.java, bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/type/ChannelGroupTypeBuilder.java, bundles/org.openhab.core.thing/src/test/java/org/openhab/core/thing/type/ChannelGroupTypeBuilderTest.java, bundles/org.openhab.core.ui/src/main/java/org/openhab/core/ui/internal/items/ItemUIRegistryImpl.java, itests/org.openhab.core.thing.tests/src/main/java/org/openhab/core/thing/binding/ThingFactoryTest.java, itests/org.openhab.core.thing.xml.tests/src/main/resources/test-bundle-pool/ThingTypesTest.bundle/OH-INF/thing/thing-types.xml
- Removed 'advanced' attribute from `ChannelGroupType`
Resolves #1402 
@kaikreuzer What would be an appropriate versioning for the XSD file? 3.0.0? matching OHC version? If we change it we have to migrate all XML files in this repo.
=> Removed 'advanced' attribute from 'ChannelGroupType'

bom/compile/pom.xml, bom/runtime/pom.xml, features/karaf/openhab-tp/src/main/feature/feature.xml
Updates nrjavaserial to the official 3.20.0 release (compatible with Java 8/11).
With the upgraded version the library will no longer crash the Java 11 VM on Windows.
The native libraries now use the built in RXTX lockfiles instead of the previously used (OS dependent) liblockdev whereas the OH build didn't use any lockfiles at all.
It also has a fix for errors being printed when scanning for serial ports whenever a serial port is locked (NeuronRobotics/nrjavaserial#166).
With the new version RXTX threads also have proper names and there is a fix for an IllegalMonitorStateException that might occur when closing ports.
Fixes #1384
=> Update nrjavaserial to 3.20.0

itests/org.openhab.core.thing.xml.tests/src/main/resources/test-bundle-pool/ChannelTypesI18nTest.bundle/OH-INF/thing/thing-types.xml
- Fixed failing `ChannelTypesI18nTest` because of invalid XML - it is not allowed to have an empty channels-tag
That was never really noticeable because the related test allows to throw an `Exception` which does not look comfortable. The `Exception` has to be handled because it could be thrown by the `SyntheticBundleInstaller.install()` method.
https://github.com/openhab/openhab-core/blob/778c72eabbce798271edf189b356975c8a54569f/itests/org.openhab.core.thing.xml.tests/src/main/java/org/openhab/core/thing/xml/test/ChannelTypesI18nTest.java#L65-L67
https://github.com/openhab/openhab-core/blob/778c72eabbce798271edf189b356975c8a54569f/itests/org.openhab.core.thing.xml.tests/src/main/java/org/openhab/core/thing/xml/test/ChannelTypesI18nTest.java#L94-L96
Signed-off-by: Christoph Weitkamp …
=> Fixed failing 'ChannelTypesI18nTest' because of invalid XML

bundles/org.openhab.core.ui/src/main/java/org/openhab/core/ui/internal/items/ItemUIRegistryImpl.java, bundles/org.openhab.core/src/main/java/org/openhab/core/items/ItemRegistry.java
- Removed deprecated `newItemBuilder` method
=> Removed deprecated 'newItemBuilder' method

bundles/org.openhab.core.config.discovery/src/main/java/org/openhab/core/config/discovery/AbstractDiscoveryService.java, bundles/org.openhab.core.config.discovery/src/main/java/org/openhab/core/config/discovery/DiscoveryResult.java, bundles/org.openhab.core.config.discovery/src/main/java/org/openhab/core/config/discovery/DiscoveryResultBuilder.java, bundles/org.openhab.core.config.discovery/src/main/java/org/openhab/core/config/discovery/internal/DiscoveryResultImpl.java, bundles/org.openhab.core.config.discovery/src/test/java/org/openhab/core/config/discovery/inbox/InboxPredicatesTest.java, bundles/org.openhab.core.config.discovery/src/test/java/org/openhab/core/config/discovery/inbox/events/InboxEventFactoryTest.java, bundles/org.openhab.core.config.discovery/src/test/java/org/openhab/core/config/discovery/internal/DiscoveryResultImplTest.java, itests/org.openhab.core.config.discovery.tests/src/main/java/org/openhab/core/config/discovery/DiscoveryServiceMock.java, itests/org.openhab.core.config.discovery.tests/src/main/java/org/openhab/core/config/discovery/DiscoveryServiceMockOfBridge.java, itests/org.openhab.core.config.discovery.tests/src/main/java/org/openhab/core/config/discovery/inbox/DynamicThingUpdateOSGiTest.java, itests/org.openhab.core.config.discovery.tests/src/main/java/org/openhab/core/config/discovery/internal/InboxOSGiTest.java
- Removed deprecated constructor for `DiscoveryResultImpl`
- Replaced `DiscoveryResultImpl` by `DiscoveryResultBuilder`
=> Removed deprecated constructor for 'DiscoveryResultImpl'

bundles/org.openhab.core.model.script/src/org/openhab/core/model/script/actions/Timer.java, bundles/org.openhab.core.model.script/src/org/openhab/core/model/script/internal/actions/TimerImpl.java
The following is referring to org.eclipse.smarthome.model.script.actions.Timer
There seems to be no way to programmatically tell whether a timer is no longer "active" e.g. because it was cancelled.
There's Timer::hasTerminated() but that will only return true if the timer has finished executing. It will not return true if timer.cancel() was called before the scheduled execution occurred. 
Then there's Timer::isRunning() but that will only return true if the timer has reached its time and is actually still executing and not yet finished.
Example code to illustrate:
```
@rule("test1")
@when("System started")
def test(event):  
timer = ScriptExecution.createTimer(DateTime.now().plusSeconds(5), lambda: test.log.info("Timer executing. isRunning(): {}".format(timer.isRunning()))) …
```
=> [timer] Add Timer::isActive()

bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/handler/BaseModuleHandler.java, bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/ModuleImpl.java, bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/module/config/EphemerisConditionConfig.java, bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/module/handler/EphemerisConditionHandler.java, bundles/org.openhab.core.automation/src/test/java/org/openhab/core/automation/internal/module/factory/EphemerisModuleHandlerFactoryTest.java
- Fixed creation of `EphemerisConditionHandler`
Closes #1452
The `offset` is not required it should not throw an exception at all.
=> [automation] Fixed creation of 'EphemerisConditionHandler'

bom/runtime/pom.xml
Fixes resolving bundles in the Demo App.
It's a dependency of [org.apache.felix.webconsole](https://github.com/openhab/openhab-distro/blob/5e0d51c4c40593ca7720fcc4cb2f746e3a9ae2de/launch/app/app.bndrun#L8-L9)
Caused by: #1436
---
It's probably best to always check that bundles can still be resolved in the Demo App when changing this BOM.
=> Add commons-fileupload back to runtime BOM

bundles/org.openhab.core.config.core/src/main/java/org/openhab/core/config/core/ConfigDescriptionParameterBuilder.java, bundles/org.openhab.core.config.core/src/main/java/org/openhab/core/config/core/ConfigDescriptionParameterGroup.java, bundles/org.openhab.core.config.core/src/main/java/org/openhab/core/config/core/ConfigDescriptionParameterGroupBuilder.java, bundles/org.openhab.core.config.core/src/main/java/org/openhab/core/config/core/i18n/ConfigI18nLocalizationService.java, bundles/org.openhab.core.config.core/src/test/java/org/openhab/core/config/core/ConfigDescriptionBuilderTest.java, bundles/org.openhab.core.config.core/src/test/java/org/openhab/core/config/core/ConfigDescriptionParameterGroupBuilderTest.java, bundles/org.openhab.core.config.xml/src/main/java/org/openhab/core/config/xml/ConfigDescriptionParameterGroupConverter.java
- Added builder for `ConfigDescriptionParameterGroup`
We already have builder for `ConfigDescription`s and `ConfigDescriptionParameter`s. To improve and streamline the API I added a `ConfigDescriptionParameterGroupBuilder`.
=> [config] Added builder for 'ConfigDescriptionParameterGroup'

bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/module/handler/ItemStateConditionHandler.java
Previously, the state values were compared only if the item state was instanceof DecimalType
which did not work for channels that had a dimension specifier, such as Type:Length. The itemState
instance was of type QuantityType<Quantity<BigDecimal>> and therefore was never compared in the rules
Signed-off-by: Sebastian Irimia <aisebastian@yahoo.com>
=> [automation] add more robust value comparison

bom/compile/pom.xml, bom/runtime/pom.xml, bundles/org.openhab.core.io.transport.serial.rxtx.rfc2217/bnd.bnd, bundles/org.openhab.core.io.transport.serial.rxtx/bnd.bnd, features/karaf/openhab-tp/src/main/feature/feature.xml
The first version of nrjavaserial with OSGi manifest entries is 3.12.0.
The interface has not changed and is still the same with nrjavaserial 5.x.
So using 3.12.0 as compile time dependency and defining a [3.12,6) version range using bnd.bnd files allows for maximum flexibility.
=> Update nrjavaserial in TP to 5.0.2 and define import version range

bundles/org.openhab.core.io.transport.serial/src/main/java/org/openhab/core/io/transport/serial/SerialPortManager.java
The current JavaDocs do not clearly state that it does not always return all identifiers.
E.g. it will not return any RFC2217 identifiers or undiscovered RXTX port identifiers.
So it should not be used to search for an identifier when the serial port name is known.
This method is useful for listing available port options in UIs and logging.
---
Related to:
* https://github.com/openhab/openhab-core/issues/1462
* https://github.com/openhab/openhab-addons/pull/7609
=> Improve SerialPortManager.getIdentifiers() JavaDoc

bundles/org.openhab.core.config.core/src/main/java/org/openhab/core/config/core/internal/ConfigMapper.java, bundles/org.openhab.core.config.core/src/test/java/org/openhab/core/config/core/ConfigurationTest.java
- Use field from calling method to check superclass hierarchy for writing fields in `ConfigMapper`
Fixes #1473
=> [config] Use field from calling method to check superclass hierarchy for writing fields in 'ConfigMapper'

bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/binding/BaseBridgeHandler.java
- Removed `getThingByUID()` method from `BaseBridgeHandler`
The code for `BaseBridgeHandler#getThingByUID(ThingUID)` and `BridgeImpl#getThing(ThingUID)` are identical thus I marked it as deprecated.
Another option will be to remove it right now. 
---
Related to https://github.com/openhab/openhab-addons/pull/7665
=> [thing] Removed 'getThingByUID()' method from 'BaseBridgeHandler'

bundles/org.openhab.core.auth.oauth2client/src/main/java/org/openhab/core/auth/oauth2client/internal/OAuthConnector.java, bundles/org.openhab.core.automation.rest/src/main/java/org/openhab/core/automation/rest/internal/RuleResource.java, bundles/org.openhab.core.io.net/src/main/java/org/openhab/core/io/net/http/HttpUtil.java, bundles/org.openhab.core.model.core/src/main/java/org/openhab/core/model/core/internal/ModelRepositoryImpl.java, bundles/org.openhab.core.storage.json/src/main/java/org/openhab/core/storage/json/internal/JsonStorageService.java, itests/org.openhab.core.storage.json.tests/src/main/java/org/openhab/core/storage/json/internal/JsonStorageServiceOSGiTest.java
- Avoid `UnsupportedEncodingException`
- Use const from StandardCharsets
=> Avoid UnsupportedEncodingException & use const from StandardCharsets

bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/provider/i18n/ModuleTypeI18nServiceImpl.java, bundles/org.openhab.core.config.core/src/main/java/org/openhab/core/config/core/ConfigDescription.java, bundles/org.openhab.core.config.core/src/main/java/org/openhab/core/config/core/ConfigDescriptionParameter.java, bundles/org.openhab.core.config.core/src/main/java/org/openhab/core/config/core/ConfigDescriptionParameterBuilder.java, bundles/org.openhab.core.config.core/src/main/java/org/openhab/core/config/core/ConfigDescriptionRegistry.java, bundles/org.openhab.core.config.core/src/main/java/org/openhab/core/config/core/ConfigUtil.java, bundles/org.openhab.core.config.core/src/main/java/org/openhab/core/config/core/i18n/ConfigI18nLocalizationService.java, bundles/org.openhab.core.config.core/src/main/java/org/openhab/core/config/core/internal/metadata/MetadataConfigDescriptionProviderImpl.java, bundles/org.openhab.core.config.core/src/test/java/org/openhab/core/config/core/ConfigDescriptionParameterBuilderTest.java, bundles/org.openhab.core.config.core/src/test/java/org/openhab/core/config/core/ConfigDescriptionRegistryTest.java, bundles/org.openhab.core.config.core/src/test/java/org/openhab/core/config/core/ConfigUtilTest.java, bundles/org.openhab.core.config.core/src/test/java/org/openhab/core/config/core/internal/normalization/NormalizerTest.java, bundles/org.openhab.core.config.core/src/test/java/org/openhab/core/config/core/internal/validation/ConfigDescriptionValidatorTest.java, bundles/org.openhab.core.config.discovery/src/test/java/org/openhab/core/config/discovery/internal/PersistentInboxTest.java, bundles/org.openhab.core.config.xml/src/main/java/org/openhab/core/config/xml/ConfigDescriptionConverter.java, bundles/org.openhab.core.config.xml/src/main/java/org/openhab/core/config/xml/ConfigDescriptionParameterConverter.java, bundles/org.openhab.core.io.rest.core/src/test/java/org/openhab/core/io/rest/core/config/EnrichedConfigDescriptionDTOMapperTest.java, bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/internal/link/ItemChannelLinkConfigDescriptionProvider.java, itests/org.openhab.core.automation.integration.tests/src/main/java/org/openhab/core/automation/integration/test/AutomationIntegrationTest.java, itests/org.openhab.core.config.core.tests/src/main/java/org/openhab/core/config/core/ConfigOptionRegistryOSGiTest.java, itests/org.openhab.core.config.discovery.tests/src/main/java/org/openhab/core/config/discovery/internal/InboxOSGiTest.java, itests/org.openhab.core.model.thing.tests/src/main/java/org/openhab/core/model/thing/test/hue/GenericThingProviderTest3.java, itests/org.openhab.core.model.thing.testsupport/src/main/java/org/openhab/core/model/thing/testsupport/hue/TestHueConfigDescriptionProvider.java, itests/org.openhab.core.thing.tests/src/main/java/org/openhab/core/thing/binding/BindingBaseClassesOSGiTest.java, itests/org.openhab.core.thing.tests/src/main/java/org/openhab/core/thing/binding/ChangeThingTypeOSGiTest.java, itests/org.openhab.core.thing.tests/src/main/java/org/openhab/core/thing/binding/ThingFactoryTest.java, itests/org.openhab.core.thing.tests/src/main/java/org/openhab/core/thing/internal/ThingManagerOSGiJavaTest.java, itests/org.openhab.core.thing.tests/src/main/java/org/openhab/core/thing/internal/ThingManagerOSGiTest.java
- Removed deprecated constructors and methods from Config API
- Replaced deprecated constructors by related builder where possible
Relates to #1408
=> Removed deprecated constructors and methods from Config API

bundles/org.openhab.core.automation.module.script.rulesupport/src/main/java/org/openhab/core/automation/module/script/rulesupport/internal/loader/ScriptFileWatcher.java
- Use UTF-8 to read files
Otherwise I am seeing e.g. such log messages:
```
2020-05-19 14:37:56.639 [INFO ] [ipse.smarthome.model.script.presence] - Trigger fÃ¼r presenceChristophPresent changed from OFF to ON ...
```
Or wrong tags:
```JSON
"tags": [
"Anwesenheit",
"KÃ¼che"
],
```
=> [automation] Use UTF-8 to read files

bundles/org.openhab.core.audio/src/main/java/org/openhab/core/audio/internal/AudioManagerImpl.java, bundles/org.openhab.core.config.core/src/main/java/org/openhab/core/config/core/ConfigurableService.java, bundles/org.openhab.core.config.discovery/src/main/java/org/openhab/core/config/discovery/internal/AutomaticInboxProcessor.java, bundles/org.openhab.core.ephemeris/src/main/java/org/openhab/core/ephemeris/internal/EphemerisManagerImpl.java, bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/internal/service/ConfigurableServiceResource.java, bundles/org.openhab.core.io.transport.mqtt/src/main/java/org/openhab/core/io/transport/mqtt/internal/MqttBrokerConnectionServiceInstanceMarker.java, bundles/org.openhab.core.karaf/src/main/java/org/openhab/core/karaf/internal/FeatureInstaller.java, bundles/org.openhab.core.model.lsp/src/main/java/org/openhab/core/model/lsp/internal/ModelServer.java, bundles/org.openhab.core.model.script/src/org/openhab/core/model/script/internal/RuleHumanLanguageInterpreter.java, bundles/org.openhab.core.persistence/src/main/java/org/openhab/core/persistence/internal/PersistenceServiceRegistryImpl.java, bundles/org.openhab.core.storage.json/src/main/java/org/openhab/core/storage/json/internal/JsonStorageService.java, bundles/org.openhab.core.ui/src/main/java/org/openhab/core/ui/internal/chart/ChartServlet.java, bundles/org.openhab.core.voice/src/main/java/org/openhab/core/voice/internal/VoiceManagerImpl.java, itests/org.openhab.core.io.rest.core.tests/src/main/java/org/openhab/core/io/rest/core/internal/service/ConfigurableServiceResourceOSGiTest.java
It is easier to use the `ConfigurableService` properties when it's possible to annotate classes using a `ComponentPropertyType`.
---
I gave it a test and it is backwards compatible with the ported add-ons that still use the properties.
=> Use ConfigurableService as ComponentPropertyType

bundles/org.openhab.core.voice/src/main/java/org/openhab/core/voice/text/ASTNode.java, bundles/org.openhab.core.voice/src/main/java/org/openhab/core/voice/text/AbstractRuleBasedInterpreter.java, bundles/org.openhab.core/src/main/java/org/openhab/core/scheduler/CronScheduler.java, itests/pom.xml, pom.xml
See: https://github.com/openhab/openhab-core/pull/1345#issuecomment-632639071
It seems to produce something useful when I run:
`mvn javadoc:javadoc javadoc:aggregate -B -Dfeatures.verify.skip=true -Dspotless.check.skip=true -T 1C`
Can you check the result @mhilbush?
=> Update maven-javadoc-plugin to 3.2.0

bundles/org.openhab.core/src/main/java/org/openhab/core/items/ManagedItemProvider.java
- Removed unused `InstanceCreator` implementation
See https://github.com/openhab/openhab-core/pull/1488#issuecomment-632760388
=> Removed unused 'InstanceCreator' implementation

bom/runtime/pom.xml, features/karaf/openhab-tp/src/main/feature/feature.xml
With this version it will no longer completely exit :exclamation:  the JVM in certain scenarios when ports are closed/reopened.
Related to:
* openhab/org.openhab.binding.zigbee#577
* openhab/org.openhab.binding.zwave#1332
=> Update nrjavaserial in TP to 5.2.1

bundles/org.openhab.core/src/main/java/org/openhab/core/common/registry/AbstractRegistry.java
This ensures that the managed provider is unregistered by the same provider that is registered. Otherwise it's possible for the provider to be inadvertently removed.
Signed-off-by: Chris Jackson <chris@cd-jackson.com>
=> Ensure managed provider is unset by registered provider

bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/module/factory/CoreModuleHandlerFactory.java, bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/module/handler/GenericCronTriggerHandler.java, bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/module/handler/GroupCommandTriggerHandler.java, bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/module/handler/GroupStateTriggerHandler.java, bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/module/handler/SystemTriggerHandler.java, bundles/org.openhab.core.automation/src/main/resources/OH-INF/automation/moduletypes/ItemTriggers.json, bundles/org.openhab.core.automation/src/main/resources/OH-INF/automation/moduletypes/SystemTriggers.json, bundles/org.openhab.core/src/main/java/org/openhab/core/events/system/StartlevelEvent.java, bundles/org.openhab.core/src/main/java/org/openhab/core/events/system/SystemEventFactory.java
This PR completes the automation component to provide the same triggers as the "old" rule engine. It thus specifically adds modules for "member of group" triggers as well as a start level trigger, which can be used to run rules once at system startup (disclaimer: No start level events are defined in this PR yet, so the trigger itself is still rather useless).
This was part of #1451 and has been separated as an independent PR that can already been reviewed and merged independently.
=> Added group and system triggers to automation component

bundles/org.openhab.core.model.core/src/main/java/org/openhab/core/model/core/ModelRepository.java, bundles/org.openhab.core.model.core/src/main/java/org/openhab/core/model/core/internal/ModelRepositoryImpl.java, bundles/org.openhab.core.model.core/src/main/java/org/openhab/core/model/core/internal/folder/FolderObserver.java, itests/org.openhab.core.model.core.tests/src/main/java/org/openhab/core/model/core/internal/folder/FolderObserverTest.java
- Model refactoring, Memory Leak prevention, UTF-8 encoding
Beside our basic improvements (nullness annotations and constructor injection) this draft tries to address two other issues - I will link them, when I find them - eventually they are placed in old ESH repository. First one is a potential memory leak in the `ModelRepositoryÌmpl` where we did not close the copied `InputStream`s (e.g. for validation). Second one is a potential encoding issue - I added `XtextResource.OPTION_ENCODING = "UTF-8"` in all places where the resources are loaded.
What do you think about that? I am fine with splitting this PR into smaller pieces.
But there might be a bigger problem related to the internal `resourceSet` (`SynchronizedXtextResourceSet`). Today I faced a system crash and luckily I could save the …
=> Model refactoring, Memory Leak prevention, UTF-8 encoding

bundles/org.openhab.core.model.core/src/main/java/org/openhab/core/model/core/internal/ModelRepositoryImpl.java, bundles/org.openhab.core.model.core/src/main/java/org/openhab/core/model/core/internal/folder/FolderObserver.java, bundles/org.openhab.core.model.item/src/org/openhab/core/model/item/internal/GenericItemProvider.java, itests/org.openhab.core.model.core.tests/src/main/java/org/openhab/core/model/core/internal/folder/FolderObserverTest.java
Some further changes extracted from my work in #1451:
- removed superfluous null checks
- improved logging
- fixed bug that cause "_tmp" resources to be loaded (which are only internally temporarily created during model validation)
- added ready marker after finishing loading a model type
- let GenericItemProvider only start once at least one ItemFactory is available (I often had the effect in the IDE that items were not available as the file was loaded before the CoreItemFactory was available).
=> [dsl] Model loading improvements

bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/internal/thing/ThingTypeResource.java
A nullpointer exception is thrown when it cannot find the channel group type. This happens during development of bindings when you made a typo. This add a helpful message to the logs to help the binding developer.
=> Give the missing channel group type

bundles/org.openhab.core/src/main/java/org/openhab/core/items/ItemUtil.java, bundles/org.openhab.core/src/main/java/org/openhab/core/library/types/DateTimeType.java, bundles/org.openhab.core/src/main/java/org/openhab/core/library/types/RawType.java, bundles/org.openhab.core/src/test/java/org/openhab/core/library/types/DateTimeTypeTest.java, itests/org.openhab.core.tests/src/main/java/org/openhab/core/items/GroupItemOSGiTest.java
- Removed deprecated constructors and methods
---
Depends on https://github.com/openhab/openhab-addons/pull/7766
=> Removed deprecated constructors and methods

bundles/org.openhab.core/src/main/java/org/openhab/core/library/types/QuantityType.java, bundles/org.openhab.core/src/test/java/org/openhab/core/library/types/QuantityTypeTest.java
- Allow DateTimeFormat for labels of Number:Time items
=> [uom] Allow DateTimeFormat for labels of Number:Time items

bundles/org.openhab.core.model.item/src/org/openhab/core/model/Items.xtext, bundles/org.openhab.core.model.thing/src/org/openhab/core/model/thing/Thing.xtext, itests/org.openhab.core.model.item.tests/src/main/java/org/openhab/core/model/item/internal/GenericItemProviderTest.java
- Allow negative numbers in metadata for Items
What is the best solution:
> If we compare the grammar to the one for Things there is exactly the "-" sign missing.
> 
> https://github.com/openhab/openhab-core/blob/1f4e374ece9d8d72f5bc77d647152b9430ca7524/bundles/org.openhab.core.model.thing/src/org/openhab/core/model/thing/Thing.xtext#L96
> 
> We have options to solve it.
> 
> 1. Add the "-" sign to the terminal `ID` in the Items grammar. This could lead to an impact on the Item names because the terminal `ID` is used to define allowed characters for it too.
> 2. Add an optional "-" sign for the `NUMBER` definition like this
> 
> ```
> NUMBER returns ecore::EBigDecimal:
>     ('-')? ID ('.' ID )?
> ;
> ```
Closes #1501
=> [dsl] Allow negative numbers in metadata for Items

bundles/org.openhab.core.io.rest/src/main/java/org/openhab/core/io/rest/SseBroadcaster.java
- Suppress ISE in `SseBroadcaster` if sink already has been closed
I am having a lot if ISEs in my log when working with new Default UI:
```
07:45:24.448 [WARN ] [g.openhab.core.io.rest.SseBroadcaster] - failure
java.lang.IllegalStateException: The sink has been already closed
at org.apache.cxf.jaxrs.sse.SseEventSinkImpl.close(SseEventSinkImpl.java:157) [bundleFile:1.0.8]
at org.openhab.core.io.rest.SseBroadcaster.close(SseBroadcaster.java:148) [bundleFile:?]
at org.openhab.core.io.rest.SseBroadcaster.lambda$2(SseBroadcaster.java:109) [bundleFile:?]
at java.util.concurrent.CompletableFuture.uniExceptionally(CompletableFuture.java:986) [?:?]
at java.util.concurrent.CompletableFuture$UniExceptionally.tryFire(CompletableFuture.java:970) [?:?]
at …
```
=> [rest] Suppress ISE in 'SseBroadcaster' if sink already has been closed

bundles/org.openhab.core/src/main/java/org/openhab/core/internal/items/GroupFunctionHelper.java, bundles/org.openhab.core/src/main/java/org/openhab/core/items/dto/ItemDTOMapper.java, bundles/org.openhab.core/src/main/java/org/openhab/core/types/TypeParser.java, itests/org.openhab.core.tests/src/main/java/org/openhab/core/items/GroupItemOSGiTest.java
- Moved `parseState()` method into `GroupFunctionHelper` and apply only if
needed
Fixes #1531 
=> Moved 'parseState()' method into 'GroupFunctionHelper' and apply only if needed

bundles/org.openhab.core.audio/src/main/java/org/openhab/core/audio/internal/AudioManagerImpl.java, bundles/org.openhab.core.audio/src/test/java/org/openhab/core/audio/internal/AudioManagerTest.java, bundles/org.openhab.core.config.core/src/main/java/org/openhab/core/config/core/ConfigOptionProvider.java, bundles/org.openhab.core.config.core/src/main/java/org/openhab/core/config/core/internal/i18n/I18nConfigOptionsProvider.java, bundles/org.openhab.core.config.core/src/main/java/org/openhab/core/config/core/internal/net/NetworkConfigOptionProvider.java, bundles/org.openhab.core.config.core/src/test/java/org/openhab/core/config/core/internal/i18n/I18nConfigOptionsProviderTest.java, bundles/org.openhab.core.config.serial/src/main/java/org/openhab/core/config/serial/internal/SerialConfigOptionProvider.java, bundles/org.openhab.core.ephemeris/src/main/java/org/openhab/core/ephemeris/internal/EphemerisManagerImpl.java, bundles/org.openhab.core.persistence/src/main/java/org/openhab/core/persistence/internal/PersistenceServiceRegistryImpl.java, bundles/org.openhab.core.test.magic/src/main/java/org/openhab/core/magic/binding/internal/MagicServiceImpl.java, bundles/org.openhab.core.voice/src/main/java/org/openhab/core/voice/internal/VoiceManagerImpl.java, itests/org.openhab.core.ephemeris.tests/src/main/java/org/openhab/core/ephemeris/internal/EphemerisManagerImplOSGiTest.java, itests/org.openhab.core.voice.tests/src/main/java/org/openhab/core/voice/internal/VoiceManagerImplTest.java
- Remove deprecated method of `ConfigOptionProvider`
---
Depends on https://github.com/openhab/openhab-addons/pull/8093
=> Remove deprecated method of 'ConfigOptionProvider'

bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/internal/extensions/ExtensionResource.java
The getById method is missing the ":". See the install and uninstall method.
=> Use the same regex as the install and uninstall method

bundles/org.openhab.core.persistence/src/main/java/org/openhab/core/persistence/QueryablePersistenceService.java
- [persistence] Clarification in JavaDoc about `QueryablePersistenceService` methods
See https://github.com/openhab/openhab-addons/issues/8138#issuecomment-659582158
=> [persistence] Clarification in JavaDoc about 'QueryablePersistenceService' methods

bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/internal/link/ItemChannelLinkResource.java
This changes the value in the "responseContainer" attribute to one of the three valid values.
The [documentation](https://docs.swagger.io/swagger-core/v1.5.0/apidocs/io/swagger/annotations/ApiResponse.html#responseContainer()) says:
_"Valid values are "List", "Set" or "Map". Any other value will be ignored."_
This fixes #1550
=> [REST] Change responseContainer from Collection to List in swagger @ApiOperation and @ApiResponse annotations

bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/internal/binding/BindingResource.java
By default the Swagger plugin uses the method name as operationId.
Since the operationId must be unique across all methods and some method names are named the same, we should use the nickname element in the ApiOperation annotation and thus set the operationId manually.
I will create more prs for some other classes that need to be fixed.
Reference:
* [Nickname attribute](https://docs.swagger.io/swagger-core/v1.5.X/apidocs/io/swagger/annotations/ApiOperation.html#nickname--) in swagger annotations documentation
* [Operation Object](https://swagger.io/specification/#operation-object) in swagger specification
=> [rest] introduce nickname attribute in ApiOperation annotation to make operationIds unique

bundles/org.openhab.core/src/main/java/org/openhab/core/net/CidrAddress.java
We can remove the explicit conversion to the string, as this is done implicitly.
=> [Code style] Remove unnecessary conversion to string

bundles/org.openhab.core/src/main/java/org/openhab/core/internal/scheduler/CronAdjuster.java
Replaces the way an array is declared with the way "prefered for java", because the [] is part of the TYPE and not the NAME.
I think this makes it more readable and easier to understand.
See [this stackoverflow post](https://stackoverflow.com/questions/129178/difference-between-int-array-and-int-array) for reference.
=> [Code style] Replace c-style array declaration with java-style array declaration

bundles/org.openhab.core.automation.rest/src/main/java/org/openhab/core/automation/rest/internal/RuleResource.java
This changes the value in the "responseContainer" attribute to one of the three valid values.
The [documentation](https://docs.swagger.io/swagger-core/v1.5.0/apidocs/io/swagger/annotations/ApiResponse.html#responseContainer()) says:
"Valid values are "List", "Set" or "Map". Any other value will be ignored."
See #1553
=> [REST] RuleResource: Change responseContainer from Collection to List in swagger @ApiOperation and @ApiResponse annotations

bundles/org.openhab.core.automation.rest/src/main/java/org/openhab/core/automation/rest/internal/TemplateResource.java
This changes the value in the "responseContainer" attribute to one of the three valid values.
The [documentation](https://docs.swagger.io/swagger-core/v1.5.0/apidocs/io/swagger/annotations/ApiResponse.html#responseContainer()) says:
"Valid values are "List", "Set" or "Map". Any other value will be ignored."
See #1553 and #1554
=> [REST] TemplateResource: Change responseContainer from Collection to List in swagger @ApiOperation and @ApiResponse annotations

bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/internal/config/ConfigDescriptionResource.java
By default the Swagger plugin uses the method name as operationId.
Since the operationId must be unique across all methods and some method names are named the same, we should use the nickname element in the ApiOperation annotation and thus set the operationId manually.
The `getAll()` method in `ConfigDescriptionResource.java` does not have a nickname set in its `@ApiOperation` annotation.
Swagger uses the method name (getAll) as default operationId which is not unique.
I will create more prs for some other classes that need to be fixed.
Reference:
* [Nickname attribute](https://docs.swagger.io/swagger-core/v1.5.X/apidocs/io/swagger/annotations/ApiOperation.html#nickname--) in swagger annotations documentation
* [Operation Object](https://swagger.io/specification/#operation-object) in …
=> [rest] introduce nickname attribute in ConfigDescriptionResource to make swaggers operationId unique

bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/module/provider/AnnotatedActionModuleTypeProvider.java, bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/module/provider/AnnotationActionModuleTypeHelper.java, bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/thingsupport/AnnotatedThingActionModuleTypeProvider.java, bundles/org.openhab.core.automation/src/test/java/org/openhab/core/automation/thingsupport/AnnotatedThingActionModuleTypeProviderTest.java
- Fixed removal / replacement of annotated `ThingActions`
Beside fixing https://github.com/openhab/openhab-core/issues/1265#issuecomment-651766273 I added some warnings for developers and missing null-checks inside the code. 
=> [automation] Fixed duplication of config descriptions

bundles/org.openhab.core.io.http/src/main/java/org/openhab/core/io/http/internal/SmartHomeHttpContext.java, bundles/org.openhab.core.karaf/src/main/java/org/openhab/core/karaf/internal/KarafExtensionService.java
Uses List.sort() instead of Collections.sort() to sort lists.
This function was introduced with Java 8 and might speed up sorting a bit.
See [javadocs](https://docs.oracle.com/javase/8/docs/api/java/util/List.html#sort-java.util.Comparator-) for reference.
Second try, see #1558
=> Use more java 8 features: Replace Collections.sort() with List.sort() (second try)

bundles/org.openhab.core.automation/src/test/java/org/openhab/core/automation/internal/module/provider/AnnotationActionModuleTypeProviderTest.java, bundles/org.openhab.core.io.transport.mqtt/src/test/java/org/openhab/core/io/transport/mqtt/MqttBrokerConnectionTests.java, bundles/org.openhab.core.thing/src/test/java/org/openhab/core/thing/internal/ThingManagerImplTest.java, bundles/org.openhab.core/src/test/java/org/openhab/core/common/QueueingThreadPoolExecutorTest.java, bundles/org.openhab.core/src/test/java/org/openhab/core/internal/items/MetadataCommandDescriptionProviderTest.java, bundles/org.openhab.core/src/test/java/org/openhab/core/internal/items/MetadataStateDescriptionFragmentProviderTest.java, bundles/org.openhab.core/src/test/java/org/openhab/core/library/types/DecimalTypeTest.java, bundles/org.openhab.core/src/test/java/org/openhab/core/library/types/OnOffTypeTest.java, bundles/org.openhab.core/src/test/java/org/openhab/core/library/types/OpenClosedTypeTest.java, bundles/org.openhab.core/src/test/java/org/openhab/core/library/types/PercentTypeTest.java, bundles/org.openhab.core/src/test/java/org/openhab/core/library/types/StringTypeTest.java, bundles/org.openhab.core/src/test/java/org/openhab/core/library/types/UpDownTypeTest.java, itests/org.openhab.core.ephemeris.tests/src/main/java/org/openhab/core/ephemeris/internal/EphemerisManagerImplOSGiTest.java, itests/org.openhab.core.model.script.tests/src/main/java/org/openhab/core/model/script/engine/ScriptEngineOSGiTest.java, itests/org.openhab.core.thing.tests/src/main/java/org/openhab/core/thing/internal/ChannelCommandDescriptionProviderOSGiTest.java, itests/org.openhab.core.thing.tests/src/main/java/org/openhab/core/thing/internal/ChannelStateDescriptionProviderOSGiTest.java
Simplifies JUnit assertions with `assertEquals()` where the expected parameter is `true` or `false`, replacing them with `assertTrue()` or `assertFalse()`.
Also simplifies `assertEquals()` with null parameter (assertions against null) by replacing the function with `assertNull()`.
=> [Code style] Cleanup tests: Simplify assertEquals to assertTrue or assertFalse

bundles/org.openhab.core.io.rest.swagger/src/main/java/org/openhab/core/io/rest/swagger/impl/SwaggerResource.java, features/karaf/openhab-core/src/main/feature/feature.xml
Related to https://github.com/openhab/openhab-webui/pull/297
Also added it to the runtime-base for now.
=> Made swagger visible in the RootResource (/rest)

bom/compile/pom.xml, bom/runtime/pom.xml, bundles/org.openhab.core.automation.rest/src/main/java/org/openhab/core/automation/rest/internal/RuleResource.java, bundles/org.openhab.core.id/src/main/java/org/openhab/core/id/internal/UUIDResource.java, bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/internal/addons/AddonResource.java, bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/internal/binding/BindingResource.java, bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/internal/channel/ChannelTypeResource.java, bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/internal/config/ConfigDescriptionResource.java, bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/internal/discovery/DiscoveryResource.java, bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/internal/discovery/InboxResource.java, bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/internal/item/ItemResource.java, bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/internal/link/ItemChannelLinkResource.java, bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/internal/persistence/PersistenceResource.java, bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/internal/profile/ProfileTypeResource.java, bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/internal/service/ConfigurableServiceResource.java, bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/internal/thing/ThingResource.java, bundles/org.openhab.core.io.rest.swagger/src/main/java/org/openhab/core/io/rest/swagger/impl/AuthSwaggerReaderListener.java, bundles/org.openhab.core.io.rest.swagger/src/main/java/org/openhab/core/io/rest/swagger/impl/InfoSwaggerReaderListener.java, bundles/org.openhab.core.io.rest.swagger/src/main/java/org/openhab/core/io/rest/swagger/impl/SwaggerResource.java, bundles/org.openhab.core.io.rest.ui/src/main/java/org/openhab/core/io/rest/ui/internal/UIResource.java, bundles/org.openhab.core.io.rest/src/main/java/org/openhab/core/io/rest/RESTConstants.java, bundles/org.openhab.core.io.rest/src/main/java/org/openhab/core/io/rest/RESTResource.java, bundles/org.openhab.core.io.rest/src/main/java/org/openhab/core/io/rest/internal/resources/beans/RootBean.java, features/karaf/openhab-core/src/main/feature/feature.xml, features/karaf/openhab-tp/src/main/feature/feature.xml
This is another attempt at #1483 without any blatant (but inadvertent!) third-party code borrowing & relicensing this time.
This introduces the ability to [customize the Swagger Definition](https://github.com/swagger-api/swagger-core/wiki/Annotations-1.5.X#customising-the-swagger-definition) in a way supported directly by swagger-jaxrs by providing `ReaderListener` implementations with DI. Two of them are implemented in this PR: one to add general information and the other to add the OAuth2 security definition (which will only be injected if the auth bundle is installed).
Additionally the enumeration of resources has been simplified for openHAB's purposes as they all implement `RESTResource` and there is only one `Application`, so they can be looked up and fed to the Swagger `Reader` …
=> Swagger: support injection of ReaderListener, add OAuth2 annotations

bundles/org.openhab.core.io.rest/src/main/java/org/openhab/core/io/rest/internal/resources/RootResource.java, bundles/org.openhab.core.io.rest/src/main/java/org/openhab/core/io/rest/internal/resources/beans/RootBean.java
This adds basic information about the runtime in the response
to the root `/rest` API resource, mostly for display purposes
by UIs: the version, build string and the location of the
configuration and user data folders.
=> REST: add runtime info to root resource response

bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/binding/builder/ChannelBuilder.java, bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/binding/builder/ThingBuilder.java, bundles/org.openhab.core.thing/src/test/java/org/openhab/core/thing/binding/builder/ChannelBuilderTest.java, bundles/org.openhab.core.thing/src/test/java/org/openhab/core/thing/binding/builder/ThingBuilderTest.java, bundles/org.openhab.core.thing/src/test/java/org/openhab/core/thing/internal/AutoUpdateManagerTest.java, itests/org.openhab.core.thing.tests/src/main/java/org/openhab/core/thing/binding/BindingBaseClassesOSGiTest.java, itests/org.openhab.core.thing.tests/src/main/java/org/openhab/core/thing/internal/CommunicationManagerOSGiTest.java, itests/org.openhab.core.thing.tests/src/main/java/org/openhab/core/thing/internal/ThingManagerOSGiTest.java, itests/org.openhab.core.thing.tests/src/main/java/org/openhab/core/thing/link/ItemChannelLinkOSGiTest.java
- Added `Channelbuilder.create(ChannelUID)` method -> as a consequence we additionally need a `withAcceptedItemType(String)` method
- Enhanced JavaDoc for `ChannelBuilder` 
Follow-up of discussion in https://github.com/openhab/openhab-addons/pull/6678#discussion_r457121894 and ff.
=> Added shortcut method 'Channelbuilder.create(ChannelUID)', Enhanced JavaDoc for 'ChannelBuilder'

bundles/org.openhab.core/src/main/java/org/openhab/core/library/types/QuantityType.java
The following asserts failed for me when building in CEST:
```
assertThat(seconds.format("%1$tH:%1$tM:%1$tS"), is("00:01:20"));
assertThat(millis.format("%1$tHh %1$tMm %1$tSs"), is("00h 01m 20s"));
```
In the original code it would convert the quantity to my timezone by adding 1h and thus formatting the 80s quantity as `01:01:20` and `01h 01m 20s` respectively.
Caused by #1470
=> Fix QuantityType.format timezone bug

pom.xml
I would suggest to use the version range for the Super POM here as well - like we do it in all other repositories (e.g. [here ](https://github.com/openhab/openhab-addons/blob/2.5.x/pom.xml#L7 ) and [here](https://github.com/openhab/openhab-distro/blob/2.5.x/pom.xml#L7)).
=> Use version range for Super POM

bom/compile/pom.xml
This newer version would make bnd resolve the lower bound to 1.2 instead of 1.1 for add-ons.
See: https://github.com/openhab/openhab-core/pull/1576#issuecomment-670972932
=> Exclude transitive activation-api dependency from swagger

bundles/org.openhab.core.io.net/src/main/java/org/openhab/core/io/net/exec/ExecUtil.java
This PR reduces some aggressive log levels that had been introduced with https://github.com/openhab/openhab-core/pull/1359. They cause stack traces to occur when code is testing whether a certain command is available, like the network binding is doing:
```
2020-08-10 22:21:08.205 [ERROR] [rg.openhab.core.io.net.exec.ExecUtil] - couldn't execute commandLine 'arping --help'
java.io.IOException: Cannot run program "arping --help": error=2, No such file or directory
at java.lang.ProcessBuilder.start(ProcessBuilder.java:1128) ~[?:?]
at java.lang.ProcessBuilder.start(ProcessBuilder.java:1071) ~[?:?]
at org.openhab.core.io.net.exec.ExecUtil.internalExecute(ExecUtil.java:104) [bundleFile:?]
at org.openhab.core.io.net.exec.ExecUtil.executeCommandLineAndWaitResponse(ExecUtil.java:72) [bundleFile:?] …
```
=> reduced log levels of ExecUtil

bundles/org.openhab.core.model.script/src/org/openhab/core/model/script/actions/Log.java, bundles/org.openhab.core.model.script/src/org/openhab/core/model/script/scoping/ScriptImplicitlyImportedTypes.java, tools/static-code-analysis/spotbugs/suppressions.xml
The log feature in scripts got accidentially lost in https://github.com/openhab/openhab-core/pull/1588.
Additionally, I noticed that those classes only need to be added as static imports, but not as extensions. Extensions are merely used for operator overloading and stuff like that.
=> re-added log action to script scope and cleaned up imported extensions

bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/internal/item/ItemResource.java, bundles/org.openhab.core.io.rest.sitemap/src/main/java/org/openhab/core/io/rest/sitemap/internal/SitemapResource.java
Fixes https://github.com/openhab/openhab-android/issues/2139
=> [rest] fixed item links in rest api

bundles/org.openhab.core.model.script/src/org/openhab/core/model/script/scoping/ScriptImplicitlyImportedTypes.java
I just learned that [my latest learning](https://github.com/openhab/openhab-core/pull/1590#issue-467620666) was not fully correct. Statically imported methods can/should also be registered as extensions, if it is desired to have them made available as a method on the type of their first parameter. We specifically make use of this feature for sending commands by writing
```
MyItem.sendCommand(ON)
```
instead of
```
sendCommand(MyItem, ON)
```
I accidentially broke that feature with https://github.com/openhab/openhab-core/pull/1590, sorry for that.
It can be neat to have it for some of the other methods as well, so I re-added them again, where it makes sense.
=> registered static methods as extensions

bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/internal/profiles/ProfileCallbackImpl.java
Adding a call to the TypeParser in ProfileCallbackImpl#sendUpdate if the provided state is a StringType (which is what transform profiles return) and the linked item is not a StringItem. This should enable transform profiles to be used with other item types.
Fixes #1565 
Signed-off-by: Anders Alfredsson <andersb86@gmail.com>
=> Use TypeParser in ProfileCallbackImpl#sendUpdate for StringType state

bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/binding/BaseThingHandler.java
With the changes in #1598 the BaseThingHandler could no longer update property values to null.
---
In the unchanged Nest tests the following stracktraces were logged:
```
[pool-80-thread-1] WARN  o.o.b.n.i.r.NestStreamingRestClient - An exception occurred while processing the inbound event
java.lang.NullPointerException: null
at java.base/java.util.Objects.requireNonNull(Objects.java:221)
at java.base/java.util.ImmutableCollections$Map1.<init>(ImmutableCollections.java:749)
at java.base/java.util.Map.of(Map.java:1307)
at org.openhab.core.thing.binding.BaseThingHandler.updateProperty(BaseThingHandler.java:512)
at org.openhab.binding.nest.internal.handler.NestThermostatHandler.update(NestThermostatHandler.java:211)
at org.openhab.binding.nest.internal.handler.NestThermostatHandler.update(Nes …
```
=> Allow property value to be updated to null

bundles/org.openhab.core.karaf/src/main/java/org/openhab/core/karaf/internal/FeatureInstaller.java, bundles/org.openhab.core/src/main/java/org/openhab/core/addon/AddonEvent.java
- Checking the existence of an add-on before trying to install it and otherwise logging a warning.
- Additionally checking for real changes in the config, which stops the regular re-installation mechanism that otherwise runs every minute. In case of a failure, this means people have to manually restart or to change their configuration once, but they anyhow see an error in the log.
- Applied thread naming convention and removed one (hopefully?) unnecessary scheduler thread.
=> Improved add-on installation logic

bundles/org.openhab.core.config.discovery/src/main/java/org/openhab/core/config/discovery/DiscoveryResultBuilder.java, bundles/org.openhab.core.config.discovery/src/test/java/org/openhab/core/config/discovery/DiscoveryResultBuilderTest.java, itests/org.openhab.core.config.discovery.tests/src/main/java/org/openhab/core/config/discovery/DiscoveryServiceMock.java, itests/org.openhab.core.config.discovery.tests/src/main/java/org/openhab/core/config/discovery/DiscoveryServiceMockOfBridge.java, itests/org.openhab.core.config.discovery.tests/src/main/java/org/openhab/core/config/discovery/DiscoveryServiceRegistryOSGiTest.java, itests/org.openhab.core.config.discovery.tests/src/main/java/org/openhab/core/config/discovery/internal/InboxOSGiTest.java
- Added validation for relation between `ThingUID` and `BridgeUID`
See discussion in https://github.com/openhab/openhab-addons/pull/7496#discussion_r425425821
=> [discovery] Added validation for relation between ThingUID and BridgeUID

bundles/org.openhab.core.persistence/src/main/java/org/openhab/core/persistence/FilterCriteria.java, bundles/org.openhab.core.persistence/src/test/java/org/openhab/core/persistence/extensions/TestPersistenceService.java
Also removes "Zoned" from the getters so they follow the naming of the setters.
=> Remove deprecated FilterCriteria methods

bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/internal/profiles/ProfileCallbackImpl.java
The changes in #1614 caused null analysis errors in `CommunicationManager.createCallback` and caused unnecessary null check warnings in `ProfileCallbackImpl`.
=> Fix null analysis errors/warnings

bundles/org.openhab.core.io.rest/src/main/java/org/openhab/core/io/rest/JSONResponse.java
The ResponseBuilder's `encoding(String encoding)` function sets the http header "Content-Encoding", which is used to compress the media type and not to specify the character encoding.
See [ResponseBuilderImpl](https://github.com/apache/cxf/blob/master/rt/frontend/jaxrs/src/main/java/org/apache/cxf/jaxrs/impl/ResponseBuilderImpl.java#L286):
```java
public ResponseBuilder encoding(String encoding) {
return this.setHeader("Content-Encoding", encoding);
}
```
The content-encoding header should be used to compress the media type.
See [MDN Web Docs Content-Encoding](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Encoding).
If you want to specify the charset you should use the content-type header.
See [MDN Web Docs Content-Type](https://developer.mozilla.org/en-US/docs/Web/HTTP …
=> Removes the incorrect use of the encoding header in each JSON response

bundles/org.openhab.core.config.core/src/main/java/org/openhab/core/config/core/Configuration.java, bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/UID.java, bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/util/ThingHelper.java
Removes the following deprecated methods:
* org.openhab.core.config.core.Configuration.get​(Object)
* org.openhab.core.config.core.Configuration.remove​(Object)
* org.openhab.core.thing.UID.getSegments()
* org.openhab.core.thing.util.ThingHelper.ensureUnique​(Collection<Channel>)
---
I could not find any usages of these methods by add-ons/UIs.
=> Remove deprecated methods from Configuration, UID and ThingHelper

.travis.yml
Upgrades the Travis CI build environment to Ubuntu 20.04 (Focal Fossa).
Also fixes the following Travis config validation warnings:
* deprecated key sudo (The key `sudo` has no effect anymore.)
* missing os, using the default linux
=> Upgrade Travis CI to use Ubuntu 20.04 and fix warnings

.travis.yml
There is no `$HOME/.bnd/cache` dir after a Travis build.
There is a `$HOME/.bnd/urlcache` dir, but it contains info about artifacts in `/target` dirs so it's also useless to cache.
=> Remove non-existing $HOME/.bnd/cache/ dir from .travis.yml

tools/archetype/binding/src/main/resources/archetype-resources/src/main/java/internal/__bindingIdCamelCase__Handler.java
See https://www.openhab.org/docs/developer/guidelines.html#f-logging point 4
```
void myFun() {
logger.trace("Enter myfun"); // DONT, DONT, really DONT do that
doSomething();
logger.trace("Leave myfun"); // DONT, DONT, really DONT do that
}
```
Also give an example for the logging severities, as many binding PRs log to info or error.
=> [skeleton] Make example logging compliant to Coding Guidelines

bundles/org.openhab.core/src/main/java/org/openhab/core/library/types/QuantityType.java
This makes QuantityType serialisable and thus fixes #1651
=> Make logger transient

bom/runtime/pom.xml, bom/test/pom.xml, features/karaf/openhab-tp/src/main/feature/feature.xml, itests/org.openhab.core.io.rest.core.tests/itest.bndrun
This version uses CXF 3.2.13 which has some SSE fixes (see [changelog](https://issues.apache.org/jira/secure/ReleaseNote.jspa?projectId=12310511&version=12346756)).
---
Since I gave this a test to see if it would f i x https://github.com/openhab/openhab-core/issues/1655, we might as well upgrade to use the newer version.
=> Upgrade Aries JAX-RS Whiteboard to 1.0.9

bundles/org.openhab.core.transform/src/main/java/org/openhab/core/transform/AbstractFileTransformationService.java
The path is incorrect because a bug was introduced in #1650.
This results in the MapTransformationServiceTest failing so it was disabled in openhab/openhab-addons#8519.
=> Fix transformation file path with locale specific files

bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/binding/BaseThingHandler.java, itests/org.openhab.core.model.thing.tests/src/main/java/org/openhab/core/model/thing/test/hue/GenericThingProviderTest4.java, itests/org.openhab.core.thing.tests/src/main/java/org/openhab/core/thing/internal/ThingManagerOSGiJavaTest.java, itests/org.openhab.core.thing.tests/src/main/java/org/openhab/core/thing/internal/ThingRegistryOSGiTest.java
Related to #1408, see also https://github.com/openhab/openhab-addons/pull/8553.
=> Remove deprecated BaseThingHandler.initialize()

bundles/org.openhab.core.config.core/src/main/java/org/openhab/core/config/core/ConfigOptionProvider.java, bundles/org.openhab.core.config.discovery/src/main/java/org/openhab/core/config/discovery/DiscoveryListener.java
Removes:
* ConfigOptionProvider.getParameterOptions(URI, String, Locale) (see also #1541)
* DiscoveryListener.removeOlderResults(DiscoveryService, long, Collection<ThingTypeUID>)
=> Remove deprecate default methods

bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/internal/ChannelLinkNotifier.java, itests/org.openhab.core.thing.tests/src/main/java/org/openhab/core/thing/internal/ChannelLinkNotifierOSGiTest.java
I've tested the `ChannelLinkNotifier` by @splatch (https://github.com/openhab/openhab-core/pull/1385#issuecomment-633454655) and it solves the channel linking issues for me. 
I made a few small changes:
* add `@NonNullByDefault`
* tune logging
* addRegistryChangeListener before notifying handlers to prevent events getting lost (if channels can be unlinked during this call synchronization may be necessary too)
* removeRegistryChangeListener on `@Deactivate`
With the channels being properly linked, adding Things via the inbox and adding them to the model works a lot better. :-)
Fixes #1596
=> Fix item channel links not properly initialized

bom/compile/pom.xml, bom/test/pom.xml
The add-ons still depend on JAXB 2.2 so it for instance caused the avmfritz itest to fail.
=> Exclude transitive JAXB 2.3 dependencies

bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/binding/BaseThingHandler.java, bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/binding/ThingHandler.java, bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/internal/profiles/ProfileCallbackImpl.java, bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/internal/profiles/SystemDefaultProfile.java, bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/internal/profiles/SystemOffsetProfile.java, bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/profiles/ProfileCallback.java, bundles/org.openhab.core.thing/src/test/java/org/openhab/core/thing/internal/profiles/SystemDefaultProfileTest.java, bundles/org.openhab.core.thing/src/test/java/org/openhab/core/thing/internal/profiles/SystemOffsetProfileTest.java
The `handleUpdate` method was deprecated when profiles were introduced (see eclipse-archived/smarthome#4108).
Instead the [follow profile](https://www.openhab.org/docs/developer/transformations/#followprofile) can be used which forwards item updates as commands to handlers.
This profile works with any binding instead of only those that implement the handleUpdate method.
=> Remove deprecated handleUpdate from ThingHandler

bundles/org.openhab.core.config.core/src/main/java/org/openhab/core/config/core/ConfigurableService.java, bundles/org.openhab.core.config.core/src/main/java/org/openhab/core/config/core/ConfigurableServiceUtil.java, bundles/org.openhab.core.config.core/src/test/java/org/openhab/core/config/core/ConfigurableServiceUtilTest.java, bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/internal/service/ConfigurableServiceResource.java, bundles/org.openhab.core.test.magic/src/main/java/org/openhab/core/magic/binding/internal/MagicServiceImpl.java, bundles/org.openhab.core.test.magic/src/main/java/org/openhab/core/magic/binding/internal/automation/modules/MagicMultiActionMarker.java, bundles/org.openhab.core.test.magic/src/main/java/org/openhab/core/magic/binding/internal/automation/modules/MagicSingleActionService.java, bundles/org.openhab.core.test.magic/src/main/java/org/openhab/core/magic/service/MagicMultiInstanceServiceMarker.java
The property keys are now hidden so contributors are now forced to always annotate classes with `@ConfigurableService`.
Related to https://github.com/openhab/openhab-core/issues/1408.
=> Fix ConfigurableService deprecations

bundles/org.openhab.core.io.transport.mqtt/src/main/java/org/openhab/core/io/transport/mqtt/MqttBrokerConnection.java, bundles/org.openhab.core.io.transport.mqtt/src/main/java/org/openhab/core/io/transport/mqtt/MqttBrokerConnectionConfig.java, bundles/org.openhab.core.io.transport.mqtt/src/main/java/org/openhab/core/io/transport/mqtt/MqttException.java, bundles/org.openhab.core.io.transport.mqtt/src/main/java/org/openhab/core/io/transport/mqtt/internal/MqttServiceImpl.java, bundles/org.openhab.core.io.transport.mqtt/src/test/java/org/openhab/core/io/transport/mqtt/MqttBrokerConnectionTests.java
This removes the remaining deprecated MQTT transport code which was not part of #1668.
The `retainMessages` configuration parameter in the `MqttBrokerConnectionConfig` is already unused by MQTT Broker Things (see [config description](https://github.com/openhab/openhab-addons/blob/cc042dabff6cb4bc3fabc3f3264d2e520d7cd46b/bundles/org.openhab.binding.mqtt/src/main/resources/OH-INF/thing/thing-types.xml#L11)). So keeping track of it and using it serves no purpose because the value would always be `false`.
=> Remove remaining deprecated MQTT transport code

bundles/org.openhab.core.io.rest.sitemap/src/main/java/org/openhab/core/io/rest/sitemap/SitemapSubscriptionService.java, bundles/org.openhab.core.io.rest.sitemap/src/main/java/org/openhab/core/io/rest/sitemap/internal/SitemapResource.java
* Add listener to SseBroadcaster so sseEventSinkRemoved events are handled
* Use Instant instead of long for tracking subscription creation times
* Run cleanup every 2 minutes instead of every 5 minutes
Fixes #1674
=> Fix sitemap subscription cleanup

bundles/org.openhab.core.config.core/src/main/java/org/openhab/core/config/core/internal/i18n/I18nConfigOptionsProvider.java, bundles/org.openhab.core.config.core/src/test/java/org/openhab/core/config/core/internal/i18n/I18nConfigOptionsProviderTest.java
There are many locales that do not have a country resulting in these empty parameter options.
Related to #1662
=> Filter empty i18n config parameter options

bom/compile/pom.xml, bom/runtime/pom.xml, features/karaf/openhab-tp/src/main/feature/feature.xml, itests/org.openhab.core.automation.integration.tests/itest.bndrun, itests/org.openhab.core.automation.module.core.tests/itest.bndrun, itests/org.openhab.core.automation.module.script.tests/itest.bndrun, itests/org.openhab.core.automation.module.timer.tests/itest.bndrun, itests/org.openhab.core.automation.tests/itest.bndrun, itests/org.openhab.core.ephemeris.tests/itest.bndrun, itests/org.openhab.core.ephemeris.tests/src/main/java/org/openhab/core/ephemeris/internal/EphemerisManagerImplOSGiTest.java, itests/org.openhab.core.model.core.tests/itest.bndrun, itests/org.openhab.core.model.item.tests/itest.bndrun, itests/org.openhab.core.model.rule.tests/itest.bndrun, itests/org.openhab.core.model.script.tests/itest.bndrun, itests/org.openhab.core.model.thing.tests/itest.bndrun
With some excludes and the upgraded JAXB I got the most recent Jollyday version working.
The integration tests also succeed again on Java 11.
=> Upgrade to Jollyday 0.5.10

features/karaf/openhab-core/src/main/feature/feature.xml, features/karaf/openhab-tp/src/main/feature/feature.xml
I did a fresh install of openHAB 3.0 and ended up 2 activated guava bundles. While 1 is already to much :wink: 
```
28 │ Active │  80 │ 18.0.0                  │ Guava: Google Core Libraries for Java
29 │ Active │  80 │ 27.1.0.jre              │ Guava: Google Core Libraries for Java
```
So I tracked down to this dependencies.
My only question. Shouldn't it be removed completely here actually?
=> Synced guava version with openhab-tp usages

bom/compile/pom.xml, bom/runtime/pom.xml, bundles/org.openhab.core.binding.xml/src/main/java/org/openhab/core/binding/xml/internal/BindingInfoReader.java, bundles/org.openhab.core.config.xml/src/main/java/org/openhab/core/config/xml/internal/ConfigDescriptionReader.java, bundles/org.openhab.core.config.xml/src/main/java/org/openhab/core/config/xml/util/XmlDocumentReader.java, bundles/org.openhab.core.config.xml/src/test/java/com/acme/Product.java, bundles/org.openhab.core.config.xml/src/test/java/org/openhab/core/config/xml/util/XmlDocumentReaderTest.java, features/karaf/openhab-tp/src/main/feature/feature.xml, itests/org.openhab.core.binding.xml.tests/itest.bndrun, itests/org.openhab.core.config.discovery.tests/itest.bndrun, itests/org.openhab.core.config.xml.tests/itest.bndrun, itests/org.openhab.core.ephemeris.tests/itest.bndrun, itests/org.openhab.core.model.core.tests/itest.bndrun, itests/org.openhab.core.model.item.tests/itest.bndrun, itests/org.openhab.core.model.rule.tests/itest.bndrun, itests/org.openhab.core.model.script.tests/itest.bndrun, itests/org.openhab.core.model.thing.tests/itest.bndrun, itests/org.openhab.core.thing.tests/itest.bndrun, itests/org.openhab.core.thing.xml.tests/itest.bndrun
* Fixes bugs (vulnerabilities/performance issues)
* Supports OSGi better
* Prevents illegal reflective access warnings on newer Java versions
* Supports java.time converters
For XStream release notes see: https://x-stream.github.io/changes.html
The `XmlDocumentReader` which uses XStream has also been modified to configure XStream security to prevent "Security framework of XStream not initialized, XStream is probably vulnerable" warnings.
=> Upgrade to XStream 1.4.13

bom/compile/pom.xml
It doesn't seem to be used by anything and it is also not part of the target platform.
=> Remove Jackson 1.x compile dependency

bundles/org.openhab.core.karaf/src/main/java/org/openhab/core/karaf/internal/KarafAddonService.java
Since there are no more action add-ons in the distribution, I'd suggest to remove these from the `KarafAddonService` so they won't appear in the UI menus.
=> Remove actions from available add-on types

bundles/org.openhab.core.io.rest/src/main/java/org/openhab/core/io/rest/SseBroadcaster.java
When handling an exception, the sink may already have been closed.
So don't close it again to prevent the IllegalStateException.
Fixes #1499
=> Prevent IllegalStateException when closing SSE sink

bundles/org.openhab.core.io.net/src/main/java/org/openhab/core/io/net/exec/ExecUtil.java, bundles/org.openhab.core.io.net/src/test/java/org/openhab/core/io/net/exec/ExecUtilTest.java, bundles/org.openhab.core.model.script/src/org/openhab/core/model/script/actions/Exec.java
Ever since I first read this code I've been waiting for an excuse to rewrite it.
I went ahead and got rid of the `@@` delimiter usage since it seems silly to not just take the arguments as an additional parameter.
Fixes #1677 
Signed-off-by: Connor Petty <mistercpp2000+gitsignoff@gmail.com>
=> Make ExecUtil more robust

features/karaf/openhab-core/src/main/feature/feature.xml
It seems that when multiple features install the same bundle it may cause Karaf to refresh bundles when (un)installing features.
I found the bundles which cause these refreshes by (un)installing features with the verbose (-v) option so Karaf shows what happens:
```
openhab> feature:install -v openhab-binding-mail
Adding features: openhab-binding-mail/[3.0.0.SNAPSHOT,3.0.0.SNAPSHOT]
Changes to perform:
Region: root
Bundles to install:
mvn:com.sun.mail/javax.mail/1.6.2
mvn:org.openhab.addons.bundles/org.openhab.binding.mail/3.0.0-SNAPSHOT
Stopping bundles:
org.openhab.binding.network/3.0.0.202010080341
org.openhab.core.automation.rest/3.0.0.202010080309
org.openhab.core.model.script.runtime/3.0.0.202010080314
org.openhab.core.model.rule.runtime/3.0.0.202010080314 …
```
=> Simplify core features to prevent unnecessary bundle refreshes

bundles/org.openhab.core.io.rest.auth/src/main/java/org/openhab/core/io/rest/auth/internal/JwtHelper.java
Catch specific exceptions and don't log errors but instead add an appropriate message and preserve the stacktrace.
It would for instance always log these exceptions whenever I recreate my test openHAB instance and it was using an old token:
```
[ERROR] [.core.io.rest.auth.internal.JwtHelper] - Error while processing JWT token
org.jose4j.jwt.consumer.InvalidJwtSignatureException: JWT rejected due to invalid signature. Additional details: [[9] Invalid JWS Signature: JsonWebSignature{"kid":null,"alg":"RS256"}->eyJraWQiOm51bGwsImFsZyI6I...
at org.jose4j.jwt.consumer.JwtConsumer.processContext(JwtConsumer.java:224) ~[bundleFile:?]
at org.jose4j.jwt.consumer.JwtConsumer.process(JwtConsumer.java:433) ~[bundleFile:?]
at org.jose4j.jwt.consumer.JwtConsumer.processToClaims(JwtConsumer.java:171) …
```
=> Improve JwtHelper exception handling

bundles/org.openhab.core/src/main/java/org/openhab/core/internal/i18n/I18nProviderImpl.java, bundles/org.openhab.core/src/main/java/org/openhab/core/library/unit/ImperialUnits.java, bundles/org.openhab.core/src/main/java/org/openhab/core/library/unit/SIUnits.java
Related to https://github.com/openhab/openhab-core/issues/1678#issuecomment-706775966.
Imho "US" is not really ideal as a name since it is rather "Imperial", but since this is already established and used by the UI (and Alexa), I'd think it is ok to stick to it.
=> Fixed name of measurement systems

bundles/org.openhab.core/src/main/java/org/openhab/core/items/ManagedItemProvider.java, itests/org.openhab.core.tests/src/main/java/org/openhab/core/items/ItemRegistryImplTest.java
Fixes #1706
The GroupFunctionHelper still used a lot of deprecated classes and failed creating items if started early, since it still relied on `itemFactories` instead of using the `ItemBuilderFactory`.
=> Fixed initialization of group items with aggregation functions

features/karaf/openhab-core/src/main/feature/feature.xml
This adds a missing feature required for being able to load JSR223 JavaScript rules out of the box.
See also this [community post](https://community.openhab.org/t/oh3-js-rules-gone/106581?u=wborn).
=> Fix JSR223 JavaScript files not loading

bundles/org.openhab.core.karaf/src/main/java/org/openhab/core/karaf/internal/FeatureInstaller.java, bundles/org.openhab.core.karaf/src/main/java/org/openhab/core/karaf/internal/KarafAddonService.java
This type allows for installing automation add-ons such as:
* [Groovy Scripting](https://github.com/openhab/openhab-addons/pull/8772)
* [Jython Scripting](https://github.com/openhab/openhab-addons/pull/7208)
* [JS Scripting](https://github.com/openhab/openhab-addons/pull/8516)
=> Add Automation extension type

bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/internal/thing/ThingResource.java, itests/org.openhab.core.thing.tests/src/main/java/org/openhab/core/thing/internal/ThingRegistryOSGiTest.java
- Check for valid `ThingUID` when creating a `Thing` which is related to a `Bridge`
Similar to https://github.com/openhab/openhab-core/pull/1481
My first idea was to add the check inside [ThingRegistryImpl.createThingOfType(ThingTypeUID, ThingUID, ThingUID, String, Configuration)](https://github.com/openhab/openhab-core/blob/c4b76a0ad11d5098f0f48bb3f86b0f943afc23cf/bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/internal/ThingRegistryImpl.java#L245) but I was not sure if it is the best idea to throw an IAE if the given `ThingUID` does not match as it will be API breaking. 
Maybe we should not merge it until we have a valid solution for https://github.com/openhab/openhab-webui/issues/380.
=> [REST] Added validation for relation between ThingUID and BridgeUID

bundles/org.openhab.core/src/main/java/org/openhab/core/common/registry/AbstractRegistry.java, bundles/org.openhab.core/src/test/java/org/openhab/core/internal/items/MetadataCommandDescriptionProviderTest.java, bundles/org.openhab.core/src/test/java/org/openhab/core/internal/items/MetadataRegistryImplTest.java, bundles/org.openhab.core/src/test/java/org/openhab/core/internal/items/MetadataStateDescriptionFragmentProviderTest.java, itests/org.openhab.core.thing.tests/src/main/java/org/openhab/core/thing/link/ItemChannelLinkOSGiTest.java
Based on the fix in https://github.com/openhab/openhab-core/issues/890#issuecomment-611920483 which seems to work nicely!
This issue seems to have been introduced by the use of constructor injection to prevent null values.
Because of the abstract nature of the `AbstractRegistry`, it cannot inject providers using a `@Reference` MULTIPLE/DYNAMIC annotated method. So instead it has to open a `ServiceTracker` in the activate method to keep track of all available providers. If it were able to use a `@Reference` annotated method the providers would also have been populated asynchronously and there would be no cycle.
Other ways to break the cycle would be to not inject the `ItemRegistry` in the `SemanticsMetadataProvider` constructor but to use a `@Reference` annotated method for this instead. …
=> Open ProviderTracker asynchronously when activating AbstractRegistry

bundles/org.openhab.core.test.magic/src/main/java/org/openhab/core/magic/binding/internal/MagicServiceImpl.java, bundles/org.openhab.core.ui/src/main/java/org/openhab/core/ui/internal/chart/ChartServlet.java, bundles/org.openhab.core/src/main/java/org/openhab/core/net/NetUtil.java, features/karaf/openhab-core/src/main/feature/feature.xml
* Fixes warnings about "using different service PIDs"
* Fixes missing default values
---
These warnings would show up:
```
[WARN ] [.service.ConfigurableServiceResource] - The component "org.openhab.core.net.NetUtil" is using different service PIDs ([org.openhab.core.network, org.openhab.network]). Different service PIDs are not supported, the first one (org.openhab.core.network) is used.
[WARN ] [.service.ConfigurableServiceResource] - The component "org.openhab.core.ui.internal.chart.ChartServlet" is using different service PIDs ([org.openhab.core.chart, org.openhab.chart]). Different service PIDs are not supported, the first one (org.openhab.core.chart) is used.
```
=> Fix issues with configuration PIDs

bundles/org.openhab.core.io.rest.auth/src/main/java/org/openhab/core/io/rest/auth/internal/AnonymousUserSecurityContext.java, bundles/org.openhab.core.io.rest.auth/src/main/java/org/openhab/core/io/rest/auth/internal/AuthFilter.java, bundles/org.openhab.core.io.rest.auth/src/main/java/org/openhab/core/io/rest/auth/internal/RolesAllowedDynamicFeatureImpl.java, bundles/org.openhab.core.io.rest.auth/src/main/java/org/openhab/core/io/rest/auth/internal/UserSecurityContext.java, bundles/org.openhab.core.io.rest.auth/src/main/resources/OH-INF/config/config.xml
Closes #1699.
Note, this opens a minor security issue that allows an attacker
to brute force passwords by making calls to the API - contrary to
the authorization page, the credentials parsing for the REST API
is stateless & doesn't have a lock mechanism to lock user accounts
after too many failed login attempts.
=> Allow basic authentication to authorize API access

bundles/org.openhab.core.io.rest.auth/src/main/resources/OH-INF/config/config.xml
=> Fix build by wrapping lines

bundles/org.openhab.core.persistence/src/main/java/org/openhab/core/persistence/internal/PersistenceManagerImpl.java
After enabling debug logging, I ran into this exception due to ZonedDateTime being used with persistence instead of of Date objects:
```
[ERROR] [org.openhab.core.persistence         ] - bundle org.openhab.core.persistence:3.0.0.202010180300 (184)[org.openhab.core.persistence.internal.PersistenceManagerImpl(202)] : The addPersistenceService method has thrown an exception
java.lang.IllegalArgumentException: Cannot format given Object as a Date
at java.text.DateFormat.format(DateFormat.java:338) ~[?:?]
at java.text.Format.format(Format.java:158) ~[?:?]
at org.openhab.core.persistence.internal.PersistenceManagerImpl.initialize(PersistenceManagerImpl.java:295) ~[?:?]
at org.openhab.core.persistence.internal.PersistenceManagerImpl.startEventHandling(PersistenceManagerImpl.java:406) ~[?:?]
at …
```
=> Fix IAE when enabling debug logging on PersistenceManagerImpl

bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/internal/profile/ProfileTypeResource.java, bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/internal/thing/ThingTypeResource.java, bundles/org.openhab.core.io.rest.sse/src/main/java/org/openhab/core/io/rest/sse/SseResource.java
(I included these fixes in #1735 but extracted them in a stanalone
PR because it's easier to review and a little more urgent.)
As a result of the refactoring in #1713, the operations annotated with
`@RolesAllowed` containing `Role.USER` are not anymore automatically
considered accessible to all users, regardless of their actual roles.
4 operations are therefore now denied to admins if they only have the
`Role.ADMIN` role, as the first admininistrator is created only with
that role the UI encounters unexpected access denied errors and breaks.
(See https://github.com/openhab/openhab-webui/issues/422).
Closes https://github.com/openhab/openhab-webui/issues/422.
=> Add missing roles checks

bundles/org.openhab.core.automation.module.script/src/main/java/org/openhab/core/automation/module/script/internal/handler/AbstractScriptModuleHandler.java, bundles/org.openhab.core.automation.module.script/src/main/java/org/openhab/core/automation/module/script/internal/handler/ScriptActionHandler.java
* Add rule UID to error message
* Add exception with stacktrace when debug level is enabled
Related to #1734
---
Example without debug logging enabled:
```
[ERROR] [.internal.handler.ScriptActionHandler] - Script execution of rule with UID 'demo-10' failed: The name 'Wifi_Levell' cannot be resolved to an item or type; line 128, column 16, length 11 in demo
```
Example with debug logging enabled:
```
[ERROR] [.internal.handler.ScriptActionHandler] - Script execution of rule with UID 'demo-10' failed: The name 'Wifi_Levell' cannot be resolved to an item or type; line 128, column 16, length 11 in demo
javax.script.ScriptException: The name 'Wifi_Levell' cannot be resolved to an item or type; line 128, column 16, length 11 in demo
at …
```
=> Improve rule debugging

bundles/org.openhab.core.ui/src/main/java/org/openhab/core/ui/internal/items/ItemUIRegistryImpl.java, bundles/org.openhab.core.ui/src/test/java/org/openhab/core/ui/internal/items/ItemUIRegistryImplTest.java
- Added unit test for read-only Number- and String-Items to not return a Selection Element
Related to #1751
=> [ui] Added unit test for read-only Number- and String-Items to not return a Selection Element

bundles/org.openhab.core.io.net/src/main/java/org/openhab/core/io/net/http/TrustAllTrustManager.java
Will require changes in a couple addons as well.
=> Fixed typo in class name TrustAllTrustMananger.

bundles/org.openhab.core/src/main/java/org/openhab/core/library/items/StringItem.java, bundles/org.openhab.core/src/main/java/org/openhab/core/types/TypeParser.java, bundles/org.openhab.core/src/test/java/org/openhab/core/types/TypeParserTest.java
- Revert ordering of accepted data types for `StringItem`
See https://github.com/openhab/openhab-core/pull/1755 and https://github.com/openhab/openhab-addons/issues/8880#issuecomment-718200422
I tried to move `DateTimeType` too but this probably will result in more conflicts because it now can parse Unix timestamp and every positive integer will be parsed as `DateTimeType`.
=> [core] Revert ordering of accepted data types for 'StringItem'

bundles/org.openhab.core/src/main/java/org/openhab/core/common/registry/AbstractRegistry.java
- Fixed provider comparison as the variable `managedProvider` is of type `Optional<ManagedProvider<E, K>>`
Related to #1506
=> Fixed provider comparison while unsetting 

bundles/org.openhab.core.automation.module.script/src/main/java/org/openhab/core/automation/module/script/internal/ScriptEngineManagerImpl.java, bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/RuleEngineImpl.java, bundles/org.openhab.core.config.discovery.mdns/src/main/java/org/openhab/core/config/discovery/mdns/internal/MDNSDiscoveryService.java, bundles/org.openhab.core.config.discovery.usbserial/src/main/java/org/openhab/core/config/discovery/usbserial/internal/UsbSerialDiscoveryService.java, bundles/org.openhab.core.config.discovery/src/main/java/org/openhab/core/config/discovery/AbstractDiscoveryService.java, bundles/org.openhab.core.config.discovery/src/main/java/org/openhab/core/config/discovery/internal/AutomaticInboxProcessor.java, bundles/org.openhab.core.io.rest.auth/src/main/java/org/openhab/core/io/rest/auth/internal/AuthFilter.java, bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/DefaultSystemChannelTypeProvider.java, bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/binding/BaseDynamicCommandDescriptionProvider.java, bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/binding/BaseDynamicStateDescriptionProvider.java, bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/binding/BaseThingHandlerFactory.java, bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/internal/AutoUpdateManager.java, bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/internal/CommunicationManager.java, bundles/org.openhab.core/src/main/java/org/openhab/core/internal/common/SafeCallManagerImpl.java, bundles/org.openhab.core/src/main/java/org/openhab/core/service/WatchQueueReader.java
These workarounds to prevent false positives can be removed now the EEAs allow for proper null analysis.
Depends on #1775
=> Remove Map null annotation workarounds

bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/provider/AbstractResourceBundleProvider.java, bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/provider/RuleResourceBundleImporter.java, bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/provider/Vendor.java
-  Added NPE checks for result of `getSymbolicName()` methods
We are using the same fallback in other places:
https://github.com/openhab/openhab-core/blob/61e17ce39e83daa7f1d8c41512dead8d95d6e5d9/bundles/org.openhab.core/src/main/java/org/openhab/core/service/ReadyMarkerUtils.java#L39
=> [automation] Added NPE checks for result of 'getSymbolicName()' methods

bundles/org.openhab.core.persistence/src/main/java/org/openhab/core/persistence/PersistenceServiceRegistry.java, bundles/org.openhab.core.persistence/src/main/java/org/openhab/core/persistence/extensions/PersistenceExtensions.java, bundles/org.openhab.core.persistence/src/test/java/org/openhab/core/persistence/extensions/PersistenceExtensionsTest.java, bundles/org.openhab.core.persistence/src/test/java/org/openhab/core/persistence/extensions/TestPersistenceService.java
- Allow max, min and avg calculations on other types (e.g. `OnOffType`) which can be converted to `DecimalType`
Why I am thinking this is useful: Imagine you want to calculate the time someone is at home (or a light bulb was on). You are already using a [Generic Presence Detection](https://community.openhab.org/t/generic-presence-detection/17878) based on a master presence Switch - which state has to be persisted. It represents whether someone is at home or not. Currently it is very difficult to calculate the exact time of how long someone is present. By this feature you are able to calculate the average state of your Switch in a certain amount of time. The resulting value will be limited from [0...1] (0 = `OFF`, 1 = `ON`) and represents the percentage of of how long the Switch was `ON`. …
=> [persistence] Allow max, min and avg calculations on other types

bundles/org.openhab.core.model.script.runtime/src/org/openhab/core/model/script/runtime/internal/engine/DSLScriptEngine.java
Fixes https://github.com/openhab/openhab-core/issues/1802
=> [automation] Correctly map the state context variable of the ItemStateEvent to the implicit var newState

bundles/org.openhab.core.automation.module.script/src/main/java/org/openhab/core/automation/module/script/internal/NashornScriptEngineFactory.java
This should fix the issue reported here:
https://community.openhab.org/t/openhab-3-0-milestone-2-discussion/107564/8
where the Nashorn script engine would be created with the
current thread's class loader, causing JS code like this:
```
var Log = Java.type("org.openhab.core.model.script.actions.Log");
Log.logError("Experiments", "This is an OH error log");
Log.logWarn("Experiments", "This is an OH warn log");
Log.logInfo("Experiments", "This is an OH info log");
Log.logDebug("Experiments", "This is an OH debug log");
```
to run fine when the rule was triggered but fail to find the Log
class when run from the REST API's `/rest/rules/{ruleUID}/runnow`,
because in that case the generic createScriptEngine implementation
would return script engines using the JAX-RS class loader as the
"app" …
=> [automation] Create Nashorn script engines with the proper class loader

bundles/org.openhab.core.model.item/src/org/openhab/core/model/item/internal/GenericItemProvider.java, bundles/org.openhab.core/src/main/java/org/openhab/core/events/AbstractEvent.java, bundles/org.openhab.core/src/main/java/org/openhab/core/internal/items/ExpireManager.java, bundles/org.openhab.core/src/test/java/org/openhab/core/internal/items/ExpireManagerTest.java
This adds the functionality to let item states expire after a configuration duration as a core feature.
It follows the same syntax as it was defined by the 1.x expire binding, so that this feature is fully backward compatible.
The configurations are done as item metadata with the namespace `expire`.
Implements https://github.com/openhab/openhab-core/issues/1620
=> Added expire functionality as core framework feature

bundles/org.openhab.core.automation.module.script/src/main/java/org/openhab/core/automation/module/script/ScriptEngineFactory.java, bundles/org.openhab.core.automation.module.script/src/main/java/org/openhab/core/automation/module/script/internal/ScriptEngineManagerImpl.java
Pass explicit script context to script engines. Context initially includes only engine identifier.
=> [automation] Pass script context to script engines

bundles/org.openhab.core/src/main/java/org/openhab/core/items/ManagedItemProvider.java, itests/org.openhab.core.tests/src/main/java/org/openhab/core/items/ManagedItemProviderOSGiTest.java
Remove the groupname from the members if the group item is removed. 
This is implemented in the ManagedItemProvider. 
Fixes #1785 
Fixes #1392
=> Remove the groupname from the members if the group item is removed

itests/org.openhab.core.binding.xml.tests/src/main/resources/test-bundle-pool/BundleInfoTest.bundle/OH-INF/binding/binding.xml, itests/org.openhab.core.binding.xml.tests/src/main/resources/test-bundle-pool/yahooweather.bundle/OH-INF/binding/binding.xml, itests/org.openhab.core.thing.xml.tests/src/main/resources/test-bundle-pool/SystemChannels.bundle/OH-INF/binding/binding.xml, itests/org.openhab.core.thing.xml.tests/src/main/resources/test-bundle-pool/SystemChannelsInChannelGroups.bundle/OH-INF/binding/binding.xml, itests/org.openhab.core.thing.xml.tests/src/main/resources/test-bundle-pool/SystemChannelsNoThingTypes.bundle/OH-INF/binding/binding.xml, itests/org.openhab.core.thing.xml.tests/src/main/resources/test-bundle-pool/SystemChannelsUser.bundle/OH-INF/binding/binding.xml, tools/archetype/binding/src/main/resources/archetype-resources/src/main/resources/OH-INF/binding/binding.xml
This was discussed a long time ago and was planned for the start of openHAB 3 already - it fell of my plate somehow.
In short: Having a single author listed in this file does not make much sense for multiple reasons:
- Bindings in the official repo are considered to be part of the openHAB project and not by an individual.
- Many bindings have different contributors over the course of time, which isn't reflected here either.
- The attribution of contributors is done within the source code.
- We don't have this info for other types of add-on either.
- Naming an author makes sense for marketplace entries, but for those we will anyhow have other metadata files.
- The original purpose of this field was to give companies a possibility to "officially claim" a binding to be implemented and …
=> removed deprecated author information from bindings

bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/internal/thing/ThingResource.java
I can't think of a good reason why listing things or querying their status should be allowed for users.
The things layer should only be of concern to admins IMHO.
As noted here: https://community.openhab.org/t/oh3-will-list-all-your-things-even-if-you-are-not-logged-in/108006/3
passwords and other sensible information in configuration could end up being exposed without auth required.
=> [REST Auth] Remove user access to things

bundles/org.openhab.core.config.discovery/src/main/java/org/openhab/core/config/discovery/inbox/Inbox.java, bundles/org.openhab.core.config.discovery/src/main/java/org/openhab/core/config/discovery/internal/AutomaticInboxProcessor.java, bundles/org.openhab.core.config.discovery/src/main/java/org/openhab/core/config/discovery/internal/PersistentInbox.java, bundles/org.openhab.core.config.discovery/src/main/java/org/openhab/core/config/discovery/internal/console/InboxConsoleCommandExtension.java, bundles/org.openhab.core.config.discovery/src/test/java/org/openhab/core/config/discovery/internal/PersistentInboxTest.java, bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/internal/discovery/InboxResource.java, itests/org.openhab.core.config.discovery.tests/src/main/java/org/openhab/core/config/discovery/internal/InboxOSGiTest.java, itests/org.openhab.core.io.rest.core.tests/src/main/java/org/openhab/core/io/rest/core/internal/discovery/InboxResourceOSGITest.java
Fix #1783
This change does not break the current API, it just adds an additional parameter that could be used with REST API v4.
=> [inbox REST API] Added new optional parameter newThingId to approve

bom/compile/pom.xml
There is not really a reason from preventing bindings to use Jetty 9.4 features and I agree with @kgoderis that having them divert can cause confusion and problems.
Fixes https://github.com/openhab/openhab-core/issues/1275
=> sync Jetty versions between compile and runtime

bundles/org.openhab.core.model.rule.runtime/src/org/openhab/core/model/rule/runtime/internal/DSLRuleProvider.java
Fixes https://github.com/openhab/openhab-core/issues/1801
=> Prevent NPE on shutdown by making maps in DSLRuleProvider thread safe

bundles/org.openhab.core/src/main/java/org/openhab/core/internal/events/EventHandler.java
=> Adapted event handler thread names to naming convention

bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/TriggerHandlerCallbackImpl.java
This is necessary since the RulesRefresher uses the same pool and needs to be able to schedule jobs.
Fixes https://github.com/openhab/openhab-core/issues/1867
=> [automation] Request automation thread pool as a scheduled pool

bundles/org.openhab.core.model.thing/src/org/openhab/core/model/thing/internal/GenericItemChannelLinkProvider.java
This fixes the following problem:
* Description: Null type mismatch (type annotations): required '@NonNull Collection<?>' but this expression has type '@Nullable Set<@NonNull String>'	
* Resource: GenericItemChannelLinkProvider.java
* Path: /org.openhab.core.model.thing/src/org/openhab/core/model/thing/internal
* Location: line 133
* Type: Java Problem
=> fix null type in model.thing generic item channel link provider

bundles/org.openhab.core.model.thing/src/org/openhab/core/model/thing/internal/GenericThingProvider.xtend
This fixes the following problem:
* Description: Null type mismatch (type annotations): required '@NonNull URI' but this expression has type '@Nullable URI'
* Resource: GenericThingProvider.java
* Path: /org.openhab.core.model.thing/xtend-gen/org/openhab/core/model/thing/internal
* Location: line 617
* Type: Java Problem
=> fix null type mismatch in model.thing generic thing provider

bundles/org.openhab.core.model.thing/src/org/openhab/core/model/thing/internal/AbstractProviderLazyNullness.java, bundles/org.openhab.core.model.thing/src/org/openhab/core/model/thing/internal/GenericThingProvider.xtend
This fixes the following problem:
* Description: Null constraint mismatch: The type 'Thing' is not a valid substitute for the type parameter '@NonNull E extends Object'
* Resource: GenericThingProvider.java
* Path: /org.openhab.core.model.thing/xtend-gen/org/openhab/core/model/thing/internal
* Location: line 99
* Type: Java Problem
=> fix null constraint mismatch in model.thing for generic thing provider

bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/internal/AutoUpdateManager.java, bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/link/AbstractLinkRegistry.java, bundles/org.openhab.core.thing/src/test/java/org/openhab/core/thing/internal/AutoUpdateManagerTest.java
- Get only relevant Links of an Item instead of all by querying the `AbstractLinkRegistry` which holds a `itemNameToLink`
=> [autoupdatemanager] Get only relevant Links of an Item instead of all

bundles/org.openhab.core.model.rule/src/org/openhab/core/model/rule/jvmmodel/RulesJvmModelInferrer.xtend, bundles/org.openhab.core.model.script.runtime/src/org/openhab/core/model/script/runtime/internal/engine/DSLScriptEngine.java, bundles/org.openhab.core.model.script/src/org/openhab/core/model/script/jvmmodel/ScriptJvmModelInferrer.xtend, bundles/org.openhab.core/src/main/java/org/openhab/core/items/events/GroupItemStateChangedEvent.java, bundles/org.openhab.core/src/main/java/org/openhab/core/items/events/ItemCommandEvent.java, bundles/org.openhab.core/src/main/java/org/openhab/core/items/events/ItemEvent.java, bundles/org.openhab.core/src/main/java/org/openhab/core/items/events/ItemEventFactory.java, bundles/org.openhab.core/src/main/java/org/openhab/core/items/events/ItemStateChangedEvent.java, bundles/org.openhab.core/src/main/java/org/openhab/core/items/events/ItemStateEvent.java, bundles/org.openhab.core/src/main/java/org/openhab/core/items/events/ItemStatePredictedEvent.java
~~I have created this PR for discussion wrt whether we should merge it or not.~~
It addressed #1768, but as mentioned in that issue, it isn't easily feasible to provide the item itself, but rather only the item name.
My assumption is that this should be ok for most rules as it is really the item name that the user is after, but it nonetheless means a(nother) breaking change.
Fixes #1768
=> [automation] Provide triggering item name in the rule context

bundles/org.openhab.core.automation.module.media/src/main/java/org/openhab/core/automation/module/media/internal/MediaActionTypeProvider.java, bundles/org.openhab.core.automation.module.media/src/main/java/org/openhab/core/automation/module/media/internal/MediaModuleHandlerFactory.java, bundles/org.openhab.core.automation.module.media/src/main/java/org/openhab/core/automation/module/media/internal/PlayActionHandler.java, bundles/org.openhab.core.automation.module.media/src/main/java/org/openhab/core/automation/module/media/internal/SayActionHandler.java
- Added Actions for Play and Say which sets the volume
=> [automation] Added Actions for Play and Say which sets the volume

bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/internal/CommunicationManager.java
- Register `CommunicationManager` to listen on `ItemChannelLink` changes
We missed it in #1487.
Fixes #1645
=> Register CommunicationManager to listen on ItemChannelLink changes

bundles/org.openhab.core.test.magic/src/main/resources/OH-INF/thing/channel-types.xml, bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/DefaultSystemChannelTypeProvider.java, bundles/org.openhab.core.ui.icon/src/main/java/org/openhab/core/ui/icon/AbstractResourceIconProvider.java, itests/org.openhab.core.thing.tests/src/main/java/org/openhab/core/thing/internal/ChannelStateDescriptionProviderOSGiTest.java
- Removed references to not existing category "DimmableLight"
Has been removed in https://github.com/eclipse-archived/smarthome/pull/4298
=> [icon] Removed references to not existing category "DimmableLight"

bundles/org.openhab.core.config.core/src/main/java/org/openhab/core/config/core/ConfigDescriptionParameterGroup.java, bundles/org.openhab.core.thing.xml/src/main/java/org/openhab/core/thing/xml/internal/ChannelTypeConverter.java, bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/Channel.java, bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/binding/builder/ChannelBuilder.java, bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/i18n/ChannelTypeI18nLocalizationService.java, bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/internal/type/StateChannelTypeBuilderImpl.java, bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/internal/type/TriggerChannelTypeBuilderImpl.java, bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/type/ChannelType.java, bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/type/StateChannelTypeBuilder.java, bundles/org.openhab.core.thing/src/test/java/org/openhab/core/thing/type/ChannelTypeBuilderTest.java, itests/org.openhab.core.thing.tests/src/main/java/org/openhab/core/thing/internal/ChannelStateDescriptionProviderOSGiTest.java
Fixes #1408
---
Some builders are in different packages as the types they build. So for those I've removed the public constructors by creating some sub-classes that call a protected constructor. That will hopefully make contributors use the builders.  In newer Java versions you can also limit which classes are allowed to subclass a certain type.
=> Fix remaining deprecations

bundles/org.openhab.core.io.http.auth/src/main/resources/messages_de.properties, bundles/org.openhab.core.io.http.auth/src/main/resources/messages_it.properties, bundles/org.openhab.core.io.http.auth/src/main/resources/messages_nl.properties
This is the PR with the messages.properties files in Dutch, German (partial) & Italian extracted from #1929 and converted to the proper ISO-8859 encoding (note the Umlaut below):
=> Translated messages for auth pages

bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/internal/thing/ThingResource.java
The "summary" mode for `/rest/things` introduced in https://github.com/openhab/openhab-core/pull/1827
leads to these warnings in the console about `firmwareStatus`:
```
Field 'firmwareStatus' could not be eliminated: Can not set final org.openhab.core.thing.firmware.dto.FirmwareStatusDTO field org.openhab.core.io.rest.core.thing.EnrichedThingDTO.firmwareStatus to null value
```
The easiest solution to remove those warnings is to add it again to the list of fields included in the summaries.
=> [REST] Add firmwareStatus to things in summary mode

bundles/org.openhab.core.persistence/src/main/java/org/openhab/core/persistence/extensions/PersistenceExtensions.java
- Use `getStateAs()` or `as()` instead of type casting
As we now allow the persistence services to return `QuantityType` values we should be a little bit more careful with type casting and rather use framework provided methods.
See https://community.openhab.org/t/openhab3-rule-with-quantitytype-items/110284
=> [persistence] Use 'getStateAs()' instead of type casting

bundles/org.openhab.core/src/main/java/org/openhab/core/service/StartLevelService.java
Fixes https://github.com/openhab/openhab-core/issues/1937
=> Fixed first startup: Let StartLevelService only start once its configuration is available

bundles/org.openhab.core.model.rule/bnd.bnd, bundles/org.openhab.core.model.script/bnd.bnd, bundles/org.openhab.core.model.script/src/org/openhab/core/model/script/scoping/ScriptImportSectionNamespaceScopeProvider.java, itests/org.openhab.core.model.script.tests/src/main/java/org/openhab/core/model/script/engine/ScriptEngineOSGiTest.java
Fixes https://github.com/openhab/openhab-core/issues/1763
=> [automation] Make quantity types available in scripts

bundles/org.openhab.core.automation.module.script/src/main/java/org/openhab/core/automation/module/script/internal/handler/ScriptConditionHandler.java
- Fixed NPE by not calling `toString()` on parameters passed to a logger
Related to #1946 
=> [automation] Fixed NPE by not calling 'toString()' on parameters passed to a logger

bundles/org.openhab.core.model.script.runtime/src/org/openhab/core/model/script/runtime/internal/engine/DSLScriptEngine.java
Fixes https://github.com/openhab/openhab-core/issues/1946
=> [automation] Correctly return the evaluation result of DSL scripts

bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/module/provider/AnnotationActionModuleTypeHelper.java
- Temporarily hide Binding action in UIs
This PR will temporarily hide all Binding ThingActions in UIs. Please do not merge if you do not agree on this temporarily solution.
Related to #1745
=> [automation] Temporarily hide Binding ThingActions in UIs

bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/RuleEngineImpl.java
The `SystemTriggerHandler` ignores start level 50 as it assumes that the rule engine itself runs those rules - this fix makes sure that this is really the case.
=> [automation] Correctly trigger rules with start level 50 trigger

bundles/org.openhab.core.io.rest/src/main/java/org/openhab/core/io/rest/internal/filter/CorsFilter.java, bundles/org.openhab.core.io.rest/src/test/java/org/openhab/core/io/rest/internal/filter/CorsFilterTest.java
Due to the introduction of the oAuth authorization layer, the CORS filter for preflight requests needs to be adapted. Currently, pre flight requests with an authorization header are rejected by the API. 
This pull request corrects this behaviour by adding the value "Authorization" to the "Access-Control-Allow-Headers“.
@kaikreuzer: If it's not too late, this fix might be interesting for the stable release.
=> Fix CORS header to allow preflight requests with authorization payload

bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/internal/ThingManagerImpl.java
Fixes https://github.com/openhab/openhab-core/issues/1967
@openhab/core-maintainers I consider that as a rather critical bug that should be merged for 3.0.
=> Do not consider disabled things for start level 80

bundles/org.openhab.core.io.http.auth/src/main/java/org/openhab/core/io/http/auth/internal/CreateAPITokenPageServlet.java, bundles/org.openhab.core.io.http.auth/src/main/resources/messages_no.properties
Fixes https://github.com/openhab/openhab-webui/issues/674.
Remove unnecessary checks and fix exception message.
Add Norwegian messages for auth pages.
=> [auth] Don't allow creating API tokens with no name

bundles/org.openhab.core.model.script/src/org/openhab/core/model/script/engine/ScriptError.java
- Fixed NPE in `ScriptError` if `INode` is empty
This will at lest show the message without referencing line and column.
See https://community.openhab.org/t/openhab-3-0-release-discussion/110751/16
=> Fixed NPE in ScriptError if INode is empty

bundles/org.openhab.core.ui/src/main/java/org/openhab/core/ui/internal/chart/ChartServlet.java
- Harden ChartServlet against NPEs when no 'period' parameter is given
See https://community.openhab.org/t/oh3-chart-nullpointerexception-when-accessing-http-openhabserver-port-chart/110974
=> [chart] Harden ChartServlet against NPEs when no 'period' parameter is given

bundles/org.openhab.core/src/main/java/org/openhab/core/internal/types/StateDescriptionFragmentImpl.java, bundles/org.openhab.core/src/main/java/org/openhab/core/types/StateDescription.java
I forgot to hide this constructor in https://github.com/openhab/openhab-core/pull/1918!
The add-ons were already updated for this.
=> Hide StateDescription constructor

bundles/org.openhab.core.model.rule.runtime/src/org/openhab/core/model/rule/runtime/internal/DSLRuleProvider.java
I migrated from openhab 2.x to 3.x and many of my rules managed in `.rules` dsl files where not shown in the UI. I found that the uid of the rules only contained the string before ".".  Examples of my rule filenames: `Bedroom.TV.rules`, `Bedroom.Light.rules`
This resulted in a collision of uids for the rules. With openhab 2.x this was not a problem.
To fix this problem, the full filename without extension should be used in the uid for rules provided by DSL files.
=> Updated rule dsl filename to rule uid mapping

bundles/org.openhab.core.model.script/src/org/openhab/core/model/script/actions/ScriptExecution.java
Fixes https://github.com/openhab/openhab-core/issues/1990
=> Correctly handle file extension when looking up script

bundles/org.openhab.core.persistence/src/main/java/org/openhab/core/persistence/extensions/PersistenceExtensions.java, bundles/org.openhab.core.persistence/src/test/java/org/openhab/core/persistence/extensions/PersistenceExtensionsTest.java
Fixed `varianceSince` and `deviationSince`, which always returned null. Also enabled tests for `varianceSince` and `deviationSince`, which were not being executed (and therefore masking that those functions didn't work).
Signed-off-by: Mark Hilbush <mark@hilbush.com>
=> [Persistence Extensions] Fixed varianceSince and deviationSince

bundles/org.openhab.core.model.script.runtime/src/org/openhab/core/model/script/runtime/internal/engine/DSLScriptEngine.java
Since we have a dedicated DSLScriptEngine instance per rule script action, we can easily cache the parsed script.
Parsing seems to cause significant CPU and memory usage - with this PR, there is no noticeable CPU activity anymore and also the heap size does not increase over time anymore.
Fixes https://github.com/openhab/openhab-core/issues/1877
Fixes https://github.com/openhab/openhab-core/issues/2031
=> [automation] Cache parsed script in order to improve performance

bundles/org.openhab.core.ui/src/main/java/org/openhab/core/ui/internal/components/UIComponentSitemapProvider.java
Also catch remaining exceptions and log a warning/ignore the parameter
instead of making the whole sitemap building process fail.
Fix wrong feature ID for the video widget URL.
Fixes #2047.
Fixes #2005.
Fixes #1987.
Fixes #1898.
Fixes #1875.
Fixes https://github.com/openhab/openhab-webui/issues/745.
=> Fix parsing integer & booleans parameters in UI component based sitemaps

bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/DefaultSystemChannelTypeProvider.java
- Add category for system channel type 'power'
- Changed category for system channel type 'low-battery'
=> Add category for system channel type 'power'

bundles/org.openhab.core/src/main/java/org/openhab/core/common/ThreadPoolManager.java
This PR adds a new getPoolNames method to ThreadPoolManager in order to iterate over all thread pools. The intention is to extract metrics for a new [Prometheus](https://prometheus.io/) exporter binding I've got in the works. 
Signed-off-by: Robert Bach <openhab@mortalsilence.net> (github: pravussum)
=> add getPoolNames method to ThreadPoolManager

bundles/org.openhab.core.io.transport.serial.javacomm/src/main/java/org/openhab/core/io/transport/serial/internal/SerialPortImpl.java, bundles/org.openhab.core.io.transport.serial.rxtx/src/main/java/org/openhab/core/io/transport/serial/rxtx/RxTxSerialPort.java, bundles/org.openhab.core.io.transport.serial/src/main/java/org/openhab/core/io/transport/serial/SerialPort.java
Serial port interface is extended by non implemented methods
Fixes #2048 
Signed-off-by: Vita Tucek
=> Extended serial port implementation

bundles/org.openhab.core.model.rule.runtime/src/org/openhab/core/model/rule/runtime/internal/DSLRuleProvider.java
=> [automation] Avoid disappearing rules by correctly checking the model and its type

bundles/org.openhab.core.automation.rest/src/main/java/org/openhab/core/automation/rest/internal/RuleResource.java
I stumbled upon the same issue as described here:
https://community.openhab.org/t/solved-oh3-issue-unable-to-create-rules-scripts-schedules/111325
https://community.openhab.org/t/openhab-3-error-creating-rules-or-scripts-using-blocky/111422
This makes the logging a bit more useful
=> Improved error logging when adding rules

bundles/org.openhab.core.persistence/src/test/java/org/openhab/core/persistence/extensions/PersistenceExtensionsTest.java, bundles/org.openhab.core.persistence/src/test/java/org/openhab/core/persistence/extensions/TestPersistenceService.java
- Added unit tests for check if persistence extension returns `QuantityType` if persistence service returns `QuantityType`
This PR adds support for unit tests returning `QuantityType` values and splits test for `historicState()`, `previousState()`, `maximumSince()` and `minimumSince()` to validate to already work like expected.
Related to #1954 
=> Added unit tests for check if persistence extension returns QuantityType if persistence service returns QuantityType

bundles/org.openhab.core.io.net/src/main/java/org/openhab/core/io/net/exec/ExecUtil.java
Fixes https://github.com/openhab/openhab-core/issues/2033
Fixes #2078 
=> Also return command line execution result in case of error return code

bom/runtime/pom.xml, bom/test-index/pom.xml, itests/org.openhab.core.auth.oauth2client.tests/itest.bndrun, itests/org.openhab.core.automation.integration.tests/itest.bndrun, itests/org.openhab.core.automation.module.core.tests/itest.bndrun, itests/org.openhab.core.automation.module.script.tests/itest.bndrun, itests/org.openhab.core.automation.module.timer.tests/itest.bndrun, itests/org.openhab.core.automation.tests/itest.bndrun, itests/org.openhab.core.binding.xml.tests/itest.bndrun, itests/org.openhab.core.config.core.tests/itest.bndrun, itests/org.openhab.core.config.discovery.mdns.tests/itest.bndrun, itests/org.openhab.core.config.discovery.tests/itest.bndrun, itests/org.openhab.core.config.discovery.usbserial.linuxsysfs.tests/itest.bndrun, itests/org.openhab.core.config.discovery.usbserial.tests/itest.bndrun, itests/org.openhab.core.config.dispatch.tests/itest.bndrun, itests/org.openhab.core.config.xml.tests/itest.bndrun, itests/org.openhab.core.ephemeris.tests/itest.bndrun, itests/org.openhab.core.io.rest.core.tests/itest.bndrun, itests/org.openhab.core.model.core.tests/itest.bndrun, itests/org.openhab.core.model.item.tests/itest.bndrun, itests/org.openhab.core.model.rule.tests/itest.bndrun, itests/org.openhab.core.model.script.tests/itest.bndrun, itests/org.openhab.core.model.thing.tests/itest.bndrun, itests/org.openhab.core.storage.json.tests/itest.bndrun, itests/org.openhab.core.tests/itest.bndrun, itests/org.openhab.core.thing.tests/itest.bndrun, itests/org.openhab.core.thing.xml.tests/itest.bndrun, itests/org.openhab.core.voice.tests/itest.bndrun
* Sync biz.aQute.tester.junit-platform version using bnd.version property
* Remove duplicate osgi-resource-locator dependency, causing warnings/unstability
=> Fix BOM dependency issues

bundles/org.openhab.core.io.net/src/main/java/org/openhab/core/io/net/exec/ExecUtil.java, bundles/org.openhab.core.io.net/src/test/java/org/openhab/core/io/net/exec/ExecUtilTest.java
NOTE: this relates to Issue https://github.com/openhab/openhab-core/issues/2033#issuecomment-759781893
If ErrorCode == 0 then executeCommandLineAndWaitResponse() would always return the response from STDOUT. 
However on some Unix commands (e.g. wget, curl) if ErrorCode == 0 there is no response on STDOUT, but the commands return valid information on STDERR (even though there was not an error).
In this PR, if ErrorCode == 0, the return value of executeCommandLineAndWaitResponse() is `!"".equals(STDOUT) ? STDOUT : STDERR`
=> [executeCommandLine] should return STDERR if STDOUT is empty

bundles/org.openhab.core.io.transport.serial.javacomm/src/main/java/org/openhab/core/io/transport/serial/internal/SerialPortIdentifierImpl.java, bundles/org.openhab.core.io.transport.serial.rxtx/src/main/java/org/openhab/core/io/transport/serial/internal/SerialPortIdentifierImpl.java, bundles/org.openhab.core.io.transport.serial/src/main/java/org/openhab/core/io/transport/serial/PortInUseException.java
I don't know when the javacomm bundle is needed, so I applied the changes there, too.
=> Add current owner to PortInUseException

bom/compile/pom.xml, bundles/org.openhab.core.io.transport.serial.rxtx.rfc2217/pom.xml, features/karaf/openhab-core/src/main/feature/feature.xml, pom.xml
* Exclude commons-net from core dependencies so it is no longer automatically a transitive compile dependency
* Update nrjavaserial compile dependency to a version that no longer includes commons-net packages
* Define and use commons.net.version property
* Rework features so commons-net is only installed when required
---
This stops commons-net from being automatically available on the compile classpath and in features.
That way we can stop it from being used unintentionally.
Related to:
* https://github.com/openhab/openhab-core/pull/2141
* https://github.com/openhab/openhab-addons/pull/9921
=> Stop commons-net proliferation

bundles/org.openhab.core.storage.json/src/main/java/org/openhab/core/storage/json/internal/JsonStorage.java
Fixes #2136
A file which has legitimately had all items removed, e.g. deleting all things from the UI, results in a 2 byte file containing just `{}`, so there should be no problem with unintentionally restoring a file from backup.
Here's an example of the output with a zero byte Things DB and a couple of zero byte backups:
```
2021-01-25 17:31:25.590 [WARN ] [re.storage.json.internal.JsonStorage] - Json storage file at '/var/lib/openhab/jsondb/org.openhab.core.thing.Thing.json' is empty - ignoring corrupt file.
2021-01-25 17:31:25.598 [INFO ] [re.storage.json.internal.JsonStorage] - Json storage file at '/var/lib/openhab/jsondb/org.openhab.core.thing.Thing.json' seems to be corrupt - checking for a backup.
2021-01-25 17:31:25.614 [WARN ] [re.storage.json.internal.JsonStorage] - Json …
```
=> [jsondb] Restore zero byte files from backup

bundles/org.openhab.core.model.script/src/org/openhab/core/model/script/actions/Timer.java, bundles/org.openhab.core.model.script/src/org/openhab/core/model/script/internal/actions/TimerImpl.java
This will return a ZonedDateTime of the scheduled execution time. This will allow the timer logic to determine how much extension (via reschedule) a timer would need, based on the current timer schedule.
It will return null if the timer has been cancelled.
It will return a time in the past if the timer has terminated.
=> [timer] Add Timer.getExecutionTime()

bundles/org.openhab.core.automation.module.script.rulesupport/src/main/java/org/openhab/core/automation/module/script/rulesupport/internal/loader/DependencyTracker.java, bundles/org.openhab.core.automation.module.script.rulesupport/src/main/java/org/openhab/core/automation/module/script/rulesupport/internal/loader/ScriptFileWatcher.java, bundles/org.openhab.core.automation.module.script.rulesupport/src/main/java/org/openhab/core/automation/module/script/rulesupport/internal/loader/ScriptLibraryWatcher.java, bundles/org.openhab.core.automation.module.script.rulesupport/src/main/java/org/openhab/core/automation/module/script/rulesupport/internal/loader/collection/BidiSetBag.java, bundles/org.openhab.core.automation.module.script/src/main/java/org/openhab/core/automation/module/script/ScriptDependencyListener.java, bundles/org.openhab.core.automation.module.script/src/main/java/org/openhab/core/automation/module/script/ScriptEngineFactory.java, bundles/org.openhab.core.automation.module.script/src/main/java/org/openhab/core/automation/module/script/ScriptEngineManager.java, bundles/org.openhab.core.automation.module.script/src/main/java/org/openhab/core/automation/module/script/internal/ScriptEngineManagerImpl.java
Added ability for ScriptEngines to allow script dependencies to be tracked and changes to trigger script reloading.
This is via a supplier function included in the Script Context.
I have tested this with (a) Python that does not use it and (b) GraalJS which does.
=> [automation] Script dependency tracking

bundles/org.openhab.core.automation.module.script.rulesupport/src/main/java/org/openhab/core/automation/module/script/rulesupport/shared/ScriptedAutomationManager.java
Allow scripts to register to create rules that are unmanaged: that is will be tied to the lifecycle of the script itself. This typically makes for cleaner script code.
=> Add ability for scripts to create unmanaged rules

bundles/org.openhab.core.ui/src/main/java/org/openhab/core/ui/internal/items/ItemUIRegistryImpl.java, bundles/org.openhab.core.ui/src/test/java/org/openhab/core/ui/internal/items/ItemUIRegistryImplTest.java
As described in https://github.com/openhab/openhab-webui/issues/765 changing temperature via BasicUI fails as long as the widget in the sitemap doesn't have a label defined.
I debugged the issue on my openHAB instance (v3.0.0) and saw that the unit-symbol of the Item will not be used in case no label was defined and instead of this `null` will be returned.
Therefore I added a small check that will ensure that the unit-symbol of the item will be returned as long as no label is given.
Unfortunately I don't know how to test the changes, I tried replacing the corresponding JAR in the runtime directory, but seems that it doesn't work. If someone could give me some hints how I can check this in my running openHAB instance please let me know.
Anyway I added some unit-tests based on the …
=> Fix changing temperature via BasicUI (#2091)

bundles/org.openhab.core.io.transport.modbus/pom.xml, bundles/org.openhab.core.io.transport.modbus/src/main/java/org/openhab/core/io/transport/modbus/ModbusReadRequestBlueprint.java, bundles/org.openhab.core.io.transport.modbus/src/main/java/org/openhab/core/io/transport/modbus/ModbusWriteCoilRequestBlueprint.java, bundles/org.openhab.core.io.transport.modbus/src/main/java/org/openhab/core/io/transport/modbus/ModbusWriteRegisterRequestBlueprint.java, bundles/org.openhab.core.io.transport.modbus/src/main/java/org/openhab/core/io/transport/modbus/endpoint/EndpointPoolConfiguration.java, bundles/org.openhab.core.io.transport.modbus/src/main/java/org/openhab/core/io/transport/modbus/endpoint/ModbusIPSlaveEndpoint.java, bundles/org.openhab.core.io.transport.modbus/src/main/java/org/openhab/core/io/transport/modbus/endpoint/ModbusSerialSlaveEndpoint.java, bundles/org.openhab.core.io.transport.modbus/src/main/java/org/openhab/core/io/transport/modbus/internal/BasicPollTask.java, bundles/org.openhab.core.io.transport.modbus/src/main/java/org/openhab/core/io/transport/modbus/internal/BasicWriteTask.java, bundles/org.openhab.core.io.transport.modbus/src/main/java/org/openhab/core/io/transport/modbus/internal/ModbusManagerImpl.java, bundles/org.openhab.core.io.transport.modbus/src/main/java/org/openhab/core/io/transport/modbus/json/WriteRequestJsonUtilities.java, bundles/org.openhab.core.io.transport.modbus/src/test/java/org/openhab/core/io/transport/modbus/test/IntegrationTestSupport.java, bundles/org.openhab.core.io.transport.modbus/src/test/java/org/openhab/core/io/transport/modbus/test/SmokeTest.java
Addressing the following Issues..
- https://github.com/openhab/openhab-core/issues/2006 (dependency org.eclipse.jetty.util.ConcurrentHashSet)
- https://github.com/openhab/openhab-core/issues/2115 (dependency org.apache.commons.*)
References..
- https://github.com/openhab/jamod/pull/9
This PR removes a few (but not all) of the deprecated libraries..
- org.eclipse.jetty.util.ConcurrentHashSet
- org.apache.commons.lang.builder.EqualsBuilder
- org.apache.commons.lang.builder.HashCodeBuilder
- org.apache.commons.lang.builder.ToStringBuilder
- org.apache.commons.lang.builder.StandardToStringStyle
**_Note: it does not remove all of the dependencies on 'org.apache.commons.*'_** (but it is a big first step..)
@ssalonen @splatch @cweitkamp
=> [transport.modbus] Remove dependencies on deprecated libraries

bundles/org.openhab.core.config.discovery.upnp/src/main/java/org/openhab/core/config/discovery/upnp/UpnpDiscoveryParticipant.java, bundles/org.openhab.core.config.discovery.upnp/src/main/java/org/openhab/core/config/discovery/upnp/internal/UpnpDiscoveryService.java, bundles/org.openhab.core.io.transport.modbus/pom.xml
**BACKGROUND**
The JUPnP library strictly follows the UPnP specification insofar as if a device fails to send its next 'ssdp:alive' notification within its declared 'maxAge' period, it is immediately considered to be gone. Unfortunately some types of OpenHAB bindings have devices that can sometimes be a bit late in sending their 'ssdp:alive' notifications even though they have not really gone offline (e.g. the Philips Hue bridge), which means that such devices are repeatedly removed from, and (re)added to, the InBox. This leads to confusion in the UI, and repeated logger messages.
**SOLUTION**
To prevent this, when the OH core receives a remoteDeviceRemoved() notification from JUPnP it asks the binding if it should immediately remove the device from the Inbox, or alternatively wait for a …
=> [discovery.upnp] Devices may apply a grace period for removal from the Inbox

bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/internal/JSONResponseExceptionMapper.java, bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/internal/link/ItemChannelLinkResource.java
This fixes the HTTP 500 error that I reported in https://github.com/openhab/openhab-webui/issues/878 and also makes sure that such errors turn up in the log file and are no longer swallowed.
=> Prevent internal server error on invalid link requests on REST API

bundles/org.openhab.core.ui/src/main/java/org/openhab/core/ui/internal/proxy/ProxyServletService.java, bundles/org.openhab.core.ui/src/test/java/org/openhab/core/ui/internal/proxy/ProxyServletServiceTest.java
Third attempt at this PR, but this very simply allows for the proxy to find the sitemaps for both file based as well as gui generated.
Fixes #2154
Fixes openhab/openhab-webui#763
Fixes openhab/openhab-webui#745
=> Support sitemaps created through UI in proxy

bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/module/factory/EphemerisModuleHandlerFactory.java, bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/module/handler/EphemerisConditionHandler.java, bundles/org.openhab.core.automation/src/main/resources/OH-INF/automation/moduletypes/EphemerisConditions.json, bundles/org.openhab.core.automation/src/test/java/org/openhab/core/automation/internal/module/factory/EphemerisModuleHandlerFactoryTest.java
Fixes #2035
Signed-off-by: Sönke Küper <soenkekueper@gmx.de>
=> Added rule condition for not a holiday

bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/DefaultSystemChannelTypeProvider.java
Currently, Things that support this channel type always show two color temperature channels, which looks weird and distracting to the user:
As the absolute channel is an optional feature for advanced users and use cases, it should imho also only appear as an advanced channel.
=> Make absolute color temperature channel type advanced

bundles/org.openhab.core.voice/src/main/java/org/openhab/core/voice/VoiceManager.java, bundles/org.openhab.core.voice/src/main/java/org/openhab/core/voice/internal/VoiceConsoleCommandExtension.java, bundles/org.openhab.core.voice/src/main/java/org/openhab/core/voice/internal/VoiceManagerImpl.java, itests/org.openhab.core.voice.tests/src/main/java/org/openhab/core/voice/internal/VoiceManagerImplTest.java
- Added nullness annotations to `VoiceManagerImpl` in https://github.com/openhab/openhab-core/commit/7eb3a9fe254c4cf70bfe2fddf2f7f50973cbb5c1
- Changed annotation of `getPreferredVoice` method to allow null results in https://github.com/openhab/openhab-core/commit/db9a6d91f92b4732e78495c61ada138a8c0567c4
See https://community.openhab.org/t/openhab-3-google-tts/116531
=> [voice] Changed annotation of `getPreferredVoice` method to allow null results

bundles/org.openhab.core.semantics/model/generateTagClasses.groovy, bundles/org.openhab.core.semantics/pom.xml
This way you can generate the classes with Maven when adding `-DgenerateTagClasses` to your build command.
I.e. you no longer need to have Groovy locally installed for this.
Also properly sorts the generated imports so they match the Spotless configuration.
=> Add profile to generate semantics classes with groovy-maven-plugin

bom/runtime/pom.xml, bundles/org.openhab.core.io.monitor/bnd.bnd, bundles/org.openhab.core.io.monitor/pom.xml, bundles/org.openhab.core.io.monitor/src/main/java/org/openhab/core/io/monitor/MeterRegistryProvider.java, bundles/org.openhab.core.io.monitor/src/main/java/org/openhab/core/io/monitor/internal/DefaultMetricsRegistration.java, bundles/org.openhab.core.io.monitor/src/main/java/org/openhab/core/io/monitor/internal/EventLogger.java, bundles/org.openhab.core.io.monitor/src/main/java/org/openhab/core/io/monitor/internal/metrics/BundleStateMetric.java, bundles/org.openhab.core.io.monitor/src/main/java/org/openhab/core/io/monitor/internal/metrics/EventCountMetric.java, bundles/org.openhab.core.io.monitor/src/main/java/org/openhab/core/io/monitor/internal/metrics/JVMMetric.java, bundles/org.openhab.core.io.monitor/src/main/java/org/openhab/core/io/monitor/internal/metrics/OpenhabCoreMeterBinder.java, bundles/org.openhab.core.io.monitor/src/main/java/org/openhab/core/io/monitor/internal/metrics/RuleMetric.java, bundles/org.openhab.core.io.monitor/src/main/java/org/openhab/core/io/monitor/internal/metrics/ThingStateMetric.java, bundles/org.openhab.core.io.monitor/src/main/java/org/openhab/core/io/monitor/internal/metrics/ThreadPoolMetric.java
This is the initial draft of the micrometer integration to address #774.
I figured the best place to put it would be the already existing core.io.monitoring bundle. I'll move it otherwise.
Some notes: 
- the bundle registers some "default" metrics (basically all JVM related) and some openhab specific metrics (ThreadManager pool statistics, event counts, bundle states, thing states, rule run counts)
- it uses the Micrometer [global meter registry](https://micrometer.io/docs/concepts#_global_registry), a [composite registry](https://micrometer.io/docs/concepts#_composite_registries) where other registries (e. g. the Prometheus one) can attach later to generate the actual metrics
- I'm developing an IO addon, which attaches to the global meter registry and provides the actual metrics as REST …
=> Integrated micrometer metering #774

bundles/org.openhab.core.io.transport.modbus/src/main/java/org/openhab/core/io/transport/modbus/ModbusManager.java, bundles/org.openhab.core.io.transport.modbus/src/main/java/org/openhab/core/io/transport/modbus/internal/ModbusManagerImpl.java, bundles/org.openhab.core.io.transport.modbus/src/main/java/org/openhab/core/io/transport/modbus/internal/pooling/ModbusSlaveConnectionFactoryImpl.java
Small fixes and consistency improvements when utilizing default `EndpointPoolConfiguration`, i.e. creating `newModbusCommunicationInterface` with `null` configuration.
Note: this code path is never executed with real openHAB bindings as they always construct `EndpointPoolConfiguration` explicitly. https://github.com/openhab/openhab-addons/pull/10147 ensures that all  `EndpointPoolConfiguration` parameters have the correct defaults
=> [modbus] Modbus poolconfig handling

bundles/org.openhab.core.io.rest.sitemap/src/main/java/org/openhab/core/io/rest/sitemap/internal/SitemapResource.java
Resolves issue with interfaces that use the API to generate content.   
https://github.com/openhab/openhab-core/pull/2178#issuecomment-779386044
The problem is the rest api adds a .sitemap extension to sitemaps, so this will now fail with the new proxy that does it's lookups based on name, not relying on the .sitemap extension to know it was file generated.   
This brings the API in line with everything else.
=> Fix sitemap proxy URL provided by Rest API

bundles/org.openhab.core.model.script.runtime/src/org/openhab/core/model/script/runtime/internal/engine/ScriptEngineImpl.java
Fixes #2200
Signed-off-by: Mark Hilbush <mark@hilbush.com>
=> [automation] Fixed memory leak caused by invalid UI DSL rule

bundles/org.openhab.core.model.script/bnd.bnd, bundles/org.openhab.core.model.script/pom.xml, bundles/org.openhab.core.model.script/src.moved/test/java/org/openhab/core/model/script/actions/SemanticsTest.java, bundles/org.openhab.core.model.script/src/org/openhab/core/model/script/actions/Semantics.java, bundles/org.openhab.core.model.script/src/org/openhab/core/model/script/internal/engine/action/SemanticsActionService.java, bundles/org.openhab.core.semantics/src/main/java/org/openhab/core/semantics/SemanticTags.java, bundles/org.openhab.core.semantics/src/test/java/org/openhab/core/semantics/SemanticTagsTest.java, bundles/org.openhab.core.semantics/src/test/java/org/openhab/core/semantics/SemanticsPredicatesTest.java, itests/org.openhab.core.model.core.tests/itest.bndrun, itests/org.openhab.core.model.item.tests/itest.bndrun, itests/org.openhab.core.model.rule.tests/itest.bndrun, itests/org.openhab.core.model.script.tests/itest.bndrun, itests/org.openhab.core.model.thing.tests/itest.bndrun
- Added ActionService to support using Semantics features in Rules
- Enhanced unit tests
I like to use Semantic features in Rules. E.g. determine the location of an item. Regardless if it is a Point, an Equipment or a Location itself. Therefore I propose to add a bunch methods to be used in Rules. I submitted this as a draft because I am not sure if this is the preferred way to add such features.
- `boolean isLocation(Item)` - checks if the given Item is is a Location
- `boolean isEquipment(Item)` - checks if the given Item is is an Equipment
- `boolean isPoint(Item)` - checks if the given Item is is a Point
- `Item getLocation(Item)` - gets the Location Item of the Item
- `Class<? extends Location> getLocationType(Item)` - gets the Location type of the Item
- `Item getEquipment(Item)` - …
=> [semantics] Added ActionService to support using Semantics features in Rules

bundles/org.openhab.core/src/main/java/org/openhab/core/internal/scheduler/CronSchedulerImpl.java, bundles/org.openhab.core/src/main/java/org/openhab/core/internal/scheduler/SchedulerImpl.java, bundles/org.openhab.core/src/main/java/org/openhab/core/scheduler/ScheduledCompletableFuture.java, bundles/org.openhab.core/src/test/java/org/openhab/core/internal/scheduler/CronAdjusterTest.java, bundles/org.openhab.core/src/test/java/org/openhab/core/internal/scheduler/SchedulerImplTest.java
Some users reported the scheduler to be run to earlier. It actual is known the Java scheduler can drift.
To handle this problem 2 changes have been made:
1. If the scheduler triggers > 2 sec before expected end time it will reschedule.
2. The scheduler keeps track of the timestamp the job should run. For recurring schedulers, like cron, when the next job is run it offsets of the calculated time, and not the actual time. This guaranties that the next scheduled time is actual the next scheduled time and not the same end time in case the scheduler would trigger to early.
Closes #1976
=> [scheduler] Mitigation fix for earlier triggers #1976

bundles/org.openhab.core.io.transport.mqtt/src/main/java/org/openhab/core/io/transport/mqtt/internal/client/MqttAsyncClientWrapper.java
Solves issue #2145 "io transport mqtt sets wrong QoS levels to hiveMQ" 
https://github.com/openhab/openhab-core/issues/2145
Fix is simply exchanging the enum values returned for the case 0 and case 1 branches, as they have been mixed up as compared to the mqtt specification:
> According to https://www.hivemq.com/blog/mqtt-essentials-part-6-mqtt-quality-of-service-levels/, the QoS levels are:
> 
> - At most once (0)
> - At least once (1)
> - Exactly once (2)
=> Fix MQTT QoS levels setting

bom/runtime/pom.xml, features/karaf/openhab-tp/src/main/feature/feature.xml
Upgrades Jackson from 2.10.3 to 2.12.2.
For release notes see:
* https://github.com/FasterXML/jackson/wiki/Jackson-Release-2.10
* https://github.com/FasterXML/jackson/wiki/Jackson-Release-2.11
* https://github.com/FasterXML/jackson/wiki/Jackson-Release-2.12
Also adds jackson-dataformat-cbor to the feature and runtime BOM so it can be more easily managed as it is a small bundle that is used by a few add-ons.
=> Upgrade Jackson to 2.12.2

bundles/org.openhab.core.automation.module.media/src/main/java/org/openhab/core/automation/module/media/internal/PlayActionHandler.java, bundles/org.openhab.core.automation.module.media/src/main/java/org/openhab/core/automation/module/media/internal/SayActionHandler.java
- sink might be null
Otherwise you cannot use the action without specifying a sink:
=> [automation] Sink might be null

bom/compile/pom.xml, bom/runtime/pom.xml, features/karaf/openhab-tp/src/main/feature/feature.xml
Upgrades Swagger from 2.1.0 to 2.1.7 .
See the tags on GitHub for release notes, e.g.:
https://github.com/swagger-api/swagger-core/releases/tag/v2.1.7
=> Upgrade Swagger to 2.1.7

bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/internal/ThingFactoryHelper.java, bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/internal/ThingManagerImpl.java, itests/org.openhab.core.thing.tests/src/main/java/org/openhab/core/thing/internal/ThingManagerOSGiJavaTest.java
Fixes createChannelBuilders not using the overridden label/description (#2225)
Below example would lead to a channel with label "Original Label", with the new code it will lead to "Label Overridden" as expected.
thing-types.xml
```
<channel-group-type id="channel_group_type_example">
<label>Channel Group Type Example</label>
<channels>
<channel id="channel_example" typeId="channel_type_example">
<label>Label Overridden</label>
</channel>
</channels>
</channel-group-type>
<channel-type id="channel_type_example">
<item-type>String</item-type>
<label>Original Label</label>
</channel-type>
```
In the ThingHandler:
```
void updateChannels() {
List<Channel> toBeAddedChannels = new ArrayList<>();
toBeAddedChannels.addAll(createChannelsForGroup(groupID, CHANNEL_GROUP_TYPE_EXTRUDER));
}
private …
```
=> Fix createChannelBuilders not using overriden label/description

bundles/org.openhab.core/src/main/java/org/openhab/core/net/HttpServiceUtil.java
- Added nullness annotations to fix NPE in `HttpServiceUtil`
```
2021-03-12 12:28:48.124 [ERROR] [core.thing.internal.ThingManagerImpl] - Exception occurred while calling thing handler factory 'org.openhab.binding.chromecast.internal.factory.ChromecastHandlerFactory@6a197e': null
java.lang.NullPointerException: null
at org.openhab.core.net.HttpServiceUtil.getHttpServicePortProperty(HttpServiceUtil.java:54) ~[?:?]
at org.openhab.core.net.HttpServiceUtil.getHttpServicePort(HttpServiceUtil.java:39) ~[?:?]
at org.openhab.binding.chromecast.internal.factory.ChromecastHandlerFactory.createCallbackUrl(ChromecastHandlerFactory.java:101) ~[?:?]
at org.openhab.binding.chromecast.internal.factory.ChromecastHandlerFactory.createHandler(ChromecastHandlerFactory.java:80) ~[?:?]
at …
```
=> Added nullness annotations to fix NPE in HttpServiceUtil

bundles/org.openhab.core.automation.module.script.rulesupport/src/main/java/org/openhab/core/automation/module/script/rulesupport/internal/loader/DependencyTracker.java, bundles/org.openhab.core.automation.module.script.rulesupport/src/main/java/org/openhab/core/automation/module/script/rulesupport/internal/loader/ScriptFileReference.java, bundles/org.openhab.core.automation.module.script.rulesupport/src/main/java/org/openhab/core/automation/module/script/rulesupport/internal/loader/ScriptFileWatcher.java, bundles/org.openhab.core.automation.module.script.rulesupport/src/test/java/org/openhab/core/automation/module/script/rulesupport/internal/loader/DelegatingScheduledExecutorService.java, bundles/org.openhab.core.automation.module.script.rulesupport/src/test/java/org/openhab/core/automation/module/script/rulesupport/internal/loader/ScriptFileWatcherTest.java
Allows scripts to specify per-script start levels (which differ from the start level for the `ScriptFileWatcher` itself). Also extracted various functionality from ScriptFileWatcher into distinct components & added unit tests to cover all script loading functionality.
This fixes #2002 and possibly #1983 too. The vast majority of the new LOC are unit tests.
Signed-off-by: jpg0 <jpg@trillica.com>
=> [automation] Added automation script StartLevels

bom/compile/pom.xml
This helps with preventing contributors from annotating classes with wrong annotations.
Related to:
* https://github.com/openhab/openhab-core/pull/2241
* https://github.com/openhab/openhab-addons/pull/10334
* https://github.com/openhab/org.openhab.binding.zwave/pull/1558
=> Exclude jetbrains annotations

bom/compile/pom.xml, bom/runtime/pom.xml, features/karaf/openhab-tp/src/main/feature/feature.xml
There was already a transitive commons-lang3:3.9 compile dependency used by several add-ons.
This is a transitive dependency of pax-web-jetty and swagger-core.
---
Depends on:
* https://github.com/openhab/openhab-addons/pull/10314
* https://github.com/openhab/openhab-webui/pull/955
=> Remove commons-lang dependency

bundles/org.openhab.core.ui/src/main/java/org/openhab/core/ui/internal/items/ItemUIRegistryImpl.java
When using groups in the sitemap the order is quite randomly.
According [ticket](https://github.com/openhab/openhab-webui/issues/76) was closed in the ui repository as the solution needs to come from the core.
I saw @ghys coming up with some orderid property which I really liked but wasn't sure whether that is a general solution. Would love to implement that if I got some hint.
For now sorting by string (which I implemented with this little PR) is to me much better than a random order.
Signed-off-by: bjoernbrings <bjoernbrings@web.de>
=> Sort group item by string

bom/compile/pom.xml, bom/runtime/pom.xml, bundles/org.openhab.core.io.transport.modbus/src/main/java/org/openhab/core/io/transport/modbus/json/WriteRequestJsonUtilities.java, features/karaf/openhab-tp/src/main/feature/feature.xml, itests/org.openhab.core.auth.oauth2client.tests/itest.bndrun, itests/org.openhab.core.automation.integration.tests/itest.bndrun, itests/org.openhab.core.automation.module.core.tests/itest.bndrun, itests/org.openhab.core.automation.module.script.tests/itest.bndrun, itests/org.openhab.core.automation.module.timer.tests/itest.bndrun, itests/org.openhab.core.automation.tests/itest.bndrun, itests/org.openhab.core.binding.xml.tests/itest.bndrun, itests/org.openhab.core.config.core.tests/itest.bndrun, itests/org.openhab.core.config.discovery.mdns.tests/itest.bndrun, itests/org.openhab.core.config.discovery.tests/itest.bndrun, itests/org.openhab.core.config.discovery.usbserial.linuxsysfs.tests/itest.bndrun, itests/org.openhab.core.config.discovery.usbserial.tests/itest.bndrun, itests/org.openhab.core.config.dispatch.tests/itest.bndrun, itests/org.openhab.core.config.xml.tests/itest.bndrun, itests/org.openhab.core.ephemeris.tests/itest.bndrun, itests/org.openhab.core.io.rest.core.tests/itest.bndrun, itests/org.openhab.core.model.core.tests/itest.bndrun, itests/org.openhab.core.model.item.tests/itest.bndrun, itests/org.openhab.core.model.rule.tests/itest.bndrun, itests/org.openhab.core.model.script.tests/itest.bndrun, itests/org.openhab.core.model.thing.tests/itest.bndrun, itests/org.openhab.core.storage.json.tests/itest.bndrun, itests/org.openhab.core.tests/itest.bndrun, itests/org.openhab.core.thing.tests/itest.bndrun, itests/org.openhab.core.thing.xml.tests/itest.bndrun, itests/org.openhab.core.voice.tests/itest.bndrun
Upgrades Gson from 2.8.2 to 2.8.6.
See change log: https://github.com/google/gson/blob/master/CHANGELOG.md
=> Upgrade Gson to 2.8.6

bundles/org.openhab.core.automation.module.script.rulesupport/src/main/java/org/openhab/core/automation/module/script/rulesupport/internal/loader/ScriptFileReference.java, bundles/org.openhab.core.automation.module.script.rulesupport/src/test/java/org/openhab/core/automation/module/script/rulesupport/internal/loader/ScriptFileWatcherTest.java
#2222 accidentally prevented unload of scripts before reload upon modification, due to omission of equality implementation for script file references.
This PR fixes the bug by implementing equality, plus adds a unit test to verify the corrected behaviour.
=> Correctly unload script before reload. Fixes #2246

bundles/org.openhab.core.automation.rest/src/main/java/org/openhab/core/automation/rest/internal/RuleResource.java, bundles/org.openhab.core.io.rest.auth/src/main/java/org/openhab/core/io/rest/auth/internal/TokenResource.java, bundles/org.openhab.core.io.rest.auth/src/main/java/org/openhab/core/io/rest/auth/internal/UserApiTokenDTO.java, bundles/org.openhab.core.io.rest.auth/src/main/java/org/openhab/core/io/rest/auth/internal/UserDTO.java, bundles/org.openhab.core.io.rest.auth/src/main/java/org/openhab/core/io/rest/auth/internal/UserSessionDTO.java, bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/internal/addons/AddonResource.java, bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/internal/item/ItemResource.java, bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/internal/link/ItemChannelLinkResource.java, bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/internal/persistence/PersistenceResource.java, bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/internal/service/ConfigurableServiceResource.java, bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/internal/thing/ThingResource.java, bundles/org.openhab.core.io.rest.sitemap/src/main/java/org/openhab/core/io/rest/sitemap/internal/SitemapResource.java, bundles/org.openhab.core.ui.icon/src/main/java/org/openhab/core/ui/icon/internal/IconSetResource.java
This fixes some issues where the response content is missing or wrong in the generated OpenAPI spec.
=> Fix wrong/missing OpenAPI ApiResponse content

bundles/org.openhab.core.io.rest.auth/src/main/java/org/openhab/core/io/rest/auth/internal/AuthFilter.java, bundles/org.openhab.core.io.rest.auth/src/main/java/org/openhab/core/io/rest/auth/internal/ExpiringUserSecurityContextCache.java, bundles/org.openhab.core.io.rest.auth/src/main/resources/OH-INF/config/config.xml
This PR adds a small cache for calculating the auth hashes which aims to fix the performance issues introduced with OH3.
The cache does **not** store plain text passwords and is limited to a certain size.
Fixes https://github.com/openhab/openhab-core/issues/1899
=> Add cache for Basic Authentication

bundles/org.openhab.core.io.transport.modbus/src/main/java/org/openhab/core/io/transport/modbus/internal/ModbusManagerImpl.java
Workaround for https://github.com/openhab/openhab-core/issues/1842.
Typically serial connections are disconnected and reconnected on IO
errors. This has turned out to be problematic with the recent
nrjavaserial updates brought by OH3 (locking behaviour of nrjavaserial
seems to be prone to deadlocks).
We workaround the issues by trying to keep the serial connection open
as long as possible.
This might not a foolproof fix as commented by @fwolter https://github.com/openhab/openhab-core/issues/1842#issuecomment-792978074 :
> [...] I often observed the error right after the start of the JVM.
> I agree that this problem is very annoying. A "quick" solution would be to disable the locks in general.
But on the other hand the community reports seem to be very often related to "I/O" errors and the …
=> [modbus] Workaround for nrjavaserial issues: do not disconnect serial

tools/archetype/binding/src/main/resources/archetype-resources/src/main/java/internal/__bindingIdCamelCase__Configuration.java, tools/archetype/binding/src/main/resources/archetype-resources/src/main/java/internal/__bindingIdCamelCase__HandlerFactory.java, tools/archetype/binding/src/main/resources/archetype-resources/src/main/resources/OH-INF/i18n/__bindingId___xx.properties, tools/archetype/binding/src/main/resources/archetype-resources/src/main/resources/OH-INF/thing/thing-types.xml
Added some examples as many new bindings don't make use of context tags or supported bridges.
Also add a refresh parameter to show the `unit` and `min` attributes.
=> [skeleton] Use real world examples; fix imports

features/karaf/openhab-core/pom.xml, features/karaf/openhab-tp/pom.xml
These versions should also have been updated in https://github.com/openhab/openhab-core/pull/2264.
=> Align Jetty/JNA version properties with Karaf 4.3.1

pom.xml, tools/static-code-analysis/checkstyle/suppressions.xml
- Use SAT release version 0.11.1
- Added suppression for new OhInfXmlLabelCheck (PR https://github.com/openhab/static-code-analysis/pull/360)
Release notes:
https://github.com/openhab/static-code-analysis/releases/tag/0.11.0
https://github.com/openhab/static-code-analysis/releases/tag/0.11.1
=> [static-code-analysis] Use SAT release version 0.11.1

bundles/org.openhab.core.io.transport.modbus/pom.xml
This PR bumps version of jamod modbus library to include fix for case with fragmented modbus packets received via TCP connection (discussed here https://github.com/openhab/jamod/pull/11)
=> Upgrade jamod (to get rid of case with fragmented packets)

bundles/org.openhab.core.thing/src/main/resources/OH-INF/i18n/firmware.properties
=> Remove trailing space from update-canceled in firmware.properties

crowdin.yml
Looks like this is the root cause of the generated translation filenames not matching the original filename.
=> Fix Crowdin translation filename mismatch

bundles/org.openhab.core.io.transport.modbus/pom.xml
Modbus library jamod updated, bringing the following updates:
- Modbus TCP client to read the full modbus message, even if
fragmented/segmented. https://github.com/openhab/jamod/pull/13#issuecomment-825923270
- Serial/RTU to error more clearly if all bytes are not received as
expected. https://github.com/openhab/jamod/pull/15
Precompiled jar: [org.openhab.core.io.transport.modbus-3.1.0-SNAPSHOT.zip](https://github.com/openhab/openhab-core/files/6368861/org.openhab.core.io.transport.modbus-3.1.0-SNAPSHOT.zip)
Signed-off-by: Sami Salonen
=> [modbus] Modbus TCP robust against fragmentation/segmentation and more clear error message when all bytes are not received with Modbus/RTU

bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/internal/ThingManagerImpl.java, itests/org.openhab.core.thing.tests/src/main/java/org/openhab/core/thing/internal/ThingManagerOSGiTest.java
Ignore illegal thing status transitions from REMOVING instead of throwing IllegalArgumentException. Feedback is appreciated, especially concerning unexpected side-effects and the added integration test.
Closes #2311
=> Ignore illegal thing status updates from REMOVING

bundles/org.openhab.core.config.core/src/main/java/org/openhab/core/config/core/internal/net/NetworkConfigOptionProvider.java
- Filter duplicate broadcast addresses for service configuration if multiple network interfaces are available
=> [net] Filter duplicate broadcast addresses for service configuration if multiple network interfaces are available

bundles/org.openhab.core.io.monitor/bnd.bnd, bundles/org.openhab.core.io.monitor/pom.xml, bundles/org.openhab.core.io.monitor/src/main/java/org/openhab/core/io/monitor/internal/metrics/RuleMetric.java
Fixes #2288. 
Signed-off-by: Robert Bach <openhab@mortalsilence.net>
=> [metering] Fix dependency issue in io.monitor bundle (#2288)

bom/compile/pom.xml, features/karaf/openhab-tp/src/main/feature/feature.xml
Depends on https://github.com/openhab/openhab-osgiify/pull/27
---
Upgrades:
* hivemq-mqtt-client from 1.1.2 to 1.2.2
* Netty from 4.1.42.Final to 4.1.63.Final
For all fixes and improvements of these upgrades, see:
* https://github.com/hivemq/hivemq-mqtt-client/releases/
* https://netty.io/news/index.html
Fixes #2309
=> Upgrade hivemq-mqtt-client to 1.2.2, Netty to 4.1.63.Final

bom/compile/pom.xml, bom/runtime/pom.xml, features/karaf/openhab-tp/src/main/feature/feature.xml
Depends on https://github.com/openhab/openhab-addons/pull/10614, https://github.com/openhab/openhab-webui/pull/1028
Related to openhab/openhab-addons#7722
Replaces #2321, #2322
=> Remove commons-io and commons-codec dependencies

bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/module/handler/ChannelEventTriggerHandler.java, bundles/org.openhab.core.automation/src/test/java/org/openhab/core/automation/internal/module/handler/ChannelEventTriggerHandlerTest.java
Matching only on "topic.contains(channelUID)" will lead to false
positivies.
This was reported for the linuxinput binding, where pressing the "left"
key would also trigger rules for the "l" key.
The channels for these are
`linuxinput:input-device:test:keypresses#KEY_L` and
`linuxinput:input-device:test:keypresses#KEY_LEFT`
Signed-off-by: Thomas Weißschuh <thomas@t-8ch.de>
=> [automation] match on complete channel UID

bundles/org.openhab.core.audio/src/main/resources/OH-INF/i18n/audio.properties, bundles/org.openhab.core.config.discovery/src/main/resources/OH-INF/i18n/inbox.properties, bundles/org.openhab.core.ephemeris/src/main/resources/OH-INF/i18n/ephemeris.properties, bundles/org.openhab.core.io.rest.auth/src/main/resources/OH-INF/i18n/restauth.properties, bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/internal/service/ConfigurableServiceResource.java, bundles/org.openhab.core.karaf/src/main/resources/OH-INF/i18n/addons.properties, bundles/org.openhab.core.persistence/src/main/resources/OH-INF/i18n/persistence.properties, bundles/org.openhab.core.storage.json/src/main/resources/OH-INF/i18n/jsonStorage.properties, bundles/org.openhab.core.ui/src/main/resources/OH-INF/i18n/chart.properties, bundles/org.openhab.core.voice/src/main/resources/OH-INF/i18n/voice.properties, bundles/org.openhab.core/src/main/resources/OH-INF/i18n/i18n.properties, bundles/org.openhab.core/src/main/resources/OH-INF/i18n/network.properties
- Added i18n feature for labels of ConfigurableServices
Notation is either ` service.<uri>.label = ...` (`:` has to be replaced by `.` in the `<uri>` part) or `@text/<key>`.
=> [i18n] Added i18n feature for labels of ConfigurableServices

bom/compile/pom.xml, bom/runtime/pom.xml, features/karaf/openhab-tp/src/main/feature/feature.xml
Updates Swagger from 2.1.7 to 2.1.9.
* https://github.com/swagger-api/swagger-core/releases/tag/v2.1.8
* https://github.com/swagger-api/swagger-core/releases/tag/v2.1.9
=> Update Swagger to 2.1.9

bom/runtime/pom.xml, features/karaf/openhab-tp/src/main/feature/feature.xml
Updates Jackson from 2.12.2 to 2.12.3.
https://github.com/FasterXML/jackson/wiki/Jackson-Release-2.12.3
=> Update Jackson to 2.12.3

pom.xml
This fixes the issue that the `tech.units.indriya` packages cannot be resolved in the JavaDoc build.
See: [openHAB JavaDoc down](https://community.openhab.org/t/openhab-javadoc-down/122223?u=wborn)
=> Fix JavaDoc build by upgrading plexus-java dependency

bundles/org.openhab.core.io.rest.sse/src/main/java/org/openhab/core/io/rest/sse/internal/SseItemStatesEventBuilder.java
With the addition of Profiles, there are situations where a Channel sends format information that
does not match the type. For example, "Timestamp on update" always sends a DateTime, but the channel
may specify a different format (e.g., if it is a battery level, "%.0f %%"). In such a case, we
attempt to format the DateTime according to the pattern, it (predictably and correctly) fails, and
this results in an error in the UI and a warning in the log.
While this is an expected error if a user uses an incorrect format code in an Item's metadata (user
error), it is somewhat unexpected if a user is choosing an option as presented in the UI. Because
this is purely a formatting issue, one solution is to direct users to add a formatting code if they
see an error. However, the disadvantage of this …
=> Display raw item state when formatting fails

bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/DefaultSystemChannelTypeProvider.java, itests/org.openhab.core.thing.tests/src/main/java/org/openhab/core/thing/SystemWideChannelTypesTest.java
- Expose Channel Type UIDs of default System Channel Types
https://github.com/openhab/openhab-addons/blob/e1a76505a07f9d329f046a7e3f41ddf9a6360247/bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/handler/SensorBaseThingHandler.java#L186-L191
The advantage of this is that bindings do not need to create the `ChannelTypeUID`s on there own but can reuse the exposed constants. Additionally bundles can use them for defining Profiles.
https://github.com/openhab/openhab-core/blob/a8f469e5e78ba86c5d648b85a0054b5a978c6ee9/bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/profiles/ProfileTypeBuilder.java#L111
https://github.com/openhab/openhab-core/blob/a8f469e5e78ba86c5d648b85a0054b5a978c6ee9/bundles/org.openhab.core.thing/src/main/java/org/openh …
=> Expose Channel Type UIDs of default System Channel Types

bundles/org.openhab.core/src/main/java/org/openhab/core/types/util/UnitUtils.java, bundles/org.openhab.core/src/test/java/org/openhab/core/types/util/UnitUtilsTest.java
- Catch `MeasurementParseException` in `UnitUtils.parseUnit(String)` method
Related to #2319
Avoids regressions when trying to parse an unknown unit:
```
17:46:20.356 [WARN ] [ue.internal.handler.HueBridgeHandler] - An unexpected error occurred: Parse Error
javax.measure.format.MeasurementParseException: Parse Error
at tech.units.indriya.format.SimpleUnitFormat$DefaultFormat.check(SimpleUnitFormat.java:631) ~[indriya-2.1.2.jar:2.1.2]
at tech.units.indriya.format.SimpleUnitFormat$DefaultFormat.parseSingleUnit(SimpleUnitFormat.java:486) ~[indriya-2.1.2.jar:2.1.2]
at tech.units.indriya.format.SimpleUnitFormat$DefaultFormat.parseProductUnit(SimpleUnitFormat.java:505) ~[indriya-2.1.2.jar:2.1.2]
at tech.units.indriya.format.SimpleUnitFormat.parseObject(SimpleUnitFormat.java:293) …
```
=> [UoM] Catch MeasurementParseException in UnitUtils.parseUnit(String) method

bundles/org.openhab.core.io.transport.modbus/pom.xml
Bumping jamod to 1.3.4.OH
Pending https://github.com/openhab/jamod/pull/16 and release
=> [modbus] clearer error messages

bom/compile/pom.xml, bom/runtime/pom.xml, features/karaf/openhab-tp/src/main/feature/feature.xml, itests/org.openhab.core.binding.xml.tests/itest.bndrun, itests/org.openhab.core.config.discovery.tests/itest.bndrun, itests/org.openhab.core.config.xml.tests/itest.bndrun, itests/org.openhab.core.ephemeris.tests/itest.bndrun, itests/org.openhab.core.model.core.tests/itest.bndrun, itests/org.openhab.core.model.item.tests/itest.bndrun, itests/org.openhab.core.model.script.tests/itest.bndrun, itests/org.openhab.core.model.thing.tests/itest.bndrun, itests/org.openhab.core.thing.tests/itest.bndrun, itests/org.openhab.core.thing.xml.tests/itest.bndrun
Upgrades XStream from 1.4.15 to 1.4.17
Prevents the following vulnerabilities when using XStream instances with an uninitialized security framework:
* CVE-2021-21341
* CVE-2021-21342
* CVE-2021-21343
* CVE-2021-21344
* CVE-2021-21345
* CVE-2021-21346
* CVE-2021-21347
* CVE-2021-21348
* CVE-2021-21349
* CVE-2021-21350
* CVE-2021-21351
* CVE-2021-29505
See: http://x-stream.github.io/changes.html#1.4.17
Related to: #2250, #2251
=> Upgrade XStream to 1.4.17

bundles/org.openhab.core/src/main/java/org/openhab/core/library/types/DecimalType.java, bundles/org.openhab.core/src/main/java/org/openhab/core/library/types/PercentType.java, bundles/org.openhab.core/src/main/java/org/openhab/core/library/types/QuantityType.java, bundles/org.openhab.core/src/test/java/org/openhab/core/internal/items/ItemStateConverterImplTest.java, bundles/org.openhab.core/src/test/java/org/openhab/core/library/types/DecimalTypeTest.java, bundles/org.openhab.core/src/test/java/org/openhab/core/library/types/PercentTypeTest.java, bundles/org.openhab.core/src/test/java/org/openhab/core/library/types/QuantityTypeArithmeticGroupFunctionTest.java, bundles/org.openhab.core/src/test/java/org/openhab/core/library/types/QuantityTypeTest.java
Adds constructors with a Locale parameter for parsing localized string to DecimalType, PercentType and QuantityType.
This allows for parsing locale specific group and decimal seperators in strings.
Also fixes:
* IllegalArgumentException not being thrown if numbers in strings are only partially parsed as QuantityType
* MeasurementParseException not caught and rethrown as IllegalArgumentException
Several new unit tests cover the new functionality and fixed regressions.
---
Further improves https://github.com/openhab/openhab-core/pull/2362
=> Support parsing localized strings with DecimalType, PercentType and QuantityType

bundles/org.openhab.core/src/main/java/org/openhab/core/library/types/DecimalType.java, bundles/org.openhab.core/src/main/java/org/openhab/core/library/types/PercentType.java, bundles/org.openhab.core/src/main/java/org/openhab/core/library/types/QuantityType.java, bundles/org.openhab.core/src/test/java/org/openhab/core/library/types/DecimalTypeTest.java, bundles/org.openhab.core/src/test/java/org/openhab/core/library/types/PercentTypeTest.java, bundles/org.openhab.core/src/test/java/org/openhab/core/library/types/QuantityTypeTest.java
Throw NumberFormatException when numbers are invalid and cannot be parsed to BigDecimals.
Add JavaDocs to document when which exception is thrown.
Add more unit tests to cover the thrown exceptions.
Related to #2365
=> Rework thrown exceptions for DecimalType, PercentType and QuantityType

bundles/org.openhab.core.automation.module.script/src/main/java/org/openhab/core/automation/module/script/internal/provider/ScriptModuleTypeProvider.java
Not sure if there's a good rationale behind it being read-only (maybe because it's not supposed to change after having been set) but removing it will fix https://github.com/openhab/openhab-webui/issues/1061.
=> [automation] Remove readOnly flag on script type parameter

bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/module/handler/ItemCommandActionHandler.java, bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/module/handler/ItemStateUpdateActionHandler.java, bundles/org.openhab.core.automation/src/main/resources/OH-INF/automation/moduletypes/ItemActions.json, bundles/org.openhab.core.automation/src/main/resources/OH-INF/automation/moduletypes/ItemTriggers.json
Tags are required to enable auto-mapping of inputs and outputs of modules in a rule, see https://github.com/openhab/openhab-addons/pull/10205#discussion_r636433332.
Also made command/state config params optional and being regarded, if they are set. This way it is avoided that auto-wiring prevents users from defining dedicated values in the actions.
=> [automation] add tags to item modules

itests/org.openhab.core.config.discovery.tests/src/main/java/org/openhab/core/config/discovery/inbox/DynamicThingUpdateOSGiTest.java, itests/org.openhab.core.config.discovery.tests/src/main/java/org/openhab/core/config/discovery/internal/InboxOSGiTest.java
- Fixed warnings on missing representation properties
=> [test] Fixed warnings on missing representation properties

bundles/org.openhab.core.config.core/src/main/java/org/openhab/core/config/core/FilterCriteria.java, bundles/org.openhab.core.config.core/src/main/java/org/openhab/core/config/core/dto/ConfigDescriptionDTOMapper.java, bundles/org.openhab.core.config.core/src/main/java/org/openhab/core/config/core/dto/ConfigDescriptionParameterDTO.java, bundles/org.openhab.core.config.core/src/test/java/org/openhab/core/config/core/dto/ConfigDescriptionDTOTest.java, bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/internal/config/ConfigDescriptionResource.java, bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/internal/item/ItemResource.java, bundles/org.openhab.core.io.rest.core/src/test/java/org/openhab/core/io/rest/core/config/EnrichedConfigDescriptionDTOMapperTest.java, bundles/org.openhab.core.io.rest.core/src/test/java/org/openhab/core/io/rest/core/internal/config/ConfigDescriptionResourceTest.java, itests/org.openhab.core.automation.integration.tests/src/main/java/org/openhab/core/automation/integration/test/AutomationIntegrationJsonTest.java, itests/org.openhab.core.automation.integration.tests/src/main/resources/OH-INF/automation/moduletypes/CustomActionsTypeDefinition.json
- Changed `ConfigDescriptionParameterDTO` field serialization: "defaultValue" -> "default"
- Fixed a minor bug in `ConfigDescriptionDTOMapper` for field "unit"
- Added unit tests for `ConfigDescriptionDTOMapper`, `ConfigDescriptionResource` and `AutomationIntegrationJsonTest`
Supersedes #2376
Related to #2148
=> [config] Changed 'ConfigDescriptionParameterDTO' field serialization 'defaultValue' -> 'default'

bundles/org.openhab.core/src/main/java/org/openhab/core/library/unit/ImperialUnits.java
Corrected type for of SQUARE_FOOT and CUBIC_FOOT to be Unit<Area> and Unit<Volume>, respectively
Added SQUARE_INCH, CUBIC_INCH, GALLON_LIQUID_US and GALLON_PER_MINUTE
=> Added GALLON_LIQUID_US and GALLON_PER_MINUTE to UoM

bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/internal/persistence/PersistenceResource.java
**Problem:**
At the moment, the openapi specification generator for the rest api of openhab generates the following block for the api in the endpoint (GET) /things:
```yaml
put:
tags:
- persistence
summary: Stores item persistence data into the persistence service.
operationId: storeItemDataInPersistenceService
parameters:
- name: serviceId
in: query
description: >-
Id of the persistence service. If not provided the default service
will be used
schema:
type: string
- name: itemname
in: path
description: The item name.
required: true
schema:
type: string
- name: time
in: query
description: >-
Time of the data to be stored. Will default to current time.
[yyyy-MM-dd'T'HH:mm:ss.SSSZ]
required: true
schema:
type: string
- name: state
in: query
description: The state to store.
required: true …
```
=> [REST][Docs] Corrects the docs for security requirement for the PersistenceResource (in the openapi specification)

bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/internal/thing/ThingResource.java
**Problem:**
At the moment, the openapi specification generator for the rest api of openhab generates the following block for the api in the endpoint (GET) /things:
```yaml
/things:
get:
tags:
- things
summary: Get all available things.
operationId: getThings
parameters:
- name: Accept-Language
in: header
description: language
schema:
type: string
- name: summary
in: query
description: summary fields only
schema:
type: boolean
responses:
'200':
description: OK
content:
application/json:
schema:
uniqueItems: true
type: array
items:
$ref: '#/components/schemas/EnrichedThingDTO'
```
However, this is incorrect because the getThings function requires authentication (admin level). The output should therefore be as follows:
```yaml
/things:
get:
tags:
- things
summary: Get all available things. …
```
=> [REST][Docs] Corrects the docs for security requirement for the ThingResource (in the openapi specification)

bundles/org.openhab.core.test.magic/src/main/java/org/openhab/core/magic/binding/handler/MagicDynamicStateDescriptionThingHandler.java, bundles/org.openhab.core.test.magic/src/main/java/org/openhab/core/magic/binding/internal/MagicDynamicCommandDescriptionProvider.java, bundles/org.openhab.core.test.magic/src/main/java/org/openhab/core/magic/binding/internal/MagicDynamicStateDescriptionProvider.java, bundles/org.openhab.core.test.magic/src/main/java/org/openhab/core/magic/binding/internal/MagicHandlerFactory.java, bundles/org.openhab.core.test.magic/src/test/java/org/openhab/core/magic/binding/internal/MagicHandlerFactoryTest.java, bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/binding/AbstractDynamicDescriptionProvider.java, bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/binding/BaseDynamicCommandDescriptionProvider.java, bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/binding/BaseDynamicStateDescriptionProvider.java, bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/events/AbstractThingRegistryEvent.java, bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/events/ChannelDescriptionChangedEvent.java, bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/events/ChannelTriggeredEvent.java, bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/events/ThingEventFactory.java, bundles/org.openhab.core.thing/src/test/java/org/openhab/core/thing/binding/BaseDynamicCommandDescriptionProviderTest.java, bundles/org.openhab.core.thing/src/test/java/org/openhab/core/thing/binding/BaseDynamicStateDescriptionProviderTest.java, bundles/org.openhab.core.thing/src/test/java/org/openhab/core/thing/events/ThingEventFactoryTest.java, bundles/org.openhab.core.thing/src/test/java/org/openhab/core/thing/link/events/LinkEventFactoryTest.java, bundles/org.openhab.core/src/main/java/org/openhab/core/types/CommandOption.java, bundles/org.openhab.core/src/main/java/org/openhab/core/types/StateOption.java, itests/org.openhab.core.thing.tests/src/main/java/org/openhab/core/thing/events/ThingEventOSGiTest.java
- Added `ChannelDescriptionChangedEvent`
Problem statement: 
OHC framework supports dynamic `StateDescription`s and dynamic `CommandDescription`s which are set by bindings and may change during runtime. When the state options / command options are changed the UI doesn't update automatically. You need to do a page refresh to pick up the changes. This approach introduces a new event (`ChannelDescriptionChangedEvent`) which UIs can subscribe to and reload related widgets. The event payload contains the `ChannelUID`, a field identifier to give a hint which field has changed and a list of linked item names.
See e.g. https://github.com/openhab/openhab-addons/pull/7396#issuecomment-630773749
Closes #1753 
=> Added 'ChannelDescriptionChangedEvent'

bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/events/ThingEventFactory.java, bundles/org.openhab.core.thing/src/test/java/org/openhab/core/thing/events/ThingEventFactoryTest.java
- Added method to publish whole `StateDescriptionFragment`
Related to https://github.com/openhab/openhab-core/pull/1505
=> Added method to publish whole 'StateDescriptionFragment'

bundles/org.openhab.core/src/main/java/org/openhab/core/internal/service/StateDescriptionServiceImpl.java, bundles/org.openhab.core/src/test/java/org/openhab/core/internal/service/StateDescriptionServiceImplTest.java
- Create a deep copy of the first found fragment before merging other fragments into it
Fixes #2409
=> [item] Create a deep copy of the first found fragment before merging other fragments into it

bundles/org.openhab.core.io.rest.sitemap/src/main/java/org/openhab/core/io/rest/sitemap/SitemapSubscriptionService.java, bundles/org.openhab.core.io.rest.sitemap/src/main/java/org/openhab/core/io/rest/sitemap/internal/PageChangeListener.java, bundles/org.openhab.core.io.rest.sitemap/src/main/java/org/openhab/core/io/rest/sitemap/internal/SitemapWidgetEvent.java
item state or command description has been updated
Listen to the new ChannelDescriptionChangedEvent
=> Enhanced sitemap SSE event with a new boolean field informing if the

bundles/org.openhab.core.automation.module.script.rulesupport/src/main/java/org/openhab/core/automation/module/script/rulesupport/internal/loader/DependencyTracker.java, bundles/org.openhab.core.automation.module.script.rulesupport/src/main/java/org/openhab/core/automation/module/script/rulesupport/internal/loader/ScriptFileWatcher.java, bundles/org.openhab.core.automation.module.script.rulesupport/src/main/java/org/openhab/core/automation/module/script/rulesupport/internal/loader/ScriptLibraryWatcher.java
ScriptFileWatcher can now be configured to ignore specific, relative directories. This is used so that it can ignore "node_modules" which is what JS is hardcoded to use as a library path.
(Note that this also disables generic library tracking, and instead leaves specific enablement up to script engine providers. I will re-enable this in the JS add-on.)
This change is required to allow JS scripts to use relative paths for libraries, to allow general support for 3rd party libraries and tooling.
=> [automation] Ignore relative lib directories for scripts

bundles/org.openhab.core.ui/src/main/java/org/openhab/core/ui/internal/items/ItemUIRegistryImpl.java, bundles/org.openhab.core.ui/src/main/resources/OH-INF/config/sitemap.xml, bundles/org.openhab.core.ui/src/main/resources/OH-INF/i18n/sitemap.properties
=> Add a system setting to define how to sort group members

bundles/org.openhab.core.automation.rest/src/main/java/org/openhab/core/automation/rest/internal/RuleResource.java
Openapi requires either a `schema` or `content` property for `/rules.post.responses.201.headers.Location`. 
See openapi documentation [Description of Responses](https://swagger.io/docs/specification/describing-responses/#headers) for details. 
The code 
```java
final Rule newRule = ruleRegistry.add(RuleDTOMapper.map(rule));
return Response.status(Status.CREATED)
.header("location", "rules/" + URLEncoder.encode(newRule.getUID(), StandardCharsets.UTF_8)).build();
```
tells us that the "Location" header is a string with the url to the newly created rule.
We should add the schema specification for the header as a string by extending the annotation `@Header` within the `@ApiResponse` with `schema = @Schema(implementation = String.class)`.
=> RuleResource: Add schema specification for "Location" header

bundles/org.openhab.core.io.rest.swagger/src/main/java/org/openhab/core/io/rest/swagger/impl/OpenApiResource.java
**The problem:**
Right now, the output OpenAPI3 specification for openHAB (from /rest/spec) lists the OAuth2 SecurityScheme with properties `type` and `name`.
```json
// Other schemes and such ...
{
"securitySchemes":{
"oauth2":{
"type":"oauth2",
"name":"oauth2",
"flows":{
"authorizationCode":{
"authorizationUrl":"/auth/authorize",
"tokenUrl":"/rest/auth/token",
"scopes":{
"admin":"Administration operations"
}
}
}
}
}
}
```
OpenAPI3 only requires the type, but not the name of the SecurityScheme if its type is OAuth2.
In fact, it is even forbidden to specify the name here and it causes an error when validating the specification.
See the OAuth2 example:
```json
{
"type":"oauth2",
"flows":{
"implicit":{
"authorizationUrl":"https://example.com/api/oauth/dialog",
"scopes":{ …
```
=> OpenApiResource: Remove name from OAuth SecurityScheme to make it OpenAPI3 compliant

bundles/org.openhab.core.automation.module.script.rulesupport/src/main/java/org/openhab/core/automation/module/script/rulesupport/internal/loader/ScriptFileWatcher.java, bundles/org.openhab.core.automation.module.script.rulesupport/src/test/java/org/openhab/core/automation/module/script/rulesupport/internal/loader/ScriptFileWatcherTest.java, bundles/org.openhab.core.automation.module.script/src/main/java/org/openhab/core/automation/module/script/ScriptEngineManager.java, bundles/org.openhab.core.automation.module.script/src/main/java/org/openhab/core/automation/module/script/internal/ScriptEngineManagerImpl.java
Fixes #2458 
This is a different approach than the one proposed in the issue which implements a cleaner solution.
=> [automation] implement a listener for ScriptEngineFactory changes

bundles/org.openhab.core.model.item/pom.xml, bundles/org.openhab.core.model.persistence/pom.xml, bundles/org.openhab.core.model.rule/pom.xml, bundles/org.openhab.core.model.script/pom.xml, bundles/org.openhab.core.model.sitemap/pom.xml, bundles/org.openhab.core.model.thing/pom.xml
This should help a lot as a workaround to https://github.com/mvndaemon/mvnd/issues/440 which has no real fix.
=> Use exec:exec instead of exec:java goal to avoid classloaders leak

bundles/org.openhab.core.io.rest.auth/src/main/resources/OH-INF/config/restauth.xml
Following the discussion in #2476, I believe the order and "advanced" status of config parameters in API Security (`system:restauth`) should be changed.
This promotes "Implicit User Role" to a non-advanced option (even if it can break some clients, it is clearly stated in the description), and demotes "Allow Basic Authentication" to an advanced option (API Tokens can be used to authenticate to the API as a better alternative to Basic).
=> Rework system:restauth config parameters

bundles/org.openhab.core.io.monitor/src/main/java/org/openhab/core/io/monitor/internal/DefaultMetricsRegistration.java
Workaround for #2389
Catches `Throwable`, because a `NoClassDefFoundError` is thrown.
=> [metrics] Catch any Throwable during initialization

bom/compile/pom.xml, bom/runtime/pom.xml, features/karaf/openhab-tp/src/main/feature/feature.xml, itests/org.openhab.core.binding.xml.tests/itest.bndrun, itests/org.openhab.core.config.discovery.tests/itest.bndrun, itests/org.openhab.core.config.xml.tests/itest.bndrun, itests/org.openhab.core.ephemeris.tests/itest.bndrun, itests/org.openhab.core.model.thing.tests/itest.bndrun, itests/org.openhab.core.thing.tests/itest.bndrun, itests/org.openhab.core.thing.xml.tests/itest.bndrun
https://x-stream.github.io/changes.html#1.4.18
---
There were already PRs some time ago to properly initialize the XStream security framework in all code that uses XStream.
=> Upgrade XStream to 1.4.18

bundles/org.openhab.core.io.monitor/bnd.bnd
Fixes https://github.com/openhab/openhab-core/issues/2389
=> [monitor] Import javax.management package to correctly register GC metrics

bundles/org.openhab.core/src/main/java/org/openhab/core/service/StartLevelService.java
This makes unchecked and uncought exception visible, thrown in start level triggers. Tested with the exception from #2389.
Discussed in #2392 
=> [startlevel] Use wrapped scheduler to make swallowed exceptions visible

bundles/org.openhab.core.io.monitor/bnd.bnd, bundles/org.openhab.core.io.monitor/pom.xml, bundles/org.openhab.core.io.monitor/src/main/java/org/openhab/core/io/monitor/internal/metrics/BundleStateMetric.java, bundles/org.openhab.core.io.monitor/src/main/java/org/openhab/core/io/monitor/internal/metrics/EventCountMetric.java, bundles/org.openhab.core.io.monitor/src/main/java/org/openhab/core/io/monitor/internal/metrics/JVMMetric.java, bundles/org.openhab.core.io.monitor/src/main/java/org/openhab/core/io/monitor/internal/metrics/RuleMetric.java, bundles/org.openhab.core.io.monitor/src/main/java/org/openhab/core/io/monitor/internal/metrics/ThingStateMetric.java, bundles/org.openhab.core.io.monitor/src/main/java/org/openhab/core/io/monitor/internal/metrics/ThreadPoolMetric.java, bundles/org.openhab.core/src/main/java/org/openhab/core/common/ThreadPoolManager.java
* Fix `StringIndexOutOfBoundsException` when using rules file name that starts with 'state' (#2472)
* Null annotations fixes/improvements
* Add transitive `com.codahale.metrics` dependency which is used by `io.micrometer.core.instrument.dropwizard.DropwizardMeterRegistry`. This fixes a `NoClassDefFoundError` when implementing metrics exporters that use a `MeterRegistry` extending `DropwizardMeterRegistry` (e.g. `JmxMeterRegistry`).
* Prevent `ConcurrentModificationException` in `ThreadPoolMetric` at startup
Fixes #2472
=> Metrics improvements and fixes

bundles/org.openhab.core.addon.marketplace/src/main/java/org/openhab/core/addon/marketplace/internal/community/CommunityMarketplaceAddonService.java, bundles/org.openhab.core.addon.marketplace/src/main/resources/OH-INF/config/marketplace.xml
Add a config parameter to bypass the filtering of Dicourse topics
to include those which don't have the "published" tag.
Set the API key parameter as advanced (irrelevant to most users).
=> [Marketplace] Add option to include unpublished entries

bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/internal/addons/AddonResource.java
The code was already prepared for a nullable default service and then returns a 404 not found.
Fixes #2491
=> Prevent NSEE when there is no AddonService

bundles/org.openhab.core.io.transport.modbus/src/main/java/org/openhab/core/io/transport/modbus/exception/ModbusSlaveErrorResponseException.java, bundles/org.openhab.core.io.transport.modbus/src/main/java/org/openhab/core/io/transport/modbus/internal/ModbusManagerImpl.java, bundles/org.openhab.core.io.transport.modbus/src/main/java/org/openhab/core/io/transport/modbus/internal/ModbusSlaveErrorResponseExceptionImpl.java, bundles/org.openhab.core.io.transport.modbus/src/test/java/org/openhab/core/io/transport/modbus/test/ModbusSlaveErrorResponseExceptionImplTest.java
When modbus slave responds with explicit error code, we communicate the
user what it means. E.g. error code 2 refers to "Illegal Data Access".
In addition, fixed some simple typos discussed in
https://github.com/openhab/openhab-addons/issues/8973#issuecomment-922232756
=> [modbus] Improved error messages, fixed typos

bundles/org.openhab.core.io.rest.core/src/test/java/org/openhab/core/io/rest/core/internal/channel/ChannelTypeResourceTest.java, bundles/org.openhab.core/src/test/java/org/openhab/core/internal/items/ItemBuilderTest.java, itests/org.openhab.core.io.rest.core.tests/src/main/java/org/openhab/core/io/rest/core/internal/item/ItemResourceOSGiTest.java, itests/org.openhab.core.io.rest.core.tests/src/main/java/org/openhab/core/io/rest/core/internal/profile/ProfileTypeResourceTest.java, itests/org.openhab.core.model.thing.tests/src/main/java/org/openhab/core/model/thing/test/GenericItemChannelLinkProviderJavaTest.java, itests/org.openhab.core.model.thing.tests/src/main/java/org/openhab/core/model/thing/test/hue/GenericThingProviderTest.java, itests/org.openhab.core.model.thing.tests/src/main/java/org/openhab/core/model/thing/test/hue/GenericThingProviderTest3.java, itests/org.openhab.core.model.thing.testsupport/src/main/java/org/openhab/core/model/thing/testsupport/hue/TestHueChannelTypeProvider.java, itests/org.openhab.core.tests/src/main/java/org/openhab/core/items/ItemRegistryImplTest.java, itests/org.openhab.core.thing.tests/src/main/java/org/openhab/core/thing/binding/ThingFactoryTest.java, itests/org.openhab.core.thing.tests/src/main/java/org/openhab/core/thing/internal/ThingManagerOSGiJavaTest.java, itests/org.openhab.core.thing.tests/src/main/java/org/openhab/core/thing/internal/ThingManagerOSGiTest.java, itests/org.openhab.core.thing.xml.tests/src/main/java/org/openhab/core/thing/xml/test/ThingTypesTest.java
This prevents typos and using the constants makes it easier to find out what other items types are accepted.
It also makes it easier to see that these values are item types and not labels or descriptions.
=> Use CoreItemFactory item type constants in tests

features/karaf/openhab-tp/src/main/feature/feature.xml
Update to latest Netty which has 2 security fixes in it.
Change log here:
https://netty.io/news/2021/09/09/4-1-68-Final.html
Also this PR is also needed see here:
https://github.com/openhab/openhab-addons/pull/11326
Signed-off-by: Matthew Skinner <matt@pcmus.com>
=> Bump Netty.io library to 4.1.68.Final

bundles/org.openhab.core.automation.module.script/src/main/java/org/openhab/core/automation/module/script/internal/defaultscope/ScriptBusEvent.java
Currently the item name is missing and it is nearly impossible to find the cause of the warning as there is no hint which rule sent the wrong update/command. Now at least the item name is shown which helps to identify the offending rule.
=> add item name to ScriptBusEvent log messages

bom/test/pom.xml
There should only be one SLF4J binding used for logging and we already use slf4j-simple.
This fixes the following warning when running unit tests:
```
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/home/wouter/.m2/repository/org/slf4j/slf4j-simple/1.7.32/slf4j-simple-1.7.32.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/home/wouter/.m2/repository/ch/qos/logback/logback-classic/1.2.3/logback-classic-1.2.3.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.SimpleLoggerFactory]
```
=> Exclude logback-classic from org.apache.aries.jax.rs.whiteboard

bundles/org.openhab.core.thing/src/test/java/org/openhab/core/thing/internal/profiles/TimestampOffsetProfileTest.java
- Removed failing timestamp offset test. This test is is covered in the following lines by applying the timezone too.
=> [profile] Removed failing timestamp offset test

bundles/org.openhab.core.io.net/src/main/java/org/openhab/core/io/net/http/internal/WebClientFactoryImpl.java, bundles/org.openhab.core.io.net/src/test/java/org/openhab/core/io/net/http/internal/WebClientFactoryImplTest.java
* Update the `WebClientFactoryImpl` so it no longer uses a deprecated `WebSocketClient` constructor.
* Use a workaround so `WebClientFactoryImplTest.tearDown()` cannot block forever when the commonWebSocketClient is stopped when it has not yet been fully started.
---
When the commonWebSocketClient has not yet fully started, this exception occurs when stopping it:
```
[OH-httpClient-common-20] WARN org.eclipse.jetty.io.ManagedSelector - java.nio.channels.ClosedSelectorException
```
When this exception occurs, the blocking thread would have a stack trace like this:
```
"main" #1 prio=5 os_prio=0 cpu=2079,48ms elapsed=270,59s tid=0x00007eff6c029000 nid=0xbfb20 waiting on condition  [0x00007eff729a0000]
java.lang.Thread.State: WAITING (parking)
at …
```
=> WebClientFactoryImpl deprecation and blocking test fixes

bundles/org.openhab.core.config.discovery.mdns/src/main/java/org/openhab/core/config/discovery/mdns/internal/MDNSDiscoveryService.java, bundles/org.openhab.core.config.discovery.upnp/src/main/java/org/openhab/core/config/discovery/upnp/internal/UpnpDiscoveryService.java, bundles/org.openhab.core.config.discovery/src/main/java/org/openhab/core/config/discovery/AbstractDiscoveryService.java, bundles/org.openhab.core.config.discovery/src/test/java/org/openhab/core/config/discovery/AbstractDiscoveryServiceTest.java
=> mDNS / UPnP discovery internationalization

bundles/org.openhab.core/src/main/java/org/openhab/core/service/WatchQueueReader.java
Fix NPE in WatchQueueReader. The NPE would cause the watch queue to stop being watched, and script files will no longer be reloaded when changed.
This seems to occur when files were created and quickly removed within the watched directories. It should resolve #2537 and #2535
=> Fix NPE in WatchQueueReader

bundles/org.openhab.core/src/main/java/org/openhab/core/i18n/AbstractI18nException.java, bundles/org.openhab.core/src/main/java/org/openhab/core/i18n/CommunicationException.java, bundles/org.openhab.core/src/main/java/org/openhab/core/i18n/ConfigurationException.java, bundles/org.openhab.core/src/main/java/org/openhab/core/i18n/ConnectionException.java, bundles/org.openhab.core/src/main/java/org/openhab/core/i18n/I18nException.java, bundles/org.openhab.core/src/test/java/org/openhab/core/internal/i18n/I18nExceptionTest.java
=> New exception class that incorporates support for internationalization

bundles/org.openhab.core.automation.module.script/src/main/java/org/openhab/core/automation/module/script/LifecycleScriptExtensionProvider.java
LifecycleScriptExtensionProvider's Disposable interface is package-private which caused scriptry engines, e.g. JRuby unable to create a hook needed by the LifecycleTracker.addDisposeHook(). The hook is implemented from the `Disposable` functional interface which was not public.
Just making Disposable public without moving LifecycleScriptExtensionProvide out of the internal package wasn't enough.
Resolve #2287 
See https://github.com/boc-tothefuture/openhab-jruby/issues/366
=> Make LifecycleScriptExtensionProvider and its Disposable interface public

bom/openhab-core/pom.xml, bundles/org.openhab.core.config.discovery.usbserial.ser2net/.classpath, bundles/org.openhab.core.config.discovery.usbserial.ser2net/.project, bundles/org.openhab.core.config.discovery.usbserial.ser2net/NOTICE, bundles/org.openhab.core.config.discovery.usbserial.ser2net/pom.xml, bundles/org.openhab.core.config.discovery.usbserial.ser2net/src/main/java/org/openhab/core/config/discovery/usbserial/ser2net/internal/Ser2NetUsbSerialDiscovery.java, bundles/org.openhab.core.config.discovery.usbserial.ser2net/src/test/java/org/openhab/core/config/discovery/usbserial/ser2net/internal/Ser2NetUsbSerialDiscoveryTest.java, bundles/org.openhab.core.config.discovery.usbserial/src/main/java/org/openhab/core/config/discovery/usbserial/internal/UsbSerialDiscoveryService.java, bundles/org.openhab.core.config.serial/src/main/java/org/openhab/core/config/serial/internal/SerialConfigOptionProvider.java, bundles/org.openhab.core.config.serial/src/test/java/org/openhab/core/config/serial/internal/SerialConfigOptionProviderTest.java, bundles/org.openhab.core.io.transport.serial.rxtx.rfc2217/src/main/java/org/openhab/core/io/transport/serial/rxtx/rfc2217/internal/RFC2217PortProvider.java, bundles/pom.xml, features/karaf/openhab-core/src/main/feature/feature.xml
* Add support for using multiple UsbSerialDiscovery services
* Add Ser2NetUsbSerialDiscovery that can use mDNS to discover ser2net RFC2217 serial ports
* Use discovered USB ports in SerialConfigOptionProvider
mDNS discovery is supported in ser2net 4.3.0 and newer.
E.g. you can install a ser2net version that provides this using APT in Ubuntu 21.04 and Debian 11.
Example ser2net YAML configuration that allows a serial port to be discovered using mDNS discovery:
```
%YAML 1.1
---
connection: &con01
accepter: telnet(rfc2217),tcp,2222
connector: serialdev,/dev/ttyUSB0
options:
mdns: true
mdns-sysattrs: true
mdns-name: devicename
```
Closes #1511
=> Add ser2net mDNS USB serial discovery

bundles/org.openhab.core/src/main/java/org/openhab/core/common/ThreadPoolManager.java, bundles/org.openhab.core/src/test/java/org/openhab/core/common/ThreadPoolManagerTest.java
Right now shared thread pools can be shut down, which leads to many problems (as described in #760 and #2465).
This PR fixes it by overriding shutdown and shutdownNow methods on wrapper classes around thread pools returned from factory methods on ThreadPoolManager, preventing shutdown and logging errors to help find out what addon calls them. This should not cause any issues since shared pools are never shut down by framework.
Closes #760
=> Prevent shutdown of shared thread pool

bom/openhab-core-index/pom.xml, bom/runtime-index/pom.xml, bom/test-index/pom.xml
Looks like only the POM dependencies are used by the indexer, so the JAR is unused and useless as this warning correctly indicates when you build them:
```
[WARNING] JAR will be empty - no content was marked for inclusion!
```
=> Use POM packaging with index BOMs

bom/runtime/pom.xml, features/karaf/openhab-tp/src/main/feature/feature.xml
Updates Jackson from 2.12.3 to 2.12.5.
For all bug fixes, see:
* https://github.com/FasterXML/jackson/wiki/Jackson-Release-2.12.4
* https://github.com/FasterXML/jackson/wiki/Jackson-Release-2.12.5
=> Update Jackson to 2.12.5

bundles/org.openhab.core.addon.marketplace.karaf/src/main/java/org/openhab/core/addon/marketplace/karaf/internal/community/CommunityKarafAddonHandler.java, bundles/org.openhab.core.addon.marketplace/src/main/java/org/openhab/core/addon/marketplace/MarketplaceBundleInstaller.java
The current implementation could result in collision of file-path and failed in determining the installation status if other AddonProviders re-use the marketplace addon handlers.
=> [marketplace] avoid collisions with multiple AddonProviders

bundles/org.openhab.core.model.script/src.moved/test/java/org/openhab/core/model/script/internal/actions/TimerImplTest.java, bundles/org.openhab.core.model.script/src/org/openhab/core/model/script/actions/Timer.java, bundles/org.openhab.core.model.script/src/org/openhab/core/model/script/internal/actions/TimerImpl.java
I found the need for Timer.isCancelled() inside a long running timer that self-reschedules itself.
Example:
```java
var timer = null
rule "Long running timer"
when
System started
then
timer = createTimer(now.plusSeconds(1), [|
downloadFile() // do something that takes a long time here, e.g. a http get from a large source            
timer.reschedule(now.plusSeconds(1))
])
end
rule "Cancel the timer"
when
Item Switch1 received command ON
then
timer.cancel()
end
```
When Switch1 received a command ON while `downloadFile()` is executing, the timer got cancelled, but the currently running task is still continuing, it will reschedule the timer and therefore the timer continues to run despite having been "cancelled".
In this case, the timer code can check with `isCancelled()` before calling …
=> Add Timer.isCancelled() method

bundles/org.openhab.core.io.rest.auth/src/main/java/org/openhab/core/io/rest/auth/internal/ExpiringUserSecurityContextCache.java, bundles/org.openhab.core.io.rest.auth/src/test/java/org/openhab/core/io/rest/auth/internal/ExpiringUserSecurityContextCacheTest.java
The issue occurs when expired entries are removed from the cache.
Also adds some unit tests in which the same issue could be reproduced.
Fixes #2528
=> Fix ConcurrentModificationException in ExpiringUserSecurityContextCache

.github/workflows/ci-build.yml
This new version fixes a few regressions, see:
https://issues.apache.org/jira/secure/ReleaseNote.jspa?projectId=12316922&version=12350685
=> Use Maven 3.8.4 in GHA CI builds

pom.xml
When the plugin dependency is managed you can also use the plugin without adding GAV parameters to commands.
E.g. it allows for using it with:
```
mvn i18n:generate-default-translations
```
Related to #2544
=> Add i18n-maven-plugin dependency

bundles/org.openhab.core.model.rule/src/org/openhab/core/model/rule/jvmmodel/RulesJvmModelInferrer.xtend, bundles/org.openhab.core.model.script.runtime/src/org/openhab/core/model/script/runtime/internal/engine/DSLScriptEngine.java, bundles/org.openhab.core.model.script/src/org/openhab/core/model/script/jvmmodel/ScriptJvmModelInferrer.xtend
- Added variable 'triggeringChannel' to DSL rules
Closes #2143 
=> [DSL] Added variable 'triggeringChannel' to DSL rules

pom.xml
Reverts openhab/openhab-core#2584 because it makes the release build fail.
=> Revert "Add i18n-maven-plugin dependency"

bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/handler/TriggerHandlerCallback.java, bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/TriggerHandlerCallbackImpl.java
- Fixed nullness anotations for `TriggerHandlerCallback`
It looks like I made a wrong assumption regarding the `getScheduler()` method of `TriggerHandlerCallback` in https://github.com/openhab/openhab-core/pull/2586.
=> Fixed nullness anotations for TriggerHandlerCallback

bundles/org.openhab.core.ui/src/main/java/org/openhab/core/ui/internal/items/ItemUIRegistryImpl.java
- Added item name to error message
There are three places logging the item name and one does not.
```
2021-12-07 14:38:13.858 [ERROR] [ui.internal.items.ItemUIRegistryImpl] - Cannot retrieve item for widget org.openhab.core.model.sitemap.sitemap.Text
2021-12-07 14:38:13.861 [ERROR] [ui.internal.items.ItemUIRegistryImpl] - Cannot retrieve item 'sensorTerraceEnergyCostsProfile' for widget org.openhab.core.model.sitemap.sitemap.Text
2021-12-07 14:38:13.864 [ERROR] [ui.internal.items.ItemUIRegistryImpl] - Cannot retrieve item 'sensorTerraceEnergyCostsProfile' for widget org.openhab.core.model.sitemap.sitemap.Text
2021-12-07 14:38:13.868 [ERROR] [ui.internal.items.ItemUIRegistryImpl] - Cannot retrieve item 'sensorTerraceEnergyCostsProfile' for widget org.openhab.core.model.sitemap.sitemap.Text …
```
=> [UI] Added item name to error message

bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/internal/service/ConfigurableServiceResource.java, itests/org.openhab.core.io.rest.core.tests/src/main/java/org/openhab/core/io/rest/core/internal/service/ConfigurableServiceResourceOSGiTest.java
Most RESTResources already use the LocaleService to get the locale based on the Accept-Language header and use the system locale only as fallback.
Because the ConfigurableServiceResource does not do this, it results in mixed up languages whenever your browser locale is not the same as the configured system locale.
See:
* https://community.openhab.org/t/language-support-question-regional-settings-language-vs-browser-language/128010
* https://github.com/openhab/openhab-webui/issues/1083
=> Use Accept-Language header for locale in ConfigurableServiceResource

bom/runtime/pom.xml, bom/test/pom.xml, features/karaf/openhab-tp/src/main/feature/feature.xml, itests/org.openhab.core.io.rest.core.tests/itest.bndrun
It causes unneccessary bundle refreshes whenever add-ons are installed/uninstalled.
As a result the UI does not get properly notified of installation changes.
Fixes #2580
Reverts the Aries JAX-RS Whiteboard upgrade of #2532
=> Downgrade Aries JAX-RS Whiteboard from 2.0.1 to 2.0.0

bundles/org.openhab.core.addon.marketplace/src/main/java/org/openhab/core/addon/marketplace/internal/community/CommunityBlockLibaryAddonHandler.java, bundles/org.openhab.core.addon.marketplace/src/main/java/org/openhab/core/addon/marketplace/internal/community/CommunityMarketplaceAddonService.java
Related to https://github.com/openhab/openhab-webui/pull/1225.
This add-on handler supports installing block libraries in the
UIComponentRegistry, `ui:blocks` namespace.
It is very similar to the CommunityUIWidgetAddonHandler, as the format
is the same, so are the features and implementation, the only
differences being:
- Supported content type: `application/vnd.openhab.uicomponent;type=blocks`
(vs. `application/vnd.openhab.uicomponent;type=widget`)
- Discourse category nb.: 76 (vs. 75)
- Inferred Add-on type: "automation" (vs. "ui")
=> [marketplace] Add add-on handler for block libraries

bundles/org.openhab.core.automation.module.script/src/main/java/org/openhab/core/automation/module/script/internal/defaultscope/DefaultScriptScopeProvider.java, bundles/org.openhab.core.model.script/src/org/openhab/core/model/script/scoping/ScriptImplicitlyImportedTypes.java
- Added basic time-related classes for usage in script and rules
This allows to use DateTime functions a lot easier for users without defining additional imports. We have public methods in different types which makes use of these classes e.g.
https://github.com/openhab/openhab-core/blob/a9504bfced5054bb8c7a864876f66df27c69c661/bundles/org.openhab.core/src/main/java/org/openhab/core/library/types/DateTimeType.java#L170
https://github.com/openhab/openhab-core/blob/a9504bfced5054bb8c7a864876f66df27c69c661/bundles/org.openhab.core.model.script/src/org/openhab/core/model/script/actions/Timer.java#L76
`org.joda.time` API has a method `DateTime.now().withTimeAtStartOfDay()` which was used by many users. The replacement is `ZonedDateTime.now().truncatedTo(ChronoUnit.DAYS)`.
`Duration` class …
=> [automation] Added basic time-related classes for usage in script and rules

bundles/org.openhab.core.automation.module.script.rulesupport/src/main/java/org/openhab/core/automation/module/script/rulesupport/internal/loader/DefaultScriptFileWatcher.java, bundles/org.openhab.core.automation.module.script.rulesupport/src/main/java/org/openhab/core/automation/module/script/rulesupport/internal/loader/ScriptLibraryWatcher.java, bundles/org.openhab.core.automation.module.script.rulesupport/src/main/java/org/openhab/core/automation/module/script/rulesupport/loader/DependencyTracker.java, bundles/org.openhab.core.automation.module.script.rulesupport/src/main/java/org/openhab/core/automation/module/script/rulesupport/loader/ScriptFileReference.java, bundles/org.openhab.core.automation.module.script.rulesupport/src/main/java/org/openhab/core/automation/module/script/rulesupport/loader/ScriptFileWatcher.java, bundles/org.openhab.core.automation.module.script.rulesupport/src/test/java/org/openhab/core/automation/module/script/rulesupport/loader/ScriptFileWatcherTest.java
Extracted reusable parts of script watching to allow language-specific instantiations:
- Moved to non-internal package
- Extracted logic into non-osgi-component classes
- Added back in basic osgi-component versions
This change is specifically to prepare for JS-specific scripts to operate as standard NodeJS which is slightly different to the existing openHAB mechanism, as discussed with @kaikreuzer. No functionality change to core with this change, except the creation of the script directory if not already present. PR to use this functionality in openhab-addons to follow. 
=> [automation] Script file watchers now reusable for language-specific versions

bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/util/ReferenceResolver.java, bundles/org.openhab.core.automation/src/test/java/org/openhab/core/automation/util/ReferenceResolverUtilTest.java, itests/org.openhab.core.automation.integration.tests/src/main/resources/OH-INF/automation/templates/SimpleTestTemplate.json, itests/org.openhab.core.automation.integration.tests/src/main/resources/OH-INF/automation/templates/TestTemplateRuleWithReferences.json, itests/org.openhab.core.automation.integration.tests/src/main/resources/OH-INF/automation/templates/TestTemplateWithCompositeModules.json
Fixes #2510.
This changes the placeholder syntax used by the reference resolver notably
used in rule templates from `${reference}` to `{{reference}}`.
The former syntax is also used by other languages, notably JavaScript's
template strings, and therefore writing rule templates including JavaScript
code with template strings wouldn't behave as expected.
This also fixes a bug identified in #2510 where you couldn't have a
single closing brace before the start of the first placeholder - which
could more easily happen than having two closing braces.
=> Change the syntax for references in automation modules configuration

bundles/org.openhab.core.automation.module.script/src/main/java/org/openhab/core/automation/module/script/internal/provider/ScriptModuleTypeProvider.java
Use the mime types provided by the ScriptEngineFactory and not the underlying script engines they provide. This allows mutliple versions of script engines to co-exist, like Nashorn and GraalVM .
Signed-off-by: Dan Cunningham <dan@digitaldan.com>
=> Use the mime types provided by the ScriptEngineFactory

bundles/org.openhab.core.addon.marketplace.karaf/src/main/java/org/openhab/core/addon/marketplace/karaf/internal/community/CommunityKarafAddonHandler.java, bundles/org.openhab.core.addon.marketplace/src/main/java/org/openhab/core/addon/marketplace/MarketplaceBundleInstaller.java
Fixes #2614 
Unfortunately the (full) addonId created from a path missed the addonId when the addon was installed from the community marketplace.
=> [marketplace] fix re-installation of marketplace addons

bundles/org.openhab.core.addon.marketplace/src/main/java/org/openhab/core/addon/marketplace/internal/json/JsonAddonService.java
This fixes a regression introduced by #2605 which results in addon installation exiting early if the first `MarketplaceAddonHandler` does not support the addon.
=> [addonservices] fix JsonAddonService

bundles/org.openhab.core.automation.module.script/src/main/java/org/openhab/core/automation/module/script/internal/provider/ScriptModuleTypeProvider.java
As discussed in https://github.com/openhab/openhab-addons/issues/11818.
This should select `application/x-python` for Jython (instead of `application/python` currently)
and allow other script engines to advertise their MIME type:
- JRuby: `application/x-ruby`
- Groovy: `application/x-groovy`
=> Improve logic to choose a script engine preferred MIME type

bundles/org.openhab.core.config.discovery.mdns/src/main/java/org/openhab/core/config/discovery/mdns/MDNSDiscoveryParticipant.java
Signed-off-by: Jacob Laursen <jacob-github@vindvejr.dk>
See:
- https://www.openhab.org/javadoc/latest/org/openhab/core/config/discovery/mdns/mdnsdiscoveryparticipant#createResult(javax.jmdns.ServiceInfo)
- https://www.openhab.org/javadoc/latest/org/openhab/core/config/discovery/mdns/mdnsdiscoveryparticipant#getThingUID(javax.jmdns.ServiceInfo)
=> [discovery.mdns] MDNSDiscoveryParticipant: Fix wrong argument names in Javadoc.

bundles/org.openhab.core.config.discovery.mdns/src/main/java/org/openhab/core/config/discovery/mdns/MDNSDiscoveryParticipant.java, bundles/org.openhab.core.config.discovery.mdns/src/main/java/org/openhab/core/config/discovery/mdns/internal/MDNSDiscoveryService.java
**BACKGROUND**
Some types of OpenHAB bindings have devices that can sometimes be a bit late in sending their mDNS renewal announcements, which means that such devices are repeatedly removed from, and (re)added to, the InBox. This leads to confusion in the UI, and repeated logger messages. This is an exact analog to the UPNP Discovery issue that was solved by https://github.com/openhab/openhab-core/pull/2144
**SOLUTION**
The solution is an exact analog to the solution in https://github.com/openhab/openhab-core/pull/2144
Resolves #1835
**DOCUMENTATION**
The binding developer guide will also be updated via this PR https://github.com/openhab/openhab-docs/pull/1708
Signed-off-by: Andrew Fiddian-Green software@whitebear.ch
=> [discovery.mdns] Devices may apply a grace period for removal from the Inbox

features/karaf/openhab-tp/src/main/feature/feature.xml
Nettys news/change log is here:
https://netty.io/news/2021/12/13/4-1-72-Final.html
Contains an update to log4j2 2.15.0 to fix security issue.
Also have made a PR here for the addons repo changes..
https://github.com/openhab/openhab-addons/pull/11826
Signed-off-by: Matthew Skinner <matt@pcmus.com>
=> Bump netty to 4.1.72.Final for log4j2 2.15.0 fix

bundles/org.openhab.core.io.net/src/main/java/org/openhab/core/io/net/http/PEMTrustManager.java, bundles/org.openhab.core.io.net/src/main/java/org/openhab/core/io/net/http/internal/ExtensibleTrustManagerImpl.java
- Added a PEMTrustManager to deal with different PEM files (e.g. self-signed or global CA certificates)
=> [tls] Add a PEMTrustManager to deal with different PEM files (e.g. self-signed or global CA certificates)

bundles/org.openhab.core.io.rest.sse/src/main/java/org/openhab/core/io/rest/sse/SseResource.java
Fixes https://github.com/openhab/openhab-core/issues/2651
=> Make SSEResource robust against missing parameters

bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/internal/GsonMessageBodyWriter.java
- Prevent errors in log when there is a connection timeout
We already added a block to catch exceptions in https://github.com/openhab/openhab-core/pull/2049. This PR makes it even harder.
```
2021-12-25 14:39:02.618 [ERROR] [rg.apache.cxf.jaxrs.utils.JAXRSUtils] - Problem with writing the data, class org.openhab.core.io.rest.Stream2JSONInputStream, ContentType: application/json
2021-12-25 14:39:02.623 [ERROR] [internal.JSONResponseExceptionMapper] - Unexpected exception occurred while processing REST request.
java.io.IOException: java.util.concurrent.TimeoutException: Idle timeout expired: 30000/30000 ms
at org.eclipse.jetty.util.SharedBlockingCallback$Blocker.block(SharedBlockingCallback.java:257) ~[bundleFile:9.4.43.v20210629]
at …
```
=> Prevent errors in log when there is a connection timeout

bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/internal/JSONResponseExceptionMapper.java
- Prevent errors in log when client closes the HTTP connection
See https://github.com/openhab/openhab-distro/issues/1188#issuecomment-1002745172 and https://github.com/openhab/openhab-core/pull/2049.
@openhab/core-maintainers Please tell me your opinion.
=> Prevent errors in log when client closes the HTTP connection

bundles/org.openhab.core.addon.marketplace/src/main/java/org/openhab/core/addon/marketplace/internal/community/CommunityMarketplaceAddonService.java, bundles/org.openhab.core.addon.marketplace/src/main/java/org/openhab/core/addon/marketplace/internal/json/JsonAddonService.java
=> [addonservices] allow offline mode

bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/internal/persistence/PersistenceResource.java, bundles/org.openhab.core.persistence/src/main/java/org/openhab/core/persistence/ModifiablePersistenceService.java
If PRs are created to implement this interface, it would be better if we can prevent the propagation of old APIs like Date.
Related to:
* https://github.com/openhab/openhab-addons/pull/11922
* https://github.com/openhab/openhab-addons/pull/11923
* https://github.com/openhab/openhab-core/issues/2618#issuecomment-1003544762
=> Use ZonedDateTime instead of Date in ModifiablePersistenceService interface

bundles/org.openhab.core.addon.marketplace/src/main/java/org/openhab/core/addon/marketplace/internal/community/CommunityBlockLibaryAddonHandler.java, bundles/org.openhab.core.addon.marketplace/src/main/java/org/openhab/core/addon/marketplace/internal/community/CommunityUIWidgetAddonHandler.java
Related to https://community.openhab.org/t/error-installing-widgets-from-community-in-user-interfaces/128729/16
When the locale is not English the timestamp might fail to be deserialized into a Date:
```
2022-01-02 21:01:42.260 [ERROR] [munity.CommunityUIWidgetAddonHandler] - Unable to parse YAML: Cannot deserialize value of type `java.util.Date` from String "Oct 2, 2021, 9:24:59 PM": not a valid representation (error: Failed to parse Date value 'Oct 2, 2021, 9:24:59 PM': Unparseable date: "Oct 2, 2021, 9:24:59 PM")
at [Source: (StringReader); line: 36, column: 12] (through reference chain: org.openhab.core.ui.components.RootUIComponent["timestamp"])
2022-01-02 21:01:42.261 [ERROR] [munity.CommunityUIWidgetAddonHandler] - Widget from marketplace is invalid: Unable to parse YAML
```
=> Force English locale to parse marketplace UI components timestamp

bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/internal/profiles/SystemHysteresisStateProfile.java, bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/internal/profiles/SystemOffsetProfile.java, bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/internal/profiles/SystemRangeStateProfile.java, bundles/org.openhab.core.thing/src/test/java/org/openhab/core/thing/internal/profiles/SystemHysteresisStateProfileTest.java, bundles/org.openhab.core.thing/src/test/java/org/openhab/core/thing/internal/profiles/SystemOffsetProfileTest.java, bundles/org.openhab.core.thing/src/test/java/org/openhab/core/thing/internal/profiles/SystemRangeStateProfileTest.java
- Do not log a warning if `QuantityState` has unit `AbstractUnit.ONE`
I added this check to deal with dimensionless `QuantityTypes` without unit (internally `AbstractUnit.ONE`) because for them it is not possible to define a unit in the compare condition as the unit symbol is an empty string.
=> [profiles] Do not log a warning if QuantityState has unit AbstractUnit.ONE

bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/RuleEngineImpl.java
- Align parsing of startlevel config
We assume that configuration values are `BigDecimal` in `SystemTriggerHandler` thus it might make sense to align the parsing in the `RuleEngine`.
https://github.com/openhab/openhab-core/blob/0bdaeef789a52d637134800f3dbaf4827b543c60/bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/module/handler/SystemTriggerHandler.java#L62
Otherwise it might happen that we see a warning in the log:
```
2022-01-03 12:35:24.420 [WARN ] [e.automation.internal.RuleEngineImpl] - Configuration '80.0' is not a valid start level!
```
Extract from Json Storage:
```json
{
"e8c39a6060": {
"class": "org.openhab.core.automation.dto.RuleDTO",
"value": {
"triggers": [
{
"id": "1",
"configuration": {
"startlevel": 80.0
},
"type": …
```
=> [automation] Align parsing of startlevel config

bundles/org.openhab.core.audio/src/main/java/org/openhab/core/audio/AudioFormat.java, bundles/org.openhab.core.audio/src/main/java/org/openhab/core/audio/AudioWaveUtils.java, bundles/org.openhab.core.audio/src/main/java/org/openhab/core/audio/FileAudioStream.java, bundles/org.openhab.core.audio/src/main/java/org/openhab/core/audio/internal/javasound/AudioPlayer.java, bundles/org.openhab.core.audio/src/main/java/org/openhab/core/audio/utils/AudioWaveUtils.java
This pull request aims to replace hardcoded value by values extracted from the wav file itself, for the System speaker audio sink to play correctly some files.
Things I'm not sure about : 
- I added a new AudioFormat constructor, instead of adding a parameter to the already existing one, because I'm not confortable with introducing a breaking change.
- The values I compute (bitrate, framerate and framesize). I'm not proficient in audio, and honestly I don't really know what I'm doing. But it works when I test it. If someone using other audio sinks (compatible with WAV) could test it would be great.
Signed-off-by: Gwendal Roulleau <gwendal.roulleau@gmail.com>
=> [audio] Fix hardcoded value for WAV file

bundles/org.openhab.core.automation.module.script.rulesupport/src/main/java/org/openhab/core/automation/module/script/rulesupport/loader/ScriptFileWatcher.java
… to true
This matters as subclasses can override this behaviour and it was previously being ignored upon startup (only).
=> ScriptFileWatcher subdirectory loading upon startup no longer hardcoded

bundles/org.openhab.core.semantics/model/generateTagClasses.groovy, bundles/org.openhab.core.semantics/pom.xml, pom.xml, tools/archetype/binding/src/main/resources/META-INF/archetype-post-generate.groovy
Updates the year in a few groovy file headers that were missed in #2671.
=> Update groovy license headers to 2022

bundles/org.openhab.core.audio/src/main/java/org/openhab/core/audio/internal/javasound/AudioPlayer.java, bundles/org.openhab.core.audio/src/main/java/org/openhab/core/audio/utils/AudioWaveUtils.java
A 'clac' can be heard at the beginning of a wav file when playing on the javasound sink.
This is because the code playing the sound targets PCM. But a WAV file has an additional header (fmt). When the code tries to play this header as if it was actual sound, it outputs a "pop" noise.
This bug was first encoutered when [playing WAV from the Google TTS](https://community.openhab.org/t/oh3-google-tts-only-white-noise/112714/35), and also in my tests with the Pico TTS, and with the play action from a wav file in the sound directory.
With the fix in this PR, the code consumes (at most) 400 + 2 bytes (if it is a wav file) by trying to get to a "magic" packet that marks the beginning of the real PCM data.
I put the removal code in an utility class because every audio sink playing PCM could …
=> [audio] Remove 'clac' noise when playing wave (javasound)

bundles/org.openhab.core.addon.marketplace/src/main/java/org/openhab/core/addon/marketplace/internal/community/CommunityMarketplaceAddonService.java, bundles/org.openhab.core.addon.marketplace/src/main/java/org/openhab/core/addon/marketplace/internal/json/JsonAddonService.java
=> Fix NPE of AddonServices during startup

bundles/org.openhab.core.config.core/src/main/java/org/openhab/core/config/core/status/ConfigStatusCallback.java, bundles/org.openhab.core.config.core/src/main/java/org/openhab/core/config/core/status/ConfigStatusInfo.java, bundles/org.openhab.core.config.core/src/main/java/org/openhab/core/config/core/status/ConfigStatusMessage.java, bundles/org.openhab.core.config.core/src/main/java/org/openhab/core/config/core/status/ConfigStatusService.java, bundles/org.openhab.core.config.core/src/main/java/org/openhab/core/config/core/status/events/ConfigStatusEventFactory.java, bundles/org.openhab.core.config.core/src/main/java/org/openhab/core/config/core/status/events/ConfigStatusInfoEvent.java, bundles/org.openhab.core.config.core/src/test/java/org/openhab/core/config/core/status/ConfigStatusInfoTest.java, bundles/org.openhab.core.config.core/src/test/java/org/openhab/core/config/core/status/ConfigStatusServiceTest.java
- Suppress `ConfigStatusInfoEvent` if list of `ConfigStatusMessage`s is empty
=> [config] Added nullness annotations and suppress 'ConfigStatusInfoEvent' if list of 'ConfigStatusMessage's is empty

bundles/org.openhab.core.automation.module.script/src/main/java/org/openhab/core/automation/module/script/internal/ScriptEngineManagerImpl.java
This change:
- Prevents scripts (and their associated engines) from replacing themselves without proper unloading
- Closes any engines with implement `AutoCloseable`
(Required to fix https://github.com/openhab/openhab-addons/issues/11952)
=> [automation] Script engines now unloaded if replaced, and closed if AutoCloseable

bundles/org.openhab.core.config.core/src/main/java/org/openhab/core/config/core/internal/validation/ConfigDescriptionValidatorImpl.java, bundles/org.openhab.core.config.core/src/test/java/org/openhab/core/config/core/internal/validation/ConfigDescriptionValidatorTest.java
The `ConfigDescriptionValidator` implementation did not iterate over the content of the `ConfigDescription` but over the content of the provided configuration. As a result parameters that were missing (and not just set to `null`) are not detected.
Tests results are re-ordered due to fixed typos.
=> fix broken config validation for required parameters

bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/module/handler/ItemStateConditionHandler.java, bundles/org.openhab.core.automation/src/test/java/org/openhab/core/automation/internal/module/handler/ItemStateConditionHandlerTest.java
- Log warning for equals condition for `DecimalType`s and `QuantityType`s
Closes #2624 
=> [automation] Log warning for equals condition for DecimalTypes and QuantityTypes

bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/internal/persistence/PersistenceResource.java, bundles/org.openhab.core.io.rest.core/src/test/java/org/openhab/core/io/rest/core/internal/persistence/PersistenceResourceTest.java, bundles/org.openhab.core.persistence/src/main/java/org/openhab/core/persistence/FilterCriteria.java
- Do not reuse `FilterCriteria` instance for more than one query
Closes #2665
=> [rest] Do not reuse FilterCriteria instance for more than one query

bundles/org.openhab.core.model.rule.runtime/src/org/openhab/core/model/rule/runtime/internal/DSLRuleProvider.java, bundles/org.openhab.core.model.rule/src/org/openhab/core/model/rule/Rules.xtext
This implements a way to trigger dsl-based rules on various start levels, like it is already possible with ui-based rules.
=> "System reached start level XX" trigger for DSL rules

bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/internal/ThingManagerImpl.java, bundles/org.openhab.core.thing/src/main/resources/OH-INF/i18n/SystemThingStatusInfos.properties, itests/org.openhab.core.thing.tests/src/main/java/org/openhab/core/thing/binding/BindingBaseClassesOSGiTest.java, itests/org.openhab.core.thing.tests/src/main/java/org/openhab/core/thing/internal/ThingManagerOSGiTest.java
=> enable config validation for thing creation and update

tools/archetype/binding/src/main/resources/archetype-resources/README.md, tools/archetype/binding/src/main/resources/archetype-resources/src/main/java/internal/__bindingIdCamelCase__Configuration.java, tools/archetype/binding/src/main/resources/archetype-resources/src/main/java/internal/__bindingIdCamelCase__Handler.java, tools/archetype/binding/src/main/resources/archetype-resources/src/main/resources/OH-INF/thing/thing-types.xml
This addresses some review findings for new addons by making some small improvements to the binding skeleton.
- put each sentence in a seperate line
- add note that only PNG images are supported. See https://github.com/openhab/openhab-addons/pull/11116#discussion_r775838188
- add examples to "Supported Things"
- add RW column to example Channel table
- add advanced and default config value
- add note that textual config examples are mandatory
- make .sitemap example optional (see small internal discussion)
- put emphasis on initialize() shall return quickly
- add note about logging to INFO
- fix compiler warning
@openhab/add-ons-maintainers 
=> [skeleton] Add Thing config table to readme; minor improvements

bundles/org.openhab.core.automation.module.script/src/main/java/org/openhab/core/automation/module/script/internal/ScriptEngineManagerImpl.java
Remove script engines from managed once they are closed. It looks like this is a longstanding bug that was only recently uncovered by https://github.com/openhab/openhab-core/pull/2681.
=> Script Engines now removed from manager when closed

bundles/org.openhab.core.config.core/src/main/java/org/openhab/core/config/core/ConfigParser.java, bundles/org.openhab.core.config.core/src/main/java/org/openhab/core/config/core/Configuration.java, bundles/org.openhab.core.config.core/src/test/java/org/openhab/core/config/core/ConfigParserTest.java, bundles/org.openhab.core.config.core/src/test/java/org/openhab/core/config/core/ConfigurationTest.java
Closes #2700 
Some points are still open:
- If a conversion is not possible (e.g. provided value is `"foo"` and desired type is `int`), shall we return `null` or throw an `IllegalArgumentException` (or better a newly defined checked `ConfigValueParserException`)?
- Currently `float`, `int`, `long` and `double` (and their wrapper classes) are supported. Shall we add code for `short`, `byte` and `char`?
- There is no support for arrays. Is that needed?
- All `Collections` are mapped to `List`. Shall we at least add `Set`?
-
=> [config] make configuration value parser available for export

bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/internal/discovery/InboxResource.java
- Fixed wrong openAPI schema for /inbox
Fixes #2707
=> [REST] Fixed wrong openAPI schema for /inbox

bundles/org.openhab.core.config.core/src/main/java/org/openhab/core/config/core/internal/validation/TypeIntrospections.java, bundles/org.openhab.core.config.core/src/test/java/org/openhab/core/config/core/internal/validation/ConfigDescriptionValidatorTest.java
- Allow String values for other Types
To not introduce regressions after #2682 on the type validation we should allow `String` values for all parameter types.
=> [config] Allow String values for other Types

bundles/org.openhab.core.automation.module.script.rulesupport/src/main/java/org/openhab/core/automation/module/script/rulesupport/loader/ScriptFileWatcher.java
ScriptFileWatcher reused logic for recursion and initial import. Initial import always processes a directory and it's contents (only), whereas ongoing monitoring may choose not to descend into subdirs, and processes files too. This change separates the logic.
=> [automation] ScriptFileWatcher Initial import now only processes dir

bundles/org.openhab.core.voice/src/main/java/org/openhab/core/voice/VoiceManager.java, bundles/org.openhab.core.voice/src/main/java/org/openhab/core/voice/internal/DialogProcessor.java, bundles/org.openhab.core.voice/src/main/java/org/openhab/core/voice/internal/VoiceConsoleCommandExtension.java, bundles/org.openhab.core.voice/src/main/java/org/openhab/core/voice/internal/VoiceManagerImpl.java, bundles/org.openhab.core.voice/src/main/resources/OH-INF/i18n/voice.properties, itests/org.openhab.core.voice.tests/src/main/java/org/openhab/core/voice/internal/HumanLanguageInterpreterStub.java, itests/org.openhab.core.voice.tests/src/main/java/org/openhab/core/voice/internal/KSServiceStub.java, itests/org.openhab.core.voice.tests/src/main/java/org/openhab/core/voice/internal/STTServiceStub.java, itests/org.openhab.core.voice.tests/src/main/java/org/openhab/core/voice/internal/TTSServiceStub.java, itests/org.openhab.core.voice.tests/src/main/java/org/openhab/core/voice/internal/VoiceManagerImplTest.java, itests/org.openhab.core.voice.tests/src/main/java/org/openhab/core/voice/internal/VoiceStub.java, itests/org.openhab.core.voice.tests/src/main/java/org/openhab/core/voice/voiceconsolecommandextension/InterpretCommandTest.java, itests/org.openhab.core.voice.tests/src/main/java/org/openhab/core/voice/voiceconsolecommandextension/VoicesCommandTest.java
Related to #2688
Updated methods startDialog
New method stopDialog
Null annotations added to the class DialogProcessor
Allow translation of sentences "said" by the dialog processor in case of error
2 console commands added to start and stop a dialog
Enhanced integration tests
=> [voice] Update dialog processing

bundles/org.openhab.core.io.net/src/main/java/org/openhab/core/io/net/http/PEMTrustManager.java
- Do not throw `CertificateParsingException` all the time
- Fixed pinned certificate creation
- Added `hashCode()` and `equals()` to ensure correct removals from `Queue` in `ExtensibleTrustManager` implementation
See https://community.openhab.org/t/java-connection-to-https-with-self-signed-cert/130593
=> Do not throw CertificateParsingException all the time; Fixed pinned certificate creation;

bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/binding/BaseThingHandler.java, bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/binding/ThingHandlerCallback.java, bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/internal/ThingManagerImpl.java, itests/org.openhab.core.thing.tests/src/main/java/org/openhab/core/thing/binding/BindingBaseClassesOSGiTest.java
See https://github.com/openhab/openhab-core/pull/2682#discussion_r795035470
It was assumed that thing handlers only update valid configuration. After merging #2682 it was discovered that this is not true. This PR enables the same validation for updates through the handler. If an invalid configuration or otherwise illegal (not-initializable) thing is detected, the changes are discarded and a warning logged.
=> [config] Enable config validation for updates by handler

bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/item/EnrichedItemDTOMapper.java, bundles/org.openhab.core.io.rest.core/src/test/java/org/openhab/core/io/rest/core/item/EnrichedItemDTOMapperTest.java
Fixes #2734 
This adds a check if a child is already a parent of the currently processed item in recursive mapping. If a recursion is found an ERROR is logged and the child is not processed.
I chose ERROR because this may cause issues in several components and could potentially affect the system stability.
=> fix recursive membership throws StackOverflowException on REST API call

bom/compile/pom.xml, bom/runtime/pom.xml, features/karaf/openhab-tp/src/main/feature/feature.xml, itests/org.openhab.core.binding.xml.tests/itest.bndrun, itests/org.openhab.core.config.discovery.tests/itest.bndrun, itests/org.openhab.core.config.xml.tests/itest.bndrun, itests/org.openhab.core.ephemeris.tests/itest.bndrun, itests/org.openhab.core.model.core.tests/itest.bndrun, itests/org.openhab.core.model.item.tests/itest.bndrun, itests/org.openhab.core.model.rule.tests/itest.bndrun, itests/org.openhab.core.model.script.tests/itest.bndrun, itests/org.openhab.core.model.thing.tests/itest.bndrun, itests/org.openhab.core.thing.tests/itest.bndrun, itests/org.openhab.core.thing.xml.tests/itest.bndrun, tools/i18n-plugin/pom.xml
This addresses CVE-2021-43859, see:
https://x-stream.github.io/changes.html
---
Replaces #2721, #2722, #2737
=> Upgrade XStream to 1.4.19

bundles/org.openhab.core.audio/src/main/java/org/openhab/core/audio/internal/javasound/JavaSoundAudioSource.java, bundles/org.openhab.core.audio/src/main/java/org/openhab/core/audio/internal/javasound/JavaSoundInputStream.java, bundles/org.openhab.core.voice/src/main/java/org/openhab/core/voice/internal/DialogProcessor.java
This is a proposed solution for https://github.com/openhab/openhab-core/issues/2702 about the system audio (javasound) returning closed audio streams after the first audio stream is closed. 
Also includes the use of RecognitionStartEvent on the dialog processor to wait for the STT add-on to be ready for toggling the "listening" item, so everything is really ready for the user to start talking.
Hope everything is in place. I have tested this changes with the porcupineKS and googleSTT add-ons.
=> [javasound/dialogprocessor] Not share mic ref on javasound + close audio streams and use RecognitionStartEvent on dialogprocessor

bundles/org.openhab.core.config.core/src/main/java/org/openhab/core/config/core/internal/validation/ConfigDescriptionParameterValidatorFactory.java, bundles/org.openhab.core.config.core/src/main/java/org/openhab/core/config/core/internal/validation/ConfigDescriptionValidatorImpl.java, bundles/org.openhab.core.config.core/src/main/java/org/openhab/core/config/core/internal/validation/MessageKey.java, bundles/org.openhab.core.config.core/src/main/java/org/openhab/core/config/core/internal/validation/MinMaxValidator.java, bundles/org.openhab.core.config.core/src/main/java/org/openhab/core/config/core/internal/validation/OptionsValidator.java, bundles/org.openhab.core.config.core/src/main/resources/OH-INF/i18n/validation.properties, bundles/org.openhab.core.config.core/src/test/java/org/openhab/core/config/core/internal/validation/ConfigDescriptionValidatorTest.java
- Added config validator for parameter options
Depends on #2690 
=> [config] Add config validator for parameter options

bundles/org.openhab.core/src/main/java/org/openhab/core/service/WatchQueueReader.java, bundles/org.openhab.core/src/test/java/org/openhab/core/JavaTest.java, bundles/org.openhab.core/src/test/java/org/openhab/core/service/AbstractWatchServiceTest.java
Related to #2727 
While investigating the issue above I found that the new version of the `WatchQueueReader` erroneously cancelled the job when removing it from the stored jobs. 
This is done on two occasions: 
- If a jobs is stored and we try to replace it. In this case cancellation is correct.
- If the job executes. Cancelling the job here is wrong. It is not noticed by the tests because it interrupts the job, which is not checked for our short-running jobs. In the issue above the job is checking if the thread is interrupted and therefore fails.
@wborn I also moved the tests to the `org.openhab.core` package and added the `JavaTest` as you suggested.
=> Fix WatchQueueReader cancelling jobs too early

bundles/org.openhab.core.automation.module.script/src/main/java/org/openhab/core/automation/module/script/ScriptExtensionManagerWrapper.java, bundles/org.openhab.core.automation.module.script/src/main/java/org/openhab/core/automation/module/script/defaultscope/ScriptBusEvent.java, bundles/org.openhab.core.automation.module.script/src/main/java/org/openhab/core/automation/module/script/defaultscope/ScriptThingActions.java, bundles/org.openhab.core.automation.module.script/src/main/java/org/openhab/core/automation/module/script/internal/ScriptEngineManagerImpl.java, bundles/org.openhab.core.automation.module.script/src/main/java/org/openhab/core/automation/module/script/internal/ScriptExtensionManagerWrapperImpl.java, bundles/org.openhab.core.automation.module.script/src/main/java/org/openhab/core/automation/module/script/internal/defaultscope/DefaultScriptScopeProvider.java, bundles/org.openhab.core.automation.module.script/src/main/java/org/openhab/core/automation/module/script/internal/defaultscope/ScriptBusEventImpl.java, bundles/org.openhab.core.automation.module.script/src/main/java/org/openhab/core/automation/module/script/internal/defaultscope/ScriptThingActionsImpl.java
=> expose three classes used as bindings in JSR-223 rules as interfaces

bundles/org.openhab.core.model.rule/src/org/openhab/core/model/rule/jvmmodel/RulesJvmModelInferrer.xtend, bundles/org.openhab.core.model.script.runtime/src/org/openhab/core/model/script/runtime/internal/engine/DSLScriptEngine.java, bundles/org.openhab.core.model.script/src/org/openhab/core/model/script/jvmmodel/ScriptJvmModelInferrer.xtend
I wanted to be able to detect which thing had triggered a DSL rule in order to write rules which used a single set of functionality when detecting that one of many things had gone offline. Whilst I was at it I figured it might be useful to include the previous and new statuses and remove the reference to previousState which didn't seem to make sense. I've tried to follow the pattern in the code and this PR #2567
=> Add triggeringThing name to DSL rules

itests/itest-include.bndrun, itests/pom.xml
It is probably always a good idea to run the OSGi HTTP service on a random available port in itests.
This fixes some stacktraces when running itests and it will also prevent future issues when tests using the HTTP service are written.
These stacktraces often show when running itests in parallel:
```
org.ops4j.pax.web.pax-web-runtime [org.ops4j.pax.web.service.internal.HttpServiceStarted] ERROR : Could not start the servlet context for context path []
java.io.IOException: Failed to bind to /0.0.0.0:8080
at org.eclipse.jetty.server.ServerConnector.openAcceptChannel(ServerConnector.java:349)
at org.eclipse.jetty.server.ServerConnector.open(ServerConnector.java:310)
at org.eclipse.jetty.server.AbstractNetworkConnector.doStart(AbstractNetworkConnector.java:80)
at …
```
=> Always run OSGi HTTP service on random port in itests

bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/binding/BaseThingHandler.java
Related to #2764 
The reason why the new configuration was rejected is now included in the log message.
=> Improve log message for invalid configuration updates by handler

bundles/org.openhab.core.io.monitor/src/main/java/org/openhab/core/io/monitor/internal/DefaultMetricsRegistration.java
Looks like this workaround introduced in #2480 is unnecessary nowadays because #2484 addressed the root cause.
This fixes the AvoidCatchingThrowable SAT findings.
=> Stop catching Throwables in DefaultMetricsRegistration

bundles/org.openhab.core.config.core/src/test/java/org/openhab/core/config/core/ConfigUtilTest.java, bundles/org.openhab.core.config.core/src/test/java/org/openhab/core/config/core/dto/ConfigDescriptionDTOTest.java, bundles/org.openhab.core.config.core/src/test/java/org/openhab/core/config/core/internal/validation/ConfigDescriptionValidatorTest.java, bundles/org.openhab.core.config.discovery/src/test/java/org/openhab/core/config/discovery/internal/PersistentInboxTest.java, bundles/org.openhab.core.io.rest.core/src/test/java/org/openhab/core/io/rest/core/internal/config/ConfigDescriptionResourceTest.java, bundles/org.openhab.core.io.rest/src/test/java/org/openhab/core/io/rest/internal/filter/ProxyFilterTest.java, bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/internal/firmware/FirmwareUpdateServiceImpl.java, bundles/org.openhab.core.ui/src/test/java/org/openhab/core/ui/internal/proxy/ProxyServletServiceTest.java, itests/org.openhab.core.config.core.tests/src/main/java/org/openhab/core/config/core/ConfigOptionRegistryOSGiTest.java, itests/org.openhab.core.config.discovery.tests/src/main/java/org/openhab/core/config/discovery/internal/InboxOSGiTest.java, itests/org.openhab.core.config.xml.tests/src/main/java/org/openhab/core/config/xml/test/ConfigDescriptionI18nTest.java, itests/org.openhab.core.config.xml.tests/src/main/java/org/openhab/core/config/xml/test/ConfigDescriptionsTest.java, itests/org.openhab.core.model.thing.testsupport/src/main/java/org/openhab/core/model/thing/testsupport/hue/TestHueConfigDescriptionProvider.java, itests/org.openhab.core.thing.tests/src/main/java/org/openhab/core/thing/binding/BindingBaseClassesOSGiTest.java, itests/org.openhab.core.thing.tests/src/main/java/org/openhab/core/thing/internal/ThingManagerOSGiTest.java, itests/org.openhab.core.thing.xml.tests/src/main/java/org/openhab/core/thing/xml/test/ConfigDescriptionsTest.java, itests/org.openhab.core.voice.tests/src/main/java/org/openhab/core/voice/internal/VoiceManagerImplTest.java
- Avoid `URISyntaxException` in tests by using`URI.create()` method
=> Avoid `URISyntaxException` in tests

bundles/org.openhab.core.config.core/src/main/java/org/openhab/core/config/core/internal/validation/OptionsValidator.java, bundles/org.openhab.core.config.core/src/test/java/org/openhab/core/config/core/internal/validation/ConfigDescriptionValidatorTest.java
- Fixed config validation message for parameter options
The message has two placeholder ans we should pass the current value and the possible options to it. 
=> [config] Fixed config validation message for parameter options

bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/internal/ThingManagerImpl.java, bundles/org.openhab.core.thing/src/test/java/org/openhab/core/thing/internal/ThingManagerImplTest.java
Fixes #1893 
The reason for the reported behavior is that a handler is registered on startup for disabled things. The thing is not initialized because the enabled-state is check while initializing the handler. 
Since we unregister the handler if the thing is disabled at runtime (and register a new one once the thing is enabled again), I believe we should not register a handler at this point.
=> Fix dispose is called on handlers for disabled things

bundles/org.openhab.core.voice/src/main/java/org/openhab/core/voice/internal/DialogProcessor.java
After recent changes to null checks, seems like this need to be changed as the way of return no response from an hli has changed to return an empty string.
@lolodomo, @wborn WDYT?
=> [DialogProcessor] change non null check for non empty check

tools/i18n-plugin/src/main/java/org/openhab/core/tools/i18n/plugin/BundleInfo.java, tools/i18n-plugin/src/main/java/org/openhab/core/tools/i18n/plugin/BundleInfoReader.java, tools/i18n-plugin/src/main/java/org/openhab/core/tools/i18n/plugin/XmlToTranslationsConverter.java
The plugin did not generate translations for bundles of bindings that do not have a binding.xml file.
With this change it should also be possible to generate the default translations of the modbus and mqtt bindings.
Related to openhab/openhab-addons#12220
=> Support multi bundle bindings in i18n-maven-plugin

bundles/org.openhab.core.voice/src/main/java/org/openhab/core/voice/internal/DialogProcessor.java
Hi, this small change fix the execution of the dialog processor.
It was aborting its own thread, because the event was produced by the stt service. So it causes an interruption execution during the tss execution after the hli.
I already tested this and change should not have other side effects as the whole method is synchronized.
Is this change ok @kaikreuzer, @lolodomo?
=> [DialogProcessor] processor aborting before response

itests/org.openhab.core.automation.module.script.tests/src/main/java/org/openhab/core/automation/module/script/internal/defaultscope/ScriptScopeOSGiTest.java, pom.xml
* Adds some --add-opens to maven-surefire-plugin for:
* modbus transport tests (java.net)
* tests using Gson/XStream (java.util)
* Only run ScriptScopeOSGiTest when Nashorn is available as it has been removed since JDK 15
=> Fix test failures when building with Java 17

bundles/org.openhab.core.automation.module.script/src/main/java/org/openhab/core/automation/module/script/internal/provider/ScriptModuleTypeProvider.java
On Java 17 there is no Nashorn scripting engine so it takes a bit longer before `ScriptEngine`s are available.
Rules would stay uninitialized forever because the `ScriptModuleTypeProvider` did not notify its listeners whenever the `script.ScriptAction`, `script.ScriptCondition` module types became available.
=> Fix rules stay uninitialized when using Java 17

bundles/org.openhab.core.audio/src/main/java/org/openhab/core/audio/AudioManager.java, bundles/org.openhab.core.audio/src/main/java/org/openhab/core/audio/internal/AudioManagerImpl.java, bundles/org.openhab.core.io.rest.voice/src/main/java/org/openhab/core/io/rest/voice/internal/VoiceResource.java, bundles/org.openhab.core.voice/src/main/java/org/openhab/core/voice/internal/VoiceConsoleCommandExtension.java
=> [audio] Add missing method getSource with sourceId as parameter

bundles/org.openhab.core.model.script/src/org/openhab/core/model/script/jvmmodel/ScriptJvmModelInferrer.xtend
Follow up to #2756
Suggestion from [rossko57](https://community.openhab.org/t/oh3-getting-triggeringitemname-and-previousstate-of-thing-changed/128794/9) that we make the variable names more explicit to avoid confusion of `previousStatus` with `previousState`.
I'll log a docs PR assuming this is accepted.
=> Rename Thing status variables to be more explicit

bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/internal/profiles/SystemProfileFactory.java, bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/internal/profiles/TriggerEventStringProfile.java, bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/profiles/SystemProfiles.java, bundles/org.openhab.core.thing/src/test/java/org/openhab/core/thing/internal/profiles/TriggerEventStringProfileTest.java, itests/org.openhab.core.thing.tests/src/main/java/org/openhab/core/thing/internal/profiles/SystemProfileFactoryOSGiTest.java
Related to https://github.com/openhab/openhab-webui/issues/886
This was suggested by @kaikreuzer because there is no profile available to link non-system-channeltype trigger channels to an item. 
=> Add a profile for linking trigger channels to String items

bundles/org.openhab.core.voice/src/main/java/org/openhab/core/voice/internal/DialogProcessor.java, bundles/org.openhab.core.voice/src/main/java/org/openhab/core/voice/internal/VoiceManagerImpl.java
This is a proposed solution for https://github.com/openhab/openhab-core/issues/2794.
Includes:
* use specific format for ks, stt and tts on the dialog processor.
* <s>refactor of static method getBestMatch in AudioFormat.</s>
* remove duplicated method getBestMatch in VoiceManagerImpl and use the one from AudioFormat.
=> [Voice] get compatible audio format refactor

bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/binding/BaseThingHandler.java, bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/binding/ThingHandlerCallback.java, bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/internal/ThingManagerImpl.java
Closes #2719 
This enables a thing handler to check the configuration of the thing and it's channels prior to changing them. 
=> Make ConfigDescription for thing and channels available to ThingHandler

bundles/org.openhab.core/src/main/java/org/openhab/core/internal/items/ExpireManager.java, bundles/org.openhab.core/src/test/java/org/openhab/core/internal/items/ExpireManagerTest.java
Fixes #1994 
Fixes #2542 
This needs an additional PR in UI to make it configurable via UI.
=> [expiry] extend ExpiryManager to allow ignoring state updates

bundles/org.openhab.core/src/main/java/org/openhab/core/library/types/DecimalType.java, bundles/org.openhab.core/src/test/java/org/openhab/core/library/types/DecimalTypeTest.java
The expectation is, that when a `DecimalType` was constructed with a
`float` value, the precision of its `doubleValue()`, `floatValue()`,
`toBigDecimal()` and `toString()` is preserved. But there are `float`
values like `4.2f` or `37.1f` that cannot directly converted to `double`
without precision loss.
This commit replaces all the numerical constructors of `DecimalType`
with a single constructor with a `Number` argument, so that all `float`
values can be used without precision loss.
NOTE: There is some special handling needed for `QuantityType` and
`HSBType` because these types have a special none conventional `toString`
implementation.
=> [openhab.core] DecimalType-ctor with Number argument

bundles/org.openhab.core.addon.marketplace/src/main/java/org/openhab/core/addon/marketplace/internal/json/JsonAddonService.java, bundles/org.openhab.core.addon.marketplace/src/main/java/org/openhab/core/addon/marketplace/internal/json/model/AddonEntryDTO.java, bundles/org.openhab.core.karaf/pom.xml, bundles/org.openhab.core.karaf/src/main/java/org/openhab/core/karaf/internal/KarafAddonService.java, bundles/org.openhab.core.karaf/src/main/java/org/openhab/core/karaf/internal/LoggerBean.java, bundles/org.openhab.core.karaf/src/main/java/org/openhab/core/karaf/internal/LoggerResource.java, bundles/org.openhab.core/src/main/java/org/openhab/core/addon/Addon.java
Related to #299
This adds the necessary parts in core for solving the mentioned issue. With these extensions it is possible 
- to add/modify/delete log settings via REST API
- get the Java package names that belong to an add-on
A future UI component can then retrieve the package names for an add-on and modify the log-levels of these packages. This could e.g. be integrated in the add-on page (next to the "remove" button). 
This is much more user-friendly than directing user to use the karaf console. On openHABian the log is displayed in frontail, so no console interaction is needed at all to get DEBUG logs.
=> [rest] Add ability to change loggers and expose package names of addons

bundles/org.openhab.core.io.rest/src/main/java/org/openhab/core/io/rest/internal/filter/ProxyFilter.java, bundles/org.openhab.core.io.rest/src/test/java/org/openhab/core/io/rest/internal/filter/ProxyFilterTest.java
Fixes #2684 
This seems to be safe, because a comma is not an allowed character in a host-name.
=> Fix proxy can't handle requests with forwarded host list

bundles/org.openhab.core.voice/src/main/java/org/openhab/core/voice/internal/DialogProcessor.java, bundles/org.openhab.core.voice/src/main/java/org/openhab/core/voice/internal/VoiceManagerImpl.java
Partially revert https://github.com/openhab/openhab-core/pull/2795
The getBestMatch implementation from AudioFormat behaves different. 
This restores the previous one.
Described here https://github.com/openhab/openhab-core/issues/2801
=> [Voice] restore getBestMatch method

bundles/org.openhab.core.automation.module.script/src/main/java/org/openhab/core/automation/module/script/internal/ScriptEngineManagerImpl.java
Fixes #2727 
Awaiting feed-back from reporting user.
=> Fix deadlock when removing ScriptEngine

bundles/org.openhab.core/src/main/java/org/openhab/core/library/types/DecimalType.java
This re-introduces the constructors removed in #2596. This should restore binary compatibility with 3.2.
=> Re-introduce removed DecimalType ctors to maintain compatibility

bundles/org.openhab.core.automation.module.script/src/main/java/org/openhab/core/automation/module/script/internal/handler/AbstractScriptModuleHandler.java
It's unused so it can be safely removed.
=> Remove unused local variable

bundles/org.openhab.core.voice/src/main/java/org/openhab/core/voice/internal/DialogProcessor.java, bundles/org.openhab.core.voice/src/main/java/org/openhab/core/voice/internal/VoiceManagerImpl.java
This pr contains:
* <s>stop ks while stt in dialog processor (we were already ignoring ks events)</s>
* fix language check for services involved in dialog
* fix the "best match" format resolution broken by me in a previous pr.
I'm able to use the audio capabilities again after this changes.
=> [Voice] fix "best match" format resolution and language check for services involved in dialog

bundles/org.openhab.core.voice/src/main/java/org/openhab/core/voice/internal/VoiceManagerImpl.java
Check for null and emptyness, as, for example, RuleHumanLanguageInterpreter returns an empty set to tell it has no locale preference.
Found by testing the new voice system (ks, stt)
Signed-off-by: Gwendal Roulleau <gwendal.roulleau@gmail.com>
=> [Voice] fix checklocale with RuleHumanLanguageInterpreter

.github/workflows/ci-build.yml, pom.xml
This adds Java 17 to the GitHub Actions CI build matrix so we can make sure the build keeps working with both Java 11 and Java 17. It also updates the required Java version range used by the enforcer plugin so it is also possible to build with the supported Java versions. Furthermore it prevents duplicate error annotations being added by only adding these in the Java 11 matrix build.
=> Add Java 17 to GHA CI build matrix

bundles/org.openhab.core.voice/src/main/java/org/openhab/core/voice/internal/text/StandardInterpreter.java, bundles/org.openhab.core.voice/src/main/java/org/openhab/core/voice/text/AbstractRuleBasedInterpreter.java
This just apply to 'es' locale. Fixes tokenization and onOff rule.
=> [standardinterpreter] spanish: fix text tokenization and on/off rule

bundles/org.openhab.core.voice/src/main/java/org/openhab/core/voice/internal/VoiceConsoleCommandExtension.java
=> [voice] New optional arguments for console command voice startdialog

itests/itest-include.bndrun
The itests are run using an R7 framework so the inclusion no longer seems required.
This also allows for easily customizing Import-Package headers in itest bundles.
Sometimes it useful to be able to customize this header when including libraries without OSGi bundle headers like in https://github.com/openhab/openhab-addons/pull/12431/.
=> Remove temporary OSGi framework inclusion

bundles/org.openhab.core/src/main/java/org/openhab/core/service/StartLevelService.java
Since no requirements are defined for `STARTLEVEL_COMPLETE` no `ReadyMarker` was added to the map of `ReadyMarker`s.
=> Fix missing STARTLEVEL_COMPLETE ReadyMarker

bundles/org.openhab.core.io.jetty.certificate/src/main/java/org/openhab/core/io/jetty/certificate/internal/CertificateGenerator.java
The class is in a package that does not match the bundle name.
=> Fix CertificateGenerator package

bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/internal/ProfileContextImpl.java, bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/profiles/ProfileContext.java
I'm working on a very generic script profile which can be used with every item type. E.g. a script could half all commands from the handler to the item. Since a `Dimmer` channel accepts different item types, I need to know which types are accepted by the receiving item. This could e.g. also be used to link a `String` channel (containing a JSON array as result of an HTTP request) to an `Number` item (for element count in the array).
Even tough I doubt that there are other implementations of `ProfileContext` out there, I decided to keep it backward compatible and make the implementation of the newly introduced methods optional. If you don't mind the breaking change, I can easily remove them.
=> Add accepted types to ProfileContext

bundles/org.openhab.core/pom.xml
This saves about 1 minute when building this bundle.
Most bundles depend on org.openhab.core so cores would stay idle until this bundle is build in a parallel build.
=> Run org.openhab.core tests in forks to reduce build time

bundles/org.openhab.core.config.discovery/src/main/java/org/openhab/core/config/discovery/DiscoveryResult.java, bundles/org.openhab.core.config.discovery/src/main/java/org/openhab/core/config/discovery/internal/DiscoveryResultImpl.java, bundles/org.openhab.core.config.discovery/src/main/java/org/openhab/core/config/discovery/internal/PersistentInbox.java, bundles/org.openhab.core.config.discovery/src/test/java/org/openhab/core/config/discovery/internal/PersistentInboxTest.java
Fixes #1098 
This fixes the reported problem with thing properties having a wrong representation. When adding a thing to the `PersistentInbox` the config description is retrieved and all non-configuration properties are converted to `String`. Properties with the same name as a configuration parameter stay unchanged.
There is one thing to consider:
The implementation relies on a config description being available. This is currently not enforced as it breaks a lot of tests for the persistent inbox. IMO it would be ok to not accept discovery results if the thing-type is missing in the registry or the config-description is not available.
=> [discovery] keep format of thing properties

bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/internal/item/ItemResource.java
Closes #1581 
This PR adds the ability to use different media types for RawType states. If the `Accept` header does not specify `text/plain` (which is the default used before), a new method checks if any of the provided media types in the header matches the media type of the state and sends the response with that media-type set. If no match is found, but the `Accept` header specifies `application/octet-stream` this media type is used. In case of media-type mismatch status 415 (unsupported media type) is returned. If the item state is not `RawType` the request is considered invalid and a 400 (bad request) is returned.
=> [rest] Allow binary MediaType for RawType item states

bundles/org.openhab.core.io.jetty.certificate/bnd.bnd
There is also a bnd.bnd file referencing the CertificateGenerator so it also needs to be updated for the change in #2838
=> Update bnd.bnd for CertificateGenerator package change

bundles/org.openhab.core.karaf/src/main/java/org/openhab/core/karaf/internal/FeatureInstaller.java
Follow-Up To #2753
It was reported on the forum that under some circumstances the service PID of the fileinstall service is not `org.apache.felix.fileinstall~deploy` but something like `org.apache.felix.fileinstall.a702e1ba-1635-4154-906d-a9646a043a56`. As a result the check if all KARs are installed failed because the addons directory could not be determined.
This PR requests all configurations for the factoryPID `org.apache.felix.fileinstall` and then takes the first to determine the addons directory. I believe this is fine because the service should not exist multiple times.
=> Fix KAR installation check

bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/internal/ThingManagerImpl.java, itests/org.openhab.core.thing.tests/src/main/java/org/openhab/core/thing/binding/BindingBaseClassesOSGiTest.java, itests/org.openhab.core.thing.tests/src/main/java/org/openhab/core/thing/internal/ThingManagerOSGiTest.java
Following up a discussion in the forum this does not log the validation errors at DEBUG level but adds them as thing status detail message, so it can be shown in the UI.
=> Show config validation messages in thing status

bom/runtime/pom.xml
This prevents deprecation warnings when running the itests with Java 17:
```
WARNING: A terminally deprecated method in java.lang.System has been called
WARNING: System::setSecurityManager has been called by org.eclipse.osgi.internal.framework.SystemBundleActivator (file:org.openhab.core.tests/target/test/tmp/testing/itest/cnf/cache/6.2.0/org.openhab.core.bom.runtime-index/org.eclipse.osgi-3.16.300.v20210525-1715.jar)
WARNING: Please consider reporting this to the maintainers of org.eclipse.osgi.internal.framework.SystemBundleActivator
WARNING: System::setSecurityManager will be removed in a future release
```
See: https://bugs.eclipse.org/bugs/show_bug.cgi?id=574729
=> Upgrade Eclipse OSGi system bundle to 3.17.200 in runtime BOM

bundles/org.openhab.core/src/test/java/org/openhab/core/internal/scheduler/PeriodicSchedulerImplTest.java
Fixes #2848 
The old implementation truncated timestamps to 1/10 s. Under some circumstances this could result in a failed tests:
offset = 201 -> truncatedOffset = 2
200ms delay expected, adjustment calculation results in an actual delay of 198ms
time = 399 -> truncatedTime = 3
expected: truncatedOffset + expected => 2 + 2 = 4
actual: truncatedTime = 3
The new implementation allows for an error of +/- 30ms which is far more than needed (and better than the +99/-1 ms we had before). Also the periodic time is always calculated from the last value, not from the original start, preventing failures from small deviations summing up. 
=> Improve PeridodicSchedulerImplTest

bundles/org.openhab.core.automation.module.script.rulesupport/src/test/java/org/openhab/core/automation/module/script/rulesupport/loader/ScriptFileWatcherTest.java
Fixes #2854 
Most of the tests add a timeout of 1s to account for small delays in async processing in the AbstractWatchService. This adds some more timeouts for tests which were missing those.
=> Improve ScriptFileWatcherTest

itests/org.openhab.core.thing.tests/src/main/java/org/openhab/core/thing/internal/ThingManagerOSGiTest.java
Fixes #2539 
This change ensures that the storage of bridge and thing are done before the initialization is reported.
=> Improve ThingManagerOSGiTest

itests/org.openhab.core.thing.tests/src/main/java/org/openhab/core/thing/binding/BindingBaseClassesOSGiTest.java, itests/org.openhab.core.thing.tests/src/main/java/org/openhab/core/thing/internal/ThingManagerOSGiTest.java
Since #2829 localized messages may appear in the status info of a thing. This makes the OSGi thing tests fail because an unlocalized version is used for comparison.
=> Fix build in localized environments

bundles/org.openhab.core.addon.marketplace/src/main/java/org/openhab/core/addon/marketplace/internal/community/CommunityMarketplaceAddonService.java
For some reason if I disable "Enable Community Marketplace" it still keeps showing marketplace add-ons.
_Originally posted by @wborn in https://github.com/openhab/openhab-core/issues/2811#issuecomment-1073362324_
Simple typo when I refactored the config key to a static constant. In the `marketplace.xml` the configuration option is named `enable` not `enabled`.
=> Fix enabling/disabling CommunityMarketplace

bundles/org.openhab.core.addon.marketplace/src/main/resources/OH-INF/i18n/marketplace.properties, bundles/org.openhab.core/src/main/resources/OH-INF/i18n/addons.properties
This makes it possible to use Crowdin for translating the new configuration options introduced in #2811.
=> Add missing default translations for add-ons/marketplace configuration options
