openhab/openhab-core

itests/org.openhab.core.automation.integration.tests/src/main/java/org/openhab/core/automation/integration/test/HostFragmentSupportTest.java
* Remove duplications
* Better null handling
* Use constants
* Use default waitForAssert timeout (10s)
This may help to get the test more stable (#1089).
=> Improve HostFragmentSupportTest

bundles/org.openhab.core.persistence/src/main/java/org/openhab/core/persistence/PersistenceItemConfiguration.java
Fixes #2875 
I didn't check if we can omit null-checks, because of the bigger refactoring in #2871 which would create merge conflicts.
=> Fix null annotations on PersistenceItemConfiguration

tools/i18n-plugin/pom.xml
This makes it follow the naming scheme as used with the other projects:
```
...
[INFO] openHAB Core :: Tools :: Archetypes                                [pom]
[INFO] openHAB Core :: Tools :: Archetypes :: Binding         [maven-archetype]
[INFO] openHAB Core :: Tools :: Internationalization Maven Plugin [maven-plugin]
[INFO] openHAB Core :: Integration Tests                                  [pom]
[INFO] openHAB Core :: Integration Tests :: Tests                         [jar]
[INFO] openHAB Core :: Integration Tests :: OAuth2Client Tests            [jar]
...
```
=> Fix i18n-maven-plugin project name

bundles/org.openhab.core.automation.module.script/src/main/java/org/openhab/core/automation/module/script/internal/handler/ScriptActionHandler.java
=> Fix ScriptEngine not removed if created by ScriptAction

bundles/org.openhab.core.semantics/src/main/java/org/openhab/core/semantics/internal/SemanticsMetadataProvider.java, bundles/org.openhab.core.semantics/src/test/java/org/openhab/core/semantics/internal/SemanticsMetadataProviderTest.java
This fixes the issue that the semantic metadata is incorrect when defining group member items in files and their groups in the UI.
Fixes #2106
Fixes #2117
=> Update semantic metadata of group members when groups are added/removed

bundles/org.openhab.core.voice/src/main/java/org/openhab/core/voice/text/AbstractRuleBasedInterpreter.java
Fix Spanish tokenization. I realize last time I tried to do it I forgot the 'ñ' character.
This time it should be right as I have followed this reference https://www1.icsi.berkeley.edu/~chema/espanol/caracteres_hispanos.html
Regards
=> [AbstractRuleBasedInterpreter] Fix spanish tokenization

bundles/org.openhab.core.automation.module.script.rulesupport/src/main/java/org/openhab/core/automation/module/script/rulesupport/shared/ScriptedRuleProvider.java
The Rule was never removed from the internal tracking map and therefore allocated resources were never freed.
=> Fix memory leak in ScriptedRuleProvider

bom/runtime/pom.xml, features/karaf/openhab-tp/src/main/feature/feature.xml
Uses an openHAB 5.2.1.OH1 build based on the latest changes in the nrjavaserial master branch ([7aa21d1](https://github.com/NeuronRobotics/nrjavaserial/tree/7aa21d1dc8cecdc8daad3ebc40273cfb8179e9d2)).
When there is an official release containing those changes we can upgrade to that.
Most importantly this fixes a file descriptor leak when checking lock dir permissions.
It also adds FreeBSD aarch64 (ARM64) support.
Fixes #1842
---
Can you add the JAR/POM in https://github.com/wborn/nrjavaserial/releases/tag/5.2.1.OH1 to the openHAB Maven repository @kaikreuzer?
=> Upgrade nrjavaserial to fix file descriptor leak

bundles/org.openhab.core.storage.json/src/main/java/org/openhab/core/storage/json/internal/JsonStorage.java, bundles/org.openhab.core.storage.json/src/main/java/org/openhab/core/storage/json/internal/JsonStorageService.java, bundles/org.openhab.core.storage.json/src/main/java/org/openhab/core/storage/json/internal/migration/RenamingTypeMigrator.java, bundles/org.openhab.core.storage.json/src/main/java/org/openhab/core/storage/json/internal/migration/TypeMigrationException.java, bundles/org.openhab.core.storage.json/src/main/java/org/openhab/core/storage/json/internal/migration/TypeMigrator.java, bundles/org.openhab.core.storage.json/src/test/java/org/openhab/core/storage/json/internal/JsonStorageTest.java, bundles/org.openhab.core.storage.json/src/test/java/org/openhab/core/storage/json/internal/MigrationTest.java
This is a pre-requisite to solving #1301. It allows maintaining backward compatibility when types are renamed or changed.
Inspired by https://github.com/maggu2810/openhab-core/commit/b5c224e
=> Allow type migrations in JSONStorage

bom/openhab-core/pom.xml, bundles/org.openhab.core.io.rest.transform/NOTICE, bundles/org.openhab.core.io.rest.transform/pom.xml, bundles/org.openhab.core.io.rest.transform/src/main/java/org/openhab/core/io/rest/transform/TransformationConfigurationDTO.java, bundles/org.openhab.core.io.rest.transform/src/main/java/org/openhab/core/io/rest/transform/internal/TransformationConfigurationResource.java, bundles/org.openhab.core.transform/src/main/java/org/openhab/core/transform/AbstractFileTransformationService.java, bundles/org.openhab.core.transform/src/main/java/org/openhab/core/transform/FileTransformationConfigurationProvider.java, bundles/org.openhab.core.transform/src/main/java/org/openhab/core/transform/LegacyTransformationConfigurationProvider.java, bundles/org.openhab.core.transform/src/main/java/org/openhab/core/transform/ManagedTransformationConfigurationProvider.java, bundles/org.openhab.core.transform/src/main/java/org/openhab/core/transform/TransformationConfiguration.java, bundles/org.openhab.core.transform/src/main/java/org/openhab/core/transform/TransformationConfigurationProvider.java, bundles/org.openhab.core.transform/src/main/java/org/openhab/core/transform/TransformationConfigurationRegistry.java, bundles/org.openhab.core.transform/src/main/java/org/openhab/core/transform/internal/TransformationActivator.java, bundles/org.openhab.core.transform/src/main/java/org/openhab/core/transform/internal/TransformationConfigurationRegistryImpl.java, bundles/org.openhab.core.transform/src/test/java/org/openhab/core/transform/FileTransformationConfigurationProviderTest.java, bundles/org.openhab.core.transform/src/test/java/org/openhab/core/transform/LegacyTransformationConfigurationProviderTest.java, bundles/org.openhab.core.transform/src/test/java/org/openhab/core/transform/ManagedTransformationConfigurationProviderTest.java, bundles/org.openhab.core.transform/src/test/java/org/openhab/core/transform/actions/TransformationTest.java, bundles/org.openhab.core.transform/src/test/java/org/openhab/core/transform/internal/TransformationConfigurationRegistryImplTest.java, bundles/pom.xml, features/karaf/openhab-core/src/main/feature/feature.xml
Related to #2068 
Succeeds #2782
This adds a registry for transformation configurations and two providers:
- The `LegacyTransformationConfigurationProvider` reads transformation files from the `transform` directory and stores them with a UID equal to the file name. This allows transformation services to maintain fully backward compatibility regarding the configuration if they switch from the `AbstractFileTransformationService` to the new registry. Configuration provided by this service are read-only.
- The `ManagedTransformationConfigurationProvider` stores configurations in a JSON database. The UID has the format `config:<type>:<identifier>[:<locale>]`, where `type` is equal to the file extension for legacy files. Configurations provided by this service can be added/updated/removed via …
=> Add a registry for transformation configurations and allow editing them

itests/org.openhab.core.model.core.tests/itest.bndrun, itests/org.openhab.core.model.item.tests/itest.bndrun, itests/org.openhab.core.model.rule.tests/itest.bndrun, itests/org.openhab.core.model.script.tests/itest.bndrun, itests/org.openhab.core.model.thing.tests/itest.bndrun
CI builds hang forever (also observed locally).
Probably related to #2657
=> Fix hanging build

bundles/org.openhab.core.model.thing/src.moved/test/java/org/openhab/core/model/thing/internal/GenericThingProviderMultipleBundlesTest.java, bundles/org.openhab.core.model.thing/src/org/openhab/core/model/thing/internal/GenericThingProvider.xtend
Fixes #2218 
A message at INFO level is logged when a thing could not be added because there is no corresponding binding (which could indicate a typo in the binding name or thing-type). This is only relevant for textual configuration as the UI prevents typos.
The message is suppressed on initial loading to prevent flooding the log (the model most likely is parsed before all ThingHandlerFactories have been added).
=> Log a message if a model is parsed and no thing handler factory can be found

.gitignore
While openHAB uses Maven, under some circumstances IntelliJ creates files in the .gradle/ directory.
=> Add .gradle to .gitignore

bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/internal/CommunicationManager.java, bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/internal/ProfileContextImpl.java, bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/profiles/ProfileContext.java, itests/org.openhab.core.thing.tests/src/main/java/org/openhab/core/thing/internal/CommunicationManagerOSGiTest.java
This is a follow-up to #2814.
It makes use of the methods added in #2814 and also adds a new method to access the command types accepted by the handler. Additionally it adds support for thing/item change detection. In case an update/creation/removal event is received, all corresponding profiles are removed from the cache. This ensures that the accepted data types and command types are always up-to-date with the current link configuration. If the item or channel cannot be found in the registry/thing, no profile is created. While this seems like a breaking change at first glance it is not, because the link would not work anyway if either item or thing(-channel) are not available.
=> Extend ProfileContext to allow data type changing profiles

bundles/org.openhab.core/src/main/java/org/openhab/core/common/AbstractUID.java, bundles/org.openhab.core/src/test/java/org/openhab/core/common/AbstractUIDTest.java
Fixes #2900 
The last segment is not allowed to be empty. Also adds tests for UID construction.
Originally I thought (and still think) that empty segments make no sense at any position. But at least for `ThingUID` there is a test that ensures that a missing thing-type is considered a valid UID.
=> Do not allow empty last segment in UID

bundles/org.openhab.core/src/main/java/org/openhab/core/types/util/UnitUtils.java, bundles/org.openhab.core/src/test/java/org/openhab/core/types/util/UnitUtilsTest.java
[An Angle is also Dimensionless](https://en.wikipedia.org/wiki/Angle#Units) and because it is the first compatible unit it is always returned instead of any other Dimensionless unit.
With these changes `getDimensionName` will prefer the dimension of equal units over those of compatible units.
Fixes #2880
=> Fix UnitUtils.getDimensionName returns Angle instead of Dimensionless

.gitattributes, bundles/org.openhab.core.audio/src/test/java/org/openhab/core/audio/internal/AudioConsoleTest.java, bundles/org.openhab.core.audio/src/test/java/org/openhab/core/audio/internal/AudioServletTest.java, bundles/org.openhab.core.automation.module.script.rulesupport/src/test/java/org/openhab/core/automation/module/script/rulesupport/loader/ScriptFileWatcherTest.java, bundles/org.openhab.core.io.net/src/test/java/org/openhab/core/io/net/exec/ExecUtilTest.java, bundles/org.openhab.core.model.script/src.moved/test/java/org/openhab/core/model/script/internal/actions/TimerImplTest.java, bundles/org.openhab.core/pom.xml, bundles/org.openhab.core/src/test/java/org/openhab/core/internal/common/SafeCallerImplTest.java, bundles/org.openhab.core/src/test/java/org/openhab/core/internal/items/ExpireManagerTest.java, bundles/org.openhab.core/src/test/java/org/openhab/core/internal/scheduler/PeriodicSchedulerImplTest.java, bundles/org.openhab.core/src/test/java/org/openhab/core/internal/scheduler/SchedulerImplTest.java, itests/org.openhab.core.config.discovery.tests/src/main/java/org/openhab/core/config/discovery/internal/InboxOSGiTest.java, itests/org.openhab.core.model.item.tests/src/main/java/org/openhab/core/model/item/internal/GenericItemProviderTest.java, itests/org.openhab.core.model.script.tests/src/main/java/org/openhab/core/model/script/engine/ScriptEngineOSGiTest.java, itests/org.openhab.core.model.thing.tests/src/main/java/org/openhab/core/model/thing/test/hue/GenericItemChannelLinkProviderTest.java, itests/org.openhab.core.model.thing.tests/src/main/java/org/openhab/core/model/thing/test/hue/GenericThingProviderTest.java, itests/org.openhab.core.thing.tests/src/main/java/org/openhab/core/thing/internal/ChannelCommandDescriptionProviderOSGiTest.java, itests/org.openhab.core.thing.tests/src/main/java/org/openhab/core/thing/internal/ChannelLinkNotifierOSGiTest.java, itests/org.openhab.core.thing.tests/src/main/java/org/openhab/core/thing/internal/ChannelStateDescriptionProviderOSGiTest.java, itests/org.openhab.core.thing.tests/src/main/java/org/openhab/core/thing/internal/ThingManagerOSGiTest.java, itests/org.openhab.core.voice.tests/src/main/java/org/openhab/core/voice/internal/VoiceManagerImplTest.java, tools/i18n-plugin/src/main/java/org/openhab/core/tools/i18n/plugin/BundleInfoReader.java, tools/i18n-plugin/src/test/java/org/openhab/core/tools/i18n/plugin/GenerateDefaultTranslationsMojoTest.java
This fixes the build being broken when building on Windows.
It also contains many fixes for timing issues which seem to impact macOS and Windows more than Linux.
* Fix .gitattributes and add *.xml_gen to fix line ending issues on Windows
* Derive fork count from CPU details in org.openhab.core tests for more stable tests on machines with fewer cores
* Adjust SafeCallerImplTest timings
* Increase ExecUtilTest timeout
* Increase SchedulerImplTest timeouts
* Increase AudioConsoleTest serveStream timeout
* Increase AudioServletTest serveStream timeout
* Increase SchedulerImplTest test timeouts
* Increase ExpireManagerTest timeout used for checking published events
* Increase PeriodicSchedulerImplTest max allowed delta
* Increase SchedulerImplTest timeouts
* Fix BundleInfoReader file stream …
=> Improve test stability and OS compatibility

bundles/org.openhab.core/src/main/java/org/openhab/core/common/AbstractUID.java, bundles/org.openhab.core/src/main/java/org/openhab/core/items/Metadata.java, bundles/org.openhab.core/src/main/java/org/openhab/core/items/MetadataKey.java
Fixes #2917
Fixes #2920 
This fixes a side-effect of #2901. The no-args constructor of `MetadataKey` and `Metadata` tried to invoke `ÀbstractUID(String segments...)` with empty strings. Due to the added check this failed. Since the no-args constructors are only used during deserialization we can call the no-args constructor of `AbstractUID` instead and don't care about the required number of segments.
=> Fix Metadata can't be deserialized

bundles/org.openhab.core/src/test/java/org/openhab/core/internal/scheduler/SchedulerImplTest.java
Fixes #2915 
Related to #2878 
This re-adds the delay before the job is cancelled.
=> Improve SchedulerImplTest

bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/handler/TimeBasedTriggerHandler.java, bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/module/handler/DateTimeTriggerHandler.java, bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/module/handler/TimerModuleHandlerFactory.java, bundles/org.openhab.core.automation/src/main/resources/OH-INF/automation/moduletypes/DateTimeTrigger.json, bundles/org.openhab.core/src/main/java/org/openhab/core/scheduler/CronAdjuster.java
=> Add new module DateTimeTrigger for triggering on a DateTime state

bundles/org.openhab.core.io.rest.core/pom.xml, bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/item/EnrichedItemDTOMapper.java, bundles/org.openhab.core.io.rest.core/src/test/java/org/openhab/core/io/rest/core/item/EnrichedItemDTOMapperTest.java
Fixes #2916 
Plain items can't have Childs and therefore should not be considered when calculating parents/childs of a group.
=> Fix "recursive membership detected" for plain items

bundles/org.openhab.core.automation.module.script/pom.xml, bundles/org.openhab.core.automation.module.script/src/main/java/org/openhab/core/automation/module/script/ScriptTransformationService.java, bundles/org.openhab.core.automation.module.script/src/test/java/org/openhab/core/automation/module/script/ScriptTransformationServiceTest.java, itests/org.openhab.core.automation.module.script.tests/itest.bndrun
Depends on #2821
Related to #2872 
=> Add a generic script transformation

bundles/org.openhab.core/src/main/java/org/openhab/core/service/AbstractWatchService.java, bundles/org.openhab.core/src/test/java/org/openhab/core/service/AbstractWatchServiceTest.java
The current implementation of the `AbstractWatchService` requires the directory to be known on instantiation. It is not possible to retrieve it from anywhere because the parent's constructor must be called first. The `WatchQueueReader` is customized (subscribed by WatchService instance) in `activate` and unsubscribed in `deactivate`. This PR adds a new method that allows changing the directory. If called, the old subscription is removed, the directory changed and the service activated again.
=> Allow changing watched directory of a WatchService

bundles/org.openhab.core.model.script/src.moved/test/java/org/openhab/core/model/script/actions/SemanticsTest.java, bundles/org.openhab.core.model.script/src/org/openhab/core/model/script/actions/Semantics.java
Resolve #2924 
Instead of returning the given item, getEquipment() and getLocation() return the item's parent Equipment / Location. This allows the caller to navigate the hierarchy, e.g. get the parent location of the given location.
=> [Semantics] Return parent Location and Equipment

bom/runtime/pom.xml, features/karaf/openhab-tp/src/main/feature/feature.xml
The `jackson-databind` bundle contains a vulnerability that is fixed in version 2.12.6.1. This version is only available for that bundle, all other bundles are still available as 2.12.6. This requires a manual revert for the `jackson-databind` bundle. I have added a note as comment. 
See #2882
=> Bump jackson to 2.12.6(.1)

bundles/org.openhab.core.audio/src/main/java/org/openhab/core/audio/internal/javasound/JavaSoundAudioSource.java, bundles/org.openhab.core.audio/src/main/java/org/openhab/core/audio/internal/javasound/JavaSoundInputStream.java
This is a proposed solution to address the microphone stream sharing on Windows.
The problem was fixed before for other OSs in this PR https://github.com/openhab/openhab-core/pull/2732 by opening separate microphone instances as it's supported on those platform. In that pr there is a workaround for windows to avoid  closing the shared mic input stream until all consumer have closed their streams, but still do not ensure that all the microphone data reach all the consumers.
I used the same solution here https://github.com/openhab/openhab-addons/blob/main/bundles/org.openhab.binding.pulseaudio/src/main/java/org/openhab/binding/pulseaudio/internal/PulseAudioAudioSource.java as the problem was the same (there is just one input source …
=> [Javasound] Fix microphone data line sharing on Windows OS

bundles/org.openhab.core.ui/src/main/java/org/openhab/core/ui/internal/components/ManagedPageProvider.java, bundles/org.openhab.core.ui/src/main/java/org/openhab/core/ui/internal/components/ManagedWidgetProvider.java, bundles/org.openhab.core.ui/src/main/java/org/openhab/core/ui/internal/components/UIComponentProvider.java, bundles/org.openhab.core.ui/src/main/java/org/openhab/core/ui/internal/components/UIComponentRegistryFactoryImpl.java, bundles/org.openhab.core.ui/src/main/java/org/openhab/core/ui/internal/components/UIComponentRegistryImpl.java, bundles/org.openhab.core.ui/src/main/java/org/openhab/core/ui/internal/components/UIProvider.java
This is to allow the UI registry & providers to follow the standard extensible pattern to allow osgi to supply other widgets and pages.
Fixes #2513 
=> UIRegistry now extensible, like other Registries

bundles/org.openhab.core.test.magic/src/main/java/org/openhab/core/magic/binding/internal/automation/modules/MagicMultiActionMarker.java, bundles/org.openhab.core.test.magic/src/main/java/org/openhab/core/magic/service/MagicMultiInstanceServiceMarker.java
This adds some spaces to the Magic service labels so they look nicer in UIs:
=> Add spaces to Magic service labels

bundles/org.openhab.core.ephemeris/src/main/java/org/openhab/core/ephemeris/internal/EphemerisManagerImpl.java, itests/org.openhab.core.ephemeris.tests/src/main/java/org/openhab/core/ephemeris/internal/EphemerisManagerImplOSGiTest.java
It has been reported in the past (and in the forum) that the EphemerisManagerImpl can't handle illegal configurations. Due to dependencies in other bundles this results in the whole automation component to be unavailable.
This PR adds code to strip illegal characters (which will solve most reported issues with additional double quotes) and just skips a days configuration with unknown day names (instead of failing to activate/modify the service in total).
=> Fix EphemerisManager crashing on invalid configuration

bundles/org.openhab.core.audio/src/main/java/org/openhab/core/audio/internal/AudioServlet.java, bundles/org.openhab.core.audio/src/test/java/org/openhab/core/audio/internal/AudioServletTest.java
Fixes #532
Add closing of streams on deactivation and add tests to ensure that all streams are closed after they are expired or retrieved.
There might be still one possible resource leak: a one-time stream that is served but never retrieved will stay in the map forever. But since that is exactly the wanted behavior for streams without timeout, there is nothing we can do about it. Those streams are only closed if the servlet is deactivated.
=> Fix resource leaks in AudioServlet

bundles/org.openhab.core.ui.icon/src/main/java/org/openhab/core/ui/icon/internal/CustomIconProvider.java, bundles/org.openhab.core.ui.icon/src/main/java/org/openhab/core/ui/icon/internal/IconServlet.java, bundles/org.openhab.core.ui.icon/src/test/java/org/openhab/core/ui/icon/internal/IconServletTest.java
Closes #2896 
This immediately works in Main UI, but needs an adjustment in Basic UI.
=> Allow sub-directories for icons

bundles/org.openhab.core.io.console.karaf/src/main/java/org/openhab/core/io/console/karaf/internal/CommandWrapper.java, bundles/org.openhab.core.io.console.karaf/src/main/java/org/openhab/core/io/console/karaf/internal/OSGiConsole.java
Fixes #1545
The `PrintStream` used for printing should not be `System.out` but the `PrintStream` associated with the `Session` of the karaf shell.
=> Fix console extension output to wrong console

bundles/org.openhab.core.io.console.karaf/bnd.bnd, bundles/org.openhab.core.io.console.karaf/pom.xml, bundles/org.openhab.core.io.console.karaf/src/main/java/org/openhab/core/io/console/karaf/internal/CommandWrapper.java, bundles/org.openhab.core.io.console.karaf/src/main/java/org/openhab/core/io/console/karaf/internal/InstallServiceCommand.java, bundles/org.openhab.core.karaf/bnd.bnd, bundles/org.openhab.core.karaf/pom.xml, features/karaf/openhab-core/src/main/feature/feature.xml, tools/static-code-analysis/pmd/suppressions.properties
=> Fix "openhab --help" and "help openhab" in Karaf console

pom.xml
Windows build was failing with:
```
[ERROR] Failed to execute goal org.commonjava.maven.plugins:directory-maven-plugin:0.3.1:highest-basedir (directories) on project org.openhab.core.reactor: Cannot find a single highest directory for this project set. First two candidates directories don't share a common root. -> [Help 1]
```
when started from directory: "C:\Users\Jacob Laursen\Development\jlaur\openhab-core"
Maven version: 3.8.5
The issue might have been fixed by jdcasey/directory-maven-plugin#17, but I'm not sure.  At least the build works after upgrading to 1.0.
I don't know if the upgrade can have any undesired side-effects, so PR is to be considered a proposal and I'm hoping maintainers can assess this.
See also releases here: …
=> Upgrade directory-maven-plugin from 0.3.1 to 1.0

bundles/org.openhab.core/src/main/java/org/openhab/core/items/ItemUtil.java
Fixes #2243 
Since numbers as first character of the item name cause issues and the documentation already states that they are not allowed, the validity check is adjusted to reflect the correct policy.
=> Fix item name checking in ItemUtil

bundles/org.openhab.core.addon.marketplace/src/main/java/org/openhab/core/addon/marketplace/AbstractRemoteAddonService.java, bundles/org.openhab.core.addon.marketplace/src/test/java/org/openhab/core/addon/marketplace/AbstractRemoteAddonServiceTest.java
It was reported that after an upgrade from aprevious version installed addons from marketplaces are not shown in the add-ons pages. This is a result of the new compatibility check which excludes incompatible add-ons by default. Already installed add-ons must be excluded from this check otherwise they can't be uninstalled.
=> Assume installed addons are compatible

bom/test/pom.xml, bundles/org.openhab.core.test/pom.xml, bundles/org.openhab.core.test/src/main/resources/logback-test.xml, bundles/org.openhab.core/src/test/resources/logback-test.xml
Related to #2939
Needed to solve issues in openhab-addons 
=> Fix log levels and duplicate implementation warning in tests

bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/provider/i18n/ModuleTypeI18nUtil.java, bundles/org.openhab.core.automation/src/main/resources/OH-INF/automation/moduletypes/GenericConditions.json, tools/i18n-plugin/pom.xml, tools/i18n-plugin/src/main/java/org/openhab/core/tools/i18n/plugin/BundleInfo.java, tools/i18n-plugin/src/main/java/org/openhab/core/tools/i18n/plugin/BundleInfoReader.java, tools/i18n-plugin/src/main/java/org/openhab/core/tools/i18n/plugin/GenerateDefaultTranslationsMojo.java, tools/i18n-plugin/src/main/java/org/openhab/core/tools/i18n/plugin/JsonToTranslationsConverter.java, tools/i18n-plugin/src/test/java/org/openhab/core/tools/i18n/plugin/BundleInfoReaderTest.java, tools/i18n-plugin/src/test/java/org/openhab/core/tools/i18n/plugin/JsonToTranslationsConverterTest.java, tools/i18n-plugin/src/test/java/org/openhab/core/tools/i18n/plugin/PropertiesToTranslationsConverterTest.java, tools/i18n-plugin/src/test/resources/acmeweather.bundle/OH-INF/automation/moduletypes/Modules.json, tools/i18n-plugin/src/test/resources/acmeweather.bundle/OH-INF/i18n/acmeweather.generated.properties, tools/i18n-plugin/src/test/resources/acmeweather.bundle/OH-INF/i18n/acmeweather.properties
=> Allow generation of default translations for automation modules

bundles/org.openhab.core.audio/src/main/java/org/openhab/core/audio/internal/javasound/JavaSoundAudioSource.java
Testing a new add-on I just discovered I broke the java sound for non windows OSs on my last change to it.
Fixed error:
```
java.lang.ClassCastException: class com.sun.media.sound.DirectAudioDevice$DirectTDL cannot be cast to class java.io.InputStream (com.sun.media.sound.DirectAudioDevice$DirectTDL is in module java.desktop of loader 'bootstrap'; java.io.InputStream is in module java.base of loader 'bootstrap')
```
Tested and working again on macOS, sorry for the problems.
=> [javasound] Fix invalid cast on non windows OSs

bundles/org.openhab.core.io.jetty.certificate/pom.xml
This is necessary for Java 17 source level.
=> Bump maven-shade-plugin to 3.3.0

tools/i18n-plugin/pom.xml
Needed for Java 17 source level. This also removes build errors with wrong scope and an unused dependency.
=> Bump maven-plugin-plugin to 3.6.4

bundles/org.openhab.core.model.rule/src/org/openhab/core/model/rule/Rules.xtext
This fixes a critical regression caused by #2963, which made the `equals` method disfunctional within rules.
This resulted in log messages like:
```
2022-06-06 11:30:46.587 [WARN ] [el.core.internal.ModelRepositoryImpl] - Configuration model 'test.rules' has errors, therefore ignoring it: [91,83]: no viable alternative at input 'equals'
```
It seems that Xtext is able to parse everything, if we use the same vocabulary as for the TimerTrigger, i.e. "is". The only drawback might be that the DateTime trigger cannot be used with items of name `midnight` or `noon`, but I think this is acceptable.
=> Fix DateTime trigger syntax to not break the equals function in the execution script

bundles/org.openhab.core.automation.module.script/src/main/java/org/openhab/core/automation/module/script/ScriptTransformationService.java, bundles/org.openhab.core.automation.module.script/src/test/java/org/openhab/core/automation/module/script/ScriptTransformationServiceTest.java, bundles/org.openhab.core.model.script.runtime/src/org/openhab/core/model/script/runtime/internal/engine/DSLScriptEngine.java, bundles/org.openhab.core.model.script/src/org/openhab/core/model/script/jvmmodel/ScriptJvmModelInferrer.xtend
This extends the DSL scriptengine to accept `inputString` as implicit variable in the engine context. By that DSL scripts can be used for the script transformation. 
=> Allow DSL scripts for script transformation

bom/compile-model/pom.xml
Someone added a dependency on a non-existing artifact in the new Equinox release and now many builds are broken because Xtext defines a version range for Equinox :disappointed:, see:
* https://github.com/eclipse-equinox/equinox.bundles/issues/54
* https://github.com/eclipse/xtext/issues/2077
=> Exclude org.osgi.service.prefs to fix build

bundles/org.openhab.core.io.rest.sse/src/main/java/org/openhab/core/io/rest/sse/internal/util/SseUtil.java, bundles/org.openhab.core.io.rest.sse/src/test/java/org/openhab/core/io/rest/sse/internal/util/SseUtilTest.java
Fixes #2473 
According to the [documentation](https://www.openhab.org/docs/developer/utils/events.html), topic filters are regular expressions. The SSE topic filters are converted to regular expressions, therefore `openhab/items/*/state` should result in `openhab/items/.*/state`. The code however adds a `.*` at the end `openhab/items/.*/state.*`. This makes it impossible to filter for `/state` but exclude `/statechanged`, which is IMO expected. 
=> Fix SSE topic filters

bom/compile-model/pom.xml
Reverts openhab/openhab-core#3001
Let's see if we need to manually clean some Maven repos for a successful build now that some of this mess was addressed with https://issues.sonatype.org/browse/OSSRH-81766.
=> Revert "Exclude org.osgi.service.prefs to fix build"

bundles/org.openhab.core.model.script/src/org/openhab/core/model/script/actions/ScriptExecution.java, bundles/org.openhab.core.model.script/src/org/openhab/core/model/script/internal/actions/TimerImpl.java, bundles/org.openhab.core/pom.xml, bundles/org.openhab.core/src/main/java/org/openhab/core/internal/scheduler/DelegatedSchedulerImpl.java, bundles/org.openhab.core/src/main/java/org/openhab/core/internal/scheduler/SchedulerImpl.java, bundles/org.openhab.core/src/main/java/org/openhab/core/scheduler/Scheduler.java, bundles/org.openhab.core/src/test/java/org/openhab/core/internal/scheduler/SchedulerImplTest.java
Closes #1255
Closes #2750 
Potentially API breaking, although I think that alternative scheduler implementations are unlikely. I could add a default for the new method that just throws away the identifier.
=> Add ability to name timers / scheduled jobs

itests/org.openhab.core.automation.integration.tests/src/main/java/org/openhab/core/automation/integration/test/AutomationIntegrationJsonTest.java
Nullness default is redundant with a default specified for the enclosing type AutomationIntegrationJsonTest.
=> Remove redundant `@NonNullByDefault`

itests/org.openhab.core.storage.json.tests/src/main/java/org/openhab/core/storage/json/internal/ThingMigrationOSGiTest.java
In Eclipse the `storageService` would be inferred as nullable which conflicts with the `ManagedThingProvider` non-null constructor argument.
=> Fix null analysis error in ThingMigrationOSGiTest

bundles/org.openhab.core.config.core/src/main/java/org/openhab/core/config/core/internal/validation/MinMaxValidator.java, bundles/org.openhab.core.config.core/src/test/java/org/openhab/core/config/core/internal/validation/ConfigDescriptionValidatorTest.java
Reported on the forum. The problem is that on deserialization 255 is deserialized to a `BigDecimal` without scale. The validation the fails because the `BigDecimal` is converted to a `255.0` string, which is not equal to the `255` string from the config description option. The value is now properly normalized.
=> Fix config validation for integer values

bundles/org.openhab.core/src/main/java/org/openhab/core/service/WatchQueueReader.java
This addresses https://community.openhab.org/t/openhab-3-3-milestone-discussion/132715/220
@openhab/core-maintainers: I don't know how likely this race condition is to happen - please decide whether you consider it critical and merge it for 3.3 or leave it for later.
=> Fix ConcurrentModificationException in WatchQueueReader

bundles/org.openhab.core/src/main/java/org/openhab/core/common/AbstractUID.java
https://community.openhab.org/t/openhab-3-3-release-discussion/136925/18
The segments are now integrated in the message so it's easier to determine which UID was wrong.
=> Improve UID error message

bundles/org.openhab.core.karaf/src/main/java/org/openhab/core/karaf/internal/FeatureInstaller.java, bundles/org.openhab.core.karaf/src/main/java/org/openhab/core/karaf/internal/KarafAddonService.java
OH1 add-ons are not present in the OH3 distribution as they are not supported anyway, so we do not to filter them.
=> Remove OH2 leftover in Karaf Add-On service

bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/module/factory/CoreModuleHandlerFactory.java, bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/module/handler/GroupCommandTriggerHandler.java, bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/module/handler/GroupStateTriggerHandler.java, bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/module/handler/ItemCommandTriggerHandler.java, bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/module/handler/ItemStateConditionHandler.java, bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/module/handler/ItemStateTriggerHandler.java, bundles/org.openhab.core.automation/src/test/java/org/openhab/core/automation/internal/module/handler/ItemStateConditionHandlerTest.java
Closes #2526 
The solution here not only works for DSL but for all rules since the check is done in the module handler.
=> Log a warning when item for trigger/condition is missing or removed

bundles/org.openhab.core.addon.marketplace/src/main/java/org/openhab/core/addon/marketplace/internal/community/CommunityMarketplaceAddonService.java
Fixes #3040 
Instead of using the full id (`marketplace:123456`) the id without service prefix was used to lookup installed add-ons. This is not an issue if the network is available because then the information is request from the forum. If no network connection is present it obviously fails.
This also reduces the log level in the case of connection issues. ERROR is to much and the stack trace is not necessary.
=> Fix marketplace add-on uninstall

bundles/org.openhab.core.config.discovery/src/main/java/org/openhab/core/config/discovery/inbox/Inbox.java, bundles/org.openhab.core.config.discovery/src/main/java/org/openhab/core/config/discovery/internal/PersistentInbox.java, bundles/org.openhab.core.config.discovery/src/test/java/org/openhab/core/config/discovery/internal/PersistentInboxTest.java, itests/org.openhab.core.config.discovery.tests/src/main/java/org/openhab/core/config/discovery/DiscoveryServiceRegistryOSGiTest.java, itests/org.openhab.core.config.discovery.tests/src/main/java/org/openhab/core/config/discovery/internal/InboxOSGiTest.java, itests/org.openhab.core.config.discovery.tests/src/main/java/org/openhab/core/config/discovery/test/DummyThingTypeProvider.java
Fixes #1393
An alternative implementation would not break API (the return type of the `add` method would still be `boolean`), but this would move the retry-logic to the discovery service. IMO it is cleaner to have it in the `PersistentInbox` as it is specific to this implementation. It would also be difficult if the discovery result is rejected because the thing is already present.
The benefit of waiting on the thing type is that the normalization of the configuration values will always be possible.
=> Wait for thing-type available in PersistentInbox

bundles/org.openhab.core.io.console/src/main/java/org/openhab/core/io/console/internal/extension/MetadataConsoleCommandExtension.java, bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/internal/item/ItemResource.java
This adds similar functionality that is available for links with #2970. Also support for cleaning the metadata registry is added. Regarding exposing the compression functionality the general question in #2970 should be answered.
=> Allow bulk deletion of metadata

bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/internal/item/ItemResource.java, bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/internal/link/ItemChannelLinkResource.java, bundles/org.openhab.core.io.rest.core/src/test/java/org/openhab/core/io/rest/core/internal/link/ItemChannelLinkResourceTest.java, bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/link/ItemChannelLinkRegistry.java, bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/link/ManagedItemChannelLinkProvider.java, itests/org.openhab.core.thing.tests/src/main/java/org/openhab/core/thing/link/ItemChannelLinkOSGiTest.java
Closes #1454 
This add support for deleting all item-channel-links to an item or to a thing. This allows support for preventing orphaned links in UI (similar to the "delete item" when unlinking a channel). 
Also support for removing all orphaned links in the registry is added. I'm not sure where to expose this in the API. Something like `POST /links/compress` would be my first choice, but considering that we have the same issue with orphaned metadata and `POST /items/compress` is not possible (that is already used for sending a command to an item names `compress`), I'm not convinced that this is the best solution. Any ideas?
=> Add REST support for deleting links and removing orphaned links

bundles/org.openhab.core.test/pom.xml
Related to #2982
This fixes the warning reported in the attached PR. Technically this dependency is not necessary but it's missing in the PMD class path if it is not explicitly added here.
=> Fix build warnings in addons

bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/module/handler/DateTimeTriggerHandler.java, bundles/org.openhab.core.automation/src/main/resources/OH-INF/automation/moduletypes/DateTimeTrigger.json, bundles/org.openhab.core.model.rule.runtime/src/org/openhab/core/model/rule/runtime/internal/DSLRuleProvider.java, bundles/org.openhab.core.model.rule/src/org/openhab/core/model/rule/Rules.xtext
Extends the DateTimeTrigger introduced in ca94fd5 and dd13da5 to allow triggering only when the time matches to allow for daily triggers.
I tried to use "Time is time of item" as trigger for DSL-Rules first as that seems to better fit into the existing model but unfortunately that breaks the existing rules, so "Time matches time of" was chosen instead. Other ideas are very welcome.
=> Add "time only"-Option for DateTimeTrigger in rules

bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/module/handler/DateTimeTriggerHandler.java, bundles/org.openhab.core.automation/src/test/java/org/openhab/core/automation/internal/module/handler/DateTimeTriggerHandlerTest.java
Fix #3059
To test, install the jar from: https://github.com/jimtng/openhab-core/releases/tag/datetimetrigger-0.0.1
=> [DateTimeTrigger] Adjust to system timezone

bundles/org.openhab.core.io.transport.mqtt/src/main/java/org/openhab/core/io/transport/mqtt/MqttBrokerConnection.java, bundles/org.openhab.core.io.transport.mqtt/src/main/java/org/openhab/core/io/transport/mqtt/MqttBrokerConnectionConfig.java
This allows for using some additional configuration parameters in MQTT broker configurations.
See: https://github.com/openhab/openhab-addons/pull/13303
=> Add additional `MqttBrokerConnectionConfig` options

bundles/org.openhab.core.io.rest.sse/src/main/java/org/openhab/core/io/rest/sse/internal/SseItemStatesEventBuilder.java
Fixes #3067 
Signed-off-by: Anders Alfredsson <andersb86@gmail.com>
=> Use configured locale for SSE displayState

bundles/org.openhab.core.ui/src/main/java/org/openhab/core/ui/internal/components/UIComponentSitemapProvider.java
This adds the missing parameters to the sitemap provider. This allows the UI to be further extended in a follow-up PR and make the sitemap UI configuration support the same features as textual configuration.
Signed-off-by: Mark Herwege <mark.herwege@telenet.be>
=> Add visibility and color parameters to UI sitemap provider

bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/internal/thing/ThingResource.java
- Check for an existing thing handler before updating config
Otherwise you will see an ISE in your log when updating a disabled thing.
```
2022-09-09 15:04:58.259 [ERROR] [st.core.internal.thing.ThingResource] - Exception during HTTP PUT request for update config at 'things/avmfritz:Comet_DECT:XXX:YYY/config'
java.lang.IllegalStateException: Thing with UID avmfritz:Comet_DECT:XXX:YYY has no handler attached.
at org.openhab.core.thing.internal.ThingRegistryImpl.updateConfiguration(ThingRegistryImpl.java:96) ~[?:?]
at org.openhab.core.io.rest.core.internal.thing.ThingResource.updateConfiguration(ThingResource.java:498) ~[?:?]
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
at …
```
=> [rest] Check for an existing thing handler before updating config

bundles/org.openhab.core.io.net/src/main/java/org/openhab/core/io/net/http/PEMTrustManager.java
- Rethrow `IOException` instead of swallowing it
In case of unreachable servers there is an `IOException` leading to an error message in the log file. This case can be handled even better when rethrowing the thrown exception which allows the calling instance to react to server side errors.
https://community.openhab.org/t/vizio-tv-binding/138367/12
=> [tls] Rethrow 'IOException' instead of swallowing it

bundles/org.openhab.core.auth.oauth2client/pom.xml, bundles/org.openhab.core.auth.oauth2client/src/main/java/org/openhab/core/auth/oauth2client/internal/OAuthStoreHandlerImpl.java, bundles/org.openhab.core.auth.oauth2client/src/test/java/org/openhab/core/auth/oauth2client/OAuthStoreHandlerTest.java
This fixes a regression of #3066 where serialization and deserialization to and from storage was broken after migrating from `LocalDateTime` to `Instant`.
Value will now correctly be serialized as `Instant` into the store, and deserialization supports both `Instant` and `LocalDateTime` (for backwards compatibility).
=> [oauth] Fix access token serialization/deserialization

bundles/org.openhab.core.karaf/src/main/java/org/openhab/core/karaf/internal/FeatureInstaller.java, features/karaf/openhab-core/pom.xml, features/karaf/openhab-core/src/main/feature/feature.xml, features/karaf/openhab-tp/pom.xml, features/karaf/openhab-tp/src/main/feature/feature.xml
There are some flaws in the `FeatureInstaller` which this PR tries to solve. While debugging #3025 I found that the periodic sync job sets the config cache before the configuration is applied. This might lead to issues if another call to `modified` re-sets the configuration to something else but does not update the configuration cache. It is also not ensured that all configuration updates are processed in the order they arrive, so the asynchronous processing of the updates might result in an older configuration overwriting a newer one. 
This PR 
- introduces a queue that holds the configuration supplied to `modified` and processes them in the correct order 
- ensures that configuration cache is properly updated when an update is processed (independent from the configuration source)
- …
=> Improve FeatureInstaller

bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/events/ThingStatusInfoEvent.java, bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/internal/ThingManagerImpl.java, bundles/org.openhab.core.thing/src/test/java/org/openhab/core/thing/internal/ThingManagerImplTest.java, itests/org.openhab.core.thing.tests/src/main/java/org/openhab/core/thing/internal/ThingManagerOSGiTest.java
A thing always has a status. This status is not properly propagated to the event bus when the thing is added. This e.g. leads to a situation where a thing's first status that is received by am event subscriber is "INITIALIZING" instead of "UNINITIALIZED". The status should always be sent so that the thing lifecycle can properly be tracked by event listeners.
=> Fix missing initial thing status event

bundles/org.openhab.core/src/main/java/org/openhab/core/internal/items/ManagedMetadataProviderImpl.java
Fixes #1904 
The reason is that GSON de-serializes numeric metadata configuration values from JSON storage to `Double`, while textual defined values are `BigDecimal`. This PR adds normalization of the entries provided by the managed provider.
=> Normalize Metadata configuration from managed provider

bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/internal/ThingManagerImpl.java
There were some reports on the forum that de-serialized values (and probably other) do not have the correct type. We already normalize thing configurations when they are set via REST API, but it seems that under some circumstances integer values are not properly de-serialized. This PR adds normalization of the configuration before the thing is initialized. 
This is not the best solution, but unfortunately it'll get very complex otherwise. The best would be to normalize the configuration immediately when it is read from the database, but that can't be done because the config description needed for that is not available at the time the thing registry is first filled. Holding back things in the `ManagedProvider` would require keeping track of the config descriptions and thus duplicating what …
=> Normalize thing configuration before initialization

bom/compile/pom.xml, bom/runtime/pom.xml, features/karaf/openhab-tp/src/main/feature/feature.xml
Upgrades Californium from 2.0.0 to 2.7.3 which has many fixes.
For release notes see:
* https://projects.eclipse.org/projects/iot.californium/governance
Replaces #3061, #3062
---
Feature verification only succeeds when using the Eclipse Orbit version of net.i2p.crypto.eddsa.
So [net.i2p.crypto.eddsa_0.3.0.v20220506-1020.jar](https://download.eclipse.org/releases/2022-06/202206151000/plugins/net.i2p.crypto.eddsa_0.3.0.v20220506-1020.jar) needs to be added to the OH Maven Repo before CI will succceed.
=> Upgrade Californium to 2.7.3

bundles/org.openhab.core/src/main/java/org/openhab/core/service/StartLevelService.java
Unregistered trackers aren't clear, so then we never register new trackers, and thus never get notified of any changes.
=> Fix StartLevelService "hanging" if config is changed.

bundles/org.openhab.core.io.rest.sse/src/main/java/org/openhab/core/io/rest/sse/SseResource.java
Browser SSE implementations  have no support for monitoring connection states once a connection is made.  This makes detecting the health of our UI problematic.  This PR adds a separate 'keepalive' message to the SSE stream using the 'keepalive' event name, so should not affect existing clients who may not support this new message.  The message itself contains the interval value so clients can easily discover and setup their own watchdog functions. 
See https://github.com/openhab/openhab-webui/issues/1441 for information on the UI point of view of this issue. 
Signed-off-by: Dan Cunningham <dan@digitaldan.com>
=> Support sending a keepalive packet to SSE item state connections

bundles/org.openhab.core.model.script/src/org/openhab/core/model/script/internal/actions/TimerImpl.java
- Use identifier when rescheduling the timer
In #2911 a new feature to name the timer has been introduced. The identifier should be used for rescheduled timers too.
=> Use identifier when rescheduling the timer

bundles/org.openhab.core.automation.module.script.rulesupport/src/main/java/org/openhab/core/automation/module/script/rulesupport/loader/ScriptFileReference.java, bundles/org.openhab.core.automation.module.script.rulesupport/src/test/java/org/openhab/core/automation/module/script/rulesupport/loader/ScriptFileWatcherTest.java
The docs say that JSR223 scripts will be loaded in order of start level (as defined by filename or containing folder). this works (mostly) fine when you're stepping through start levels sequentially on startup, but if you're already at SL100, and have scripts located in sl folders, and then install an addon for those scripts, they were loading in alphabetic order instead. This ensures they'll still respect start level order relative to each other.
This should also fix the case of script start levels not matching start levels OpenHAB actually steps through (which are all multiples of 10) - i.e. if you define scripts in sl30, sl31, and sl32, when OpenHAB jumps from 30 to 40, 31 should be executed before 32.
=> [rulesupport] sort JSR223 scripts by start level before filename

bundles/org.openhab.core.io.rest.auth/src/main/java/org/openhab/core/io/rest/auth/internal/AuthFilter.java, bundles/org.openhab.core.io.rest.auth/src/test/java/org/openhab/core/io/rest/auth/internal/AuthFilterTest.java
Follow-up to #3106 
See also: https://community.openhab.org/t/authfilter-has-arrayindexoutofboundexception/139866/7
The code did not properly handle an empty network. This also adds test for implicit user role handling and trusted networks.
@openhab/core-maintainers I beliebe this is critical as it breaks all installations until either this is merged or the user configures a trusted network (which should not be done in general).
=> Fix AuthFilter crash if trusted network not configured

bundles/org.openhab.core.automation.module.script/src/main/java/org/openhab/core/automation/module/script/internal/defaultscope/DefaultScriptScopeProvider.java, bundles/org.openhab.core.model.script/src/org/openhab/core/model/script/scoping/ScriptImplicitlyImportedTypes.java
- Add more basic time-related classes for usage in script and rules
Allows comparisons like `new DateTimeType().zonedDateTime.getDayOfWeek() = DayOfWeek.MONDAY` or `new DateTimeType().zonedDateTime.getMonth() = Month.APRIL` in rules or scripts.
=> [automation] Add more basic time-related classes for usage in script and rules

bundles/org.openhab.core.io.rest.sse/src/main/java/org/openhab/core/io/rest/sse/internal/SseItemStatesEventBuilder.java, bundles/org.openhab.core.model.script/src/org/openhab/core/model/script/lib/NumberExtensions.java, bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/internal/profiles/SystemHysteresisStateProfile.java, bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/internal/profiles/SystemRangeStateProfile.java, bundles/org.openhab.core.ui/src/main/java/org/openhab/core/ui/internal/items/ItemUIRegistryImpl.java, bundles/org.openhab.core/src/main/java/org/openhab/core/library/items/NumberItem.java, bundles/org.openhab.core/src/main/java/org/openhab/core/library/types/QuantityType.java, bundles/org.openhab.core/src/main/java/org/openhab/core/library/types/QuantityTypeArithmeticGroupFunction.java, bundles/org.openhab.core/src/main/java/org/openhab/core/library/unit/Units.java, bundles/org.openhab.core/src/main/java/org/openhab/core/types/util/UnitUtils.java, bundles/org.openhab.core/src/test/java/org/openhab/core/library/items/NumberItemTest.java, bundles/org.openhab.core/src/test/java/org/openhab/core/library/types/QuantityTypeTest.java
Mireds are fairly common to describe the color temperature of lightbulbs (slightly less common than Kelvin), but are very useful for various calculations when adjusting the color temperature, as well as being necessary for various integerations that require mired units.
This commit makes them a well-known unit (previously they were still usable, using "MK^-1"), as well as making them easier to work with on QuantityType. The hiccup is that Mireds aren't technically a Temperature dimension, because they're a reciprocal. So add a `inverse` method that delegates to javax.measure's same method, and then use it as necessary when doing unit conversions and comparisons. Unfortunately, because the dimension changes, the return value of a conversion won't necessarily be the same type, an additional …
=> Support mired units

bundles/org.openhab.core.io.console.karaf/src/main/java/org/openhab/core/io/console/karaf/internal/CommandWrapper.java, bundles/org.openhab.core.io.console.karaf/src/main/java/org/openhab/core/io/console/karaf/internal/CompleterWrapper.java, bundles/org.openhab.core.io.console.karaf/src/test/java/org/openhab/core/io/console/karaf/internal/CompleterWrapperTest.java, bundles/org.openhab.core.io.console/src/main/java/org/openhab/core/io/console/Completer.java, bundles/org.openhab.core.io.console/src/main/java/org/openhab/core/io/console/ConsoleCommandCompleter.java, bundles/org.openhab.core.io.console/src/main/java/org/openhab/core/io/console/StringsCompleter.java, bundles/org.openhab.core.io.console/src/main/java/org/openhab/core/io/console/extensions/ConsoleCommandExtension.java, bundles/org.openhab.core.io.console/src/main/java/org/openhab/core/io/console/internal/extension/ItemConsoleCommandCompleter.java, bundles/org.openhab.core.io.console/src/main/java/org/openhab/core/io/console/internal/extension/ItemConsoleCommandExtension.java, bundles/org.openhab.core.io.console/src/main/java/org/openhab/core/io/console/internal/extension/SendConsoleCommandExtension.java, bundles/org.openhab.core.io.console/src/main/java/org/openhab/core/io/console/internal/extension/StatusConsoleCommandExtension.java, bundles/org.openhab.core.io.console/src/main/java/org/openhab/core/io/console/internal/extension/UpdateConsoleCommandExtension.java, bundles/org.openhab.core.io.console/src/test/java/org/openhab/core/io/console/StringsCompleterTest.java, bundles/org.openhab.core.io.console/src/test/java/org/openhab/core/io/console/internal/extension/ItemConsoleCommandCompleterTest.java, bundles/org.openhab.core.io.console/src/test/java/org/openhab/core/io/console/internal/extension/ItemConsoleCommandExtensionTest.java
And subcommands can implement it if they want. At the least the CommandConsoleExtension's description will now be visible in tab-completion.
I've also implemented detailed completion for openhab:items, openhab:status, openhab:send, and openhab:update.
=> Implement command completion in console for openhab command

bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/module/handler/ItemStateConditionHandler.java, bundles/org.openhab.core.automation/src/test/java/org/openhab/core/automation/internal/module/handler/ItemStateConditionHandlerTest.java
Dimmer items return their state as PercentType. The code did not properly handle PercentType because PercentType is a subclass of DecimalType. One value was converted by casting the value to DecimalType (which leads to 40 for 40%) while the other one used `.as` (which results in 0.4 for 40%). A comparison "state <= 50" with state = 20 is therefore executed as "20 <= 0.5"  which is not what the user would expect.
Reported on the forum.
=> Fix ItemStateCondition for PercentType values

bundles/org.openhab.core.io.rest.core/pom.xml, bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/internal/item/ItemResource.java, itests/org.openhab.core.io.rest.core.tests/itest.bndrun, itests/org.openhab.core.io.rest.core.tests/src/main/java/org/openhab/core/io/rest/core/internal/item/ItemResourceOSGiTest.java
Closes #2977
The approach here is a little bit broader than what was originally requested. The new endpoint delivers the item matching the provided semantic tag for a given item. To get the physical location, `Location` has to be used. 
=> [rest] add semantics query endpoint  to item resource

bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/module/factory/CoreModuleHandlerFactory.java, bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/module/handler/ItemStateConditionHandler.java, bundles/org.openhab.core.automation/src/test/java/org/openhab/core/automation/internal/module/handler/ItemStateConditionHandlerTest.java
This adds the capability to handle `DateTime` items to the `ItemStateConditionHandler`. The given state can be
- the string representation of a `ZonedDateTime` (e.g. `2022-01-15T17:23:15+02:00`)
- the string representation of a `LocalDateTime` (e.g. `2022-11-06T16:05:10`), the configured time zone from the `TimeZoneProvider` is used
- a period that is applied to the current time (`ZonedDateTime.now()`). The period can contain days (`D`), hours (`H`), minutes (`M`) or seconds (`S`) or an ordered combination of these, including a sign (e.g. `1D-2H` would be the same as `ZonedDateTime.now().plusDays(1).minusHours(2)`).
I didn't find the documentation for the conditions in general, can someone point me to the correct place so that documentation for this can be added?
Signed-off-by: Jan N. …
=> Add DateTime handling to ItemStateConditionHandler

bundles/org.openhab.core.io.transport.mqtt/src/main/java/org/openhab/core/io/transport/mqtt/internal/Subscription.java, bundles/org.openhab.core.io.transport.mqtt/src/test/java/org/openhab/core/io/transport/mqtt/MqttBrokerConnectionTests.java
Only the _first_ message has the retained flag (always on MQTT3, there is a flag to forward the retain flag on all messages with MQTT5, but we don't set it), so we have to keep track of previously retained messages as well.
This shows up as when a thing comes back online and re-subscribes to a retained message that another thing subscribed to also, it won't see any changes that happened to that topic since the very first message was received.
=> [mqtt] Properly process retained messages

bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/DefaultSystemChannelTypeProvider.java
refs https://github.com/openhab/openhab-addons/pull/13570#issuecomment-1288139778
now that Kelvin and mireds/mireks are easily convertible
=> update system.color-temperature-abs channel type to be a Number:Temperature

bundles/org.openhab.core.io.transport.mqtt/src/main/java/org/openhab/core/io/transport/mqtt/internal/Subscription.java, bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/link/AbstractLinkRegistry.java, bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/link/ItemChannelLinkRegistry.java
To mitigate issue #3125 (common thread pool exhaustion when combining parallel streams with `synchronization` or locks)
=> Avoid parallel streams with common thread pool to avoid deadlocks

bundles/org.openhab.core.voice/src/main/java/org/openhab/core/voice/internal/DialogProcessor.java, bundles/org.openhab.core.voice/src/main/java/org/openhab/core/voice/internal/VoiceManagerImpl.java
Introduces two small changes on the Voice manager:
* Register current running single shot dialog instances so they can be stoped by the voice manager stop method.
* Allow the execution of a single dialog when calling the listenAndAnswer method with the same configurations that other dialog processor running persistently. 
Explanation on the second point: Before, any call to this method that collide by source id with a registered processor was rejected, but if you are using same configurations (ignoring the keyword),I think that makes sense to trigger a dialog execution with the registered dialog processor and the DialogProcessor class implementation already ensures that the keyword will be ignored while processing so there should be no problems on doing so.
Let me know if anything needs …
=> [voice] Allow stop single dialogs and start dialog on an existing processor

bundles/org.openhab.core/src/main/java/org/openhab/core/internal/items/ItemRegistryImpl.java, bundles/org.openhab.core/src/main/java/org/openhab/core/items/GroupItem.java, itests/org.openhab.core.tests/src/main/java/org/openhab/core/items/ItemRegistryImplTest.java
Fixes #2449 
The stateDescriptionProvider was not properly passed to the base item. Because of that units set in the state description were not properly used when setting the griup state after calculating aggregation functions.
=> Fix missing stateDescriptionProvider in Group items

bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/internal/ThingManagerImpl.java
Fixes #3122 
The reason is that the "oldThing" is once again retrieved from the storage, not from the registry (where the normalized values are stored).
=> Fix config normalization in ThingUpdatedEvent

bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/RuleManager.java, bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/RuleEngineImpl.java, bundles/org.openhab.core.model.rule.runtime/src/org/openhab/core/model/rule/runtime/internal/DSLRuleProvider.java
This allows access to unmanaged DSL scripts from all rules. This is achieved by adding them as rules with tag `Script` (like managed scripts) to the `RuleRegistry`. Thy can now be called in the same way as managed scripts.
In addition the script context is made accessible as return value for `runNow` methods which will later allow calling scripts with their return value from scripted rules or other scripts.
=> Add unmanaged scripts to rule registry

bundles/org.openhab.core.io.http.auth/src/main/java/org/openhab/core/io/http/auth/internal/AuthorizePageServlet.java
Found this small bug while reading the authorization code.
Edit: couple of lines after is enforcing the client id to match the refresh token which is now always true. 
=> [auth] Fix wrong parameter on AuthorizePageServlet

bundles/org.openhab.core.automation.module.script/src/main/java/org/openhab/core/automation/module/script/action/ScriptExecution.java, bundles/org.openhab.core.automation.module.script/src/main/java/org/openhab/core/automation/module/script/action/Timer.java, bundles/org.openhab.core.automation.module.script/src/main/java/org/openhab/core/automation/module/script/internal/action/ScriptActionScriptScopeProvider.java, bundles/org.openhab.core.automation.module.script/src/main/java/org/openhab/core/automation/module/script/internal/action/ScriptExecutionImpl.java, bundles/org.openhab.core.automation.module.script/src/main/java/org/openhab/core/automation/module/script/internal/action/TimerImpl.java, bundles/org.openhab.core.automation.module.script/src/test/java/org/openhab/core/automation/module/script/TimerImplTest.java, bundles/org.openhab.core.model.script/bnd.bnd, bundles/org.openhab.core.model.script/pom.xml, bundles/org.openhab.core.model.script/src/org/openhab/core/model/script/actions/ScriptExecution.java, bundles/org.openhab.core.model.script/src/org/openhab/core/model/script/internal/engine/action/ScriptExecutionActionService.java
JSR-223 automation add-ons often use the script actions from the `org.openhab.core.model.script` bundle. The downside is that the actions are tied to XText, making it impossible for the automation add-ons to modify/wrap these actions without explicit dependency on XText (see #3128).
This is the first step to refactor these actions to plain Java, making them available as `ScriptExtension` via an import-preset `ScriptAction` which is not imported by default to prevent unwanted shadowing of other components. They are wrapped for DSL rules, to stay backward compatible.
=> Refactor ScriptExecution to plain Java ScriptExtension

bundles/org.openhab.core.automation/src/test/java/org/openhab/core/automation/internal/module/handler/ItemStateConditionHandlerTest.java, bundles/org.openhab.core/src/main/java/org/openhab/core/library/items/NumberItem.java, bundles/org.openhab.core/src/main/java/org/openhab/core/library/types/QuantityType.java, bundles/org.openhab.core/src/test/java/org/openhab/core/library/items/NumberItemTest.java
Related to #3121 
As discussed in the linked issue: The state of a `Number` item (i.e. without dimension) is expected to be `DecimalType` without a unit. If a state update is posted or command received that is of `QuantityType` the unit should be stripped to ensure that.
=> Strip unit if NumberItem has no dimension

bundles/org.openhab.core/src/main/java/org/openhab/core/internal/i18n/I18nProviderImpl.java, bundles/org.openhab.core/src/main/java/org/openhab/core/library/unit/ImperialUnits.java, bundles/org.openhab.core/src/test/java/org/openhab/core/internal/i18n/I18nProviderImplTest.java, bundles/org.openhab.core/src/test/java/org/openhab/core/library/unit/UnitsTest.java
Fixes #3150 
Fixes #3121 
Fixes #3096 
It would be great if someone from the US could check if I did pick good units for the imperial measurement system or if something is missing there. 
=> Add default units for all dimensions

bundles/org.openhab.core.persistence/src/main/java/org/openhab/core/persistence/FilterCriteria.java
See https://github.com/openhab/openhab-addons/issues/9906#issuecomment-1317604058
Most persistence implementations filters by `beginDate` <=date <= `endDate` which contradicts the Javadoc comments with proposed changes in this PR. The exception is JDBC persistence which lead to openhab/openhab-addons#9906.
Therefore, I would propose to either:
- Close this PR and fix persistence services RRD4j, JPA and MongoDB.
- Consider/merge this PR and fix persistence service JDBC according to mentioned issue. openhab/openhab-addons#13734 prepared.
=> [persistence] Clarify intention of FilterCriteria beginDate/endDate

bundles/org.openhab.core.automation.module.script.rulesupport/src/main/java/org/openhab/core/automation/module/script/rulesupport/shared/RuleSupportRuleRegistryDelegate.java, bundles/org.openhab.core.automation.module.script.rulesupport/src/main/java/org/openhab/core/automation/module/script/rulesupport/shared/ScriptedRuleProvider.java
extend AbstractProvider so that it doesn't need to re-implement managing listeners, and have it implement ManagedProvider
=> tweak ScriptedRuleProvider slightly

bundles/org.openhab.core/src/main/java/org/openhab/core/library/types/HSBType.java, bundles/org.openhab.core/src/test/java/org/openhab/core/library/types/HSBTypeTest.java
Pattern %s will match `<hue>,<saturation>,<brightness>`
Pattern %hsb% will match `<hue>,<saturation>,<brightness>`
Pattern %rgb% will match `<red>,<green>,<blue>`
Related to discussion in openhab/openhab-webui#427
=> Define format method for HSBType

bundles/org.openhab.core.automation.module.script/src/main/java/org/openhab/core/automation/module/script/internal/ScriptEngineManagerImpl.java
The scripts are user code, so in order to help them debug their code, the full stack trace is very useful.
=> log full exception information when calling JSR223 scripts

bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/internal/profiles/SystemOffsetProfile.java, bundles/org.openhab.core/src/main/java/org/openhab/core/library/types/QuantityType.java, bundles/org.openhab.core/src/test/java/org/openhab/core/library/types/QuantityTypeTest.java
this is a useful helper that can eliminate some complicated code elsewhere. starting in SystemOffsetProfile. then I also want to use it in the homekit addon.
extracted from https://github.com/openhab/openhab-core/pull/3132, since the StateDescription portion of that PR is still being discussed what direction to go
=> add QuantityType.toUnitRelative

bundles/org.openhab.core.automation.module.script/src/main/java/org/openhab/core/automation/module/script/internal/action/TimerImpl.java
When writing tests and mocking time, it can be important that execution_time match _exactly_ with what was sent to reschedule(). When re-calculating based on now and the expected remaining delay, this might be off by a few milliseconds. We have the exact time that was requested already, so might as well use it.
=> return the precise scheduled execution time for timers

bundles/org.openhab.core.automation.module.script/src/main/java/org/openhab/core/automation/module/script/internal/ScriptEngineManagerImpl.java, bundles/org.openhab.core.automation.module.script/src/test/java/org/openhab/core/automation/module/script/internal/ScriptEngineManagerImplTest.java
=> wrap ScriptEngine executions in a SafeCaller

bundles/org.openhab.core.automation.module.script.rulesupport/src/main/java/org/openhab/core/automation/module/script/rulesupport/internal/CacheScriptExtension.java, bundles/org.openhab.core.automation.module.script.rulesupport/src/main/java/org/openhab/core/automation/module/script/rulesupport/shared/ValueCache.java, bundles/org.openhab.core.automation.module.script.rulesupport/src/test/java/org/openhab/core/automation/module/script/rulesupport/internal/CacheScriptExtensionTest.java
Closes #2084
Closes #2881 
Closes #2943 
Depends on #2886
This implements option 1 that was discussed in #2084 (which seems to be what most comments prefer). It is remotely based on the code here: https://github.com/openhab/openhab-addons/blob/4f4dfcca20f39c2d8ed059b67e1dba09c9c83957/bundles/org.openhab.automation.jsscripting/src/main/java/org/openhab/automation/jsscripting/internal/scope/SharedCache.java.
Two separate key-value-caches are implemented:
1. `privateCache`: It is created per `scriptIdentifier` and can only be accessed from the same script. It is not cleared between two subsequent runs of a rule but removed when the script is unloaded. This can be used e.g. to store timers. 
2. `sharedCache`: It is shared between all scripts. Every access to a certain key in the cache is …
=> Add an access-tracking cache to be used in rules

bundles/org.openhab.core.voice/src/main/java/org/openhab/core/voice/internal/VoiceManagerImpl.java
I broke the startDialog voice customization when creating the new methods on the VoiceManager.
Was merged few days ago.
Sorry for the troubles.
=> [voice] Fix start dialog with non default voice (broken recently)

bundles/org.openhab.core.io.rest.sse/src/main/java/org/openhab/core/io/rest/sse/SseResource.java
Simple attempt to fix #3192.
I am not really certain how the `sse` field could end up being `null`, but possibly the job is only executed after the `SseResource` has been destroyed already due to a service/bundle restart.
=> Prevent NPE in SseResource

tools/archetype/binding/src/main/resources/archetype-resources/README.md
This is mainly based on my workings for consistent markdown doc files, i am currently doing in the docs repo and also for the many addons.
Hopefully it will increase the consistency by providing predefined code examples.
I have adapted the templating simply from other headlines without further research and hope that it is correct already.
References:
openhab/openhab-addons#13858
openhab/openhab-docs#999
=> [Binding Skeleton] Add doc code examples

bundles/org.openhab.core.automation.module.script.rulesupport/src/main/java/org/openhab/core/automation/module/script/rulesupport/internal/CacheScriptExtension.java
The check for scheduling a cancellation task did not include the `Timer` class of the automation bundle.
@florian-h05 Can you check if this works for you?
=> Fix timer cancellation in automation cache

bom/compile/pom.xml, bom/openhab-core/pom.xml, bundles/org.openhab.core.io.websocket/pom.xml, bundles/org.openhab.core.io.websocket/src/main/java/org/openhab/core/io/websocket/EventDTO.java, bundles/org.openhab.core.io.websocket/src/main/java/org/openhab/core/io/websocket/EventProcessingException.java, bundles/org.openhab.core.io.websocket/src/main/java/org/openhab/core/io/websocket/EventWebSocket.java, bundles/org.openhab.core.io.websocket/src/main/java/org/openhab/core/io/websocket/EventWebSocketServlet.java, bundles/org.openhab.core.io.websocket/src/main/java/org/openhab/core/io/websocket/ItemEventUtility.java, bundles/org.openhab.core.io.websocket/src/test/java/org/openhab/core/io/websocket/EventWebSocketTest.java, bundles/org.openhab.core.io.websocket/src/test/java/org/openhab/core/io/websocket/ItemEventUtilityTest.java, bundles/pom.xml, features/karaf/openhab-core/src/main/feature/feature.xml
It has been reported in the past that high-traffic applications like HABApp and systems with a large number of subscribers are affected by performance limits in the REST/SSE implementation.
This PR adds a websocket connection that can be used to receive events on the event bus (filtered by type and source) and accepts `ItemStateEvent`s and `ItemCommandEvent`s from the remote side. The connection is protected by a heartbeat-protocol and can be easily integrated in UIs as web sockets are available in ECMA script. Access is protected by token or basic auth.
@spacemanspiff2007 has done some performance tests:
```
REST + SSE (Basic Auth)
Sent: 8894 msgs
Dur : 10.0 sec
889.3 msg/sec
```
```
REST + SSE (Token)
Sent: 2532 msgs
Dur : 10.0 sec
253.2 msg/sec
```
```
Websockets
Sent: 28418 msgs
Dur : …
```
=> Add EventWebSocket

bundles/org.openhab.core.audio/src/main/java/org/openhab/core/audio/AudioManager.java, bundles/org.openhab.core.audio/src/main/java/org/openhab/core/audio/internal/AudioManagerImpl.java, bundles/org.openhab.core.io.rest.voice/src/main/java/org/openhab/core/io/rest/voice/internal/VoiceResource.java, bundles/org.openhab.core.model.script/src/org/openhab/core/model/script/actions/Voice.java, bundles/org.openhab.core.voice/src/main/java/org/openhab/core/voice/DialogContext.java, bundles/org.openhab.core.voice/src/main/java/org/openhab/core/voice/VoiceManager.java, bundles/org.openhab.core.voice/src/main/java/org/openhab/core/voice/internal/VoiceManagerImpl.java
This is a follow up PR for [#3142](https://github.com/openhab/openhab-core/pull/3142) and related to issue [#3140](https://github.com/openhab/openhab-core/issues/3140).
I realize testing the code on that pr that it introduces and unwanted behavior. If you have setup a default sink/source that is not available (because of a binding uninstall in my case) it will prevent any call to the startDialog method to work.
This PR aims to fix that by introducing a builder for the DialogContext so services availability is checked in the correct moment.
This PR also contains the removal of some deprecated voice manager method usages.
=> [voice] Use a builder to configure the dialog context and remove some deprecated method usages

bundles/org.openhab.core/src/main/java/org/openhab/core/library/types/ArithmeticGroupFunction.java, bundles/org.openhab.core/src/main/java/org/openhab/core/library/types/QuantityTypeArithmeticGroupFunction.java, bundles/org.openhab.core/src/test/java/org/openhab/core/library/types/QuantityTypeArithmeticGroupFunctionTest.java
Reported on the forum. Due to selection of the `RoundingMode` instead of a `MathContext` the average calculation is returning unexpected results: 19.0 °C / 19.5 °C results in 19.3 °C (instead of 19.25 °C) which might be acceptable, but 19.5 °C / 19.5 °C results in 20 °C (instead of 19.5 °C) which is obviously not what we want or expect. Setting the `MathContext` fixes this problem. I also corrected the same calculation for non-dimensional groups.
=> Fix AVG calculation in GroupFunction

bundles/org.openhab.core.io.rest.voice/src/main/java/org/openhab/core/io/rest/voice/internal/VoiceResource.java, bundles/org.openhab.core.model.script/src/org/openhab/core/model/script/actions/Voice.java, bundles/org.openhab.core.voice/src/main/java/org/openhab/core/voice/VoiceManager.java, bundles/org.openhab.core.voice/src/main/java/org/openhab/core/voice/internal/VoiceManagerImpl.java
I detected there is still a bug on the latest code.
Basically requiring build a context to stop a dialog is not a good idea as could cause a exception due to other service been missing (for example the default audio sink).
=> [voice] avoid build a context to stop a dialog

bundles/org.openhab.core.automation.rest/src/main/java/org/openhab/core/automation/rest/internal/RuleResource.java
This is the core part to #2150. 
An empty request body behaves like before, a body of
```
{
"1.command" : "ON"
}
```
sets the `receivedCommand` to `ON` for DSL rules.
=> [REST] allow running rules with context

bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/RuleEngineImpl.java
=> Prevent compiler error in Eclipse due to potential null value

bom/compile/pom.xml, bundles/org.openhab.core/src/main/java/org/openhab/core/library/unit/Units.java, bundles/org.openhab.core/src/test/java/org/openhab/core/library/dimension/DataAmountTest.java
Fixes #3207 (a regression from #3108). 
I also fixed the wrong case prefix for the "kilo"-Units (`K` instead of `k`) but kept the old ones for backward compatibility.
=> Fix DataAmount dimension units

bundles/org.openhab.core/src/main/java/org/openhab/core/internal/i18n/I18nProviderImpl.java
=> Fix default unit for Energy

bundles/org.openhab.core.persistence/src/main/java/org/openhab/core/persistence/extensions/PersistenceExtensions.java, bundles/org.openhab.core.persistence/src/test/java/org/openhab/core/persistence/extensions/PersistenceExtensionsTest.java
https://github.com/openhab/openhab-core/pull/3145#issuecomment-1345405725
=> Add countStateChangesSince/countStateChangesBetween to persistence extensions

bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/internal/profiles/ProfileCallbackImpl.java, bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/profiles/ProfileCallback.java
So that they can vary their processing based on the item or channeluid itself, instead of (or in addition to) solely on the prior states passing through it.
This was inspired by/extracted from #3135, since that PR is still being discussed.
=> Allow profiles to access the entire context of the link they're applied to

bundles/org.openhab.core.automation.module.script.rulesupport/src/main/java/org/openhab/core/automation/module/script/rulesupport/loader/AbstractScriptFileWatcher.java
Fixes #3214 
Regression from #3185 
@wborn It would be great if you could check if it also fixes the issue in GHA builds.
=> Fix AbstractScriptFileWatcher missing deletes on Windows

bundles/org.openhab.core.io.websocket/src/main/java/org/openhab/core/io/websocket/EventWebSocketServlet.java
Follow-Up to #2891
This fixes a bug in decoding the access token validation using basic authentication.
=> Fix BasicAuthentication for websockets

bundles/org.openhab.core.automation.rest/src/main/java/org/openhab/core/automation/rest/internal/RuleResource.java
This fixes a regression from #3160 when trying to run rules from UI. The change in content-type results in a 415 error for `text/plain` POST calls.
=> [rest] Fix missing backward compatibility in rules/runNow

bundles/org.openhab.core.io.websocket/src/main/java/org/openhab/core/io/websocket/EventWebSocket.java, bundles/org.openhab.core.io.websocket/src/test/java/org/openhab/core/io/websocket/EventWebSocketTest.java
The topics of the websocket event did not follow the openHAB convention of starting with `openhab/` followed by the component.
=> Fix wrong websocket topics

bundles/org.openhab.core/src/main/java/org/openhab/core/library/unit/Units.java, bundles/org.openhab.core/src/test/java/org/openhab/core/library/dimension/DataAmountTest.java, bundles/org.openhab.core/src/test/java/org/openhab/core/library/types/QuantityTypeTest.java
These wrong DataAmount units were added in #3208 for backwards compatibility. In OH4 we can clean them up because this major version allows for breaking changes.
=> Remove wrong DataAmount units

bundles/org.openhab.core.auth.oauth2client/src/main/java/org/openhab/core/auth/oauth2client/internal/OAuthConnector.java, bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/TriggerHandlerCallbackImpl.java, bundles/org.openhab.core.config.discovery/src/main/java/org/openhab/core/config/discovery/DiscoveryResultBuilder.java, bundles/org.openhab.core.config.discovery/src/main/java/org/openhab/core/config/discovery/internal/DiscoveryServiceRegistryImpl.java, bundles/org.openhab.core.io.net/src/main/java/org/openhab/core/io/net/http/internal/WebClientFactoryImpl.java, bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/internal/ThingManagerImpl.java, bundles/org.openhab.core/src/main/java/org/openhab/core/internal/common/AbstractInvocationHandler.java, bundles/org.openhab.core/src/main/java/org/openhab/core/internal/common/SafeCallerBuilderImpl.java, bundles/org.openhab.core/src/main/java/org/openhab/core/internal/events/OSGiEventPublisher.java
The `AccessController` and the `SecurityManager` is deprecated for removal in Java 17. We don't make use of the `SecurityManager` anyway, so we can safely remove it.
=> Remove AccessController.doPrivileged calls

bundles/org.openhab.core.addon.marketplace/src/main/java/org/openhab/core/addon/marketplace/BundleVersion.java, bundles/org.openhab.core.addon.marketplace/src/main/java/org/openhab/core/addon/marketplace/internal/community/CommunityMarketplaceAddonService.java
With this fix it will use the correct string for pattern matching add-on version ranges introduced in #2811.
=> Fix Marketplace add-on range pattern matching

bundles/org.openhab.core/src/main/java/org/openhab/core/library/types/DateTimeType.java, bundles/org.openhab.core/src/test/java/org/openhab/core/library/types/DateTimeTypeTest.java
Wish from forum post:
- **Original post:** https://community.openhab.org/t/openhab-4-0-wishlist/142388/78
- **Conclusion:** https://community.openhab.org/t/openhab-4-0-wishlist/142388/107
In relation to #2898 the plan would be to internally switch from `ZonedDateTime` to `Instant` while preserving backwards compatibility. This means `getZonedDateTime()` will stay, but it will eventually be changed to return a `ZonedDateTime` with the currently configured time-zone based on the internal `Instant`.
Therefore it would only be natural to also add a method for returning the `Instant` representation of the current object. This does not need to wait for the additional refactoring as it will provide user value right away, but implementation will of course change when we figure out how to make …
=> [core] Add DateTimeType method for returning Instant

bom/runtime/pom.xml, features/karaf/openhab-tp/src/main/feature/feature.xml, itests/org.openhab.core.io.rest.core.tests/itest.bndrun, itests/org.openhab.core.model.core.tests/itest.bndrun, itests/org.openhab.core.model.item.tests/itest.bndrun, itests/org.openhab.core.model.rule.tests/itest.bndrun, itests/org.openhab.core.model.script.tests/itest.bndrun, itests/org.openhab.core.model.thing.tests/itest.bndrun
Updates Jackson from 2.12.7 to 2.14.1
https://github.com/FasterXML/jackson/wiki/Jackson-Release-2.13
https://github.com/FasterXML/jackson/wiki/Jackson-Release-2.14
=> Update Jackson to 2.14.1

bundles/org.openhab.core.automation.rest/src/main/java/org/openhab/core/automation/rest/internal/ThingActionsResource.java
Closes #926 
May I ask for guidance for the correct endpoint? Originally I thought that `/things/{thingUid}/action` would be a good idea but it turned out that having two classes providing endpoints under `/things` results in strange effects (like 404s even if the bundle is loaded). It is not possible to integrate this resource in the resource that provides `/things` without adding a dependency to the automation bundle.
=> [rest] Allow invoking ThingActions via API

bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/internal/item/ItemResource.java, bundles/org.openhab.core/src/main/java/org/openhab/core/internal/items/MetadataRegistryImpl.java, bundles/org.openhab.core/src/main/java/org/openhab/core/items/MetadataRegistry.java
This adds a new method to ItemResource to retrieve all namespaces of an item via the path "/{itemname: [a-zA-Z_0-9]+}/metadata/namespaces" which will eventually allow us to show even the custom namespaces in the UI (the PR for that is also already in the making).
It also extends the Item-Registry to provide a getAllNamespaces()-method which could also be exposed via other languages (e.g. jsscripting)
=> Add method to get namespaces to MetadataRegistry and ItemResource

bundles/org.openhab.core/src/main/java/org/openhab/core/library/types/QuantityType.java, bundles/org.openhab.core/src/test/java/org/openhab/core/library/types/QuantityTypeTest.java
Resolves #3296
~Note: this is not changing behaviour of silly things like `QuantityType("0.05 m")` converted to `PercentType`.~ (changed in https://github.com/openhab/openhab-core/pull/3297/commits/169bd4c4263758f4bd2d23511cc1ea0af8d56476)
Note2: this is changing behaviour in backwards-compatible way with dimensionless `QuantityType`s
=> QuantityType.as(PercentType.class) fixes with dimensionless units

bundles/org.openhab.core/src/main/java/org/openhab/core/common/registry/AbstractRegistry.java
if multiple providers provide the same element, the added callback simply ignores the duplicates. but the provider has no idea its element was ignored, so it may try to remove it in the future, and things will get all out of whack if the element is removed from the registry even if another provider thinks it's still there
this is easily reproducible by creating an item in the UI, then creating the same item via a .items file, and then removing the item from the .items file. The item will seem like it is gone to most of openHAB, but will come back after reboot when the managed provider re-adds.
=> prevent a provider from removing an element from another provider

bundles/org.openhab.core/src/main/java/org/openhab/core/internal/items/MetadataRegistryImpl.java, bundles/org.openhab.core/src/test/java/org/openhab/core/internal/items/MetadataCommandDescriptionProviderTest.java, bundles/org.openhab.core/src/test/java/org/openhab/core/internal/items/MetadataRegistryImplTest.java, bundles/org.openhab.core/src/test/java/org/openhab/core/internal/items/MetadataStateDescriptionFragmentProviderTest.java
This makes the `MetadataRegistry` report when the elements of the `ManagedMetadataProvider` is available via a ready marker (like other registries). This is needed to properly determine the unit for restoring values from persistence.  I labelled it as "bug" because I believe it could explain some strange behavior that has been reported in rare cases when restoring values during startup.
This is independent from the discussion in #3248.
=> Ensure metadata available at startlevel 20

bundles/org.openhab.core.io.transport.upnp/src/main/java/org/openhab/core/io/transport/upnp/internal/UpnpIOServiceImpl.java
Call `callback.end()` after removal to avoid concurrency situation of subscription being created right between looking for callback and removing it. Implementation uses `ConcurrentHashMap` without explicit locking. In this case `end()` would not be called, but callback would still be removed.
I have no proof of this situation happening but was reviewing some of the code while working on openhab/openhab-addons#14163.
=> [transport.upnp] Slightly decrease risk of removing callback without calling end()

bundles/org.openhab.core.addon.xml/addon-1.0.0.xsd
The namespace was missing, leading to problems in SAT
=> Fix addon.xsd

bundles/org.openhab.core.addon.marketplace.karaf/src/main/java/org/openhab/core/addon/marketplace/karaf/internal/community/CommunityKarafAddonHandler.java, bundles/org.openhab.core.addon.marketplace/src/main/java/org/openhab/core/addon/marketplace/AbstractRemoteAddonService.java, bundles/org.openhab.core.addon.marketplace/src/main/java/org/openhab/core/addon/marketplace/internal/community/CommunityBlockLibaryAddonHandler.java, bundles/org.openhab.core.addon.marketplace/src/main/java/org/openhab/core/addon/marketplace/internal/community/CommunityBundleAddonHandler.java, bundles/org.openhab.core.addon.marketplace/src/main/java/org/openhab/core/addon/marketplace/internal/community/CommunityMarketplaceAddonService.java, bundles/org.openhab.core.addon.marketplace/src/main/java/org/openhab/core/addon/marketplace/internal/community/CommunityRuleTemplateAddonHandler.java, bundles/org.openhab.core.addon.marketplace/src/main/java/org/openhab/core/addon/marketplace/internal/community/CommunityUIWidgetAddonHandler.java, bundles/org.openhab.core.addon.marketplace/src/main/java/org/openhab/core/addon/marketplace/internal/json/JsonAddonService.java, bundles/org.openhab.core.addon.marketplace/src/main/java/org/openhab/core/addon/marketplace/internal/json/model/AddonEntryDTO.java, bundles/org.openhab.core.addon.marketplace/src/test/java/org/openhab/core/addon/marketplace/AbstractRemoteAddonServiceTest.java, bundles/org.openhab.core.addon.marketplace/src/test/java/org/openhab/core/addon/marketplace/test/TestAddonHandler.java, bundles/org.openhab.core.addon.marketplace/src/test/java/org/openhab/core/addon/marketplace/test/TestAddonService.java, bundles/org.openhab.core.addon.sample/src/main/java/org/openhab/core/addon/sample/internal/SampleAddonService.java, bundles/org.openhab.core.addon.xml/src/main/java/org/openhab/core/addon/xml/internal/AddonInfoConverter.java, bundles/org.openhab.core.addon.xml/src/main/java/org/openhab/core/addon/xml/internal/AddonInfoReader.java, bundles/org.openhab.core.addon.xml/src/main/java/org/openhab/core/addon/xml/internal/AddonInfoXmlProvider.java, bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/internal/addons/AddonResource.java, bundles/org.openhab.core.karaf/src/main/java/org/openhab/core/karaf/internal/KarafAddonService.java, bundles/org.openhab.core/src/main/java/org/openhab/core/addon/Addon.java, bundles/org.openhab.core/src/main/java/org/openhab/core/addon/AddonI18nLocalizationService.java, bundles/org.openhab.core/src/main/java/org/openhab/core/addon/AddonInfo.java, bundles/org.openhab.core/src/main/java/org/openhab/core/internal/addon/BundleAddonService.java, bundles/org.openhab.core/src/main/java/org/openhab/core/internal/addon/JarFileAddonService.java
Follow-Up to #3050 
Fixes #3323 
Needs to be merged together with https://github.com/openhab/openhab-webui/pull/1651
- Adds an add-on service that provides add-ons from JARs in the addons-folder. This is needed to show manually added add-ons in the UI. It's useful because then add-ons can be configured from UI or their log-level changed (see https://github.com/openhab/openhab-webui/pull/1452). It is also needed to install things from bindings installed via .jar files
- Fixes issues with community-marketplace and JSON 3rd party add-on services. Due to inconsistent use of add-on ids throughout core and Main UI add-ons from these services could not be installed. 
- Fixes issues with parsing addon.xml (connection and countries)
For better handling the id and the uid of an add-on has been …
=> Fixes and enhancements for add-on services

bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/internal/CommunicationManager.java
Some bindings that dynamically create channels (mqtt.homie) might create a channel that declares itself as Number:Dimensionless because the end-device metadata has a unit of "%". But a savvy user might want to link that to a Dimmer or Rollershutter item depending on what the device actually is. This actually works just fine since QuantityType (with unit PERCENT) and PercentType implicitly convert between each other. Except this odd compatibility code in CommunicationManager that tries to assist bindings that _aren't_ QuantityType compatible. It assumes if the channel's item type is a dimensioned item, that the actual Item is a NumberItem, and casts without checking. All this does is checks for that case to avoid a ClassCastException.
The actual stack trace before this fix:
```
2023-01-21 …
```
=> Fix CommunicationManager erroring on unusual item<->channel link

bundles/org.openhab.core.addon.marketplace/src/main/java/org/openhab/core/addon/marketplace/internal/community/CommunityMarketplaceAddonService.java
When parsing marketplace addons, if one fails, none is loaded. This change ignores those that fail.
Fixes https://github.com/openhab/openhab-core/issues/3338.
Signed-off-by: Boris Krivonog boris.krivonog@inova.si
=> Properly handle failure when parsing marketplace add-ons

bundles/org.openhab.core.persistence/src/main/java/org/openhab/core/persistence/extensions/PersistenceExtensions.java
When calculating `.changedSince` the "then" state is queried via the `.historicState` method. Regardless of the `serviceId` used when calling `.changedSince` the historic state was always queried from the default persistence service.
=> Fix wrong .historicState call in .changedSince

bundles/org.openhab.core.automation.module.script.rulesupport/src/test/java/org/openhab/core/automation/module/script/rulesupport/loader/AbstractScriptFileWatcherTest.java
The test only succeeded due to bad timing. This is a regression from #3255.
=> Fix AbstractScriptFileWatcherTest

bundles/org.openhab.core.voice/pom.xml, bundles/org.openhab.core.voice/src/main/java/org/openhab/core/voice/DialogContext.java, bundles/org.openhab.core.voice/src/main/java/org/openhab/core/voice/DialogRegistration.java, bundles/org.openhab.core.voice/src/main/java/org/openhab/core/voice/VoiceManager.java, bundles/org.openhab.core.voice/src/main/java/org/openhab/core/voice/internal/DialogProcessor.java, bundles/org.openhab.core.voice/src/main/java/org/openhab/core/voice/internal/VoiceManagerImpl.java, itests/org.openhab.core.voice.tests/itest.bndrun, itests/org.openhab.core.voice.tests/src/main/java/org/openhab/core/voice/internal/VoiceManagerImplTest.java, itests/org.openhab.core.voice.tests/src/main/java/org/openhab/core/voice/voiceconsolecommandextension/InterpretCommandTest.java, itests/org.openhab.core.voice.tests/src/main/java/org/openhab/core/voice/voiceconsolecommandextension/SayCommandTest.java, itests/org.openhab.core.voice.tests/src/main/java/org/openhab/core/voice/voiceconsolecommandextension/VoiceConsoleCommandExtensionTest.java, itests/org.openhab.core.voice.tests/src/main/java/org/openhab/core/voice/voiceconsolecommandextension/VoicesCommandTest.java
This PR adds a new functionality to the voice manager for register/unregister dialog descriptions.
The voice manager will try to keep a started dialog for each registered description (and stop the dialog if it's unregistered).
The dialog descriptions are persisted using a storage.
This PR do not introduce any code breaking changes, but introduces the behavior to stop the dialogs whenever a service in use became unavailable. 
Related to https://github.com/openhab/openhab-core/issues/3265
<s>This is a draft because integration tests are missing.</s>
=> [voice] Support managed dialogs

bundles/org.openhab.core.io.net/src/main/java/org/openhab/core/io/net/http/HttpClientFactory.java, bundles/org.openhab.core.io.net/src/main/java/org/openhab/core/io/net/http/WebSocketFactory.java, bundles/org.openhab.core.io.net/src/main/java/org/openhab/core/io/net/http/internal/WebClientFactoryImpl.java
=> Add param sslContextFactory when creating a HTTP or web socket client

bundles/org.openhab.core.ui/src/main/java/org/openhab/core/ui/internal/items/ItemUIRegistryImpl.java
Fix openhab/openhab-webui#1697
=> Use setpoint as default sitemap element for item with tag "Setpoint"

bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/module/handler/GenericEventConditionHandler.java, bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/module/handler/GenericEventTriggerHandler.java, bundles/org.openhab.core.automation/src/main/resources/OH-INF/automation/moduletypes/GenericConditions.json, bundles/org.openhab.core.automation/src/main/resources/OH-INF/automation/moduletypes/GenericTriggers.json, bundles/org.openhab.core.automation/src/main/resources/OH-INF/i18n/automation.properties, bundles/org.openhab.core.automation/src/test/java/org/openhab/core/automation/internal/module/handler/GenericEventTriggerHandlerTest.java, bundles/org.openhab.core/src/main/java/org/openhab/core/events/TopicGlobEventFilter.java, bundles/org.openhab.core/src/test/java/org/openhab/core/events/TopicGlobEventFilterTest.java, itests/org.openhab.core.automation.integration.tests/src/main/java/org/openhab/core/automation/integration/test/AutomationIntegrationJsonTest.java, itests/org.openhab.core.automation.integration.tests/src/main/java/org/openhab/core/automation/integration/test/AutomationIntegrationTest.java, itests/org.openhab.core.automation.integration.tests/src/main/resources/OH-INF/automation/rules/ItemRuleDefinition.json, itests/org.openhab.core.automation.integration.tests/src/main/resources/OH-INF/automation/templates/SimpleTestTemplate.json, itests/org.openhab.core.automation.integration.tests/src/main/resources/OH-INF/automation/templates/TestTemplateRuleWithReferences.json, itests/org.openhab.core.automation.module.core.tests/src/main/java/org/openhab/core/automation/internal/module/RunRuleModuleTest.java, itests/org.openhab.core.automation.module.core.tests/src/main/java/org/openhab/core/automation/internal/module/RuntimeRuleTest.java, itests/org.openhab.core.automation.module.script.tests/src/main/java/org/openhab/core/automation/module/script/internal/defaultscope/DemoScriptRule.json, itests/org.openhab.core.automation.module.script.tests/src/main/java/org/openhab/core/automation/module/script/internal/defaultscope/ScriptRuleOSGiTest.java, itests/org.openhab.core.automation.module.script.tests/src/main/resources/OH-INF/automation/rules/DemoScriptRule.json, itests/org.openhab.core.automation.tests/src/main/java/org/openhab/core/automation/event/RuleEventTest.java
to make their interfaces and semantics match, as well as having a well defined (and useful) way of defining topic filters
fixes #3234
=> rework GenericEventTrigger and GenericEventCondition

bundles/org.openhab.core.model.script/src/org/openhab/core/model/script/actions/Audio.java, bundles/org.openhab.core.model.script/src/org/openhab/core/model/script/actions/Voice.java
Closes #3331.
Related to https://github.com/openhab/openhab-js/issues/98.
This PR adds method overloads for Audio and Voice actions to accept float as volume in addition to `PercentType`.
This is especially useful when accessing these actions from the JSR223 languages because you do not need to import and construct a `PercentType` then.
I also aligned the params for the methods to increase readability of code and corrected the mathematical notation of intervals in strings (correct is `;` instead of `,`).
=> Actions: Add method overloads for `PercentType` to Audio & Voice

bundles/org.openhab.core.automation.module.script.rulesupport/src/main/java/org/openhab/core/automation/module/script/rulesupport/loader/AbstractScriptFileWatcher.java
=> Fix file-processing in AbstractScriptFileWatcher

itests/org.openhab.core.thing.tests/src/main/java/org/openhab/core/thing/internal/update/ThingUpdateOSGiTest.java
This got lost in the review process of https://github.com/openhab/openhab-core/pull/3330.
=> Add nullable annotation to avoid error marker in Eclipse

bundles/org.openhab.core.config.dispatch/src/main/java/org/openhab/core/config/dispatch/internal/ConfigDispatcherFileWatcher.java, bundles/org.openhab.core.config.dispatch/src/test/java/org/openhab/core/config/dispatch/internal/ConfigDispatcherFileWatcherTest.java
Fixes #3383
I'm not 100% sure if this would have been an issue in a real-world setup, because the tests failed when the file was not existing. It seems that `Files.isHidden` behaves differently on *nix and Windows for non-existing files.
=> Fix ConfigDispatcherFileWatcher

bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/util/ThingWebClientUtil.java, bundles/org.openhab.core.thing/src/test/java/org/openhab/core/thing/util/ThingWebClientUtilTest.java
To associate a HTTP or WebSocket client to a thing.
=> New method to build a valid consumer name for a WEB client

bundles/org.openhab.core.automation.module.script.rulesupport/src/main/java/org/openhab/core/automation/module/script/rulesupport/loader/AbstractScriptFileWatcher.java, bundles/org.openhab.core.automation.module.script.rulesupport/src/test/java/org/openhab/core/automation/module/script/rulesupport/loader/AbstractScriptFileWatcherTest.java
Fixes #3386 
This fixes a real bug with script start-level handling on windows systems.
=> Fix AbstractScriptFileWatcher for windows

bundles/org.openhab.core.model.sitemap/src/org/openhab/core/model/sitemap/Sitemap.xtext
So far, it has not been possible to have text or numeric input in a sitemap. This can be useful to do simple updating of items, for instance for manual meter readings.
The workaround so far has been to use a Webview element and some javascript, see forum: https://community.openhab.org/t/input-field-for-number-free-text-for-openhab-uis/12461.
This PR adds an sitemap input widget. A second PR will add this to Basic UI.
If these PR's would be accepted, I will also update the main UI sitemap configuration pages to include the input widget. I have not done any app development (Android, IOS) so far, but would hope this is interesting enough for someone to also consider adding it to the apps.
Some configuration options could definitely be added in follow-up PR's for the input field, but my …
=> add sitemap Input type

bundles/org.openhab.core.io.rest.sitemap/src/main/java/org/openhab/core/io/rest/sitemap/internal/PageChangeListener.java, bundles/org.openhab.core.io.rest.sitemap/src/main/java/org/openhab/core/io/rest/sitemap/internal/SitemapResource.java, bundles/org.openhab.core.io.rest.sitemap/src/main/java/org/openhab/core/io/rest/sitemap/internal/SitemapWidgetEvent.java, bundles/org.openhab.core.io.rest.sitemap/src/main/java/org/openhab/core/io/rest/sitemap/internal/WidgetDTO.java, bundles/org.openhab.core.io.rest.sitemap/src/test/java/org/openhab/core/io/rest/sitemap/internal/SitemapResourceTest.java, bundles/org.openhab.core.model.sitemap/src/org/openhab/core/model/sitemap/Sitemap.xtext, bundles/org.openhab.core.ui/src/main/java/org/openhab/core/ui/internal/components/UIComponentSitemapProvider.java, bundles/org.openhab.core.ui/src/main/java/org/openhab/core/ui/internal/items/ItemUIRegistryImpl.java, bundles/org.openhab.core.ui/src/main/java/org/openhab/core/ui/items/ItemUIRegistry.java, bundles/org.openhab.core.ui/src/test/java/org/openhab/core/ui/internal/items/ItemUIRegistryImplTest.java
This attribute was already available in syntax for the Image element but was probably not used by any UI.
It is now available for any sitemap element and allows defining a color for the widget icon based on conditional statements on the item value.
=> Extend "iconcolor" attribute to all sitemap elements

bundles/org.openhab.core.io.net/src/main/java/org/openhab/core/io/net/http/HttpUtil.java
[request.header](https://github.com/eclipse/jetty.project/blob/4563f7a90e6ca11efeb1a48b5475e9853e6e2bcf/jetty-client/src/main/java/org/eclipse/jetty/client/HttpRequest.java#L309-L316) just _adds_ the header, resulting in multiple 'User-Agent' headers, whereas [request.agent](https://github.com/eclipse/jetty.project/blob/4563f7a90e6ca11efeb1a48b5475e9853e6e2bcf/jetty-client/src/main/java/org/eclipse/jetty/client/HttpRequest.java#L286-L290) _replaces_ it.
Looking at the implementation of headers.add, a workaround could be done (without this PR) by giving a 'User-Agent' of nil, and the second 'User-Agent' header containing the intended value. The nil entry would cause headers.add to remove existing headers of the same name.
=> Fix overriding Jetty's User-Agent in HttpUtil

bundles/org.openhab.core.config.dispatch/src/main/java/org/openhab/core/config/dispatch/internal/ConfigDispatcherFileWatcher.java
The latest snapshot logs the following on the initial startup:
```
22:45:38.553 [INFO ] [org.openhab.core.Activator           ] - Starting openHAB 4.0.0 (build Build #3336)
22:45:46.826 [INFO ] [b.core.model.lsp.internal.ModelServer] - Started Language Server Protocol (LSP) service on port 5007
22:45:51.811 [INFO ] [re.automation.internal.RuleEngineImpl] - Rule engine started.
22:45:53.144 [WARN ] [ig.dispatch.internal.ConfigDispatcher] - Could not process config file 'basicui.cfg': /Users/kai/oh4/conf/basicui.cfg
22:45:53.663 [WARN ] [ig.dispatch.internal.ConfigDispatcher] - Could not process config file 'rrd4j.cfg': /Users/kai/oh4/conf/rrd4j.cfg
22:45:53.683 [INFO ] [hab.ui.habpanel.internal.HABPanelTile] - Started HABPanel at /habpanel
```
This shows that the config files are tried to …
=> Fix service folder resolution path

bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/internal/ThingManagerImpl.java
Fix #3410 
If several threads try to acquire a lock for things a CME is thrown.
=> Fix CME in ThingManagerImpl

bundles/org.openhab.core.config.discovery.usbserial.linuxsysfs/src/main/java/org/openhab/core/config/discovery/usbserial/linuxsysfs/internal/DeltaUsbSerialScanner.java, bundles/org.openhab.core.config.discovery.usbserial.linuxsysfs/src/main/java/org/openhab/core/config/discovery/usbserial/linuxsysfs/internal/PollingUsbSerialScanner.java, bundles/org.openhab.core.config.discovery.usbserial.linuxsysfs/src/main/java/org/openhab/core/config/discovery/usbserial/linuxsysfs/internal/SysfsUsbSerialScanner.java, bundles/org.openhab.core.config.discovery.usbserial.ser2net/src/main/java/org/openhab/core/config/discovery/usbserial/ser2net/internal/Ser2NetUsbSerialDiscovery.java, bundles/org.openhab.core.config.discovery.usbserial.ser2net/src/test/java/org/openhab/core/config/discovery/usbserial/ser2net/internal/Ser2NetUsbSerialDiscoveryTest.java, bundles/org.openhab.core.config.discovery.usbserial/src/main/java/org/openhab/core/config/discovery/usbserial/UsbSerialDiscovery.java, bundles/org.openhab.core.io.transport.serial.rxtx/src/main/java/org/openhab/core/io/transport/serial/internal/RxTxPortProvider.java, itests/org.openhab.core.config.discovery.usbserial.linuxsysfs.tests/src/main/java/org/openhab/core/config/discovery/usbserial/linuxsysfs/internal/PollingUsbSerialScannerTest.java
The rxtx serial port provider is now able to scan symlink in /dev/serial/by-id and use them as valid identifier.
Benefit : users won't have to fix the path of their USB serial device  with udev anymore, they can now use the explicit and stable symlink directly.
EDIT: explaining how: 
**OLD, not relevant anymore ---------------**
~~1. First, we get as usual all the `CommPortIdentifier` by scan and properties. (I modified these methods to return list instead of stream to avoid unnecessary conversion)
2. Then if we are on linux (to do this I use `System.getProperty("os.name")` and check if "linux" is present, is there something better ?), we add the result of the new scan. What does this new scan ? : 
a - list symlinks inside `/dev/serial/by-id/`
b- trying to resolve each of them against the …
=> [serial] Ability to use /dev/serial/ symlinks for usb serial device

bundles/org.openhab.core.config.dispatch/src/main/java/org/openhab/core/config/dispatch/internal/ConfigDispatcherFileWatcher.java, bundles/org.openhab.core.model.core/src/main/java/org/openhab/core/model/core/internal/folder/FolderObserver.java, bundles/org.openhab.core.model.core/src/test/java/org/openhab/core/model/core/internal/folder/FolderObserverTest.java, bundles/org.openhab.core/src/main/java/org/openhab/core/internal/service/WatchServiceImpl.java
Closes #3400 
On Samba shares a single MODIFY event may result in different sequences of CREATE/DELETE/MODIFY events. Unfortunately this is not properly handled by the underlying library and we have to re-introduce our ugly workaround. The solution itself is a bit improved over the old one as it not only keeps the last event but determines the correct event by examining the sequence of received events.
=> Prevent duplicate events in WatchService

bundles/org.openhab.core/src/main/java/org/openhab/core/internal/service/WatchServiceImpl.java
Fixes #3387 
Added a check to prevent attempts to unregister already unregistered service. I don't fully understand why this happens, but probably it's a race condition on shutdown where the framework unregisters the service before the deactivate method is called.
=> Fix IllegalStateException in WatchServiceImpl

bundles/org.openhab.core.io.rest.sitemap/src/main/java/org/openhab/core/io/rest/sitemap/internal/SitemapResource.java, bundles/org.openhab.core.io.rest.sitemap/src/main/java/org/openhab/core/io/rest/sitemap/internal/WidgetDTO.java, bundles/org.openhab.core.model.sitemap/src/org/openhab/core/model/sitemap/Sitemap.xtext, bundles/org.openhab.core.ui/src/main/java/org/openhab/core/ui/internal/components/UIComponentSitemapProvider.java
Related to openhab/openhab-webui#1755
Related to openhab/openhab-android#3285
This sitemap widget is not documented.
It is not implemented neither in Android app nor iOS app.
It was implemented in BasicUI but was buggy.
Support in BasicUI has been removed.
=> Remove List element from sitemap syntax

bundles/org.openhab.core.thing/schema/update/update-description-1.0.0.xsd, bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/internal/update/RemoveChannelInstructionImpl.java, bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/internal/update/ThingUpdateInstructionReader.java, bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/internal/update/UpdateChannelInstructionImpl.java, itests/org.openhab.core.thing.tests/src/main/java/org/openhab/core/thing/internal/update/ThingUpdateOSGiTest.java, itests/org.openhab.core.thing.tests/src/main/resources/test-bundle-pool/thingUpdateTest.bundle/OH-INF/update/singleInstructions.xml
Follow-up to #3330 
https://github.com/openhab/openhab-addons/pull/14460 shows that we need channel-group support for the update instructions.
=> Add support for channel-groups to update instructions

bundles/org.openhab.core.ui/src/main/java/org/openhab/core/ui/internal/proxy/ProxyServletService.java, bundles/org.openhab.core.ui/src/test/java/org/openhab/core/ui/internal/proxy/ProxyServletServiceTest.java
Reverts the partially working Whiteboard config changes of #3252 back to a working implementation using the HttpService. The configurable threading makes this a non-trivial Servlet for use with the Whiteboard.
Fixes openhab/openhab-webui#1782
=> Fix broken ProxyServletService

bundles/org.openhab.core.voice/src/main/java/org/openhab/core/voice/AbstractCachedTTSService.java
Related to https://github.com/openhab/openhab-core/pull/3057#issuecomment-1460729131
We need the ability to override this method when extending `AbstractCachedTTSService`.
=> AbstractCachedTTSService: make synthesize method non final

bundles/org.openhab.core.automation.module.script/src/main/java/org/openhab/core/automation/module/script/ScriptTransformationService.java, bundles/org.openhab.core.automation.module.script/src/test/java/org/openhab/core/automation/module/script/ScriptTransformationServiceTest.java
Closes #3243 
Inline scripts are identified by starting with `|` which is fine since that is neither an allowed character on nearly all file systems nor for UIDs. Additionally, the old JS transformation also defined inline scripts in this way, so it is already a known concept.
=> Allow inline scripts in SCRIPT transformation

bom/compile/pom.xml, bom/runtime/pom.xml, features/karaf/openhab-tp/src/main/feature/feature.xml, itests/org.openhab.core.addon.tests/itest.bndrun, itests/org.openhab.core.auth.oauth2client.tests/itest.bndrun, itests/org.openhab.core.automation.integration.tests/itest.bndrun, itests/org.openhab.core.automation.module.core.tests/itest.bndrun, itests/org.openhab.core.automation.module.script.tests/itest.bndrun, itests/org.openhab.core.automation.module.timer.tests/itest.bndrun, itests/org.openhab.core.automation.tests/itest.bndrun, itests/org.openhab.core.config.core.tests/itest.bndrun, itests/org.openhab.core.config.discovery.mdns.tests/itest.bndrun, itests/org.openhab.core.config.discovery.tests/itest.bndrun, itests/org.openhab.core.config.discovery.usbserial.linuxsysfs.tests/itest.bndrun, itests/org.openhab.core.config.discovery.usbserial.tests/itest.bndrun, itests/org.openhab.core.config.dispatch.tests/itest.bndrun, itests/org.openhab.core.ephemeris.tests/itest.bndrun, itests/org.openhab.core.io.rest.core.tests/itest.bndrun, itests/org.openhab.core.model.item.tests/itest.bndrun, itests/org.openhab.core.model.rule.tests/itest.bndrun, itests/org.openhab.core.model.script.tests/itest.bndrun, itests/org.openhab.core.model.thing.tests/itest.bndrun, itests/org.openhab.core.storage.json.tests/itest.bndrun, itests/org.openhab.core.tests/itest.bndrun, itests/org.openhab.core.thing.tests/itest.bndrun, itests/org.openhab.core.voice.tests/itest.bndrun, tools/i18n-plugin/pom.xml, tools/i18n-plugin/src/test/java/org/openhab/core/tools/i18n/plugin/GenerateDefaultTranslationsMojoTest.java
This addresses CVE-2022-40151 and CVE-2022-41966, see:
https://x-stream.github.io/changes.html#1.4.20
This version also [fixes](https://github.com/x-stream/xstream/pull/287) an issue with closing streams so the workaround in GenerateDefaultTranslationsMojoTest is no longer needed.
=> Upgrade XStream to 1.4.20

bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/internal/ThingImpl.java, itests/org.openhab.core.thing.tests/src/main/java/org/openhab/core/thing/ThingChannelsTest.java
Fixes #3442
As described in #3442 _"we switched from a `List<Channel>` to a `Map<ChannelUID, Channel>` which does not necessarily preserve the order"_ -- with the consequence that in the Main UI, Thing Channels were no longer displayed in the order in which they were declared in the `thing.xml` file.
This PR uses `LinkedHashMap<ChannelUID, Channel>` instead of `HashMap<ChannelUID, Channel>` so that Thing Channels are once more displayed in the order in which they were declared in the `thing.xml` file.
=> Channels once more displayed in correct order in Main UI

bundles/org.openhab.core/src/main/java/org/openhab/core/internal/service/ReadyServiceImpl.java, bundles/org.openhab.core/src/test/java/org/openhab/core/internal/service/ReadyServiceImplTest.java
In #3451 it was discovered that the `ReadyServiceImpl` sends ready markers in arbitrary order when the listener is registered after the ready marker was received. This PR changes the implementation so that the original order is preserved.
=> Fix ready marker ordering on late subscriptions

bundles/org.openhab.core.auth.oauth2client/src/main/java/org/openhab/core/auth/oauth2client/internal/OAuthConnector.java, bundles/org.openhab.core.auth.oauth2client/src/main/java/org/openhab/core/auth/oauth2client/internal/OAuthStoreHandlerImpl.java, bundles/org.openhab.core.auth.oauth2client/src/test/java/org/openhab/core/auth/oauth2client/internal/OAuthStoreHandlerTest.java
This fixes a regression from #3083 and #2994 since JDK internals are now [strongly encapsulated](https://openjdk.org/jeps/403). The first mentioned PR removed the type adapter for `LocalDateTime`, which ultimately lead to the issue when Java 17 was introduced.
Since type adapters already exist for `Instant`, the `InaccessibleObjectException` has been fixed by refactoring remaining `LocalDateTime`s to `Instant`.
JAR: [org.openhab.core.auth.oauth2client-4.0.0-SNAPSHOT.jar](https://drive.google.com/file/d/1aKYQtfaNRxnLqA-WvzVS8z0-NlkNvASb/view?usp=sharing)
Fixes #3447
=> [oauth] Fix `InaccessibleObjectException`

bundles/org.openhab.core.transform/src/main/java/org/openhab/core/transform/FileTransformationProvider.java, bundles/org.openhab.core.transform/src/test/java/org/openhab/core/transform/FileTransformationProviderTest.java
Fixes #3456 
Relative and absolute path were not properly handled. The watch service provides relative paths to the root watch folder. The implementation expected absolute path (which were provided in the initial import).
This was not discovered by the tests because the tests wrongly modeled the watch service calls to `processWatchEvent`.
=> Fix file processing in FileTransformationProvider

features/karaf/openhab-tp/src/main/feature/feature.xml
The `jetty-alpn-java-client` dependency was missing in #3433
=> Add dependency on jetty-alpn-java-client

bundles/org.openhab.core.voice/src/main/java/org/openhab/core/voice/DialogContext.java, bundles/org.openhab.core.voice/src/main/java/org/openhab/core/voice/internal/VoiceManagerImpl.java
This fixes the selection of the default human language interpreter.
By error it's loading the whole list of interpreters.
Should this be back-ported to the 3.4.x branch? I think the issue is also there.
Regards!
=> [voice] Fix default interpreter selection.

bundles/org.openhab.core.io.rest.sitemap/src/main/java/org/openhab/core/io/rest/sitemap/internal/PageChangeListener.java, bundles/org.openhab.core.io.rest.sitemap/src/main/java/org/openhab/core/io/rest/sitemap/internal/SitemapResource.java
=> [Sitemap] Add new color keyword "itemValue"

bundles/org.openhab.core/src/main/java/org/openhab/core/library/types/HSBType.java, bundles/org.openhab.core/src/main/java/org/openhab/core/util/ColorUtil.java, bundles/org.openhab.core/src/test/java/org/openhab/core/library/types/HSBTypeTest.java, bundles/org.openhab.core/src/test/java/org/openhab/core/util/ColorUtilTest.java, tools/static-code-analysis/checkstyle/suppressions.xml
This has been refactored to align with the usually used conversion by a lot of ZigBee products like Hue or deconz.
=> Add ColorUtil for better support of xyY conversion

bundles/org.openhab.core.automation.module.script.rulesupport/src/main/java/org/openhab/core/automation/module/script/rulesupport/loader/AbstractScriptFileWatcher.java, bundles/org.openhab.core.automation.module.script.rulesupport/src/test/java/org/openhab/core/automation/module/script/rulesupport/loader/AbstractScriptFileWatcherTest.java
See the discussion in #3445
Another problem I encountered was the onReadyMarkerAdded got called out of order. It jumped from 80 -> 20 -> 100 -> 40 -> 50 -> 70 -> 30. Here's an example trace:
```
023-03-13 01:42:22.428 [TRACE] [ort.loader.AbstractScriptFileWatcher] - onReadyMarkerAdded(startlevel=80) 100 => 100 for /openhab/conf/automation/ruby
2023-03-13 01:42:22.428 [TRACE] [ort.loader.AbstractScriptFileWatcher] - onReadyMarkerAdded(startlevel=20) 100 => 100 for /openhab/conf/automation/ruby
2023-03-13 01:42:22.429 [TRACE] [ort.loader.AbstractScriptFileWatcher] - onReadyMarkerAdded(startlevel=100) 100 => 100 for /openhab/conf/automation/ruby
2023-03-13 01:42:22.430 [TRACE] [ort.loader.AbstractScriptFileWatcher] - onReadyMarkerAdded(startlevel=40) 100 => 100 for …
```
=> Fix NPE caused by AbstractScriptFileWatcher initialization order

bundles/org.openhab.core.automation.module.script/src/main/java/org/openhab/core/automation/module/script/ScriptTransformationService.java, bundles/org.openhab.core.automation.module.script/src/test/java/org/openhab/core/automation/module/script/ScriptTransformationServiceTest.java
...by setting all attributes before compiling.
In JRuby, because an identifier can either be a variable or a method call, the compiler needs to know variables ahead of time  in order to recognise them as variables. Because scripts are compiled first, and then the attributes set, this information is missing, therefore [a "hack" was needed in jruby transformations](https://github.com/openhab/openhab-docs/blob/ad1e66c440e7a6150b11aeaef31a132c389d552b/addons/transformations.md?plain=1#L113) to give the compiler the needed hint.
This PR simply reverses the order so that attributes were set before compiling, so the hack in jruby will no longer be needed. I have tested this on my jrubyscripting addon installation.
For more info, see https://github.com/jruby/jruby/issues/5876
=> Fix variable binding in ScriptTransformationService

bundles/org.openhab.core.automation.module.script/pom.xml, bundles/org.openhab.core.automation.module.script/src/main/java/org/openhab/core/automation/module/script/ScriptTransformationService.java, bundles/org.openhab.core.automation.module.script/src/main/java/org/openhab/core/automation/module/script/internal/ScriptEngineFactoryHelper.java, bundles/org.openhab.core.automation.module.script/src/main/java/org/openhab/core/automation/module/script/internal/provider/ScriptModuleTypeProvider.java, bundles/org.openhab.core.automation.module.script/src/main/java/org/openhab/core/automation/module/script/profile/ScriptProfile.java, bundles/org.openhab.core.automation.module.script/src/main/java/org/openhab/core/automation/module/script/profile/ScriptProfileFactory.java, bundles/org.openhab.core.automation.module.script/src/main/resources/OH-INF/config/script-profile.xml, bundles/org.openhab.core.automation.module.script/src/main/resources/OH-INF/i18n/scriptprofile.properties, bundles/org.openhab.core.automation.module.script/src/test/java/org/openhab/core/automation/module/script/profile/ScriptProfileTest.java
This is a replacement for #2872 which for unknown reasons can't be re-opened. I did another check and found that a general TRANSFORM profile is not feasible without a nearly complete refactoring of the whole transformation infrastructure. It would also need extensive refactoring in the UI part which I can't do.
=> Introduce a profile for the generic SCRIPT transformation

bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/internal/ThingManagerImpl.java
Seen in the message in #3473: The placeholder was not properly replaced.
=> Fix ConfigValidationMessage in ThingManagerImpl

bundles/org.openhab.core.model.sitemap/src/org/openhab/core/model/sitemap/Sitemap.xtext, bundles/org.openhab.core.model.sitemap/src/org/openhab/core/model/sitemap/validation/SitemapValidator.xtend
See discussion in https://github.com/openhab/openhab-core/pull/3398.
See implementation of usage in BasicUI https://github.com/openhab/openhab-webui/pull/1787.
This is a first step of work to be done in the respective sitemap based UI's.
This PR adds a new inputHint parameter that can take a string that describes behaviour of the UI widget.
Right now, I propose to develop support for following values in the UI's:
-  `text`: default for non numeric item types, would show a standard keyboard on touch devices with on screen keyboard
-  `number`: show a numeric only keyboard on touch devices, default if item type is Numeric
-  `date`: show a date picker
-  `time`: show a time picker
-  `datetime`: show a combined date/time picker (or sequence of two pickers), default for DateTime type items …
=> Add inputHint param to sitemap Input element

bundles/org.openhab.core/src/main/java/org/openhab/core/internal/items/MetadataCommandDescriptionProvider.java, bundles/org.openhab.core/src/main/java/org/openhab/core/internal/items/MetadataStateDescriptionFragmentProvider.java
Related to UI issue https://github.com/openhab/openhab-webui/issues/1641.
The current implementation for parsing the stateDescription and commandDescription metadata value could fail if the characters = or , are used on the value or label.
This PR introduces the use of a regex to split the stateDescription and commandDescription metadata value in the same way but discarding the split characters wrapped by double quotes.
This implementation still could fail if a single " character gets introduced in a label or value, but as this have not syntactic sense I think the solution is good enough.
=> [State/Command Metadata] Allow using '=' in a double quoted value/label

bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/internal/profile/ProfileTypeResource.java
Sort the profile type json result from the REST service. This makes the UI a bit more predictable. Helpful for repetitive operations so your eyes don't go around hunting for the wanted item.
Current:
Sorted:
=> Sort profile-type resources by their label

bundles/org.openhab.core.addon.marketplace.karaf/src/main/java/org/openhab/core/addon/marketplace/karaf/internal/community/CommunityKarafAddonHandler.java, bundles/org.openhab.core.addon.marketplace/src/main/java/org/openhab/core/addon/marketplace/MarketplaceBundleInstaller.java, bundles/org.openhab.core.audio/src/test/java/org/openhab/core/audio/internal/utils/BundledSoundFileHandler.java, bundles/org.openhab.core/src/main/java/org/openhab/core/cache/lru/LRUMediaCache.java
It is recommended to use try-with-resources when using `File.list` or `Files.walk` to ensure streams are properly closed.
=> Use try-with-resources on Files.walk/Files.list

bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/module/handler/ItemStateTriggerHandler.java, bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/internal/CommunicationManager.java, bundles/org.openhab.core/src/main/java/org/openhab/core/items/GenericItem.java, bundles/org.openhab.core/src/main/java/org/openhab/core/items/GroupItem.java, bundles/org.openhab.core/src/main/java/org/openhab/core/items/events/GroupStateUpdatedEvent.java, bundles/org.openhab.core/src/main/java/org/openhab/core/items/events/ItemEventFactory.java, bundles/org.openhab.core/src/main/java/org/openhab/core/items/events/ItemStateUpdatedEvent.java, bundles/org.openhab.core/src/test/java/org/openhab/core/items/GenericItemTest.java, bundles/org.openhab.core/src/test/java/org/openhab/core/library/items/NumberItemTest.java, itests/org.openhab.core.automation.module.timer.tests/src/main/java/org/openhab/core/automation/module/timer/internal/BasicConditionHandlerTest.java, itests/org.openhab.core.tests/src/main/java/org/openhab/core/items/GroupItemOSGiTest.java, itests/org.openhab.core.thing.tests/src/main/java/org/openhab/core/thing/internal/CommunicationManagerOSGiTest.java
There has been some discussion in the past about the `ItemStateEvent` which in some cases may not carry the unit of a value even if the item has a unit (#2956).
This PR adds an `ItemStateUpdatedEvent` which is fired by the item itself (similar to the `ItemStateChangedEvent`. Since the item knows about its dimension and unit, the new event can carry this information even if the unit is derived from a unit provider or the state description. This also clearly separates the events when the item reports something and when the item is supposed to do something:
- `ItemStateEvent` -> the item shall update to the contained state
- `ItemCommandEvent`-> the item receives this command
- `ItemStateUpdatedEvent` -> the item updated the state
- `ItemStateChangedEvent` -> the item changed the state
Since …
=> Add ItemStateUpdatedEvent and enable group channel-links

bundles/org.openhab.core.config.discovery.usbserial.linuxsysfs/src/main/java/org/openhab/core/config/discovery/usbserial/linuxsysfs/internal/SysfsUsbSerialScanner.java
This is a regression from #3290 and was reported on the community forum and results in "too many open files" errors after some days.
=> Fix resource leak in SysfsUsbSerialScanner

bundles/org.openhab.core.automation.module.script.rulesupport/src/main/java/org/openhab/core/automation/module/script/rulesupport/loader/AbstractScriptDependencyTracker.java, bundles/org.openhab.core.automation.module.script.rulesupport/src/test/java/org/openhab/core/automation/module/script/rulesupport/loader/AbstractScriptDependencyTrackerTest.java
Reported in private communication. This is the same issue that was already fixed in #3457. The `.canRead` check failed because it was done on a relative path instead of an absolute one.
=> Fix AbstractDependencyTracker

bundles/org.openhab.core.addon.marketplace/src/main/java/org/openhab/core/addon/marketplace/MarketplaceBundleInstaller.java, bundles/org.openhab.core.addon/src/main/java/org/openhab/core/addon/Addon.java, bundles/org.openhab.core.audio/src/test/java/org/openhab/core/audio/internal/AbstractAudioServletTest.java, bundles/org.openhab.core.automation.rest/src/main/java/org/openhab/core/automation/rest/internal/ThingActionsResource.java, bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/module/handler/ItemCommandTriggerHandler.java, bundles/org.openhab.core.io.http.auth/src/main/java/org/openhab/core/io/http/auth/internal/AuthenticationHandler.java, bundles/org.openhab.core.io.net/src/main/java/org/openhab/core/io/net/http/internal/WebClientFactoryImpl.java, bundles/org.openhab.core.model.core/src/main/java/org/openhab/core/model/core/internal/folder/FolderObserver.java, bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/internal/update/UpdateChannelInstructionImpl.java, bundles/org.openhab.core.voice/src/main/java/org/openhab/core/voice/VoiceManager.java, bundles/org.openhab.core.voice/src/main/java/org/openhab/core/voice/internal/cache/TTSLRUCacheImpl.java, bundles/org.openhab.core.voice/src/test/java/org/openhab/core/voice/internal/cache/TTSLRUCacheImplTest.java, bundles/org.openhab.core/src/main/java/org/openhab/core/cache/lru/LRUMediaCacheEntry.java, bundles/org.openhab.core/src/main/java/org/openhab/core/internal/common/WrappedScheduledExecutorService.java, bundles/org.openhab.core/src/main/java/org/openhab/core/internal/items/ItemStateConverterImpl.java, bundles/org.openhab.core/src/main/java/org/openhab/core/internal/scheduler/SchedulerImpl.java, bundles/org.openhab.core/src/test/java/org/openhab/core/cache/lru/LRUMediaCacheEntryTest.java, bundles/org.openhab.core/src/test/java/org/openhab/core/internal/service/WatchServiceImplTest.java, bundles/org.openhab.core/src/test/java/org/openhab/core/library/unit/UnitsTest.java, itests/org.openhab.core.storage.json.tests/src/main/java/org/openhab/core/storage/json/internal/ThingMigrationOSGiTest.java, itests/org.openhab.core.thing.tests/src/main/java/org/openhab/core/thing/internal/ChannelLinkNotifierOSGiTest.java
This PR fixes some recently introduced SAT issues.
=> Fix recently introduced SAT issues

bom/runtime/pom.xml
It is not needed in openhab-core or openhab-addons.
=> Bump commons-fileupload

bundles/org.openhab.core/src/test/java/org/openhab/core/internal/service/WatchServiceImplTest.java
=> Fix WatchService tests

bundles/org.openhab.core.addon.marketplace.karaf/src/main/java/org/openhab/core/addon/marketplace/karaf/internal/community/CommunityKarafAddonHandler.java
This is a regression from #3504: the stream is used as return value in a method but is closed because the try-with-resources was contained in the method itself. The stream is now collected to a list and then returned as a stream.
This results in continuous re-installs for kars from the community market place or JSON 3rd party addon services
=> Fix IllegalStateException in CommunityKarafAddonHandler

bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/internal/CommunicationManager.java, bundles/org.openhab.core/src/main/java/org/openhab/core/items/GroupItem.java, bundles/org.openhab.core/src/main/java/org/openhab/core/items/events/ItemEventFactory.java
https://github.com/openhab/openhab-core/pull/3141 introduced an `ItemStateUpdatedEvent` and updated `CommunicationManager` to only receive updates on this event.
However, it was forgotten to update the subscribed event types, so no updated were received at all.
The `CommuncationManagerOSGiTest` was not able to detect this regression, because in the test the event is `received` via a method call, but not an event subscription/the event bus.
This also renames the method for creating a `GroupStateUpdatedEvent` for more clarity.
=> Fix wrong event subscription in `CommunicationManager`

bundles/org.openhab.core/src/main/java/org/openhab/core/internal/service/WatchServiceImpl.java, bundles/org.openhab.core/src/test/java/org/openhab/core/internal/service/WatchServiceImplTest.java
Related to #3518 
In some cases writing the same content to a file results in a MODIFY event because in an intermediate state the file is truncated to zero length. With this PR prior to emitting a MODIFY event the `WatchServiceImpl` checks whether the hash of the file content at the end of the wait time is the same as before and suppresses the event.
Found in CI tests.
=> Prevent unnecessary MODIFY events in WatchServiceImpl

bundles/org.openhab.core/src/main/java/org/openhab/core/library/types/HSBType.java, bundles/org.openhab.core/src/main/java/org/openhab/core/util/ColorUtil.java, bundles/org.openhab.core/src/test/java/org/openhab/core/library/types/HSBTypeTest.java, bundles/org.openhab.core/src/test/java/org/openhab/core/util/ColorUtilTest.java
RGB colors are converted into HSBType, and sometimes also need to be transformed back to RGB. Whenever a binding uses  integer values to represent RGB or HSB, a lossless conversion is not possible without further measures. ```HSBType::fromRGB``` rounds to integer numbers. This results in a small difference when you receive an RGB value, store it in OH HSBType representation, and then sent it out as RGB. This is not unexpected.
But looking at openhab/openhab-addons#12643, I found larger deviations than expected.
This PR improves the rounding of results when values are converted to PercentType.
A few parameterized tests have been added to check if this improves the behavior. Some old tests could be deleted and included in the parameterized tests, but I wanted to keep them in for reference. …
=> Reduce rounding errors of RGB/HSB conversion and enhance ColorUtil

bundles/org.openhab.core.io.monitor/src/main/java/org/openhab/core/io/monitor/internal/EventLogger.java
Just a very minor change, but since this gets called a lot, might be worth it.
- Cleaner code
- Avoid doing string concat every time
=> EventLogger minor refactor

bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/module/handler/ItemStateConditionHandler.java
Fixes #3370 
This improves the log messages in the `ItemStateConditionHandler` by adding the rule UID. This makes it easier to identify the condition that creates the message.
=> Improve log messages in ItemStateConditionHandler

bundles/org.openhab.core.model.item/src/org/openhab/core/model/Items.xtext
The icon value can now contain until 3 segments separated by a semi-column.
First segment is the icon source. Example: oh, if, iconify, material, f7, ...
Second segment is the icon set. Example: classic
Third segment is the icon name (and can contain hyphen). Example: temperature
In case only two segments are provided, the first segment is the icon source and the second the icon name. "classic" icon set is assumed if icon source is "oh".
In case only one segment is provided, the icon source is assumed to be the openHAB server and its classic icon set and the value is then the icon name.
Ability to use a string containing anything has been removed.
Related to #3052
=> Extend item syntax for category/icon

bundles/org.openhab.core.model.sitemap/src/org/openhab/core/model/sitemap/Sitemap.xtext
The icon value can now contain until 3 segments separated by a semi-column.
First segment is the icon source. Example: oh, if, iconify, material, f7, ...
Second segment is the icon set (and can be empty). Example: classic
Third segment is the icon name (and can contain hyphen). Example: temperature
In case only two segments are provided, the first segment is the icon source and the second the icon name. "classic" icon set is assumed if icon source is "oh".
In case only one segment is provided, the icon source is assumed to be the openHAB server and its classic icon set and the value is then the icon name.
Ability to surround the value with simple or double quotes is kept for better backward compatibility.
=> Extend sitemap syntax for icon

bundles/org.openhab.core.automation.module.script/src/main/java/org/openhab/core/automation/module/script/ScriptTransformationService.java, bundles/org.openhab.core.automation.module.script/src/main/java/org/openhab/core/automation/module/script/ScriptTransformationServiceFactory.java, bundles/org.openhab.core.automation.module.script/src/main/java/org/openhab/core/automation/module/script/internal/ScriptEngineFactoryHelper.java, bundles/org.openhab.core.automation.module.script/src/main/java/org/openhab/core/automation/module/script/profile/ScriptProfile.java, bundles/org.openhab.core.automation.module.script/src/main/java/org/openhab/core/automation/module/script/profile/ScriptProfileFactory.java, bundles/org.openhab.core.automation.module.script/src/main/resources/OH-INF/config/script-profile.xml, bundles/org.openhab.core.automation.module.script/src/main/resources/OH-INF/i18n/scriptprofile.properties, bundles/org.openhab.core.automation.module.script/src/main/resources/OH-INF/i18n/scriptprofile_da.properties, bundles/org.openhab.core.automation.module.script/src/main/resources/OH-INF/i18n/scriptprofile_de.properties, bundles/org.openhab.core.automation.module.script/src/main/resources/OH-INF/i18n/scriptprofile_fi.properties, bundles/org.openhab.core.automation.module.script/src/main/resources/OH-INF/i18n/scriptprofile_he.properties, bundles/org.openhab.core.automation.module.script/src/main/resources/OH-INF/i18n/scriptprofile_it.properties, bundles/org.openhab.core.automation.module.script/src/main/resources/OH-INF/i18n/scriptprofile_pl.properties, bundles/org.openhab.core.automation.module.script/src/test/java/org/openhab/core/automation/module/script/ScriptTransformationServiceTest.java, bundles/org.openhab.core.automation.module.script/src/test/java/org/openhab/core/automation/module/script/profile/ScriptProfileTest.java, bundles/org.openhab.core.io.rest.transform/src/main/java/org/openhab/core/io/rest/transform/internal/TransformationResource.java, bundles/org.openhab.core.transform/src/main/java/org/openhab/core/transform/TransformationHelper.java, bundles/org.openhab.core.transform/src/main/java/org/openhab/core/transform/TransformationService.java
See previous discussions in #3465 and #3476
Resolve #3465
Potentially fix #3521
Documentation: https://github.com/openhab/openhab-docs/pull/2042
Breaking change notice: https://github.com/openhab/openhab-distro/pull/1514
Why? 
- A simpler syntax for file-based transformations, reduces potential errors
- Transformation script files will have their own proper extension that corresponds to its actual language, e.g. .js, .rb, .py, etc. This is a much more elegant way than using .script which is very confusing especially when utilising multiple languages.
- Simplified UI when choosing script based profile transformations. Users only need to select the language when _creating_ the transformation, and not having to choose the language again each and every time they need to _use_ the …
=> Add dynamic scripting-language transformation service

bundles/org.openhab.core.io.rest.sitemap/src/main/java/org/openhab/core/io/rest/sitemap/internal/SitemapResource.java, bundles/org.openhab.core.io.rest.sitemap/src/main/java/org/openhab/core/io/rest/sitemap/internal/WidgetDTO.java, bundles/org.openhab.core.ui/src/main/java/org/openhab/core/ui/internal/components/UIComponentSitemapProvider.java
Recreated https://github.com/openhab/openhab-core/pull/3419 as there was a mixup in my local branches.
This was missed in https://github.com/openhab/openhab-webui/pull/1735
Extended to cover REST API and inputHint parameter to the Input element.
=> Add Input widget to main UI sitemap configuration and REST API

bundles/org.openhab.core.semantics/model/generateTagClasses.groovy, bundles/org.openhab.core.semantics/pom.xml, bundles/org.openhab.core.semantics/src/main/java/org/openhab/core/semantics/SemanticTags.java, bundles/org.openhab.core.semantics/src/main/java/org/openhab/core/semantics/model/equipment/Equipments.java, bundles/org.openhab.core.semantics/src/main/java/org/openhab/core/semantics/model/location/Locations.java, bundles/org.openhab.core.semantics/src/main/java/org/openhab/core/semantics/model/point/Points.java, bundles/org.openhab.core.semantics/src/main/java/org/openhab/core/semantics/model/property/Properties.java, bundles/org.openhab.core.semantics/src/test/java/org/openhab/core/semantics/SemanticTagsTest.java, features/karaf/openhab-core/src/main/feature/feature.xml
Add the ability to dynamically add new semantic tags
For example, to add a new tag called `MainBedroom` with `Bedroom` as the parent:
`SemanticTags.add("MainBedroom", Bedroom.class)` or
`SemanticTags.add("MainBedroom", "Bedroom")` 
The new tags can then be used in items and rules.
A text file in the following format can be easily loaded and parsed with a simple rule on startup in any scripting language.
```
NewTag(Label,Synonym1,Synonym2): ParentTag A long description can go here
SecretRoom: Room
SwimmingPool: Location
Motion: Status
Color: Property
Brightness: Property
```
or go full YAML... the syntax is up to the rule writer.
Currently the MainUI can recognise and display the added tags:
However, because MainUI uses a static list of tags (loaded from a file), it doesn't list the new …
=> Add dynamic creation of semantic tags

bundles/org.openhab.core.auth.oauth2client/src/main/java/org/openhab/core/auth/oauth2client/internal/OAuthClientServiceImpl.java, bundles/org.openhab.core.auth.oauth2client/src/main/java/org/openhab/core/auth/oauth2client/internal/OAuthConnector.java, bundles/org.openhab.core.auth.oauth2client/src/main/java/org/openhab/core/auth/oauth2client/internal/PersistedParams.java, bundles/org.openhab.core/src/main/java/org/openhab/core/auth/client/oauth2/OAuthClientService.java, bundles/org.openhab.core/src/main/java/org/openhab/core/auth/client/oauth2/OAuthFactory.java
This reverts #1891 and fixes #1888 by providing a new way to customize deserialization of `AccessTokenResponse` which has been tested with the Netatmo binding. See openhab/openhab-addons#14755 for a description of the concrete Netatmo problem that so far prevented Netatmo from using the core OAuth implementation.
In this new approach a custom `GsonBuilder` can be provided which can be preconfigured with custom type adapters etc.
This fixes the issue with #1891:
```
[oauth2client.internal.OAuthConnector] - Unable to construct custom deserializer 'org.openhab.binding.netatmo.internal.deserialization.AccessTokenResponseDeserializer'
java.lang.ClassNotFoundException: org.openhab.binding.netatmo.internal.deserialization.AccessTokenResponseDeserializer cannot be found by …
```
=> [oauth] Add support for custom deserialization of AccessTokenResponse

bundles/org.openhab.core.model.thing/src/org/openhab/core/model/thing/internal/GenericThingProvider.xtend, bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/Channel.java, bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/util/ThingHelper.java, bundles/org.openhab.core.thing/src/test/java/org/openhab/core/thing/util/ThingHelperTest.java
Fixes #3527 
It was found that things from textual configuration are not properly updated if changes are only made in configuration or label of a channel. The reason is that for assuming equality only uid and accepted item-type of the channel were checked. This is obviously wrong and also confusing because for the thing itself configuration and other fields are also compared.
Another bug in the `GenericThingProvider`: The things are cached in the provider to determine changes. However, this list was never updated, resulting in changes back to the first version (v1 -> v2 -> v1) not resulting in an update notification, because the new thing and the cached thing are equal.
=> Fix thing reloading from things file

bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/module/handler/GroupStateTriggerHandler.java, bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/module/handler/ItemStateTriggerHandler.java
The `GroupStateTrigger` subscibed to `ItemStateEvent` instead of `ItemStateUpdatedEvent` (while `ItemStateTrigger` uses `ItemStateUpdatedEvent`), this is confusiing and results in different behavior of both triggers.
The `ItemStateTrigger` did not subscribe to `GroupStateUpdatedEvent` which results in the trigger not firing for group state UPDATES. This is wrong because it fires for item UPDATES and for both, group and item CHANGES.
=> Fix wrong event subscription in GroupStateTrigger and ItemStateTrigger

bundles/org.openhab.core.semantics/src/main/java/org/openhab/core/semantics/SemanticTags.java, bundles/org.openhab.core.semantics/src/test/java/org/openhab/core/semantics/SemanticTagsTest.java
Add methods for getting the label and description of a semantic tag.
In addition to enriching the ability to work with semantic tags, this should also help in building a rest endpoint that provides the semantic tags to mainui, as discussed here: https://github.com/openhab/openhab-webui/issues/1822
Although at this point I'm not yet sure exactly what's needed for the rest endpoint. More methods would probably be needed when we tackle the implementation of that feature.
=> Add methods to get Semantic tag synonyms and description

bundles/org.openhab.core.io.transport.modbus/src/main/java/org/openhab/core/io/transport/modbus/internal/ModbusConnectionPool.java, bundles/org.openhab.core.io.transport.modbus/src/main/java/org/openhab/core/io/transport/modbus/internal/ModbusManagerImpl.java, bundles/org.openhab.core.io.transport.modbus/src/main/java/org/openhab/core/io/transport/modbus/internal/ModbusPoolConfig.java, bundles/org.openhab.core.io.transport.modbus/src/main/java/org/openhab/core/io/transport/modbus/internal/pooling/ModbusSlaveConnectionFactoryImpl.java
Potential fix for unhandled exception, leading to "unrecoverable" error state (openHAB restart needed). See the community post below.
I cannot verify whether this actually fixes the issue as the error is very rare
This would be good candidate for 3.x maintenance branch as well
- Corrected null typing -- apparently IDE was not strict enough to complain
- handle case of ModbusSlaveConnectionFactoryImpl::create returning null ModbusSlaveConnection, leading to activateObject called with PooledObject(null) [NPE was handled], and then leading to validateObject called with PooledObject(null) [was not handled, p.getObject().isConnected() crashes -- probably bad things happened!]
From https://community.openhab.org/t/modbus-binding-problems-with-silently-disconnected-items/139363/28?u=ssalonen
logs …
=> [modbus] Fix error handling with DNS resolution / Unknown host errors

bundles/org.openhab.core.ui.icon/src/main/java/org/openhab/core/ui/icon/internal/IconServlet.java, bundles/org.openhab.core.ui.icon/src/test/java/org/openhab/core/ui/icon/AbstractResourceIconProviderTest.java, bundles/org.openhab.core.ui.icon/src/test/java/org/openhab/core/ui/icon/internal/IconServletTest.java
The state is now expected to be passed only in the "state" parameter of the request.
As a result, the icon name can now contain hyphen(s).
Closes #3543
=> Icon server: remove old style request with the state in the URL

bundles/org.openhab.core.addon/schema/addon-1.0.0.xsd, bundles/org.openhab.core.addon/src/main/java/org/openhab/core/addon/AddonInfo.java, itests/org.openhab.core.addon.tests/src/main/resources/test-bundle-pool/BundleInfoTest.bundle/OH-INF/addon/addon.xml, itests/org.openhab.core.addon.tests/src/main/resources/test-bundle-pool/acmeweather.bundle/OH-INF/addon/addon.xml
Redefines `connection` in addon.xsd by:
- Adding new member `none` for no interactions with external systems at all (e.g. astro)
- Replacing member `cloudDiscovery` by `hybrid` which is more generic and can be used when internet access is not required, but can provide optional extended functionality (for example discovery).
Also includes a commit a very small cleanup after #3362.
Resolves #3555
=> Redefine connection in addon.xsd

bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/internal/tag/TagDTO.java, bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/internal/tag/TagResource.java, bundles/org.openhab.core.io.rest/src/main/java/org/openhab/core/io/rest/LocaleServiceImpl.java, bundles/org.openhab.core.semantics/src/main/java/org/openhab/core/semantics/SemanticTags.java
This is to enable the use of dynamically added tags (#3519) in the main ui (https://github.com/openhab/openhab-webui/pull/1850)
=> [REST] List semantic tags

bundles/org.openhab.core.voice/src/main/java/org/openhab/core/voice/VoiceManager.java, bundles/org.openhab.core.voice/src/main/java/org/openhab/core/voice/internal/VoiceManagerImpl.java, itests/org.openhab.core.voice.tests/src/main/java/org/openhab/core/voice/internal/VoiceManagerImplTest.java
Remove VoiceManager deprecated method overloads for 'startDialog' and 'listenAndAnswer'.
Closes #3262
=> [voice] Remove deprecated dialog methods

bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/type/AutoUpdatePolicy.java, itests/org.openhab.core.thing.tests/src/main/java/org/openhab/core/thing/ThingChannelsTest.java, itests/org.openhab.core.thing.tests/src/main/java/org/openhab/core/thing/internal/AutoUpdateManagerTest.java, itests/org.openhab.core.thing.tests/src/main/java/org/openhab/core/thing/internal/CommunicationManagerOSGiTest.java
When the Main UI creates things/channels through the REST API, it does not set autoUpdatePolicy for the channels, which makes the core use "RECOMMEND" as a policy without looking at a potential information at the channel type definition.
This PR leaves the autoUpdatePolicy for the channels unset, so that the AutoUpdateManager then checks for the information in the channel type.
See also https://github.com/openhab/openhab-addons/pull/14809#issuecomment-1510455008
=> Consider auto-update policy from channel types

bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/internal/profile/ProfileTypeResource.java, bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/internal/tag/TagResource.java, bundles/org.openhab.core.io.rest.sse/src/main/java/org/openhab/core/io/rest/sse/internal/util/SseUtil.java, bundles/org.openhab.core.persistence/src/main/java/org/openhab/core/persistence/extensions/PersistenceExtensions.java, bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/internal/AutoUpdateManager.java, bundles/org.openhab.core/src/main/java/org/openhab/core/internal/events/OSGiEventPublisher.java, bundles/org.openhab.core/src/main/java/org/openhab/core/internal/service/WatchServiceImpl.java, bundles/org.openhab.core/src/test/java/org/openhab/core/library/types/HSBTypeTest.java
remove unused private methods and variables, remove additional newlines
=> Reduce SAT warnings

tools/pom.xml, tools/upgradetool/pom.xml, tools/upgradetool/src/main/java/org/openhab/core/tools/UpgradeTool.java, tools/upgradetool/src/main/java/org/openhab/core/tools/internal/Upgrader.java
This is the initial contribution for a tool that can perform more complex upgrade tasks. The idea is to provide an easy way for the user to perform one-time upgrade operations to the databases that are optional but useful.
The first task is the migration of the unit of a `NumberItem` with dimension from the state description to the new `defaultUnit` metadata introduced in #3248. Since there might be side-effects this should not be performed automatically. For textual configuration this can easily be done with a text editor or command line-tools. For UI defined items it's more difficult since two files need to be considered.
Other tasks might be automatically executed by the update script if necessary.
=> Initial contribution of an CLI upgrade-tool

bundles/org.openhab.core.ephemeris/src/main/java/org/openhab/core/ephemeris/internal/EphemerisManagerImpl.java, bundles/org.openhab.core.ephemeris/src/main/resources/jollyday/holidays/Holidays_dk.xml, itests/org.openhab.core.ephemeris.tests/src/main/java/org/openhab/core/ephemeris/internal/EphemerisManagerImplOSGiTest.java
The version of Jollyday we are using was abandoned years ago, so the holiday definitions we are using are getting outdated as well.
This pull request introduces the possibility to override holiday definitions in core, and as an example contains updated Danish definitions, ending Great Prayer Day this year, since our government has [abolished](https://www.thelocal.dk/20230228/great-prayer-day-abolished-by-danish-parliament) it from next year.
The obvious disadvantage is that we would then take over the maintenance. But on the other hand, they are not maintained upstream anymore, so at least it would improve the user experience. Additionally, it would not change the API, so upgrading to **focus-shift** later will be seamless for users.
Related to #3544
=> [ephemeris] Add support for overriding holiday definitions

tools/upgradetool/src/main/java/org/openhab/core/tools/UpgradeTool.java
Almost all openHAB installations should have the $OPENHAB_USERDATA env variable set. If this is the case, the user does not have to provide a directory, so this parameter can be made optional.
=> Make --dir param optional for upgradetool

bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/handler/BaseModuleHandlerFactory.java, bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/composite/CompositeModuleHandlerFactory.java
Fixes #3505 
The cause is the naming of the module handlers. Internally the `BaseModuleHandlerFactory` stores the modules in a `Map` where the key is `ruleUid+moduleId`. 
Textual defined rules have `ruleUid` that consists of the filename, a dash and a number that denotes the position of the rule in the file, so in a file `foo.rules`, the first rule gets a `foo-1`, the 11th gets `foo-11`. Within a rule, the modules are numbered from 0 to n. So the if the first rule has 10 triggers, the last module handler is stored with a key `foo-110`. When the 11th rule is added and has a trigger of the same type as first trigger, the `BaseModuleHandlerFactory` generates the same key and returns the already created handler for 10th trigger of rule 1 instead creating a new handler.
This PR changes the key …
=> Fix non-unique module handler identifiers

bundles/org.openhab.core.config.core/src/main/resources/OH-INF/i18n/validation.properties, bundles/org.openhab.core.config.core/src/main/resources/OH-INF/i18n/validation_cs.properties, bundles/org.openhab.core.config.core/src/main/resources/OH-INF/i18n/validation_de.properties, bundles/org.openhab.core.config.core/src/main/resources/OH-INF/i18n/validation_he.properties, bundles/org.openhab.core.config.core/src/main/resources/OH-INF/i18n/validation_hu.properties, bundles/org.openhab.core.config.core/src/main/resources/OH-INF/i18n/validation_it.properties, bundles/org.openhab.core.config.core/src/main/resources/OH-INF/i18n/validation_no.properties, bundles/org.openhab.core.config.core/src/main/resources/OH-INF/i18n/validation_pl.properties, bundles/org.openhab.core.config.core/src/main/resources/OH-INF/i18n/validation_sl.properties, bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/internal/ThingFactoryHelper.java, bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/internal/ThingManagerImpl.java, bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/internal/update/ThingUpdateInstructionReader.java, bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/internal/update/ThingUpdateInstructionReaderImpl.java, bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/internal/update/UpdateChannelInstructionImpl.java, bundles/org.openhab.core.thing/src/test/java/org/openhab/core/thing/internal/ThingManagerImplTest.java, itests/org.openhab.core.thing.tests/src/main/java/org/openhab/core/thing/internal/update/ThingUpdateOSGiTest.java
=> Improve thing updates

bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/binding/AbstractStorageBasedTypeProvider.java
@lolodomo FYI.
Since `StateDescriptionFragment` is an interface it can't be restored from the storage without adding type specific converters. Since `JsonStorage` does not provide a solution for that, the `StateDescriptionFragment` is now mapped to a storage entity.
=> Fix storing of StateDescriptionFragment in AbstractStorageBasedTypeProvider

features/karaf/openhab-tp/src/main/feature/feature.xml
Bump Netty to latest versions.
https://netty.io/news/2023/04/25/4-1-92-Final.html
Also requires this PR
https://github.com/openhab/openhab-addons/pull/14878
Signed-off-by: Matthew Skinner <matt@pcmus.com>
=> Bump Netty version to 4.1.92.Final

tools/upgradetool/src/main/java/org/openhab/core/tools/UpgradeTool.java, tools/upgradetool/src/main/java/org/openhab/core/tools/internal/Upgrader.java
Fixes upgrade tool not running if database missing.
Also enables "run all if no command option present" as discussed in https://github.com/openhab/openhab-distro/pull/1532
=> Fix UpgradeTool and enable default=all policy

bundles/org.openhab.core.addon.marketplace/src/main/java/org/openhab/core/addon/marketplace/AbstractRemoteAddonService.java
A format change in the database (related to the introduction of addon.xml) leads to a non-migrateable and permanent error that floods the log with exceptions and malfunctions.
If such an error is detected, the database is purged and an error logged.
Also reported on the forum several times.
=> Fix marketplace add-on services fail after upgrade

bundles/org.openhab.core/src/main/java/org/openhab/core/library/unit/Units.java, bundles/org.openhab.core/src/test/java/org/openhab/core/library/unit/UnitsTest.java
Adds unit `rpm` (revolutions per minute) for rotational frequency. Even though I'd prefer `min⁻¹`, `rpm` seems to be more common.
Please let me know, if I missed something. I have to admit that this is untested as core does currently not build for me locally.
=> [UoM] add unit rpm for rotational frequency

tools/upgradetool/src/main/java/org/openhab/core/tools/internal/Upgrader.java
The JSON database that stores the already executed steps was not always properly flushed. This could result in the last step not being properly persisted, resulting in a new execution on next update.
=> Fix Upgradetool does not remember last executed step

bundles/org.openhab.core.transform/src/main/java/org/openhab/core/transform/TransformationHelper.java
Fixes https://github.com/openhab/openhab-webui/issues/1867
Runtime exceptions thrown by transformation services propagated from the `TransformationHelper` to the `EnrichtedItemDTOMapper` to the `ItemResource`. In general transformation services should throw `TransformationException` and this should be fixed there but in this case safe-guarding the `TransformationHelper` makes sense because of the severity of issues created by fault add-ons.
=> Fix exception in TransformationHelper

bundles/org.openhab.core.model.script/resources/OH-INF/config/hli.xml, bundles/org.openhab.core.model.script/resources/OH-INF/i18n/hli.properties, bundles/org.openhab.core.model.script/resources/OH-INF/i18n/hli_cs.properties, bundles/org.openhab.core.model.script/resources/OH-INF/i18n/hli_da.properties, bundles/org.openhab.core.model.script/resources/OH-INF/i18n/hli_de.properties, bundles/org.openhab.core.model.script/resources/OH-INF/i18n/hli_el.properties, bundles/org.openhab.core.model.script/resources/OH-INF/i18n/hli_fi.properties, bundles/org.openhab.core.model.script/resources/OH-INF/i18n/hli_fr.properties, bundles/org.openhab.core.model.script/resources/OH-INF/i18n/hli_he.properties, bundles/org.openhab.core.model.script/resources/OH-INF/i18n/hli_hu.properties, bundles/org.openhab.core.model.script/resources/OH-INF/i18n/hli_it.properties, bundles/org.openhab.core.model.script/resources/OH-INF/i18n/hli_nl.properties, bundles/org.openhab.core.model.script/resources/OH-INF/i18n/hli_no.properties, bundles/org.openhab.core.model.script/resources/OH-INF/i18n/hli_pl.properties, bundles/org.openhab.core.model.script/resources/OH-INF/i18n/hli_pt.properties, bundles/org.openhab.core.model.script/resources/OH-INF/i18n/hli_ru.properties, bundles/org.openhab.core.model.script/resources/OH-INF/i18n/hli_sl.properties, bundles/org.openhab.core.model.script/resources/OH-INF/i18n/hli_sv.properties, bundles/org.openhab.core.model.script/resources/OH-INF/i18n/hli_uk.properties, bundles/org.openhab.core.model.script/resources/OH-INF/i18n/hli_zh.properties, bundles/org.openhab.core.model.script/src/org/openhab/core/model/script/internal/RuleHumanLanguageInterpreter.java
This is needed to clean-up UI. The categories should be used for add-ons while core services should use `system`. This is non-breaking, configurations ill be preserved.
=> Move RuleHLI service from voice to system

bundles/org.openhab.core/src/main/java/org/openhab/core/util/ColorUtil.java
Two improvements to ColorUtils..
- define static constants for code optimisation
- hue value overflow check and correction
=> [ColorUtil] optimise constants; hue overflow check

bundles/org.openhab.core.karaf/src/main/java/org/openhab/core/karaf/internal/FeatureInstaller.java
Packages are no longer needed since we have the setup wizard in place.
See https://github.com/openhab/openhab-distro/pull/1543
=> Remove package support from FeatureInstaller

bundles/org.openhab.core.io.rest/src/main/java/org/openhab/core/io/rest/internal/resources/SystemInfoResource.java, bundles/org.openhab.core.io.rest/src/main/java/org/openhab/core/io/rest/internal/resources/beans/UoMInfoBean.java, bundles/org.openhab.core/src/main/java/org/openhab/core/i18n/UnitProvider.java, bundles/org.openhab.core/src/main/java/org/openhab/core/internal/i18n/I18nProviderImpl.java, bundles/org.openhab.core/src/test/java/org/openhab/core/internal/i18n/TestUnitProvider.java
Currently the list of available dimensions for `Number` items is hard-coded in Main UI. The reason is that there is no way to determine the available dimensions at runtime. This endpoint adds that, so that the list can be created dynamically and will automatically be up-to-date if new dimensions (like #3608 or #3408) are added.
=> [rest] Add endpoint for UoM information

bundles/org.openhab.core.persistence/src/main/java/org/openhab/core/persistence/extensions/PersistenceExtensions.java
This would open up a lot more possibilities on what can be done with persistence data.
=> Add getAllStatesSince() and getAllStatesBetween() to PersistenceExtensions

bundles/org.openhab.core.automation.module.script/src/main/java/org/openhab/core/automation/module/script/internal/ScriptEngineFactoryBundleTracker.java, bundles/org.openhab.core/src/main/java/org/openhab/core/service/StartLevelService.java
Closes #3272 
The `ScriptEngingeFactoryBundleTracker` tracks all bundles that provide `ScriptEngineFcatory` capabilities and sets a `ReadyMarker` if all of them are activated.
=> Add a ScriptEngineFactory bundle tracker

bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/module/factory/CoreModuleHandlerFactory.java, bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/module/handler/SystemTriggerHandler.java, bundles/org.openhab.core.automation/src/test/java/org/openhab/core/automation/internal/module/handler/SystemTriggerHandlerTest.java, bundles/org.openhab.core.test/src/main/java/org/openhab/core/test/java/JavaOSGiTest.java, itests/org.openhab.core.automation.integration.tests/itest.bndrun, itests/org.openhab.core.automation.integration.tests/src/main/java/org/openhab/core/automation/integration/test/AutomationIntegrationJsonTest.java, itests/org.openhab.core.automation.integration.tests/src/main/java/org/openhab/core/automation/integration/test/AutomationIntegrationTest.java, itests/org.openhab.core.automation.module.core.tests/itest.bndrun, itests/org.openhab.core.automation.module.core.tests/src/main/java/org/openhab/core/automation/internal/module/RunRuleModuleTest.java, itests/org.openhab.core.automation.module.core.tests/src/main/java/org/openhab/core/automation/internal/module/RuntimeRuleTest.java, itests/org.openhab.core.automation.module.timer.tests/itest.bndrun, itests/org.openhab.core.automation.module.timer.tests/src/main/java/org/openhab/core/automation/module/timer/internal/BasicConditionHandlerTest.java, itests/org.openhab.core.automation.module.timer.tests/src/main/java/org/openhab/core/automation/module/timer/internal/DayOfWeekConditionHandlerTest.java, itests/org.openhab.core.automation.module.timer.tests/src/main/java/org/openhab/core/automation/module/timer/internal/RuntimeRuleTest.java, itests/org.openhab.core.automation.tests/itest.bndrun, itests/org.openhab.core.automation.tests/src/main/java/org/openhab/core/automation/event/RuleEventTest.java
Fixes #3199
The `StartLevelTrigger` did not fire when the start level was already above the desired start level. Also added some tests.
=> Trigger immediately when start level already reached

bundles/org.openhab.core.automation.rest/src/main/java/org/openhab/core/automation/rest/internal/RuleResource.java, bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/events/AutomationEventFactory.java, bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/events/ExecutionEvent.java, bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/events/TimerEvent.java, bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/module/handler/DateTimeTriggerHandler.java, bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/module/handler/GenericCronTriggerHandler.java, bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/module/handler/RunRuleActionHandler.java, bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/module/handler/TimeOfDayTriggerHandler.java, bundles/org.openhab.core/src/main/java/org/openhab/core/events/AbstractEventFactory.java
Closes #1391 
This creates event information for time-based triggers (DateTimeTrigger, GenericCronTrigger, TimeOfDayTrigger). The topic contains the trigger type, the trigger id (or label) is passed as source and the trigger configuration as payload of the event. 
=> Add event information in rules for time, manual and RunRuleAction trigger

bundles/org.openhab.core.io.rest.auth/src/main/java/org/openhab/core/io/rest/auth/AuthFilter.java
Regression from #3622 
The `AuthFilter` no longer declared `ContainerRequestFilter` as service.
=> Fix AuthFilter service declaration

bundles/org.openhab.core.audio/src/main/java/org/openhab/core/audio/AudioHTTPServer.java, bundles/org.openhab.core.audio/src/main/java/org/openhab/core/audio/AudioManager.java, bundles/org.openhab.core.audio/src/main/java/org/openhab/core/audio/AudioSink.java, bundles/org.openhab.core.audio/src/main/java/org/openhab/core/audio/AudioSinkAsync.java, bundles/org.openhab.core.audio/src/main/java/org/openhab/core/audio/AudioSinkSync.java, bundles/org.openhab.core.audio/src/main/java/org/openhab/core/audio/AudioStream.java, bundles/org.openhab.core.audio/src/main/java/org/openhab/core/audio/ClonableAudioStream.java, bundles/org.openhab.core.audio/src/main/java/org/openhab/core/audio/FileAudioStream.java, bundles/org.openhab.core.audio/src/main/java/org/openhab/core/audio/FixedLengthAudioStream.java, bundles/org.openhab.core.audio/src/main/java/org/openhab/core/audio/StreamServed.java, bundles/org.openhab.core.audio/src/main/java/org/openhab/core/audio/URLAudioStream.java, bundles/org.openhab.core.audio/src/main/java/org/openhab/core/audio/internal/AudioManagerImpl.java, bundles/org.openhab.core.audio/src/main/java/org/openhab/core/audio/internal/AudioServlet.java, bundles/org.openhab.core.audio/src/main/java/org/openhab/core/audio/internal/javasound/JavaSoundAudioSink.java, bundles/org.openhab.core.audio/src/main/java/org/openhab/core/audio/internal/webaudio/WebAudioAudioSink.java, bundles/org.openhab.core.audio/src/main/java/org/openhab/core/audio/utils/AudioSinkUtils.java, bundles/org.openhab.core.audio/src/main/java/org/openhab/core/audio/utils/AudioSinkUtilsImpl.java, bundles/org.openhab.core.audio/src/main/java/org/openhab/core/audio/utils/AudioStreamUtils.java, bundles/org.openhab.core.audio/src/test/java/org/openhab/core/audio/internal/AbstractAudioServletTest.java, bundles/org.openhab.core.audio/src/test/java/org/openhab/core/audio/internal/AudioServletTest.java, bundles/org.openhab.core.voice/src/main/java/org/openhab/core/voice/internal/DialogProcessor.java, bundles/org.openhab.core.voice/src/main/java/org/openhab/core/voice/internal/VoiceManagerImpl.java, bundles/org.openhab.core.voice/src/main/java/org/openhab/core/voice/internal/cache/AudioStreamFromCache.java, bundles/org.openhab.core.voice/src/main/java/org/openhab/core/voice/internal/cache/TTSLRUCacheImpl.java, bundles/org.openhab.core/src/main/java/org/openhab/core/cache/lru/LRUMediaCacheEntry.java, bundles/org.openhab.core/src/main/java/org/openhab/core/common/Disposable.java, bundles/org.openhab.core/src/test/java/org/openhab/core/cache/lru/LRUMediaCacheEntryTest.java
Hello,
Following discussions with @lolodomo, I try here to enhance some aspect of the audio framework
- This proposal extracts `ClonableAudioStream` from `FixedLengthAudioStream`. We can have clonable Stream but without the fixed length property (example : `URLAudioStream`).
- Some (`AudioServlets` ?) sink can only work with `FixedLengthAudioStream `(at least squeezebox and webaudio sinks). Because they need to clone a stream to serve several client, or a client several times. To lift this limitation, this proposal make the `AudioServlet` able to cache the whole stream in memory (if < 1MB)  or in file (if <5 MB) to serve the sink a fitting stream by wrapping it with an implementation of `FixedLenghtAudioStream` (either `ByteArrayAudioStream` or `FileAudioStream`)
- Some AudioSink services …
=> [audio] More capabilities for AudioSink using the AudioServlet

bundles/org.openhab.core.ui/NOTICE, bundles/org.openhab.core.ui/bnd.bnd, bundles/org.openhab.core.ui/pom.xml, bundles/org.openhab.core.ui/src/main/java/org/openhab/core/ui/internal/chart/defaultchartprovider/DefaultChartProvider.java
Closes #3279 
Not yet ready for merge. See the discussion in attached issue.
Edit: Seems to be ok now.
=> Upgrade XChart to 3.8.4

bundles/org.openhab.core.addon/src/main/java/org/openhab/core/addon/internal/JarFileAddonService.java
See title. This brings the query id in-line with the other add-on services. Before queries without add-on service id were not properly processed. As a result the add-on configuration page could not be accessed.
Also adds correct content type.
=> Fix missing query prefix in JarFileAddonService

bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/RuleEngineImpl.java, bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/RuleRegistryImpl.java, bundles/org.openhab.core.io.console/src/main/java/org/openhab/core/io/console/ConsoleInterpreter.java, bundles/org.openhab.core.test.magic/src/main/java/org/openhab/core/magic/binding/internal/MagicServiceConfig.java, bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/internal/console/FirmwareUpdateConsoleCommandExtension.java
See: https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/lang/StringBuilder.html
> This class provides an API compatible with StringBuffer, but with no guarantee of synchronization.
> This class is designed for use as a drop-in replacement for StringBuffer in places where the string buffer was being used by a single thread (as is generally the case).
> Where possible, it is recommended that this class be used in preference to StringBuffer as it will be faster under most implementations.
=> Replace `StringBuffer` usages with `StringBuilder`

bundles/org.openhab.core.io.monitor/src/main/java/org/openhab/core/io/monitor/internal/metrics/ThingStateMetric.java, bundles/org.openhab.core.io.monitor/src/test/java/org/openhab/core/io/monitor/internal/metrics/ThingStateMetricTest.java
At bind time, ThingId was being used, but then ThingUid was being used when changes occured, causing multiple meters to be created for the same Thing, with the status always being 0 for the meter created at bind time.
This change uses the full ThingUid, for both binding and event processing, since ThingUid is the globally unique value.
Fixes #3672
In case it is useful, the original PR to add this code can be found here: https://github.com/openhab/openhab-core/pull/2133
=> Always use ThingUid as the unique identifier for thing status metrics

bundles/org.openhab.core.audio/src/main/java/org/openhab/core/audio/AudioFormat.java, bundles/org.openhab.core.audio/src/main/java/org/openhab/core/audio/AudioHTTPServer.java, bundles/org.openhab.core.audio/src/main/java/org/openhab/core/audio/ByteArrayAudioStream.java, bundles/org.openhab.core.audio/src/main/java/org/openhab/core/audio/FileAudioStream.java, bundles/org.openhab.core.audio/src/main/java/org/openhab/core/audio/FixedLengthAudioStream.java, bundles/org.openhab.core.audio/src/main/java/org/openhab/core/audio/SizeableAudioStream.java, bundles/org.openhab.core.audio/src/main/java/org/openhab/core/audio/URLAudioStream.java, bundles/org.openhab.core.audio/src/main/java/org/openhab/core/audio/internal/AudioServlet.java, bundles/org.openhab.core.audio/src/main/java/org/openhab/core/audio/utils/AudioSinkUtilsImpl.java, bundles/org.openhab.core.audio/src/test/java/org/openhab/core/audio/internal/AudioServletTest.java, bundles/org.openhab.core.audio/src/test/java/org/openhab/core/audio/internal/fake/AudioSinkFake.java, bundles/org.openhab.core/src/main/java/org/openhab/core/cache/lru/InputStreamCacheWrapper.java
Add another way of computing sound duration (using information from the AudioFormat class)
Allows the use of a "Sizeable" interface (for AudioStream that we know the length of, but we cannot clone). We can then improve the success of the duration detection, for example for the pulseaudio sink (PR coming after). We can also give the length information to sink in more cases, even if we cannot clone the stream.
Add the support of the mark / reset methods to some common AudioStream. We then allow more stream analysis for sink requiring it (Stream analysis often requires to get back in time after consuming a few bytes)
=> [audio] Improve audio duration computation

bundles/org.openhab.core.io.rest.sitemap/src/main/java/org/openhab/core/io/rest/sitemap/SitemapSubscriptionService.java, bundles/org.openhab.core.io.rest.sitemap/src/main/java/org/openhab/core/io/rest/sitemap/internal/PageChangeListener.java, bundles/org.openhab.core.io.rest.sitemap/src/main/java/org/openhab/core/io/rest/sitemap/internal/SitemapResource.java, bundles/org.openhab.core.io.rest.sitemap/src/test/java/org/openhab/core/io/rest/sitemap/internal/SitemapResourceTest.java, bundles/org.openhab.core/src/main/java/org/openhab/core/internal/events/EventHandler.java
Fixes #3620 
There are two improvements in this PR:
- The `EventHandler` now uses a "one-thread-per-subscriber` policy. This prevents single "slow" consumers from blocking others but still preserves event order.
- The `PageChangeListener` and the `SitemapResource` have been refactored to use events instead implementing `StateChangeListener`.
=> Improve performance for state update handling 

bundles/org.openhab.core.persistence/src/main/java/org/openhab/core/persistence/filter/PersistenceIncludeFilter.java
Removing them was overlooked when #3642 was created.
=> Remove error logging from PersistenceIncludeFilter

bundles/org.openhab.core.ui/src/main/java/org/openhab/core/ui/internal/items/ItemUIRegistryImpl.java
Fix openhab/openhab-webui#1951
=> Avoid warning log introduced by PR #3644

bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/thing/EnrichedThingDTO.java
Fix #3679
If not, calls of method limitToFields by PR #3335 fails when the list of fields does not contain firmwareStatus.
=> Make firmwareStatus field not final in DTO object

bundles/org.openhab.core.automation.module.script/src/main/java/org/openhab/core/automation/module/script/internal/ScriptEngineFactoryBundleTracker.java
=> Fix wrong ready marker in ScriptEngineFactoryBundleTracker

bundles/org.openhab.core.addon.marketplace/src/main/java/org/openhab/core/addon/marketplace/AbstractRemoteAddonService.java, bundles/org.openhab.core.addon.marketplace/src/main/java/org/openhab/core/addon/marketplace/internal/community/CommunityMarketplaceAddonService.java, bundles/org.openhab.core.addon.marketplace/src/main/java/org/openhab/core/addon/marketplace/internal/json/JsonAddonService.java, bundles/org.openhab.core.addon.marketplace/src/test/java/org/openhab/core/addon/marketplace/AbstractRemoteAddonServiceTest.java, bundles/org.openhab.core.addon.marketplace/src/test/java/org/openhab/core/addon/marketplace/test/TestAddonService.java, bundles/org.openhab.core.addon/src/main/java/org/openhab/core/addon/Addon.java
=> Fix marketplace add-ons missing config description URI

bundles/org.openhab.core/src/main/java/org/openhab/core/internal/service/WatchServiceImpl.java
=> WatchService: avoid a warn log when a null hash is not a problem

bundles/org.openhab.core.audio/src/main/java/org/openhab/core/audio/internal/AudioServlet.java
Instead of 5s before.
It helps triggering the end of playback earlier for audio sinks in asynchronous mode.
=> HTTP audio servlet: check end of play every 2 seconds

bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/item/EnrichedGroupItemDTO.java, bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/item/EnrichedItemDTO.java, bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/item/EnrichedItemDTOMapper.java
This extends the enrichedItemDTO with a unitSymbol field, representing the default unit for a number item. This would be the value configured in unit metadata or the default for the dimension.
This field is required to better support sitemap input widgets in apps. When no unit is provided in the label pattern or state description, it allows the input widget to show the default unit symbol. Combined with https://github.com/openhab/openhab-core/pull/3644 this would allow to make the functionality for the input widget equivalent to the proposed functionality for BasicUI.
=> [rest] Add unit to item response

bundles/org.openhab.core/src/main/java/org/openhab/core/internal/events/EventHandler.java
Closes #3690 
On larger installations with 1000+ items the limit of 1000 elements in the queue is exceeded easily. Since no events are lost (they just take longer to be processed), the limit that needs to be exceeded before a warning is issued should be increased.
See reports on the forum.
=> Increase large event queue warn limit

bundles/org.openhab.core.voice/src/main/java/org/openhab/core/voice/internal/cache/TTSLRUCacheImpl.java, bundles/org.openhab.core.voice/src/main/resources/OH-INF/config/voice.xml, bundles/org.openhab.core.voice/src/main/resources/OH-INF/i18n/voice.properties
During the TTS cache development, there was some discussion about adding a boolean to enable / disable cache per request. We didn't keep that because it makes the API complicated.
But time passed and new usages arise, and maybe it now can be discussed, on a new form ?
For example, there is now a ChatGPT binding. It is possible to make some  advanced chat/queries with a LLM. Most of the time, the chat response are lengthy. And so one "discussion" with a LLM can clog the LRU cache and removes older entries worth keeping.
Proposal :
We can use the TTS length as a simple way to differentiate TTS sentences that should be cached, automatically. 
TTS we should cache are those that can be repeated, and they are nearly always pretty short. examples :
"Ok, I'll do that"
"Hello, what can I do for …
=> [voice] Add length limit to TTS handled by cache

bundles/org.openhab.core/src/main/java/org/openhab/core/library/unit/Units.java, bundles/org.openhab.core/src/test/java/org/openhab/core/library/unit/UnitsTest.java
=> Add unit "calorie"

bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/internal/update/UpdateChannelInstructionImpl.java
=> Keep channel properties in thing updates

bundles/org.openhab.core.ui/src/main/java/org/openhab/core/ui/internal/items/ItemUIRegistryImpl.java
Fix openhab/openhab-webui#1953
Fix a regression introduced by PR #3644
=> [Sitemap UI] Do not break format defined in label with extra spaces

bundles/org.openhab.core.config.discovery/src/test/java/org/openhab/core/config/discovery/internal/AutomaticInboxProcessorTest.java, bundles/org.openhab.core.config.discovery/src/test/java/org/openhab/core/config/discovery/internal/PersistentInboxTest.java, bundles/org.openhab.core.io.websocket/src/test/java/org/openhab/core/io/websocket/CommonWebSocketServletTest.java, bundles/org.openhab.core.persistence/src/test/java/org/openhab/core/persistence/filter/PersistenceEqualsFilterTest.java, bundles/org.openhab.core.persistence/src/test/java/org/openhab/core/persistence/filter/PersistenceIncludeFilterTest.java, itests/org.openhab.core.thing.tests/src/main/java/org/openhab/core/thing/internal/AutoUpdateManagerTest.java, pom.xml
This is the result after running:
`mvn spotless:apply -Dspotless.eclipse.version=4.25`
Perhaps we should just revert the version in the property?
I still don't know of any negative side effects and the PR will probably also build successfully while it is uses 4.26.
See also https://github.com/openhab/openhab-core/issues/3515#issuecomment-1493256202.
=> Use Eclipse formatter 4.25 with Spotless

bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/DefaultSystemChannelTypeProvider.java, itests/org.openhab.core.thing.tests/src/main/java/org/openhab/core/thing/SystemWideChannelTypesTest.java
These are only used by one binding at the moment and it's very inconsistent to have power, voltage and current with the "electric" prefix and energy with "electrical".
=> Align system-channel-types for electricity

bundles/org.openhab.core.persistence/src/main/java/org/openhab/core/persistence/filter/PersistenceIncludeFilter.java, bundles/org.openhab.core.persistence/src/main/java/org/openhab/core/persistence/filter/PersistenceThresholdFilter.java, bundles/org.openhab.core.persistence/src/main/java/org/openhab/core/persistence/filter/PersistenceTimeFilter.java
Setting up a treshold filter with the UI, it did not work because the unit field was blank. I got an NPE from PersistenceTresholdFilter, and the PersistenceIncludeFilter would also throw a NPE in that case. For PersistenceTimeFilter, defaulting to "s" is just cosmetic.
@J-N-K Picks-up PR #3681 and should be merged for the 4.0 release, because the UI does not prevent the unit field from being null.
=> [persistence] Handle null value for unit field of filters

bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/internal/item/ItemResource.java
Fixes https://github.com/openhab/openhab-webui/issues/1958.
I have checked the contents of those two fields, they should not change without a user-change to the Item.
@openhab/core-maintainers Can this please be merged for openHAB 4? The linked UI issue is a regression from https://github.com/openhab/openhab-webui/pull/1661 and https://github.com/openhab/openhab-core/pull/3335.
@ghys FYI.
=> [rest] Add missing fields to /rest/items?staticDataOnly=true resource

bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/RuleEngineImpl.java, bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/module/factory/CoreModuleHandlerFactory.java, bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/module/handler/SystemTriggerHandler.java, bundles/org.openhab.core.automation/src/test/java/org/openhab/core/automation/internal/module/handler/SystemTriggerHandlerTest.java, itests/org.openhab.core.automation.integration.tests/src/main/java/org/openhab/core/automation/integration/test/AutomationIntegrationJsonTest.java, itests/org.openhab.core.automation.integration.tests/src/main/java/org/openhab/core/automation/integration/test/AutomationIntegrationTest.java, itests/org.openhab.core.automation.integration.tests/src/main/java/org/openhab/core/automation/integration/test/RuleSimulationTest.java, itests/org.openhab.core.automation.module.core.tests/src/main/java/org/openhab/core/automation/internal/module/RunRuleModuleTest.java, itests/org.openhab.core.automation.module.core.tests/src/main/java/org/openhab/core/automation/internal/module/RuntimeRuleTest.java, itests/org.openhab.core.automation.module.timer.tests/src/main/java/org/openhab/core/automation/module/timer/internal/BasicConditionHandlerTest.java, itests/org.openhab.core.automation.module.timer.tests/src/main/java/org/openhab/core/automation/module/timer/internal/RuntimeRuleTest.java, itests/org.openhab.core.automation.tests/src/main/java/org/openhab/core/automation/event/RuleEventTest.java, itests/org.openhab.core.automation.tests/src/main/java/org/openhab/core/automation/internal/RuleEngineTest.java
=> Fix rule startlevel trigger executes during initialization

bundles/org.openhab.core.io.transport.mqtt/src/main/java/org/openhab/core/io/transport/mqtt/internal/Subscription.java
Fixes https://github.com/openhab/openhab-addons/issues/15282
=> Fix MQTT client crashes when subscriber throws exception

bundles/org.openhab.core.ui/NOTICE
@kaikreuzer This is basically the PR you requested. We want to make sure we provide accurate information about the XChart version used in our NOTICE file. For some reason it was outdated.
=> Provide correct version information for XChart in NOTICE

bundles/org.openhab.core.io.rest.auth/src/main/java/org/openhab/core/io/rest/auth/AuthFilter.java
Hi openHAB maintainers.
I just discovered testing the version 4.0.0 RC1 that I left a bug on the check of the trusted networks for the WebSocket connections.
I just by mistake couple of times servletRequest instead of request which do not api the api call validations as in that case both point to the same ref, but causes a null pointer exception when validating a websocket connection.
This issue is reproducible when you have implicitRole disabled but trustedNetworks configured in the "API Security" options and connect over WebSocket to the server (using the functionality exposed by the bundle org.openhab.core.io.websocket).
=> [Auth Filter] Fix implicit user role for websocket connections

bundles/org.openhab.core.model.rule.runtime/src/org/openhab/core/model/rule/runtime/internal/DSLRuleProvider.java, itests/org.openhab.core.model.rule.tests/src/main/java/org/openhab/core/model/rule/runtime/DSLRuleProviderTest.java
Fixes #3723 
@lolodomo can you test if that resolves your issues? On my system it seems to work fine.
=> Fix system started DSL rules

bundles/org.openhab.core.automation.module.script/src/main/resources/OH-INF/config/script-profile.xml
Fixes https://github.com/openhab/openhab-webui/issues/1981
=> Fix limitToOptions in script profile

bundles/org.openhab.core.automation.rest/src/main/java/org/openhab/core/automation/rest/internal/RuleResource.java, bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/internal/item/ItemResource.java, bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/internal/tag/TagResource.java, bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/internal/thing/ThingResource.java, bundles/org.openhab.core/src/main/java/org/openhab/core/common/registry/RegistryChangedRunnableListener.java
This implements caching for GET `/rest/tags` and GET `/rest/tags/:tagname` as in #3335 and de-duplicates RegistryChangeListener code used by nearly all cached REST resources by introducing the `RegistryChangedRunnableListener` class.
=> [rest] Add caching for TagResource & De-duplicate code for caching

bundles/org.openhab.core.persistence/src/main/java/org/openhab/core/persistence/filter/PersistenceEqualsFilter.java, bundles/org.openhab.core.persistence/src/main/java/org/openhab/core/persistence/filter/PersistenceIncludeFilter.java, bundles/org.openhab.core.persistence/src/main/java/org/openhab/core/persistence/filter/PersistenceThresholdFilter.java
This allows the UI to remove some specific checks that are performed on every save, and simplifies usage of the API for external applications.
=> [persistence] Handle `null` value for `relative` & `inverted` props of filters

bundles/org.openhab.core.automation.module.script/src/main/java/org/openhab/core/automation/module/script/internal/provider/ScriptModuleTypeProvider.java, bundles/org.openhab.core.automation/src/main/resources/OH-INF/automation/moduletypes/RuleEnablementAction.json, bundles/org.openhab.core.automation/src/main/resources/OH-INF/automation/moduletypes/RunRuleAction.json, bundles/org.openhab.core.automation/src/main/resources/OH-INF/i18n/automation.properties
Core part of https://github.com/openhab/openhab-webui/issues/1921.
With UI-support for scenes & scripts, the texts (labels, descriptions etc.) for rule-based actions should be updated to mention scenes & scripts as well. This improves the UI experience.
=> [automation] Update texts for rule-based actions

bom/compile/pom.xml, bom/runtime/pom.xml, features/karaf/openhab-tp/src/main/feature/feature.xml
Fixes CVE-2020-12695
Previous upgrade (for reference): #3421
=> Upgrade JUPnP to 2.7.1

itests/itest-include.bndrun, pom.xml
I ran into some more build issues due to this "Improved ZIP64 Extra Field Validation" (see https://github.com/openhab/openhab-core/issues/3718)  now that Temurin 17.0.8 upgrades are available in APT repos.
The org.openhab.core.karaf bundle fails to build as Java thinks there are some issues with org.apache.karaf.features.core-4.4.0.jar. However `zip -T ...` thinks it's OK. So perhaps this is a false positive. It doesn't complain about org.apache.karaf.features.core-4.4.3.jar so let's use that instead.
Also the itests generate lots of ZipException stacktraces due to the issue with geronimo-osgi-locator.jar.
=> ZipException workarounds

bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/binding/generic/ChannelHandler.java, bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/internal/binding/generic/converter/AbstractTransformingChannelHandler.java
The factory interface should be available for usage in bindings, so it needs to be in an exported package. This was overlooked when the `AbstractTransformingChannelHandler` was moved to an internal package.
=> Move factory interface to public package

bundles/org.openhab.core/src/main/java/org/openhab/core/common/QueueingThreadPoolExecutor.java, bundles/org.openhab.core/src/main/java/org/openhab/core/events/TopicEventFilter.java
This prevents issues because older documentation may not apply to Java 17.
See also openhab/openhab-addons#15406
=> Link to Java 17 documentation

bundles/org.openhab.core.semantics/pom.xml, bundles/org.openhab.core.semantics/src/main/java/org/openhab/core/semantics/internal/SemanticsMetadataProvider.java, bundles/org.openhab.core.semantics/src/test/java/org/openhab/core/semantics/internal/SemanticsMetadataProviderTest.java
In case of cyclic/recursive membership of groups (i.e. a group has itself or a child as parent) the recursive processing of the items leads to an `StackOverflowError` (reported in the forum and the german Facebook group). Also this is clearly a configuration error it should not result in the bundle not starting.
=> Fix StackOverflowError in SemanticsMetadataProvider

bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/RuleEngineImpl.java
=> Fix CME in RuleEngineImpl

bundles/org.openhab.core.model.persistence/src/org/openhab/core/model/persistence/internal/PersistenceModelManager.java, bundles/org.openhab.core.model.thing/src/org/openhab/core/model/thing/internal/GenericItemChannelLinkProvider.java, bundles/org.openhab.core/src/main/java/org/openhab/core/common/registry/AbstractProvider.java
Implementations should not use the logger of the parent
=> Fix logging in AbstractProvider implementations

bundles/org.openhab.core.io.rest.sitemap/src/main/java/org/openhab/core/io/rest/sitemap/internal/SitemapResource.java, bundles/org.openhab.core.io.rest.sitemap/src/main/java/org/openhab/core/io/rest/sitemap/internal/WidgetDTO.java, bundles/org.openhab.core.model.sitemap/src/org/openhab/core/model/sitemap/Sitemap.xtext, bundles/org.openhab.core.ui/src/main/java/org/openhab/core/ui/internal/components/UIComponentSitemapProvider.java, bundles/org.openhab.core.ui/src/main/java/org/openhab/core/ui/internal/items/ItemUIRegistryImpl.java
When set, the UI should not provide the item state when requestiong the OH icon and should not request again the icon when the item state is updated.
Related to openhab/openhab-android#3404
=> [sitemap] Add new "staticIcon" parameter

bom/compile/pom.xml, bom/runtime/pom.xml, bundles/org.openhab.core/src/main/java/org/openhab/core/common/QueueingThreadPoolExecutor.java, features/karaf/openhab-core/src/main/feature/feature.xml, features/karaf/openhab-tp/src/main/feature/feature.xml, itests/org.openhab.core.addon.tests/itest.bndrun, itests/org.openhab.core.auth.oauth2client.tests/itest.bndrun, itests/org.openhab.core.automation.integration.tests/itest.bndrun, itests/org.openhab.core.automation.module.core.tests/itest.bndrun, itests/org.openhab.core.automation.module.script.tests/itest.bndrun, itests/org.openhab.core.automation.module.timer.tests/itest.bndrun, itests/org.openhab.core.automation.tests/itest.bndrun, itests/org.openhab.core.config.core.tests/itest.bndrun, itests/org.openhab.core.config.discovery.mdns.tests/itest.bndrun, itests/org.openhab.core.config.discovery.tests/itest.bndrun, itests/org.openhab.core.config.discovery.usbserial.linuxsysfs.tests/itest.bndrun, itests/org.openhab.core.config.discovery.usbserial.tests/itest.bndrun, itests/org.openhab.core.config.dispatch.tests/itest.bndrun, itests/org.openhab.core.ephemeris.tests/itest.bndrun, itests/org.openhab.core.io.net.tests/itest.bndrun, itests/org.openhab.core.io.rest.core.tests/itest.bndrun, itests/org.openhab.core.model.item.tests/itest.bndrun, itests/org.openhab.core.model.rule.tests/itest.bndrun, itests/org.openhab.core.model.script.tests/itest.bndrun, itests/org.openhab.core.model.thing.tests/itest.bndrun, itests/org.openhab.core.storage.json.tests/itest.bndrun, itests/org.openhab.core.tests/itest.bndrun, itests/org.openhab.core.thing.tests/itest.bndrun, itests/org.openhab.core.voice.tests/itest.bndrun
This is a workaround for [JDK-8301341](https://bugs.openjdk.org/browse/JDK-8301341) by using the Java 11 `LinkedTransferQueue` with the `QueueingThreadPoolExecutor` in the Core and jUPnP.
---
Using the Java 11 `LinkedTransferQueue` is probably the most stable option because it did not cause these issues with OH3.
To be able to use the same artifact with jUPnP, jUPnP also needs to be build with Java 11 or newer (it's currently still compatible with Java 8).
I put the Java 11 `LinkedTransferQueue` in a [separate repo](https://github.com/wborn/openhab-base-fixes) because it has a GPLv2+CE license.
Perhaps the repo can also be moved to the openHAB organization?
Because Java and OpenJDK are trademarks, it is probably best to avoid these in repo and package names etc.
Let me know if you agree …
=> Use workaround to fix high CPU usage by LinkedTransferQueue

bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/internal/tag/TagResource.java
=> [REST] Check a label is provided when creating a new semantic tag

itests/org.openhab.core.automation.integration.tests/src/main/java/org/openhab/core/automation/integration/test/AutomationIntegrationJsonTest.java
=> Improve AutomationIntegrationJsonTest

bundles/org.openhab.core.io.jetty.certificate/pom.xml
This upgrades addresses:
* CVE-2016-1000338
* CVE-2016-1000339
* CVE-2016-1000340
* CVE-2016-1000341
* CVE-2016-1000342
* CVE-2016-1000343
* CVE-2016-1000344
* CVE-2018-1000613
* CVE-2019-17359
* CVE-2020-26939
The jdk18on jars are compiled to work with anything from Java 1.8 up. They are also multi-release jars so do support some features that were introduced in Java 9, Java 11, and Java 15.
=> Upgrade org.bouncycastle:bcpkix-jdk15on

bom/runtime/pom.xml, features/karaf/openhab-tp/src/main/feature/feature.xml, itests/org.openhab.core.io.rest.core.tests/itest.bndrun
Updates Jackson from 2.14.1 to 2.15.2
https://github.com/FasterXML/jackson/wiki/Jackson-Release-2.15
This upgrade addresses:
* CVE-2022-1471
=> Update Jackson to 2.15.2

bundles/org.openhab.core.audio/src/main/java/org/openhab/core/audio/internal/AudioServlet.java
Use function from nio package as it uses more restrictive file permissions.
I did not test this. We use nio.file.createTempFile in all other places in core.
=> Migrate to java.nio.file.createTempFile

bom/test/pom.xml, itests/org.openhab.core.io.rest.core.tests/itest.bndrun
Updates json-path from 2.4.0 to 2.8.0
This addresses:
* CVE-2021-27568
* CVE-2021-31684
* CVE-2023-1370
=> Update json-path to 2.8.0

bundles/org.openhab.core.ui/src/main/java/org/openhab/core/ui/internal/components/UIComponentSitemapProvider.java
See https://github.com/openhab/openhab-webui/pull/1487#issuecomment-1673764126
Sitemap visibility and color rules, maintained in mainUI failed with blanks in the condition state. This happens because string quotes are stripped from the json REST format.
This fix modifies the regex identifying the condition states to allow any character, with the exception of = in color rules, as that will identify the target color.
=> Fix sitemap visibility rule with blanks

bundles/org.openhab.core.config.discovery.usbserial.linuxsysfs/src/main/java/org/openhab/core/config/discovery/usbserial/linuxsysfs/internal/SysfsUsbSerialScanner.java
This fixes that some linuxsysfs tests always fail on Linux whenever a real serial device is connected. Due to the changes in #3290 the tests would also scan the actual devices causing tests to fail due to unexpected results.
=> Fix linuxsysfs itest failing when serial device is connected

bundles/org.openhab.core.model.thing/src/org/openhab/core/model/thing/internal/GenericThingProvider.xtend
When things from multiple handler factories are provisioned from the same file the internal thing map was not properly updated.
=> Fix GenericThingProvider

bom/compile/pom.xml, bom/runtime/pom.xml, features/karaf/openhab-tp/src/main/feature/feature.xml
Updates Swagger from 2.1.9 to 2.2.15.
This adds OpenAPI v3.1 support.
For more release notes see:
https://github.com/swagger-api/swagger-core/releases
=> Update Swagger to 2.2.15

bom/compile/pom.xml, bom/runtime/pom.xml, features/karaf/openhab-core/src/main/feature/feature.xml, itests/org.openhab.core.addon.tests/itest.bndrun, itests/org.openhab.core.auth.oauth2client.tests/itest.bndrun, itests/org.openhab.core.automation.integration.tests/itest.bndrun, itests/org.openhab.core.automation.module.core.tests/itest.bndrun, itests/org.openhab.core.automation.module.script.tests/itest.bndrun, itests/org.openhab.core.automation.module.timer.tests/itest.bndrun, itests/org.openhab.core.automation.tests/itest.bndrun, itests/org.openhab.core.config.core.tests/itest.bndrun, itests/org.openhab.core.config.discovery.mdns.tests/itest.bndrun, itests/org.openhab.core.config.discovery.tests/itest.bndrun, itests/org.openhab.core.config.discovery.usbserial.linuxsysfs.tests/itest.bndrun, itests/org.openhab.core.config.discovery.usbserial.tests/itest.bndrun, itests/org.openhab.core.config.dispatch.tests/itest.bndrun, itests/org.openhab.core.ephemeris.tests/itest.bndrun, itests/org.openhab.core.io.net.tests/itest.bndrun, itests/org.openhab.core.io.rest.core.tests/itest.bndrun, itests/org.openhab.core.model.item.tests/itest.bndrun, itests/org.openhab.core.model.rule.tests/itest.bndrun, itests/org.openhab.core.model.script.tests/itest.bndrun, itests/org.openhab.core.model.thing.tests/itest.bndrun, itests/org.openhab.core.storage.json.tests/itest.bndrun, itests/org.openhab.core.tests/itest.bndrun, itests/org.openhab.core.thing.tests/itest.bndrun, itests/org.openhab.core.voice.tests/itest.bndrun
Updates the directory-watcher from 0.17.1 to 0.18.0.
This version has some bug fixes/improvements, see:
https://github.com/gmethvin/directory-watcher/compare/v0.17.1...v0.18.0
---
Depends on https://github.com/openhab/openhab-osgiify/pull/42
=> Update directory-watcher to 0.18.0

bundles/org.openhab.core.model.script/bnd.bnd, bundles/org.openhab.core.model.script/src/org/openhab/core/model/script/actions/CoreUtil.java, bundles/org.openhab.core.model.script/src/org/openhab/core/model/script/scoping/ScriptImplicitlyImportedTypes.java
=> [DSL] Expose ColorUtil methods to DSL rules

bundles/org.openhab.core.voice/src/main/java/org/openhab/core/voice/internal/text/StandardInterpreter.java, bundles/org.openhab.core.voice/src/main/java/org/openhab/core/voice/text/AbstractRuleBasedInterpreter.java, bundles/org.openhab.core.voice/src/test/java/org/openhab/core/voice/internal/text/StandardInterpreterTest.java
Hi openHAB maintainers, I would like to add this changes to the StandardInterpreter so it uses the item synonyms and to reduce collision between items labels in case of single exact match. I think the changes can be seen as a bug fix as the current item resolution method is unchanged an takes priority in case of succeed.
Note that I have added a test suite for the StandardInterpreter with tests cases for the changes included and also some debug logs to the AbstractRuleBasedInterpreter getMatchingItems method so users have a way to know what the collisions are.
Hope everything is in place.
Best regards
=> [voice] Reduce collisions on exact match and use item synonyms

bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/internal/profiles/SystemOffsetProfile.java, bundles/org.openhab.core/src/main/java/org/openhab/core/library/types/QuantityType.java, bundles/org.openhab.core/src/test/java/org/openhab/core/library/types/QuantityTypeTest.java
Signed-off-by: Mark Herwege [mark.herwege@telenet.be](mailto:mark.herwege@telenet.be)
EDIT 05/09/23: Summary updated with analysis, conclusions and proposed behaviour.
In tests performed for a Blockly issue, it was identified that calculations with temperatures in °F produce strange results: https://github.com/openhab/openhab-webui/issues/2001#issuecomment-1699460223
Notably:
- 65 °F / Qty(1) produces 36.11 K: reason is 65° F is treated as relative temperature and the result is relative as well. Δ 1 K = Δ 0.55 °F. Converting back the result to °F therefore is not equal to 65 °F, which would be the typical expectation fo a user. Note that 65 °F / 1 does produce 65 °F, so there is a difference in behaviour between scalar and dimensionless quantity.
- 65 °F / 1 °F produces 65: seems …
=> Adjust QuantityType calculations for temperatures

bundles/org.openhab.core.addon.eclipse/src/main/java/org/openhab/core/addon/eclipse/internal/EclipseAddonService.java, bundles/org.openhab.core.addon.marketplace/src/main/java/org/openhab/core/addon/marketplace/internal/json/JsonAddonService.java, bundles/org.openhab.core.addon.marketplace/src/main/java/org/openhab/core/addon/marketplace/internal/json/model/AddonEntryDTO.java, bundles/org.openhab.core.addon/src/main/java/org/openhab/core/addon/AddonInfo.java, bundles/org.openhab.core.addon/src/main/java/org/openhab/core/addon/internal/JarFileAddonService.java, bundles/org.openhab.core.karaf/src/main/java/org/openhab/core/karaf/internal/KarafAddonService.java
Fixes the following:
* connection and countries details missing for some AddonServices
* missing connection getter on AddonInfo
* countries lists has empty String when when countries info is missing
Related to #3795
=> Fix countries and connection AddonInfo issues

bundles/org.openhab.core.voice/src/main/java/org/openhab/core/voice/DialogContext.java, bundles/org.openhab.core.voice/src/main/java/org/openhab/core/voice/DialogRegistration.java, bundles/org.openhab.core.voice/src/main/java/org/openhab/core/voice/internal/DialogProcessor.java, bundles/org.openhab.core.voice/src/main/java/org/openhab/core/voice/internal/VoiceConsoleCommandExtension.java, bundles/org.openhab.core.voice/src/main/java/org/openhab/core/voice/internal/VoiceManagerImpl.java, bundles/org.openhab.core.voice/src/main/java/org/openhab/core/voice/text/AbstractRuleBasedInterpreter.java, bundles/org.openhab.core.voice/src/main/java/org/openhab/core/voice/text/HumanLanguageInterpreter.java, bundles/org.openhab.core.voice/src/main/java/org/openhab/core/voice/text/Rule.java, bundles/org.openhab.core.voice/src/test/java/org/openhab/core/voice/internal/text/StandardInterpreterTest.java
I would like to merge this minor improvement into the voice bundle, it introduces two new configurations into the dialog context, the dialogGroup which defaults to "default" and the locationItem with defaults to null.
The dialogGroup is used to discard spot events raised at same time in different dialog executions, so you can have multiple near speakers and not "awake" them at the same time. Also fixes a race error that happened when a KS service sent two consecutive spot events.
The locationItem, is meant to optionally contain the name of a "Location" group item, it is propagated to the StandarInterpreter (to its base class to be correct) so it can reduce label collisions based on this location context.
=> [voice] Add dialog group and location

bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/internal/CommunicationManager.java, bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/internal/profiles/ProfileCallbackImpl.java, itests/org.openhab.core.thing.tests/src/main/java/org/openhab/core/thing/internal/CommunicationManagerOSGiTest.java
=> Fix CommunicationManager command handling

bundles/org.openhab.core.ui/src/main/java/org/openhab/core/ui/internal/components/UIComponentSitemapProvider.java
Fixes https://github.com/openhab/openhab-webui/issues/2082
https://github.com/openhab/openhab-core/pull/3769 fixes an issue with blanks in visibility or color command arguments. It did overlook trailing blanks in color arguments and included them in the argument.
This PR fixes this issue.
=> [sitemap mainUI] fix trailing space in state string

bom/compile/pom.xml, bom/runtime/pom.xml, features/karaf/openhab-tp/src/main/feature/feature.xml
Upgrades:
* hivemq-mqtt-client from 1.2.2 to 1.3.3
* Netty from 4.1.92.Final to 4.1.99.Final
For all fixes and improvements of these upgrades, see:
* https://github.com/hivemq/hivemq-mqtt-client/releases/
* https://netty.io/news/index.html
=> Upgrade hivemq-mqtt-client to 1.3.3, Netty to 4.1.99.Final

bom/runtime/pom.xml, bom/test/pom.xml, features/karaf/openhab-tp/src/main/feature/feature.xml, itests/org.openhab.core.io.rest.core.tests/itest.bndrun
Upgrades CXF from 3.6.1 to 3.6.2.
https://issues.apache.org/jira/secure/ReleaseNote.jspa?projectId=12310511&version=12353311
It has a fix to address OOM issues when using HTTP clients:
https://issues.apache.org/jira/browse/CXF-8885
=> Upgrade CXF to 3.6.2

bundles/org.openhab.core.io.rest.sse/src/main/java/org/openhab/core/io/rest/sse/SseResource.java, bundles/org.openhab.core.karaf/src/main/java/org/openhab/core/karaf/internal/jaas/ManagedUserBackingEngine.java, bundles/org.openhab.core.karaf/src/main/java/org/openhab/core/karaf/internal/jaas/ManagedUserBackingEngineFactory.java, bundles/org.openhab.core.karaf/src/main/java/org/openhab/core/karaf/internal/jaas/ManagedUserRealm.java
AFAIK these annotations are not used when using declarative services.
I stumbled upon these annotations when feature validation failed while creating #3817. Xtext now uses Guice 7 which is using jakarta.inject imports.
Only si.uom:si-units:2.1 still imports javax.inject but it will also switch to jakarta.inject when 2.2 gets released.
=> Remove unused javax.inject annotations

bom/test-index/pom.xml, bom/test/pom.xml, itests/org.openhab.core.addon.tests/itest.bndrun, itests/org.openhab.core.auth.oauth2client.tests/itest.bndrun, itests/org.openhab.core.automation.integration.tests/itest.bndrun, itests/org.openhab.core.automation.module.core.tests/itest.bndrun, itests/org.openhab.core.automation.module.script.tests/itest.bndrun, itests/org.openhab.core.automation.module.timer.tests/itest.bndrun, itests/org.openhab.core.automation.tests/itest.bndrun, itests/org.openhab.core.config.core.tests/itest.bndrun, itests/org.openhab.core.config.discovery.mdns.tests/itest.bndrun, itests/org.openhab.core.config.discovery.tests/itest.bndrun, itests/org.openhab.core.config.discovery.usbserial.linuxsysfs.tests/itest.bndrun, itests/org.openhab.core.config.discovery.usbserial.tests/itest.bndrun, itests/org.openhab.core.config.dispatch.tests/itest.bndrun, itests/org.openhab.core.ephemeris.tests/itest.bndrun, itests/org.openhab.core.io.net.tests/itest.bndrun, itests/org.openhab.core.io.rest.core.tests/itest.bndrun, itests/org.openhab.core.model.item.tests/itest.bndrun, itests/org.openhab.core.model.rule.tests/itest.bndrun, itests/org.openhab.core.model.script.tests/itest.bndrun, itests/org.openhab.core.model.thing.tests/itest.bndrun, itests/org.openhab.core.storage.json.tests/itest.bndrun, itests/org.openhab.core.tests/itest.bndrun, itests/org.openhab.core.thing.tests/itest.bndrun, itests/org.openhab.core.voice.tests/itest.bndrun
Upgrades JUnit from 5.9.2 to 5.10.0.
https://junit.org/junit5/docs/5.10.0/release-notes/#release-notes-5.10.0
=> Upgrade JUnit to 5.10.0

bundles/org.openhab.core.io.rest.sitemap/src/main/java/org/openhab/core/io/rest/sitemap/internal/PageChangeListener.java, bundles/org.openhab.core.io.rest.sitemap/src/main/java/org/openhab/core/io/rest/sitemap/internal/SitemapResource.java, bundles/org.openhab.core.io.rest.sitemap/src/test/java/org/openhab/core/io/rest/sitemap/internal/SitemapResourceTest.java, bundles/org.openhab.core.model.sitemap/src/org/openhab/core/model/sitemap/Sitemap.xtext, bundles/org.openhab.core.ui/src/main/java/org/openhab/core/ui/internal/components/UIComponentSitemapProvider.java, bundles/org.openhab.core.ui/src/main/java/org/openhab/core/ui/internal/items/ItemUIRegistryImpl.java, bundles/org.openhab.core.ui/src/test/java/org/openhab/core/ui/internal/items/ItemUIRegistryImplTest.java
Concerns labelcolor, valuecolor and visibility
Also fix wrong positions of ")" in Sitemap.xtext
Closes #3058
=> [Sitemap] Add support for multiple AND conditions

bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/module/handler/GenericEventTriggerHandler.java
While reviewing https://github.com/openhab/openhab-js/pull/300, I noticed that filtering by source `org.openhab.core.expire` was not possible.
This was because the specified source was checked against the event topic, which makes no sense at all given that different schemes. Source filtering is done inside the `apply` method.
In case you need some code to reproduce the described issue, just let me know.
=> Fixes source filter not working for `GenericEventTrigger`

bundles/org.openhab.core/src/main/java/org/openhab/core/library/types/DecimalType.java, bundles/org.openhab.core/src/main/java/org/openhab/core/library/types/QuantityType.java, bundles/org.openhab.core/src/test/java/org/openhab/core/library/types/DecimalTypeTest.java, bundles/org.openhab.core/src/test/java/org/openhab/core/library/types/PercentTypeTest.java, bundles/org.openhab.core/src/test/java/org/openhab/core/library/types/QuantityTypeTest.java
Resolve #3833 and https://github.com/openhab/openhab-addons/issues/13371
=> Make DecimalType, QuantityType, PercentType accept lowercased exponent notation

features/karaf/openhab-tp/src/main/feature/feature.xml
The pax-web-jetty-http2-jdk9 feature should not have been removed in #3814.
See: https://community.openhab.org/t/openhab-4-1-milestone-discussion/149502/42
=> Fix missing ALPN bundles

bundles/org.openhab.core.automation.module.media/src/main/java/org/openhab/core/automation/module/media/internal/MediaActionTypeProvider.java, bundles/org.openhab.core.automation.module.script.rulesupport/src/main/java/org/openhab/core/automation/module/script/rulesupport/internal/ScriptedCustomModuleTypeProvider.java, bundles/org.openhab.core.automation.module.script.rulesupport/src/main/java/org/openhab/core/automation/module/script/rulesupport/shared/ScriptedAutomationManager.java, bundles/org.openhab.core.automation.module.script/src/main/java/org/openhab/core/automation/module/script/internal/provider/ScriptModuleTypeProvider.java, bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/ActionImpl.java, bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/commands/CommandlineModuleTypeProvider.java, bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/commands/CommandlineTemplateProvider.java, bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/module/provider/AnnotatedActionModuleTypeProvider.java, bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/provider/ModuleTypeResourceBundleProvider.java, bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/provider/TemplateResourceBundleProvider.java, bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/provider/file/ModuleTypeFileProvider.java, bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/provider/file/TemplateFileProvider.java, bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/module/provider/AnnotationActionModuleTypeHelper.java, bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/template/RuleTemplate.java, bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/template/TemplateProvider.java, bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/thingsupport/AnnotatedThingActionModuleTypeProvider.java, bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/type/ActionType.java, bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/type/CompositeTriggerType.java, bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/type/ModuleTypeProvider.java, bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/dto/AbstractThingDTO.java, bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/dto/ChannelTypeDTO.java, bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/dto/StrippedThingTypeDTO.java, bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/dto/ThingDTO.java, bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/dto/ThingTypeDTO.java, itests/org.openhab.core.automation.integration.tests/src/main/java/org/openhab/core/automation/integration/test/AutomationIntegrationTest.java, itests/org.openhab.core.automation.tests/src/main/java/org/openhab/core/automation/internal/TestModuleTypeProvider.java
Using 'UID' is confusing as method parameter because it can be mistaken for some kind of constant while reading code.
Some were already updated in #3836.
=> Use 'uid' instead of 'UID' as method parameters

bundles/org.openhab.core.model.core/src/main/java/org/openhab/core/model/core/internal/folder/FolderObserver.java
The FolderObserver needs to make sure that paths are properly handled for any parsers that are added at any moment by other threads during activation.
Fixes #3784
Fixes #3793
---
To test the fix, update the bundle on the [Karaf console](https://www.openhab.org/docs/administration/console.html) using one of these commands and then restart openHAB.
`bundle:update org.openhab.core.model.core https://github.com/wborn/openhab-core/releases/download/folder-observer-20231020/org.openhab.core.model.core-4.0.4-SNAPSHOT.jar`
`bundle:update org.openhab.core.model.core https://github.com/wborn/openhab-core/releases/download/folder-observer-20231020/org.openhab.core.model.core-4.1.0-SNAPSHOT.jar`
=> Improve FolderObserver ignored paths handling

bundles/org.openhab.core.ui/src/main/java/org/openhab/core/ui/internal/components/UIComponentSitemapProvider.java
Close https://github.com/openhab/openhab-core/issues/3846.
Recent enhancements to the sitemap syntax completely broke UI defined sitemaps.
This PR makes sitemap definitions in the UI work again, and is a quick fix.
However, most of the new syntax will still not work in the UI. This requires a larger refactoring both in core and webui.
EDIT:
With the second commit, AND conditions in visibility, color and icon rules are now allowed.
The JSON config format has not been changed (except for the addition of iconrules) to keep full backward compatibility and avoid major refactoring on the UI side. Logic has been created to correctly interpret the condition text strings.
This logic has one inherent problem. Condition strings will be split on ' AND ' strings in their composing parts. If any of the …
=> Fix UI defined sitemaps

bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/binding/builder/BridgeBuilder.java, bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/internal/ThingManagerImpl.java
Bridges could not be updated because the updated bridge was a `ThingImpl` instead of a `BridgeImpl`. Also the copy-creator in the `BridgeBuilder` was missing. This should also be cherry-picked to 4.0.x.
=> Fix thing upgrades for bridges

bundles/org.openhab.core.audio/src/main/java/org/openhab/core/audio/internal/webaudio/WebAudioAudioSink.java
By sending an empty string we can ask the webui to stop playing sound, as specification says.
See [here ](https://github.com/openhab/openhab-webui/pull/2031)for the corresponding webui modification.
Also : By removing the URLAudioStream special case, we force the webaudio servlet to act as a proxy for every audio. It has the benefit of eliminitating CORS issue.
But there is still an issue with infinite stream. webUI (and webaudio API as it is used) does not support unlimited stream. I'm not knowledgeable enough of the webaudio API for this kind of modification (and it seems pretty hard).
The two modifications comes from this community discussion :
https://community.openhab.org/t/webaudio-not-working-when-trying-to-stream-webradio/148610/18
=> [webaudio] Allow stopping play

bundles/org.openhab.core.voice/src/main/java/org/openhab/core/voice/internal/text/StandardInterpreter.java, bundles/org.openhab.core.voice/src/main/java/org/openhab/core/voice/text/AbstractRuleBasedInterpreter.java, bundles/org.openhab.core.voice/src/main/java/org/openhab/core/voice/text/Rule.java, bundles/org.openhab.core.voice/src/test/java/org/openhab/core/voice/internal/text/StandardInterpreterTest.java
Hello OpenHAB's maintainers, I would like to merge the following changes in the voice bundle.
It enables support in the standard interpreter to use the item StateDescription/CommandDescription labels to update them in the current available languages.
As an example: 
If you have a dimmer item labeled as `Brightness` with command description `50=normal`, the command `set brightness to normal` will be handled and send a PercentageType command with value 50 to the item.
French and German command needs to be reviewed, I made them by coping the color command or using a translator.  
It introduces a minor behavior change, if the language (a locale instance) is provided only the rules for that language are loaded. I think it's the correct thing to do in order to avoid register rules you are not …
=> [voice] Support item descriptions in built-in interpreter.

bundles/org.openhab.core.io.rest.sse/src/main/java/org/openhab/core/io/rest/sse/internal/SseItemStatesEventBuilder.java
During openhab startup the following warnings were logged:
```
09:35:16.934 [WARN ] [se.internal.SseItemStatesEventBuilder] - Attempting to send a state update of an item which doesn't exist: Power_Load_Display
09:35:16.935 [WARN ] [se.internal.SseItemStatesEventBuilder] - Attempting to send a state update of an item which doesn't exist: Power_From_Solar_Display
09:35:16.937 [WARN ] [se.internal.SseItemStatesEventBuilder] - Attempting to send a state update of an item which doesn't exist: Power_From_Grid
09:35:16.938 [WARN ] [se.internal.SseItemStatesEventBuilder] - Attempting to send a state update of an item which doesn't exist: Power_From_Grid_Display
09:35:16.939 [WARN ] [se.internal.SseItemStatesEventBuilder] - Attempting to send a state update of an item which doesn't exist: …
```
=> Suppress SseItemStates warnings during startup

bundles/org.openhab.core.io.rest.sitemap/src/main/java/org/openhab/core/io/rest/sitemap/internal/PageChangeListener.java, bundles/org.openhab.core.io.rest.sitemap/src/main/java/org/openhab/core/io/rest/sitemap/internal/SitemapResource.java, bundles/org.openhab.core.io.rest.sitemap/src/main/java/org/openhab/core/io/rest/sitemap/internal/SitemapWidgetEvent.java, bundles/org.openhab.core.io.rest.sitemap/src/main/java/org/openhab/core/io/rest/sitemap/internal/WidgetDTO.java, bundles/org.openhab.core.io.rest.sitemap/src/test/java/org/openhab/core/io/rest/sitemap/internal/SitemapResourceTest.java, bundles/org.openhab.core.ui/src/main/java/org/openhab/core/ui/internal/items/ItemUIRegistryImpl.java, bundles/org.openhab.core.ui/src/main/java/org/openhab/core/ui/items/ItemUIRegistry.java, bundles/org.openhab.core.ui/src/test/java/org/openhab/core/ui/internal/items/ItemUIRegistryImplTest.java
The label can be populated from a label specified on the respective sitemap widget, or (if no label was specified) from the label of the backing item. Allow clients to differentiate between both cases. This allows clients (BasicUI, mobile apps) to e.g. show the label for charts if they were specified on the sitemap widget and to hide it when it just was populated from the item label.
Related to openhab/openhab-webui#2065
=> [sitemap] Provide information about widget label source to clients

bundles/org.openhab.core/src/main/java/org/openhab/core/util/ColorUtil.java, bundles/org.openhab.core/src/test/java/org/openhab/core/util/ColorUtilTest.java
For KNX DPT251.600 to use all 4 colors.
With the new feature, the HSBType can converted into RGBW, and also back to HSB.
Due to the conversion, some accuracy is lost, but the result is approximately correct.
=> [core] Add conversion for HSB to RGBW and back

bundles/org.openhab.core.audio/src/test/java/org/openhab/core/audio/internal/AudioManagerTest.java, bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/ModuleHandlerCallback.java, bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/RuleManager.java, bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/RuleEngineImpl.java, bundles/org.openhab.core.model.rule/src/org/openhab/core/model/rule/jvmmodel/RulesJvmModelInferrer.xtend, bundles/org.openhab.core.model.script/src/org/openhab/core/model/script/jvmmodel/ScriptJvmModelInferrer.xtend, bundles/org.openhab.core.semantics/src/main/java/org/openhab/core/semantics/SemanticTagRegistry.java, bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/internal/ThingRegistryImpl.java, bundles/org.openhab.core/src/main/java/org/openhab/core/common/registry/AbstractManagedProvider.java, bundles/org.openhab.core/src/main/java/org/openhab/core/internal/service/WatchServiceImpl.java
* Removes hyphens from JavaDoc parameters
* Fixes a few 'exists' grammar mistakes
=> Small code cleanup

bundles/org.openhab.core.storage.json/src/main/java/org/openhab/core/storage/json/internal/JsonStorage.java
The intention of this PR was to have less idling threads created by the Timer instances.
A `ScheduledExecutorService` is now used instead to have only some worker threads.
This PR will also fix two issues of this class:
1. The commitTimerTask field was never set to another value than null.
See line 411 in the old version, it should be `this.commitTimerTask = new CommitTimerTask();` and not `commitTimerTask = new CommitTimerTask();`
2. The conversion between milliseconds and nanoseconds was incorrect it should have been `maxDeferredPeriod * 1000000L` and not `maxDeferredPeriod * 1000L`.
=> Use a scheduled thread pool in JsonStorage + Bugfixes

bundles/org.openhab.core/src/main/java/org/openhab/core/internal/events/EventHandler.java
This PR will use a single thread to watch all event executors. Having one watcher thread for each event thread is not needed, the only task is to print a log line with a warning about slow dispatching of a event.
On my system, this one thread will replace 15 watcher threads.
=> Use a single thread to watch all event executors

bundles/org.openhab.core/src/main/java/org/openhab/core/common/ThreadPoolManager.java
In theory the `ThreadPoolManager` could leak running thread pools an create new ones.
I have not seen this in the wild, but it could happen.
The `ThreadPoolManager` did use a `WeakHashMap<String, ExecutorService>` to store the running pools.
It holds a weak reference to the `String` and a strong to the `ExecutorService`.
As soon as the `String` gets collected by the GC, the strong reference to the `ExecutorService` is dopped.
This is a example of problematic code, this could create two pools when GC did clear the `WeakReferences` between the two calls to `ThreadPoolManager.getScheduledPoolUnwrapped`:
```
ThreadPoolManager.getScheduledPoolUnwrapped("test" + 1);
System.gc();
ThreadPoolManager.getScheduledPoolUnwrapped("test" + 1);
```
Beside this, there are [other issues like …
=> Do not leak running pools from the internal collection

bundles/org.openhab.core.io.websocket/src/main/java/org/openhab/core/io/websocket/event/EventWebSocket.java, bundles/org.openhab.core.io.websocket/src/main/java/org/openhab/core/io/websocket/event/ItemEventUtility.java, bundles/org.openhab.core.io.websocket/src/test/java/org/openhab/core/io/websocket/ItemEventUtilityTest.java
Follow-up to #3597 
This allows sending time-series events from web socket connections.
=> Add time-series support for websockets

bundles/org.openhab.core.io.rest.sitemap/src/main/java/org/openhab/core/io/rest/sitemap/internal/MappingDTO.java, bundles/org.openhab.core.io.rest.sitemap/src/main/java/org/openhab/core/io/rest/sitemap/internal/SitemapResource.java, bundles/org.openhab.core.io.rest.sitemap/src/main/java/org/openhab/core/io/rest/sitemap/internal/WidgetDTO.java, bundles/org.openhab.core.model.sitemap/src/org/openhab/core/model/sitemap/Sitemap.xtext, bundles/org.openhab.core.ui/src/main/java/org/openhab/core/ui/internal/components/UIComponentSitemapProvider.java
Follow-up #3810
Location in the grid is now defined by a row number and a column number.
Signed-off-by: Laurent Garnier <lg.hc@ree.fr>
=> [Sitemap] Change syntax for Buttongrid sitemap element

bundles/org.openhab.core.voice/src/main/java/org/openhab/core/voice/internal/text/StandardInterpreter.java, bundles/org.openhab.core.voice/src/main/java/org/openhab/core/voice/text/AbstractRuleBasedInterpreter.java, bundles/org.openhab.core.voice/src/main/java/org/openhab/core/voice/text/Rule.java, bundles/org.openhab.core.voice/src/main/resources/LanguageSupport_es.properties, bundles/org.openhab.core.voice/src/test/java/org/openhab/core/voice/internal/text/StandardInterpreterTest.java
Hello OpenHAB maintainers, I would like to merge these PR which is a continuation of https://github.com/openhab/openhab-core/pull/3853 to include support for custom rules declared on the item metadata namespace voice system. 
It introduces a breaking change over it because it changes the dynamic token from `*` to `$*$`. These way it looks similar to the other supported special tokens `$name$` and `$cmd$`.
I let here a small summary of the interpreter functionality after these PR.
BR
---------
The built-in text rule engine in OpenHAB.
The interpreter resolves the item name based on the its label/synonyms and it's parent label/synonyms.
An example of the possible situations will be:
If you have `Group` item labeled as `TV` with a `Dimmer` child `Brightness`.
The interpreter understands …
=> [voice] Support custom rules on item metadata

bundles/org.openhab.core.addon/src/main/java/org/openhab/core/addon/AddonInfo.java, bundles/org.openhab.core.addon/src/main/java/org/openhab/core/addon/AddonInfoRegistry.java, bundles/org.openhab.core.addon/src/main/java/org/openhab/core/addon/internal/xml/AddonInfoAddonsXmlProvider.java
Fixes [#2204](https://github.com/openhab/openhab-webui/issues/2204)
Since time is of the essence, I am opening this PR now for code review. I will create and test a full OH build tomorrow.
=> [addon] Fix localisation of suggested Add-ons

bundles/org.openhab.core.addon.eclipse/src/main/java/org/openhab/core/addon/eclipse/internal/EclipseAddonService.java, bundles/org.openhab.core.addon/src/main/java/org/openhab/core/addon/AddonInfo.java, bundles/org.openhab.core.addon/src/main/java/org/openhab/core/addon/AddonInfoRegistry.java, bundles/org.openhab.core.addon/src/main/java/org/openhab/core/addon/internal/xml/AddonInfoAddonsXmlProvider.java, bundles/org.openhab.core.karaf/src/main/java/org/openhab/core/karaf/internal/KarafAddonService.java
Fixes https://github.com/openhab/openhab-webui/issues/2204
Replaces https://github.com/openhab/openhab-core/pull/3905
The issue is that no addon info is available for distribution addons before installation. The only thing available is the feature description and the addon endpoint gets it from the addon data, not the addonInfo data. So a merge of addonInfo is not even happening.
This change introduces a flag in AddonInfo indicating if it is the master info or not. When the info is coming from the addon repository scan, it is flagged to not be the master data and name and description will be ignored (because localization info is not available). Addon services will check if the addon info is master info, and only then update name and description.
=> Fix addon name localisation before installation

bundles/org.openhab.core/src/main/resources/OH-INF/config/addons.xml, bundles/org.openhab.core/src/main/resources/OH-INF/i18n/addons.properties
Closes https://github.com/openhab/openhab-core/issues/3911#issuecomment-1849067618
Internationalization of finder config parameters was missed.
Also made configuration description more explicit on what to expect, see https://github.com/openhab/openhab-addons/issues/16023#issuecomment-1849079270
=> Internationalization suggestion finders config

bundles/org.openhab.core.config.discovery.addon.upnp/src/main/java/org/openhab/core/config/discovery/addon/upnp/UpnpAddonFinder.java
Potentially fixes https://github.com/openhab/openhab-addons/issues/16036
In the above-mentioned issue, it has been reported that the UPnpAddonFinder may not be finding computers which are running the deconz application. Whereas by contrast the deconz binding's bridge discovery (based on UpnpDiscoveryParticipant) does find the respective computer.
A potential reason could be that `UpnpAddonFinder` issues a root device search (`M-SEARCH ST: upnp:rootdevice`) and perhaps the deconz application has a bug whereby it does not respond to root device searches.
On the other hand the `UpnpDiscoveryService` issues both a root device search plus also a 'catch-all' search (`M-SEARCH ST: ssdp:all`) so perhaps the deconz application does respond to the latter search but not the former.
Notes:
1. this is …
=> UpnpAddonFinder execute M-SEARCH ST: ssdp:all

bundles/org.openhab.core.config.core/src/main/java/org/openhab/core/config/core/CurrencyServiceConfigOptionProvider.java, bundles/org.openhab.core.config.core/src/main/java/org/openhab/core/config/core/internal/i18n/I18nConfigOptionsProvider.java, bundles/org.openhab.core/src/main/java/org/openhab/core/internal/i18n/I18nProviderImpl.java, bundles/org.openhab.core/src/main/java/org/openhab/core/internal/library/unit/CurrencyConverter.java, bundles/org.openhab.core/src/main/java/org/openhab/core/internal/library/unit/CurrencyService.java, bundles/org.openhab.core/src/main/java/org/openhab/core/internal/library/unit/FixedCurrencyProvider.java, bundles/org.openhab.core/src/main/java/org/openhab/core/internal/library/unit/LocaleBasedCurrencyProvider.java, bundles/org.openhab.core/src/main/java/org/openhab/core/internal/library/unit/UnitInitializer.java, bundles/org.openhab.core/src/main/java/org/openhab/core/library/dimension/Currency.java, bundles/org.openhab.core/src/main/java/org/openhab/core/library/dimension/EnergyPrice.java, bundles/org.openhab.core/src/main/java/org/openhab/core/library/unit/CurrencyProvider.java, bundles/org.openhab.core/src/main/java/org/openhab/core/library/unit/CurrencyUnit.java, bundles/org.openhab.core/src/main/java/org/openhab/core/library/unit/CurrencyUnits.java, bundles/org.openhab.core/src/main/java/org/openhab/core/types/util/UnitUtils.java, bundles/org.openhab.core/src/main/resources/OH-INF/config/i18n.xml, bundles/org.openhab.core/src/main/resources/OH-INF/config/units.xml, bundles/org.openhab.core/src/test/java/org/openhab/core/internal/i18n/I18nProviderImplTest.java, bundles/org.openhab.core/src/test/java/org/openhab/core/library/unit/CurrencyUnitTest.java
Closes #3408 
Related to #3478 
This enables currency handling for UoM. You can define prices (e.g. `0.336 €/kWh`) and do calculations based on that like any other unit.
Currently you can define a "system currency" (e.g. `€`, defaults zu `@` if not set at all) which is then available as any other unit. It is also possible to define a `CurrencyProvider` which adds additional currencies and their exchange rates (relative to the system currency). Switching between different currency providers is not yet implemented.
=> [UoM] Add currency handling 

bundles/org.openhab.core.addon/src/main/java/org/openhab/core/addon/internal/JarFileAddonService.java
Add-ons provided as jar files in the addons in the add-on folder did not have any information about loggers, so the logger could not be set through the UI.
As jar files are often provided to test new add-on functionality, the ability to set logging in the UI is relevant.
This PR adds the symbolic name as the name for the logger, which should be the main logger for most of the jar file provided add-ons.
=> Make logger for jar file add-ons configurable in UI

bundles/org.openhab.core.voice/src/main/java/org/openhab/core/voice/internal/text/StandardInterpreter.java, bundles/org.openhab.core.voice/src/main/java/org/openhab/core/voice/text/AbstractRuleBasedInterpreter.java, bundles/org.openhab.core.voice/src/main/java/org/openhab/core/voice/text/Rule.java, bundles/org.openhab.core.voice/src/test/java/org/openhab/core/voice/internal/text/StandardInterpreterTest.java
Hello, I would like to merge these fixes related to #3897.
It fixes an error introduced in that PR because the "?" should be removed when tokenizing unless when tokenizing the custom rule text, if not, it's imposible to match a question with the current implementation.
Also I have introduced the option to allow a custom rule to send a command no matter the item is already on that state, because if you are going to use the item to trigger a rule "on command received" instead of "on state change" you want the rule to behave that way and send the command always.
=> [Voice] Fix match question and allow force command

bundles/org.openhab.core.config.discovery.addon.upnp/src/main/java/org/openhab/core/config/discovery/addon/upnp/UpnpAddonFinder.java, bundles/org.openhab.core.config.discovery.upnp/src/main/java/org/openhab/core/config/discovery/upnp/internal/UpnpDiscoveryService.java
Following release of OH v4.1M5 some users found that the new Add-on Suggestion Finder was not discovering all UPnP devices on their LAN.
The OH UPnP discovery mechanism currently sends an `M-SEARCH` broadcast with a search target `ST: ssdp:all` header -- yet some devices do not respond to broadcasts with `ST: ssdp:all` and only respond to broadcasts with `ST: upnp:rootdevice`.
This PR adds a `M-SEARCH` broadcast with search target `ST: upnp:rootdevice`.
The functionality of this PR was tested already live via https://github.com/openhab/openhab-addons/pull/16077
=> UPnP add M-SEARCH for root devices

bundles/org.openhab.core.addon/src/main/java/org/openhab/core/addon/internal/xml/AddonInfoAddonsXmlProvider.java
This PR is intended to get more information if reading of addons.xml / openhab-addons.xml is failing.
It indicates in which line the problem is located.
```
22:17:11.743 [WARN ] [ternal.xml.AddonInfoAddonsXmlProvider] - File 'openhab-addons.xml' has invalid content:
---- Debugging information ----
cause-exception     : com.thoughtworks.xstream.mapper.CannotResolveClassException
cause-message       : mdns-service-type
class               : java.util.ArrayList
required-type       : java.util.ArrayList
converter-type      : com.thoughtworks.xstream.converters.collections.CollectionConverter
path                : /addon-info-list/addons/addon[18]/discovery-methods/discovery-method/mdns-service-type
line number         : 238
class[1]            : org.openhab.core.addon.AddonDiscoveryMethod …
```
=> Additional logging AddonInfo addons.xml

bundles/org.openhab.core/src/main/resources/OH-INF/i18n/i18n.properties, bundles/org.openhab.core/src/main/resources/OH-INF/i18n/network.properties, bundles/org.openhab.core/src/main/resources/OH-INF/i18n/units.properties
Seems missing from #3503.
Generated by:
```shell
mvn i18n:generate-default-translations
```
Then manually moved to new file `units.properties` where I manually added the last line:
```ini
service.system.units.label = Unit Settings
```
I don't know if this is the correct process or if there is a better one.
To make sure the manually added label is correct, I built and tested it with a Danish string provided:
=> Provide I18N properties for Unit Settings

bundles/org.openhab.core.config.discovery.addon/src/main/java/org/openhab/core/config/discovery/addon/AddonSuggestionService.java
Fixes #3946 
@kaikreuzer / @mherwege can you please check this? I am not sure if the fix that I proposed is fully sufficient to synchronize the stream access, if synchronization also needs to be applied in the other methods that access `addonFinders` or `addonInfoProviders` too??
``
public void addAddonInfoProvider(AddonInfoProvider addonInfoProvider) {
public void removeAddonInfoProvider(AddonInfoProvider addonInfoProvider) {
public void addAddonFinder(AddonFinder addonFinder) {
public void removeAddonFinder(AddonFinder addonFinder) {
```
=> Fix for #3946

bundles/org.openhab.core.addon.marketplace/src/main/java/org/openhab/core/addon/marketplace/AbstractRemoteAddonService.java, bundles/org.openhab.core.addon.marketplace/src/main/java/org/openhab/core/addon/marketplace/internal/json/JsonAddonService.java, bundles/org.openhab.core.addon.marketplace/src/test/java/org/openhab/core/addon/marketplace/AbstractRemoteAddonServiceTest.java
Missing UIDs or multiple versions of the same add-on resulted in duplicate entries for the community marketplace or JSON add-on service. With this fix add-ons with missing UID (i.e. from versions pre-4.0, before UIDs were introduced in the JSON) are now discarded and duplicate UIDs are filtered, with compatible add-ons and - if same compatibility - higher version being preferred. This is mostly a bug-fix, but also necessary for the upcoming multi-version community-marketplace add-ons I'm working on (see #3852). Since it affects users I suggest to also back-port it to `4.1.x`.
=> Fix duplicate UIDs in remote add-on services

bundles/org.openhab.core.config.discovery/src/main/java/org/openhab/core/config/discovery/AbstractDiscoveryService.java, bundles/org.openhab.core.io.net/src/main/java/org/openhab/core/io/net/http/HttpUtil.java, bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/internal/thing/ThingResource.java, bundles/org.openhab.core.io.transport.mqtt/src/main/java/org/openhab/core/io/transport/mqtt/MqttWillAndTestament.java, bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/internal/profiles/SystemHysteresisStateProfile.java, bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/internal/profiles/SystemRangeStateProfile.java, bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/internal/profiles/TimestampOffsetProfile.java, bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/xml/internal/StateDescriptionConverter.java, bundles/org.openhab.core.ui.icon/src/main/java/org/openhab/core/ui/icon/AbstractResourceIconProvider.java, bundles/org.openhab.core.ui/src/main/java/org/openhab/core/ui/internal/components/UIComponentSitemapProvider.java, bundles/org.openhab.core/src/main/java/org/openhab/core/net/NetUtil.java
Using primitives makes the code faster and consume less memory.
=> Remove unnecessary boxing

bundles/org.openhab.core.audio/src/main/java/org/openhab/core/audio/internal/AudioManagerImpl.java, bundles/org.openhab.core.config.core/src/test/java/org/openhab/core/config/core/ConfigurableServiceUtilTest.java, bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/internal/service/ConfigurableServiceResource.java, bundles/org.openhab.core.voice/src/main/java/org/openhab/core/voice/internal/VoiceManagerImpl.java, bundles/org.openhab.core.voice/src/main/java/org/openhab/core/voice/text/AbstractRuleBasedInterpreter.java, bundles/org.openhab.core/src/main/java/org/openhab/core/common/ThreadPoolManager.java, bundles/org.openhab.core/src/main/java/org/openhab/core/scheduler/CronAdjuster.java, bundles/org.openhab.core/src/test/java/org/openhab/core/cache/lru/LRUMediaCacheTest.java
These parentheses do not change the meaning of the code and also do not improve the readability.
=> Remove unnecessary parenthesis from lambdas

bundles/org.openhab.core.automation.rest/src/main/java/org/openhab/core/automation/rest/internal/RuleResource.java, bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/internal/item/ItemResource.java, bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/internal/tag/TagResource.java, bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/internal/thing/ThingResource.java, bundles/org.openhab.core.io.rest.ui/src/main/java/org/openhab/core/io/rest/ui/internal/UIResource.java, bundles/org.openhab.core.io.rest/src/main/java/org/openhab/core/io/rest/internal/resources/SystemInfoResource.java
Fixes https://github.com/openhab/openhab-webui/issues/2102, where Firefox users reported problems with outdated data in Main UI due to Firefox handling caching different than Chromium.
Also reported on the community, e.g. https://community.openhab.org/t/firefox-oh-4-0-1-issues/148633 and https://community.openhab.org/t/updating-widget-code-not-working/148265.
This forces the browser to revalidate the cache every time it is accessed to ensure the data is always fresh. See https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control#directives.
This is approach is also suggested in the mdn web docs, see https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control#up-to-date_contents_always.
This PR should be backported to 4.1.x.
=> [rest] Add `no-cache` directive to cached REST responses

bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/module/handler/GroupCommandTriggerHandler.java, bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/module/handler/GroupStateTriggerHandler.java, bundles/org.openhab.core.automation/src/test/java/org/openhab/core/automation/internal/module/handler/GroupCommandTriggerHandlerTest.java, bundles/org.openhab.core.automation/src/test/java/org/openhab/core/automation/internal/module/handler/GroupStateTriggerHandlerTest.java
Reported on the community forum. The handler checks if the item's group names contains the configured value. A `null` group name results in the NPW during that check.
=> Fix NPE in GroupStateTriggerHandler and GroupCommandTriggerHandler

bundles/org.openhab.core.addon/src/main/java/org/openhab/core/addon/internal/xml/AddonDiscoveryMethodConverter.java, bundles/org.openhab.core.addon/src/main/java/org/openhab/core/addon/internal/xml/AddonInfoConverter.java, bundles/org.openhab.core.addon/src/main/java/org/openhab/core/addon/internal/xml/AddonInfoListConverter.java, bundles/org.openhab.core.audio/src/main/java/org/openhab/core/audio/internal/AudioServlet.java, bundles/org.openhab.core.automation.module.media/src/main/java/org/openhab/core/automation/module/media/internal/MediaActionTypeProvider.java, bundles/org.openhab.core.config.core/src/main/java/org/openhab/core/config/core/internal/i18n/I18nConfigOptionsProvider.java, bundles/org.openhab.core.config.core/src/main/java/org/openhab/core/config/core/internal/validation/OptionsValidator.java, bundles/org.openhab.core.config.discovery.addon.ip/src/main/java/org/openhab/core/config/discovery/addon/ip/IpAddonFinder.java, bundles/org.openhab.core.config.discovery.addon.mdns/src/main/java/org/openhab/core/config/discovery/addon/mdns/MDNSAddonFinder.java, bundles/org.openhab.core.config.discovery.addon.upnp/src/main/java/org/openhab/core/config/discovery/addon/upnp/UpnpAddonFinder.java, bundles/org.openhab.core.config.discovery.addon.usb/src/main/java/org/openhab/core/config/discovery/addon/usb/UsbAddonFinder.java, bundles/org.openhab.core.config.discovery/src/main/java/org/openhab/core/config/discovery/AbstractDiscoveryService.java, bundles/org.openhab.core.config.dispatch/src/main/java/org/openhab/core/config/dispatch/internal/ConfigDispatcher.java, bundles/org.openhab.core.io.console/src/main/java/org/openhab/core/io/console/internal/extension/ItemConsoleCommandCompleter.java, bundles/org.openhab.core.io.console/src/main/java/org/openhab/core/io/console/internal/extension/ItemConsoleCommandExtension.java, bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/internal/item/MetadataSelectorMatcher.java, bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/internal/profile/ProfileTypeResource.java, bundles/org.openhab.core.io.transport.modbus/src/main/java/org/openhab/core/io/transport/modbus/BitArray.java, bundles/org.openhab.core.io.transport.modbus/src/main/java/org/openhab/core/io/transport/modbus/ValueBuffer.java, bundles/org.openhab.core.io.transport.modbus/src/main/java/org/openhab/core/io/transport/modbus/internal/ModbusManagerImpl.java, bundles/org.openhab.core.io.transport.modbus/src/main/java/org/openhab/core/io/transport/modbus/internal/ModbusSlaveErrorResponseExceptionImpl.java, bundles/org.openhab.core.io.transport.modbus/src/test/java/org/openhab/core/io/transport/modbus/test/BitUtilitiesExtractIndividualMethodsTest.java, bundles/org.openhab.core.semantics/src/main/java/org/openhab/core/semantics/internal/SemanticTagRegistryImpl.java, bundles/org.openhab.core.storage.json/src/main/java/org/openhab/core/storage/json/internal/JsonStorage.java, bundles/org.openhab.core.storage.json/src/main/java/org/openhab/core/storage/json/internal/StorageEntryMapDeserializer.java, bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/i18n/ThingStatusInfoI18nLocalizationService.java, bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/link/AbstractLinkRegistry.java, bundles/org.openhab.core.ui/src/main/java/org/openhab/core/ui/internal/chart/defaultchartprovider/DefaultChartProvider.java
Method references are more readable because they refer to class names and usually result in less code.
=> Replace lambdas with method references

bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/commands/AutomationCommandsPluggable.java, bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/internal/item/MetadataSelectorMatcher.java, bundles/org.openhab.core.io.rest/src/main/java/org/openhab/core/io/rest/internal/filter/CorsFilter.java, bundles/org.openhab.core.io.transport.serial.rxtx/src/main/java/org/openhab/core/io/transport/serial/internal/SerialPortUtil.java, bundles/org.openhab.core.model.core/src/main/java/org/openhab/core/model/core/internal/ModelRepositoryImpl.java, bundles/org.openhab.core.model.thing/src/org/openhab/core/model/thing/valueconverter/UIDtoStringConverter.java, bundles/org.openhab.core/src/main/java/org/openhab/core/items/GenericItem.java, bundles/org.openhab.core/src/main/java/org/openhab/core/items/GroupItem.java, itests/org.openhab.core.config.dispatch.tests/src/main/java/org/openhab/core/config/dispatch/internal/ConfigDispatcherOSGiTest.java
String.join results in less code when joining an Iterable or Array.
=> Use String.join instead of Collectors.joining

bundles/org.openhab.core.io.transport.mdns/src/main/java/org/openhab/core/io/transport/mdns/internal/MDNSClientImpl.java
=> Consider network settings to avoid creating unexpected JmDNS instances

bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/internal/addons/AddonResource.java
Fixes #3987 
We can easily check if the requested service supports the add-on and respond with "NOT_FOUND" when the service is unknown or the add-on is not available from that service.
=> Respond with 404 if add-on is missing in add-on service

bundles/org.openhab.core.config.core/src/main/java/org/openhab/core/config/core/internal/net/NetworkConfigOptionProvider.java
This allows for selecting network interface names in configuration parameters.
Just add `<context>network-interface</context>` to your config parameter similar to `<context>serial-port</context>` .
=> Add network-interface context

bundles/org.openhab.core/src/main/java/org/openhab/core/Activator.java
openHAB currently logs during startup something like
```
22:09:04.949 [INFO ] [org.openhab.core.Activator          ] - Starting openHAB 4.2.0 (build Unknown Build No.)
```
The word `build` seems unnecessary here.
- In case of a release build, the `version.properties` file contains `Release Build`
- In case of a snapshot build, the `version.properties` file contains `Build #3814`
In all cases, we hence do not need the word `build` before it.
=> Fix build number reporting at startup

bom/runtime/pom.xml, bundles/org.openhab.core.config.discovery/src/main/java/org/openhab/core/config/discovery/AbstractDiscoveryService.java, bundles/org.openhab.core.config.discovery/src/main/java/org/openhab/core/config/discovery/AbstractThingHandlerDiscoveryService.java, bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/binding/BaseThingHandlerFactory.java, bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/binding/ThingHandlerService.java, features/karaf/openhab-tp/src/main/feature/feature.xml, itests/org.openhab.core.automation.integration.tests/itest.bndrun, itests/org.openhab.core.automation.module.core.tests/itest.bndrun, itests/org.openhab.core.automation.module.script.tests/itest.bndrun, itests/org.openhab.core.automation.module.timer.tests/itest.bndrun, itests/org.openhab.core.automation.tests/itest.bndrun, itests/org.openhab.core.config.discovery.mdns.tests/itest.bndrun, itests/org.openhab.core.config.discovery.tests/itest.bndrun, itests/org.openhab.core.config.discovery.usbserial.linuxsysfs.tests/itest.bndrun, itests/org.openhab.core.config.discovery.usbserial.tests/itest.bndrun, itests/org.openhab.core.io.rest.core.tests/itest.bndrun, itests/org.openhab.core.model.item.tests/itest.bndrun, itests/org.openhab.core.model.rule.tests/itest.bndrun, itests/org.openhab.core.model.script.tests/itest.bndrun, itests/org.openhab.core.model.thing.tests/itest.bndrun, itests/org.openhab.core.storage.json.tests/itest.bndrun, itests/org.openhab.core.thing.tests/itest.bndrun, itests/org.openhab.core.voice.tests/itest.bndrun
Supersedes #1941 
Since Connor is no longer available I decided to pick up the PR and enhance it. A very good example why we should go this way is https://github.com/openhab/openhab-addons/pull/16037. It implements a `TheKeyTranslationProvider.java` just to pass it from the handler factory to the thing handler and then to the `ThinghandlerService` for localization of the discovery results. There is already similar code in the repository. This is only necessary because we can't inject OSGi services directly to the discovery services.
I started with two implementations in openhab-addons (https://github.com/openhab/openhab-addons/pull/16107) and would like to hear comments from @openhab/core-maintainers before I start a bigger refactoring in openhab-addons.
=> Refactor ThingHandlerService to an OSGi component prototype

bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/internal/persistence/PersistenceResource.java, bundles/org.openhab.core.io.transport.modbus/src/main/java/org/openhab/core/io/transport/modbus/json/WriteRequestJsonUtilities.java, bundles/org.openhab.core.io.transport.mqtt/src/main/java/org/openhab/core/io/transport/mqtt/MqttBrokerConnectionConfig.java, bundles/org.openhab.core.model.core/src/main/java/org/openhab/core/model/core/internal/ModelRepositoryImpl.java, bundles/org.openhab.core.model.script/src/org/openhab/core/model/script/engine/ScriptException.java, bundles/org.openhab.core.ui/src/main/java/org/openhab/core/ui/internal/items/ItemUIRegistryImpl.java, bundles/org.openhab.core/src/main/java/org/openhab/core/internal/items/ExpireManager.java, bundles/org.openhab.core/src/main/java/org/openhab/core/util/StringUtils.java, bundles/org.openhab.core/src/test/java/org/openhab/core/common/QueueingThreadPoolExecutorTest.java, itests/org.openhab.core.thing.tests/src/main/java/org/openhab/core/thing/xml/test/ConfigDescriptionsTest.java
`isEmpty()` expresses the intent more clearly and is therefore preferred. Counting the number of elements can also be an expensive operation e.g. when using linked lists.
=> Use isEmpty instead of 0 comparisons

bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/commands/AutomationCommandsPluggable.java, bundles/org.openhab.core.io.transport.modbus/src/main/java/org/openhab/core/io/transport/modbus/ModbusBitUtilities.java, bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/internal/firmware/ProgressCallbackImpl.java, bundles/org.openhab.core/src/test/java/org/openhab/core/library/items/StateUtil.java
These array creations are unnecessary because arrays are created automatically for methods using varargs.
=> Remove redundant array creation for calling varargs methods

bundles/org.openhab.core.audio/src/main/java/org/openhab/core/audio/utils/ToneSynthesizer.java, bundles/org.openhab.core.io.transport.modbus/src/main/java/org/openhab/core/io/transport/modbus/ModbusBitUtilities.java, bundles/org.openhab.core.io.transport.modbus/src/test/java/org/openhab/core/io/transport/modbus/test/IntegrationTestSupport.java, bundles/org.openhab.core.io.transport.modbus/src/test/java/org/openhab/core/io/transport/modbus/test/SmokeTest.java, bundles/org.openhab.core.io.transport.mqtt/src/main/java/org/openhab/core/io/transport/mqtt/reconnect/PeriodicReconnectStrategy.java, bundles/org.openhab.core/src/main/java/org/openhab/core/internal/i18n/I18nProviderImpl.java, bundles/org.openhab.core/src/main/java/org/openhab/core/library/items/NumberItem.java, bundles/org.openhab.core/src/main/java/org/openhab/core/net/NetUtil.java, bundles/org.openhab.core/src/test/java/org/openhab/core/internal/i18n/TestUnitProvider.java
Java assertions are disabled by default so in this PR they are replaced/removed where applicable.
=> Replace or remove assert statements

bundles/org.openhab.core.automation/src/test/java/org/openhab/core/automation/util/ReferenceResolverUtilTest.java, bundles/org.openhab.core.io.transport.mqtt/src/test/java/org/openhab/core/io/transport/mqtt/MqttBrokerConnectionTests.java, bundles/org.openhab.core.model.script/src.moved/test/java/org/openhab/core/model/script/lib/NumberExtensionsTest.java, bundles/org.openhab.core.semantics/src/test/java/org/openhab/core/semantics/internal/SemanticsMetadataProviderTest.java, bundles/org.openhab.core.storage.json/src/test/java/org/openhab/core/storage/json/internal/JsonStorageTest.java, bundles/org.openhab.core.ui/src/test/java/org/openhab/core/ui/internal/proxy/ProxyServletServiceTest.java, bundles/org.openhab.core/src/test/java/org/openhab/core/cache/lru/LRUMediaCacheTest.java, bundles/org.openhab.core/src/test/java/org/openhab/core/common/QueueingThreadPoolExecutorTest.java, bundles/org.openhab.core/src/test/java/org/openhab/core/internal/auth/UserRegistryImplTest.java, bundles/org.openhab.core/src/test/java/org/openhab/core/library/items/CallItemTest.java, bundles/org.openhab.core/src/test/java/org/openhab/core/library/items/DimmerItemTest.java, bundles/org.openhab.core/src/test/java/org/openhab/core/library/items/LocationItemTest.java, bundles/org.openhab.core/src/test/java/org/openhab/core/library/types/PointTypeTest.java, bundles/org.openhab.core/src/test/java/org/openhab/core/library/types/QuantityTypeTest.java, bundles/org.openhab.core/src/test/java/org/openhab/core/library/types/StringListTypeTest.java, itests/org.openhab.core.tests/src/main/java/org/openhab/core/items/ManagedItemProviderOSGiTest.java, itests/org.openhab.core.thing.tests/src/main/java/org/openhab/core/thing/internal/ChannelCommandDescriptionProviderOSGiTest.java, itests/org.openhab.core.thing.tests/src/main/java/org/openhab/core/thing/internal/ChannelStateDescriptionProviderOSGiTest.java
The first parameter should be the expected value and the second parameter the actual value.
=> Fix assertEquals order

bundles/org.openhab.core.addon.marketplace/src/main/java/org/openhab/core/addon/marketplace/internal/automation/MarketplaceRuleTemplateProvider.java, bundles/org.openhab.core.auth.jaas/src/main/java/org/openhab/core/auth/jaas/internal/ManagedUserLoginConfiguration.java, bundles/org.openhab.core.io.transport.modbus/src/main/java/org/openhab/core/io/transport/modbus/internal/ModbusLibraryWrapper.java, bundles/org.openhab.core.io.transport.modbus/src/main/java/org/openhab/core/io/transport/modbus/internal/ModbusManagerImpl.java, bundles/org.openhab.core.io.transport.modbus/src/test/java/org/openhab/core/io/transport/modbus/test/SmokeTest.java, bundles/org.openhab.core.karaf/src/main/java/org/openhab/core/karaf/internal/jaas/ManagedUserBackingEngine.java, bundles/org.openhab.core.model.sitemap/src/org/openhab/core/model/sitemap/valueconverter/SitemapConverters.java, bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/internal/profiles/SystemProfileFactory.java, bundles/org.openhab.core.ui/src/main/java/org/openhab/core/ui/components/RootUIComponent.java, bundles/org.openhab.core.ui/src/main/java/org/openhab/core/ui/components/UIComponent.java, bundles/org.openhab.core.voice/src/main/java/org/openhab/core/voice/internal/cache/TTSLRUCacheImpl.java, bundles/org.openhab.core/src/main/java/org/openhab/core/internal/common/SafeCallerImpl.java, bundles/org.openhab.core/src/main/java/org/openhab/core/internal/service/StateDescriptionServiceImpl.java, bundles/org.openhab.core/src/main/java/org/openhab/core/library/unit/ImperialUnits.java, bundles/org.openhab.core/src/main/java/org/openhab/core/library/unit/Units.java, bundles/org.openhab.core/src/test/java/org/openhab/core/cache/lru/LRUMediaCacheEntryTest.java, bundles/org.openhab.core/src/test/java/org/openhab/core/cache/lru/LRUMediaCacheTest.java, bundles/org.openhab.core/src/test/java/org/openhab/core/library/types/QuantityTypeTest.java, itests/org.openhab.core.thing.tests/src/main/java/org/openhab/core/thing/factory/ManagedThingProviderOSGiTest.java
Often the type can be inferred so the diamond operator can be used to simplify the code.
=> Use diamond operator

bundles/org.openhab.core.io.transport.serial.javacomm/src/main/java/org/openhab/core/io/transport/serial/internal/SerialPortImpl.java, bundles/org.openhab.core.io.transport.serial.rxtx/src/main/java/org/openhab/core/io/transport/serial/rxtx/RxTxSerialPort.java
An infinite recursion would occur when calling this method. I did not find any add-ons using this method but that could be due to this bug.
=> Fix `SerialPort.getFlowControlMode()` infinite recursion

bundles/org.openhab.core.automation/src/test/java/org/openhab/core/automation/thingsupport/AnnotatedThingActionModuleTypeProviderTest.java, bundles/org.openhab.core.automation/src/test/java/org/openhab/core/automation/util/ReferenceResolverUtilTest.java, bundles/org.openhab.core.test/src/test/java/org/openhab/core/test/java/JavaTestTest.java, bundles/org.openhab.core/src/test/java/org/openhab/core/auth/client/oauth2/AccessTokenResponseTest.java, bundles/org.openhab.core/src/test/java/org/openhab/core/cache/lru/LRUMediaCacheTest.java, bundles/org.openhab.core/src/test/java/org/openhab/core/internal/items/ExpireManagerTest.java, bundles/org.openhab.core/src/test/java/org/openhab/core/internal/items/ItemStateConverterImplTest.java, bundles/org.openhab.core/src/test/java/org/openhab/core/library/types/HSBTypeTest.java, bundles/org.openhab.core/src/test/java/org/openhab/core/library/types/PointTypeTest.java, bundles/org.openhab.core/src/test/java/org/openhab/core/library/types/QuantityTypeTest.java, bundles/org.openhab.core/src/test/java/org/openhab/core/util/StringUtilsTest.java, itests/org.openhab.core.config.discovery.tests/src/main/java/org/openhab/core/config/discovery/internal/InboxOSGiTest.java, itests/org.openhab.core.io.rest.core.tests/src/main/java/org/openhab/core/io/rest/core/internal/discovery/InboxResourceOSGITest.java, itests/org.openhab.core.tests/src/main/java/org/openhab/core/items/ItemRegistryImplTest.java, itests/org.openhab.core.thing.tests/src/main/java/org/openhab/core/thing/ThingChannelsTest.java, itests/org.openhab.core.thing.tests/src/main/java/org/openhab/core/thing/internal/ThingRegistryOSGiTest.java
Using the appropriate assertion methods results in less and easier to read code as well as better error messages when assertions fail.
=> Simplify assertions

bundles/org.openhab.core.config.discovery.usbserial.linuxsysfs/src/main/java/org/openhab/core/config/discovery/usbserial/linuxsysfs/internal/SysfsUsbSerialScanner.java, bundles/org.openhab.core.io.bin2json/src/main/java/org/openhab/core/io/bin2json/Bin2Json.java, bundles/org.openhab.core.io.transport.modbus/src/main/java/org/openhab/core/io/transport/modbus/json/WriteRequestJsonUtilities.java, bundles/org.openhab.core/src/test/java/org/openhab/core/library/types/PercentTypeTest.java
These argument mismatches cause wrong messages being logged and thrown in exceptions.
=> Fix `String.format` argument mismatches

bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/RuleEngineImpl.java, bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/composite/CompositeModuleHandlerFactory.java, bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/provider/HostFragmentMappingUtil.java, bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/provider/RuleResourceBundleImporter.java, bundles/org.openhab.core.config.core/src/main/java/org/openhab/core/config/core/internal/validation/ConfigDescriptionValidatorImpl.java, bundles/org.openhab.core.io.transport.upnp/src/main/java/org/openhab/core/io/transport/upnp/internal/UpnpIOServiceImpl.java, bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/binding/ThingFactory.java, bundles/org.openhab.core.ui/src/main/java/org/openhab/core/ui/internal/proxy/ProxyServletService.java, bundles/org.openhab.core.voice/src/main/java/org/openhab/core/voice/internal/VoiceManagerImpl.java, itests/org.openhab.core.config.discovery.tests/src/main/java/org/openhab/core/config/discovery/internal/InboxOSGiTest.java
Iteration using Map entries is preferred because it is more efficient and helps preventing NPEs.
=> Iterate using Map entries

bundles/org.openhab.core.automation.module.script.rulesupport/src/main/java/org/openhab/core/automation/module/script/rulesupport/shared/ScriptedAutomationManager.java, bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/RulePredicates.java, bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/commands/Printer.java, bundles/org.openhab.core.config.core/src/main/java/org/openhab/core/config/core/ConfigDescriptionRegistry.java, bundles/org.openhab.core.config.core/src/main/java/org/openhab/core/config/core/internal/metadata/MetadataConfigDescriptionProviderImpl.java, bundles/org.openhab.core.io.console.eclipse/src/main/java/org/openhab/core/io/console/eclipse/internal/ConsoleSupportEclipse.java, bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/internal/channel/ChannelTypeResource.java, bundles/org.openhab.core/src/main/java/org/openhab/core/cache/ExpiringCacheMap.java, bundles/org.openhab.core/src/main/java/org/openhab/core/internal/i18n/ResourceBundleTracker.java
This optimizes and simplifies the code that adds elements to Collections.
=> Simplify adding elements to Collections

features/karaf/openhab-core/src/main/feature/feature.xml
Karaf does not automatically install the feature after `dependency="true"` was added in #3814.
=> Fix openhab-core-auth-oauth2client feature installation

bundles/org.openhab.core.config.discovery.addon.ip/src/main/java/org/openhab/core/config/discovery/addon/ip/IpAddonFinder.java
Query AddonService to check if an addon is already installed. In case, skip scanning for the addon.
Fixes #3967
=> IpAddonFinder: Skip installed addons

bundles/org.openhab.core/src/main/java/org/openhab/core/internal/library/unit/CurrencyConverter.java, bundles/org.openhab.core/src/main/java/org/openhab/core/internal/library/unit/CurrencyService.java, bundles/org.openhab.core/src/main/java/org/openhab/core/library/unit/CurrencyUnit.java, bundles/org.openhab.core/src/test/java/org/openhab/core/library/unit/CurrencyUnitTest.java
This fixes some issues that were recently detected regarding the new currency units:
- Currency codes could not be used for the base currency (but for additional currencies) when a symbol is defined. The reason is that in this case only the symbol and not symbol and label were added to the unit formatter.
- Units composed of a currency and an additional currency (like `EUR/kWh`) were not properly converted (only the non-currency part was converted). This was caused by two problems: `CurrencyUnit` did not inherit from `AbstractUnit` and therefore the converter was not properly found (always `IDENTITY`). After I fixed that, an additional problem occurred: the `CurrencyConverter` could not be used because the list of converters is a final, non-accessible list.
@jlaur FYI.
=> Fix CurrencyUnit

bundles/org.openhab.core.config.discovery/src/main/java/org/openhab/core/config/discovery/AbstractDiscoveryService.java, bundles/org.openhab.core.config.discovery/src/main/java/org/openhab/core/config/discovery/internal/DiscoveryResultImpl.java, bundles/org.openhab.core.config.discovery/src/main/java/org/openhab/core/config/discovery/internal/PersistentInbox.java, bundles/org.openhab.core.config.discovery/src/main/java/org/openhab/core/config/discovery/internal/console/InboxConsoleCommandExtension.java, itests/org.openhab.core.config.discovery.tests/src/main/java/org/openhab/core/config/discovery/internal/InboxOSGiTest.java
This refactors some [java.util.Date](https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/util/Date.html) usages to the more modern [time API](https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/time/package-summary.html).
The API is preserved as epoch milliseconds, so this is a non-breaking change.
There is two user-facing changes, though.
1. This console command has changed formatting:
```shell
openhab> openhab:inbox list
NEW [mydevice]: My Device [thingId=my:device:0, bridgeId=null, properties={ipAddress=192.168.0.1}, representationProperty=null, timestamp=2024-01-07T15:33:15.500Z, timeToLive=UNLIMITED]
```
Previously this would be displayed like this:
```shell
openhab> openhab:inbox list
NEW [mydevice]: My Device [thingId=my:device:0, bridgeId=null, …
```
=> [discovery] Refactor `java.util.Date` usages to `java.time.Instant`

bundles/org.openhab.core.io.rest/src/main/java/org/openhab/core/io/rest/LocaleServiceImpl.java
The logging will be less confusing when the correct class name is logged.
=> Fix wrong class name logged in LocaleServiceImpl

bundles/org.openhab.core/src/test/java/org/openhab/core/common/ThreadPoolManagerTest.java
When the CPU load of a system is high these timeouts may not be realistic.
Fixes #3254
=> Improve ThreadPoolManagerTest stability

bundles/org.openhab.core.addon.marketplace/src/main/java/org/openhab/core/addon/marketplace/AbstractRemoteAddonService.java
It has been reported several times that add-ons were not properly installed / missing after an upgrade or the installation of incompatible add-ons resulted in broken installations.
After an upgrade (or clean cache) the `AddonHandler`s try to re-install the add-ons from the download cache (`<userdata>/marketplace`). This happens without checking compatibility. This was needed before OH4, because the cache was the only source providing information about installed add-ons. This is now different, since we store the add-on information in a JSON database, so the UIDs of the add-ons are known.
This PR changes improves the add-on services. It now
1. Reads the information about the installed add-ons from the database and sets the installation status based on information from the handlers.
2. …
=> Improve marketplace add-on handling

bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/internal/ChannelCommandDescriptionProvider.java
The class of the broken provider should be logged, not the class of the command description.
Found while investigating https://github.com/openhab/openhab-addons/issues/14747
=> Fix logging in ChannelCommandDescriptionProvider

bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/RuleExecutionSimulator.java, bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/commands/AutomationCommandsPluggable.java, bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/ruleengine/WrappedModule.java, bundles/org.openhab.core.config.core/src/main/java/org/openhab/core/config/core/Configuration.java, bundles/org.openhab.core.persistence/src/test/java/org/openhab/core/persistence/internal/PersistenceManagerTest.java, bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/internal/type/AbstractChannelTypeBuilder.java, bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/profiles/ProfileTypeBuilder.java, bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/type/ChannelTypeBuilder.java, bundles/org.openhab.core/src/main/java/org/openhab/core/common/NamedThreadFactory.java, bundles/org.openhab.core/src/main/java/org/openhab/core/common/QueueingThreadPoolExecutor.java, bundles/org.openhab.core/src/main/java/org/openhab/core/common/SafeCaller.java, bundles/org.openhab.core/src/main/java/org/openhab/core/common/SafeCallerBuilder.java, bundles/org.openhab.core/src/main/java/org/openhab/core/common/registry/AbstractRegistry.java, bundles/org.openhab.core/src/main/java/org/openhab/core/internal/common/SafeCallerBuilderImpl.java, bundles/org.openhab.core/src/main/java/org/openhab/core/internal/common/SafeCallerImpl.java, bundles/org.openhab.core/src/main/java/org/openhab/core/internal/items/MetadataCommandDescriptionProvider.java, bundles/org.openhab.core/src/main/java/org/openhab/core/items/GenericItem.java, bundles/org.openhab.core/src/main/java/org/openhab/core/items/GroupItem.java, bundles/org.openhab.core/src/main/java/org/openhab/core/library/unit/CurrencyUnit.java, bundles/org.openhab.core/src/test/java/org/openhab/core/internal/i18n/I18nProviderImplTest.java, bundles/org.openhab.core/src/test/java/org/openhab/core/internal/items/ItemStateConverterImplTest.java, bundles/org.openhab.core/src/test/java/org/openhab/core/items/GenericItemTest.java, bundles/org.openhab.core/src/test/java/org/openhab/core/library/dimension/DataAmountTest.java, bundles/org.openhab.core/src/test/java/org/openhab/core/library/types/DateTimeTypeTest.java, bundles/org.openhab.core/src/test/java/org/openhab/core/library/types/PercentTypeTest.java
* Add missing null annotations
* Add missing null checks
* Remove use of deprecated SecurityManager
* Remove redundant null checks
* Remove unused variables
* Fix raw use of parameterized class
=> Fix several compiler warnings

bundles/org.openhab.core.audio/src/main/java/org/openhab/core/audio/AudioManager.java, bundles/org.openhab.core.io.console.karaf/src/main/java/org/openhab/core/io/console/karaf/internal/CommandWrapper.java, bundles/org.openhab.core.io.transport.mqtt/src/test/java/org/openhab/core/io/transport/mqtt/MqttBrokerConnectionEx.java, bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/Bridge.java, bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/ChannelUID.java, bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/Thing.java, bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/internal/BridgeImpl.java, bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/internal/ThingImpl.java, bundles/org.openhab.core.thing/src/test/java/org/openhab/core/thing/ChannelUIDTest.java, bundles/org.openhab.core/src/main/java/org/openhab/core/cache/ExpiringCacheAsync.java, bundles/org.openhab.core/src/main/java/org/openhab/core/util/ColorUtil.java
The proper way to format code with JavaDoc is using code tags and not Markdown backticks.
=> Replace Markdown backticks with JavaDoc code tags

bundles/org.openhab.core.addon.marketplace/src/main/java/org/openhab/core/addon/marketplace/internal/community/CommunityUIWidgetAddonHandler.java
Installing from marketplace gives an Error that is not very helpful.
Couldn’t find the widget in the add-on entry
The cause was missing ```yaml code fence when a normal code fence was used. This used to work in the past so a number of widgets are done this way and will not install. Suggest a more useful message to help guide widget devs.
=> [marketplace] Update CommunityUIWidgetAddonHandler.java to give a more helpful error

bundles/org.openhab.core.io.console/pom.xml, bundles/org.openhab.core.io.console/src/main/java/org/openhab/core/io/console/internal/extension/AddonConsoleCommandExtension.java
=> Add console commands to manage add-ons

bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/internal/item/MetadataSelectorMatcher.java, bundles/org.openhab.core/src/main/java/org/openhab/core/common/AbstractUID.java
Avoid to compile the SEGMENT_PATTERN for each validated segment of a UID.
=> Use precompiled regular expressions to validate the segments of a UID

bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/internal/AutoUpdateManager.java, bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/internal/CommunicationManager.java, bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/internal/ThingConfigDescriptionAliasProvider.java, bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/internal/ThingHandlerCallbackImpl.java, bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/internal/ThingRegistryImpl.java, bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/internal/link/ItemChannelLinkConfigDescriptionProvider.java, bundles/org.openhab.core.thing/src/test/java/org/openhab/core/thing/internal/AutoUpdateManagerTest.java
There is no need to recreate the ChannelUID to read the Channel from a Thing when it is already there.
This will avoid the instance creation and validation of the UID segments of the channel.
=> Use the ChannelUID to retrieve the Channel from a Thing

bundles/org.openhab.core.model.item/src/org/openhab/core/model/item/internal/GenericItemProvider.java, itests/org.openhab.core.model.item.tests/src/main/java/org/openhab/core/model/item/internal/GenericItemProviderTest.java
Fix openhab/openhab-webui#2251
=> Remove state description when loading an item with a removed pattern

bundles/org.openhab.core.config.discovery/src/main/java/org/openhab/core/config/discovery/AbstractDiscoveryService.java, bundles/org.openhab.core.config.discovery/src/main/java/org/openhab/core/config/discovery/DiscoveryResult.java, bundles/org.openhab.core.config.discovery/src/main/java/org/openhab/core/config/discovery/inbox/Inbox.java, bundles/org.openhab.core.config.discovery/src/main/java/org/openhab/core/config/discovery/inbox/InboxAutoApprovePredicate.java, bundles/org.openhab.core.config.discovery/src/main/java/org/openhab/core/config/discovery/inbox/InboxPredicates.java, bundles/org.openhab.core.config.discovery/src/main/java/org/openhab/core/config/discovery/inbox/events/AbstractInboxEvent.java, bundles/org.openhab.core.config.discovery/src/main/java/org/openhab/core/config/discovery/internal/DiscoveryResultImpl.java, bundles/org.openhab.core.config.discovery/src/main/java/org/openhab/core/config/discovery/internal/DiscoveryServiceRegistryImpl.java, bundles/org.openhab.core.config.discovery/src/main/java/org/openhab/core/config/discovery/internal/PersistentInbox.java, bundles/org.openhab.core.config.discovery/src/test/java/org/openhab/core/config/discovery/internal/DiscoveryResultImplTest.java, bundles/org.openhab.core.config.discovery/src/test/java/org/openhab/core/config/discovery/internal/PersistentInboxTest.java
This fixes all warnings in [org.openhab.core.config.discovery](https://github.com/openhab/openhab-core/tree/main/bundles/org.openhab.core.config.discovery/src/main/java/org/openhab/core/config/discovery):
- [Remove unused imports and reference explicit namespaces in Javadoc links](https://github.com/openhab/openhab-core/commit/8be7a7bd04fdc1e0abbb9a3b6b108391b39a24cd)
- [Fix potential null pointer access](https://github.com/openhab/openhab-core/commit/7fd95c464b711572d35f0cf86fe0cb78b970b724)
- [Remove redundant null checks and dead code](https://github.com/openhab/openhab-core/commit/d0c176b036f56b16e2437026d119d41ec03425da)
- [Suppress deprecation warnings in tests](https://github.com/openhab/openhab-core/commit/c9c0b9ccaa6217d320ebd3328ce5caa8f6bf2f2a) (related to #1428)
One SAT …
=> [discovery] Fix warnings

bundles/org.openhab.core.config.discovery.addon.process/src/main/java/org/openhab/core/config/discovery/addon/process/ProcessAddonFinder.java
See https://github.com/openhab/openhab-core/pull/3904#issuecomment-1904702212
=> AddonFinderProcess fixes

bundles/org.openhab.core.io.transport.serial/src/main/java/org/openhab/core/io/transport/serial/SerialPortEvent.java
Several USB sticks are integrated via Serial Transport's SerialPort and related implementations.
Since these USB sticks can be removed causing the port to be not available anymore, it's useful to track this event by bindings that are interested to handle it, for example to change state of the corresponding Thing to OFFLINE.
A [HARDWARE_ERROR event has been introduced](https://github.com/NeuronRobotics/nrjavaserial/blob/5d6d4e6a8ee4d6706e3c7b19467aabccde58f765/src/main/java/gnu/io/SerialPortEvent.java#L83C2-L83C49) in NRJavaSerial 5.x but has not been added yet to OH Serial Transport.
This PR adds a PORT_DISCONNECTED event to the SerialPortEvent interface.
Fixes #4055
=> [transport.serial] add PORT_DISCONNECTED event

bundles/org.openhab.core.model.thing/src/org/openhab/core/model/thing/internal/GenericItemChannelLinkProvider.java
Apply channel config changes in .items file
Changes in channel config weren't applied because ItemChannelLink.equals() include the link configurations in the comparison. This caused the new link not being found in the set lookup, which leads to erroneously calling notifyListenersAboutAddedElement, when it should've called notifyListenersAboutUpdatedElement instead.
The problem that this PR fixes:
Changing channel config in an .items file, e.g. only the `function` is being changed from:
```
String Test { channel="foo" [ profile="transform:REGEX", function="moo" ] }
```
to:
```
String Test { channel="foo" [ profile="transform:REGEX", function="cow" ] }
```
This wouldn't take effect unless a more severe measure was taken, e.g. commenting out the item and re-adding it, or in many cases, users …
=> Fix reloading channel config changes in .items file

bundles/org.openhab.core/src/main/java/org/openhab/core/internal/i18n/I18nProviderImpl.java, bundles/org.openhab.core/src/main/java/org/openhab/core/library/dimension/EmissionIntensity.java, bundles/org.openhab.core/src/main/java/org/openhab/core/library/unit/Units.java, bundles/org.openhab.core/src/test/java/org/openhab/core/library/unit/UnitsTest.java
This adds a dimension that can be used to express emission rate of a given pollutant relative to the intensity of a specific activity, for example CO2 emissions in g/kWh (mass/energy). See https://en.wikipedia.org/wiki/Emission_intensity.
This is a preparation to support UoM for new datasets in the Energi Data Service binding:
=> [UoM] Add dimension for emission intensity

bundles/org.openhab.core.automation.module.script.rulesupport/src/main/java/org/openhab/core/automation/module/script/rulesupport/internal/RuleSupportScriptExtension.java, bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/RuleRegistryImpl.java, bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/provider/file/AbstractFileProvider.java, bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/provider/file/WatchServiceUtil.java, bundles/org.openhab.core.config.core/src/main/java/org/openhab/core/config/core/xml/AbstractXmlBasedProvider.java, bundles/org.openhab.core.model.thing/src/org/openhab/core/model/thing/internal/GenericItemChannelLinkProvider.java, bundles/org.openhab.core.test/src/main/java/org/openhab/core/test/java/JavaOSGiTest.java, bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/link/AbstractLinkRegistry.java, bundles/org.openhab.core/src/main/java/org/openhab/core/internal/common/SafeCallManagerImpl.java
If the specified key is not already associated with a value (or is mapped to null), the given mapping function computes the value.
=> Simplify Map operations using `computeIfAbsent`

bundles/org.openhab.core.automation.module.script/src/main/java/org/openhab/core/automation/module/script/profile/ScriptProfile.java, bundles/org.openhab.core.automation.module.script/src/main/resources/OH-INF/config/script-profile.xml, bundles/org.openhab.core.automation.module.script/src/main/resources/OH-INF/i18n/scriptprofile.properties, bundles/org.openhab.core.automation.module.script/src/test/java/org/openhab/core/automation/module/script/profile/ScriptProfileTest.java
This allows much more fine-grained control for the script profile. 
E.g. it is now possible to mimic the behaviour of the `system:follow` profile, but apply a script transformation to the forwarded state. I discovered the need for this when trying to make a KNX channel follow an Item state, but at the same time needed to transform the Item state before sending it to KNX.
=> Script profile: Separate toHandlerScript for commands and states

bundles/org.openhab.core/src/main/java/org/openhab/core/internal/service/ReadyServiceImpl.java
Fixes #4060 
Use a real concurrent collection instead of a `synchronizedSet`.
=> Fix CME in ReadyService

bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/item/EnrichedItemDTOMapper.java, bundles/org.openhab.core.io.rest.core/src/test/java/org/openhab/core/io/rest/core/item/EnrichedItemDTOMapperTest.java, bundles/org.openhab.core.semantics/src/main/java/org/openhab/core/semantics/internal/SemanticsMetadataProvider.java, bundles/org.openhab.core.semantics/src/test/java/org/openhab/core/semantics/internal/SemanticsMetadataProviderTest.java
Allow a group to be a member of its direct parent and also its parent's ancestors without raising an error.
So this scenario is now allowed:
```
Group G1
Group G2 (G1)
Group G3 (G1, G2)
```
Looping membership is still detected and prevented as before, thus Stack Overflow is still avoided.
So this scenario is still not allowed, as it was originally intended:
```
Group R1 (R2)
Group R2 (R1)
```
and also not allowed:
```
Group R1 (R3)
Group R2 (R1)
Group R3 (R2)
```
Hopefully the new error message is also easier to understand, although it will only be issued when a real membership loop occurred.
See https://community.openhab.org/t/recursive-group-membership-found/135192
https://github.com/openhab/openhab-core/pull/3748
=> Fix the recursive group membership check

bundles/org.openhab.core.io.rest.sitemap/src/main/java/org/openhab/core/io/rest/sitemap/internal/SitemapResource.java, bundles/org.openhab.core.io.rest.sitemap/src/main/java/org/openhab/core/io/rest/sitemap/internal/WidgetDTO.java, bundles/org.openhab.core.model.sitemap/src/org/openhab/core/model/sitemap/Sitemap.xtext, bundles/org.openhab.core.ui/src/main/java/org/openhab/core/ui/internal/components/UIComponentSitemapProvider.java, bundles/org.openhab.core.ui/src/main/java/org/openhab/core/ui/internal/items/ItemUIRegistryImpl.java, bundles/org.openhab.core.ui/src/test/java/org/openhab/core/ui/internal/items/ItemUIRegistryImplTest.java
=> [sitemap] Add releaseOnly parameter to Slider sitemap element

bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/internal/persistence/PersistenceResource.java, bundles/org.openhab.core.io.rest.core/src/test/java/org/openhab/core/io/rest/core/internal/persistence/PersistenceResourceTest.java, bundles/org.openhab.core.persistence/src/main/java/org/openhab/core/persistence/PersistenceManager.java, bundles/org.openhab.core.persistence/src/main/java/org/openhab/core/persistence/internal/PersistenceManagerImpl.java, bundles/org.openhab.core.persistence/src/main/java/org/openhab/core/persistence/registry/PersistenceServiceConfigurationRegistry.java, bundles/org.openhab.core.persistence/src/test/java/org/openhab/core/persistence/internal/PersistenceManagerTest.java
Fixes #4087 
Data added from the REST API is immediately stored in the selected persistence service, bypassing the `PersistenceManager`. Because of that the future values are not correctly "restored".
=> [persistence] Fix forecast for externally changed data

bundles/org.openhab.core.config.discovery.addon.ip/src/main/java/org/openhab/core/config/discovery/addon/ip/IpAddonFinder.java
Add **new replacement $uuid** in request frame.
This is needed for discovery of ipcamera devices.
Add **new parameter listenPort** (required for govee).
Add **new parameter requestPlain** as alternative to request (enhance readability of request for text/xml/json based req., govee and ipcamera)
Improve resource handling:
* autocloseable
* ~~restrict to 5 addresses~~ (moved to next PR)
* ~~respect system.config.network.useOnlyOneAddress setting~~ (moved to next PR)
Refs: #3936
=> Minor extension to generic ip discovery

bom/compile/pom.xml, bom/openhab-core/pom.xml, bom/runtime/pom.xml, bundles/org.openhab.core.config.jupnp/.classpath, bundles/org.openhab.core.config.jupnp/.project, bundles/org.openhab.core.config.jupnp/NOTICE, bundles/org.openhab.core.config.jupnp/pom.xml, bundles/org.openhab.core.config.jupnp/src/main/java/org/openhab/core/config/jupnp/internal/OHUpnpServiceConfiguration.java, bundles/pom.xml, features/karaf/openhab-tp/src/main/feature/feature.xml
* Upgrades jUPnP from 2.7.1 to 3.0.0.
* Uses a custom OSGiUpnpServiceConfiguration for JDK-8301341 workaround
https://github.com/jupnp/jupnp/releases/tag/3.0.0
=> Upgrade jUPnP to 3.0.0

bom/test/pom.xml
Background: `hamcrest-library` and `hamcrest-core` are obsolete because they were combined into `hamcrest`.
Both deprecated JARs contain the following text file:
```
All the classes in hamcrest-core.jar and hamcrest-library.jar has moved
into hamcrest.jar. Please update your dependencies.
```
Resolves #4112
=> Replace deprecated `hamcrest-library` with `hamcrest` in test BOM

bundles/org.openhab.core.audio/src/main/java/org/openhab/core/audio/utils/AudioSinkUtilsImpl.java, bundles/org.openhab.core.audio/src/main/java/org/openhab/core/audio/utils/AudioWaveUtils.java
Fix two errors for calculating bitrate and duration of sound.
In AudioSinkUtilsImpl : confusion between byte / bit
In AudioWaveUtils : confusion between byte / bit AND with the definition of framesize (framesize already includes number of channels)
=> Audio parsing : Fix byte / bit confusion

bundles/org.openhab.core.io.rest.sse/src/main/java/org/openhab/core/io/rest/sse/internal/SseItemStatesEventBuilder.java, bundles/org.openhab.core.io.rest.sse/src/main/java/org/openhab/core/io/rest/sse/internal/dto/StateDTO.java
This would avoid having to use parseFloat for item state by making the numericState readily available.
=> Add numericState and unit to StateDTO

bundles/org.openhab.core.io.net/src/main/java/org/openhab/core/io/net/http/internal/WebClientFactoryImpl.java
Hello, I would like to merge these small workaround that allows to access the underling Jetty EndPoint when using an http client created using the WebClientFactory.
It mimics the way the EndPoint is exposed in recent Jetty versions so it will become useless in case of an update.
I need it in order to proxy the socket data for upgraded WebSocket connections through the OpenHAB Cloud Connector.
=> [net] Expose Jetty EndPoint in http requests

tools/upgradetool/pom.xml, tools/upgradetool/src/main/java/org/openhab/core/tools/UpgradeTool.java, tools/upgradetool/src/main/java/org/openhab/core/tools/internal/Upgrader.java
Refs #4058.
/cc @jimtng @J-N-K
=> Upgrade tool: Add upgrade task for script profile changes

bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/internal/item/ItemResource.java, itests/org.openhab.core.io.rest.core.tests/src/main/java/org/openhab/core/io/rest/core/internal/item/ItemResourceOSGiTest.java
This sets the `editable` field of the `EnrichedItemDTO` for `members` of the `EnrichedGroupItemDTO`.
The `editable` field is needed by the UI, e.g. for https://github.com/openhab/openhab-webui/pull/2410.
=> [rest] Set editable for members of an item

bundles/org.openhab.core/src/main/java/org/openhab/core/items/GenericItem.java, bundles/org.openhab.core/src/main/java/org/openhab/core/library/items/CallItem.java, bundles/org.openhab.core/src/main/java/org/openhab/core/library/items/ContactItem.java, bundles/org.openhab.core/src/main/java/org/openhab/core/library/items/ImageItem.java
If a state description is set on a contact item, currently a command description is automatically created as well.
This is wrong as contact items do not accept commands (except refresh) and caused the UI to display a control for the default (list) widget for these contacts.
=> Call, Contact, Image items: Don't create command descr from state descr

bundles/org.openhab.core.io.rest.core/src/test/java/org/openhab/core/io/rest/core/internal/config/ConfigDescriptionResourceTest.java, bundles/org.openhab.core.io.rest/src/main/java/org/openhab/core/io/rest/JSONResponse.java, bundles/org.openhab.core.io.rest/src/test/java/org/openhab/core/io/rest/JSONResponseTest.java, itests/org.openhab.core.io.rest.core.tests/src/main/java/org/openhab/core/io/rest/core/internal/item/ItemResourceOSGiTest.java, itests/org.openhab.core.io.rest.core.tests/src/main/java/org/openhab/core/io/rest/core/internal/link/ItemChannelLinkResourceOSGiTest.java
This PR does use the JAX-RS way of streaming data without starting a new short living thread.
=> [rest] stream json without starting a new thread

bundles/org.openhab.core.io.http.auth/pages/authorize.html
Fixes https://github.com/openhab/openhab-webui/issues/2443.
See https://developer.mozilla.org/en-US/docs/Web/HTML/Quirks_Mode_and_Standards_Mode.
=> [auth] Set doctype for auth page

bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/item/EnrichedItemDTOMapper.java
The item REST response does include a field `unitSymbol` for Number items, but not for Group items with Number base type. While the info can be retrieved by querying the metadata, it is easier in the UI to be able to use the same field.
This PR adds unitSymbol for Group items with base type Number in the REST response.
Required to avoid workaround for groups in https://github.com/openhab/openhab-webui/pull/2312
=> unitSymbol in REST response for GroupItem

bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/internal/item/ItemResource.java
This allows the usage of filters when using `staticDataOnly=true`.
=> [rest] Enable filters for cacheable items list

bundles/org.openhab.core.io.rest/src/main/java/org/openhab/core/io/rest/Stream2JSONInputStream.java
This PR will use the `SequenceInputStream` to simplify the logic for the `Stream2JSONInputStream`.
All interface methods can now be delegated to the `SequenceInputStream`, this makes it easy to support methods like:
- `public int read(byte @Nullable [] b, int off, int len) throws IOException`
- `public long transferTo(OutputStream target) throws IOException`
=> [rest] refactored the Stream2JSONInputStream to simplify the logic

bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/internal/GsonMessageBodyWriter.java
Should fix #4144, by handling the StreamingOutput inside the GsonMessageBodyWriter.
=> [rest] special handling for StreamingOutput

bundles/org.openhab.core.automation.module.script/src/main/java/org/openhab/core/automation/module/script/internal/handler/AbstractScriptModuleHandler.java, bundles/org.openhab.core.automation.module.script/src/main/java/org/openhab/core/automation/module/script/internal/handler/ScriptActionHandler.java, bundles/org.openhab.core.automation.module.script/src/main/java/org/openhab/core/automation/module/script/internal/handler/ScriptConditionHandler.java
Required to fix https://github.com/openhab/openhab-webui/issues/2461.
Currently when adding a new script action or script condition to a rule in the UI, the first thing the user sees is a red error message, because the script is not defined yet.
As this is confusing and might worry especially new users, this issue should be fixed.
My proposal is to add support for empty script to script action and script condition and update the UI to create the script field as empty when creating a new script action or condition.
Script action and condition both short-evaluate to a value they don't affect the rule's execution when the script is empty.
=> [automation] Allow empty script for script action & script condition

bundles/org.openhab.core.auth.oauth2client/src/main/java/org/openhab/core/auth/oauth2client/internal/OAuthConnector.java
In this method, exceptions are thrown, caught and wrapped into `OAuthException`. In some cases, this results in `OAuthException` being wrapped into another `OAuthException`. However, in other cases, `OAuthResponseException` is wrapped into `OAuthException`, effectively preventing the intended [OAuthResponseException](https://www.openhab.org/javadoc/latest/org/openhab/core/auth/client/oauth2/oauthresponseexception) from being thrown  from the method (since 4.0).
See https://github.com/openhab/openhab-addons/issues/16518#issuecomment-1998324602
Regression of #3271
=> [oauth] Fix exception wrapping

bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/internal/persistence/PersistenceResource.java
The persistence REST response, when no persistence configuration is available, is a 404 at the moment.
This PR changes that and will serve a persistence configuration matching the default persistence strategy for the persistence service if one is available.
This allows the UI to show this default strategy if none is configured and the user to change this default in the UI.
=> REST response default persistence strategy when no persistence configuration

bundles/org.openhab.core.automation.rest/src/main/java/org/openhab/core/automation/rest/internal/RuleResource.java, bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/internal/addons/AddonResource.java, bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/internal/item/ItemResource.java, bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/internal/tag/TagResource.java, bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/internal/thing/ThingResource.java, bundles/org.openhab.core.io.rest.ui/src/main/java/org/openhab/core/io/rest/ui/internal/UIResource.java, bundles/org.openhab.core.io.rest/src/main/java/org/openhab/core/io/rest/RESTConstants.java, bundles/org.openhab.core.io.rest/src/main/java/org/openhab/core/io/rest/internal/resources/SystemInfoResource.java
As there are no registry listeners to use, I decided to listen to `AddonEvent`s.
/cc @jimtng
=> [rest] Add caching for add-on resource

bundles/org.openhab.core.io.rest.auth/src/main/java/org/openhab/core/io/rest/auth/internal/TokenResource.java
Fixes #4159.
See https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie#samesitesamesite-value.
Because our current implementation of `javax.ws.rs.core.NewCookie` (which is `jakarta.ws.rs/jakarta.ws.rs-api/2.1.6` provided by `org.apache.aries.spec/org.apache.aries.javax.jax.rs-api/1.0.4`) does not allow to set the SameSite attribute, we have to workaround that limitation by setting the cookie directly through a response header. 
Once our implementation is `jakarta.ws.rs/jakarta.ws.rs-api/3.1.0` or newer, we can use `NewCookie` again.
Implementing the required changes to NewCookie on our own does not work, because the servlet also needs adustment.
=> [rest] TokenResource: Set SameSite attribute for session id cookie

bundles/org.openhab.core.automation.module.script/src/main/java/org/openhab/core/automation/module/script/internal/ScriptEngineManagerImpl.java
Core part of the fix for https://github.com/openhab/openhab-addons/issues/16462.
=> [automation] Avoid memory leak on script loading failure

bundles/org.openhab.core/src/main/java/org/openhab/core/internal/scheduler/CronSchedulerImpl.java, bundles/pom.xml, pom.xml
openhab-core can now be compiled an run both on Java 17 and Java 21.
- Upgrade SAT to 0.16.0
- Add profiles j17 and j21, automatically activated based on JDK version unless specified.
- Pin Java version for xtend to 17. As xtend does not yet support Java 21, compile model with Java 17.
- Includes #4125.
Refs: openhab/openhab-distro#1590
=> Support Java 21

bom/compile/pom.xml, bom/runtime/pom.xml, bundles/org.openhab.core.config.jupnp/pom.xml, bundles/org.openhab.core.config.jupnp/src/main/java/org/openhab/core/config/jupnp/internal/OHUpnpServiceConfiguration.java, features/karaf/openhab-tp/src/main/feature/feature.xml
This requires first the release of JUPnP 3.0.1 including the following fix:
https://github.com/jupnp/jupnp/pull/227#issuecomment-2029533316
Fix #4140 
=> Move to JUPnP v3.0.1

bundles/org.openhab.core.io.rest.auth/src/main/java/org/openhab/core/io/rest/auth/internal/ExpiringUserSecurityContextCache.java
Rename internal class.
Old implementation was breaking the Java 21 build when output was set to Java 17 class files.
Compiler got confused by similar class names ```Entry``` from local class and Map.
Refs:
https://github.com/openhab/openhab-distro/issues/1590
https://github.com/openhab/openhab-distro/pull/1640
=> [rest] Fix Java 21 build

bundles/org.openhab.core/src/main/java/org/openhab/core/util/StringUtils.java, bundles/org.openhab.core/src/test/java/org/openhab/core/util/StringUtilsTest.java
While trying to remove the apache libs from the addons i found one more string method that should be moved to this core utility. 
It is used in the Max binding, i'll update the related PR accordingly: https://github.com/openhab/openhab-addons/pull/14413
=> [util] Add abbreviate method

bundles/org.openhab.core.io.rest/src/main/java/org/openhab/core/io/rest/RESTConstants.java, bundles/org.openhab.core.model.sitemap/src/org/openhab/core/model/sitemap/Sitemap.xtext, bundles/org.openhab.core.ui/src/main/java/org/openhab/core/ui/internal/chart/ChartServlet.java, bundles/org.openhab.core.ui/src/test/java/org/openhab/core/ui/internal/chart/ChartServletPeriodParamTest.java
Closes openhab/openhab-webui#2518
=> [sitemap] Extend chart periods to cover past and future

bundles/org.openhab.core.addon.marketplace/src/main/java/org/openhab/core/addon/marketplace/AbstractRemoteAddonService.java
Fixes #4180 
I really wonder why this is showing up now, since the bug was there since quite some time. "Show incompatible" can be configured in the add-on management section and should default to "false", instead it was "true".
Should be backported to 4.1.x
=> Fix marketplace showing incompatible add-ons by default

bundles/org.openhab.core/src/main/java/org/openhab/core/library/types/DecimalType.java, bundles/org.openhab.core/src/main/java/org/openhab/core/library/types/QuantityType.java
Hey, i just wanted to add small optimization to not create a new `BigDecimal` if given object is already this class
=> Do not create new `BigDecimals` if a given object is already `BigDecimal`

bom/compile/pom.xml, bom/runtime/pom.xml, bundles/org.openhab.core.ephemeris/src/main/java/org/openhab/core/ephemeris/internal/EphemerisManagerImpl.java, features/karaf/openhab-tp/src/main/feature/feature.xml, itests/org.openhab.core.automation.integration.tests/itest.bndrun, itests/org.openhab.core.automation.module.core.tests/itest.bndrun, itests/org.openhab.core.automation.module.script.tests/itest.bndrun, itests/org.openhab.core.automation.module.timer.tests/itest.bndrun, itests/org.openhab.core.automation.tests/itest.bndrun, itests/org.openhab.core.config.discovery.usbserial.linuxsysfs.tests/itest.bndrun, itests/org.openhab.core.ephemeris.tests/itest.bndrun, itests/org.openhab.core.model.item.tests/itest.bndrun, itests/org.openhab.core.model.rule.tests/itest.bndrun, itests/org.openhab.core.model.script.tests/itest.bndrun, itests/org.openhab.core.model.thing.tests/itest.bndrun
Upgrades Jollyday from 0.23.2 to 0.27.0.
https://github.com/focus-shift/jollyday/releases
=> Upgrade Jollyday to 0.27.0

bundles/org.openhab.core.automation.module.script/src/main/java/org/openhab/core/automation/module/script/internal/handler/ScriptConditionHandler.java
=> [automation] Improve logging in ScriptConditionHandler

bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/internal/persistence/PersistenceResource.java, bundles/org.openhab.core.persistence/src/main/java/org/openhab/core/persistence/dto/ItemHistoryDTO.java, bundles/org.openhab.core/src/main/java/org/openhab/core/library/types/QuantityType.java
This PR will improve throughput and memory consumption while building the ItemHistoryDTO by:
- removing not needed auto-boxing of a field
- apply the diagonal lines workaround only when needed
- ensure the internal cache of `BigDecimal.toString` is hit and the `BigDecimal` is not rebuilded (relevant since PR #16379 reuses the State)
=> [persistence] improve building the ItemHistoryDTO

bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/RuleRegistryImpl.java, bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/module/handler/AnnotationActionHandler.java, bundles/org.openhab.core.config.core/src/main/java/org/openhab/core/config/core/internal/normalization/BooleanNormalizer.java, bundles/org.openhab.core.config.core/src/main/java/org/openhab/core/config/core/internal/normalization/DecimalNormalizer.java, bundles/org.openhab.core.config.core/src/main/java/org/openhab/core/config/core/internal/normalization/IntNormalizer.java, bundles/org.openhab.core.io.net/src/main/java/org/openhab/core/io/net/http/internal/WebClientFactoryImpl.java, bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/internal/item/ItemResource.java, bundles/org.openhab.core.model.item/src/org/openhab/core/model/item/internal/GenericItemProvider.java, bundles/org.openhab.core.model.script/src/org/openhab/core/model/script/lib/NumberExtensions.java, bundles/org.openhab.core.persistence/src/main/java/org/openhab/core/persistence/filter/PersistenceThresholdFilter.java, bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/internal/ChannelStateDescriptionProvider.java, bundles/org.openhab.core.ui/src/main/java/org/openhab/core/ui/internal/components/UIComponentSitemapProvider.java, bundles/org.openhab.core/src/main/java/org/openhab/core/internal/items/GroupFunctionHelper.java, bundles/org.openhab.core/src/main/java/org/openhab/core/internal/items/MetadataStateDescriptionFragmentProvider.java, bundles/org.openhab.core/src/main/java/org/openhab/core/net/HttpServiceUtil.java
=> More instanceof pattern matching

bundles/org.openhab.core.config.discovery.addon/src/main/java/org/openhab/core/config/discovery/addon/AddonFinderConstants.java, bundles/org.openhab.core.config.discovery.addon/src/main/java/org/openhab/core/config/discovery/addon/AddonSuggestionService.java, bundles/org.openhab.core.karaf/src/main/java/org/openhab/core/karaf/internal/FeatureInstaller.java, bundles/org.openhab.core.karaf/src/main/java/org/openhab/core/karaf/internal/KarafAddonFinderService.java
See https://github.com/openhab/openhab-core/issues/3983
This PR changes the installation/deinstallation of suggestion finders, not directly calling the FeatureService, but through FeatureInstaller. This should reduce the amount of bundle refreshes happening, but will not completely avoid it (the root cause is not with the finders, but the refersh on install/deinstall of any bundle).
At a minimum, it moves the installation/deinstallation into the same code as installing/deinstalling addons, so improvements in that code will also benefit the installation/deinstallation of the addon finders.
@J-N-K @lolodomo let me know if this change is worth doing, or the benefit is too limited.
=> Use FeatureInstaller for suggestion finder installation

bundles/org.openhab.core.audio/src/main/java/org/openhab/core/audio/utils/AudioWaveUtils.java
<s>I think bitrate was miscalculated after #4116 </s>
nBitsPerSecond = nSamplesPerChannelPerSecond * nBitsPerSample * nChannels;
PR seems to make no difference but seems a little clear to me. Feel free to close it if irrelevant.
=> [audio] Update bitrate calc

bundles/org.openhab.core.io.transport.modbus/src/main/java/org/openhab/core/io/transport/modbus/internal/ModbusManagerImpl.java
This exception is meant to indicate that the request should be retried shortly, essentially, and at least some of the devices I own seem to be busy bees. Thus my logs receive significant spam of this warning.
Since the exception is transient and retrying it is the expected course of action, I think it makes sense to reduce the log level here slightly and only output an error when the retries get exhausted.
=> [modbus] reduce log level when modbus slave returns DEVICE_BUSY exception

bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/TriggerHandlerCallbackImpl.java, bundles/org.openhab.core/src/main/java/org/openhab/core/common/PoolBasedSequentialScheduledExecutorService.java, bundles/org.openhab.core/src/main/java/org/openhab/core/common/ThreadPoolManager.java, bundles/org.openhab.core/src/main/java/org/openhab/core/internal/events/EventHandler.java, bundles/org.openhab.core/src/test/java/org/openhab/core/common/ThreadPoolManagerTest.java, tools/static-code-analysis/pmd/suppressions.properties
This is basically a reincarnation of the idea in #2182 with a different approach.
The `SequentialScheduledExecutorService` in this PR will act like a `Executors.newSingleThreadScheduledExecutor`, but it does use a thread pool to execute the tasks. The mechanism to block the `ScheduledExecutorService` to run tasks concurrently is based on a chain of `CompletableFutures`. Each instance has a reference to the last CompletableFuture and will call `handleAsync` to add a new task. This will ensure tasks are running sequentially. 
A `.schedule` call will register a callback which will then submit the task to perform now, ending in the same handleAsync call on the `CompletableFutures`, to ensure these are also running sequentially.
The only side effect a rule has, is to not run inside the same …
=> Use a thread pool backed sequential executor for DSL rules and events

bundles/org.openhab.core.persistence/src/main/java/org/openhab/core/persistence/extensions/PersistenceExtensions.java, bundles/org.openhab.core.persistence/src/test/java/org/openhab/core/persistence/extensions/PersistenceExtensionsTest.java, bundles/org.openhab.core.persistence/src/test/java/org/openhab/core/persistence/extensions/TestCachedValuesPersistenceService.java, bundles/org.openhab.core.persistence/src/test/java/org/openhab/core/persistence/extensions/TestPersistenceService.java
Closes https://github.com/openhab/openhab-core/issues/3732
Closes https://github.com/openhab/openhab-core/issues/3896
This PR implements unit support in all PersistenceExtension commands, returning the full value including unit for Number item types with a dimension. It therefore changes return types from DecimalType to a State type, whereby the state can include the unit.
This has been tested to work with rules DSL, and it should be possible to extend other scripting languages to support this, making calculations with historic states of items with dimensions more straightforward.
This may require adapting user rules and is therefore a breaking change.
Secondly, this PR makes sure persistence extensions work properly with persisted items in the future:
- all `Between` commands have been …
=> Return units in persistence extension commands and support future persisted states

bundles/org.openhab.core.config.discovery.addon/src/main/java/org/openhab/core/config/discovery/addon/AddonSuggestionService.java
https://github.com/openhab/openhab-core/pull/4188 caused finders not to be installed anymore by default.
This PR should fix the issue.
=> Fix initial suggestion finder installation

bundles/org.openhab.core/src/main/java/org/openhab/core/util/ColorUtil.java
javadoc is broken since ~10 days due to a wrong parameter name in a description of a function.
Maybe we should extend github actions to include javadoc...
=> Fix javadoc build

bundles/org.openhab.core.io.rest.sitemap/src/main/java/org/openhab/core/io/rest/sitemap/SitemapSubscriptionService.java
As suggested by @lolodomo, a small correction to the documentation after #3652 introduced an inconsistency
=> Complete sitemap subscriptions documentation correction

bundles/org.openhab.core.persistence/src/main/java/org/openhab/core/persistence/extensions/PersistenceExtensions.java
See https://github.com/openhab/openhab-core/pull/3736#issuecomment-2092837280
=> Persistence extension, re-add deprecated evolutionRate method variants

bundles/org.openhab.core.config.discovery.addon/src/main/java/org/openhab/core/config/discovery/addon/AddonSuggestionService.java
It looks like https://github.com/openhab/openhab-core/pull/4206 didn't fix the issue completely.
Here is a complement, that so far works well for me. The issue was in the variable sequence of starting the AddonSuggestionService and KarafAddonFinderService.
@jlaur Can you have a look if this works for you as well?
@J-N-K Sorry for these iterations. Hopefully, it works out well this time.
=> Fix suggestion finder installation

bundles/org.openhab.core.model.script/src.moved/test/java/org/openhab/core/model/script/lib/NumberExtensionsTest.java, bundles/org.openhab.core.model.script/src/org/openhab/core/model/script/lib/NumberExtensions.java, bundles/org.openhab.core/src/main/java/org/openhab/core/library/types/DecimalType.java, bundles/org.openhab.core/src/main/java/org/openhab/core/library/types/PercentType.java
This PR will speed up calculations in rules by handling translation of common number types to `BigDecimal`.
These common number types should match most cases when calculations are done in rules.
=> Reuse existing BigDecimals in rules while converting types

bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/internal/CommunicationManager.java
This PR does replace the hash as key for the cache lookup with a `record` and removes the `ExpiringCacheMap`.
1. The lookup inside the cache could return wrong results when identical hashs are computed. This might be unlikely but possible and should be avoided. 
**Note:** Using `Objects.hash` does create an array for the varargs, so there should be no performance penalty when creating a new `record` instead.
2. The `ExpiringCacheMap` does not actively remove entries, it will only prevent entries older than the timeout to be read. There is no need to rebuild the cache after some time, i guess the idea was not to leak memory here. But this is not the case, therefore the regular `ConcurrentHashMap` can be used.
**Note:** This was the only use of `ExpiringCacheMap` i could see, so this class …
=> Prevent potential incorrect cache lookup due to hash collisions

bundles/org.openhab.core.io.rest.sitemap/src/main/java/org/openhab/core/io/rest/sitemap/internal/MappingDTO.java, bundles/org.openhab.core.io.rest.sitemap/src/main/java/org/openhab/core/io/rest/sitemap/internal/SitemapResource.java, bundles/org.openhab.core.model.sitemap/src/org/openhab/core/model/sitemap/Sitemap.xtext, bundles/org.openhab.core.ui/src/main/java/org/openhab/core/ui/internal/components/UIComponentSitemapProvider.java
Mappings attribute for switch element now accepts one or two commands for each button. If only one command is provided, the button is a click button, the command is sent to the item when the button is clicked. If two commands are provided (separated by ":"), the button is a press & release button, the first command is sent to the item when the button is pressed and the second when the button is released.
Syntax example for a click button: Switch item=DemoSwitch mappings=[ ON="ON" ]
Syntax example for a press & release button: Switch item=DemoSwitch mappings=[ ON:OFF="ON" ]
Related to #3822
=> Extend sitemap syntax for switch to support press & release buttons

bundles/org.openhab.core.ui/src/main/java/org/openhab/core/ui/internal/components/UIComponentSitemapProvider.java
Depends on: https://github.com/openhab/openhab-core/pull/4183
This PR adds support for press and release buttons in the sitemap generator.
It will required further testing after merging Depends on: https://github.com/openhab/openhab-core/pull/4183
The sitemap generator in the UI so far was stripping quotes from arguments in mappings and conditions sent to core.
As more functionality is added to the sitemap syntax, this is leading to problems to correctly interpret the arguments containing complex syntax:
- more characters become not allowed (splitting on =, :, ...)
- blanks are not always treated properly
To get over this limit, quote stripping should be removed on the UI side, but that means it needs to be done in core when creating the widget from the UIComponent.
Related to: …
=> Support press and release buttons in sitemap generator

bundles/org.openhab.core.persistence/src/main/java/org/openhab/core/persistence/extensions/PersistenceExtensions.java
See https://github.com/openhab/openhab-core/pull/3736#issuecomment-2093140530
=> Persistence extensions: allow null serviceId

bundles/org.openhab.core.karaf/src/main/java/org/openhab/core/karaf/internal/FeatureInstaller.java, features/karaf/openhab-core/src/main/feature/feature.xml
Fixes #4222
@lolodomo @holgerfriedrich @jimtng Can you confirm this also fixes the issues on your systems? My Win11/Parallels now works fine.
=> Fix resolver errors during bundle add-on installation

bundles/org.openhab.core.audio/src/main/java/org/openhab/core/audio/AudioFormat.java, bundles/org.openhab.core.audio/src/main/java/org/openhab/core/audio/AudioManager.java, bundles/org.openhab.core.audio/src/main/java/org/openhab/core/audio/internal/AudioConsoleCommandExtension.java, bundles/org.openhab.core.audio/src/main/java/org/openhab/core/audio/internal/AudioManagerImpl.java, bundles/org.openhab.core.voice/src/main/java/org/openhab/core/voice/VoiceManager.java, bundles/org.openhab.core.voice/src/main/java/org/openhab/core/voice/internal/VoiceConsoleCommandExtension.java, bundles/org.openhab.core.voice/src/main/java/org/openhab/core/voice/internal/VoiceManagerImpl.java
I would like add these new console commands to allow testing the audio sources and audio transcription capabilities.
Recently I was mentioned at https://community.openhab.org/t/problems-with-dialog-processing-with-pulseaudiobinding/155573 asking for help about these matters and it's difficult to give support about remote setups, so I though that having these commands can help users to troubleshot problems with the audio input and the transcription add-ons.
The new commands are:
Transcribe audio from default source, optionally specify a different source/file, speech-to-text service or locale.
```sh
voice transcribe [--source <source>]|[--file <file>] [<sttId>] [<locale>]
```
```sh
openhab> voice transcribe --file turn_on_light.wav
Transcription: turn on light.
```
Record a wav file of the …
=> [audio|voice] Add console commands to troubleshoot audio sources and speech-to-text services

bundles/org.openhab.core.config.discovery.addon.ip/src/main/java/org/openhab/core/config/discovery/addon/ip/IpAddonFinder.java
Extends #3920 to support broadcast-based scanning as well.
The broadcast implementation is based on the discovery implementation in the Danfoss Air Unit binding:
https://github.com/openhab/openhab-addons/blob/dd47b64fbb8865cd3b83ba782a79a7dc7286048f/bundles/org.openhab.binding.danfossairunit/src/main/java/org/openhab/binding/danfossairunit/internal/discovery/DanfossAirUnitDiscoveryService.java#L88-L151
=> Add IP broadcast add-on finder for suggestions

bundles/org.openhab.core.ui/src/main/java/org/openhab/core/ui/internal/items/ItemUIRegistryImpl.java
When the Switch widget has mappings or when the item has a state description with options, the Switch widget is rendered by UIs with buttons. There was no state conversion into OnOffType when the switch widget has mappings. But when the item has a state description with options, it was wrongly converted into OnOffType.
See this community discussion for an example:
https://community.openhab.org/t/item-statedescription-and-sitemaps/155935
=> [sitemap] Do not try to convert item state into OnOffType for Switch widget if item has options

bundles/org.openhab.core.io.rest.sitemap/src/main/java/org/openhab/core/io/rest/sitemap/internal/SitemapResource.java, bundles/org.openhab.core.io.rest.sitemap/src/main/java/org/openhab/core/io/rest/sitemap/internal/WidgetDTO.java, bundles/org.openhab.core.io.rest.sitemap/src/main/java/org/openhab/core/io/rest/sitemap/internal/WidgetsChangeListener.java, bundles/org.openhab.core.io.rest/src/main/java/org/openhab/core/io/rest/RESTConstants.java, bundles/org.openhab.core.model.sitemap/src/org/openhab/core/model/sitemap/Sitemap.xtext, bundles/org.openhab.core.model.sitemap/src/org/openhab/core/model/sitemap/validation/SitemapValidator.xtend, bundles/org.openhab.core.ui/src/main/java/org/openhab/core/ui/internal/components/UIComponentSitemapProvider.java
=> [sitemap] Buttongrid as container for new Button elements

bundles/org.openhab.core/src/main/java/org/openhab/core/library/types/QuantityType.java, bundles/org.openhab.core/src/test/java/org/openhab/core/library/types/QuantityTypeTest.java
Resolves https://github.com/openhab/openhab-core/issues/4166
Resolves https://github.com/openhab/openhab-core/issues/4163
This PR tries to resolve two issues with QuantityType:
1. Updating a Number:Dimensionless Item with a value of unit one, when the unit is set in metadata to another unit, will not update correctly. The proposed solution is to remove the special handling of unit one and make the unit part of the string again. It can be removed from visualisation using a state description.
2. Formatting a QuantityType<Time> tries to use the DateTime String formatting methods. When it fails it may output a UTC date. Durations will also not be correctly formatted when days/hours/minutes/seconds are above the month (31)/day (24)/hour (60)/minute (60) limits. In this PR, the formatting …
=> Fix QuantityType dimensionless one and time formatting

bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/DefaultSystemChannelTypeProvider.java, bundles/org.openhab.core.thing/src/main/resources/OH-INF/i18n/DefaultSystemChannels.properties, itests/org.openhab.core.thing.tests/src/main/java/org/openhab/core/thing/SystemWideChannelTypesTest.java
=> Adding UV Index system channel

bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/DefaultSystemChannelTypeProvider.java
There is a classic icon `SoundVolume_Mute` available:
https://www.openhab.org/docs/configuration/iconsets/classic/
Icon is here:
https://github.com/openhab/openhab-webui/blob/main/bundles/org.openhab.ui.iconset.classic/src/main/resources/icons/soundvolume_mute.svg
This is not used for channel type `system.mute` which currently uses the same icon as `system.volume`.
=> Change icon for channel type `system.mute`

.gitattributes
Closes #4246
This should help git clients and spotless on windows systems to select the correct line-endings for .xsd files.
=> Add .xsd to .gitattributes

bundles/org.openhab.core.model.sitemap/src/org/openhab/core/model/sitemap/Sitemap.xtext, bundles/org.openhab.core.model.sitemap/src/org/openhab/core/model/sitemap/validation/SitemapValidator.xtend
Problem introduced by #4223
checkFramesInWidgetList for LinkableWidget was triggering an error when the Buttongrid element has no parameter set.
=> Fix a wrongly failing validation rule for sitemap

bundles/org.openhab.core.config.discovery.usbserial.linuxsysfs/src/main/java/org/openhab/core/config/discovery/usbserial/linuxsysfs/internal/SysfsUsbSerialScanner.java
I was wondering why a fresh installed openhab instance without addons was creating ~ 1000 `int[]` instances every 15s.
This fallout is visible when monitoring the free memory of the instance:
This PR will add a fast path to avoid this fallout from matching a regex against dozens of not matching directories.
=> [serial] Use a fast path to avoid pattern matching

bundles/org.openhab.core/src/main/resources/OH-INF/config/addons.xml
The IP addon suggestion finder is on by default (like all other suggestion finders).
Because the default parameter was missing, it was wrongly shown in the UI.
=> Fix ip suggestion finder default parameter

bundles/org.openhab.core.config.discovery.sddp/src/main/java/org/openhab/core/config/discovery/sddp/SddpDiscoveryService.java, bundles/org.openhab.core.config.discovery.sddp/src/test/java/org/openhab/core/config/discovery/sddp/test/SddpDiscoveryServiceTests.java
The Atlona hdmi switch does not respond to SDDP SEARCH requests (although it periodically sends NOTIFY ALIVE packets). As an alternative it has a button in its web-ui that when pushed sends out a NOTIFY IDENTIFY packet that is the same the NOTIFY ALIVE packet, less the 'Max-Age' field. This PR changes SddpDiscoveryService to handle these packets as well.
reference (but not depended on by) https://github.com/openhab/openhab-addons/pull/16832
> NOTIFY IDENTIFY SDDP/1.0
From: "192.168.1.10:1902"
Host: "AT-UHD-PRO3-44M_B898B0030F4D"
Type: "AT-UHD-PRO3-44M"
Primary-Proxy: "avswitch"
Proxies: "avswitch"
Manufacturer: "Atlona"
Model: "AT-UHD-PRO3-44M"
Driver: "avswitch_Atlona_AT-UHD-PRO3-44M_IP.c4i"
Config-URL: "http://192.168.1.10/"
=> Add support for SDDP IDENTIFY packets

bundles/org.openhab.core.persistence/src/main/java/org/openhab/core/persistence/extensions/PersistenceExtensions.java
Evaluating https://github.com/openhab/openhab-js/issues/335, one bug was identified in the persistence extension when persisting with a date.
It is not sure it solves the whole issue, but it is a bug that should be fixed.
=> Fix persist with date method

bundles/org.openhab.core.persistence/src/main/java/org/openhab/core/persistence/extensions/PersistenceExtensions.java
This is a very useful addition for scripts & rules, e.g. for JS Scripting because in JS Scripting no native (Java) types are used (nearly everything is converted to JS tyes).
=> PersistenceExtensions: Support state as string for persist method

bundles/org.openhab.core.model.rule/src/org/openhab/core/model/rule/jvmmodel/RulesJvmModelInferrer.xtend
This was missed from #3536
This PR makes this possible:
```
rule "test"
when
Member of TestSwitches received command
Member of TestSwitches changed
then
logInfo("test", "TriggeringGroup: {}", triggeringGroup)
logInfo("test", "TriggeringGroupName: {}", triggeringGroupName)
end
```
=> RulesDSL: add triggeringGroup and triggeringGroupName to rule context

bundles/org.openhab.core.voice/src/main/java/org/openhab/core/voice/internal/DialogProcessor.java, bundles/org.openhab.core.voice/src/main/resources/OH-INF/i18n/voice.properties, bundles/org.openhab.core.voice/src/main/resources/OH-INF/i18n/voice_cs.properties, bundles/org.openhab.core.voice/src/main/resources/OH-INF/i18n/voice_de.properties, bundles/org.openhab.core.voice/src/main/resources/OH-INF/i18n/voice_el.properties, bundles/org.openhab.core.voice/src/main/resources/OH-INF/i18n/voice_fi.properties, bundles/org.openhab.core.voice/src/main/resources/OH-INF/i18n/voice_fr.properties, bundles/org.openhab.core.voice/src/main/resources/OH-INF/i18n/voice_he.properties, bundles/org.openhab.core.voice/src/main/resources/OH-INF/i18n/voice_hu.properties, bundles/org.openhab.core.voice/src/main/resources/OH-INF/i18n/voice_it.properties, bundles/org.openhab.core.voice/src/main/resources/OH-INF/i18n/voice_nl.properties, bundles/org.openhab.core.voice/src/main/resources/OH-INF/i18n/voice_no.properties, bundles/org.openhab.core.voice/src/main/resources/OH-INF/i18n/voice_pl.properties, bundles/org.openhab.core.voice/src/main/resources/OH-INF/i18n/voice_sl.properties, itests/org.openhab.core.voice.tests/src/main/java/org/openhab/core/voice/internal/VoiceManagerImplTest.java
<s>I would like to add this fix to the dialog processor, which avoid playing the content of the SpeechRecognitionErrorEvent unless it's explicitly indicated on it.
I think is more friendly to just fail and don't continue the dialog than to "speak" a text that can be a forwarded exception message, so I changed the log for the SpeechRecognitionErrorEvent and added the "notify" field on the SpeechRecognitionErrorEvent class which is false by default.</s>
I would like to add this fix to the dialog processor, which avoids the text concatenation on the content of the SpeechRecognitionErrorEvent and also allows to emit silent errors by passing an empty message.
=> [voice] Avoid text concatenation on speech recognition errors

bundles/org.openhab.core/src/main/java/org/openhab/core/util/StringUtils.java, bundles/org.openhab.core/src/test/java/org/openhab/core/util/StringUtilsTest.java
Earlier some string utils where added to core in order to remove the dependency on `org.apache.commons.lang3.StringUtils`.
While doing so i create a `padLeft`, but forgot a `padRight` method. This PR corrects that.
=> Extend Stringutils with padRight

bundles/org.openhab.core.persistence/src/main/java/org/openhab/core/persistence/extensions/PersistenceExtensions.java, bundles/org.openhab.core.persistence/src/test/java/org/openhab/core/persistence/extensions/PersistenceExtensionsTest.java, bundles/org.openhab.core.persistence/src/test/java/org/openhab/core/persistence/extensions/TestPersistenceService.java
Persistence extensions have lastUpdate and nextUpdate methods. However, when the same value is stored multiple times in the database (e.g. with a everyMinute persistence policy), it doesn't say anything about when the lastChange was.
This PR adds lastChange and nextChange methods.
To further extend on the situation:
Imagine the following persisted values at timestamps 1 to 4 (4 is most recent):
1. 10
2. 10
3. 20
4. 20
Currently existing persistence methods will return following timestamps:
- `previousState.timestamp`: 4
- `previousState(skipEqual = true).timestamp`: 2
- `lastUpdate`: 4
This enhancement adds a `lastChange` method which will return timestamp 3, somethings required if one wants to know when an item last changed. All existing methods also suffer from the impact of a …
=> Persistence extensions, add lastChange and nextChange

bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/item/EnrichedItemDTOMapper.java, bundles/org.openhab.core.io.rest.sse/src/main/java/org/openhab/core/io/rest/sse/internal/SseItemStatesEventBuilder.java, bundles/org.openhab.core.io.rest.sse/src/test/java/org/openhab/core/io/rest/sse/internal/SseItemStatesEventBuilderTest.java, bundles/org.openhab.core.ui/src/main/java/org/openhab/core/ui/internal/items/ItemUIRegistryImpl.java, bundles/org.openhab.core.ui/src/test/java/org/openhab/core/ui/internal/items/ItemUIRegistryImplTest.java
Use item state formatter to format input of transformation, meaning using state.format(format) instead of String.format(format, state.toString())
This was already the case in sitemap API but not in other APIs used by Main UI.
Make sure to call transformation even for NULL and UNDEF states.
It was not the case in one API used by Main UI.
When calling transformation and state is NULL or UNDEF, do not apply format to the input value and do not replace by "-".
That means the transformation will be called with "NULL" or "UNDEF".
Sitemap API was calling the transformation using a pattern containing "-".
Fix #4101 
Also related to discussion in openhab/openhab-addons#13777
=> Make input formatting for transformations consistent everywhere

bundles/org.openhab.core.config.discovery.sddp/src/main/java/org/openhab/core/config/discovery/sddp/SddpDevice.java, bundles/org.openhab.core.config.discovery.sddp/src/test/java/org/openhab/core/config/discovery/sddp/test/SddpDiscoveryServiceTests.java
Fix issue reported by: https://github.com/openhab/openhab-addons/issues/16964
If the SDDP host address field contains colons in the mac address, remove them.
@andrewfg @lolodomo
=> Fix parsing of mac address in SDDP Discovery

bundles/org.openhab.core/src/main/java/org/openhab/core/common/PoolBasedSequentialScheduledExecutorService.java, bundles/org.openhab.core/src/main/java/org/openhab/core/common/ThreadPoolManager.java, bundles/org.openhab.core/src/test/java/org/openhab/core/common/ThreadPoolManagerTest.java
This PR will ensure the `PoolBasedSequentialScheduledExecutorService` does keep the configured minimum size.
The unit test does now only need to spawn 10 new threads instead of up to 20, this should fix the latency issue.
@holgerfriedrich could you please run the CI multiple times for this PR to see if it does fix the issue?
=> Ensure the PoolBasedSequentialScheduledExecutorService does keep a minimum size

bundles/org.openhab.core.persistence/src/main/java/org/openhab/core/persistence/extensions/PersistenceExtensions.java, bundles/org.openhab.core.persistence/src/test/java/org/openhab/core/persistence/extensions/PersistenceExtensionsTest.java, bundles/org.openhab.core.persistence/src/test/java/org/openhab/core/persistence/extensions/TestPersistenceService.java
Closes https://github.com/openhab/openhab-core/issues/4254
Persistence extensions retrieving persisted data for GroupItems with a QuantityType as base type returned null or a value without the unit. This PR fixes that issue.
This was not an issue before https://github.com/openhab/openhab-core/pull/3736 as a DecimalType would be returned, ignoring the unit.
Second issue this resolves:
In the (rare) case a persistence service would have values stored with different units than the default (or configured) unit, the calculation would be off. This PR also corrects that. Most persistence services today assume the unit is the default (or configured) unit and don't store it explicitly. But it would be possible for some services.
=> Fix persistence extensions for group items and number dimension items with different units

bundles/org.openhab.core.model.yaml/src/main/java/org/openhab/core/model/yaml/internal/YamlModelRepositoryImpl.java
=> YAML files: ignore files inside automation sub-folder

bundles/org.openhab.core.persistence/src/main/java/org/openhab/core/persistence/extensions/PersistenceExtensions.java
This is a very quick attempt, tested manually, but without test coverage, sorry.
Logic is similar to this:
https://github.com/openhab/openhab-core/blob/b932a4df5e6d4f0706afee20b112b710683d16d7/bundles/org.openhab.core.persistence/src/main/java/org/openhab/core/persistence/internal/PersistenceManagerImpl.java#L318-L326
Fixes #4297
=> [PersistenceExtensions] Fix TimeSeries policy `REPLACE` not being applied

bundles/org.openhab.core.persistence/src/main/java/org/openhab/core/persistence/extensions/PersistenceExtensions.java
Fix regression from #4298
When a TimeSeries is empty, `getBegin()` and `getEnd()` return `Instant.MAX` and `Instant.MIN` which when converted to a ZonedDateTime causes a DateTimeException
=> PersistenceExtensions: fix DateTimeException when persisting an empty TimeSeries

bundles/org.openhab.core.addon/src/main/java/org/openhab/core/addon/AddonInfoRegistry.java
This fix allows having translated label for bindings when showing list of installed bindings in Main UI parameters.
Fix openhab/openhab-webui#2639
=> Fix merge of AddonInfo (masterAddonInfo field)

bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/binding/AbstractStorageBasedTypeProvider.java, bundles/org.openhab.core.thing/src/test/java/org/openhab/core/thing/binding/AbstractStorageBasedTypeProviderTest.java
#4079 added a unitHint property to ChannelTypes, but the AbstractStorageBasedTypeProvider wasn't updated to reflect the change. This adds this property so it can be persisted when adding ChannelTypes dynamically.
Fixes #4315
Signed-off-by: Anders Alfredsson <andersb86@gmail.com>
=> Add unitHint to AbstractStorageBasedTypeProvider.ChannelTypeEntity

bundles/org.openhab.core.automation.module.script/src/main/java/org/openhab/core/automation/module/script/internal/handler/AbstractScriptModuleHandler.java
Removes a left over from previous version of #4289.
Fixes https://github.com/openhab/openhab-core/pull/4289#issuecomment-2227353211.
=> [rules] Remove leftover from rfc in #4289

bundles/org.openhab.core.config.discovery/src/main/java/org/openhab/core/config/discovery/AbstractThingHandlerDiscoveryService.java
Apply the same logic in AbstractThingHandlerDiscoveryService as in AbstractDiscoveryService to determine if background discovery should be enabled or disabled.
Fix openhab/openhab-addons#17089
=> Fix startup of background discovery

bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/ChannelUID.java
I have missed this pattern in PR #4064, this PR will use a precompiled pattern in `ChannelUID.validateSegment` too.
=> Use a precompiled pattern in ChannelUID.validateSegment

bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/RuleEngineImpl.java
Fixes an issue, where an error that compilation failed for disabled rules.
Reported on the community: https://community.openhab.org/t/oh-4-2-snapshot-disabled-rules-failed-to-compile-error-in-opehab-log/157402.
Follow-up for #4289.
=> [rules] Don't attempt to pre-compile disabled rules

bundles/org.openhab.core.model.thing/src/org/openhab/core/model/thing/internal/GenericItemChannelLinkProvider.java
Fix an issue reported in https://community.openhab.org/t/openhab-4-2-updating-an-items-file-does-not-remove-links-to-channels/157331
=> Clean up removed links in GenericItemChannelLinkProvider

bundles/org.openhab.core.config.core/src/main/java/org/openhab/core/config/core/internal/i18n/ConfigDescriptionI18nUtil.java
Fix openhab/openhab-webui#2641
The i18n key for add-on configuration parameter should now start with `addon.config.<param>`.
To maintain compatibility with hundreds of existing translations, an alternative key starting with `<type>.config.<param>` is still accepted for an add-on parameter
=> Config parameter: Change inferred i18n key for add-ons + alternative key

bundles/org.openhab.core.ui.icon/src/main/java/org/openhab/core/ui/icon/internal/IconServlet.java
I have removed the Modified-Since handling as it did not have an effect due to the missing Cache-Control header, and instead added Cache-Control with a max-age set. 
This enables "forever" caching of icons, which should be fine since they are static assets - they now have the same caching policy as files in $OPENHAB_CONF/the html folder.
Should be a nice change especially on mobile, where I can often see that icons need some time to load with slow cellular network.
=> Icon servlet: Set Cache-Control header to enable icon caching

bundles/org.openhab.core.io.http.auth/pages/authorize.html
The icon files are provided by the UI bundle, see https://github.com/openhab/openhab-webui/tree/85cd64e147e9b2cca32e2dc60d8686c354591639/bundles/org.openhab.ui/web/src/res/icons.
=> Fix favicon for authorize/login page

bundles/org.openhab.core.model.item/src/org/openhab/core/model/Items.xtext, bundles/org.openhab.core.model.item/src/org/openhab/core/model/item/internal/GenericItemProvider.java, itests/org.openhab.core.model.item.tests/src/main/java/org/openhab/core/model/item/internal/GenericItemProviderTest.java
I'm looking into adding a feature to the HomeKit add-on that is best implemented with array/list properties. I'm able to create arrays just fine in MainUI with the code editor, but it's not currently possible with file based items.
https://github.com/openhab/openhab-addons/pull/17144 is the PR utilizing this feature.
=> Support lists for metadata properties in items files

bom/compile/pom.xml, bom/runtime/pom.xml, features/karaf/openhab-tp/src/main/feature/feature.xml, itests/org.openhab.core.automation.integration.tests/itest.bndrun, itests/org.openhab.core.automation.module.core.tests/itest.bndrun, itests/org.openhab.core.automation.module.script.tests/itest.bndrun, itests/org.openhab.core.automation.module.timer.tests/itest.bndrun, itests/org.openhab.core.automation.tests/itest.bndrun, itests/org.openhab.core.ephemeris.tests/itest.bndrun, itests/org.openhab.core.model.item.tests/itest.bndrun, itests/org.openhab.core.model.rule.tests/itest.bndrun, itests/org.openhab.core.model.script.tests/itest.bndrun, itests/org.openhab.core.model.thing.tests/itest.bndrun
Upgrades Jollyday from 0.28.1 to 0.30.0.
https://github.com/focus-shift/jollyday/releases/tag/v0.30.0
=> Upgrade Jollyday to 0.30.0

itests/itest-include.bndrun
When this JVM variable is not set Jetty creates selectors based on the number of available processors (`Runtime.getRuntime().availableProcessors()`). Jetty will also throw an exception when there is a mismatch between the max thread pool size and the number of selectors. This causes issues with the default thread pool size of 10 on machines with more than 10 available processors.
See also [`SelectorManager.defaultSelectors(Executor)`](https://github.com/jetty/jetty.project/blob/70015831e5195ba74da6383c4ab7c90c56bb08af/jetty-io/src/main/java/org/eclipse/jetty/io/SelectorManager.java#L71-L80).
=> Fix itests on machines with lots of processors

bundles/org.openhab.core.model.script/src/org/openhab/core/model/script/actions/Audio.java, bundles/org.openhab.core.test/src/main/java/org/openhab/core/test/java/JavaTest.java, bundles/org.openhab.core/src/main/java/org/openhab/core/cache/lru/InputStreamCacheWrapper.java, bundles/org.openhab.core/src/main/java/org/openhab/core/cache/lru/LRUMediaCacheEntry.java, bundles/org.openhab.core/src/test/java/org/openhab/core/JavaTest.java
Fix CodeQL warnings
* Implicit narrowing conversion in compound assignment
This PR only fixes the first 4 of the warnings.
There are more CodeQL warnings left, help is appreciated:
https://github.com/holgerfriedrich/openhab-core/security/code-scanning
=> Fix CodeQL warnings

bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/binding/generic/ChannelTransformation.java, bundles/org.openhab.core.thing/src/test/java/org/openhab/core/thing/binding/generic/ChannelTransformationTest.java
Support both `JSONPATH:$.xx` and `JSONPATH($.xx)` syntaxes.
The aim is to make transformation pattern uniform between bindings and core, e.g. in item / sitemap labels, so we can just use the parentheses everywhere. Perhaps colon syntax can be phased out eventually but for now they're both supported to maintain compatibility.
=> Support channel transformations with parentheses

bundles/org.openhab.core.automation.module.script/src/main/java/org/openhab/core/automation/module/script/ScriptTransformationService.java
for commandFromItemScript and stateFromItemScript
See https://github.com/openhab/openhab-core/pull/4058
This could perhaps be cherry picked to 4.2.x
=> Add missing ScriptProfile parameter options

bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/binding/generic/ChannelHandler.java, bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/internal/binding/generic/converter/AbstractTransformingChannelHandler.java, bundles/org.openhab.core.thing/src/test/java/org/openhab/core/thing/internal/binding/generic/converter/AbstractTransformingItemConverterTest.java
@J-N-K did this get missed when moving from the http binding to core?
=> Rename parameter of ChannelHandler

bundles/org.openhab.core/src/main/java/org/openhab/core/library/types/DateTimeType.java, bundles/org.openhab.core/src/test/java/org/openhab/core/library/types/DateTimeTypeTest.java
While working on the [State Profile PR](https://github.com/openhab/openhab-addons/pull/17323), I came across the issue that DateTimeType is not comparable. Making it comparable will enable inequality comparisons in the profile without having to resort to special handling for DateTimeType.
=> Make DateTimeType Comparable

bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/binding/generic/ChannelTransformation.java, bundles/org.openhab.core.thing/src/test/java/org/openhab/core/thing/binding/generic/ChannelTransformationTest.java
This is needed by the user of this class, e.g. mqtt binding, to know whether to convert the command to `StringType` when transformations were involved, or continue using the native type.
Example use cases
https://github.com/openhab/openhab-addons/blob/0d6feb72aa23dcfce946e1367ea0ce8b8c03b330/bundles/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/ChannelState.java#L136
https://github.com/openhab/openhab-addons/blob/0d6feb72aa23dcfce946e1367ea0ce8b8c03b330/bundles/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/ChannelState.java#L340
`isTransform()` is needed by the [modbus addon](https://github.com/openhab/openhab-addons/pull/17306)
=> Add isTransform(), isEmpty() and isPresent() to ChannelTransformation

bundles/org.openhab.core/src/main/java/org/openhab/core/library/types/DateTimeType.java, bundles/org.openhab.core/src/test/java/org/openhab/core/library/types/DateTimeTypeTest.java
Support `yyyy-MM-dd HH:mm`  syntax in addition to `yyyy-MM-ddTHH:mm`.
The syntax with space often appears in incoming data, e.g. mqtt. By supporting this, we won't need to run the input data through a transformation.
=> Support space-separated date/time format for DateTimeType

bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/binding/generic/ChannelTransformation.java, bundles/org.openhab.core.thing/src/test/java/org/openhab/core/thing/binding/generic/ChannelTransformationTest.java
This allows users to insert comments inbetween transformations in a multi-line / chained (or even a single transformation).
e.g.
```
REGEX(\d{2,})
```
=> Filter out blank lines and comments in a multi-line transformations

bundles/org.openhab.core.io.rest.sitemap/src/main/java/org/openhab/core/io/rest/sitemap/internal/SitemapResource.java, bundles/org.openhab.core.io.rest.sitemap/src/main/java/org/openhab/core/io/rest/sitemap/internal/WidgetDTO.java, bundles/org.openhab.core.model.sitemap/src/org/openhab/core/model/sitemap/Sitemap.xtext, bundles/org.openhab.core.ui/src/main/java/org/openhab/core/ui/internal/components/UIComponentSitemapProvider.java
=> [sitemap] Remove sendFrequency parameter for Slider/Colorpicker widgets

bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/internal/service/ConfigurableServiceResource.java
The i18n file containing this label is in org.openhab.core bundle.
Fix openhab/openhab-webui#1669
=> Fix translation of label for system:addons service

bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/module/handler/DateTimeTriggerHandler.java, bundles/org.openhab.core.automation/src/main/resources/OH-INF/automation/moduletypes/DateTimeTrigger.json, bundles/org.openhab.core.automation/src/main/resources/OH-INF/i18n/automation.properties, bundles/org.openhab.core.automation/src/test/java/org/openhab/core/automation/internal/module/handler/DateTimeTriggerHandlerTest.java
Resolve #4195
This should be merged before #4272 (Rules DSL support)
=> Support offset in DateTimeTrigger

bundles/org.openhab.core.persistence/src/main/java/org/openhab/core/persistence/internal/PersistenceServiceBundleTracker.java, bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/internal/ThingManagerImpl.java, bundles/org.openhab.core/src/main/java/org/openhab/core/service/AbstractServiceBundleTracker.java
While working on adding time series support to the Awattar binding I found that - depending on the installation order - things might get initialized before all persistence services are ready. It might happen that this leads to issues with persisting data (because a state or time series is sent before the persistence service is ready). 
I propose to add a persistence service bundle tracker (similar to what we have for script engine factories) and prevent early thing initialization. Adding the new `persistence=services` ready marker as a requirement to start level 30 and delaying thing initialization until that level is reached makes sure that persistence services are ready. 
Increasing the minimum start level for thing initialization also solves another issue reported on the forum: things …
=> Add a PersistenceService bundle tracker

bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/internal/BridgeImpl.java, bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/internal/ThingImpl.java
This is nice to have when working with Things in scripts.
I have chosen to not include the config because the config might include sensitive data like passwords.
=> [thing] Add toString overrides to ThingImpl & BridgeImpl

bundles/org.openhab.core.ui/src/main/java/org/openhab/core/ui/internal/components/UIComponentSitemapProvider.java
The syntax using nested Button components inside a Buttongrid component is currently not supported for configuration in the UI. This adds the necessary logic in core to make this possible.
@lolodomo
Related to https://github.com/openhab/openhab-core/pull/4223. This PR did not include the necessary part for UI sitemap configuration.
=> [sitemap] Buttongrid with Button components available for main UI configuration

bundles/org.openhab.core.config.discovery/src/main/java/org/openhab/core/config/discovery/AbstractDiscoveryService.java, bundles/org.openhab.core.config.discovery/src/main/java/org/openhab/core/config/discovery/AbstractThingHandlerDiscoveryService.java, bundles/org.openhab.core.config.discovery/src/main/java/org/openhab/core/config/discovery/DiscoveryService.java, bundles/org.openhab.core.config.discovery/src/main/java/org/openhab/core/config/discovery/DiscoveryServiceRegistry.java, bundles/org.openhab.core.config.discovery/src/main/java/org/openhab/core/config/discovery/internal/DiscoveryServiceRegistryImpl.java, bundles/org.openhab.core.config.discovery/src/main/java/org/openhab/core/config/discovery/internal/console/DiscoveryConsoleCommandExtension.java, bundles/org.openhab.core.config.discovery/src/test/java/org/openhab/core/config/discovery/AbstractDiscoveryServiceTest.java, bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/discovery/DiscoveryInfoDTO.java, bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/internal/discovery/DiscoveryResource.java, itests/org.openhab.core.config.discovery.tests/src/main/java/org/openhab/core/config/discovery/DiscoveryServiceRegistryOSGiTest.java
=> Add a new optional input parameter to discovery services

bundles/org.openhab.core.config.discovery/src/main/java/org/openhab/core/config/discovery/AbstractDiscoveryService.java
Fixes an issue from #4389.
For more details/explanation see https://github.com/openhab/openhab-core/pull/4389#discussion_r1781097842.
=> Fix discovery input parameter not enabled if label/description provided

bundles/org.openhab.core.automation.module.script/src/test/java/org/openhab/core/automation/module/script/profile/ScriptProfileTest.java
In Windows, successive invocations of Instant.now() may return the same instant, thus not creating new TimeSeries entries
Regression introduced in #4365
Resolve #4391
=> Ensure timeseries entries have unique timestamps

bom/compile/pom.xml, bom/runtime/pom.xml, features/karaf/openhab-tp/src/main/feature/feature.xml, itests/org.openhab.core.automation.integration.tests/itest.bndrun, itests/org.openhab.core.automation.module.core.tests/itest.bndrun, itests/org.openhab.core.automation.module.script.tests/itest.bndrun, itests/org.openhab.core.automation.module.timer.tests/itest.bndrun, itests/org.openhab.core.automation.tests/itest.bndrun, itests/org.openhab.core.ephemeris.tests/itest.bndrun, itests/org.openhab.core.model.item.tests/itest.bndrun, itests/org.openhab.core.model.rule.tests/itest.bndrun, itests/org.openhab.core.model.script.tests/itest.bndrun, itests/org.openhab.core.model.thing.tests/itest.bndrun
Upgrades Jollyday from 0.30.0 to 0.32.0.
* https://github.com/focus-shift/jollyday/releases/tag/v0.31.0
* https://github.com/focus-shift/jollyday/releases/tag/v0.32.0
=> Upgrade Jollyday to 0.32.0

bundles/org.openhab.core.automation.module.script/src/main/java/org/openhab/core/automation/module/script/internal/handler/AbstractScriptModuleHandler.java
If the ScriptEngine implements the Lock interface, the execution of the CompiledScript is synced by acquisition and release of the log.
This is required for add-ons like JS Scripting.
=> [automation] Add support for synchronized execution of compiled scripts

bundles/org.openhab.core.automation.module.script/src/main/java/org/openhab/core/automation/module/script/internal/ScriptEngineManagerImpl.java, bundles/org.openhab.core/src/main/java/org/openhab/core/net/NetUtil.java, bundles/org.openhab.core/src/test/java/org/openhab/core/net/NetUtilTest.java
Multiple bindings scan the network for devices by looping though all ip addresses. When trying to get rid of the apache libs, i also noticed the code is similar and it would be better to deduplicate this.
In future we can discuss if this scanning should be limited to the openHAB network setting or to all interfaces, but that is beyond the scope of this PR. Atleast we then have a central place to control that behaviour.
Reference: https://github.com/openhab/openhab-core/issues/3965
=> Extend NetUtils for network range scanning

bundles/org.openhab.core/src/main/java/org/openhab/core/util/ColorUtil.java, bundles/org.openhab.core/src/test/java/org/openhab/core/util/ColorUtilTest.java
This adds a new helper method to calculate the Duv (Delta u, v) of a color. The code is taken almost literally from the mqtt.espmilighthub binding, but changed slightly to fit in with other functions in ColorUtil. I intend to use this from espmilighthub, but also the HomeKit add-on. HomeKit doesn't allow linking both HSB _and_ Color Temperature characteristics to a single accessory, even though the iOS Home App will present a Color Temperature picker for any HSB light. So I want to allow linking devices that support both RGB+CCT to HomeKit, and if the Duv is within threshold, send a command to the Color Temperature channel instead.
I also think it might be useful to add a profile to apply to a Color channel link that does the same thing - if a color is close enough to "white", send a …
=> Add ColorUtil.xyToDuv

bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/internal/persistence/PersistenceResource.java, bundles/org.openhab.core.io.rest.core/src/test/java/org/openhab/core/io/rest/core/internal/persistence/PersistenceResourceTest.java, bundles/org.openhab.core.persistence/src/main/java/org/openhab/core/persistence/dto/ItemHistoryDTO.java
This adds a new query param `itemState` to the GET `/rest/persistence/items/{itemname}` endpoint.
This new parameter allows to add the current Item state to the data returned from persistence, which is a huge improvement for charts in the UI:
- "normal" charts range until the end of the requested time range
- "aggregate" charts such as a monthly chart are able to display the values of the current month even if the monthly value is only persisted at the end of the month
There are two special cases where the Item state is not added with the current time to the response:
- If the `boundary` query param is also set to true and a state was already added to the requested end time, there is no need to include the current Item state as there already is a state at the end of the time range.
- If …
=> [rest] Persistence: Optionally add current Item state to response

bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/internal/persistence/PersistenceResource.java, bundles/org.openhab.core.persistence/src/main/java/org/openhab/core/persistence/HistoricItem.java, bundles/org.openhab.core.persistence/src/main/java/org/openhab/core/persistence/internal/PersistenceManagerImpl.java, bundles/org.openhab.core.ui/src/main/java/org/openhab/core/ui/internal/chart/defaultchartprovider/DefaultChartProvider.java
This PR will add a new `default` method to the HistoricItem interface, to get the timestamp as `Instant`.
The most areas using the `HistoricItem` must transform the internal `Instant` to a `ZonedDateTime` (e.g. [all the persistence implementations](https://github.com/joerg1985/openhab-addons/commit/e400f7352cc8151db25304e33fce256c025b6e9f)) or need to transform the returned `ZonedDateTime` to an `Instant` (e.g. see the below).
So i my mind it does make sense to use a `Instant` here and not transform the data.
The link to the persistence implementations above does show the changes needed to the addons.
=> Extend HistoricItem to work with Instant instead of ZonedDateTime

bundles/org.openhab.core.addon.marketplace/src/main/java/org/openhab/core/addon/marketplace/AbstractRemoteAddonService.java, bundles/org.openhab.core.addon.marketplace/src/main/java/org/openhab/core/addon/marketplace/internal/community/CommunityMarketplaceAddonService.java
This improves the handling of remote add-ons. In some corner cases the list of remote add-ons was not properly refreshed after an add-on has been removed.
=> Improve marketplace remote handling

bundles/org.openhab.core/src/main/java/org/openhab/core/library/types/DecimalType.java
Instead of running expensive `BigInteger.toString()` and then parsing `BigDecimal` from it, run direclty constructor `BigDecimal(BigInteger)`
=> Parse BigInteger directly in DecimalType

bundles/org.openhab.core.io.transport.modbus/src/test/java/org/openhab/core/io/transport/modbus/test/SmokeTest.java, bundles/org.openhab.core.transform/src/main/java/org/openhab/core/transform/AbstractFileTransformationService.java, pom.xml
https://github.com/lastnpe/eclipse-null-eea-augments/releases/tag/v2.4.0
=> Upgrade lastnpe EEA to 2.4.0

bundles/org.openhab.core.automation.rest/src/main/java/org/openhab/core/automation/rest/internal/ThingActionsResource.java, bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/annotation/ActionOutput.java
This documents how to make the UI render an action output as QR code and fixes a wrong API response annotation in `ThingActionsResource`.
Refs https://github.com/openhab/openhab-webui/pull/2818 for the QR code rendering.
=> ActionOutput: Document QR code rendering & Fix action REST doc

bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/util/ActionInputsHelper.java, bundles/org.openhab.core.automation/src/test/java/org/openhab/core/automation/util/ActionInputHelperTest.java, bundles/org.openhab.core.config.core/src/main/java/org/openhab/core/config/core/ConfigDescriptionParameter.java
This changes the default format for the datetime context to the ISO standard. This context is not used by add-ons and supported by the UI, so it should be possible to change it (again after #4392.)
Also update the context docs from https://next.openhab.org/docs/developer/addons/config-xml.html#supported-contexts and the UI code.
=> ConfigDescriptionParameter: Change default format for datetime & Update context docs

bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/util/ActionInputsHelper.java, bundles/org.openhab.core.automation/src/test/java/org/openhab/core/automation/util/ActionInputHelperTest.java
- Set the step size of the config description parameter to 0 if the paramerer type is decimal, which enables the UI to allow entering any number of decimals (see https://github.com/openhab/openhab-webui/pull/2832).
- Apply the default value for primitive action inputs that have a default value (has been forgotten in #4392).
=> ActionInputsHelper: Allow any number of decimals & Apply primitive input default values

bundles/org.openhab.core.automation.module.script/src/main/java/org/openhab/core/automation/module/script/internal/handler/AbstractScriptModuleHandler.java, bundles/org.openhab.core.automation.module.script/src/main/java/org/openhab/core/automation/module/script/internal/handler/ScriptActionHandler.java, bundles/org.openhab.core.automation.module.script/src/main/java/org/openhab/core/automation/module/script/internal/handler/ScriptConditionHandler.java
If the `ScriptEngine` implements `Lock`, synchronize the execution of script action/condition.
In contrast to #4402, this now synchronizes the full script context access, which setup of execution context, script evaluation and reset of execution context, and not only the script evaluation.
It moves the locking mechanism added in #4402 from `AbstractScriptModuleHandler` to the inheritors of `AbstractScriptModuleHandler`.
This fixes the bug that https://github.com/openhab/openhab-addons/pull/17510 worked around by using `Thread.sleep`.
=> [automation] Fully synchronize script action/condition execution if supported by engine

bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/annotation/ActionOutput.java, bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/module/handler/AnnotationActionHandler.java, bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/module/provider/AnnotationActionModuleTypeHelper.java
See discussion in https://github.com/openhab/openhab-addons/issues/17504#issuecomment-2439906483.
This adds processing of the ActionOutput annotation for Thing actions with a single return value, which allows providing a label for use in the UI. The output name for those actions is "result", which is now the default value in the @ActionOutput annotation. If a binding overrides the default name, a warning is logged.
If a Thing action returns a Map<String, Object> but does not provide the @ActionOutputs annotation, a warning is logged.
=> Thing actions: Support `@ActionOutput` for single return values

bundles/org.openhab.core.io.rest.sitemap/src/main/java/org/openhab/core/io/rest/sitemap/internal/SitemapResource.java, bundles/org.openhab.core.model.sitemap/src/org/openhab/core/model/sitemap/Sitemap.xtext, bundles/org.openhab.core.model.sitemap/src/org/openhab/core/model/sitemap/validation/SitemapValidator.xtend, bundles/org.openhab.core.ui/src/main/java/org/openhab/core/ui/internal/components/UIComponentSitemapProvider.java, bundles/org.openhab.core.ui/src/main/java/org/openhab/core/ui/internal/items/ItemUIRegistryImpl.java
=> [sitemap] Add new element Colortemperaturepicker

bundles/org.openhab.core.io.rest.voice/src/main/java/org/openhab/core/io/rest/voice/internal/VoiceResource.java
Also add annotations for the response.
=> [rest] VoiceResource: Return answer from /interpreters endpoint

bundles/org.openhab.core/src/main/java/org/openhab/core/library/unit/Units.java, bundles/org.openhab.core/src/test/java/org/openhab/core/library/unit/UnitsTest.java
See discussion https://github.com/openhab/openhab-addons/issues/17638#issuecomment-2444023328
Signed-off-by: AndrewFG <software@whitebear.ch>
=> [Units] Add MK⁻¹ unit alias

bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/util/ActionInputsHelper.java, bundles/org.openhab.core.automation/src/test/java/org/openhab/core/automation/util/ActionInputHelperTest.java
By setting the step size to 1 for time and datetime, seconds are enabled in the UI.
Refs https://github.com/openhab/openhab-webui/pull/2848.
Discussion in https://github.com/openhab/openhab-webui/issues/2847#issuecomment-2446426478
=> [automation] ActionInputsHelper: Enable seconds for time & datetime

bundles/org.openhab.core.automation.rest/src/main/java/org/openhab/core/automation/rest/internal/ThingActionsResource.java, bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/module/provider/AnnotationActionModuleTypeHelper.java, bundles/org.openhab.core.automation/src/test/java/org/openhab/core/automation/internal/module/provider/AnnotationActionModuleTypeProviderTest.java, bundles/org.openhab.core.automation/src/test/java/org/openhab/core/automation/thingsupport/AnnotatedThingActionModuleTypeProviderTest.java
Supersedes #4438.
This appends a method signature hash to `@RuleAction` methods which have overloades to ensure module IDs are unique.
It also returns the visibility for Thing actions from the REST API.
=> [automation] Ensure unique module IDs for overloaded `@RuleAction` methods

bundles/org.openhab.core.automation.rest/src/main/java/org/openhab/core/automation/rest/internal/ThingActionsResource.java
=> [rest] Fix ThingActionsResource does not accept new Thing action UIDs with hash

bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/DefaultSystemChannelTypeProvider.java
Discussed in openhab/openhab-addons#17638.
=> Add unit hint to color-temperature-abs system channel type

bundles/org.openhab.core.ui/src/main/java/org/openhab/core/ui/internal/components/UIComponentSitemapProvider.java
Closes https://github.com/openhab/openhab-core/issues/4431
This closes an issue with color and icon rules when no item and comparator was provided in the rule (should default to item of the widget and == comparator) and the rule condition started with an alpha character.
=> Sitemap editor: Fix color and icon rules

bom/compile/pom.xml, bom/runtime/pom.xml, features/karaf/openhab-tp/src/main/feature/feature.xml, itests/org.openhab.core.automation.integration.tests/itest.bndrun, itests/org.openhab.core.automation.module.core.tests/itest.bndrun, itests/org.openhab.core.automation.module.script.tests/itest.bndrun, itests/org.openhab.core.automation.module.timer.tests/itest.bndrun, itests/org.openhab.core.automation.tests/itest.bndrun, itests/org.openhab.core.ephemeris.tests/itest.bndrun, itests/org.openhab.core.model.item.tests/itest.bndrun, itests/org.openhab.core.model.rule.tests/itest.bndrun, itests/org.openhab.core.model.script.tests/itest.bndrun, itests/org.openhab.core.model.thing.tests/itest.bndrun
Upgrades Jollyday from 0.32.0 to 0.35.1.
* https://github.com/focus-shift/jollyday/releases/tag/v0.33.0
* https://github.com/focus-shift/jollyday/releases/tag/v0.34.0
* https://github.com/focus-shift/jollyday/releases/tag/v0.35.0
* https://github.com/focus-shift/jollyday/releases/tag/v0.35.1
=> Upgrade Jollyday to 0.35.1

bundles/org.openhab.core.config.discovery.addon.ip/src/main/java/org/openhab/core/config/discovery/addon/ip/IpAddonFinder.java
Adds support for a `srcMac` substitution token which allows the scan packets to include the source mac address.
The mac address is formatted by the given `fmtMac` format specifier.
See https://github.com/openhab/openhab-addons/issues/17847
=> IP addon finder: add support for sending local mac address

bundles/org.openhab.core.model.persistence/src/org/openhab/core/model/persistence/Persistence.xtext, bundles/org.openhab.core.model.persistence/src/org/openhab/core/model/persistence/internal/PersistenceModelManager.java, bundles/org.openhab.core.persistence/src/main/java/org/openhab/core/persistence/config/PersistenceGroupExcludeConfig.java, bundles/org.openhab.core.persistence/src/main/java/org/openhab/core/persistence/config/PersistenceItemExcludeConfig.java, bundles/org.openhab.core.persistence/src/main/java/org/openhab/core/persistence/internal/PersistenceManagerImpl.java, bundles/org.openhab.core.persistence/src/main/java/org/openhab/core/persistence/registry/PersistenceServiceConfigurationDTOMapper.java
Closes https://github.com/openhab/openhab-core/issues/3665
This has been an often requested enhancement in the forum.
Allow syntax like in a persistence file:
```
Items {
*, !Item1, !Item2 : strategy = everyChange // every Item but Item1 and Item2
PersistGroup*, !DoNotPersistGroup* : strategy = everyMinute // items member of PersistGroup but not member of DoNotPersistGroup
}
```
The issue also proposes an alternative approach (`Vetoed`). I have not implemented this. It would also not be strategy/filter specific, so left that out for now and could be a future enhancement.
=> Persistence exclude items and groups

bundles/org.openhab.core.automation.rest/src/main/java/org/openhab/core/automation/rest/internal/RuleResource.java, bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/module/handler/DateTimeTriggerHandler.java, bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/module/handler/ItemStateConditionHandler.java, bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/internal/item/ItemResource.java, bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/internal/persistence/PersistenceResource.java, bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/item/EnrichedItemDTOMapper.java, bundles/org.openhab.core.io.rest.core/src/test/java/org/openhab/core/io/rest/core/item/EnrichedItemDTOMapperTest.java, bundles/org.openhab.core.io.rest.sitemap/src/main/java/org/openhab/core/io/rest/sitemap/SitemapSubscriptionService.java, bundles/org.openhab.core.io.rest.sitemap/src/main/java/org/openhab/core/io/rest/sitemap/internal/SitemapResource.java, bundles/org.openhab.core.io.rest.sitemap/src/main/java/org/openhab/core/io/rest/sitemap/internal/WidgetsChangeListener.java, bundles/org.openhab.core.io.rest.sitemap/src/test/java/org/openhab/core/io/rest/sitemap/internal/SitemapResourceTest.java, bundles/org.openhab.core.io.rest.sse/src/main/java/org/openhab/core/io/rest/sse/internal/SseItemStatesEventBuilder.java, bundles/org.openhab.core.io.rest.sse/src/test/java/org/openhab/core/io/rest/sse/internal/SseItemStatesEventBuilderTest.java, bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/internal/profiles/TimestampOffsetProfile.java, bundles/org.openhab.core.thing/src/main/resources/OH-INF/config/timestampOffsetProfile.xml, bundles/org.openhab.core.thing/src/main/resources/OH-INF/i18n/SystemProfiles.properties, bundles/org.openhab.core.thing/src/test/java/org/openhab/core/thing/internal/profiles/TimestampOffsetProfileTest.java, bundles/org.openhab.core.thing/src/test/java/org/openhab/core/thing/internal/profiles/TimestampProfileTest.java, bundles/org.openhab.core.thing/src/test/java/org/openhab/core/thing/internal/profiles/TimestampTriggerProfileTest.java, bundles/org.openhab.core.ui/src/main/java/org/openhab/core/ui/internal/items/ItemUIRegistryImpl.java, bundles/org.openhab.core.ui/src/test/java/org/openhab/core/ui/internal/items/ItemUIRegistryImplTest.java, bundles/org.openhab.core/src/main/java/org/openhab/core/library/types/DateTimeGroupFunction.java, bundles/org.openhab.core/src/main/java/org/openhab/core/library/types/DateTimeType.java, bundles/org.openhab.core/src/test/java/org/openhab/core/library/types/DateTimeGroupFunctionTest.java, bundles/org.openhab.core/src/test/java/org/openhab/core/library/types/DateTimeTypeTest.java, itests/org.openhab.core.io.rest.core.tests/src/main/java/org/openhab/core/io/rest/core/item/EnrichedItemDTOMapperWithTransformOSGiTest.java
Proposal for switching `DateTimeType` to use `Instant` internally rather than `ZonedDateTime`.
This will effectively discard time-zone information from the _source_ of the `DateTimeType` and leave it to consumers to apply time-zone at the moment of _presentation_, according to the configured time-zone in openHAB regional settings or in the browser.
Configured time-zone is now applied for:
- REST API
- SSE item state events
- Item UI registry (affecting e.g. sitemaps)
Consequential changes because `DateTimeType` is now "zone-less":
- Parameter `timezone` for `TimestampOffsetProfile` has been removed. openhab/openhab-docs#2403 has been prepared.
- Methods `toZone` and `toLocaleZone` have been marked as deprecated and all usages have been refactored. I would suggest to remove them in 5.0 (or …
=> [core] Switch `DateTimeType` to `Instant` internally for consistent time-zone handling

bundles/org.openhab.core.automation.rest/src/main/java/org/openhab/core/automation/rest/internal/ThingActionsResource.java
It is required for actions from the max binding.
=> Thing action REST API: allow extended scope like bindingid-xxx

bundles/org.openhab.core.addon.marketplace/src/main/java/org/openhab/core/addon/marketplace/BundleVersion.java, bundles/org.openhab.core.addon.marketplace/src/main/java/org/openhab/core/addon/marketplace/internal/community/CommunityRuleTemplateAddonHandler.java, bundles/org.openhab.core.addon.marketplace/src/main/java/org/openhab/core/addon/marketplace/internal/community/CommunityTransformationAddonHandler.java, bundles/org.openhab.core.addon/src/main/java/org/openhab/core/addon/AddonInfoRegistry.java, bundles/org.openhab.core.addon/src/main/java/org/openhab/core/addon/internal/xml/AddonDiscoveryMethodConverter.java, bundles/org.openhab.core.addon/src/main/java/org/openhab/core/addon/internal/xml/AddonInfoConverter.java, bundles/org.openhab.core.addon/src/main/java/org/openhab/core/addon/internal/xml/AddonInfoListConverter.java, bundles/org.openhab.core.addon/src/main/java/org/openhab/core/addon/internal/xml/AddonInfoXmlProvider.java, bundles/org.openhab.core.addon/src/main/java/org/openhab/core/addon/internal/xml/AddonInfoXmlResult.java, bundles/org.openhab.core.addon/src/main/java/org/openhab/core/addon/internal/xml/AddonMatchPropertyConverter.java, bundles/org.openhab.core.addon/src/main/java/org/openhab/core/addon/internal/xml/AddonParameterConverter.java, bundles/org.openhab.core.addon/src/main/java/org/openhab/core/addon/internal/xml/AddonXmlConfigDescriptionProvider.java
=> Warning hunt in org.openhab.core.addon.xxx

bundles/org.openhab.core.persistence/src/main/java/org/openhab/core/persistence/registry/PersistenceServiceConfigurationDTOMapper.java
A persistence item exclusion configuration done in the UI was not properly set in the REST call.
This PR fixes this.
See discussion: https://community.openhab.org/t/openhab-4-3-release-discussion/160888/59
If merged, this should probably be picked for the first 4.3 patch release.
=> Fix UI persistence item exclude config

bundles/org.openhab.core.automation.module.script/src/main/java/org/openhab/core/automation/module/script/ScriptTransformationService.java, bundles/org.openhab.core.automation.module.script/src/test/java/org/openhab/core/automation/module/script/ScriptTransformationServiceTest.java
Fix #4414
Note that the problem didn't occur with JRuby scripting, but it does occur with JS Scripting.
Perhaps this should be backported to 4.3.x?
=> Clean up arguments after executing Script Transformation

features/karaf/openhab-tp/src/main/feature/feature.xml
Related to https://github.com/openhab/openhab-core/issues/4466.
=> Start SPI Fly (OSGi service loader) early

bundles/org.openhab.core/src/main/java/org/openhab/core/library/types/DateTimeType.java, bundles/org.openhab.core/src/test/java/org/openhab/core/library/types/DateTimeTypeTest.java
This DSL rule:
```java
rule "Test"
when
Item Test changed to ON
then
var zoned = ZonedDateTime.parse("2024-12-22T16:29+01:00")
logInfo("zoned to item", zoned.toString)
TestDateTime.postUpdate(zoned.toString)
zoned = (TestDateTime.state as DateTimeType).getZonedDateTime()
logInfo("zoned from item", zoned.toString)
TestDateTime.postUpdate(zoned.toString)
end
```
generates the following output in 4.3:
```
2024-12-23 00:27:00.168 [INFO ] [nhab.core.model.script.zoned to item] - 2024-12-22T16:29+01:00
2024-12-23 00:27:00.169 [INFO ] [ab.core.model.script.zoned from item] - 2024-12-22T16:29+01:00[Europe/Copenhagen]
2024-12-23 00:27:00.170 [WARN ] [b.core.model.script.actions.BusEvent] - Cannot convert '2024-12-22T16:29+01:00[Europe/Copenhagen]' to a state type which item 'TestDateTime' accepts: …
```
=> Enhance `DateTimeType` to parse `ZonedDateTime` with time-zone ID

bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/internal/addons/AddonResource.java
Reported on the forum. When installing add-ons from the marketplace the config-description could not be found because a wrong uid was used when retrieving it. As a result the configuration was not normalized and all numeric values were converted to a `Double`instead of the correct type.
=> Fix config normalization in addon configuration

bundles/org.openhab.core.model.rule/bnd.bnd, bundles/org.openhab.core.model.rule/pom.xml, bundles/org.openhab.core.model.rule/src/org/openhab/core/model/rule/jvmmodel/RulesJvmModelInferrer.xtend, bundles/org.openhab.core.model.script.runtime/src/org/openhab/core/model/script/runtime/internal/engine/DSLScriptEngine.java
=> Add sharedCache and privateCache to file-based RulesDSL

bundles/org.openhab.core/src/main/java/org/openhab/core/library/types/DateTimeType.java
Methods deprecated by #3583 and usages removed by openhab/openhab-addons#17725
I would suggest to keep `getZonedDateTime()` for some time, since it's commonly used in DSL rules:
- https://community.openhab.org/t/the-method-getzoneddatetime-from-the-type-datetimetype-is-deprecated/160763
- https://community.openhab.org/t/datetime-conversion-after-update-to-4-3-0/161053
- https://community.openhab.org/t/datetime-operations/160794/5
Related to #3583
=> Remove deprecated `DateTimeType` methods `toLocaleZone` and `toZone`

bundles/org.openhab.core.io.rest.auth/src/main/java/org/openhab/core/io/rest/auth/AuthFilter.java, bundles/org.openhab.core.io.websocket/src/main/java/org/openhab/core/io/websocket/CommonWebSocketServlet.java
Closes #4490.
Browser clients do not have the ability to set an `Authorization` header programatically on websocket requests. All they have control over is the URL and the websocket subprotocols sent (see https://developer.mozilla.org/en-US/docs/Web/API/WebSocket)
This PR adds support for specifying a bearer token via a websocket subprotocol, with the format `org.openhab.ws.accessToken.base64.<encoded-token>`.
The browser must specify at least one other subprotocol since the server must echo a selected subprotocol back.
For this, `org.openhab.ws.protocol.default` is used.
`<encoded-token>` must be base64-encoded without padding, since bearer tokens can contain characters a websocket protocol may not (`/` and `=`).
=> [websocket] Support token authentication through header

bundles/org.openhab.core.io.websocket/src/main/java/org/openhab/core/io/websocket/event/EventWebSocketAdapter.java
This is aligns the event WS name with the SSE events endpoint.
This is a breaking change for clients that have explicitly used `/ws/event-subscriber` instead of the default `/ws`.
=> [websocket] Change EventWebSocketAdapter adapter id to `events`

bundles/org.openhab.core/src/main/java/org/openhab/core/scheduler/CronAdjuster.java, bundles/org.openhab.core/src/test/java/org/openhab/core/internal/scheduler/CronAdjusterTest.java
Fix one of the problems in #4547
=> Prevent infinite loop in CronAdjuster with invalid date combinations

bundles/org.openhab.core.io.net/src/main/java/org/openhab/core/io/net/http/HttpUtil.java, bundles/org.openhab.core.io.net/src/test/java/org/openhab/core/io/net/http/BaseHttpUtilTest.java, bundles/org.openhab.core.io.net/src/test/java/org/openhab/core/io/net/http/HttpRequestBuilderTest.java, bundles/org.openhab.core.io.net/src/test/java/org/openhab/core/io/net/http/HttpUtilTest.java
Providing an invalid URI input was throwing an IllegalArgumentException from the underlying jetty library. This change properly catches it and throws an IOException instead, aligned with the error treatment in the rest of the method.
See also https://github.com/openhab/openhab-addons/pull/18066
=> HttpUtil: fix invalid URI

bundles/org.openhab.core.io.rest.sitemap/src/main/java/org/openhab/core/io/rest/sitemap/internal/SitemapResource.java
Fixes an issue where sitemaps containing group items that change,  only update when a subscription times out (30 seconds)
I noticed while troubleshooting our IOS client that the sitemap i use for the apple watch would not update in realtime, only every 30 seconds.  Turns out this sitemap only has group items, and our SitemapResource was not subscribing to those events.  This is a pretty small change, i would recommend to back port as well.
=> Ensure sitemap subscriptions are updated on Group Items

bundles/org.openhab.core.addon.marketplace.karaf/src/main/java/org/openhab/core/addon/marketplace/karaf/internal/community/CommunityKarafAddonHandler.java, bundles/org.openhab.core.addon.marketplace/src/main/java/org/openhab/core/addon/marketplace/internal/community/CommunityBlockLibaryAddonHandler.java, bundles/org.openhab.core.addon.marketplace/src/main/java/org/openhab/core/addon/marketplace/internal/community/CommunityBundleAddonHandler.java, bundles/org.openhab.core.addon.marketplace/src/main/java/org/openhab/core/addon/marketplace/internal/community/CommunityMarketplaceAddonService.java, bundles/org.openhab.core.addon.marketplace/src/main/java/org/openhab/core/addon/marketplace/internal/community/CommunityRuleTemplateAddonHandler.java, bundles/org.openhab.core.addon.marketplace/src/main/java/org/openhab/core/addon/marketplace/internal/community/CommunityTransformationAddonHandler.java, bundles/org.openhab.core.addon.marketplace/src/main/java/org/openhab/core/addon/marketplace/internal/community/CommunityUIWidgetAddonHandler.java, bundles/org.openhab.core.addon.marketplace/src/main/java/org/openhab/core/addon/marketplace/internal/json/JsonAddonService.java, bundles/org.openhab.core.auth.oauth2client/src/main/java/org/openhab/core/auth/oauth2client/internal/OAuthClientServiceImpl.java, bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/commands/AutomationCommandImport.java, bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/commands/AutomationCommandRemove.java, bundles/org.openhab.core.config.discovery.addon.upnp/src/test/java/org/openhab/core/config/discovery/addon/upnp/tests/UpnpAddonFinderTests.java, bundles/org.openhab.core.ephemeris/src/main/java/org/openhab/core/ephemeris/internal/EphemerisManagerImpl.java, bundles/org.openhab.core.io.net/src/main/java/org/openhab/core/io/net/http/PEMTrustManager.java, bundles/org.openhab.core.storage.json/src/test/java/org/openhab/core/storage/json/internal/JsonStorageTest.java, bundles/org.openhab.core.ui/src/main/java/org/openhab/core/ui/internal/proxy/ProxyServletService.java, itests/org.openhab.core.thing.tests/src/main/java/org/openhab/core/thing/binding/firmware/FirmwareTest.java, itests/org.openhab.core.thing.tests/src/main/java/org/openhab/core/thing/firmware/Constants.java
As part of https://github.com/openhab/openhab-core/pull/4546, it was pointed out the `URL` constructor has been deprecated in Java 21.
This PR removes all uses of the URL constructor in core.
It starts from https://github.com/openhab/openhab-core/pull/4546, which only looks at one class in `HttpUtil` (and also solves a different problem), so that should be reviewed first (and this one rebased afterwards).
@holgerfriedrich Let me know what you think.
=> Remove calls to deprecated URL constructor

bundles/org.openhab.core.io.websocket/src/main/java/org/openhab/core/io/websocket/log/LogWebSocket.java
Logging a log message within the log handler causes a stack overflow.
=> Avoid stack overflow - don't log a message within the log handler

bundles/org.openhab.core.id/src/main/java/org/openhab/core/id/InstanceUUID.java
From 3 to 0. Added null annotations.
=> Clear warnings in org.openhab.core.id

bom/compile/pom.xml, bom/runtime/pom.xml, features/karaf/openhab-tp/src/main/feature/feature.xml
Upgrades JUPnP from 3.0.1 to 3.0.3.
* https://github.com/jupnp/jupnp/releases/tag/3.0.2
* https://github.com/jupnp/jupnp/releases/tag/3.0.3
=> Upgrade JUPnP to 3.0.3

bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/binding/BaseThingHandler.java
This pull request fixes #4557. If the update of thing is not valid, the warning message now contains detailed information about the validation result.
=> Extends updateThing method warning message.

bom/compile/pom.xml, bom/runtime/pom.xml, features/karaf/openhab-tp/src/main/feature/feature.xml, itests/org.openhab.core.automation.integration.tests/itest.bndrun, itests/org.openhab.core.automation.module.core.tests/itest.bndrun, itests/org.openhab.core.automation.module.script.tests/itest.bndrun, itests/org.openhab.core.automation.module.timer.tests/itest.bndrun, itests/org.openhab.core.automation.tests/itest.bndrun, itests/org.openhab.core.ephemeris.tests/itest.bndrun, itests/org.openhab.core.model.item.tests/itest.bndrun, itests/org.openhab.core.model.rule.tests/itest.bndrun, itests/org.openhab.core.model.script.tests/itest.bndrun, itests/org.openhab.core.model.thing.tests/itest.bndrun
Upgrades Jollyday from 0.35.1 to 1.4.0.
https://github.com/focus-shift/jollyday/releases
=> Upgrade Jollyday to 1.4.0

bom/runtime/pom.xml, features/karaf/openhab-tp/src/main/feature/feature.xml
* Add wstx version matching cxf 3.x
This seems to be required for the demo app to resolve properly.
Transitive dependencies from karaf libs brings fasterxml.woodstox 7.x, whereas cxf 3.6.4 still requires fasterxml.woodstox 6.x.
Adding this resolves the issue with the demo app.
Relates to latest karaf upgrade, #4406.
Relates to openhab/openhab-distro#1721.
=> Fix version of fasterxml.woodstox

bundles/org.openhab.core.addon.marketplace/src/main/java/org/openhab/core/addon/marketplace/internal/community/CommunityTransformationAddonHandler.java
As discussed [here](https://community.openhab.org/t/marketplace-versioning-with-embedded-resource/161421/97), after installing transformations from the marketplace, retrieval of managed transformations from storage during OH startup fails with:
```
Couldn't deserialize value 'org.openhab.core.storage.json.internal.StorageEntry@168c2c9b'. Root cause is: org.openhab.core.transform.ManagedTransformationProvider$PersistedTransformation cannot be found by org.openhab.core.storage.json_5.0.0.202501210532
```
This PR fixes it according to my testing, the problem is that the correct classloader isn't available to `JsonStorage`.
I can't comply with the DCO as I don't submit real name and e-mail in public, but this should be small enough for the exception to apply. It was a one-liner until Spotless …
=> Fix managed transformations retrieval

bundles/org.openhab.core.io.websocket/src/main/java/org/openhab/core/io/websocket/event/EventWebSocket.java, bundles/org.openhab.core.io.websocket/src/test/java/org/openhab/core/io/websocket/EventWebSocketTest.java, bundles/org.openhab.core/src/main/java/org/openhab/core/events/TopicEventFilter.java, bundles/org.openhab.core/src/test/java/org/openhab/core/events/TopicEventFilterTest.java
Closes #4549.
Closes #3764.
The topic filter can be configured by sending a WS message like in following examples:
Only send all ItemCommandEvents:
```
{
"type": "WebSocketEvent",
"topic": "openhab/websocket/filter/topic",
"payload": "[\"openhab/items/*/command\"]",
"source": "ui-c2ead538aa"
}
```
Only send all ItemCommandEvents, except for the `test` Item:
```
{
"type": "WebSocketEvent",
"topic": "openhab/websocket/filter/topic",
"payload": "[\"openhab/items/*/command\", \"!openhab/items/test/command\"]",
"source": "ui-c2ead538aa"
}
```
Send all events, except ItemCommandEvents:
```
{
"type": "WebSocketEvent",
"topic": "openhab/websocket/filter/topic",
"payload": "[\"!openhab/items/*/command\"]",
"source": "ui-c2ead538aa"
}
```
=> Add topic filter for event WebSocket

bundles/org.openhab.core.model.rule/src/org/openhab/core/model/rule/RulesStandaloneSetup.xtend, bundles/org.openhab.core.model.rule/src/org/openhab/core/model/rule/jvmmodel/RulesJvmModelInferrer.xtend, bundles/org.openhab.core.model.script/src/org/openhab/core/model/script/ScriptStandaloneSetup.xtend, bundles/org.openhab.core.model.script/src/org/openhab/core/model/script/interpreter/ScriptInterpreter.xtend, bundles/org.openhab.core.model.script/src/org/openhab/core/model/script/jvmmodel/ScriptJvmModelInferrer.xtend, bundles/org.openhab.core.model.thing/src/org/openhab/core/model/thing/internal/GenericThingProvider.xtend
1. Remove unused imports and unnecessary private modifiers
2. Use `===` when comparing to null
3. Replace deprecated methods (`initializeLater`)
During the mvn phase ```generate-sources```, we have had around 70 warnings from the Xtend generator.
This PR fixes half of the warnings of the generate phase (still the compiler has some issues with the generated code, but this is out of scope for now).
These changes seem to be safe, the generated code does not have significant changes compared to the old output. 
FTR: those are the issues this PR is resolving:
```
[INFO] --- xtend:2.37.0:compile (default) @ org.openhab.core.model.rule ---
[WARNING] 
WARNING: 	RulesStandaloneSetup.xtend - org.openhab.core.model.rule\src\org\openhab\core\model\rule\RulesStandaloneSetup.xtend
32: The private …
```
=> Fix Xtend warnings

bundles/org.openhab.core.io.websocket/src/main/java/org/openhab/core/io/websocket/log/LogDTO.java, bundles/org.openhab.core.io.websocket/src/main/java/org/openhab/core/io/websocket/log/LogFilterDTO.java, bundles/org.openhab.core.io.websocket/src/main/java/org/openhab/core/io/websocket/log/LogWebSocket.java, bundles/org.openhab.core.io.websocket/src/main/java/org/openhab/core/io/websocket/log/LogWebSocketAdapter.java
- Reads the history so that the UI can populate logs on startup
- Manages high rate logging by sending logs in an array
This supports sending of history, and provides a method of managing message cadence.
When a client connects, it must send a filter request before the server will send any logs. This triggers the sending of history.
Live logs are sent as individual messages if they are received with sufficient spacing. When logs come in very quickly, they are clustered together and sent as an array after (up to) 100mS. With these changes I can view full zigbee debug logging which results in over 100 logs per second. The UI retains full responsiveness at this logging rate.
In principle the history size is configured in the `org.apache.felix.log.maxSize` property, but so far I've been …
=> Update logger to provide history and improve performance

bundles/org.openhab.core.addon.eclipse/src/main/java/org/openhab/core/addon/eclipse/internal/EclipseAddonService.java, bundles/org.openhab.core.addon/src/main/java/org/openhab/core/addon/AddonInfo.java, bundles/org.openhab.core.addon/src/main/java/org/openhab/core/addon/AddonInfoRegistry.java, bundles/org.openhab.core.addon/src/main/java/org/openhab/core/addon/internal/xml/AddonInfoAddonsXmlProvider.java, bundles/org.openhab.core.karaf/src/main/java/org/openhab/core/karaf/internal/KarafAddonService.java
This reverts commit 708a954081499754e3d36adc28cf16b7ffec7ad7
but with some modifications
This PR will use the name and description fields from addons.xml and return that to MainUI via REST. This is a change from before #3908 where the name and description fields from addons.xml were overwritten with "n/a". 
This data will be used for:
- This PR extends the search for addons within the description field too: https://github.com/openhab/openhab-webui/pull/3028
- Future improvements to addons store listing that can include addon description along with the title.
The addons.xml will be cleaned up so that all name/description fields of all addons contain the actual readable text, not i18n reference tags in this PR: https://github.com/openhab/openhab-addons/pull/18139
=> Revert "Fix addon name localisation before installation (#3908)"

bundles/org.openhab.core.config.discovery.sddp/src/main/java/org/openhab/core/config/discovery/sddp/SddpDevice.java
This PR adds a `toString()` method to the SddpDevice class to help developers add logging of discovery issues.
=> Enhance SDDP discovery by adding toString() method to aid logging

bundles/org.openhab.core.config.core/src/main/java/org/openhab/core/config/core/ConfigUtil.java, bundles/org.openhab.core.config.core/src/main/java/org/openhab/core/config/core/internal/normalization/AbstractNormalizer.java, bundles/org.openhab.core.config.core/src/main/java/org/openhab/core/config/core/internal/normalization/BooleanNormalizer.java, bundles/org.openhab.core.config.core/src/main/java/org/openhab/core/config/core/internal/normalization/DecimalNormalizer.java, bundles/org.openhab.core.config.core/src/main/java/org/openhab/core/config/core/internal/normalization/IntNormalizer.java, bundles/org.openhab.core.config.core/src/main/java/org/openhab/core/config/core/internal/normalization/ListNormalizer.java, bundles/org.openhab.core.config.core/src/main/java/org/openhab/core/config/core/internal/normalization/Normalizer.java, bundles/org.openhab.core.config.core/src/main/java/org/openhab/core/config/core/internal/normalization/NormalizerFactory.java, bundles/org.openhab.core.config.core/src/main/java/org/openhab/core/config/core/internal/normalization/TextNormalizer.java
Null annotations added
Code evolution to Java 17
=> Adding null annotations to config.core.internal.normalization 

bundles/org.openhab.core.config.core/src/main/java/org/openhab/core/config/core/ConfigParser.java, bundles/org.openhab.core.config.core/src/test/java/org/openhab/core/config/core/ConfigurationTest.java
This PR enables the usage of record for configuration DTOs.
Comes along with a bit of revamp of the ConfigParser class.
=> Let's also use records for configuration files.

bundles/org.openhab.core/src/main/java/org/openhab/core/library/types/QuantityType.java, bundles/org.openhab.core/src/test/java/org/openhab/core/library/types/QuantityTypeArithmeticGroupFunctionTest.java, bundles/org.openhab.core/src/test/java/org/openhab/core/library/types/QuantityTypeTest.java
Comparing QuantityType with inverted units was opposite of what it should be.
Also included tests to verify.
See https://github.com/openhab/openhab-addons/issues/18122#issuecomment-2602466530
@andrewfg @jimtng
=> Fix comparing QuantityType with inverted dimensions

bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/module/handler/IntervalConditionHandler.java, bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/module/handler/TimerModuleHandlerFactory.java, bundles/org.openhab.core.automation/src/main/resources/OH-INF/automation/moduletypes/IntervalCondition.json, itests/org.openhab.core.automation.module.timer.tests/src/main/java/org/openhab/core/automation/module/timer/internal/IntervalConditionHandlerTest.java
This condition handler limits how often the rule executes.
Main UI support https://github.com/openhab/openhab-webui/pull/3049
Self note: documentation - To be done after the acceptance of PR
=> Add IntervalConditionHandler

bundles/org.openhab.core.persistence/src/main/java/org/openhab/core/persistence/extensions/PersistenceExtensions.java, bundles/org.openhab.core.persistence/src/test/java/org/openhab/core/persistence/extensions/PersistenceExtensionsTest.java
Sum calculations in persistence extensions for QuantityType items where done, summing the values in the configured unit.
This creates a challenge for temperatures, where the result would be different depending on the configured unit. To keep the results consistent, the sums should be done in the system unit for the dimension, wich has an absolute zero.
This PR changes that.
The only impact would be for summing temperatures, whereby it is highly unlikely someone would be summing temperatures over a time series.
This relates to https://github.com/openhab/openhab-core/pull/4563 and would make the logic consistent between summing for groups and summing over persisted values.
This PR would also change the returned units for QuantityType variance and deviation calculations to the  logically …
=> Persistence extensions, calculate QuantityType sums in absolute values

bundles/org.openhab.core.addon.marketplace/src/main/java/org/openhab/core/addon/marketplace/internal/automation/MarketplaceRuleTemplateProvider.java, bundles/org.openhab.core.addon.marketplace/src/main/java/org/openhab/core/addon/marketplace/internal/community/CommunityRuleTemplateAddonHandler.java, bundles/org.openhab.core.automation.module.script.rulesupport/src/main/java/org/openhab/core/automation/module/script/rulesupport/loader/AbstractScriptDependencyTracker.java, bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/parser/jackson/AbstractJacksonYAMLParser.java, bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/parser/jackson/TemplateYAMLParser.java, bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/provider/file/AbstractFileProvider.java, bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/provider/file/AutomationWatchService.java, bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/provider/file/ModuleTypeFileProviderWatcher.java, bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/provider/file/TemplateFileProviderWatcher.java, bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/parser/Parser.java, bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/parser/ParsingNestedException.java, bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/parser/ValidationException.java, bundles/org.openhab.core.config.dispatch/src/main/java/org/openhab/core/config/dispatch/internal/ConfigDispatcherFileWatcher.java, bundles/org.openhab.core.model.yaml/src/main/java/org/openhab/core/model/yaml/internal/YamlModelRepositoryImpl.java, itests/org.openhab.core.automation.integration.tests/itest.bndrun, itests/org.openhab.core.automation.module.core.tests/itest.bndrun, itests/org.openhab.core.automation.module.script.tests/itest.bndrun, itests/org.openhab.core.automation.module.timer.tests/itest.bndrun, itests/org.openhab.core.automation.tests/itest.bndrun, itests/org.openhab.core.model.item.tests/itest.bndrun, itests/org.openhab.core.model.rule.tests/itest.bndrun, itests/org.openhab.core.model.script.tests/itest.bndrun, itests/org.openhab.core.model.thing.tests/itest.bndrun
Rule Template installation fixes
=> Rule Template installation fixes

bundles/org.openhab.core.io.console.karaf/src/main/java/org/openhab/core/io/console/karaf/internal/ConsoleSupportKaraf.java
I just came across this whilst reading the code. I'm not sure why it was calling registerCommand here, but it seems wrong.
=> Call unregisterCommand instead of registerCommand

bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/item/EnrichedGroupItemDTO.java, bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/item/EnrichedItemDTO.java, bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/item/EnrichedItemDTOMapper.java, bundles/org.openhab.core/src/main/java/org/openhab/core/items/GenericItem.java, bundles/org.openhab.core/src/main/java/org/openhab/core/items/Item.java, bundles/org.openhab.core/src/test/java/org/openhab/core/items/GenericItemTest.java
These methods are handy in many situations and isn't possible with mapdb persistence, so previously it would require something like influxdb.
It also solves the issue of needing to wait until persistence write operation is finished (if it was at all set up to persist on change), so this gives us a cheap and reliable / dependable way of getting the last change / last update time.
See discussions in 
https://community.openhab.org/t/persistence-on-off-transitions-with-influx/156271/
https://community.openhab.org/t/blockly-persistence-last-changed-returns-no-result-quite-often/157842
=> Add `getLastStateChange`, `getLastStateUpdate`, and `getLastState` to GenericItem

bundles/org.openhab.core/src/main/java/org/openhab/core/library/types/QuantityTypeArithmeticGroupFunction.java
The new code of the `toInvertibleUnit()` method of #4561 had been duplicated in parallel in #4563.
This PR simply removes that duplication.
=> GroupFunction calculations remove duplicate code

bundles/org.openhab.core/src/main/java/org/openhab/core/service/StartLevelService.java
This PR will add a debug log line in case a start level is not reached, there are small changes to update the code to use the `SequencedMap` interface added in JDK21.
Signed-off-by: Jörg Sautter joerg.sautter@gmx.net
=> Add logging to the StartLevelService

bundles/org.openhab.core.addon.marketplace/src/main/java/org/openhab/core/addon/marketplace/internal/json/JsonAddonService.java
When starting openHAB, I always get the following warning:
```
14:44:47.082 [WARN ] [tplace.internal.json.JsonAddonService] - JSON Addon Service invalid URL:
```
We should avoid this warning, I don't see a problem there, and we should not confuse users with unnecessary warnings.
=> JsonAddonService: Fix warning on startup if no URL configured

bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/internal/persistence/PersistenceResource.java, bundles/org.openhab.core.io.rest.core/src/test/java/org/openhab/core/io/rest/core/internal/persistence/PersistenceResourceTest.java, bundles/org.openhab.core.model.persistence/src/org/openhab/core/model/persistence/Persistence.xtext, bundles/org.openhab.core.model.persistence/src/org/openhab/core/model/persistence/internal/PersistenceModelManager.java, bundles/org.openhab.core.persistence/src/main/java/org/openhab/core/persistence/FilterCriteria.java, bundles/org.openhab.core.persistence/src/main/java/org/openhab/core/persistence/ModifiablePersistenceService.java, bundles/org.openhab.core.persistence/src/main/java/org/openhab/core/persistence/PersistenceItemConfiguration.java, bundles/org.openhab.core.persistence/src/main/java/org/openhab/core/persistence/QueryablePersistenceService.java, bundles/org.openhab.core.persistence/src/main/java/org/openhab/core/persistence/dto/PersistenceItemConfigurationDTO.java, bundles/org.openhab.core.persistence/src/main/java/org/openhab/core/persistence/dto/PersistenceServiceConfigurationDTO.java, bundles/org.openhab.core.persistence/src/main/java/org/openhab/core/persistence/extensions/PersistenceExtensions.java, bundles/org.openhab.core.persistence/src/main/java/org/openhab/core/persistence/internal/PersistenceManagerImpl.java, bundles/org.openhab.core.persistence/src/main/java/org/openhab/core/persistence/registry/PersistenceServiceConfiguration.java, bundles/org.openhab.core.persistence/src/main/java/org/openhab/core/persistence/registry/PersistenceServiceConfigurationDTOMapper.java, bundles/org.openhab.core.persistence/src/test/java/org/openhab/core/persistence/extensions/PersistenceExtensionsTest.java, bundles/org.openhab.core.persistence/src/test/java/org/openhab/core/persistence/internal/PersistenceManagerTest.java, bundles/org.openhab.core.ui/src/main/java/org/openhab/core/ui/internal/chart/defaultchartprovider/DefaultChartProvider.java
See discussion https://github.com/openhab/openhab-core/issues/4359
At its current state, defining and using aliases for persistence is largely broken.
1. At the point of definining aliases, one can define an alias in the syntax for an item, item group or all items. There are several issues with this way of defining:
- The last two options obviously don't make sense.
- One has to define with all parameters (strategy, filters) for each item you want to define an alias for (otherwise the default will be used). It becomes impossible to use a group definition for the strategy and filters.
- It is not possible to define an alias for an item without a strategy (once you define it, the default strategy will be applied). This can be useful if an item is persisted manually through a rule, and not …
=> Persistence aliases

bom/compile/pom.xml, bom/runtime/pom.xml, features/karaf/openhab-tp/src/main/feature/feature.xml, itests/org.openhab.core.automation.integration.tests/itest.bndrun, itests/org.openhab.core.automation.module.core.tests/itest.bndrun, itests/org.openhab.core.automation.module.script.tests/itest.bndrun, itests/org.openhab.core.automation.module.timer.tests/itest.bndrun, itests/org.openhab.core.automation.tests/itest.bndrun, itests/org.openhab.core.ephemeris.tests/itest.bndrun, itests/org.openhab.core.model.item.tests/itest.bndrun, itests/org.openhab.core.model.rule.tests/itest.bndrun, itests/org.openhab.core.model.script.tests/itest.bndrun, itests/org.openhab.core.model.thing.tests/itest.bndrun
Upgrades Jollyday from 1.4.0 to 1.5.0.
https://github.com/focus-shift/jollyday/releases
=> Upgrade Jollyday to 1.5.0

bundles/org.openhab.core.model.item/src/org/openhab/core/model/item/internal/fileconverter/DslItemFileConverter.java, bundles/org.openhab.core.model.thing/src/org/openhab/core/model/thing/internal/fileconverter/DslThingFileConverter.java
Fix a bug in link with item metadata when using DSL generator provided by PR #4569
=> [DSL generator] Handle config parameter value of type Double

bundles/org.openhab.core.persistence/src/main/java/org/openhab/core/persistence/QueryablePersistenceService.java, bundles/org.openhab.core.persistence/src/main/java/org/openhab/core/persistence/internal/PersistenceManagerImpl.java, bundles/org.openhab.core.persistence/src/test/java/org/openhab/core/persistence/internal/PersistenceManagerTest.java
Closes https://github.com/openhab/openhab-core/issues/4645
https://github.com/openhab/openhab-core/pull/4463 introduced restoring `lastState` and `lastStateUpdate` from persistence, introducing a new method `persistedItem` in the `QueryablePersistenceService`.
To achieve this, the default implementation would iterate backwards over the full persisted history. Specific services could override this and implement a better algorithm. This has been done for `mapdb` and `rrd4j`.
It turns out this unbounded iteration over the history can lead to performance problems, see issue. Specifically for `influxdb` there are optimizations when only retrieving the last value.
To avoid problems, I have partially reverted the logic of https://github.com/openhab/openhab-core/pull/4463. The default method will …
=> Revert iterating over history for restore on startup

bundles/org.openhab.core.persistence/src/main/java/org/openhab/core/persistence/internal/PersistenceManagerImpl.java, bundles/org.openhab.core/src/main/java/org/openhab/core/items/GenericItem.java, bundles/org.openhab.core/src/main/java/org/openhab/core/items/GroupItem.java
Closes https://github.com/openhab/openhab-core/issues/4649
https://github.com/openhab/openhab-core/pull/4463 introduced restoring `lastState`, `lastStateUpdate` and `lastStateChange` from persistence.
This broke restoring nested groups, as this relied on update events from the items to the groups. Update events would not allows group state updates to be restored with correct dates, or the `lastState` of the group to be restored.
This PR also saves the nested group itself when it has a state and uses this in restore.
=> Fix restoring nested group items from persistence

bundles/org.openhab.core.io.console.karaf/src/main/java/org/openhab/core/io/console/karaf/OSGiConsole.java, bundles/org.openhab.core.io.console.karaf/src/main/java/org/openhab/core/io/console/karaf/internal/CommandWrapper.java, bundles/org.openhab.core.io.console/src/main/java/org/openhab/core/io/console/Console.java
This PR provides Karaf's Session object through OSGiConsole object that's provided to `ConsoleCommandExtension`s.
The Karaf `Session` enables ConsoleCommandExtensions to prompt for user input. The simplest usage is provided through a convenience method `OSGiConsole.readLine()`.
A more advanced usage is also possible by constructing a custom org.jline.reader.LineReader object which requires the Terminal from console.getSession().getTerminal(). This is useful for more complex input scenarios, such as when you need to have sub-shell history, custom completion, etc.
This PR will enable the creation of a JRuby REPL inside the Karaf console. This REPL will run inside the same engine / environment as a normal JRuby rule, so it will have access to runtime Items, Things, events, etc, just like a …
=> Provide Karaf Session object inside OSGiConsole

bundles/org.openhab.core.model.sitemap/src/org/openhab/core/model/sitemap/Sitemap.xtext, bundles/org.openhab.core.model.sitemap/src/org/openhab/core/model/sitemap/validation/SitemapValidator.xtend, bundles/org.openhab.core.ui/src/main/java/org/openhab/core/ui/chart/ChartProvider.java, bundles/org.openhab.core.ui/src/main/java/org/openhab/core/ui/internal/chart/ChartServlet.java, bundles/org.openhab.core.ui/src/main/java/org/openhab/core/ui/internal/chart/defaultchartprovider/DefaultChartProvider.java, bundles/org.openhab.core.ui/src/main/java/org/openhab/core/ui/internal/components/UIComponentSitemapProvider.java
Closes https://github.com/openhab/openhab-core/issues/3662
This introduces an extra parameter for sitemap charts, `interpolation`, that can take two possible values: `linear` or `step`. If not set, the current behaviour will be used (`step` for OnOff or OpenClosed and `linear` for all other values).
Also fixes an issue where the `yAxisDecimalPattern` was not considered for managed sitemaps.
=> Sitemap interpolation parameter for charts

bundles/org.openhab.core.persistence/src/main/java/org/openhab/core/persistence/extensions/PersistenceExtensions.java, bundles/org.openhab.core.persistence/src/test/java/org/openhab/core/persistence/extensions/PersistenceExtensionsTest.java, bundles/org.openhab.core.persistence/src/test/java/org/openhab/core/persistence/extensions/TestPersistenceService.java
Closes https://github.com/openhab/openhab-core/issues/4439
At the moment, it is not possible to easily calculate the integral value of the curve represented by persisted values. This is useful for calculating e.g. total energy consumed (in kWh) from instantaneous power meter readings (in W).
The current `sum` persistence actions calculate a sum without considering the time dimension, and therefore are only useful when we have a guaranteed constant interval between persisted values for this.
The `average` actions do use a time weighting in their calculation. Multiplying the average with the total duration considered would give an approximation. However, the `average` calculations assume a constant value over the bucket and take the value at the start of the bucket. Using this average to …
=> Persistence Extensions: Riemann Sums

.github/workflows/ci-build.yml
* pin external action stCarolas/setup-maven to specific SHA
* set global timeout
* comments
* Restore broken registration of problem matchers (this was forgotten when we removed Java17)
=> Improve GitHub Action

bundles/org.openhab.core.config.core/src/test/java/org/openhab/core/config/core/internal/validation/ConfigDescriptionValidatorTest.java, bundles/org.openhab.core.config.discovery/src/test/java/org/openhab/core/config/discovery/inbox/events/InboxEventFactoryTest.java, bundles/org.openhab.core.io.rest/src/test/java/org/openhab/core/io/rest/Stream2JSONInputStreamTest.java, bundles/org.openhab.core.model.yaml/src/test/java/org/openhab/core/model/yaml/internal/YamlModelRepositoryImplTest.java, bundles/org.openhab.core.thing/src/test/java/org/openhab/core/thing/link/events/LinkEventFactoryTest.java, bundles/org.openhab.core/src/test/java/org/openhab/core/cache/ExpiringCacheMapTest.java, bundles/org.openhab.core/src/test/java/org/openhab/core/items/events/ItemEventFactoryTest.java
This pull request resolves several non-deterministic tests in the repository, addressing some of the tests mentioned in the issue [openhab-core issue #4474](https://github.com/openhab/openhab-core/issues/4474).
There were a number of flaky tests in the repository which were detected using the [NonDex](https://github.com/TestingResearchIllinois/NonDex) tool. More details about the steps to reproduce it and the details for the tools are mentioned in [openhab-core issue #4474](https://github.com/openhab/openhab-core/issues/4474).
This PR fixes the following tests mentioned below and the steps to reproduce the issue is already mentioned in [openhab-core issue #4474](https://github.com/openhab/openhab-core/issues/4474):
- org.openhab.core.thing.link.events.LinkEventFactoryTest.testCreateItemCha …
=> Fixed a few non deterministic tests in the repository

tools/i18n-plugin/src/main/java/org/openhab/core/tools/i18n/plugin/GenerateDefaultTranslationsMojo.java, tools/i18n-plugin/src/main/java/org/openhab/core/tools/i18n/plugin/XmlToTranslationsConverter.java, tools/i18n-plugin/src/test/java/org/openhab/core/tools/i18n/plugin/XmlToTranslationsConverterTest.java
Fix the translations generation for non-binding addons, e.g. org.openhab.io.homekit, org.openhab.automation.jrubyscripting.
Previously it would only generate the main `addon.<id>.name` and description. It ignored config.xml for these types of add-ons.
This PR processes all the config descriptions into the translation file.
This should also resolve #4362 by translating all the found config descriptions (xml files) so it will work on profiles etc.
=> Fix i18n:generate-default-translations on add-on config other than bindings

bundles/org.openhab.core.model.persistence/src/org/openhab/core/model/persistence/Persistence.xtext
Closes https://github.com/openhab/openhab-core/issues/4625#issuecomment-2692693848
Persistence definition filters with units required the unit to be a valid string. The parser would not recognize units containing special characters as Strings (e.g. °C, kΩ) unless the unit string would be surrounded by quotes. The documentation makes no mention of this constraint and only provided examples with no special characters and without quotes (https://www.openhab.org/docs/configuration/persistence.html#threshold-filter).
With this PR, the parser will also recognize special characters that can be part of a unit definition when parsing the unit, removing the need to have units with special characters to be enclosed in quotes.
This has been tested with the following filter definitions:
```
Filters { …
```
=> Persistence filters allow unquoted units

bundles/org.openhab.core.semantics/src/main/java/org/openhab/core/semantics/SemanticTags.java, bundles/org.openhab.core.semantics/src/main/java/org/openhab/core/semantics/internal/SemanticsServiceImpl.java, bundles/org.openhab.core.semantics/src/test/java/org/openhab/core/semantics/internal/SemanticsServiceImplTest.java
See discussion in https://community.openhab.org/t/openhab-5-semantic-model-proposal/162526/21
Sample log messages at `WARN` level
```
Item 'InvalidPoint1' (Point) has invalid semantic structure: It belongs to multiple locations [Location1, Location2]. It should only belong to one Equipment or one location, preferably not both at the same time.
Item 'InvalidPoint2' (Point) has invalid semantic structure: It belongs to multiple locations [Location1, Location1Sub]. It should only belong to one Equipment or one location, preferably not both at the same time.
Item 'InvalidPoint3' (Point) has invalid semantic structure: It belongs to multiple equipments [Equipment1, Equipment2]. A Point can only belong to at most one Equipment.
Item 'InvalidLocation1' (Location) has invalid semantic structure: …
```
=> Log warnings when an Item's semantic structure is incorrect

bundles/org.openhab.core.io.monitor/bnd.bnd, bundles/org.openhab.core.io.monitor/pom.xml, bundles/org.openhab.core.io.monitor/src/main/java/org/openhab/core/io/monitor/internal/DefaultMetricsRegistration.java, bundles/org.openhab.core.io.monitor/src/main/java/org/openhab/core/io/monitor/internal/metrics/ThreadPoolMetric.java, bundles/org.openhab.core/src/main/java/org/openhab/core/common/ThreadPoolManager.java
* metrics-core from 4.0.7 to 4.2.30
Release notes:
https://github.com/dropwizard/metrics/releases
* micrometer-core from 1.6.3 to 1.14.4
Release notes:
https://github.com/micrometer-metrics/micrometer/releases
* HdrHistogram from 2.1.12 to 2.2.2
Release notes:
https://github.com/HdrHistogram/HdrHistogram/releases/tag/HdrHistogram-2.2.1 https://github.com/HdrHistogram/HdrHistogram/releases/tag/HdrHistogram-2.2.2
=> [io.monitor] Upgrade dependencies and enable monitoring of ThreadPools

bundles/org.openhab.core.config.core/src/main/java/org/openhab/core/config/core/ConfigUtil.java, bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/config/EnrichedConfigDescriptionParameterDTO.java, bundles/org.openhab.core.io.rest.core/src/test/java/org/openhab/core/io/rest/core/config/EnrichedConfigDescriptionDTOMapperTest.java
This PR is needed in order to introduce a parameter with multiple="true" whose default values contain a comma character.
This PR allows a comma character to be a part of the value when escaped with a backslash. The backslash will be removed, i.e. `\,` -> `,`
To have an actual backslash and comma, add an extra backslash, i.e. `\\,` -> `\,`
A quick search in the openhab-addons repository didn't yield a current use of comma-separated default values for a `multiple="true"` parameter.
This fix will work in conjunction with a fix in webui to be submitted.
=> Allow multiple default values to contain an escaped comma

bundles/org.openhab.core.persistence/src/main/java/org/openhab/core/persistence/internal/PersistenceManagerImpl.java
#Fix timeseries restore init late initialization of listenners on GenericItem, #4656,
This PR is to fix lost value in timeseries update observe on issue #4656 on openhab startup.
The GenericItem implements a timeSeriesListener that is initialized from PersistentManagerImpl.allItemsChanged().
The initialization of this timeSeriesListerner can occurs lately after initialization of openhab because the init is in the same loop as the perstistence value restore from persistence layer.
This persistence restore take long time because of multiple request to the persistence store and db, and so delayed the initialization.
The idea there is to break the loop into 2 parts:
One for the timeSeriesListener initialization which is very fast, and have to be done immedialty.
One for the value restore that …
=> Fix timeseries restore init late initialization of listeners on GenericItem

bundles/org.openhab.core.semantics/src/test/java/org/openhab/core/semantics/SemanticTagsTest.java
This will currently fail because there's a duplicate tag. The duplicate is removed in #4700, so once that's merged, the test in this PR should pass.
Currently duplicate tags would've caused some tests to fail, but the reason for the failure isn't clear without digging into surefire-reports.
=> Check for duplicate tags in SemanticTags.csv

bundles/org.openhab.core.auth.oauth2client/src/main/java/org/openhab/core/auth/oauth2client/internal/OAuthClientServiceImpl.java, bundles/org.openhab.core.auth.oauth2client/src/main/java/org/openhab/core/auth/oauth2client/internal/OAuthConnector.java, bundles/org.openhab.core.auth.oauth2client/src/main/java/org/openhab/core/auth/oauth2client/internal/OAuthConnectorRFC8628.java
Relates to #4698 
This PR contains the following post-fixes..
- Add a timeout to OAuth HTTP calls
- Eliminate thread-lock on notification call-backs
- Fix deserialization of OAuthResponseException JSON
- Catch JSON syntax errors
=> OAuth RFC-8628 various post-fixes

bundles/org.openhab.core.config.discovery.upnp/src/main/java/org/openhab/core/config/discovery/upnp/internal/UpnpDiscoveryService.java, bundles/org.openhab.core.io.transport.upnp/src/main/java/org/openhab/core/io/transport/upnp/internal/UpnpIOServiceImpl.java
As describe in issue #4711, the UPNP embedded device are today ignore in openhab code.
We need three modification to handle them:
- In discovery service, loop on the EmbeddedDevice collection to also handle there as discovery result.
- In UpnpIOServiceImpl, change call to getDevice, passing false instead of true to rootOnly parameter.
- In UpnpIOServiceImpl, change logic in remoteDeviceAdded and remoteDeviceRemoved to also handle embeddedDevice.
=> Fix UPNP support to handle embededd devices

bundles/org.openhab.core/src/main/java/org/openhab/core/internal/items/ExpireManager.java, bundles/org.openhab.core/src/test/java/org/openhab/core/internal/items/ExpireManagerTest.java
- Enrich duration format:
- Duration format supports days e.g. `1d3h`
- Supports ISO8601 Duration syntax e.g. `P1DT3H`
- Support configuring the expire manager through the metadata configuration map by adding:
- `duration`: "1h 1m 1s"
- `command`: ON
- `state`: ON
- Fully backwards compatible. The old way of specifying expire value `1h5m,command=OFF` is still supported
- Specifying any setting (duration, command, state) in both value and metadata config will raise an error
- Specifying both command and state in the configuration will raise an error
=> Make `expire` support days, ISO8601 Duration and fully configurable through metadata configuration map

bundles/org.openhab.core/src/main/java/org/openhab/core/items/events/ItemTimeSeriesEvent.java, bundles/org.openhab.core/src/main/java/org/openhab/core/items/events/ItemTimeSeriesUpdatedEvent.java
When time series are updated, the event log files are flooded with values, which does not really help readibility - I would think that it is enough to state the number of elements, but not all the individual objects.
=> Shorten logging of timeseries updates

bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/binding/BaseThingHandlerFactory.java, pom.xml
This is needed for dynamic things like Home Assistant devices that may or may not have particular services available, and it's not known until the thing has be initialized if that is the case. See also https://github.com/openhab/openhab-addons/issues/17992
=> Allow ThingHandlers to dynamically register services

bundles/org.openhab.core/src/main/java/org/openhab/core/items/GroupItem.java
Closes https://github.com/openhab/openhab-core/issues/4736
Closes https://github.com/openhab/openhab-addons/issues/18586
Regression of https://github.com/openhab/openhab-core/pull/4651
For group items with an aggregation function (state), nested items where not persisted and restored. These nested items where missed when building the list of items to persist/restore. It did work well when the group item did not have a state.
=> Fix groupItem restore

bundles/org.openhab.core.model.yaml/src/main/java/org/openhab/core/model/yaml/internal/things/YamlThingDTO.java, bundles/org.openhab.core.model.yaml/src/main/java/org/openhab/core/model/yaml/internal/things/YamlThingProvider.java
The typo was `segement`.
@lolodomo
=> YAMLThing: fix typo and minor refactor

bundles/org.openhab.core.model.yaml/src/main/java/org/openhab/core/model/yaml/internal/YamlModelRepositoryImpl.java, bundles/org.openhab.core.model.yaml/src/test/java/org/openhab/core/model/yaml/internal/YamlModelRepositoryImplTest.java
Make the log messages include the .yaml extension, e.g.
```
2025-04-25 17:19:03.757 [INFO ] [aml.internal.YamlModelRepositoryImpl] - Adding YAML model things/test.yaml
2025-04-25 17:19:03.770 [WARN ] [aml.internal.YamlModelRepositoryImpl] - Version is missing or not a number in model things/test.yaml. Ignoring it.
```
It is even more important to include the extension in other messages such as:
https://github.com/openhab/openhab-core/blob/685264295c62f5e8179d36ba06b60aa55cc9115f/bundles/org.openhab.core.model.yaml/src/main/java/org/openhab/core/model/yaml/internal/YamlModelRepositoryImpl.java#L200
https://github.com/openhab/openhab-core/blob/685264295c62f5e8179d36ba06b60aa55cc9115f/bundles/org.openhab.core.model.yaml/src/main/java/org/openhab/core/model/yaml/internal/YamlModelRepositoryImp …
=> Yaml Model Repository: Include `.yaml` in log messages

bundles/org.openhab.core.model.yaml/src/main/java/org/openhab/core/model/yaml/internal/YamlModelRepositoryImpl.java
This fix two scenarios:
- When the new model is missing `version:` key but the old model had one, the file is considered invalid, but the previously loaded elements didn't get removed
- When the new model has a valid `version:` key, but the entire element type, e.g. `thing:` is removed, the previously loaded elements (e.g. things) didn't get removed.
Additionally, log a warning when an unknown element type is encountered, log a warning, e.g.
```
version: 2
thangs: # misspelled?
x:y:z:d: xx
```
See https://github.com/openhab/openhab-core/issues/3666#issuecomment-2829347883
=> Yaml Model Repository: Remove elements no longer in model

bundles/org.openhab.core.model.yaml/src/main/java/org/openhab/core/model/yaml/internal/YamlModelRepositoryImpl.java
Fix a problem introduced in #4749
Wait until all known elements are loaded before issuing warnings about unknown elements.
=> YAML Model Repository: Fix premature unknown element warning

bundles/org.openhab.core.model.yaml/src/main/java/org/openhab/core/model/yaml/internal/YamlModelRepositoryImpl.java
The text "at [Source: UNKNOWN; byte offset: #UNKNOWN] " is removed from the exception message before being logged.
=> YAML parser: filter unexpected part from the parse exception message

bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/internal/fileformat/FileFormatResource.java, bundles/org.openhab.core.model.item/src/org/openhab/core/model/item/internal/fileconverter/DslItemFileConverter.java, bundles/org.openhab.core.model.thing/src/org/openhab/core/model/thing/internal/fileconverter/DslThingFileConverter.java
Fix #4778
Things and items are now sorted in output only when all elements are requested. If the API is requested only for a subset of elements (things or items), the output respects the input order of elements.
DSL generator for things and items is also fixed to avoid a crash when called with 0 element.
=> [REST] Fix API to get file format when applied to a subset of elements

bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/internal/item/ItemResource.java
Adds support for sending command/state through media type `application/json` to the existing plain text endpoints.
=> [rest] Support sending Item command/state as JSON

bundles/org.openhab.core.automation.module.script.rulesupport/src/main/java/org/openhab/core/automation/module/script/rulesupport/loader/AbstractScriptDependencyTracker.java, bundles/org.openhab.core.automation.module.script.rulesupport/src/main/java/org/openhab/core/automation/module/script/rulesupport/loader/AbstractScriptFileWatcher.java, bundles/org.openhab.core.automation.module.script.rulesupport/src/test/java/org/openhab/core/automation/module/script/rulesupport/loader/AbstractScriptDependencyTrackerTest.java, bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/provider/file/AutomationWatchService.java, bundles/org.openhab.core.config.dispatch/src/main/java/org/openhab/core/config/dispatch/internal/ConfigDispatcherFileWatcher.java, bundles/org.openhab.core.config.dispatch/src/test/java/org/openhab/core/config/dispatch/internal/ConfigDispatcherFileWatcherTest.java, bundles/org.openhab.core.model.core/src/main/java/org/openhab/core/model/core/internal/folder/FolderObserver.java, bundles/org.openhab.core.model.core/src/test/java/org/openhab/core/model/core/internal/folder/FolderObserverTest.java, bundles/org.openhab.core.model.yaml/src/main/java/org/openhab/core/model/yaml/internal/YamlModelRepositoryImpl.java, bundles/org.openhab.core.model.yaml/src/test/java/org/openhab/core/model/yaml/internal/YamlModelRepositoryImplTest.java, bundles/org.openhab.core.transform/src/main/java/org/openhab/core/transform/FileTransformationProvider.java, bundles/org.openhab.core.transform/src/test/java/org/openhab/core/transform/FileTransformationProviderTest.java, bundles/org.openhab.core/src/main/java/org/openhab/core/internal/service/WatchServiceImpl.java, bundles/org.openhab.core/src/main/java/org/openhab/core/service/WatchService.java, bundles/org.openhab.core/src/test/java/org/openhab/core/internal/service/WatchServiceImplTest.java
Currently `processWatchEvent` is called with a relative path. This path is relative to the path given to `WatchService.registerListener`. For example:
```java
configWatchService.registerListener(this, Path.of("rules"));
```
Now when a file is created: `CONF/rules/test1.rules`
Will result in processWatchEvent being called with the `path` argument equals to `test1.rules`.
So far, all current implementations of `WatchService.WatchEventListener` have dealt with this by creating an absolute path that is relative to a pre-resolved absolute path that it passed to `registerListener`, for example: https://github.com/openhab/openhab-core/blob/8eb6eeae8473f8ba8ab5f74e53436dbedb53acc9/bundles/org.openhab.core.automation.module.script.rulesupport/src/main/java/org/openhab/core/automation/module/script/ …
=> WatchService: use absolute path in processWatchEvent

.github/workflows/ci-build.yml, .github/workflows/rebuild.yml
* Move triggering rebuild on label to separate workflow
```
#
#
```
* Grant permissions for removing label
Due to our default settings on this repo, changing PR labels is not possible from Actions:
```
Run gh pr edit $PR --remove-label rebuild
GraphQL: Resource not accessible by integration (removeLabelsFromLabelable)
Error: Process completed with exit code 1.
```
This PR adds the necessary permissions for `GITHUB_TOKEN` used by the `gh` tool to remove the label.
=> [GHA] Adapt rebuild

bundles/org.openhab.core.semantics/model/generateTagClasses.groovy, bundles/org.openhab.core.semantics/src/main/java/org/openhab/core/semantics/SemanticTagImpl.java, bundles/org.openhab.core.semantics/src/main/resources/tags.properties
With all the work being done on adding better semantic tags, I was looking at making the semantic tag descriptions available in the UI, to help the user in deciding what tag to use.
It turned out very few had descriptions in the first place, and they cannot be localized.
This PR adds the ability to localize the semantic tag descriptions.
I would think an effort should be made to give the semantic tags relevant descriptions that help the user to understand what tag to use when. I think the best people to do that are also the ones that worked on changing and adding the semantic tags. @andrewfg @jimtng and others?
I intend to enhance the UI to make these descriptions visible when available. They are already in the the semantic tag maintenance UI proposed in …
=> Enable semantic tag description translations

tools/upgradetool/pom.xml, tools/upgradetool/src/main/java/org/openhab/core/tools/UpgradeTool.java, tools/upgradetool/src/main/java/org/openhab/core/tools/Upgrader.java, tools/upgradetool/src/main/java/org/openhab/core/tools/internal/ItemUnitToMetadataUpgrader.java, tools/upgradetool/src/main/java/org/openhab/core/tools/internal/JSProfileUpgrader.java, tools/upgradetool/src/main/java/org/openhab/core/tools/internal/ScriptProfileUpgrader.java, tools/upgradetool/src/main/java/org/openhab/core/tools/internal/YamlConfigurationV1TagsUpgrader.java
- Refactor Upgrade Tool so that each upgrader task is contained in a separate class
- Add --list-commands parameter
- Rename --dir to --userdata to accept a custom path to OPENHAB_USERDATA dir
- Add --conf to accept a custom path to OPENHAB_CONF dir (See https://github.com/openhab/openhab-distro/pull/1740)
- Avoid some null compiler warnings
- Add a new upgrader to convert tags list to map structure in YAML configuration V1
Input file criteria:
- Search only in CONF/tags/, or in the given directory, and its subdirectories
- Contains a version key with value 1
- it must contain a tags key that is a list
- The tags list must contain a uid key
- If the above criteria are not met, the file will not be modified
Output file will
- Retain `version: 1`
- convert tags list to a map with uid as key …
=> UpgradeTool: Add Yaml configuration upgrader to convert tags list to map

bundles/org.openhab.core.model.yaml/src/main/java/org/openhab/core/model/yaml/internal/YamlModelRepositoryImpl.java
@Nadahar see https://github.com/openhab/openhab-core/commit/f5f8921e14814b3e3e6f43e32a28d2cb8d9cd23d#r156317816
The compiler issued warnings about null type mismatch. There may be a small possibility that it would return null in case `modelCache`/`model` is modified elsewhere perhaps. This refactor removes that possibility and as a result the compiler no longer has a warning about it.
=> Refactor to avoid possible null pointer dereference in YamlModelRepositoryImpl

bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/internal/fileformat/FileFormatResource.java, bundles/org.openhab.core.model.yaml/src/main/java/org/openhab/core/model/yaml/internal/YamlModelRepositoryImpl.java, bundles/org.openhab.core.model.yaml/src/main/java/org/openhab/core/model/yaml/internal/items/YamlChannelLinkProvider.java, bundles/org.openhab.core.model.yaml/src/main/java/org/openhab/core/model/yaml/internal/items/YamlGroupDTO.java, bundles/org.openhab.core.model.yaml/src/main/java/org/openhab/core/model/yaml/internal/items/YamlItemDTO.java, bundles/org.openhab.core.model.yaml/src/main/java/org/openhab/core/model/yaml/internal/items/YamlItemProvider.java, bundles/org.openhab.core.model.yaml/src/main/java/org/openhab/core/model/yaml/internal/items/YamlMetadataDTO.java, bundles/org.openhab.core.model.yaml/src/main/java/org/openhab/core/model/yaml/internal/items/YamlMetadataProvider.java, bundles/org.openhab.core.model.yaml/src/main/java/org/openhab/core/model/yaml/internal/items/fileconverter/YamlItemFileConverter.java, bundles/org.openhab.core.model.yaml/src/main/java/org/openhab/core/model/yaml/internal/util/YamlElementUtils.java, bundles/org.openhab.core.model.yaml/src/test/java/org/openhab/core/model/yaml/internal/items/YamlGroupDTOTest.java, bundles/org.openhab.core.model.yaml/src/test/java/org/openhab/core/model/yaml/internal/items/YamlItemDTOTest.java, bundles/org.openhab.core/src/main/java/org/openhab/core/library/CoreItemFactory.java
This PR adds the support of items in the YAML configuration file.
It also includes the support of items metadata and items channel links.
Related to #3666
=> YAML configuration: add support for items/metadata/channel links

bundles/org.openhab.core.model.yaml/src/main/java/org/openhab/core/model/yaml/internal/items/YamlItemProvider.java
Required after the merge of PR #4807 and PR #4776
=> YAML item proviuder: fix method isVersionSupported

bundles/org.openhab.core.ui/src/main/java/org/openhab/core/ui/internal/chart/defaultchartprovider/DefaultChartProvider.java
* Avoid overlapping of labels
Fixes #4685, which is caused by the recent upgrade of XChart library.
This might need some more iterations for special cases.
In my tests is worked fine on different resolutions and DPI settings.
=> Tweak x-axis labels of charts

bundles/org.openhab.core.model.yaml/src/main/java/org/openhab/core/model/yaml/internal/things/YamlThingProvider.java
While things can now be loaded even when the binding is not yet available, channel types for user defined channels could be not yet in the registry when these channels are first created. So when the binding is finally available, the thing is updated and user defined channels are now created again to retrieve properties from channel types.
This fix avoids warnings at startup regarding missing channel types.
=> YAML config: fix user defined channels creation when binding loads late

bundles/org.openhab.core.config.discovery.upnp/src/main/java/org/openhab/core/config/discovery/upnp/UpnpDiscoveryParticipant.java, bundles/org.openhab.core.config.discovery.upnp/src/main/java/org/openhab/core/config/discovery/upnp/internal/UpnpDiscoveryService.java
=> UPNP don't notify embedded child devices by default

tools/archetype/binding/src/main/resources/archetype-resources/src/main/java/internal/__bindingIdCamelCase__BindingConstants.java, tools/archetype/binding/src/main/resources/archetype-resources/src/main/java/internal/__bindingIdCamelCase__Configuration.java, tools/archetype/binding/src/main/resources/archetype-resources/src/main/java/internal/__bindingIdCamelCase__Handler.java, tools/archetype/binding/src/main/resources/archetype-resources/src/main/java/internal/__bindingIdCamelCase__HandlerFactory.java
Fixes the following messages when a new binding created with the skeleton script is compiled for the first time:
/** does not match until you make the files start with /*
[INFO] --- sat:0.17.0:report (sat-all) @ org.openhab.binding.mamotion ---
[INFO] Individual report appended to summary report.
[ERROR] Code Analysis Tool has found:
4 error(s)!
1 warning(s)
4 info(s)
[WARNING] .binding.mamotion\README.md:[78]
The line after code formatting section must be empty.
[ERROR] org.openhab.binding.mamotion.internal.MamotionBindingConstants.java:[1]
Header line doesn't match pattern ^/\*$
[ERROR] org.openhab.binding.mamotion.internal.MamotionConfiguration.java:[1]
Header line doesn't match pattern ^/\*$
[ERROR] org.openhab.binding.mamotion.internal.MamotionHandler.java:[1]
Header line doesn't …
=> [Skeleton]Fix copyright message format error in skeleton

tools/archetype/binding/src/main/resources/archetype-resources/README.md
Add an extra line so new bindings do not create as many errors when you compile for the first time with a fresh created binding to help new devs get started quicker.
[ERROR] Code Analysis Tool has found:
4 error(s)!
1 warning(s)
4 info(s)
[WARNING] .binding.mamotion\README.md:[78]
The line after code formatting section must be empty.
=> [Skeleton script] FIX scripts create a README.md with a missing new line that causes compile errors.

bundles/org.openhab.core.automation.module.script.rulesupport/src/main/java/org/openhab/core/automation/module/script/rulesupport/shared/ScriptedItemProvider.java, bundles/org.openhab.core.model.item/src/org/openhab/core/model/item/internal/GenericItemProvider.java, itests/org.openhab.core.model.item.tests/src/main/java/org/openhab/core/model/item/internal/GenericItemProviderTest.java
Fixes itest after #4513.
I do not understand why the new ScriptedItemProvider is returned when retrieving the ItemProvider service, as this did not happen with the ManagedItemProvider and the YamlItemProvider. Anyway, this change fixes the problem by explicitly retrieving the GenericItemProvider.
=> Fix itests after #4513

bom/compile/pom.xml, bom/runtime/pom.xml, features/karaf/openhab-tp/src/main/feature/feature.xml, itests/org.openhab.core.automation.integration.tests/itest.bndrun, itests/org.openhab.core.automation.module.core.tests/itest.bndrun, itests/org.openhab.core.automation.module.script.tests/itest.bndrun, itests/org.openhab.core.automation.module.timer.tests/itest.bndrun, itests/org.openhab.core.automation.tests/itest.bndrun, itests/org.openhab.core.config.discovery.usbserial.linuxsysfs.tests/itest.bndrun, itests/org.openhab.core.ephemeris.tests/itest.bndrun, itests/org.openhab.core.model.item.tests/itest.bndrun, itests/org.openhab.core.model.rule.tests/itest.bndrun, itests/org.openhab.core.model.script.tests/itest.bndrun, itests/org.openhab.core.model.thing.tests/itest.bndrun
Upgrades Jollyday from 1.5.0 to 1.5.4.
https://github.com/focus-shift/jollyday/releases
=> Upgrade Jollyday to 1.5.4

bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/internal/item/ItemResource.java, bundles/org.openhab.core.semantics/src/main/java/org/openhab/core/semantics/ItemSemanticsProblem.java, bundles/org.openhab.core.semantics/src/main/java/org/openhab/core/semantics/SemanticsService.java, bundles/org.openhab.core.semantics/src/main/java/org/openhab/core/semantics/internal/SemanticsServiceImpl.java
This is building on the excellent work from @jimtng in https://github.com/openhab/openhab-core/pull/4613
This PR refactors the logging to also make the warning messages available through the REST API in a new `/items/semantics/health` endpoint.
The UI part is in https://github.com/openhab/openhab-webui/pull/3202
=> Semantics health REST endpoint

bundles/org.openhab.core.model.yaml/src/main/java/org/openhab/core/model/yaml/internal/YamlModelRepositoryImpl.java
This takes advantage of #4796 to restrict the folders being watched.
=> Yaml Model: restrict the watched folders to `things`, `items`, `tags`, and `yaml`; support both '.yaml' and '.yml' extensions

bom/openhab-core/pom.xml, bundles/org.openhab.core.automation.module.script.providersupport/.classpath, bundles/org.openhab.core.automation.module.script.providersupport/.project, bundles/org.openhab.core.automation.module.script.providersupport/NOTICE, bundles/org.openhab.core.automation.module.script.providersupport/pom.xml, bundles/org.openhab.core.automation.module.script.providersupport/src/main/java/org/openhab/core/automation/module/script/providersupport/internal/ProviderRegistry.java, bundles/org.openhab.core.automation.module.script.providersupport/src/main/java/org/openhab/core/automation/module/script/providersupport/internal/ProviderRegistryDelegate.java, bundles/org.openhab.core.automation.module.script.providersupport/src/main/java/org/openhab/core/automation/module/script/providersupport/internal/ProviderScriptExtension.java, bundles/org.openhab.core.automation.module.script.providersupport/src/main/java/org/openhab/core/automation/module/script/providersupport/shared/ProviderItemChannelLinkRegistry.java, bundles/org.openhab.core.automation.module.script.providersupport/src/main/java/org/openhab/core/automation/module/script/providersupport/shared/ProviderItemRegistryDelegate.java, bundles/org.openhab.core.automation.module.script.providersupport/src/main/java/org/openhab/core/automation/module/script/providersupport/shared/ProviderMetadataRegistryDelegate.java, bundles/org.openhab.core.automation.module.script.providersupport/src/main/java/org/openhab/core/automation/module/script/providersupport/shared/ProviderThingRegistryDelegate.java, bundles/org.openhab.core.automation.module.script.providersupport/src/main/java/org/openhab/core/automation/module/script/providersupport/shared/ScriptedItemChannelLinkProvider.java, bundles/org.openhab.core.automation.module.script.providersupport/src/main/java/org/openhab/core/automation/module/script/providersupport/shared/ScriptedItemProvider.java, bundles/org.openhab.core.automation.module.script.providersupport/src/main/java/org/openhab/core/automation/module/script/providersupport/shared/ScriptedMetadataProvider.java, bundles/org.openhab.core.automation.module.script.providersupport/src/main/java/org/openhab/core/automation/module/script/providersupport/shared/ScriptedThingProvider.java, bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/internal/item/ItemResource.java, bundles/pom.xml, features/karaf/openhab-core/src/main/feature/feature.xml
Follow-up for #4513.
This moves the newly added provider script extension to a new package and etxends it with support for providing item metadata & ItemChannelLinks.
=> [automation] Extend provider script extension for metadata & ItemChannelLinks

bundles/org.openhab.core/src/main/java/org/openhab/core/internal/items/ExpireManager.java, bundles/org.openhab.core/src/main/java/org/openhab/core/util/DurationUtils.java, bundles/org.openhab.core/src/test/java/org/openhab/core/util/DurationUtilsTest.java
so it can be used elsewhere
This was prompted by the need to standardize Duration parsing across openHAB, including addons, such as in https://github.com/openhab/openhab-addons/pull/18301
=> Move expire's Duration parser to a separate utility class and support `ms` for milliseconds

bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/firmware/types/SemverVersion.java
This new type allows bindings to handle semantic versions internally using a proper type instead of String, and to compare versions. This is especially useful for bindings which need to handle multiple API versions and need to check against some version boundaries.
=> [thing] Add SemverVersion type to be used by bindings

bundles/org.openhab.core.config.discovery/src/main/java/org/openhab/core/config/discovery/AbstractDiscoveryService.java, bundles/org.openhab.core.config.discovery/src/main/java/org/openhab/core/config/discovery/DiscoveryListener.java, bundles/org.openhab.core.config.discovery/src/main/java/org/openhab/core/config/discovery/DiscoveryResult.java, bundles/org.openhab.core.config.discovery/src/main/java/org/openhab/core/config/discovery/internal/DiscoveryResultImpl.java, bundles/org.openhab.core.config.discovery/src/main/java/org/openhab/core/config/discovery/internal/DiscoveryServiceRegistryImpl.java, bundles/org.openhab.core.config.discovery/src/main/java/org/openhab/core/config/discovery/internal/PersistentInbox.java, bundles/org.openhab.core.config.discovery/src/main/java/org/openhab/core/config/discovery/internal/console/InboxConsoleCommandExtension.java, bundles/org.openhab.core.config.discovery/src/test/java/org/openhab/core/config/discovery/AbstractDiscoveryServiceTest.java, itests/org.openhab.core.config.discovery.tests/src/main/java/org/openhab/core/config/discovery/DiscoveryServiceRegistryOSGiTest.java, itests/org.openhab.core.config.discovery.tests/src/main/java/org/openhab/core/config/discovery/internal/InboxOSGiTest.java
Continuation of #4026, this time finishing the job by changing the API.
Methods related to discovery now use `Instant` rather than `long` for timestamps. This provides type safety, clarity and integration with the modern `java.time` API.
I have kept all existing methods, but immediately deprecated them. The `Instant` overload for `removeOlderResults` in the `DiscoveryListener` interface has a default implementation delegating to the `long` overload, so it is non-breaking now since an implementation is not required.
The proposed next phases:
1. Refactor add-ons to use the new methods. Prepared here: openhab/openhab-addons#18838.
2. Minor release: Invert the delegation: Make the `long` method a default method delegating to `Instant`.
Make the `Instant` method abstract — implementors must …
=> Refactor timestamps to `Instant` in discovery methods

bundles/org.openhab.core.config.discovery/src/main/java/org/openhab/core/config/discovery/AbstractDiscoveryService.java, bundles/org.openhab.core.config.discovery/src/main/java/org/openhab/core/config/discovery/DiscoveryListener.java, bundles/org.openhab.core.config.discovery/src/main/java/org/openhab/core/config/discovery/DiscoveryResult.java, bundles/org.openhab.core.config.discovery/src/main/java/org/openhab/core/config/discovery/internal/DiscoveryResultImpl.java, bundles/org.openhab.core.config.discovery/src/main/java/org/openhab/core/config/discovery/internal/DiscoveryServiceRegistryImpl.java, bundles/org.openhab.core.config.discovery/src/main/java/org/openhab/core/config/discovery/internal/PersistentInbox.java, bundles/org.openhab.core.config.discovery/src/test/java/org/openhab/core/config/discovery/AbstractDiscoveryServiceTest.java
Continuation of #4866:
- Remove unused deprecated methods.
- Interface `DiscoveryListener`: Switch `long` and `Instant` overloads, so that `Instant` is now abstract and `long` has a default implementation delegating to the other. This makes it possible to remove the old method in implementations while keeping the new one (previously it was the other way around).
Neither of these changes are breaking at this moment in time, since openhab/openhab-addons#18838 is already merged. All `DiscoveryListener` implementations currently implements both `removeOlderResults` methods.
Final cleanup steps after this:
- Remove all `removeOlderResults(long)` implementations in addons. They are no longer needed after this PR, since the interface has a default implementation. Prepared in …
=> Remove deprecated discovery methods

bundles/org.openhab.core.config.discovery/src/main/java/org/openhab/core/config/discovery/DiscoveryListener.java
This finally removes the `removeOlderResults(long)` overload from the `DiscoveryListener` interface. See previous steps:
- openhab/openhab-addons#18845
- openhab/openhab-addons#18890
- #4866
- openhab/openhab-addons#18838
- #4883
- openhab/openhab-addons#18895
=> Remove deprecated discovery method from interface

bundles/org.openhab.core.automation.module.script/src/main/java/org/openhab/core/automation/module/script/profile/ScriptProfile.java
Log before:
```
14:41:27.373 [ERROR] [n.module.script.profile.ScriptProfile] - Failed to process script 'asdf.rb': Could not get script for UID 'asdf.rb'.
```
After:
```
14:41:27.373 [ERROR] [n.module.script.profile.ScriptProfile] - Failed to process script 'asdf.rb' in link 'Bed_Room_Light_Power -> mqtt:topic:bedroom-light:switch2': Could not get script for UID 'asdf.rb'.
```
=> Log the link in the ScriptProfile execution error message

bundles/org.openhab.core/src/main/java/org/openhab/core/common/registry/AbstractRegistry.java
Fix openhab/openhab-addons#18945
Regression from #4880
For Metadata, it was reported on the community forum, it occured when an item is linked to several channels.
=> Registry: Avoid warn log when adding ActionType/Metadata several times

bundles/org.openhab.core.io.rest/src/main/java/org/openhab/core/io/rest/internal/filter/CorsFilter.java
Currently, if CORS is enabled by configuration, the startup log is cluttered with such log messages:
```
09:46:24.421 [INFO ] [e.io.rest.internal.filter.CorsFilter] - enabled CORS for REST API.
09:46:24.421 [INFO ] [e.io.rest.internal.filter.CorsFilter] - enabled CORS for REST API.
09:46:24.425 [INFO ] [e.io.rest.internal.filter.CorsFilter] - enabled CORS for REST API.
09:46:24.439 [INFO ] [e.io.rest.internal.filter.CorsFilter] - enabled CORS for REST API.
09:46:24.444 [INFO ] [e.io.rest.internal.filter.CorsFilter] - enabled CORS for REST API.
09:46:24.456 [INFO ] [e.io.rest.internal.filter.CorsFilter] - enabled CORS for REST API.
09:46:24.462 [INFO ] [e.io.rest.internal.filter.CorsFilter] - enabled CORS for REST API.
09:46:24.466 [INFO ] [e.io.rest.internal.filter.CorsFilter] - enabled …
```
=> Restrict CORS logging to a single time

bundles/org.openhab.core.model.core/src/main/java/org/openhab/core/model/core/internal/folder/FolderObserver.java
This is a bugfix that has been separated out from #4633 since it's clear that it won't be a part of 5.0.
The bug is that on some file systems, NTFS/FAT/FAT32 in particular, file system access is needed to determine if a file or folder is hidden, since this is stored as a file attribute. On *nix based systems, "hidden" is determined simply by if the file/folder name starts with '.', so no file system access is required to make this determination.
As of today, `FolderObserver` evaluates the "hidden status" of the file/folder (for excluding hidden files from processing) before looking at what kind of event it is. This will lead to a `FileNotFoundException` for `DELETE` events since the file/holder has already been deleted, and thus its attributes can't be read. The exception prevents the …
=> Prevent file system access for WatchService DELETE events in FolderObserver

bundles/org.openhab.core.model.yaml/src/main/java/org/openhab/core/model/yaml/internal/YamlModelRepositoryImpl.java
Resolve an issue reported in https://community.openhab.org/t/openhab-5-0-milestone-discussion/162686/277
=> Yaml Model Repository: skip non-existent paths during the initial scan instead of logging a warning

bundles/org.openhab.core/src/main/java/org/openhab/core/util/DurationUtils.java, bundles/org.openhab.core/src/test/java/org/openhab/core/util/DurationUtilsTest.java
Extend the expire/duration parser syntax to allow optional spaces between the number and its unit and accept alternative units:
- d|day|days
- h|hr|hrs|hour|hours
- m|min|mins|minute|minutes
- s|sec|secs|second|seconds
- ms|millisecond|milliseconds
=> Allow extended unit names for days, hours, minutes, seconds, milliseconds and allow spaces before the unit in expire duration parser

bundles/org.openhab.core.io.rest.sitemap/src/main/java/org/openhab/core/io/rest/sitemap/internal/SitemapResource.java, bundles/org.openhab.core.io.rest.sitemap/src/main/java/org/openhab/core/io/rest/sitemap/internal/WidgetDTO.java
This was missed in #4610 / commit a9a289e3f242c30daf2239d6377b805d6450478f
=> Map chart interpolation parameter into sitemap JSON response

.github/scripts/maven-build, .github/workflows/ci-build.yml, .mvn/wrapper/maven-wrapper.properties, mvnw, mvnw.cmd
Similar to https://github.com/openhab/openhab-webui/pull/3251
=> Use Maven wrapper with GHA

bom/runtime/pom.xml, features/karaf/openhab-tp/src/main/feature/feature.xml
It is required by the Jinja transformation.
Because it uses the same version of OHC and is missing in the feature, it needs to be manually uploaded each time Jackson is upgraded.
Fixes #4399
---
Jinjava [depends on it](https://github.com/HubSpot/jinjava/blob/b97bc5c095aa263604c32571aa7a2b6152f470c8/src/main/java/com/hubspot/jinjava/JinjavaConfig.java#L162) and throws a NoClassDefFoundError without it:
```
java.lang.NoClassDefFoundError: com/fasterxml/jackson/datatype/jdk8/Jdk8Module
at com.hubspot.jinjava.Jinjava.<init>(Jinjava.java:76)
at org.openhab.transform.jinja.internal.JinjaTransformationService.<init>(JinjaTransformationService.java:49)
at org.openhab.transform.jinja.internal.JinjaTransformationServiceTest.init(JinjaTransformationServiceTest.java:30)
at …
```
=> Add jackson-datatype-jdk8 bundle to Jackson feature

bundles/org.openhab.core.automation.module.script/src/main/java/org/openhab/core/automation/module/script/internal/factory/ScriptModuleHandlerFactory.java, bundles/org.openhab.core.automation.module.script/src/main/java/org/openhab/core/automation/module/script/internal/handler/AbstractScriptModuleHandler.java, bundles/org.openhab.core.automation.module.script/src/main/java/org/openhab/core/automation/module/script/internal/handler/ScriptActionHandler.java, bundles/org.openhab.core.automation.module.script/src/main/java/org/openhab/core/automation/module/script/internal/handler/ScriptConditionHandler.java
Fixes https://github.com/openhab/openhab-addons/issues/19091.
When a script's dependency changes, it should recompile the compiled script similarly to resetting the engine for uncompiled scripts. Fixing this behaviour fixes an issue where compiled scripts stopped working after a dependency changed.
This also simplifies the code a bit.
=> AbstractScriptModuleHandler: Recompile scripts on dependency change

bundles/org.openhab.core.automation.module.script/src/main/java/org/openhab/core/automation/module/script/internal/defaultscope/DefaultScriptScopeProvider.java
Added `org.openhab.core.thing.link.ItemChannelLinkRegistry` to `org.openhab.core.automation.module.script.internal.defaultscope.DefaultScriptScopeProvider` so it can be used from scripts;
=> Add ItemChannelLinkRegistry to DefaultScriptScopeProvider

bundles/org.openhab.core.model.script/src/org/openhab/core/model/script/actions/HTTP.java
This adds new functions for downloading images to image Items. This is useful for exposing images to push notifications, updating album art, showing camera snapshots in the Main UI, etc...
I went back and forth if this was a new "Image" action space, or part of the HTTP actions, in the end i think it belongs as additional HTTP actions (since it also mostly wraps HTTPUtils.java)
=> [rules actions] Add new HTTP actions for images

bundles/org.openhab.core.automation.module.script/src/main/java/org/openhab/core/automation/module/script/internal/defaultscope/DefaultScriptScopeProvider.java
Reverts openhab/openhab-core#4937
See https://github.com/openhab/openhab-addons/issues/19197
=> Revert "Add ItemChannelLinkRegistry to DefaultScriptScopeProvider"

bundles/org.openhab.core.automation.module.script/src/main/java/org/openhab/core/automation/module/script/internal/handler/AbstractScriptModuleHandler.java
I've created this PR at the request of @florian-h05 in this comment: https://github.com/openhab/openhab-core/pull/4922#discussion_r2294753784
It also addresses the nullness annotations that are discussed in the same PR.
This might fix what's causing the behavior described in #4965.
=> Script compilation fix

bundles/org.openhab.core.model.yaml/src/main/java/org/openhab/core/model/yaml/internal/items/YamlGroupDTO.java, bundles/org.openhab.core.model.yaml/src/main/java/org/openhab/core/model/yaml/internal/items/YamlItemDTO.java, bundles/org.openhab.core.model.yaml/src/main/java/org/openhab/core/model/yaml/internal/items/YamlItemProvider.java, bundles/org.openhab.core.model.yaml/src/main/java/org/openhab/core/model/yaml/internal/things/YamlThingDTO.java, bundles/org.openhab.core.model.yaml/src/main/java/org/openhab/core/model/yaml/internal/util/YamlElementUtils.java, bundles/org.openhab.core.model.yaml/src/test/java/org/openhab/core/model/yaml/internal/items/YamlGroupDTOTest.java, bundles/org.openhab.core.model.yaml/src/test/java/org/openhab/core/model/yaml/internal/items/YamlItemDTOTest.java, bundles/org.openhab.core.model.yaml/src/test/java/org/openhab/core/model/yaml/internal/items/YamlMetadataDTOTest.java, bundles/org.openhab.core.model.yaml/src/test/java/org/openhab/core/model/yaml/internal/things/YamlChannelDTOTest.java, bundles/org.openhab.core.model.yaml/src/test/java/org/openhab/core/model/yaml/internal/things/YamlThingDTOTest.java
Reduce potential collisions in hashCode()
Make identical a null list/set and an empty list/set
Test hashCode in addition to equals in unit tests.
Add new tests for YamlItemDTO (equals/hashCode)
Related to #4936
=> YAML config enhance hashCode() and add new unit tests

bom/compile/pom.xml, bom/runtime/pom.xml, features/karaf/openhab-tp/src/main/feature/feature.xml, itests/org.openhab.core.config.discovery.mdns.tests/itest.bndrun
Upgrades jmdns from 3.5.12 to 3.6.1.
Changelogs:
https://github.com/jmdns/jmdns/releases/tag/3.6.0
https://github.com/jmdns/jmdns/releases/tag/3.6.1
=> Upgrade jmdns to 3.6.1

bom/compile/pom.xml
We had different versions in compile bom and runtime.
Sync to 1.2.0.
Refs https://github.com/openhab/openhab-core/issues/4949
=> Use felix.http.servlet-api 1.2.0

bundles/org.openhab.core.config.discovery.usbserial.windowsregistry/src/main/java/org/openhab/core/config/discovery/usbserial/windowsregistry/internal/WindowsUsbSerialDiscovery.java
=> Fix USB discovery on Windows in case there is no USB port

bom/compile/pom.xml, bom/runtime/pom.xml, features/karaf/openhab-tp/src/main/feature/feature.xml, itests/org.openhab.core.auth.oauth2client.tests/itest.bndrun, itests/org.openhab.core.automation.integration.tests/itest.bndrun, itests/org.openhab.core.automation.module.core.tests/itest.bndrun, itests/org.openhab.core.automation.module.script.tests/itest.bndrun, itests/org.openhab.core.automation.module.timer.tests/itest.bndrun, itests/org.openhab.core.automation.tests/itest.bndrun, itests/org.openhab.core.config.core.tests/itest.bndrun, itests/org.openhab.core.config.discovery.mdns.tests/itest.bndrun, itests/org.openhab.core.config.discovery.tests/itest.bndrun, itests/org.openhab.core.config.discovery.usbserial.linuxsysfs.tests/itest.bndrun, itests/org.openhab.core.config.discovery.usbserial.tests/itest.bndrun, itests/org.openhab.core.config.dispatch.tests/itest.bndrun, itests/org.openhab.core.ephemeris.tests/itest.bndrun, itests/org.openhab.core.io.net.tests/itest.bndrun, itests/org.openhab.core.io.rest.core.tests/itest.bndrun, itests/org.openhab.core.model.item.tests/itest.bndrun, itests/org.openhab.core.model.rule.tests/itest.bndrun, itests/org.openhab.core.model.script.tests/itest.bndrun, itests/org.openhab.core.model.thing.tests/itest.bndrun, itests/org.openhab.core.storage.json.tests/itest.bndrun, itests/org.openhab.core.tests/itest.bndrun
* Upgrade hivemq-mqtt-client from 1.3.7 to 1.3.9,
includes upgrade of transitive dependency Dagger from 2.27 to 2.40 (still not current version)
changelog:
https://github.com/hivemq/hivemq-mqtt-client/releases/tag/v1.3.8
https://github.com/hivemq/hivemq-mqtt-client/releases/tag/v1.3.9
* Upgrade netty from 4.1.122 to 4.1.126,
changelog:
https://netty.io/news/2025/07/16/4-1-123-Final.html
https://netty.io/news/2025/08/13/4-1-124-Final.html
https://netty.io/news/2025/09/03/4-1-126-Final.html
depends on:
* openhab/openhab-osgiify#76
* resolve itests
(DO NOT SQUASH if you want to keep this separate, it is not related to the changes in this PR)
=> Upgrade hivemq-mqtt-client to 1.3.9

bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/RuleEngineImpl.java
Closes #4965.
As the rule engine needs to be started for the system to reach start level 40 and automation add-ons are not loaded before start level 80, skip pre-compilation if rule engine not yet started as automation add-ons are not available yet.
=> [automation] Skip pre-compilation if rule engine not yet started

bundles/org.openhab.core.config.core/src/main/java/org/openhab/core/config/core/internal/net/NetworkConfigOptionProvider.java
After a lot of troubleshooting of the network binding, I've found that one of the reasons for its extreme slowness is right here in core, and stems from #3981.
This relates to https://github.com/openhab/openhab-addons/issues/17956#issuecomment-3251334285
In short, when `network-interface` context was added, it was implemented by enumerating all the network interfaces on the host. As a part of trying to find a suitable label for a network interface label, `InetAddress.getHostName()` was used. This method tries to reverse lookup a hostname from an IP address, which can mean all kind of network activity. This is done for each IP address that is attached to a network interface, which makes it quite slow. On my computer, doing this enumeration once takes 4.27 seconds, but the actual time it …
=> Fix network interface configuration option enumeration

bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/internal/CommunicationManager.java, bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/profiles/StateProfile.java, itests/org.openhab.core.thing.tests/src/main/java/org/openhab/core/thing/internal/CommunicationManagerOSGiTest.java
So that a user can define a profile that takes different actions depending on what's generating the command.
=> Pass event source to profiles

bundles/org.openhab.core.model.rule/src/org/openhab/core/model/rule/Rules.xtext
Problem reported in https://community.openhab.org/t/assistance-with-rule-dsl-datetime-trigger-offset/166157?u=jimtng
- Offset doesn't accept a negative value
- Offset doesn't accept an equal sign
This PR makes the equal sign optional, so both these syntaxes work:
```
Time is X offset -60
Time is X offset=-60
```
Should be backported to 5.0 and possibly 4.3.x
=> RulesDSL: Fix DateTimeItem trigger's offset

bundles/org.openhab.core.persistence/src/main/java/org/openhab/core/persistence/extensions/PersistenceExtensions.java
This replicates the part of https://github.com/openhab/openhab-core/pull/5018 that also affects OH 4.3.
It does not include any of the tests.
=> Persistence Extensions: fix potential infinite loop

bundles/org.openhab.core.addon.marketplace/src/main/java/org/openhab/core/addon/marketplace/internal/community/CommunityBlockLibaryAddonHandler.java, bundles/org.openhab.core.addon.marketplace/src/main/java/org/openhab/core/addon/marketplace/internal/community/CommunityBundleAddonHandler.java, bundles/org.openhab.core.addon.marketplace/src/main/java/org/openhab/core/addon/marketplace/internal/community/CommunityMarketplaceAddonService.java, bundles/org.openhab.core.addon.marketplace/src/main/java/org/openhab/core/addon/marketplace/internal/community/CommunityRuleTemplateAddonHandler.java, bundles/org.openhab.core.addon.marketplace/src/main/java/org/openhab/core/addon/marketplace/internal/community/CommunityTransformationAddonHandler.java, bundles/org.openhab.core.addon.marketplace/src/main/java/org/openhab/core/addon/marketplace/internal/community/CommunityUIWidgetAddonHandler.java
This is a bugfix of an issue reported in the [5.0 Milestone discussion thread](https://community.openhab.org/t/openhab-5-0-milestone-discussion/162686/365).
Handling of the lack of an installation source have also been unified among the different community marketplace handlers.
In addition, I've included an old fix I've had lying around that removes the forum compatibility range from the title of installed add-ons.
=> Marketplace fixes

bundles/org.openhab.core.persistence/src/test/java/org/openhab/core/persistence/extensions/PersistenceExtensionsTest.java, bundles/org.openhab.core.persistence/src/test/java/org/openhab/core/persistence/extensions/TestCachedValuesPersistenceService.java, bundles/org.openhab.core.persistence/src/test/java/org/openhab/core/persistence/extensions/TestPersistenceService.java
See discussion: https://github.com/openhab/openhab-core/pull/4818#issuecomment-3188440962
This reduces the impact of `now()` on the persistence extensions test reliability. There only was a major impact for average on OnOff types. This impact has been removed by not testing the `AverageSince` and `AverageUntil` methods, only the `AverageBetween` method.
@jimtng @Nadahar FYI
EDIT: I am running the tests with a sleep of 1 minute on every query to the persistence service. If this succeeds, I consider the persistence extension tests to be independent from the current time for all practical purposes.
=> Fix persistence extensions test reliability

bundles/org.openhab.core/src/main/java/org/openhab/core/internal/common/WrappedScheduledExecutorService.java
In #4948 we added logging to the scheduler to identify tasks that take too long. The existing code uses a `try .. finally` structure so if a task is fully blocked the `finally` never gets called and nothing gets logged. This PR extends the functionality to also log fully blocked tasks.
Note to reviewer: A possible solution could be to employ an independent monitor thread to check the state of the tasks. But that would impose some overhead. So instead we check the state of the tasks whenever a) a new task is scheduled, and b) when such a task is run (or called). Reason for using a) and b) is that some tasks may be created via (say) `scheduleWithFixedDelay()` so a) is done once, and b) is done repeatedly thereafter, thus giving more opportunities to log blocked tasks.
Signed-off-by: Andrew …
=> Apply blocked task logging to scheduled executor service

bundles/org.openhab.core.io.transport.mqtt/src/main/java/org/openhab/core/io/transport/mqtt/MqttBrokerConnection.java, bundles/org.openhab.core.io.transport.mqtt/src/main/java/org/openhab/core/io/transport/mqtt/MqttBrokerConnectionConfig.java, bundles/org.openhab.core.io.transport.mqtt/src/main/java/org/openhab/core/io/transport/mqtt/internal/client/Mqtt3AsyncClientWrapper.java, bundles/org.openhab.core.io.transport.mqtt/src/main/java/org/openhab/core/io/transport/mqtt/internal/client/Mqtt5AsyncClientWrapper.java, bundles/org.openhab.core.io.transport.mqtt/src/main/java/org/openhab/core/io/transport/mqtt/internal/client/MqttAsyncClientWrapper.java, bundles/org.openhab.core.io.transport.mqtt/src/test/java/org/openhab/core/io/transport/mqtt/MqttBrokerConnectionEx.java
Some MQTT broker connections should be configured with cleanSession (MQTTv3) or cleanStart (MQTTv5) set to false. The default is true.
This was not possible so far as the MQTT transport does not expose this as an option, and therefore always starts with a clean session on every reconnect.
This PR adds support for setting it.
This is relevant for https://github.com/openhab/openhab-addons/pull/19322. That addon PR removes the code directly using hivemq and replaces it by the transport. And this parameter is not accessible. While I did not see a major impact in my testing so far, it would most likely reduce the risk of being banned from the cloud service if it is possible to set it right.
=> MQTT transport: add cleanSession/cleanStart parameter

bundles/org.openhab.core/src/main/java/org/openhab/core/items/GenericItem.java, bundles/org.openhab.core/src/main/java/org/openhab/core/items/GroupItem.java, bundles/org.openhab.core/src/main/java/org/openhab/core/library/items/ColorItem.java, bundles/org.openhab.core/src/main/java/org/openhab/core/library/items/DateTimeItem.java, bundles/org.openhab.core/src/main/java/org/openhab/core/library/items/DimmerItem.java, bundles/org.openhab.core/src/main/java/org/openhab/core/library/items/LocationItem.java, bundles/org.openhab.core/src/main/java/org/openhab/core/library/items/NumberItem.java, bundles/org.openhab.core/src/main/java/org/openhab/core/library/items/PlayerItem.java, bundles/org.openhab.core/src/main/java/org/openhab/core/library/items/RollershutterItem.java, bundles/org.openhab.core/src/main/java/org/openhab/core/library/items/StringItem.java, bundles/org.openhab.core/src/main/java/org/openhab/core/library/items/SwitchItem.java
Providing a source with a command can allow rules (or profiles) to react differently depending on what's sending the command. For example, if it's from a user interaction in BasicUI or MainUI, or from HomeKit, or if it's an automated action such as another rule. These overloads are helpful for those sources to easily declare they are who is sending the command.
=> Add item overloads for providing source
